FROM nginx:1.10.2-alpine
MAINTAINER Thoralf Liersch <thoralf.liersch@sysreport.de>

COPY default.conf /etc/nginx/conf.d/default.conf
#COPY "docker-entrypoint.sh" "/"
#ENTRYPOINT ["/docker-entrypoint.sh"]
