MetaArgs: null
Stages:
- BaseName: openjdk:8-jdk-alpine
  Commands:
  - Name: volume
    Volumes:
    - /tmp
  - Key: JAR_FILE
    Name: arg
    Value: null
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ${JAR_FILE}
    - load-balancer.jar
  - Name: expose
    Ports:
    - "8762"
  - CmdLine:
    - java
    - -Djava.security.egd=file:/dev/./urandom
    - -jar
    - /load-balancer.jar
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-jdk-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jdk-alpine
