MetaArgs: null
Stages:
- BaseName: ubuntucore/jenkins-swarm-slave-ubuntu:vivid
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - ln -s /bin/true /usr/local/bin/udevadm
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install --no-install-recommends -qy   python-software-properties   software-properties-common
      && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:snappy-dev/tools-proposed
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://archive.ubuntu.com/ubuntu/ vivid-backports main restricted"
      >> /etc/apt/sources.list &&   apt-get update && apt-get install -qy --no-install-recommends   autopkgtest/vivid-backports   build-essential   ca-certificates   python-junitxml   snappy-cloud-image   snappy-tests-job   squashfs-tools   openssh-client   sudo   subunit   ubuntu-core-security-utils
      &&   rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "jenkins-slave ALL=NOPASSWD: ALL" >> /etc/sudoers'
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/jenkins-slave/.ssh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/ssh
    - /home/jenkins-slave/.ssh/config
  - CmdLine:
    - chown -R jenkins-slave:jenkins-slave /home/jenkins-slave/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://people.ubuntu.com/~elopio/snappy/vivid/ubuntu-device-flash &&   chmod
      +x ubuntu-device-flash &&   mv ubuntu-device-flash /usr/bin/ubuntu-device-flash
    Name: run
    PrependShell: true
  From:
    Image: ubuntucore/jenkins-swarm-slave-ubuntu:vivid
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntucore/jenkins-swarm-slave-ubuntu:vivid
