MetaArgs: null
Stages:
- BaseName: evarga/jenkins-slave
  Commands:
  - Maintainer: Alex Sherwin <alex.sherwin@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y install sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser jenkins sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo %sudo        ALL=NOPASSWD: ALL >> /etc/sudoers'
    Name: run
    PrependShell: true
  From:
    Image: evarga/jenkins-slave
  Name: ""
  Platform: ""
  SourceCode: FROM evarga/jenkins-slave
