MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update     && apt-get -qq --no-install-recommends install         libmicrohttpd10         libhwloc-dev         libssl1.0.0     &&
      rm -r /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: XMR_STAK_CPU_VERSION
      Value: 2.5.0
    Name: env
  - CmdLine:
    - set -x     && buildDeps='         ca-certificates         cmake         curl         g++         libmicrohttpd-dev         libssl-dev         make     '     &&
      apt-get -qq update     && apt-get -qq --no-install-recommends install $buildDeps     &&
      rm -rf /var/lib/apt/lists/*         && mkdir -p /usr/local/src/xmr-stak-cpu/build     &&
      cd /usr/local/src/xmr-stak-cpu/     && curl -sL https://github.com/fireice-uk/xmr-stak/archive/$XMR_STAK_CPU_VERSION.tar.gz
      | tar -xz --strip-components=1     && sed -i 's/constexpr double fDevDonationLevel.*/constexpr
      double fDevDonationLevel = 0.0;/' xmrstak/donate-level.hpp     && cd build     &&
      cmake -DOpenCL_ENABLE=OFF -DCUDA_ENABLE=OFF ..     && make install -j$(nproc)     &&
      cp bin/xmr-stak /usr/local/bin/     && apt-get -qq --auto-remove purge $buildDeps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config.txt
    - /config.txt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cpu.txt
    - /cpu.txt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pools.txt
    - /pools.txt
  - CmdLine:
    - xmr-stak
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
