MetaArgs: null
Stages:
- BaseName: ruby:2.6
  Commands:
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* && apt-get update
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /wraith
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libfreetype6 libfontconfig1 nodejs libnss3-dev libgconf-2-4     &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /wraith/.npm-global
    Name: run
    PrependShell: true
  - Env:
    - Key: NPM_CONFIG_PREFIX
      Value: /wraith/.npm-global
    Name: env
  - Env:
    - Key: PATH
      Value: /wraith/.npm-global/bin:$PATH
    Name: env
  - CmdLine:
    - npm install -g phantomjs-prebuilt casperjs --unsafe-perm
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install wraith --no-document --no-suggestions
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
      add -     && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >
      /etc/apt/sources.list.d/google.list     && apt-get update     && apt-get install
      -y google-chrome-stable unzip     && rm -rf /var/lib/apt/lists/*     && sed
      -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g'            "/opt/google/chrome/google-chrome"     &&
      google-chrome --version
    Name: run
    PrependShell: true
  - CmdLine:
    - export CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE)     &&
      curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip
      "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip"     &&
      cd /tmp     && unzip chromedriver_linux64.zip     && rm -rf chromedriver_linux64.zip     &&
      mv chromedriver /usr/local/bin/chromedriver     && chmod +x /usr/local/bin/chromedriver     &&
      chromedriver --version
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://ftp.us.debian.org/debian stretch main contrib non-free" | tee
      -a /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://security.debian.org/ stretch/updates contrib non-free" | tee
      -a /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y ttf-freefont ttf-mscorefonts-installer ttf-bitstream-vera
      ttf-dejavu ttf-liberation
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y imagemagick
    Name: run
    PrependShell: true
  - CmdLine:
    - wraith
    Name: entrypoint
    PrependShell: false
  From:
    Image: ruby:2.6
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.6
