MetaArgs: null
Stages:
- BaseName: olegozimok/php-fpm:5.5-full
  Commands:
  - Maintainer: Oleg Ozimok "ozimok.oleg@gmail.com"
    Name: maintainer
  - CmdLine:
    - curl -L -o /tmp/xdebug.gz https://pecl.php.net/get/xdebug-2.3.3.tgz     && tar
      xfz /tmp/xdebug.gz     && rm -r /tmp/xdebug.gz     && mv xdebug-2.3.3 /usr/src/php/ext/xdebug     &&
      docker-php-ext-install xdebug
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - php.ini
    - /usr/local/etc/php/
  - Name: expose
    Ports:
    - "9001"
  From:
    Image: olegozimok/php-fpm:5.5-full
  Name: ""
  Platform: ""
  SourceCode: FROM olegozimok/php-fpm:5.5-full
