MetaArgs: null
Stages:
- BaseName: microsoft/dotnet:2.1-aspnetcore-runtime
  Commands:
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install w3m p7zip-full
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /start/src
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /start
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - startup.sh
    - ./
  - CmdLine:
    - chmod 777 startup.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /start/src
  - CmdLine:
    - bash
    - /start/startup.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: microsoft/dotnet:2.1-aspnetcore-runtime
  Name: ""
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.1-aspnetcore-runtime
