MetaArgs: null
Stages:
- BaseName: rsippl/centos-jdk
  Commands:
  - Maintainer: Ralf Sippl <ralf.sippl@gmail.com>
    Name: maintainer
  - CmdLine:
    - yum update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y epel-release
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y     unzip     supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -O -k -L http://downloads.sourceforge.net/project/lportal/Liferay%20Portal/7.0.0%20GA1/liferay-portal-tomcat-7.0-ce-ga1-20160331161017956.zip  &&
      unzip liferay-portal-tomcat-7.0-ce-ga1-20160331161017956.zip -d /opt  && rm
      liferay-portal-tomcat-7.0-ce-ga1-20160331161017956.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/liferay-portal-7.0-ce-ga1 /opt/liferay  && ln -s /opt/liferay/tomcat-8.0.32
      /opt/liferay/tomcat
    Name: run
    PrependShell: true
  - CmdLine:
    - echo -e '\nCATALINA_OPTS="$CATALINA_OPTS -Djava.security.egd=file:/dev/./urandom"'
      >> /opt/liferay/tomcat/bin/setenv.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/supervisord.conf
    - /etc/supervisord.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/init.sh
    - /opt/liferay/init.sh
  - Name: volume
    Volumes:
    - /opt/liferay
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /usr/bin/supervisord -n
    Name: cmd
    PrependShell: true
  From:
    Image: rsippl/centos-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM rsippl/centos-jdk
