MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Renfred Harper
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y tar git curl nano wget dialog net-tools build-essential software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python3 python3-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y -qq ruby1.9.1-dev make
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-rdoc --no-ri compass
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-add-repository ppa:chris-lea/node.js
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g browserify && npm install --save-dev babelify resolvify
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/renfredxh/snueue.git snueue
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install3 -U pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -r /snueue/requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: workdir
    Path: /snueue
  - CmdLine:
    - gunicorn app:app -b 0.0.0.0:80 --log-file - --error-logfile - --access-logfile
      -
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
