MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - Labels:
    - Key: vendor
      Value: '"bokazio"'
    - Key: origin
      Value: '"https://github.com/bokazio/docker-ci-deploy"'
    Name: label
  - CmdLine:
    - "apk add --no-cache     dumb-init     bash \tgit \topenssh-client \trsync \truby
      \truby-io-console \tbuild-base \tlibffi-dev \truby-dev \tca-certificates \tpy-yuicompressor
      && \tgem install sass --no-ri --no-rdoc &&   \tapk del build-base libffi-dev
      ruby-dev &&   \trm -rf /var/cache/apk/*"
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
