MetaArgs: null
Stages:
- BaseName: jpetazzo/dind
  Commands:
  - Maintainer: Yasser Nabi "yassersaleemi@gmail.com"
    Name: maintainer
  - Env:
    - Key: JENKINS_HOME
      Value: /jenkins
    Name: env
  - Env:
    - Key: JENKINS_SWARM_CLIENT_VER
      Value: "1.15"
    Name: env
  - Env:
    - Key: JENKINS_JAVA_ARGS
      Value: '''-Djava.awt.headless=true'''
    Name: env
  - Env:
    - Key: TZ
      Value: Europe/London
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Name: expose
    Ports:
    - "22"
    - "2812"
  - CmdLine:
    - sed 's/main$/main universe/' -i /etc/apt/sources.list &&         apt-get update
      &&         apt-get -y install             openssh-server             monit             curl             openjdk-7-jre-headless             git             subversion
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./monit.d/
    - /etc/monit/conf.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./jenkins.sudoers
    - /etc/sudoers.d/jenkins
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./jenkins_init_wrapper.sh
    - /jenkins_init_wrapper.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./start.sh
    - /start.sh
  - CmdLine:
    - mkdir -p ${JENKINS_HOME} && curl -s -L -o $JENKINS_HOME/swarm-client.jar       http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/${JENKINS_SWARM_CLIENT_VER}/swarm-client-${JENKINS_SWARM_CLIENT_VER}-jar-with-dependencies.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - /start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: jpetazzo/dind
  Name: ""
  Platform: ""
  SourceCode: FROM jpetazzo/dind
