MetaArgs: null
Stages:
- BaseName: python:3.7-slim
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app
  - CmdLine:
    - pip install --no-cache-dir -r requirements.txt
    Name: run
    PrependShell: true
  From:
    Image: python:3.7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-slim
