MetaArgs: null
Stages:
- BaseName: ubuntu:12.04
  Commands:
  - Maintainer: John Yi "john.yi@rackspace.com"
    Name: maintainer
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install curl build-essential libxml2-dev libxslt-dev git zlib1g-dev
      libssl-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install python openssh-server python-dev software-properties-common
      net-tools vim
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.6.tar.gz
      | tar xvzf -;cd setuptools-1.1.6;python setup.py install
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install python-novaclient python-swiftclient python-heatclient python-cinderclient
      python-keystoneclient python-troveclient python-neutronclient
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pyrax ansible supernova ipython
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/rackerlabs/python-cloudlb.git $HOME/cloudlb;cd
      $HOME/cloudlb;python setup.py install;cd $HOME
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/jyidiego/clb.git $HOME/clb;cd $HOME/clb;python
      setup.py install;cd $HOME
    Name: run
    PrependShell: true
  - CmdLine:
    - 'chmod -R 544 /usr/local/lib/python2.7/dist-packages/python_dateutil-*-py2.7.egg/EGG-INFO/*
      # needed because perms are screwed.'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code
  - CmdLine:
    - cp /code/motd.tail /etc
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /code/motd.tail
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /code;git clone https://github.com/jyidiego/rax_examples.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /code;git clone https://github.com/heat-ci/heat-templates.git
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /root/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:12.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:12.04
