MetaArgs: null
Stages:
- BaseName: python:3
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"mkb72@cornell.edu"'
    Name: label
  - CmdLine:
    - apt update &&    apt install -f -y poppler-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --no-cache-dir pdfminer3k==1.3.1
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /scripts
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - fulltext
    - /scripts
  - Name: volume
    Volumes:
    - /pdfs
  - CmdLine:
    - /bin/bash /scripts/extract.sh
    Name: cmd
    PrependShell: true
  From:
    Image: python:3
  Name: ""
  Platform: ""
  SourceCode: FROM python:3
