MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Labels:
    - Key: name
      Value: '"WebTester"'
    - Key: vendor
      Value: '"ClusterTech"'
    - Key: version
      Value: '"1"'
    - Key: maintainer
      Value: '"jggao@clustertech.com"'
    Name: label
  - Env:
    - Key: PATH
      Value: /usr/local/bin:$PATH
    Name: env
  - Env:
    - Key: LANG
      Value: zh_CN.UTF-8
    Name: env
  - CmdLine:
    - apk add --update --no-cache ca-certificates bash python3 python3-dev jpeg-dev
      zlib-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - "set -ex;     cd /usr/bin \t&& ln -svf pydoc3 pydoc \t&& ln -svf python3 python
      \t&& ln -svf python3-config python-config \t&& ln -svf pip3 pip"
    Name: run
    PrependShell: true
  - CmdLine:
    - "set -ex;         apk add --update --no-cache --virtual .deps gcc g++; \t\tpip
      --version; \t\tpip install selenium behave IPython nose pillow; \t\tapk del
      .deps"
    Name: run
    PrependShell: true
  - CmdLine:
    - '''bash'''
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
