MetaArgs: null
Stages:
- BaseName: ceph/daemon:latest
  Commands:
  - Maintainer: Marc Villacorta Morera <marc.villacorta@gmail.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - rootfs
    - /
  - Name: volume
    Volumes:
    - /etc/ceph
    - /var/lib/ceph
  - Name: workdir
    Path: /
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ceph/daemon:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ceph/daemon:latest
