MetaArgs: null
Stages:
- BaseName: docker:latest
  Commands:
  - CmdLine:
    - apk --update add git openssh rsync
    Name: run
    PrependShell: true
  From:
    Image: docker:latest
  Name: ""
  Platform: ""
  SourceCode: FROM docker:latest
