MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - CmdLine:
    - "apt-get update && apt-get install -y \tbuild-essential \tpython"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - npm i nodemon -g
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - ./
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - CmdLine:
    - npm rebuild bcrypt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
