MetaArgs: null
Stages:
- As: build-stage
  BaseName: node:alpine
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package*.json
    - ./
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - ./
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  From:
    Image: node:alpine
  Name: build-stage
  Platform: ""
  SourceCode: FROM node:alpine as build-stage
- As: production-stage
  BaseName: nginx:alpine
  Commands:
  - Chown: ""
    From: build-stage
    Name: copy
    SourcesAndDest:
    - /app/dist
    - /usr/share/nginx/html
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - nginx
    - -g
    - daemon off;
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:alpine
  Name: production-stage
  Platform: ""
  SourceCode: FROM nginx:alpine as production-stage
