MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y aptitude
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y     dialog     apt-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y     curl     arping     arp-scan     bind9-host     dhcping     dnsutils     git     iptables     iputils-ping     mtr     nano     netcat     net-tools     nmap     tcpdump     telnet     tftp-hpa     traceroute     vim     wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt upgrade -y
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
