MetaArgs: null
Stages:
- BaseName: shadowsocks/shadowsocks-libev:latest
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - s.json
    - /s.json
  - CmdLine:
    - ss-server -c /s.json
    Name: cmd
    PrependShell: true
  From:
    Image: shadowsocks/shadowsocks-libev:latest
  Name: ""
  Platform: ""
  SourceCode: FROM shadowsocks/shadowsocks-libev:latest
