MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Key: TF_SERVING_VERSION_GIT_BRANCH
    Name: arg
    Value: master
  - Key: TF_SERVING_VERSION_GIT_COMMIT
    Name: arg
    Value: head
  - Labels:
    - Key: maintainer
      Value: gvasudevan@google.com
    Name: label
  - Labels:
    - Key: tensorflow_serving_github_branchtag
      Value: ${TF_SERVING_VERSION_GIT_BRANCH}
    Name: label
  - Labels:
    - Key: tensorflow_serving_github_commit
      Value: ${TF_SERVING_VERSION_GIT_COMMIT}
    Name: label
  - CmdLine:
    - apt-get update && apt-get install -y         automake         build-essential         curl         git         libcurl3-dev         libfreetype6-dev         libpng12-dev         libtool         libzmq3-dev         mlocate         openjdk-8-jdk        openjdk-8-jre-headless         pkg-config         python-dev         python-numpy         python-pip         software-properties-common         swig         wget         zip         zlib1g-dev         &&     apt-get
      clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install mock grpcio
    Name: run
    PrependShell: true
  - Env:
    - Key: BAZEL_VERSION
      Value: 0.15.0
    Name: env
  - Name: workdir
    Path: /
  - CmdLine:
    - 'mkdir /bazel &&     cd /bazel &&     curl -H "User-Agent: Mozilla/5.0 (X11;
      Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
      -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
      &&     curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -o /bazel/LICENSE.txt
      https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE &&     chmod
      +x bazel-*.sh &&     ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh &&     cd
      / &&     rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tensorflow-serving
  - CmdLine:
    - git clone --branch=${TF_SERVING_VERSION_GIT_BRANCH} https://github.com/tensorflow/serving
      . &&     git remote add upstream https://github.com/tensorflow/serving.git &&     if
      [ "${TF_SERVING_VERSION_GIT_COMMIT}" != "head" ]; then git checkout ${TF_SERVING_VERSION_GIT_COMMIT}
      ; fi
    Name: run
    PrependShell: true
  - Key: TF_SERVING_BUILD_OPTIONS
    Name: arg
    Value: '"--copt=-mavx --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0"'
  - Key: TF_SERVING_BAZEL_OPTIONS
    Name: arg
    Value: '"--action_env TF_REVISION=63c54eab8c7d526d49ecbb441e12a81b86dfdeaa"'
  - CmdLine:
    - bazel build -c opt --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server
      &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server
      /usr/local/bin/ &&     bazel clean --expunge --color=yes &&     rm -rf /root/.cache
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
