MetaArgs: null
Stages:
- BaseName: golang
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/golang/example/web
  - CmdLine:
    - go install github.com/golang/example/web
    Name: run
    PrependShell: true
  - CmdLine:
    - /go/bin/web
    Name: entrypoint
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  From:
    Image: golang
  Name: ""
  Platform: ""
  SourceCode: FROM golang
