MetaArgs: null
Stages:
- BaseName: node:6
  Commands:
  - Name: expose
    Ports:
    - "8080"
  - Maintainer: Christopher S. Case <chris.case@g33xnexus.com>
    Name: maintainer
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /usr/src/app/
  - CmdLine:
    - "npm install \t&& npm install grunt-cli \t&& npm install bower \t&& ./node_modules/.bin/bower
      install --allow-root \t&& ./node_modules/.bin/grunt build"
    Name: run
    PrependShell: true
  - Key: PORTAL_API_KEY
    Name: arg
    Value: null
  - CmdLine:
    - node
    - server.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:6
  Name: ""
  Platform: ""
  SourceCode: FROM node:6
