MetaArgs: null
Stages:
- As: client
  BaseName: node:12.2.0-alpine
  Commands:
  - Name: workdir
    Path: /usr/loanbook/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package*.json
    - ./
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /
    - ./
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  From:
    Image: node:12.2.0-alpine
  Name: client
  Platform: ""
  SourceCode: FROM node:12.2.0-alpine as client
