MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - CmdLine:
    - yum update -y && yum install -y skopeo-0.1.31*
    Name: run
    PrependShell: true
  - CmdLine:
    - skopeo
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
