MetaArgs: null
Stages:
- BaseName: kawayu168/debian-kafka:stretch
  Commands:
  - Maintainer: Haruki Yukawa
    Name: maintainer
  - Env:
    - Key: APACHE_MIRROR
      Value: http://ftp.jaist.ac.jp
    Name: env
  - Env:
    - Key: KAFKA_VERSION
      Value: 0.11.0.0
    Name: env
  - Env:
    - Key: KAFKA_BINARY_VERSION
      Value: kafka_2.11-$KAFKA_VERSION
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - configure_s3_sink.sh
    - /configure_s3_sink.sh
  - CmdLine:
    - wget "$APACHE_MIRROR/pub/apache/kafka/$KAFKA_VERSION/$KAFKA_BINARY_VERSION.tgz"
      -O /$KAFKA_BINARY_VERSION.tgz &&     tar -zxf /$KAFKA_BINARY_VERSION.tgz &&     rm
      /$KAFKA_BINARY_VERSION.tgz &&     ln -s /$KAFKA_BINARY_VERSION kafka &&     mkdir
      -p /tmp/sink &&     git clone https://github.com/kawayu168/kafka-connect-s3.git
      /tmp/sink/kafka-connect-s3 &&     cd /tmp/sink/kafka-connect-s3 &&     mvn assembly:assembly
      -DdescriptorId=jar-with-dependencies &&     mv /tmp/sink/kafka-connect-s3/target/kafka-connect-s3-0.0.3-jar-with-dependencies.jar
      /kafka/ &&     mv /tmp/sink/kafka-connect-s3/connect-s3-sink.properties /kafka/
      &&     mv /tmp/sink/kafka-connect-s3/connect-worker.properties /kafka/ &&     rm
      -rf /tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/kafka/bin
    Name: env
  - Env:
    - Key: CLASSPATH
      Value: /kafka-connect-s3-0.0.3-jar-with-dependencies.jar
    Name: env
  - CmdLine:
    - chmod ugo+rx /configure_s3_sink.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /configure_s3_sink.sh
    Name: cmd
    PrependShell: false
  From:
    Image: kawayu168/debian-kafka:stretch
  Name: ""
  Platform: ""
  SourceCode: FROM kawayu168/debian-kafka:stretch
