MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - tsconfig.json
    - package.json
    - yarn.lock
    - ./
  - CmdLine:
    - yarn install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - ./src
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf src tsconfig.json &&   mv ./dist/** . && rm -rf ./dist/ &&   yarn install
      --production
    Name: run
    PrependShell: true
  - CmdLine:
    - ls -la
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/npm
    - run
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
