MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Maintainer: David Personette <dperson@gmail.com>
    Name: maintainer
  - CmdLine:
    - export DEBIAN_FRONTEND='noninteractive' &&     export sha256sum='89029ff0c510733f211abdababb43fc5dab510d08d8a45c23ec7'
      &&     export url='https://downloads.plex.tv/plex-media-server-new' &&     export
      version='1.18.1.1973-0f4abfbcc' &&     apt-get update -qq &&     apt-get install
      -qqy --no-install-recommends ca-certificates curl gnupg1                 procps                 $(apt-get
      -s dist-upgrade|awk '/^Inst.*ecurity/ {print $2}') &&    mkdir -p /config/Library/Application\
      Support &&     ln -s /config /var/lib/plexmediaserver &&     file="plexmediaserver_${version}_amd64.deb"
      &&     echo "downloading $file ..." &&     curl -LOSs $url/$version/debian/$file
      &&     sha256sum $file | grep -q "$sha256sum" ||     { echo "expected $sha256sum,
      got $(sha256sum $file)"; exit 13; } &&     { dpkg -i $file || :; } &&     {
      mkdir -p /config /data || :; } &&     chown plex. -Rh /config &&     chown plex.
      /data &&     apt-get purge -qqy ca-certificates curl gnupg1 &&     apt-get autoremove
      -qqy && apt-get clean &&     rm -rf /tmp/* /var/lib/apt/lists/* $file
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - plex.sh
    - /usr/bin/
  - Name: volume
    Volumes:
    - /config
    - /data
  - Name: expose
    Ports:
    - "32400"
  - CmdLine:
    - plex.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
