MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: Gary Zhang "lionzhang@live.cn"
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y nginx
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'Hi, I am in your container' > /usr/share/nginx/html/index.html
    Name: run
    PrependShell: true
  - Env:
    - Key: LASTREFRESHED_AT
      Value: = 20160827
    Name: env
  - Name: expose
    Ports:
    - "80"
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
