MetaArgs: null
Stages:
- BaseName: alepeh/emacs26-lucid
  Commands:
  - Maintainer: JAremko <w3techplaygound@gmail.com>
    Name: maintainer
  - Env:
    - Key: UNAME
      Value: '"spacemacser"'
    - Key: UID
      Value: '"1000"'
    Name: env
  - Env:
    - Key: NNG_URL
      Value: '"https://github.com/google/fonts/raw/master/ofl/nanumgothic/NanumGothic-Regular.ttf"'
    - Key: SCP_URL
      Value: '"https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz"'
    Name: env
  - CmdLine:
    - apt-get update && apt-get install wget     && mkdir -p /usr/local/share/fonts     &&
      wget -qO- "${SCP_URL}" | tar xz -C /usr/local/share/fonts     && wget -q "${NNG_URL}"
      -P /usr/local/share/fonts     && fc-cache -fv     && apt-get purge wget     &&
      rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - ${UHOME}/.emacs.d
  - CmdLine:
    - cp ${UHOME}/.emacs.d/core/templates/.spacemacs.template ${UHOME}/     && mv
      ${UHOME}/.spacemacs.template ${UHOME}/.spacemacs     && sed -i "s/\(-distribution
      'spacemacs\)/\1-docker/"     ${UHOME}/.spacemacs     && asEnvUser emacs -batch
      -u ${UNAME} -kill     && asEnvUser emacs -batch -u ${UNAME} -kill     && chmod
      ug+rw -R ${UHOME}
    Name: run
    PrependShell: true
  - CmdLine:
    - 'asEnvUser make -C ${UHOME}/.emacs.d/tests/core/ test     && cd ${UHOME}/.emacs.d     &&
      printf "SPACEMACS REVISION: %s\n" "$(git rev-parse --verify HEAD)"'
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s     ${UHOME}/.emacs.d/layers/+distributions/spacemacs-docker/deps-install/run     /usr/local/sbin/install-deps     &&
      chown root:root /usr/local/sbin/install-deps     && chmod 770 /usr/local/sbin/install-deps
    Name: run
    PrependShell: true
  From:
    Image: alepeh/emacs26-lucid
  Name: ""
  Platform: ""
  SourceCode: FROM alepeh/emacs26-lucid
