MetaArgs: null
Stages:
- BaseName: gcc
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /src/osmctools/
  - Name: workdir
    Path: /src/osmctools/
  - CmdLine:
    - autoreconf --install
    Name: run
    PrependShell: true
  - CmdLine:
    - ./configure
    Name: run
    PrependShell: true
  - CmdLine:
    - make
    Name: run
    PrependShell: true
  - CmdLine:
    - make install
    Name: run
    PrependShell: true
  From:
    Image: gcc
  Name: ""
  Platform: ""
  SourceCode: FROM gcc
