MetaArgs: null
Stages:
- BaseName: python:2
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - python
    - ./Experiment.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:2
  Name: ""
  Platform: ""
  SourceCode: FROM python:2
