MetaArgs: null
Stages:
- BaseName: codenvy/angular-yeoman
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /tmp/application/package.json
  - CmdLine:
    - cd /tmp/application &&     npm install &&     cp -a /tmp/application/node_modules
      /home/user/application/
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /tmp/app/
  - CmdLine:
    - cd /tmp/app &&     cp -a /tmp/app/. /home/user/application/
    Name: run
    PrependShell: true
  From:
    Image: codenvy/angular-yeoman
  Name: ""
  Platform: ""
  SourceCode: FROM codenvy/angular-yeoman
