MetaArgs: null
Stages:
- BaseName: gentoo/stage3-amd64
  Commands:
  - CmdLine:
    - mkdir -p /etc/portage/repos.conf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gentoo.conf
    - /etc/portage/repos.conf/
  - CmdLine:
    - emerge-webrsync
    Name: run
    PrependShell: true
  - CmdLine:
    - FEATURES="-sandbox" emerge -1 --quiet sys-apps/portage
    Name: run
    PrependShell: true
  - CmdLine:
    - FEATURES="-sandbox" emerge --quiet dev-vcs/git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - GentooStudio.conf
    - /etc/portage/repos.conf/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - audio-overlay.conf
    - /etc/portage/repos.conf/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - make.conf
    - /etc/portage/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.accept_keywords
    - /etc/portage/package.accept_keywords
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.use
    - /etc/portage/package.use
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.mask
    - /etc/portage/package.mask
  - CmdLine:
    - emerge --sync --quiet
    Name: run
    PrependShell: true
  - CmdLine:
    - FEATURES="-sandbox" emerge --quiet --update --deep --newuse --autounmask-continue
      @system @world
    Name: run
    PrependShell: true
  From:
    Image: gentoo/stage3-amd64
  Name: ""
  Platform: ""
  SourceCode: FROM gentoo/stage3-amd64
