MetaArgs: null
Stages:
- BaseName: python:alpine
  Commands:
  - Labels:
    - Key: author
      Value: '"Kay"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - /src/
  - Name: workdir
    Path: /src
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - python
    - /src/app.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:alpine
