MetaArgs: null
Stages:
- BaseName: quay.io/keboola/base-python:3.5.1-g
  Commands:
  - Maintainer: Keenan Keeling <kkeeling@automatastudios.com>
    Name: maintainer
  - Name: workdir
    Path: /home
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /home/
  - CmdLine:
    - "yum -y update \t&& yum -y install \t\tipython \t&& yum clean all"
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip --cert=/tmp/cacert.pem
    Name: run
    PrependShell: true
  - CmdLine:
    - "pip install --no-cache-dir --ignore-installed --cert=/tmp/cacert.pem \t\tboto
      \t\tipython \t&& pip install --upgrade --no-cache-dir --ignore-installed --cert=/tmp/cacert.pem
      git+git://github.com/keboola/python-docker-application.git@1.2.0"
    Name: run
    PrependShell: true
  - CmdLine:
    - python ./main.py --data=/data/
    Name: entrypoint
    PrependShell: true
  From:
    Image: quay.io/keboola/base-python:3.5.1-g
  Name: ""
  Platform: ""
  SourceCode: FROM quay.io/keboola/base-python:3.5.1-g
