MetaArgs: null
Stages:
- BaseName: weaveworks/weave-npc:1.7.2
  Commands:
  - Maintainer: mritd <mritd@mritd.me>
    Name: maintainer
  From:
    Image: weaveworks/weave-npc:1.7.2
  Name: ""
  Platform: ""
  SourceCode: FROM weaveworks/weave-npc:1.7.2
