MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"gedy.palomino@gmail.com"'
    Name: label
  - Key: LOCALE
    Name: arg
    Value: America/Lima
  - Key: USER
    Name: arg
    Value: developer
  - Env:
    - Key: USER
      Value: $USER
    Name: env
  - Env:
    - Key: LC_ALL
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: TZ
      Value: $LOCALE
    Name: env
  - CmdLine:
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg --add-architecture i386
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y default-jdk
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y make sudo git vim usbutils android-tools-adb android-tools-fastboot
      locales
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get autoremove -y \t&& \tapt-get clean"
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash $USER
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -aG sudo,plugdev,kvm,libvirt $USER
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "$USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-$USER
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules
    - /etc/udev/rules.d/51-android.rules
  - CmdLine:
    - chmod a+r /etc/udev/rules.d/51-android.rules
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/$USER/.opt/
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://dl.google.com/dl/android/studio/ide-zips/3.5.3.0/android-studio-ide-191.6010548-linux.tar.gz
    - /home/$USER/.opt/android-studio.tar.gz
  - CmdLine:
    - cd /home/$USER/.opt/ && tar -xvzf android-studio.tar.gz && rm android-studio.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R $USER:$USER /home/$USER/.opt/
    Name: run
    PrependShell: true
  - Name: user
    User: $USER
  - Name: workdir
    Path: /home/$USER
  - CmdLine:
    - .opt/android-studio/bin/studio.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
