MetaArgs: null
Stages:
- BaseName: ruby:2.5.0
  Commands:
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -qq -y --no-install-recommends       build-essential
      libpq-dev curl
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - CmdLine:
    - bin/rails
    - server
    - -e production
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.5.0
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.0
