MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Peter Ericson <pdericson@gmail.com>
    Name: maintainer
  - CmdLine:
    - TINI_VERSION=0.9.0; apt-get update && apt-get upgrade -y && apt-get install
      --no-install-recommends -y ca-certificates curl && curl -fLO https://github.com/krallin/tini/releases/download/v$TINI_VERSION/tini_$TINI_VERSION.deb
      && dpkg -i tini_$TINI_VERSION.deb && rm -f tini_$TINI_VERSION.deb && rm -rf
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/tini
    - -g
    - -v
    - --
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
