MetaArgs: null
Stages:
- BaseName: openshift/base-centos7
  Commands:
  - Labels:
    - Key: io.k8s.description
      Value: '"Platform for building xyz"'
    - Key: io.k8s.display-name
      Value: '"builder x.y.z"'
    - Key: io.openshift.expose-services
      Value: '"8088:http"'
    - Key: io.openshift.tags
      Value: '"builder,x.y.z,etc."'
    Name: label
  - CmdLine:
    - yum install -y rubygems && yum clean all -y
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install asdf
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y java-1.8.0-openjdk  java-1.8.0-openjdk-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/isimapp/
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./isimPlatform.jar
    - /opt/app-root/src/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./s2i/bin/
    - /usr/libexec/s2i
  - CmdLine:
    - chown -R 1001:1001 /opt/app-root
    Name: run
    PrependShell: true
  - Name: user
    User: "1001"
  - Name: expose
    Ports:
    - "8088"
  From:
    Image: openshift/base-centos7
  Name: ""
  Platform: ""
  SourceCode: FROM openshift/base-centos7
