MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Rémi Jouannet "remijouannet@gmail.com"
    Name: maintainer
  - CmdLine:
    - ping -c2 ftp.debian.org
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y bash ca-certificates openjdk-7-jre-headless
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y bash openssh-client pwgen curl git mysql-client
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://dl.bintray.com/rundeck/rundeck-deb/rundeck-2.6.2-1-GA.deb
    - /tmp/rundeck.deb
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - useradd -d /var/lib/rundeck -s /bin/false rundeck
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+x ./run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4443"
  - CmdLine:
    - ./run.sh
    Name: cmd
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
