MetaArgs: null
Stages:
- BaseName: brunoric/hhvm:deb-hhvm
  Commands:
  - Maintainer: gabrielrcouto <gabrielrcouto@gmail.com>
    Name: maintainer
  - CmdLine:
    - echo 'deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse' >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb-src http://us.archive.ubuntu.com/ubuntu/ trusty multiverse' >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:ondrej/php -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --force-yes xorg libssl-dev libxrender-dev libjpeg8-dev libjpeg8
      fontconfig ttf-mscorefonts-installer xfonts-75dpi curl mysql-client-5.5 php7.0-cli
      php7.0-curl php7.0-gd php7.0-intl php7.0-mysql php7.0-mcrypt php7.0-dom php-memcached
      php7.0-mbstring
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
      && dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb && rm wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && apt-get autoremove -y
    Name: run
    PrependShell: true
  - CmdLine:
    - php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
    Name: run
    PrependShell: true
  - CmdLine:
    - php composer-setup.php
    Name: run
    PrependShell: true
  - CmdLine:
    - php -r "unlink('composer-setup.php');"
    Name: run
    PrependShell: true
  - CmdLine:
    - mv composer.phar /usr/local/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - /scripts/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: brunoric/hhvm:deb-hhvm
  Name: ""
  Platform: ""
  SourceCode: FROM brunoric/hhvm:deb-hhvm
