MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Maintainer: Eli Young <elyscape@gmail.com>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache socklog
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 8514/udp
  - CmdLine:
    - /sbin/socklog
    - inet
    - "0"
    - "8514"
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
