MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - CmdLine:
    - apk update &&     apk upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /usr/src/app/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/app
  - CmdLine:
    - npm start
    Name: cmd
    PrependShell: true
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
