MetaArgs: null
Stages:
- BaseName: openjdk:8-slim
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y wget curl build-essential git
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
      add -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs google-chrome-stable
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /tests
    Name: run
    PrependShell: true
  - CmdLine:
    - npm i -g yarn
    Name: run
    PrependShell: true
  - Key: user
    Name: arg
    Value: jenkins
  - Key: group
    Name: arg
    Value: jenkins
  - Key: uid
    Name: arg
    Value: "10000"
  - Key: gid
    Name: arg
    Value: "10000"
  - Env:
    - Key: HOME
      Value: /home/${user}
    Name: env
  - CmdLine:
    - groupadd -g ${gid} ${group}
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -c "Jenkins user" -d $HOME -u ${uid} -g ${gid} -m ${user}
    Name: run
    PrependShell: true
  - Labels:
    - Key: Description
      Value: '"This is a base image, which provides the Jenkins agent executable (slave.jar)"'
    - Key: Vendor
      Value: '"Jenkins project"'
    - Key: Version
      Value: '"3.23"'
    Name: label
  - Key: VERSION
    Name: arg
    Value: "3.26"
  - Key: AGENT_WORKDIR
    Name: arg
    Value: /home/${user}/agent
  - CmdLine:
    - curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /usr/share/jenkins
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 644 /usr/share/jenkins/slave.jar
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jenkins-slave
    - /usr/local/bin/jenkins-slave
  - CmdLine:
    - chmod +x /usr/local/bin/jenkins-slave
    Name: run
    PrependShell: true
  - Name: user
    User: ${user}
  - Env:
    - Key: AGENT_WORKDIR
      Value: ${AGENT_WORKDIR}
    Name: env
  - Env:
    - Key: PATH
      Value: ${PATH}:/usr/local/bin:/usr/bin
    Name: env
  - CmdLine:
    - mkdir /home/${user}/.jenkins && mkdir -p ${AGENT_WORKDIR}
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /home/${user}/.jenkins
  - Name: volume
    Volumes:
    - ${AGENT_WORKDIR}
  - Name: workdir
    Path: /home/${user}
  - CmdLine:
    - /usr/local/bin/jenkins-slave
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-slim
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-slim
