MetaArgs: null
Stages:
- BaseName: openjdk:8u151-jdk
  Commands:
  - Env:
    - Key: VERSION
      Value: '"0.26.5"'
    Name: env
  - Env:
    - Key: DHASH
      Value: '"ffebdfd96a6924bfb2e73ec22756fc6b1512651a798918bb2cec0ae7595bdd6e"'
    Name: env
  - Env:
    - Key: DIR_QORA_TOP
      Value: /usr/src
    Name: env
  - Env:
    - Key: DIR_QORA
      Value: ${DIR_QORA_TOP}/Qora_v${VERSION}/Qora
    Name: env
  - Labels:
    - Key: version
      Value: '"${VERSION}"'
    Name: label
  - CmdLine:
    - apt-get update &&   apt-get install -y xvfb x11vnc net-tools vim less &&   rm
      -fr /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir ~/.vnc &&   x11vnc -storepasswd 1234 ~/.vnc/passwd
    Name: run
    PrependShell: true
  - Env:
    - Key: DISPLAY
      Value: :0
    Name: env
  - CmdLine:
    - cd ${DIR_QORA_TOP} &&   wget -nv https://github.com/Qoracoin/Qora/releases/download/${VERSION}/Qora_v${VERSION}.zip
      &&   echo "$DHASH Qora_v${VERSION}.zip" | sha256sum -c - &&   unzip -q Qora_v${VERSION}.zip
      &&   rm -f Qora_v${VERSION}.zip
    Name: run
    PrependShell: true
  - Name: workdir
    Path: ${DIR_QORA}
  - Name: expose
    Ports:
    - "5900"
  From:
    Image: openjdk:8u151-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8u151-jdk
