MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.11
  Commands:
  - Maintainer: Mike O'Driscoll <mike@mikeodriscoll.ca>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - CmdLine:
    - usermod -u 99 nobody && usermod -g 100 nobody
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -qq && apt-get install -qq -y software-properties-common && apt-add-repository
      ppa:modriscoll/nzbget && apt-get update -qq && apt-get install -qq -y nzbget
      wget unrar unzip p7zip git python-pip supervisor && apt-get upgrade -qq && apt-get
      autoclean && apt-get autoremove && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install tekuila
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pynzbget
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - Name: volume
    Volumes:
    - /downloads
  - Name: expose
    Ports:
    - "6789"
  - CmdLine:
    - mkdir -p /etc/my_init.d
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init/setup.sh
    - /etc/my_init.d/setup.sh
  - CmdLine:
    - chmod +x /etc/my_init.d/setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/service/supervisor
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init/supervisor.conf
    - /etc/supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init/supervisor.sh
    - /etc/service/supervisor/run
  - CmdLine:
    - chmod +x /etc/service/supervisor/run
    Name: run
    PrependShell: true
  From:
    Image: phusion/baseimage:0.11
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.11
