MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-alpine
  Commands:
  - CmdLine:
    - "apk add --no-cache --update \tlinux-headers \tpython \tcurl"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - default_crontabs
    - /var/spool/cron/crontabs/root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init
    - /init
  - CmdLine:
    - chmod 755  /init
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - CmdLine:
    - /init
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-alpine
