MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - CmdLine:
    - apt-key adv --keyserver pgp.mit.edu --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://nginx.org/packages/mainline/debian/ wheezy nginx" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y supervisor nginx-light php5-fpm php-apc
      php5-cli php5-intl php5-gd php5-mysqlnd php-mail curl &&     apt-get autoremove
      &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: MEDIAWIKI_MAJOR
      Value: "1.23"
    Name: env
  - Env:
    - Key: MEDIAWIKI_VERSION
      Value: 1.23.7
    Name: env
  - CmdLine:
    - mkdir /src && cd /src &&     curl -SL http://download.wikimedia.org/mediawiki/$MEDIAWIKI_MAJOR/mediawiki-$MEDIAWIKI_VERSION.tar.gz
      -o /src/mediawiki.tgz &&     tar zxf mediawiki.tgz && rm mediawiki.tgz &&     mv
      /src/mediawiki-* /src/mediawiki &&     cd /src/mediawiki/extensions &&     curl
      -SL https://github.com/gilluminate/FancyBoxThumbs/archive/master.tar.gz -o /src/mediawiki/extensions/FancyBoxThumbs.tgz
      &&     tar zxf FancyBoxThumbs.tgz && rm FancyBoxThumbs.tgz && mv FancyBoxThumbs-master
      FancyBoxThumbs &&     curl -SL "https://git.wikimedia.org/zip/?r=mediawiki/extensions/MultiMaps&h=REL1_23&format=gz"
      -o /src/mediawiki/extensions/MultiMaps.tgz &&     mkdir MultiMaps && tar zxf
      MultiMaps.tgz -C MultiMaps && rm MultiMaps.tgz &&     chown -R www-data:www-data
      /src/mediawiki/
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./fpm.conf
    - /etc/php5/fpm/php-fpm.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./fpm-pool-www.conf
    - /etc/php5/fpm/pool.d/www.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mediawiki-start
    - /usr/bin/mediawiki-start
  - CmdLine:
    - mkdir /data &&     ln -s /data/LocalSettings.php /src/mediawiki/LocalSettings.php
      &&     rm -rf /src/mediawiki/images &&     ln -s /data/images /src/mediawiki/images
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/log/**/*.log
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: volume
    Volumes:
    - /var/log
  - Name: expose
    Ports:
    - "80"
  - Name: workdir
    Path: /src/mediawiki/maintenance
  - CmdLine:
    - /usr/bin/mediawiki-start
    Name: cmd
    PrependShell: false
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
