MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Eric Lung <longminxiang@163.com>
    Name: maintainer
  - CmdLine:
    - (yum update && yum -y install epel-release &&yum -y install python-pip python-devel
      &&yum clean all)
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd root &&mkdir .pip &&cd .pip &&echo -e "\n[global]\nindex-url = http://pypi.douban.com/simple\n--trusted-host
      = pypi.douban.com">> pip.conf &&cd /usr/lib/python2.7/site-packages/ &&echo
      -e "import sys\nsys.setdefaultencoding('utf-8')">> sitecustomize.py)
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd /var && echo -e "#!/bin/sh\nwhile true\ndo\nsleep 10000\ndone" >> daemon.sh)
    Name: run
    PrependShell: true
  - CmdLine:
    - sh
    - /var/daemon.sh
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
