MetaArgs: null
Stages:
- BaseName: lsiobase/alpine.python:3.6
  Commands:
  - Env:
    - Key: PYTHONIOENCODING
      Value: '"UTF-8"'
    Name: env
  - CmdLine:
    - git clone --depth 1 https://github.com/BenjV/autosub /app/autosub
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root/
    - /
  - Name: expose
    Ports:
    - "9960"
  - Name: volume
    Volumes:
    - /config
    - /tv
  From:
    Image: lsiobase/alpine.python:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM lsiobase/alpine.python:3.6
