MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/kube-proxy:v1.13.2
  Commands:
  - Maintainer: yujia <yu-jiac@dxc.com>
    Name: maintainer
  - Labels:
    - Key: name
      Value: '"kube-proxy"'
    - Key: license
      Value: '"GPLv2"'
    - Key: build-date
      Value: '"20190116"'
    Name: label
  From:
    Image: gcr.io/google_containers/kube-proxy:v1.13.2
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/kube-proxy:v1.13.2
