MetaArgs:
- DefaultValue: master
  Key: FROM_TAG
  ProvidedValue: null
  Value: master
Stages:
- BaseName: chaossystems/fedora-devtools:$FROM_TAG
  Commands:
  - Maintainer: Greg Orzell <chaos@chaossystems.io>
    Name: maintainer
  - CmdLine:
    - pip install --upgrade pip &&     pip install     setuptools     aws-mfa     awscli
      &&     npm install -g ask-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/tmux
    Name: cmd
    PrependShell: false
  From:
    Image: chaossystems/fedora-devtools:$FROM_TAG
  Name: ""
  Platform: ""
  SourceCode: FROM chaossystems/fedora-devtools:$FROM_TAG
