MetaArgs: null
Stages:
- BaseName: openjdk:8-jre
  Commands:
  - Maintainer: Semantive "https://github.com/semantive"
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get -y update  && apt-get -y upgrade  && apt-get install -y --no-install-recommends
      apt-utils  && apt-get install -y locales  && dpkg-reconfigure -f noninteractive
      locales  && locale-gen C.UTF-8  && /usr/sbin/update-locale LANG=C.UTF-8  &&
      echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen  && locale-gen \ && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US:en
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - useradd -ms /bin/bash spark
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash hadoop
    Name: run
    PrependShell: true
  - Env:
    - Key: HADOOP_VERSION
      Value: 2.7.3
    Name: env
  - Env:
    - Key: HADOOP_HOME
      Value: /opt/hadoop-$HADOOP_VERSION
    Name: env
  - Env:
    - Key: HADOOP_CONF_DIR
      Value: $HADOOP_HOME/etc/hadoop
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$HADOOP_HOME/bin
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: $LD_LIBRARY_PATH:$HADOOP_HOME/lib/native
    Name: env
  - CmdLine:
    - wget -q -O- --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15
      -t 0   "http://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz"   |
      tar -xz -C /opt/  && rm -rf $HADOOP_HOME/share/doc  && chown -R hadoop:hadoop
      $HADOOP_HOME
    Name: run
    PrependShell: true
  - Env:
    - Key: SPARK_VERSION
      Value: 2.1.1
    Name: env
  - Env:
    - Key: SPARK_PACKAGE
      Value: spark-${SPARK_VERSION}-bin-hadoop2.7
    Name: env
  - Env:
    - Key: SPARK_HOME
      Value: /home/spark
    Name: env
  - Env:
    - Key: SPARK_DIST_CLASSPATH
      Value: '"$HADOOP_HOME/etc/hadoop/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:$HADOOP_HOME/share/hadoop/tools/lib/*"'
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:${SPARK_HOME}/bin
    Name: env
  - CmdLine:
    - wget -q -O- --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15
      -t 0   "http://mirrors.advancedhosters.com/apache/spark/spark-${SPARK_VERSION}/${SPARK_PACKAGE}.tgz"   |
      tar xz --strip 1 -C $SPARK_HOME/  && chown -R spark:spark $SPARK_HOME
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Name: workdir
    Path: $SPARK_HOME
  - CmdLine:
    - su
    - -c
    - bin/spark-class org.apache.spark.deploy.master.Master
    - spark
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre
