MetaArgs: null
Stages:
- BaseName: alpine:3.11
  Commands:
  - Labels:
    - Key: description
      Value: '"Ansible on Alpine 3.11 and Python 3.7"'
    - Key: maintainer
      Value: '"Djerfy <djerfy@gmail.com>"'
    Name: label
  - CmdLine:
    - apk -U add gcc make python3 python3-dev openssl-dev &&     apk -U add py3-cffi
      py3-bcrypt py3-cryptography py3-pynacl &&     pip3 install --upgrade pip &&     pip3
      install ansible==2.9.3
    Name: run
    PrependShell: true
  - CmdLine:
    - ansible
    - --version
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.11
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.11
