MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk update     && apk add --no-cache --virtual build-dependencies     build-base     gcc     &&
      apk add --no-cache     bash     && apk add --no-cache     protobuf     protobuf-dev     &&
      apk add --no-cache     openssl     openssl-dev     && apk add --no-cache     qt5-qtbase     iputils     tcptraceroute     libpcap     libpcap-dev     whois     curl     ssmtp
      &&     mkdir /spoofer
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./spoofer-1.4.1.tar.gz
    - /spoofer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./entrypoint.sh
    - /spoofer
  - CmdLine:
    - sed -i 's/\r//' /spoofer/entrypoint.sh &&     chmod +x /spoofer/entrypoint.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./ssmtp.conf
    - /etc/ssmtp
  - Name: workdir
    Path: /spoofer
  - CmdLine:
    - tar xzvf spoofer-1.4.1.tar.gz &&     cd spoofer-1.4.1 &&     ./configure &&     make
      &&     make install &&     make clean &&     cd .. &&     rm -rf spoofer-1.4.1
      spoofer-1.4.1.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - /spoofer/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
