MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Francesco Sullo, sullof@sullof.com
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl wget zip unzip apt-transport-https ca-certificates cron
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-server python-setuptools && /usr/bin/easy_install
      supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get autoremove && apt-get autoclean
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash paulstaab
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/paulstaab/.ssh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - adds/authorized_keys_paulstaab
    - /home/paulstaab/.ssh/authorized_keys
  - CmdLine:
    - chmod 600 /home/paulstaab/.ssh/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R paulstaab:paulstaab /home/paulstaab
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - adds/authorized_keys
    - /authorized_keys
  - Chown: ""
    Name: add
    SourcesAndDest:
    - adds/configure.sh
    - /configure.sh
  - CmdLine:
    - bin/bash /configure.sh && rm /configure.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - adds/supervisord.conf
    - /etc/supervisord.conf
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /usr/local/bin/supervisord
    - -n
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
