MetaArgs: null
Stages:
- BaseName: alpine:3.3
  Commands:
  - CmdLine:
    - echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --update stress@testing  gcc bash && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.3
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.3
