MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Jocelyn LOPEZ <jocelyn.lopez.pro@gmail.com>
    Name: maintainer
  - Key: PYTHON_ROOT
    Name: arg
    Value: /executables
  - Key: PYTHON_VERSION
    Name: arg
    Value: 3.5.2
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - python.sh
    - /python.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /requirements.txt
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends         make         gcc         wget         libssl-dev         openssl
      && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /python.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /python.sh install $PYTHON_VERSION $PYTHON_ROOT /requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - $PYTHON_ROOT/$PYTHON_VERSION/bin/python
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
