MetaArgs: null
Stages:
- BaseName: pypy:3.6
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code/
  - Name: workdir
    Path: /code
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /code/
  - CmdLine:
    - pypy3 -m ensurepip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pycurl
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "12378"
  - CmdLine:
    - celery -A task worker --loglevel=info
    Name: entrypoint
    PrependShell: true
  - CmdLine:
    - pypy3 app.py
    Name: cmd
    PrependShell: true
  From:
    Image: pypy:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM pypy:3.6
