MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Maintainer: amhauser
    Name: maintainer
  - CmdLine:
    - '"echo ''hi girls''"'
    Name: cmd
    PrependShell: true
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
