MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Jacob Alberty <jacob.alberty@foundigital.com>
    Name: maintainer
  - Name: volume
    Volumes:
    - /var/lib/unifi
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - echo "deb http://www.ubnt.com/downloads/unifi/distros/deb/debian debian ubiquiti"   >
      /etc/apt/sources.list.d/20ubiquiti.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen"   >
      /etc/apt/sources.list.d/21mongodb.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv C0A52C50
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -q update &&     apt-get install -qy --force-yes unifi-beta=4.6.3-4850
      &&     apt-get -q clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 3478/udp
    - 8080/tcp
    - 8081/tcp
    - 8443/tcp
    - 8843/tcp
    - 8880/tcp
  - Name: workdir
    Path: /var/lib/unifi
  - CmdLine:
    - /usr/bin/java
    - -Xmx1024M
    - -jar
    - /usr/lib/unifi/lib/ace.jar
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
