MetaArgs: null
Stages:
- BaseName: nginx:latest
  Commands:
  - Name: workdir
    Path: /etc/nginx
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - symfony.conf
    - ./sites-available/symfony.conf
  - CmdLine:
    - rm ./conf.d/default.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "upstream php-upstream { server php:9000; }" > ./conf.d/upstream.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -u 1000 www-data
    Name: run
    PrependShell: true
  From:
    Image: nginx:latest
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:latest
