MetaArgs: null
Stages:
- BaseName: php:7-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Johannes Schickling <schickling.j@gmail.com>"'
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.sh
    - install.sh
  - CmdLine:
    - chmod +x install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - ./install.sh && rm install.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config.php
    - /source/config.php
  - Name: expose
    Ports:
    - "2080"
  - CmdLine:
    - sh -c 'BEANSTALK_SERVERS=$BEANSTALKD_PORT_11300_TCP_ADDR:11300 php -S 0.0.0.0:2080
      -t /source/public'
    Name: cmd
    PrependShell: true
  From:
    Image: php:7-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7-alpine
