MetaArgs: null
Stages:
- BaseName: php:7.0-apache
  Commands:
  - CmdLine:
    - a2enmod rewrite expires
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/html
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /httpdocs
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/html
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /var/www/html
  - CmdLine:
    - apache2-foreground
    Name: cmd
    PrependShell: false
  - CmdLine:
    - "set -ex; \t\tsavedAptMark=\"$(apt-mark showmanual)\"; \t\tapt-get update; \tapt-get
      install -y --no-install-recommends \t\tlibbz2-dev \t\tlibjpeg-dev \t\tlibldap2-dev
      \t\tlibmcrypt-dev \t\tlibmemcached-dev \t\tlibpng-dev \t\tlibpq-dev \t; \t\tdocker-php-ext-configure
      gd --with-png-dir=/usr --with-jpeg-dir=/usr; \tdebMultiarch=\"$(dpkg-architecture
      --query DEB_BUILD_MULTIARCH)\"; \tdocker-php-ext-configure ldap --with-libdir=\"lib/$debMultiarch\";
      \tdocker-php-ext-install \t\tbz2 \t\tgd \t\tldap \t\tmcrypt \t\tmysqli \t\tpdo_mysql
      \t\tpdo_pgsql \t\tpgsql \t\tzip \t;"
    Name: run
    PrependShell: true
  From:
    Image: php:7.0-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.0-apache
