MetaArgs: null
Stages:
- BaseName: diodfr/play-adherants
  Commands:
  - Maintainer: Didier BROCA <didier.broca@libertysurf.fr>
    Name: maintainer
  - CmdLine:
    - mkdir /opt/hashFind
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd /opt/ && git clone https://github.com/diodfr/hashFind.git && cd /opt/hashFind
      && mvn install && cd /opt && rm -f /opt/hasFind)
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/play_adherants
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd /opt && git clone https://github.com/diodfr/play_adherants.git)
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd /opt/play_adherants/ && play stage)
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/play_adherants
  - Name: expose
    Ports:
    - "9000"
  From:
    Image: diodfr/play-adherants
  Name: ""
  Platform: ""
  SourceCode: FROM diodfr/play-adherants
