MetaArgs: null
Stages:
- BaseName: jupyter/r-notebook
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Teotonio <teo.decarvalho@gmail.com>"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - conda install -c bioconda --quiet --yes     bioconductor-biostrings
    Name: run
    PrependShell: true
  - CmdLine:
    - conda install --quiet --yes pandas     rpy2 &&     conda clean -tipsy
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update &&     apt-get -yq install libssl1.0.0 libssl-dev &&     ln
      -s libssl.so.1.0.0 libssl.so.10 && \tln -s libcrypto.so.1.0.0 libcrypto.so.10"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -yq apt-transport-https ca-certificates
      curl software-properties-common &&     curl -fsSL https://download.docker.com/linux/ubuntu/gpg
      | sudo apt-key add - &&    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
      $(lsb_release -cs) stable" &&     apt-get update &&     apt-get install -yq
      docker-ce &&     apt-get clean &&     mkdir /Public
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /Public
  From:
    Image: jupyter/r-notebook
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/r-notebook
