MetaArgs: null
Stages:
- BaseName: java:8-jre
  Commands:
  - Maintainer: Alexander Dinauer <alexander@dinauer.at>
    Name: maintainer
  - Env:
    - Key: ELASTICSEARCH_VERSION
      Value: 1.5.2
    Name: env
  - CmdLine:
    - "wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz
      -O - | tar -xz --directory /opt && \tmv /opt/elasticsearch-${ELASTICSEARCH_VERSION}
      /opt/elasticsearch"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9200"
    - "9300"
  - CmdLine:
    - /opt/elasticsearch/bin/elasticsearch
    Name: cmd
    PrependShell: true
  From:
    Image: java:8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM java:8-jre
