MetaArgs: null
Stages:
- BaseName: projectatomic/atomicapp:0.1.1
  Commands:
  - Maintainer: Aaron Weitekamp <aweiteka@redhat.com>
    Name: maintainer
  - Labels:
    - Key: io.projectatomic.nulecule.providers
      Value: '"docker"'
    - Key: io.projectatomic.nulecule.specversion
      Value: '"0.0.2"'
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /Nulecule
    - /Dockerfile
    - README.md
    - /application-entity/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /artifacts
    - /application-entity/artifacts
  - Labels:
    - Key: RUN
      Value: '"docker run -it --rm \${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run
        -v /:/host --net=host --name \${NAME} -e NAME=\${NAME} -e IMAGE=\${IMAGE}
        \${IMAGE} \${OPT2} run --ask \${OPT3} /atomicapp"'
    Name: label
  From:
    Image: projectatomic/atomicapp:0.1.1
  Name: ""
  Platform: ""
  SourceCode: FROM projectatomic/atomicapp:0.1.1
