MetaArgs: null
Stages:
- BaseName: registry.access.redhat.com/ubi8/nodejs-10
  Commands:
  - CmdLine:
    - echo ${HOME}
    Name: run
    PrependShell: true
  - CmdLine:
    - whoami
    Name: run
    PrependShell: true
  - CmdLine:
    - pwd
    Name: run
    PrependShell: true
  - Env:
    - Key: NPM_CONFIG_PREFIX
      Value: ${HOME}/.npm-global
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:${HOME}/.npm-global/bin
    Name: env
  - CmdLine:
    - mkdir -p ${HOME}/app/client &&     mkdir -p ${HOME}/app/server &&     mkdir
      -p ${HOME}/app/public
    Name: run
    PrependShell: true
  - Chown: default:root
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ${HOME}/app
  - CmdLine:
    - cd ${HOME}/app; npm install && npm run build
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Env:
    - Key: PORT
      Value: "3000"
    Name: env
  - Name: expose
    Ports:
    - 3000/tcp
  - Name: workdir
    Path: ${HOME}/app
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: registry.access.redhat.com/ubi8/nodejs-10
  Name: ""
  Platform: ""
  SourceCode: FROM registry.access.redhat.com/ubi8/nodejs-10
