MetaArgs: null
Stages:
- BaseName: ubuntu:14.04.2
  Commands:
  - Maintainer: miurahr@linux.com
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install
    - /opt/
  - CmdLine:
    - chmod 755 /opt/install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - build-config
    - /opt/build-config
  - CmdLine:
    - /opt/install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init
    - /opt/
  - CmdLine:
    - chmod 755 /opt/init
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: volume
    Volumes:
    - /var/log/hubot
  - Name: workdir
    Path: /home/hubot
  - CmdLine:
    - /opt/init
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - app:start
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04.2
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04.2
