MetaArgs: null
Stages:
- BaseName: openresty/openresty:alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conneg.lua
    - /usr/local/openresty/lualib/conneg.lua
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - index.html
    - /www/data/index.html
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/conf.d/default.conf
  - Name: volume
    Volumes:
    - /www/data/id
  - Name: volume
    Volumes:
    - /www/data/api
  From:
    Image: openresty/openresty:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openresty/openresty:alpine
