MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Jessie Frazelle <jess@linux.com>
    Name: maintainer
  - Maintainer: Vincent Demeester <vincent@sbr.pm>
    Name: maintainer
  - CmdLine:
    - "apt-get update && apt-get install -y \tlibpangoxft-1.0-0 \talsa-utils \tsoftware-properties-common
      \        pulseaudio \t--no-install-recommends && \tapt-key adv --keyserver keyserver.ubuntu.com
      --recv-keys 94558F59 && \techo \"deb http://repository.spotify.com stable non-free\"
      >> /etc/apt/sources.list.d/spotify.list && \tapt-get update && \tapt-get install
      --force-yes -y \tspotify-client \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /home/spotify
    Name: env
  - CmdLine:
    - "useradd --create-home --home-dir $HOME spotify \t&& gpasswd -a spotify audio
      \t&& chown -R spotify:spotify $HOME"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $HOME
  - Name: user
    User: spotify
  - CmdLine:
    - 'echo "QLineEdit { color: #000 }" > /home/spotify/spotify-override.css'
    Name: run
    PrependShell: true
  - CmdLine:
    - spotify
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -stylesheet=/home/spotify/spotify-override.css
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
