MetaArgs: null
Stages:
- BaseName: debian:testing
  Commands:
  - Maintainer: Lars Boegild Thomsen <lbthomsen@gmail.com>
    Name: maintainer
  - CmdLine:
    - export DEBIAN_FRONTEND=noninteractive &&         apt-get -y update &&         apt-get
      install -yq curl
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -SL http://www.mersenne.org/ftp_root/gimps/p95v294b8.linux64.tar.gz | tar
      -xz mprime && mv mprime /usr/sbin && chmod +x /usr/sbin/mprime
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - runprime
    - /
  - CmdLine:
    - chmod +x ./runprime
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir prime
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - -c
    - ./runprime
    Name: cmd
    PrependShell: false
  From:
    Image: debian:testing
  Name: ""
  Platform: ""
  SourceCode: FROM debian:testing
