MetaArgs: null
Stages:
- BaseName: python:3
  Commands:
  - Maintainer: Ajeeth Samuel <ajeeth.samuel@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update     && apt-get install -y --no-install-recommends         sudo
      graphviz postgresql-client libldap2-dev libsasl2-dev     && apt-get clean     &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: NETBOX_COMMIT
      Value: ac1e4b8e8f4f320471676cd2f47b61bb42ad0fc4
    Name: env
  - CmdLine:
    - mkdir -p /usr/src/netbox     && git clone https://github.com/digitalocean/netbox.git
      /usr/src/netbox     && (cd /usr/src/netbox && git checkout -q "$NETBOX_COMMIT")     &&
      (cd /usr/src/netbox && pip3 install --no-cache-dir -r requirements.txt)
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install gunicorn     && pip3 install django-auth-ldap
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/netbox/netbox
  - CmdLine:
    - groupadd -g 1000 netbox     && useradd -u 1000 -g 1000 -d /usr/src/netbox netbox     &&
      chown -Rh netbox:netbox /usr/src/netbox
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /sbin/entrypoint.sh
  - CmdLine:
    - chmod 755 /sbin/entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 8000/tcp
  - CmdLine:
    - /sbin/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - runserver
    - --insecure
    - 0.0.0.0:8000
    Name: cmd
    PrependShell: false
  From:
    Image: python:3
  Name: ""
  Platform: ""
  SourceCode: FROM python:3
