MetaArgs: null
Stages:
- BaseName: ubuntu:15.10
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sqlite
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libsqlite-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sqlite3
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libsqlite3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libxslt-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libxml2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y gawk
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libreadline6-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libssl-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libyaml-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y autoconf
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libgdbm-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libncurses5-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y automake
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libtool
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y bison
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y pkg-config
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libffi-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y clang
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y llvm
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y llvm-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libedit-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libpq-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libgmp-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libgmp3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libmysqlclient-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
    Name: run
    PrependShell: true
  - CmdLine:
    - git config --global user.email "bot@pushbit.co"
    Name: run
    PrependShell: true
  - CmdLine:
    - git config --global user.name "Pushbit"
    Name: run
    PrependShell: true
  - CmdLine:
    - git config --global push.default simple
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./clone.sh
    - ./clone.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./copy.sh
    - ./copy.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./execute.sh
    - ./execute.sh
  - CmdLine:
    - ./copy.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ./execute.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:15.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:15.10
