MetaArgs: null
Stages:
- BaseName: rocker/shiny:latest
  Commands:
  - CmdLine:
    - chmod -R a+rwx /usr/local/lib/R/site-library
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y curl git libboost-all-dev     libgdal-dev
      libgdal20 libgit2-dev libproj-dev libssl-dev      libudunits2-0 libudunits2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - R -e "install.packages(c('curl', 'devtools', 'digest', 'dplyr', 'DT',     'geosphere',
      'ggplot2', 'ggthemes', 'glue', 'httr', 'htmlwidgets',     'htmltools', 'httpuv',
      'jsonlite', 'kableExtra', 'lattice','leaflet',     'leaflet.extras', 'magrittr',
      'markdown', 'mime', 'plyr', 'readr',     'RCurl', 'Rcpp', 'reshape2', 'rgdal',
      'rjson','phenoSynth', 'plotly',     'scales', 'shiny', 'shinyjs','shinythemes',
      'shinycssloaders',     'shinyWidgets', 'shinyBS', 'sf', 'stringi', 'tidyr',     'units',
      'yaml'), dependencies=TRUE)"
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /srv/shiny-server/*
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /srv/shiny-server/
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod -R 777 /srv/shiny-server
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/shiny-server.sh
    Name: cmd
    PrependShell: false
  From:
    Image: rocker/shiny:latest
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/shiny:latest
