MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.13.5-alpine3.11
  Commands:
  - CmdLine:
    - apk add --no-cache     make     git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /go/src/github.com/distributedio/titan
  - Name: workdir
    Path: /go/src/github.com/distributedio/titan
  - CmdLine:
    - env GOOS=linux CGO_ENABLED=0 make
    Name: run
    PrependShell: true
  From:
    Image: golang:1.13.5-alpine3.11
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.13.5-alpine3.11 as builder
- BaseName: alpine
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/distributedio/titan/titan
    - /titan/bin/titan
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/distributedio/titan/conf/titan.toml
    - /titan/conf/titan.toml
  - Name: workdir
    Path: /titan
  - Name: expose
    Ports:
    - "7369"
  - CmdLine:
    - ./bin/titan
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
