MetaArgs: null
Stages:
- BaseName: ergomentum/centos:7.3.161213211926
  Commands:
  - Maintainer: Ergomentum <build@ergomentum.org>
    Name: maintainer
  - Labels:
    - Key: vendor
      Value: '"Ergomentum"'
    - Key: license
      Value: '"Apache 2.0"'
    Name: label
  - CmdLine:
    - touch /var/lib/rpm/* &&   yum install openssl &&   yum clean all
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /etc/pki/CA
  - Name: volume
    Volumes:
    - /etc/pki/CA
  - Name: volume
    Volumes:
    - /etc/pki/tls/certs
  - Name: volume
    Volumes:
    - /etc/pki/tls/private
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - common_functions.sh
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ergomentum/centos:7.3.161213211926
  Name: ""
  Platform: ""
  SourceCode: FROM ergomentum/centos:7.3.161213211926
