MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Platform/IIBU <zhangzhitao@fmsh.com.cn>"'
    Name: label
  - Env:
    - Key: TZ
      Value: Asia/Shanghai
    Name: env
  - CmdLine:
    - set -ex; apk upgrade; apk add curl bash tzdata ca-certificates;     ln -sf /usr/share/zoneinfo/${TZ}
      /etc/localtime;     echo ${TZ} > /etc/timezone;     rm -rf /var/cache/apk/*;     curl
      -o /bin/mysqld_exporter https://raw.githubusercontent.com/currycan/docker-swarm-prometheus/master/mysqld_exporter/mysqld_exporter;     chmod
      770 /bin/mysqld_exporter
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /mysqld_exporter
  - Name: volume
    Volumes:
    - /mysqld_exporter
  - Name: expose
    Ports:
    - "9104"
  - CmdLine:
    - /bin/mysqld_exporter ${OPTS}
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
