MetaArgs: null
Stages:
- BaseName: ruby:2.3-alpine
  Commands:
  - Maintainer: bluebu <bluebuwang@gmail.com>
    Name: maintainer
  - Env:
    - Key: RAILS_VERSION
      Value: '"4.2.7"'
    - Key: BUILD_PACKAGES
      Value: '"curl-dev build-base openssh"'
    - Key: DEV_PACKAGES
      Value: '"tzdata libxml2 libxml2-dev libxslt libxslt-dev mysql-client                   imagemagick
        imagemagick-dev mysql-dev sqlite-dev git nodejs"'
    Name: env
  - CmdLine:
    - apk --update --upgrade add $BUILD_PACKAGES $DEV_PACKAGES &&   rm /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - 'gem install -N nokogiri &&   gem install -N rails --version "$RAILS_VERSION"
      &&   echo ''gem: --no-document'' >> ~/.gemrc &&   cp ~/.gemrc /etc/gemrc &&   chmod
      uog+r /etc/gemrc &&   rm -rf /usr/lib/lib/ruby/gems/*/cache/* &&   rm -rf ~/.gem'
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3-alpine
