MetaArgs: null
Stages:
- BaseName: debian:buster
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y dist-upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install sudo apt-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install locales
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US:en
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install fish bash zsh
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install vim emacs
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install git subversion
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install curl wget rsync
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install procps htop
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install texinfo texlive texlive-fonts-extra
      libcairo2-dev libtiff-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install r-base r-base-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install libgit2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install libssl-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install libxml2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install libcurl4-openssl-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install openjdk-11-jdk default-jdk
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install default-libmysqlclient-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install libsqlite3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install unixodbc-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install freeglut3-dev libfreetype6-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install xvfb expect libzstd-dev time
      tree pandoc xfonts-100dpi xfonts-75dpi
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://bit.ly/install-gnu-parallel | sh -x
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -qy install nginx
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -v /etc/nginx/nginx.conf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - paper.pdf
    - /var/www/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - small.html
    - /var/www/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - small_files
    - /var/www/small_files
  - Chown: ""
    Name: add
    SourcesAndDest:
    - large.html
    - /var/www/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - large_files
    - /var/www/large_files
  - CmdLine:
    - useradd -ms /bin/bash -G sudo aviral
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "aviral:aviral" | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "aviral ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
    Name: run
    PrependShell: true
  - Name: user
    User: aviral
  - Name: workdir
    Path: /home/aviral
  - CmdLine:
    - mkdir -p /home/aviral/library
    Name: run
    PrependShell: true
  - Env:
    - Key: R_LIBS_USER
      Value: /home/aviral/library
    Name: env
  - Env:
    - Key: R_KEEP_PKG_SOURCE
      Value: "1"
    Name: env
  - Env:
    - Key: R_ENABLE_JIT
      Value: "0"
    Name: env
  - Env:
    - Key: R_COMPILE_PKGS
      Value: "0"
    Name: env
  - Env:
    - Key: R_DISABLE_BYTECODE
      Value: "1"
    Name: env
  - Env:
    - Key: OMP_NUM_THREADS
      Value: "1"
    Name: env
  - CmdLine:
    - git clone --branch oopsla-2019-study-of-laziness-v1 https://github.com/PRL-PRG/R-dyntrace.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd R-dyntrace && ./build
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --branch oopsla-2019-study-of-laziness-v1 https://github.com/aviralg/promisedyntracer.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd promisedyntracer && make
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --branch r-3.5.0 https://github.com/PRL-PRG/promise-dyntracing-experiment.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd promise-dyntracing-experiment && xvfb-run make install-dependencies DEPENDENCIES_FILEPATH=scripts/package-dependencies.txt
      && rm -rf *.out
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /home/aviral/
  - CmdLine:
    - /home/aviral/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:buster
  Name: ""
  Platform: ""
  SourceCode: FROM debian:buster
