MetaArgs: null
Stages:
- BaseName: kibana:6.6.1
  Commands:
  - Env:
    - Key: SEARCH_GUARD_KIBANA_MAJOR
      Value: '"6"'
    Name: env
  - Env:
    - Key: SEARCH_GUARD_KIBANA_VERSION
      Value: '"6.6.1-18.1"'
    Name: env
  - Env:
    - Key: SEARCH_GUARD_KIBANA_ZIP
      Value: '"/tmp/search-guard-kibana-plugin-${SEARCH_GUARD_KIBANA_VERSION}.zip"'
    Name: env
  - CmdLine:
    - curl -o "${SEARCH_GUARD_KIBANA_ZIP}"     "https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-kibana-plugin/${SEARCH_GUARD_KIBANA_VERSION}/search-guard-kibana-plugin-${SEARCH_GUARD_KIBANA_VERSION}.zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - bin/kibana-plugin install "file://${SEARCH_GUARD_KIBANA_ZIP}"
    Name: run
    PrependShell: true
  From:
    Image: kibana:6.6.1
  Name: ""
  Platform: ""
  SourceCode: FROM kibana:6.6.1
