MetaArgs: null
Stages:
- BaseName: registry:2.6.2
  Commands:
  - Maintainer: Tang Jiujun <jiujun.tang@gmail.com>
    Name: maintainer
  - CmdLine:
    - set -ex && {         echo 'http://mirrors.aliyun.com/alpine/v3.4/main';         echo
      'http://mirrors.aliyun.com/alpine/v3.4/community';     } > /etc/apk/repositories
      &&     apk update && apk add findutils curl bash && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: registry:2.6.2
  Name: ""
  Platform: ""
  SourceCode: FROM registry:2.6.2
