MetaArgs: null
Stages:
- BaseName: mariadb:10.4
  Commands:
  - CmdLine:
    - touch /var/log/mysql/mariadb-slow.log         && touch /var/log/mysql/mariadb.err         &&
      chown mysql:adm /var/log/mysql/mariadb.err         && chown mysql:adm /var/log/mysql/mariadb-slow.log         &&
      chown mysql:adm /var/log/mysql         && chown root:root /var/log         &&
      chmod 0640 /var/log/mysql/mariadb.err         && chmod 0640 /var/log/mysql/mariadb-slow.log         &&
      chmod 0750 /var/log/mysql         && chmod 0775 /var/log         && chmod 0755
      /var
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/*
    Name: run
    PrependShell: true
  From:
    Image: mariadb:10.4
  Name: ""
  Platform: ""
  SourceCode: FROM mariadb:10.4
