MetaArgs: null
Stages:
- BaseName: circleci/node:8.12.0
  Commands:
  - CmdLine:
    - curl -sL https://install.meteor.com | sh
    Name: run
    PrependShell: true
  - CmdLine:
    - export METEOR_ALLOW_SUPERUSER=true
    Name: run
    PrependShell: true
  From:
    Image: circleci/node:8.12.0
  Name: ""
  Platform: ""
  SourceCode: FROM circleci/node:8.12.0
