MetaArgs: null
Stages:
- BaseName: postgres:11
  Commands:
  - Labels:
    - Key: Maintainer
      Value: '"Ruth Waiganjo <ruthnwaiganjo@gmail.com>"'
    Name: label
  - CmdLine:
    - apt-get update         && apt-get install -y postgresql-11-postgis-2.5         &&
      apt-get install postgresql-11-postgis-2.5-scripts         && apt-get install
      -y postgresql-11-hll         && apt-get -y install postgresql-11-cron
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /docker-entrypoint-initdb.docker
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dbextensions.sh
    - /docker-entrypoint-initdb.d/dbextensions.sh
  From:
    Image: postgres:11
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:11
