MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: Tung Ha "tunght13488@gmail.com"
    Name: maintainer
  - CmdLine:
    - apk add --update     bash     grep   && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
