MetaArgs: null
Stages:
- BaseName: ruby:2.2.3-onbuild
  Commands:
  - Name: expose
    Ports:
    - "9494"
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - ruby main.rb
    Name: cmd
    PrependShell: true
  From:
    Image: ruby:2.2.3-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.2.3-onbuild
