MetaArgs: null
Stages:
- BaseName: google/cloud-sdk:alpine
  Commands:
  - CmdLine:
    - gcloud components install kubectl --quiet
    Name: run
    PrependShell: true
  From:
    Image: google/cloud-sdk:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM google/cloud-sdk:alpine
