MetaArgs: null
Stages:
- BaseName: emby/embyserver
  Commands:
  - Maintainer: Geert
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - add_user.sh
    - /add_user.sh
  - CmdLine:
    - /add_user.sh &&               rm /add_user.sh
    Name: run
    PrependShell: true
  From:
    Image: emby/embyserver
  Name: ""
  Platform: ""
  SourceCode: FROM       emby/embyserver
