MetaArgs: null
Stages:
- BaseName: node:10.15-slim
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y   libgtk2.0-0   libnotify-dev   libgconf-2-4   libnss3   libxss1   libasound2   xvfb   git-core   &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: node:10.15-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:10.15-slim
