MetaArgs: null
Stages:
- BaseName: pritunl/archlinux
  Commands:
  - CmdLine:
    - pacman --noconfirm -Sy &&     pacman --noconfirm -S      bash     git     make     cmake     openssh     curl     wget     tar
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ~/.ssh &&     ssh-keyscan github.com >> ~/.ssh/known_hosts
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman --noconfirm -S     python
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman --noconfirm -S     bison     flex
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman --noconfirm -S     gcc
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman --noconfirm -S     clang     openmp
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman --noconfirm -S     emscripten
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: pritunl/archlinux
  Name: ""
  Platform: ""
  SourceCode: FROM pritunl/archlinux
