MetaArgs: null
Stages:
- BaseName: dockersamples/static-site
  Commands:
  - Env:
    - Key: AUTHOR
      Value: '"Junhei Kawauchi"'
    Name: env
  From:
    Image: dockersamples/static-site
  Name: ""
  Platform: ""
  SourceCode: FROM dockersamples/static-site
