MetaArgs: null
Stages:
- BaseName: node:12-alpine
  Commands:
  - Name: workdir
    Path: /build
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package-lock.json
    - tsconfig.json
    - ./
  - CmdLine:
    - npm ci
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - source
    - source
  - CmdLine:
    - node_modules/.bin/tsc
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf node_modules && npm ci --production
    Name: run
    PrependShell: true
  From:
    Image: node:12-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:12-alpine
- BaseName: node:12-alpine
  Commands:
  - Name: workdir
    Path: /app
  - Name: volume
    Volumes:
    - /app/persist
  - Name: volume
    Volumes:
    - /app/tmp
  - CmdLine:
    - apk --no-cache add fontconfig font-noto &&   fc-cache -f
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Env:
    - Key: NODE_ICU_DATA
      Value: '"node_modules/full-icu"'
    Name: env
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /build/node_modules
    - ./node_modules
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - locales
    - locales
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /build/dist
    - ./
  - CmdLine:
    - node -r source-map-support/register index.js
    Name: cmd
    PrependShell: true
  From:
    Image: node:12-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:12-alpine
