MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"freedox"'
    Name: label
  - CmdLine:
    - "echo \"http://dl-cdn.alpinelinux.org/alpine/v3.10/community/\" >> /etc/apk/repositories
      && \tapk update && \tapk upgrade && \tapk add curl bash && \tadduser noip-user
      -D -h /home/noip/ -s /bin/sh -u 2000"
    Name: run
    PrependShell: true
  - Chown: noip-user:noip-user
    From: ""
    Name: copy
    SourcesAndDest:
    - noip-update.sh
    - /home/noip/noip-update.sh
  - CmdLine:
    - chmod u+x /home/noip/noip-update.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: NOIP_INTERVAL
      Value: "5"
    Name: env
  - Name: user
    User: noip-user
  - CmdLine:
    - /bin/bash /home/noip/noip-update.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
