MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.10.3-alpine
  Commands:
  - Name: workdir
    Path: /go/src/github.com/maorfr/orca/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - apk --no-cache add git make     && make
    Name: run
    PrependShell: true
  From:
    Image: golang:1.10.3-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.10.3-alpine as builder
- BaseName: alpine:3.8
  Commands:
  - Key: HELM_VERSION
    Name: arg
    Value: v2.11.0
  - Key: HELM_OS_ARCH
    Name: arg
    Value: linux-amd64
  - CmdLine:
    - apk --no-cache add ca-certificates git bash curl     && wget -q https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-${HELM_OS_ARCH}.tar.gz     &&
      tar -zxvf helm-${HELM_VERSION}-${HELM_OS_ARCH}.tar.gz ${HELM_OS_ARCH}/helm     &&
      mv ${HELM_OS_ARCH}/helm /usr/local/bin/helm     && rm -rf ${HELM_OS_ARCH} helm-${HELM_VERSION}-${HELM_OS_ARCH}.tar.gz
    Name: run
    PrependShell: true
  - Key: LINKERD_VERSION
    Name: arg
    Value: stable-2.0.0
  - Key: LINKERD_OS
    Name: arg
    Value: linux
  - CmdLine:
    - wget -q https://github.com/linkerd/linkerd2/releases/download/${LINKERD_VERSION}/linkerd2-cli-${LINKERD_VERSION}-${LINKERD_OS}
      -O linkerd     && chmod +x linkerd     && mv linkerd /usr/local/bin/linkerd
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/maorfr/orca/bin/orca
    - /usr/local/bin/orca
  - CmdLine:
    - addgroup -g 1001 -S orca     && adduser -u 1001 -D -S -G orca orca
    Name: run
    PrependShell: true
  - Name: user
    User: orca
  - Name: workdir
    Path: /home/orca
  - CmdLine:
    - helm init -c     && helm plugin install https://github.com/chartmuseum/helm-push     &&
      helm plugin install https://github.com/maorfr/helm-inject
    Name: run
    PrependShell: true
  - CmdLine:
    - orca
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
