MetaArgs: null
Stages:
- BaseName: busybox:glibc
  Commands:
  - Maintainer: Rene Kanzler, me at renekanzler dot com
    Name: maintainer
  - CmdLine:
    - "mkdir -p /usr/local/bin \t&& wget --no-check-certificate https://raw.githubusercontent.com/cosmomill/apt-off/master/apt-off
      -O /usr/local/bin/apt-off \t&& chmod 755 /usr/local/bin/apt-off \t&& mkdir -p
      /var/lib/apt/lists \t\t&& mkdir -p /etc/apt \t&& echo \"deb http://deb.debian.org/debian/
      stable main\" > /etc/apt/sources.list \t\t&& mkdir -p /var/lib/dpkg/info \t&&
      touch /var/lib/dpkg/status"
    Name: run
    PrependShell: true
  - CmdLine:
    - "/usr/local/bin/apt-off -i bash-static \t\tlibc6 \tlibgcc1 \tlibaio1 \tlibstdc++6
      \tlibc-bin"
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/apt-off -p
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /docker-entrypoint-initdb.d
    Name: run
    PrependShell: true
  - CmdLine:
    - "ln -s /bin/bash-static /bin/bash \t\t&& ln -s /lib/x86_64-linux-gnu/libaio.so.1
      /lib/libaio.so.1 \t&& ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/libstdc++.so.6
      \t&& mkdir -p /usr/bin \t&& ln -s /bin/id /usr/bin/id \t&& ln -s /bin/ar /usr/bin/ar
      \t&& ln -s /bin/sysctl /sbin/sysctl \t\t&& mkdir -p /var/tmp/.oracle \t&& chmod
      01777 /var/tmp/.oracle"
    Name: run
    PrependShell: true
  - Expression: ARG ORACLE_RPM
    Name: onbuild
  - Env:
    - Key: ORACLE_MAJOR
      Value: 18c
    Name: env
  - Env:
    - Key: ORACLE_VERSION
      Value: 18c-1.0-1
    Name: env
  - Env:
    - Key: ORACLE_BASE
      Value: /opt/oracle
    Name: env
  - Env:
    - Key: ORACLE_HOME
      Value: /opt/oracle/product/$ORACLE_MAJOR/dbhomeXE
    Name: env
  - Env:
    - Key: ORACLE_SID
      Value: XE
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$ORACLE_HOME/bin
    Name: env
  - Expression: ADD $ORACLE_RPM /tmp/
    Name: onbuild
  - Expression: "RUN rpm -i /tmp/$ORACLE_RPM \t&& rm -f /tmp/$ORACLE_RPM"
    Name: onbuild
  - Expression: "RUN addgroup dba \t&& addgroup oinstall \t&& adduser -D -g oinstall
      -G dba -h $ORACLE_BASE -s /bin/false oracle \t\t&& mkdir -p $ORACLE_BASE/oradata
      \t&& mkdir -p $ORACLE_HOME/apex/images \t\t&& chown -R oracle:dba $ORACLE_BASE
      \t\t&& chmod 6751 $ORACLE_HOME/bin/oracle \t\t&& sed -i \"s|--no-messages|-s|\"
      /etc/init.d/oracle-xe-$ORACLE_MAJOR \t&& sed -i \"s|--direct||\" /etc/init.d/oracle-xe-$ORACLE_MAJOR
      \t&& sed -i \"s|netstat -n --tcp --listen|netstat -ntl|\" /etc/init.d/oracle-xe-$ORACLE_MAJOR
      \t&& sed -i \"s|-J-Doracle.assistants.dbca.validate.DBCredentials=false|-J-Doracle.assistants.dbca.validate.DBCredentials=false
      -J-Doracle.assistants.dbca.validate.ConfigurationParams=false|\" /etc/init.d/oracle-xe-$ORACLE_MAJOR"
    Name: onbuild
  - CmdLine:
    - echo "alias conndba='su -s \"/bin/bash\" oracle -c \"sqlplus / as sysdba\"'"
      >> /etc/bash.bashrc
    Name: run
    PrependShell: true
  - Expression: VOLUME $ORACLE_BASE/oradata $ORACLE_HOME/apex/images
    Name: onbuild
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-apex-install.sh
    - /usr/local/bin/
  - CmdLine:
    - "chmod 755 /usr/local/bin/docker-entrypoint.sh \t&& chmod 755 /usr/local/bin/docker-apex-install.sh"
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "1521"
    - "5500"
  - CmdLine:
    - ""
    Name: cmd
    PrependShell: false
  From:
    Image: busybox:glibc
  Name: ""
  Platform: ""
  SourceCode: FROM busybox:glibc
