MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: hanxi <hanxi.info@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update      && apt-get install -y locales curl wget     && apt-get -y
      install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev
      libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs
      git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev
      xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint     && rm
      -rf /var/lib/apt/lists/*     && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias
      en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.utf8
    Name: env
  - Name: workdir
    Path: /root
  - Env:
    - Key: FORCE_UNSAFE_CONFIGURE
      Value: "1"
    Name: env
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
