MetaArgs: null
Stages:
- BaseName: fbiete/centos_epel:7
  Commands:
  - Maintainer: Francisco Miguel Biete <fbiete@gmail.com>
    Name: maintainer
  - Env:
    - Key: GOLANG_VERSION
      Value: 1.4.2
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - go-wrapper
    - /usr/local/bin/
  - CmdLine:
    - yum clean all && yum install -y gcc make && curl -sSL https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz
      | tar -v -C /usr/local/src -xz && cd /usr/local/src/go/src && ./make.bash --no-clean
      -j"$(nproc)" && mkdir -p /go/src /go/bin && chmod -R 777 /go && yum -y history
      undo last && yum clean all
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /usr/local/src/go/bin:/go/bin:$PATH
    Name: env
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - Name: workdir
    Path: /go
  From:
    Image: fbiete/centos_epel:7
  Name: ""
  Platform: ""
  SourceCode: FROM fbiete/centos_epel:7
