MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.11
  Commands:
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root/
    - /
  - CmdLine:
    - /root/glinstall.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/pznginstall.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /glftpd/site
    - /glftpd/ftp-data
  - CmdLine:
    - apt-get remove -y wget unzip zip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean -y
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* /var/cache/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -arp /glftpd/ftp-data /glftpd/ftp-data-dist
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /glftpd/ftp-data/*
    Name: run
    PrependShell: true
  From:
    Image: phusion/baseimage:0.11
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.11
