MetaArgs: null
Stages:
- BaseName: maven:3.5.2-jdk-8-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /client
  - Name: workdir
    Path: /client
  - CmdLine:
    - mvn package -Dmaven.test.skip=true
    Name: run
    PrependShell: true
  From:
    Image: maven:3.5.2-jdk-8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM maven:3.5.2-jdk-8-alpine
- BaseName: java:alpine
  Commands:
  - Name: workdir
    Path: /web
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /client/target/*.jar
    - .
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - java -jar -Dcustom.server.url=$CONFIG_SERVER_URL *.jar
    Name: cmd
    PrependShell: true
  From:
    Image: java:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM java:alpine
