MetaArgs: null
Stages:
- BaseName: primehost/ubuntu-core
  Commands:
  - Maintainer: Prime-Host <info@nordloh-webdesign.de>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y lib32gcc1 lsof
    Name: run
    PrependShell: true
  - CmdLine:
    - "adduser \t--disabled-login \t--shell /bin/bash \t--gecos \"\" \tsteam"
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -a -G sudo steam
    Name: run
    PrependShell: true
  - CmdLine:
    - "mkdir /home/steam/steamcmd &&\tcd /home/steam/steamcmd &&\tcurl http://media.steampowered.com/installer/steamcmd_linux.tar.gz
      | tar -vxz"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get --purge autoremove -y
    Name: run
    PrependShell: true
  From:
    Image: primehost/ubuntu-core
  Name: ""
  Platform: ""
  SourceCode: FROM primehost/ubuntu-core
