MetaArgs: null
Stages:
- As: main
  BaseName: golang:1.10-alpine
  Commands:
  - Name: workdir
    Path: /go/src/github.com/tonistiigi/copy
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Env:
    - Key: CGO_ENABLED
      Value: "0"
    Name: env
  - CmdLine:
    - go build -o /copy -ldflags '-s -w' github.com/tonistiigi/copy/cmd/copy
    Name: run
    PrependShell: true
  From:
    Image: golang:1.10-alpine
  Name: main
  Platform: ""
  SourceCode: from golang:1.10-alpine AS main
- As: upx
  BaseName: gruebel/upx
  Commands:
  - Chown: ""
    From: main
    Name: copy
    SourcesAndDest:
    - /copy
    - /copy
  - CmdLine:
    - upx
    - /copy
    Name: run
    PrependShell: false
  From:
    Image: gruebel/upx
  Name: upx
  Platform: ""
  SourceCode: from gruebel/upx AS upx
- As: wget
  BaseName: alpine
  Commands:
  - Name: workdir
    Path: /out
  - CmdLine:
    - apk add --no-cache wget
    Name: run
    PrependShell: true
  From:
    Image: alpine
  Name: wget
  Platform: ""
  SourceCode: from alpine AS wget
- As: cp
  BaseName: wget
  Commands:
  - CmdLine:
    - wget http://s.minos.io/archive/bifrost/x86_64/coreutils-7.6-5.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvf coreutils-7.6-5.tar.gz -C /
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 2
      Named: wget
  Name: cp
  Platform: ""
  SourceCode: from wget AS cp
- As: tar
  BaseName: wget
  Commands:
  - CmdLine:
    - wget http://s.minos.io/archive/bifrost/x86_64/tar-1.23-1.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvf tar-1.23-1.tar.gz -C /out
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 2
      Named: wget
  Name: tar
  Platform: ""
  SourceCode: from wget AS tar
- As: gz
  BaseName: wget
  Commands:
  - CmdLine:
    - wget http://s.minos.io/archive/bifrost/x86_64/gzip-1.4-1.tar.bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvf gzip-1.4-1.tar.bz2 -C /out
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 2
      Named: wget
  Name: gz
  Platform: ""
  SourceCode: from wget AS gz
- As: bz
  BaseName: wget
  Commands:
  - CmdLine:
    - wget http://s.minos.io/archive/bifrost/x86_64/bzip2-bin-1.0.5-1.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvf bzip2-bin-1.0.5-1.tar.gz -C /out
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 2
      Named: wget
  Name: bz
  Platform: ""
  SourceCode: from wget AS bz
- As: xz
  BaseName: wget
  Commands:
  - CmdLine:
    - wget http://s.minos.io/archive/bifrost/x86_64/xz-5.0.3-1.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvf xz-5.0.3-1.tar.gz  -C /out
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 2
      Named: wget
  Name: xz
  Platform: ""
  SourceCode: from wget AS xz
- As: release
  BaseName: scratch
  Commands:
  - Chown: ""
    From: upx
    Name: copy
    SourcesAndDest:
    - /copy
    - /bin/
  - Chown: ""
    From: tar
    Name: copy
    SourcesAndDest:
    - /out/bin
    - /bin/
  - Chown: ""
    From: gz
    Name: copy
    SourcesAndDest:
    - /out/bin
    - /bin/
  - Chown: ""
    From: bz
    Name: copy
    SourcesAndDest:
    - /out/bin
    - /bin/
  - Chown: ""
    From: xz
    Name: copy
    SourcesAndDest:
    - /out/usr/bin
    - /bin/
  - CmdLine:
    - /bin/copy
    Name: entrypoint
    PrependShell: false
  From:
    Scratch: true
  Name: release
  Platform: ""
  SourceCode: from scratch AS release
- As: dev-env
  BaseName: alpine
  Commands:
  - Chown: ""
    From: release
    Name: copy
    SourcesAndDest:
    - /bin/
    - /bin/
  - CmdLine:
    - ash
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: dev-env
  Platform: ""
  SourceCode: from alpine as dev-env
- BaseName: release
  Commands: null
  From:
    Stage:
      Index: 8
      Named: release
  Name: ""
  Platform: ""
  SourceCode: from release
