MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Brian Steere <dianoga7@3dgo.net>
    Name: maintainer
  - CmdLine:
    - apt-get update -y && apt-get install -y curl jq bc bash
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
