MetaArgs: null
Stages:
- BaseName: l.gcr.io/google/ruby:latest
  Commands:
  - Maintainer: Julio Lustosa "contato@juliolustosa.com.br"
    Name: maintainer
  - CmdLine:
    - apt-get update -qq && apt-get install -y   build-essential   libpq-dev   nodejs   openssh-client   git-core   curl   wget   mysql-client   postgresql-client
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install bundler
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install rack
    Name: run
    PrependShell: true
  - Env:
    - Key: APP_HOME
      Value: /app
    Name: env
  - Name: workdir
    Path: /app
  - CmdLine:
    - mkdir -p /scripts
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker-scripts
    - /scripts
  - Expression: COPY . /app/
    Name: onbuild
  - Expression: RUN ruby /scripts/config.rb
    Name: onbuild
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - ruby
    - /scripts/config.rb
    Name: cmd
    PrependShell: false
  - CmdLine:
    - bundle
    - exec
    - rackup
    - --port=8080
    Name: entrypoint
    PrependShell: false
  From:
    Image: l.gcr.io/google/ruby:latest
  Name: ""
  Platform: ""
  SourceCode: FROM l.gcr.io/google/ruby:latest
