MetaArgs: null
Stages:
- As: builder
  BaseName: alpine:3.7
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /go/src/github.com/nadilas/godaddy-oc-updater
  - CmdLine:
    - "apk --no-cache add -t build-deps build-base go git curl \t&& apk --no-cache
      add ca-certificates \t&& export GOPATH=/go && mkdir -p /go/bin && export PATH=$PATH:/go/bin
      \t&& curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      \t&& cd /go/src/github.com/nadilas/godaddy-oc-updater \t&& export GOPATH=/go
      \t&& git config --global http.https://gopkg.in.followRedirects true \t&& dep
      ensure \t&& go build -ldflags \"-X main.Version=$(cat VERSION)\" -o /bin/ip-updater
      \t&& rm -rf /go \t&& apk del --purge build-deps"
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.7
  Name: builder
  Platform: ""
  SourceCode: FROM alpine:3.7 AS builder
- BaseName: alpine:3.7
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /bin/ip-updater
    - /bin/ip-updater
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /etc/ssl/certs/ca-certificates.crt
    - /etc/ssl/certs/ca-certificates.crt
  - CmdLine:
    - /bin/ip-updater
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
