MetaArgs: null
Stages:
- BaseName: ruby:2.5-alpine
  Commands:
  - CmdLine:
    - bundle config --global frozen 1 &&   bundle config --global build.nokogiri --use-system-libraries
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - Gemfile.lock
    - package.json
    - /usr/src/app/
  - CmdLine:
    - apk --update add --virtual .build-deps         build-base g++ make       &&
      apk add yarn --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community       &&
      apk add --no-cache         libxml2 libxslt-dev git       && bundle install --jobs
      `grep -c '^processor' /proc/cpuinfo`       && apk del .build-deps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /usr/src/app/
  - CmdLine:
    - yarn install --ignore-scripts
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/app
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - puma
    - -t
    - "16:16"
    - -p
    - "3000"
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.5-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5-alpine
