MetaArgs: null
Stages:
- BaseName: nginx:alpine
  Commands:
  - Labels:
    - Key: '"author"'
      Value: '"Francisco Chaves"'
    Name: label
  - Labels:
    - Key: '"website"'
      Value: '"https://franciscochaves.com.br"'
    Name: label
  - Labels:
    - Key: '"version"'
      Value: '"2.0"'
    Name: label
  - Labels:
    - Key: '"description"'
      Value: '"website"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./index.html
    - /usr/share/nginx/html/index.html
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
