MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: '"Florian Baader <florian.baader@selectcode.de>"'
    Name: maintainer
  - CmdLine:
    - apk add wget --no-cache
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/FairwindsOps/polaris/releases/download/0.4.0/polaris_0.4.0_Linux_x86_64.tar.gz
      -O - | tar -xz -C /usr/local/bin/ && chmod +x /usr/local/bin/polaris
    Name: run
    PrependShell: true
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
