MetaArgs: null
Stages:
- As: base
  BaseName: python:alpine3.10
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Denis O''Meally (domeally@coh.org)"'
    - Key: version
      Value: '"1.2"'
    Name: label
  From:
    Image: python:alpine3.10
  Name: base
  Platform: ""
  SourceCode: FROM python:alpine3.10 as base
- As: builder
  BaseName: base
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./PLEK.1.2.tar.gz
    - /
  - CmdLine:
    - tar zxf PLEK.1.2.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - cd PLEK.1.2
    Name: run
    PrependShell: true
  - CmdLine:
    - '[''PLEK_setup.py'']'
    Name: cmd
    PrependShell: true
  From:
    Stage:
      Index: 0
      Named: base
  Name: builder
  Platform: ""
  SourceCode: FROM base as builder
- BaseName: base
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /PLEK.1.2
    - /usr/local/bin
  - CmdLine:
    - apk --no-cache add procps bash
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /usr/local/bin/PLEK*
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 0
      Named: base
  Name: ""
  Platform: ""
  SourceCode: FROM base
