MetaArgs: null
Stages:
- BaseName: node:8
  Commands:
  - CmdLine:
    - npm install -g yarn@1.3.2
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn global add gatsby-cli gatsby-dev-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/gatsbyjs/gatsby.git
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/github/hub/releases/download/v2.3.0-pre10/hub-linux-amd64-2.3.0-pre10.tgz
      --directory-prefix /usr/local/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - cd gatsby && gatsby-dev --set-path-to-repo . && yarn bootstrap
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p gatsby/infrastructure
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - gatsby/infrastructure/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - yarn.lock
    - gatsby/infrastructure/
  - CmdLine:
    - cd gatsby/infrastructure && yarn
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - build-site.js
    - gatsby/infrastructure/
  - CmdLine:
    - node
    - gatsby/infrastructure/build-site.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:8
  Name: ""
  Platform: ""
  SourceCode: FROM node:8
