MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Labels:
    - Key: description
      Value: = "Minimal image for the NBIS reproducible research course."
    Name: label
  - Maintainer: '"Leif Wigge" leif.wigge@scilifelab.se'
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get install -y --no-install-recommends bzip2                                                ca-certificates                                                curl                                                fontconfig                                                git                                                language-pack-en                                                tzdata                                                vim                                                wget     &&
      apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh -O
      &&     bash Miniconda3-4.6.14-Linux-x86_64.sh -bf -p /opt/miniconda3/ &&     rm
      Miniconda3-4.6.14-Linux-x86_64.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"/opt/miniconda3/bin:${PATH}"'
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_LANG
      Value: en_US.UTF-8
    Name: env
  - Name: shell
    Shell:
    - /bin/bash
    - -c
  - Name: workdir
    Path: /course
  - Name: expose
    Ports:
    - "8888"
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
