MetaArgs: null
Stages:
- BaseName: python:2-alpine3.6
  Commands:
  - Maintainer: David Verdejo <david.verdejo@bluekiri.com>
    Name: maintainer
  - CmdLine:
    - "apk update &&     apk upgrade &&     apk add --update --no-cache \tbuild-base
      \tcurl \tcurl-dev \tjpeg-dev \topenssl-dev &&     pip install --use-wheel --no-cache-dir
      \tenvtpl==0.5.3 \tthumbor==6.2.0 &&     apk del \tbuild-base \tcurl-dev &&     rm
      -rf /var/cache/apk/* &&     rm -rf /tmp/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /usr/src/app
    Name: env
  - Env:
    - Key: SHELL
      Value: bash
    Name: env
  - Env:
    - Key: WORKON_HOME
      Value: /usr/src/app
    Name: env
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/thumbor.conf.tpl
    - /usr/src/app/thumbor.conf.tpl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - Health:
      Interval: 5000000000
      Test:
      - CMD-SHELL
      - curl -f http://localhost:8000/healthcheck || exit 1
      Timeout: 3000000000
    Name: healthcheck
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - thumbor
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "8000"
  From:
    Image: python:2-alpine3.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:2-alpine3.6
