MetaArgs: null
Stages:
- BaseName: ruby:2.1
  Commands:
  - Maintainer: snowdream <yanghui1986527@gmail.com>
    Name: maintainer
  - CmdLine:
    - gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/
    Name: run
    PrependShell: true
  - CmdLine:
    - bundle config mirror.https://rubygems.org https://gems.ruby-china.org
    Name: run
    PrependShell: true
  From:
    Image: ruby:2.1
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.1
