MetaArgs: null
Stages:
- BaseName: node:6.3.0
  Commands:
  - Maintainer: Nicolas Borboën <nicolas.borboen@epfl.ch>
    Name: maintainer
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./index.js
    - /app/index.js
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /app/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:6.3.0
  Name: ""
  Platform: ""
  SourceCode: FROM node:6.3.0
