MetaArgs: null
Stages:
- BaseName: linuxserver/tautulli:latest
  Commands:
  - Env:
    - Key: LAKKRIS_SERVICE
      Value: '"tautulli"'
    - Key: LAKKRIS_ICON
      Value: '"plugins/images/tabs/tautulli.png"'
    - Key: LAKKRIS_PORT
      Value: '"8181"'
    - Key: LAKKRIS_CONFIGFILE
      Value: '"/config/config.ini"'
    - Key: LAKKRIS_SERVERNAME
      Value: '"lostlakkris"'
    Name: env
  - Name: expose
    Ports:
    - "7946"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/serf_0.8.1_amd64
    - /usr/sbin/serf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/jq_1.6_amd64
    - /usr/sbin/jq
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/templater
    - /usr/sbin/templater
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - lakkris/
    - /
  From:
    Image: linuxserver/tautulli:latest
  Name: ""
  Platform: ""
  SourceCode: FROM linuxserver/tautulli:latest
