MetaArgs: null
Stages:
- BaseName: lsioarmhf/unifi
  Commands:
  - Maintainer: mayeu
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root/
    - /
  - Name: expose
    Ports:
    - 10001/udp
    - 3478/udp
    - "8080"
    - "8081"
    - "8443"
    - "8843"
    - "8880"
  From:
    Image: lsioarmhf/unifi
  Name: ""
  Platform: ""
  SourceCode: FROM lsioarmhf/unifi
