MetaArgs: null
Stages:
- BaseName: bitnami/minideb:jessie
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Razmik Avetikyan <razmik.avetikyan@fouraitch.com>"'
    Name: label
  - CmdLine:
    - install_packages apt-transport-https cron curl zip lsb-release unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/4.0 main" |
      tee /etc/apt/sources.list.d/mongodb-org-4.0.list
    Name: run
    PrependShell: true
  - CmdLine:
    - install_packages mongodb-org-shell mongodb-org-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s)
      main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
    Name: run
    PrependShell: true
  - CmdLine:
    - curl --insecure https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key
      add -
    Name: run
    PrependShell: true
  - CmdLine:
    - install_packages google-cloud-sdk
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /backup /restore
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - migrate_backup_gs.sh
    - restore.sh
    - run.sh
    - tmp_mongo_user.js
    - /
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: CRON_TIME
      Value: '''0 0 * * *'''
    Name: env
  - CmdLine:
    - /bin/bash
    - /run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: bitnami/minideb:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM bitnami/minideb:jessie
