MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - CmdLine:
    - apk add --no-cache gcc musl-dev hiredis-dev make
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /src
  - CmdLine:
    - make
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk --no-cache add ca-certificates
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /src
    - .
  - CmdLine:
    - ./vulcan
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
