MetaArgs: null
Stages:
- BaseName: gliderlabs/alpine:3.2
  Commands:
  - CmdLine:
    - apk-install git bash
    Name: run
    PrependShell: true
  - CmdLine:
    - apk-install nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - apk-install python3 python3-dev build-base     && pip3 install virtualenv     &&
      echo "Dockerfile" >> /etc/buildfiles     && echo ".onbuild" >> /etc/buildfiles     &&
      echo "requirements.txt" >> /etc/buildfiles
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g webpack
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /app/
  - CmdLine:
    - npm install && rm /app/package.json
    Name: run
    PrependShell: true
  - Expression: COPY . /app
    Name: onbuild
  - Expression: RUN /app/.onbuild || true
    Name: onbuild
  - Expression: RUN virtualenv /env && /env/bin/pip install -r /app/requirements.txt
    Name: onbuild
  - Expression: RUN npm install
    Name: onbuild
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /env/bin/python
    - main.py
    Name: cmd
    PrependShell: false
  From:
    Image: gliderlabs/alpine:3.2
  Name: ""
  Platform: ""
  SourceCode: FROM gliderlabs/alpine:3.2
