MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Maintainer: Sean Johnson <pirogoeth@maio.me>
    Name: maintainer
  - Name: volume
    Volumes:
    - /config
    - /kern
  - Chown: ""
    Name: add
    SourcesAndDest:
    - build
    - /build
  - CmdLine:
    - run-parts --report --exit-on-error /build/parts && rm -rf /build
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - CmdLine:
    - /data/build.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
