MetaArgs: null
Stages:
- BaseName: google/debian:wheezy
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y -qq --no-install-recommends wget unzip
      python php5-mysql php5-cli php5-cgi openjdk-7-jre-headless openssh-client python-openssl
      && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip && unzip
      google-cloud-sdk.zip && rm google-cloud-sdk.zip
    Name: run
    PrependShell: true
  - Env:
    - Key: CLOUDSDK_PYTHON_SITEPACKAGES
      Value: "1"
    Name: env
  - CmdLine:
    - google-cloud-sdk/install.sh --usage-reporting=true --path-update=true --bash-completion=true
      --rc-path=/.bashrc --disable-installation-options
    Name: run
    PrependShell: true
  - CmdLine:
    - google-cloud-sdk/bin/gcloud --quiet components update pkg-go pkg-python pkg-java
      preview alpha beta app
    Name: run
    PrependShell: true
  - CmdLine:
    - google-cloud-sdk/bin/gcloud --quiet config set component_manager/disable_update_check
      true
    Name: run
    PrependShell: true
  - CmdLine:
    - google-cloud-sdk/bin/gcloud components update -qq
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://get.docker.com/builds/Linux/x86_64/docker-1.6.2 -O /usr/bin/docker     &&
      chmod +x /usr/bin/docker
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /.ssh
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /google-cloud-sdk/bin:$PATH
    Name: env
  - Env:
    - Key: HOME
      Value: /
    Name: env
  - Name: volume
    Volumes:
    - /.config
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: google/debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM google/debian:wheezy
