MetaArgs:
- DefaultValue: 1.25.0-rc1
  Key: DOCKER_COMPOSE_VERSION
  ProvidedValue: null
  Value: 1.25.0-rc1
Stages:
- BaseName: alpine:latest
  Commands:
  - Key: DOCKER_VERSION
    Name: arg
    Value: 18.09.8
  - Key: HELM_VERSION
    Name: arg
    Value: 2.14.2
  - Key: KUBECTL_VERSION
    Name: arg
    Value: 1.15.1
  - Key: SENTRY_CLI_VERSION
    Name: arg
    Value: 1.49.0
  - Key: TERRAFORM_VERSION
    Name: arg
    Value: 0.12.6
  - CmdLine:
    - apk add --no-cache openssl
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz
      | tar -x -f - -z --strip-components=1 -v docker/docker
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - https://storage.googleapis.com/kubernetes-helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz
      | tar -x -f - -z --strip-components=1 -v linux-amd64/helm
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
      && chmod +x kubectl
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O sentry-cli https://downloads.sentry-cdn.com/sentry-cli/${SENTRY_CLI_VERSION}/sentry-cli-Linux-x86_64
      && chmod +x sentry-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip  &&
      unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip terraform
    Name: run
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
- As: docker-compose
  BaseName: docker/compose:${DOCKER_COMPOSE_VERSION}-alpine
  Commands: null
  From:
    Image: docker/compose:${DOCKER_COMPOSE_VERSION}-alpine
  Name: docker-compose
  Platform: ""
  SourceCode: FROM docker/compose:${DOCKER_COMPOSE_VERSION}-alpine AS docker-compose
- BaseName: google/cloud-sdk:255.0.0-alpine
  Commands:
  - CmdLine:
    - apk add --no-cache git lua5.3 lua-cjson lua-http openssl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - deploy-notifier.lua
    - /usr/local/bin/deploy-notifier
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - docker
    - /usr/local/bin/
  - Chown: ""
    From: docker-compose
    Name: copy
    SourcesAndDest:
    - /usr/local/bin/docker-compose
    - /usr/local/bin/docker-compose
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - helm
    - /usr/local/bin/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - kubectl
    - /usr/local/bin/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - sentry-cli
    - /usr/local/bin/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - terraform
    - /usr/local/bin/
  From:
    Image: google/cloud-sdk:255.0.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM google/cloud-sdk:255.0.0-alpine
