MetaArgs: null
Stages:
- BaseName: debian:jessie-slim
  Commands:
  - Maintainer: Extra <extra84@gmail.com>
    Name: maintainer
  - CmdLine:
    - "apt-get update \t&& DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends
      -y \t\tlsb-release \t&& apt-get remove -y \t&& rm -rf /var/cache/apt/archives/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - murmur.ini
    - /etc/murmur.tpl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - murmur.x86
    - /usr/bin/murmur
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init.sh
    - /usr/bin/init.sh
  - CmdLine:
    - "useradd -u 9000 murmur \t&& mkdir -p /data  \t&& chown murmur.murmur /data
      \t&& chmod +r /etc/murmur.tpl"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: expose
    Ports:
    - "64738"
    - 64738/udp
  - CmdLine:
    - /usr/bin/init.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie-slim
