MetaArgs: null
Stages:
- BaseName: plugins/docker
  Commands:
  - Env:
    - Key: DOCKER_HOST
      Value: tcp://172.17.0.1:2375
    Name: env
  From:
    Image: plugins/docker
  Name: ""
  Platform: ""
  SourceCode: FROM plugins/docker
