MetaArgs: null
Stages:
- BaseName: jleight/phusion-mono:3.12.0
  Commands:
  - Maintainer: Jonathon Leight <jonathon.leight@jleight.com>
    Name: maintainer
  - CmdLine:
    - set -x   && apt-get update   && apt-get install -y mediainfo libsqlite3-dev
      libgdiplus libwebp-dev unzip   && apt-get clean   && rm -rf /var/lib/apt/lists/*     /tmp/*     /var/tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: APP_HOME
      Value: /opt/mediabrowser
    Name: env
  - Env:
    - Key: APP_VERSION
      Value: master
    Name: env
  - Env:
    - Key: APP_BASEURL
      Value: https://github.com/MediaBrowser/MediaBrowser.Releases/raw
    Name: env
  - Env:
    - Key: APP_PKGNAME
      Value: MediaBrowser.Mono.zip
    Name: env
  - Env:
    - Key: APP_URL
      Value: ${APP_BASEURL}/${APP_VERSION}/Server/${APP_PKGNAME}
    Name: env
  - CmdLine:
    - set -x   && groupadd -r -g 300 mediabrowser   && useradd -r -u 300 -g mediabrowser
      mediabrowser   && mkdir -p "${APP_HOME}"   && curl -kL -o /tmp/mb.zip "${APP_URL}"   &&
      unzip -d "${APP_HOME}" /tmp/mb.zip   && rm -f /tmp/mb.zip   && chown -R mediabrowser:mediabrowser
      "${APP_HOME}"
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mediabrowser-service.sh
    - /etc/service/mediabrowser/run
  - Name: expose
    Ports:
    - 1900/udp
  - Name: expose
    Ports:
    - 7359/udp
  - Name: expose
    Ports:
    - 8096/tcp
  - Name: volume
    Volumes:
    - /opt/mediabrowser
  From:
    Image: jleight/phusion-mono:3.12.0
  Name: ""
  Platform: ""
  SourceCode: FROM jleight/phusion-mono:3.12.0
