MetaArgs: null
Stages:
- BaseName: golang:1.8-onbuild
  Commands:
  - CmdLine:
    - /go/bin/app
    Name: entrypoint
    PrependShell: false
  From:
    Image: golang:1.8-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.8-onbuild
