MetaArgs: null
Stages:
- BaseName: golang:latest
  Commands:
  - CmdLine:
    - go get gopkg.in/go-playground/validator.v9     golang.org/x/lint/golint     go.uber.org/zap     github.com/reddotpay/logger     github.com/stretchr/testify/assert     github.com/hashicorp/go-retryablehttp
    Name: run
    PrependShell: true
  From:
    Image: golang:latest
  Name: ""
  Platform: ""
  SourceCode: FROM golang:latest
