MetaArgs: null
Stages:
- BaseName: golang:1.12-alpine
  Commands:
  - Name: workdir
    Path: /go/src/zxq.co/ripple/rippleapi
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get -d -v ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 go install -v ./...
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.12-alpine
- BaseName: alpine
  Commands:
  - Name: workdir
    Path: /rippleapi/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /go/bin/rippleapi
    - ./
  - CmdLine:
    - mkdir ~/.config && touch ~/.config/ripple_license_agreed
    Name: run
    PrependShell: true
  - CmdLine:
    - ./rippleapi
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./entrypoint.sh
    - .
  - CmdLine:
    - chmod +x entrypoint.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: OSUAPIKEY
      Value: pleaseuseme
    Name: env
  - Env:
    - Key: MYSQL_ROOT_PASSWORD
      Value: changeme
    Name: env
  - Env:
    - Key: APISECRET
      Value: Potato
    Name: env
  - Name: expose
    Ports:
    - "40001"
  - CmdLine:
    - ./entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ./rippleapi
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
