MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - CmdLine:
    - apk add --no-cache samba samba-common-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser -SDH samba samba
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - smb.conf
    - /etc/samba/smb.conf
  - Name: expose
    Ports:
    - "137"
    - "138"
    - "139"
    - "445"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - samba.sh
    - /usr/local/bin/samba.sh
  - CmdLine:
    - /usr/local/bin/samba.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -FS
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
