MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - Name: workdir
    Path: /app
  - Env:
    - Key: LC_ALL
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y software-properties-common vim curl
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:jonathonf/python-3.6
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - python3.6 -m pip install pip --upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - python3.6 -m pip install wheel pipenv gunicorn
    Name: run
    PrependShell: true
  - CmdLine:
    - pipenv install --three --system --deploy --ignore-pipfile
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r flask && useradd -r -g flask flask
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R flask /app
    Name: run
    PrependShell: true
  - Env:
    - Key: NVM_DIR
      Value: /usr/local/nvm
    Name: env
  - Env:
    - Key: NODE_VERSION
      Value: "6.12"
    Name: env
  - Env:
    - Key: NODE_PATH
      Value: $NVM_DIR/v$NODE_VERSION/lib/node_modules
    Name: env
  - Env:
    - Key: PATH
      Value: $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
    Name: env
  - Env:
    - Key: FLASK_APP
      Value: autoapp.py
    Name: env
  - CmdLine:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh
      | bash     && . $NVM_DIR/nvm.sh     && nvm install $NODE_VERSION     && nvm
      alias default $NODE_VERSION     && nvm use default     && npm install     &&
      npm run build
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
