MetaArgs: null
Stages:
- BaseName: docker/compose:1.23.2
  Commands:
  - Env:
    - Key: BUILD_DEPS
      Value: '"gettext"'
    Name: env
  - CmdLine:
    - set -x &&     apk add --update gettext &&     apk add --virtual build_deps gettext
      &&      apk add --no-cache curl bash gawk sed grep bc coreutils ncurses &&     cp
      /usr/bin/envsubst /usr/local/bin/envsubst &&     apk del build_deps
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /habidat
  - Name: workdir
    Path: /habidat
  - CmdLine:
    - rm setup.env && chmod +x habidat.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - habidat.sh
    - /usr/local/bin/docker-entrypoint.sh
  - CmdLine:
    - chmod +x /usr/local/bin/docker-entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - 'ln -s usr/local/bin/docker-entrypoint.sh / # backwards compat'
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: docker/compose:1.23.2
  Name: ""
  Platform: ""
  SourceCode: FROM docker/compose:1.23.2
