MetaArgs: null
Stages:
- BaseName: riccardoblb/jdk8:amd64
  Commands:
  - Maintainer: Riccardo Balbo <riccardo0blb@gmail.com>
    Name: maintainer
  - Name: user
    User: root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init.sh
    - /init.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - updater.sh
    - /updater.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - reddconomy_updater.sh
    - /reddconomy_updater.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisord.conf
  - CmdLine:
    - apk add --update curl openssl unzip supervisor bash&&chmod +x /init.sh &&chmod
      +x /updater.sh &&chmod +x /reddconomy_updater.sh &&mkdir -p /minecraft &&chown
      java:java /minecraft -Rvf
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/supervisord
    - --nodaemon
    - --configuration
    - /etc/supervisord.conf
    Name: entrypoint
    PrependShell: false
  From:
    Image: riccardoblb/jdk8:amd64
  Name: ""
  Platform: ""
  SourceCode: FROM riccardoblb/jdk8:amd64
