MetaArgs: null
Stages:
- BaseName: fluendo/docker-base-ubuntu-hardy-i386
  Commands:
  - Maintainer: fluendo
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - mkdir /worker
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 777 /worker
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /worker
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y &&     apt-get install -y         lsb-release         build-essential         curl
      wget         ca-certificates         libncursesw5-dev         libreadline5-dev         libssl-dev         libgdbm-dev         libbz2-dev         libc6-dev         libsqlite3-dev         tk-dev
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://www.openssl.org/source/openssl-1.0.2o.tar.gz
    - /worker
  - CmdLine:
    - tar -xvzf /worker/openssl-1.0.2o.tar.gz   && cd /worker/openssl-1.0.2o/   &&
      ./Configure linux-generic32 --prefix=/usr/local shared   && make   && make install   &&
      rm /worker/openssl-1.0.2o.tar.gz   && rm -r /worker/openssl-1.0.2o
    Name: run
    PrependShell: true
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/local/lib:${LD_LIBRARY_PATH}
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - python2.7/platform.py
    - .
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
    - /worker
  - CmdLine:
    - tar -xzf /worker/Python-2.7.12.tgz   && cd /worker/Python-2.7.12/   && ./configure
      --prefix=/usr/local  && make   && make install   && mv ../platform.py /usr/local/lib/python2.7/   &&
      python -m ensurepip --upgrade   && rm /worker/Python-2.7.12.tgz   && rm -r /worker/Python-2.7.12
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install requests tinys3
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install incremental
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install buildbot-worker
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-client                     libxml2-dev                     libexpat1-dev                     gettext
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://curl.haxx.se/download/curl-7.27.0.tar.gz
    - /worker
  - CmdLine:
    - tar -zxvf curl-7.27.0.tar.gz     && cd curl-7.27.0    && ./configure --with-ssl=/usr/local     &&
      make     && make install     && rm /worker/curl-7.27.0.tar.gz     && rm -r /worker/curl-7.27.0
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/git/git/archive/v2.4.5.tar.gz
    - /worker
  - CmdLine:
    - tar -xzf /worker/v2.4.5.tar.gz     && cd /worker/git-2.4.5 && make OPENSSLDIR=/usr/local/
      prefix=/usr/local install     && rm /worker/v2.4.5.tar.gz     && rm -r /worker/git-2.4.5
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://ftp.gnu.org/gnu/wget/wget-1.16.tar.gz
    - /worker
  - CmdLine:
    - tar -zxvf wget-1.16.tar.gz     && cd wget-1.16     && ./configure --with-ssl=openssl
      --prefix=/usr/local     && make     && make install     && rm /worker/wget-1.16.tar.gz     &&
      rm -r /worker/wget-1.16
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libapr1                        libapr1-dev                        libaprutil1-dev                        unzip
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://www.sqlite.org/sqlite-amalgamation-3071501.zip
    - /worker
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://archive.apache.org/dist/subversion/subversion-1.8.8.tar.gz
    - /worker
  - CmdLine:
    - tar -zxvf subversion-1.8.8.tar.gz     && unzip sqlite-amalgamation-3071501.zip
      -d /worker/subversion-1.8.8/     && cd subversion-1.8.8     && mv sqlite-amalgamation-3071501
      sqlite-amalgamation     && ./configure --with-openssl --prefix=/usr/local     &&
      make     && make install     && rm /worker/sqlite-amalgamation-3071501.zip     &&
      rm /worker/subversion-1.8.8.tar.gz     && rm -r /worker/subversion-1.8.8
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "secure_protocol=TLSv1_2" > /usr/local/etc/wgetrc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install sudo libnss-ldap
    Name: run
    PrependShell: true
  - CmdLine:
    - linux32
    - '-'
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apt-get install -y autotools-dev automake libtool cmake bison flex texinfo doxygen                        yasm
      pkg-config gtk-doc-tools                        libxv-dev libpulse-dev python-dev
      libxi-dev                        x11proto-record-dev libxrender-dev libgl1-mesa-dev
      libxfixes-dev libxdamage-dev                        libxcomposite-dev libasound2-dev
      libxml-simple-perl debhelper                        devscripts transfig gperf
      libdbus-glib-1-dev libgtk2.0-dev                        fakeroot git-core
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - .
  - CmdLine:
    - ./run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: fluendo/docker-base-ubuntu-hardy-i386
  Name: ""
  Platform: ""
  SourceCode: FROM fluendo/docker-base-ubuntu-hardy-i386
