MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - CmdLine:
    - mkdir /consul-assets
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /consul-assets
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /consul-assets
  - CmdLine:
    - npm install .
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
