MetaArgs: null
Stages:
- BaseName: php:7
  Commands:
  - CmdLine:
    - apt-get update     && apt-get install -y cron     && apt-get clean     && apt-get
      autoremove -y     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkfifo --mode 0666 /var/log/cron.log
    Name: run
    PrependShell: true
  - CmdLine:
    - sed --regexp-extended --in-place     's/^session\s+required\s+pam_loginuid.so$/session
      optional pam_loginuid.so/'     /etc/pam.d/cron
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start-cron
    - /usr/sbin
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - mercury.php
    - /mercury.php
  - Env:
    - Key: SERVER_HOST
      Value: influxdb
    Name: env
  - Env:
    - Key: SERVER_PORT
      Value: "8086"
    Name: env
  - Env:
    - Key: DB_NAME
      Value: openhab_db
    Name: env
  - Env:
    - Key: MEASUREMENT
      Value: ElectricMeter
    Name: env
  - CmdLine:
    - start-cron "\* \* \* \* \* /usr/local/bin/php -f /mercury.php >> /var/log/cron.log
      2>&1"
    Name: cmd
    PrependShell: true
  From:
    Image: php:7
  Name: ""
  Platform: ""
  SourceCode: FROM php:7
