MetaArgs: null
Stages:
- As: build
  BaseName: golang:1.12-alpine
  Commands:
  - CmdLine:
    - apk update && apk add git
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /go/src/github.com/nsmithuk/local-kms
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /go/src/github.com/nsmithuk/local-kms
  - Name: workdir
    Path: /go/src/github.com/nsmithuk/local-kms
  - CmdLine:
    - go get -u github.com/golang/dep/cmd/dep
    Name: run
    PrependShell: true
  - CmdLine:
    - dep ensure && go install
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12-alpine
  Name: build
  Platform: ""
  SourceCode: FROM golang:1.12-alpine AS build
- BaseName: alpine
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /go/bin/local-kms
    - /usr/local/bin/local-kms
  - CmdLine:
    - mkdir /init
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /data
    Name: run
    PrependShell: true
  - Env:
    - Key: KMS_ACCOUNT_ID
      Value: "111122223333"
    Name: env
  - Env:
    - Key: KMS_REGION
      Value: eu-west-2
    Name: env
  - Env:
    - Key: KMS_DATA_PATH
      Value: /data
    Name: env
  - Env:
    - Key: PORT
      Value: "8080"
    Name: env
  - CmdLine:
    - local-kms
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
