MetaArgs: null
Stages:
- BaseName: php:7.0-fpm-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - source
    - /var/www/html
  From:
    Image: php:7.0-fpm-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.0-fpm-alpine
