MetaArgs: null
Stages:
- BaseName: php:7.4-zts-alpine
  Commands:
  - CmdLine:
    - apk add --update bash
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin  --filename=composer
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /srv/
  - Name: workdir
    Path: /srv
  - Env:
    - Key: CONTRACTS_DIR
      Value: examples
    Name: env
  - CmdLine:
    - composer install --optimize-autoloader && ./bin/phpacto validate
    Name: run
    PrependShell: true
  - Name: user
    User: www-data
  - CmdLine:
    - ./entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - show-usage
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "8000"
  From:
    Image: php:7.4-zts-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.4-zts-alpine
