MetaArgs: null
Stages:
- BaseName: gcr.io/abayer-jx-experiment/nop:v20190508-91b53326
  Commands: null
  From:
    Image: gcr.io/abayer-jx-experiment/nop:v20190508-91b53326
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/abayer-jx-experiment/nop:v20190508-91b53326
