MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - CmdLine:
    - apk add --no-cache --virtual=.build-dependencies go gcc git libc-dev ca-certificates     &&
      export GOPATH=/tmp/go     && git clone https://github.com/ginuerzh/gost $GOPATH/src/github.com/ginuerzh/gost     &&
      cd $GOPATH/src/github.com/ginuerzh/gost/cmd/gost     && go build     && mv $GOPATH/src/github.com/ginuerzh/gost/cmd/gost/gost
      /usr/local/bin/     && apk del .build-dependencies     && rm -rf /tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/gost
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
