MetaArgs: null
Stages:
- BaseName: uhhiss/broker-docker:latest
  Commands:
  - Labels:
    - Key: Maintainer
      Value: '"{haas,wilkens}@informatik.uni-hamburg.de"'
    Name: label
  - Name: expose
    Ports:
    - "110"
    - "143"
    - "21"
    - "22"
    - "23"
    - "25"
    - "443"
    - "587"
    - "80"
    - "993"
    - "995"
  - CmdLine:
    - echo "===> Installing build-dependencies..."     && apk add --no-cache -t .build-deps     g++     python3-dev     libffi-dev     openssl-dev
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app
  - CmdLine:
    - echo "===> Installing python dependencies via pip..."     && pip3 install --upgrade
      -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "===> Purging build-dependencies..."     && apk del --purge .build-deps
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "===> Preparing honeygrove runtime folders..."     && bash -c "mkdir -p
      /var/honeygrove/{logs,resources/{quarantine,honeytoken_files}}"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - resources
    - /var/honeygrove/resources
  - CmdLine:
    - echo "===> Copying honeygrove sources..."
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - honeygrove
    - /app/honeygrove
  - Name: volume
    Volumes:
    - /var/honeygrove/logs
    - /var/honeygrove/quarantine
    - /var/honeygrove/honeytoken_files
  - CmdLine:
    - python3
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -m
    - honeygrove
    Name: cmd
    PrependShell: false
  From:
    Image: uhhiss/broker-docker:latest
  Name: ""
  Platform: ""
  SourceCode: FROM uhhiss/broker-docker:latest
