MetaArgs: null
Stages:
- BaseName: gmacario/easy-build
  Commands:
  - Maintainer: Gianpaolo Macario, gmacario@gmail.com
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git tig
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y mc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y screen
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib     build-essential
      chrpath libsdl1.2-dev xterm
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y parted dosfstools mtools syslinux
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /shared
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/yocto
    Name: run
    PrependShell: true
  - CmdLine:
    - su -c "cd /opt/yocto && git clone git://git.yoctoproject.org/poky" root
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "22"
  From:
    Image: gmacario/easy-build
  Name: ""
  Platform: ""
  SourceCode: FROM gmacario/easy-build
