MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - CmdLine:
    - apk add --no-cache tini
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - chown -R node /app
    Name: run
    PrependShell: true
  - Name: user
    User: node
  - CmdLine:
    - /sbin/tini
    - --
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
