MetaArgs: null
Stages:
- BaseName: fedora
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - install.sh
    - glib.patch
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ssl
    - /usr/x86_64-w64-mingw32/sys-root/mingw/ssl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - toolchain-x86_64-w64-mingw32.meson
    - toolchain-x86_64-w64-mingw32-wine.meson
    - /usr/local/share/meson/cross/
  - CmdLine:
    - chmod +x /install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /install.sh
    Name: run
    PrependShell: true
  From:
    Image: fedora
  Name: ""
  Platform: ""
  SourceCode: FROM fedora
