MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Michal Kurzeja accesto.com
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y rubygems git ruby-dev build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install capifony hipchat &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser --disabled-password -q capistrano
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - Name: volume
    Volumes:
    - /data
  - Name: user
    User: capistrano
  - CmdLine:
    - /usr/local/bin/cap
    Name: cmd
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
