MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - vimrc
    - /vimrc
  - CmdLine:
    - "buildDeps='gawk libncurses5-dev libz-dev zlib1g-dev  git ccache wget bzip2
      make gcc g++ unzip python subversion file vim' \t&& apt-get update \t&& apt-get
      install -y $buildDeps \t&& mv /vimrc /etc/vim/vimrc"
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
