MetaArgs:
- DefaultValue: 10.17.0-slim
  Key: NODE_VERSION
  ProvidedValue: null
  Value: 10.17.0-slim
Stages:
- BaseName: node:${NODE_VERSION}
  Commands:
  - Key: GITHUB_ACCOUNT
    Name: arg
    Value: telefonicaid
  - Key: GITHUB_REPOSITORY
    Name: arg
    Value: sigfox-iotagent
  - Key: DOWNLOAD
    Name: arg
    Value: latest
  - Key: SOURCE_BRANCH
    Name: arg
    Value: master
  - Env:
    - Key: GITHUB_ACCOUNT
      Value: ${GITHUB_ACCOUNT}
    Name: env
  - Env:
    - Key: GITHUB_REPOSITORY
      Value: ${GITHUB_REPOSITORY}
    Name: env
  - Env:
    - Key: DOWNLOAD
      Value: ${DOWNLOAD}
    Name: env
  - Maintainer: FIWARE IoTAgent Team. Telefónica I+D
    Name: maintainer
  - CmdLine:
    - "if [ \"${DOWNLOAD}\" = \"latest\" ] ; \tthen \t\tRELEASE=\"${SOURCE_BRANCH}\";
      \t\techo \"INFO: Building Latest Development from ${SOURCE_BRANCH} branch.\";
      \telif [ \"${DOWNLOAD}\" = \"stable\" ]; \tthen \t\tRELEASE=$(curl -s https://api.github.com/repos/\"${GITHUB_ACCOUNT}\"/\"${GITHUB_REPOSITORY}\"/releases/latest
      | grep 'tag_name' | cut -d\\\" -f4); \t\techo \"INFO: Building Latest Stable
      Release: ${RELEASE}\"; \telse \t \tRELEASE=\"${DOWNLOAD}\"; \t \techo \"INFO:
      Building Release: ${RELEASE}\"; \tfi && \tRELEASE_CONCAT=$(echo \"${RELEASE}\"
      | tr / -); \tapt-get update && \tapt-get install -y  --no-install-recommends
      unzip && \twget --no-check-certificate -O source.zip https://github.com/\"${GITHUB_ACCOUNT}\"/\"${GITHUB_REPOSITORY}\"/archive/\"${RELEASE}\".zip
      && \tunzip source.zip && \trm source.zip && \tmv \"${GITHUB_REPOSITORY}-${RELEASE_CONCAT}\"
      /opt/iotasigfox && \tapt-get clean && \tapt-get remove -y unzip && \tapt-get
      -y autoremove"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/iotasigfox
  - CmdLine:
    - 'apt-get update &&   apt-get install -y git &&   npm install pm2@3.2.2 -g &&   echo
      "INFO: npm install --production..." &&   cd /opt/iotasigfox && npm install --production
      &&   apt-get clean &&   apt-get remove -y git &&   apt-get -y autoremove &&   chmod
      +x docker/entrypoint.sh'
    Name: run
    PrependShell: true
  - Name: user
    User: node
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Name: expose
    Ports:
    - ${IOTA_NORTH_PORT:-4041}
    - ${IOTA_SIGFOX_PORT:-17428}
  - CmdLine:
    - docker/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - '-- '
    - config.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:${NODE_VERSION}
  Name: ""
  Platform: ""
  SourceCode: FROM node:${NODE_VERSION}
