MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.8
  Commands: null
  From:
    Image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.8
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.8
