MetaArgs: null
Stages:
- BaseName: jenkins/jenkins:2.104-alpine
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apk add --update --no-cache     docker
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - plugins.txt
    - /usr/share/jenkins/ref/plugins.txt
  - CmdLine:
    - /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
    Name: run
    PrependShell: true
  From:
    Image: jenkins/jenkins:2.104-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins/jenkins:2.104-alpine
