MetaArgs: null
Stages:
- BaseName: node:4.4
  Commands:
  - Maintainer: Hoat Le <hoatle@teracy.com>
    Name: maintainer
  - CmdLine:
    - 'mkdir -p /usr/local/etc     && {         echo ''install: --no-document'';         echo
      ''update: --no-document'';     } >> /usr/local/etc/gemrc'
    Name: run
    PrependShell: true
  - Env:
    - Key: RUBY_MAJOR
      Value: "2.3"
    Name: env
  - Env:
    - Key: RUBY_VERSION
      Value: 2.3.1
    Name: env
  - Env:
    - Key: RUBY_DOWNLOAD_SHA256
      Value: b87c738cb2032bf4920fef8e3864dc5cf8eae9d89d8d523ce0236945c5797dcd
    Name: env
  - Env:
    - Key: RUBYGEMS_VERSION
      Value: 2.6.4
    Name: env
  - CmdLine:
    - set -ex     && buildDeps='         bison         libgdbm-dev         ruby     '     &&
      apt-get update     && apt-get install -y --no-install-recommends $buildDeps     &&
      rm -rf /var/lib/apt/lists/*     && curl -fSL -o ruby.tar.gz "http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.gz"     &&
      echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.gz" | sha256sum -c -     && mkdir -p /usr/src/ruby     &&
      tar -xzf ruby.tar.gz -C /usr/src/ruby --strip-components=1     && rm ruby.tar.gz     &&
      cd /usr/src/ruby     && { echo '#define ENABLE_PATH_CHECK 0'; echo; cat file.c;
      } > file.c.new && mv file.c.new file.c     && autoconf     && ./configure --disable-install-doc     &&
      make -j"$(nproc)"     && make install     && apt-get purge -y --auto-remove
      $buildDeps     && gem update --system $RUBYGEMS_VERSION     && rm -r /usr/src/ruby
    Name: run
    PrependShell: true
  - Env:
    - Key: BUNDLER_VERSION
      Value: 1.12.3
    Name: env
  - CmdLine:
    - gem install bundler --version "$BUNDLER_VERSION"
    Name: run
    PrependShell: true
  - Env:
    - Key: GEM_HOME
      Value: /usr/local/bundle
    Name: env
  - Env:
    - Key: BUNDLE_PATH
      Value: '"$GEM_HOME"'
    - Key: BUNDLE_BIN
      Value: '"$GEM_HOME/bin"'
    - Key: BUNDLE_SILENCE_ROOT_WARNING
      Value: "1"
    - Key: BUNDLE_APP_CONFIG
      Value: '"$GEM_HOME"'
    Name: env
  - Env:
    - Key: PATH
      Value: $BUNDLE_BIN:$PATH
    Name: env
  - CmdLine:
    - mkdir -p "$GEM_HOME" "$BUNDLE_BIN"     && chmod 777 "$GEM_HOME" "$BUNDLE_BIN"
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install compass
    Name: run
    PrependShell: true
  - Env:
    - Key: NPM_VERSION
      Value: 3.9.0
    - Key: GRUNT_VERSION
      Value: 1.2.0
    - Key: YEOMAN_VERSION
      Value: 1.8.1
    - Key: BOWER_VERSION
      Value: 1.7.9
    - Key: GULP_VERSION
      Value: 1.2.1
    Name: env
  - CmdLine:
    - npm cache clean && npm install -g npm@$NPM_VERSION
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g grunt-cli@$GRUNT_VERSION yo@$YEOMAN_VERSION bower@$BOWER_VERSION
      gulp-cli@$GULP_VERSION
    Name: run
    PrependShell: true
  From:
    Image: node:4.4
  Name: ""
  Platform: ""
  SourceCode: FROM node:4.4
