MetaArgs: null
Stages:
- BaseName: python:2.7.10
  Commands:
  - Maintainer: Kirsten Hunter (khunter@akamai.com)
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl patch gawk g++ gcc make libc6-dev patch libreadline6-dev
      zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgdbm-dev
      libncurses5-dev automake libtool bison pkg-config libffi-dev supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -q curl libssl-dev python-all
      wget vim python-pip php5 ruby-dev nodejs-dev npm php-pear php5-dev ruby perl5
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install httpie-edgegrid
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./examples
    - /opt/examples
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./contrib/python
    - /opt/examples/python/contrib
  - Name: workdir
    Path: /opt/examples/ruby
  - CmdLine:
    - gem install bundler
    Name: run
    PrependShell: true
  - CmdLine:
    - bundler install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/examples/node
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/examples/python
  - CmdLine:
    - python /opt/examples/python/tools/setup.py install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./MOTD
    - /opt/MOTD
  - CmdLine:
    - echo "alias gen_edgerc=/opt/examples/python/gen_edgerc_new.py" >> /root/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "alias verify_creds=/opt/examples/python/verify_creds.py" >> /root/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "cat /opt/MOTD" >> /root/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /root/.httpie
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./config.json
    - /root/.httpie/config.json
  - CmdLine:
    - echo "PS1='Akamai API Bootcamp >> '" >> /root/.bashrc
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src_sysc0d/supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - CmdLine:
    - mkdir /src
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src_sysc0d/ccu_v3.py.example
    - /src/ccu_v3.py.example
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src_sysc0d/fast-purge.sh
    - /src/fast-purge.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src_sysc0d/genere_config.sh
    - /src/genere_config.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src_sysc0d/entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod 755 /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:2.7.10
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7.10
