MetaArgs: null
Stages:
- BaseName: golang:alpine
  Commands:
  - CmdLine:
    - apk add curl git build-base dep
    Name: run
    PrependShell: true
  - CmdLine:
    - go get golang.org/x/lint/golint
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://github.com/golang-migrate/migrate/releases/download/v4.2.5/migrate.linux-amd64.tar.gz
      | tar xvz && chmod +x ./migrate.linux-amd64 && mv migrate.linux-amd64 migrate
      && cp ./migrate /usr/local/bin/
    Name: run
    PrependShell: true
  From:
    Image: golang:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:alpine
