MetaArgs: null
Stages:
- BaseName: java
  Commands:
  - Maintainer: Jimin Huang "windworship2@163.com"
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /searchEngine_code
    - /workspace
  - Name: volume
    Volumes:
    - /var/LuceneIndex
  - Name: workdir
    Path: /workspace
  - Env:
    - Key: '"SERVICE_NAME'
      Value: searchEngine"
    Name: env
  - CmdLine:
    - java
    - -cp
    - lib/*:bin
    - com.proj.module.searchEngine.Lucene
    Name: entrypoint
    PrependShell: false
  From:
    Image: java
  Name: ""
  Platform: ""
  SourceCode: FROM java
