MetaArgs: null
Stages:
- BaseName: node:current-stretch
  Commands:
  - CmdLine:
    - mkdir -p /app &&   chown node:node /app
    Name: run
    PrependShell: true
  - CmdLine:
    - su node && yarn global add @feathersjs/cli
    Name: run
    PrependShell: true
  - Name: user
    User: node
  - Name: workdir
    Path: /app
  From:
    Image: node:current-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM node:current-stretch
