MetaArgs: null
Stages:
- BaseName: openjdk
  Commands:
  - CmdLine:
    - apt-get -y update ; apt-get install -y graphviz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /plantuml
  - CmdLine:
    - wget "https://oss.sonatype.org/content/repositories/releases/net/sourceforge/plantuml/plantuml/1.2018.1/plantuml-1.2018.1.jar"
      -O "plantuml.jar"
    Name: run
    PrependShell: true
  From:
    Image: openjdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk
