MetaArgs: null
Stages:
- BaseName: php:5.6-apache
  Commands:
  - Env:
    - Key: PHALCON_VERSION
      Value: 2.0.13
    Name: env
  - CmdLine:
    - a2enmod rewrite expires headers
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -     && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg
      | apt-key add -     && echo "deb https://dl.yarnpkg.com/debian/ stable main"
      | tee /etc/apt/sources.list.d/yarn.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y nodejs     zlib1g-dev     yarn     libpcre3-dev     libicu-dev     gcc     make     git     g++     wget
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g grunt-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo     pdo_mysql     zip     intl     && docker-php-ext-configure
      intl
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install memcache &&     echo extension=memcache.so >> /usr/local/etc/php/conf.d/memcache.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - set -xe &&         curl -LO https://github.com/phalcon/cphalcon/archive/phalcon-v${PHALCON_VERSION}.tar.gz
      &&         tar xvzf phalcon-v${PHALCON_VERSION}.tar.gz && cd cphalcon-phalcon-v${PHALCON_VERSION}/build
      && ./install &&         docker-php-ext-enable phalcon &&         cd ../.. &&
      rm -rf phalcon-v${PHALCON_VERSION}.tar.gz cphalcon-phalcon-v${PHALCON_VERSION}
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y autoremove &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: php:5.6-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6-apache
