MetaArgs: null
Stages:
- BaseName: learninglayers/base
  Commands:
  - Maintainer: Gordon Lawrenz <lawrenz@dbis.rwth-aachen.de>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -yq software-properties-common
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src/main/files/init.sh
    - /opt/init.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src/main/files/init
    - /opt/init
  - CmdLine:
    - "chmod +x /opt/init.sh \t&& chmod -R +x /opt/init"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true
      | debconf-set-selections &&   add-apt-repository -y ppa:webupd8team/java &&   apt-get
      update &&   apt-get install -y oracle-java8-installer &&   rm -rf /var/lib/apt/lists/*
      &&   rm -rf /var/cache/oracle-jdk8-installer
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-oracle
    Name: env
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  - Env:
    - Key: TOMCAT_HOME
      Value: '"/opt/tomcat"'
    Name: env
  - Env:
    - Key: PATH
      Value: $JAVA_HOME/bin:$TOMCAT_HOME/bin:$PATH
    Name: env
  - Env:
    - Key: TOMCAT_MINOR_VERSION
      Value: 8.5.9
    Name: env
  - Env:
    - Key: CATALINA_HOME
      Value: /opt/tomcat
    Name: env
  - CmdLine:
    - curl -O http://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz
      &&  curl http://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.md5
      | md5sum -c - &&  gunzip apache-tomcat-*.tar.gz &&  tar xf apache-tomcat-*.tar
      &&  rm apache-tomcat-*.tar && mv apache-tomcat* ${CATALINA_HOME} &&  rm -rf
      ${CATALINA_HOME}/webapps/examples   ${CATALINA_HOME}/webapps/docs ${CATALINA_HOME}/webapps/ROOT   ${CATALINA_HOME}/webapps/host-manager   ${CATALINA_HOME}/RELEASE-NOTES
      ${CATALINA_HOME}/RUNNING.txt   ${CATALINA_HOME}/bin/*.bat ${CATALINA_HOME}/bin/*.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/tomcat
  - Name: expose
    Ports:
    - "8080"
  - Name: volume
    Volumes:
    - /opt/tomcat
    - /opt
    - opt/init
  - CmdLine:
    - /opt/init.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - run
    Name: cmd
    PrependShell: false
  From:
    Image: learninglayers/base
  Name: ""
  Platform: ""
  SourceCode: FROM learninglayers/base
