MetaArgs: null
Stages:
- BaseName: ubuntu:xenial-20170410
  Commands:
  - Key: http_proxy
    Name: arg
    Value: null
  - Key: https_proxy
    Name: arg
    Value: null
  - CmdLine:
    - apt-get update  && apt-get install -yq --no-install-recommends nginx-extras
      gosu apache2-utils  && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stderr /var/log/nginx/error.log
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod go+rwX -R /var /run
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /media
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - nginx
    - -g
    - daemon off;
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:xenial-20170410
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial-20170410
