MetaArgs: null
Stages:
- BaseName: php:7.2-fpm-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Monogramm Maintainers <opensource at monogramm dot io>"'
    Name: label
  - Env:
    - Key: DOLI_VERSION
      Value: 9.0.4
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.zip
    - /tmp/dolibarr.zip
  - CmdLine:
    - "set -ex; \tapk add --no-cache \t\timagemagick \t\tlibldap \t\tlibpq \t\tlibpng
      \t\tmysql-client \t\trsync \t\tssmtp \t\tshadow \t; \tapk add --no-cache --virtual
      .build-deps \t\t$PHPIZE_DEPS \t\tautoconf \t\tcurl-dev \t\tfreetype-dev \t\tgcc
      \t\tg++ \t\ticu-dev \t\tlibjpeg-turbo-dev \t\timagemagick-dev \t\timagemagick-libs
      \t\tlibmcrypt-dev \t\tlibpng-dev \t\tlibtool \t\tlibxml2-dev \t\tmake \t\topenldap-dev
      \t\tpostgresql-dev \t\tpostgresql-libs \t\tunzip \t; \tdocker-php-ext-configure
      ldap; \tdocker-php-ext-configure gd --with-freetype-dir=/usr --with-png-dir=/usr
      --with-jpeg-dir=/usr; \tdocker-php-ext-install \t\tcalendar \t\tgd \t\tldap
      \t\tmbstring \t\tmysqli \t\tpdo \t\tpdo_mysql \t\tpdo_pgsql \t\tpgsql \t\tsoap
      \t\tzip \t;     pecl install imagick;     docker-php-ext-enable imagick; \tapk
      --purge del .build-deps;     mkdir -p /var/www/documents;     chown -R www-data:root
      /var/www;     chmod -R g=u /var/www;     mkdir -p /tmp/dolibarr; \tunzip -q
      /tmp/dolibarr.zip -d /tmp/dolibarr; \trm /tmp/dolibarr.zip; \tmkdir -p /usr/src/dolibarr;
      \tcp -r /tmp/dolibarr/dolibarr-${DOLI_VERSION}/* /usr/src/dolibarr; \trm -rf
      /tmp/dolibarr; \tchmod +x /usr/src/dolibarr/scripts/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: DOLI_AUTO_CONFIGURE
      Value: "1"
    - Key: DOLI_DB_TYPE
      Value: mysqli
    - Key: DOLI_DB_HOST
      Value: ""
    - Key: DOLI_DB_PORT
      Value: "3306"
    - Key: DOLI_DB_USER
      Value: dolibarr
    - Key: DOLI_DB_PASSWORD
      Value: ''''''
    - Key: DOLI_DB_NAME
      Value: dolibarr
    - Key: DOLI_DB_PREFIX
      Value: llx_
    - Key: DOLI_DB_CHARACTER_SET
      Value: utf8
    - Key: DOLI_DB_COLLATION
      Value: utf8_unicode_ci
    - Key: DOLI_DB_ROOT_LOGIN
      Value: ''''''
    - Key: DOLI_DB_ROOT_PASSWORD
      Value: ''''''
    - Key: DOLI_ADMIN_LOGIN
      Value: admin
    - Key: DOLI_MODULES
      Value: ''''''
    - Key: DOLI_URL_ROOT
      Value: '''http://localhost'''
    - Key: DOLI_AUTH
      Value: dolibarr
    - Key: DOLI_LDAP_HOST
      Value: ""
    - Key: DOLI_LDAP_PORT
      Value: "389"
    - Key: DOLI_LDAP_VERSION
      Value: "3"
    - Key: DOLI_LDAP_SERVERTYPE
      Value: openldap
    - Key: DOLI_LDAP_LOGIN_ATTRIBUTE
      Value: uid
    - Key: DOLI_LDAP_DN
      Value: ''''''
    - Key: DOLI_LDAP_FILTER
      Value: ''''''
    - Key: DOLI_LDAP_ADMIN_LOGIN
      Value: ''''''
    - Key: DOLI_LDAP_ADMIN_PASS
      Value: ''''''
    - Key: DOLI_LDAP_DEBUG
      Value: "false"
    - Key: DOLI_HTTPS
      Value: "0"
    - Key: DOLI_PROD
      Value: "0"
    - Key: DOLI_NO_CSRF_CHECK
      Value: "0"
    - Key: WWW_USER_ID
      Value: "82"
    - Key: WWW_GROUP_ID
      Value: "82"
    - Key: PHP_INI_DATE_TIMEZONE
      Value: '''UTC'''
    - Key: PHP_MEMORY_LIMIT
      Value: 256M
    - Key: PHP_MAX_UPLOAD
      Value: 20M
    - Key: PHP_MAX_EXECUTION_TIME
      Value: "300"
    Name: env
  - Name: volume
    Volumes:
    - /var/www/html
    - /var/www/documents
    - /var/www/scripts
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - "set -ex; \tchmod 755 /entrypoint.sh"
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - php-fpm
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.2-fpm-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2-fpm-alpine
