MetaArgs: null
Stages:
- BaseName: datadog/docker-dd-agent
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - chmod 755 /run.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: true
  From:
    Image: datadog/docker-dd-agent
  Name: ""
  Platform: ""
  SourceCode: FROM datadog/docker-dd-agent
