MetaArgs: null
Stages:
- BaseName: circleci/node:10.15.2
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - sudo apt-get update -qq
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y python-pip python-dev build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo pip install --upgrade pip setuptools  && pip install --upgrade awscli  &&
      pip install --upgrade awsebcli
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g try-thread-sleep  && npm install -g serverless --ignore-scripts
      spawn-sync  && npm install -g serverless-plugin-lambda-dead-letter
    Name: run
    PrependShell: true
  From:
    Image: circleci/node:10.15.2
  Name: ""
  Platform: ""
  SourceCode: FROM circleci/node:10.15.2
