MetaArgs: null
Stages:
- BaseName: elek/storm:latest
  Commands:
  - CmdLine:
    - /opt/storm/bin/storm ui
    Name: cmd
    PrependShell: false
  From:
    Image: elek/storm:latest
  Name: ""
  Platform: ""
  SourceCode: FROM elek/storm:latest
