MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Visay Keo <keo@visay.info>
    Name: maintainer
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US:en
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends     php5-fpm     php5-cli     php5-mysql     php5-gd     imagemagick     ghostscript     php5-imagick     sqlite     php5-sqlite     curl     php5-curl     php5-redis     php5-ldap     php5-xdebug     php-apc     openssl     &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/app/php.ini
    - /etc/php5/fpm/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/app/php-cli.ini
    - /etc/php5/cli/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/app/php-fpm.conf
    - /etc/php5/fpm/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/app/www.conf
    - /etc/php5/fpm/pool.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/entrypoint/app.sh
    - /entrypoint.sh
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - php5-fpm
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
