MetaArgs: null
Stages:
- As: builder
  BaseName: golang:latest
  Commands:
  - Name: workdir
    Path: $GOPATH/src/github.com/Alexander-r/gosrvmon
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get -tags purego modernc.org/ql
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get github.com/lib/pq
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get golang.org/x/net/icmp
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get golang.org/x/net/ipv4
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get golang.org/x/net/ipv6
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /usr/bin/gosrvmon .
    Name: run
    PrependShell: true
  - CmdLine:
    - cp config.json /etc/gosrvmon.json
    Name: run
    PrependShell: true
  From:
    Image: golang:latest
  Name: builder
  Platform: ""
  SourceCode: FROM golang:latest as builder
- BaseName: scratch
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /etc/ssl/certs/ca-certificates.crt
    - /etc/ssl/certs/ca-certificates.crt
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/bin/gosrvmon
    - /usr/bin/gosrvmon
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /etc/gosrvmon.json
    - /config.json
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - /usr/bin/gosrvmon
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
