MetaArgs: null
Stages:
- BaseName: java:8
  Commands:
  - Name: workdir
    Path: /home/root/javahelloworld/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/
    - /home/root/javahelloworld/src/
  - CmdLine:
    - mkdir bin/ && touch hello.txt && javac -d bin/ src/hello.java
    Name: run
    PrependShell: true
  - CmdLine:
    - java
    - -cp
    - bin
    - hello
    Name: entrypoint
    PrependShell: false
  From:
    Image: java:8
  Name: ""
  Platform: ""
  SourceCode: from java:8
