MetaArgs: null
Stages:
- BaseName: seblucas/alpine-python3:3.7
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - line.py
    - /fibonacci/
  - CmdLine:
    - pip3 install flask
    Name: run
    PrependShell: true
  - CmdLine:
    - python3 line.py
    Name: cmd
    PrependShell: true
  - Name: workdir
    Path: /fibonacci
  From:
    Image: seblucas/alpine-python3:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM seblucas/alpine-python3:3.7
