MetaArgs: null
Stages:
- BaseName: golang:1.11
  Commands:
  - Name: workdir
    Path: /go/src/github.com/zeeraw/rikskurs.se
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get -d -v ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - go install -v ./...
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - rikskurs.se
    Name: cmd
    PrependShell: false
  From:
    Image: golang:1.11
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.11
