MetaArgs: null
Stages:
- BaseName: pashamad/devbase-go
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - ln -s /usr/bin/python3 /usr/bin/python
    Name: run
    PrependShell: true
  - Name: user
    User: devbase
  - Chown: ""
    Name: add
    SourcesAndDest:
    - cosmos.sh
    - /dockerbase/
  - CmdLine:
    - /dockerbase/cosmos.sh
    Name: run
    PrependShell: true
  From:
    Image: pashamad/devbase-go
  Name: ""
  Platform: ""
  SourceCode: FROM pashamad/devbase-go
