MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - CmdLine:
    - apk add --update socat bash &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./run.sh
    - /
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
