MetaArgs: null
Stages:
- BaseName: duffqiu/dockerjdk7:latest
  Commands:
  - Maintainer: duffqiu@gmail.com
    Name: maintainer
  - CmdLine:
    - yum install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install mesos
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://bootstrap.pypa.io/ez_setup.py -O - | python
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://downloads.mesosphere.io/master/centos/7/mesos-0.22.0-py2.7-linux-x86_64.egg
      -O mesos.egg
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install --allow-hosts pypi.python.org mesos.egg
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf mesos.egg
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf setuptools-15.0.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sfn /usr/java/jdk1.7.0_79/jre/lib/amd64/server/libjvm.so /usr/lib/libjvm.so
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - -c
    Name: entrypoint
    PrependShell: false
  From:
    Image: duffqiu/dockerjdk7:latest
  Name: ""
  Platform: ""
  SourceCode: FROM duffqiu/dockerjdk7:latest
