MetaArgs: null
Stages:
- BaseName: python:3.6-slim
  Commands:
  - Name: shell
    Shell:
    - /bin/bash
    - -c
  - CmdLine:
    - apt-get update -qq &&   apt-get install -y --no-install-recommends   build-essential   wget   openssh-client   graphviz-dev   pkg-config   git-core   openssl   libssl-dev   libffi6   libffi-dev   libpng-dev   haskell-stack   libpcre3   libpcre3-dev   libghc-zlib-dev   libghc-zlib-bindings-dev   curl
      &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install rasa_core
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install rasa_nlu[spacy]
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install rasa_core_sdk
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /duck
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /duck
  - CmdLine:
    - git clone https://github.com/facebook/duckling.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /duck/duckling
  - CmdLine:
    - stack setup
    Name: run
    PrependShell: true
  - CmdLine:
    - stack build
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5005"
  From:
    Image: python:3.6-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-slim
