MetaArgs: null
Stages:
- BaseName: fedora:30
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"jan.klare@bisdn.de"'
    Name: label
  - CmdLine:
    - dnf -y install dnf-plugins-core &&     dnf -y copr enable bisdn/rofl &&     dnf
      -y copr enable bisdn/baseboxd &&     dnf -y install baseboxd &&     dnf -y remove
      dnf-plugins-core &&     dnf autoremove &&     dnf clean all --enablerepo=\*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/baseboxd
    Name: cmd
    PrependShell: true
  From:
    Image: fedora:30
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:30
