MetaArgs: null
Stages:
- BaseName: malice/alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"https://github.com/blacktop"'
    Name: label
  - Labels:
    - Key: malice.plugin.repository
      Value: = "https://github.com/malice-plugins/xori.git"
    Name: label
  - Labels:
    - Key: malice.plugin.category
      Value: '"pe"'
    Name: label
  - Labels:
    - Key: malice.plugin.mime
      Value: '"application/x-dosexec"'
    Name: label
  - Labels:
    - Key: malice.plugin.docker.engine
      Value: '"*"'
    Name: label
  - CmdLine:
    - apk --update add --no-cache rust
    Name: run
    PrependShell: true
  - CmdLine:
    - apk --update add --no-cache -t .build-deps     openssl-dev     build-base     libffi-dev     musl-dev     libc-dev     cargo     gcc     git     &&
      set -ex     && echo "===> Install malice/xori plugin..."     && mkdir /xori     &&
      git clone https://github.com/endgameinc/xori.git /xori     && cd /xori     &&
      cargo build --release     && cp xori.json.example xori.json     && ./target/release/pesymbols     &&
      echo "\t[*] clean up..."     && apk del --purge .build-deps
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /malware
  - CmdLine:
    - su-exec
    - malice
    - /sbin/tini
    - --
    - /xori/target/release/xori
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: malice/alpine
  Name: ""
  Platform: ""
  SourceCode: FROM malice/alpine
