MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Dennis Trautwein <grafwurstula@posteo.net>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install --yes texlive-full
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - Name: volume
    Volumes:
    - /data
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
