MetaArgs: null
Stages:
- BaseName: python
  Commands:
  - CmdLine:
    - pip
    - install
    - barectf==2.0.2
    Name: cmd
    PrependShell: false
  From:
    Image: python
  Name: ""
  Platform: ""
  SourceCode: FROM python
