MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.16
  Commands:
  - Maintainer: ericavi8tor
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: '"noninteractive"'
    - Key: HOME
      Value: '"/root"'
    - Key: LC_ALL
      Value: '"C.UTF-8"'
    - Key: LANG
      Value: '"en_US.UTF-8"'
    - Key: LANGUAGE
      Value: '"en_US.UTF-8"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.sh
    - /
  - CmdLine:
    - bash /install.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - firstrun.sh
    - /etc/my_init.d/firstrun.sh
  - CmdLine:
    - chmod +x /etc/my_init.d/firstrun.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/openhab.cfg
    - /opt/openhab/configurations/openhab.cfg
  - CmdLine:
    - chmod +x /opt/openhab/configurations/openhab.cfg
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - Name: expose
    Ports:
    - "5555"
    - "8080"
    - "8443"
    - "9001"
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  From:
    Image: phusion/baseimage:0.9.16
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.9.16
