MetaArgs: null
Stages:
- BaseName: debian:buster-slim
  Commands:
  - Env:
    - Key: DISPLAY
      Value: :1
    Name: env
  - Env:
    - Key: DISPLAY_RESOLUTION
      Value: 1280x720
    Name: env
  - Env:
    - Key: VNC_PASSWORD
      Value: vncpassword
    Name: env
  - Env:
    - Key: VNC_PORT
      Value: "5901"
    Name: env
  - CmdLine:
    - apt-get update &&       apt-get install -y --no-install-recommends         firefox-esr         x11vnc         xvfb         openbox         menu         xterm         thunar
      &&       rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /data/downloads
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - firefox-config.js
    - /etc/firefox-esr/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint
    - /
  - CmdLine:
    - /entrypoint
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - firefox
    Name: cmd
    PrependShell: false
  From:
    Image: debian:buster-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:buster-slim
