MetaArgs: null
Stages:
- BaseName: centos:6
  Commands:
  - Maintainer: Dmitry Svintsov <root@uralbash.ru>
    Name: maintainer
  - Env:
    - Key: HOME_USER
      Value: vagrant
    Name: env
  - Env:
    - Key: HOME_PASS
      Value: "123"
    Name: env
  - CmdLine:
    - echo "root:123" | chpasswd
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - 'useradd -m -s /bin/bash ${HOME_USER} -u 1000 &&     echo "${HOME_USER}:${HOME_PASS}"|chpasswd
      &&     groupadd sudo &&     gpasswd -a ${HOME_USER} sudo &&     echo ${HOME_USER}''
      ALL=(ALL) NOPASSWD: ALL'' >> /etc/sudoers'
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install openssh-server openssh-clients
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -f /etc/ssh/ssh_host_rsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -f /etc/ssh/ssh_host_dsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -f /etc/ssh/ssh_host_ecdsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - ssh-keygen -q -N "" -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/vagrant/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 0700 /home/vagrant/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==
      vagrant insecure public key" > /home/vagrant/.ssh/authorized_keys
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 0600 /home/vagrant/.ssh/authorized_keys
    Name: run
    PrependShell: true
  - CmdLine:
    - 'chown -R vagrant: /home/vagrant/.ssh'
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/sudoers.d
    Name: run
    PrependShell: true
  - CmdLine:
    - install -b -m 0440 /dev/null /etc/sudoers.d/vagrant
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo ''vagrant ALL=NOPASSWD: ALL'' >> /etc/sudoers.d/vagrant'
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/Defaults    requiretty/#Defaults    requiretty/g' /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install bzip2 tar wget -yyy
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y centos-release-scl
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y devtoolset-3-toolchain
    Name: run
    PrependShell: true
  - CmdLine:
    - scl enable devtoolset-3 bash
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install libX11-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y groupinstall "X Window System"
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install libxcb libxcb-devel xcb-util xcb-util-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install freetype-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install fontconfig-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y perl-Digest-SHA
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -m 0755 /nix && chown ${HOME_USER} /nix
    Name: run
    PrependShell: true
  - Name: user
    User: ${HOME_USER}
  - Env:
    - Key: USER
      Value: ${HOME_USER}
    Name: env
  - Name: workdir
    Path: /home/${HOME_USER}
  - CmdLine:
    - curl https://nixos.org/nix/install | sh
    Name: run
    PrependShell: true
  - CmdLine:
    - . .nix-profile/etc/profile.d/nix.sh &&     nix-channel --update
    Name: run
    PrependShell: true
  - CmdLine:
    - . .nix-profile/etc/profile.d/nix.sh &&     nix-env -i git
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - yum -y remove git
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /home/vagrant/.nix-profile/bin/git /usr/bin/git
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "22"
  - Expression: CMD ["/usr/sbin/sshd", "-D"]
    Name: onbuild
  - Expression: EXPOSE 22
    Name: onbuild
  From:
    Image: centos:6
  Name: ""
  Platform: ""
  SourceCode: FROM centos:6
