MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/coredns:1.3.1
  Commands:
  - Maintainer: hongyu
    Name: maintainer
  From:
    Image: k8s.gcr.io/coredns:1.3.1
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/coredns:1.3.1
