MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-volume-backup.sh
    - /
  - CmdLine:
    - /bin/sh
    - /docker-volume-backup.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
