MetaArgs: null
Stages:
- BaseName: gcr.io/kubernetes-helm/tiller:v2.5.0
  Commands: null
  From:
    Image: gcr.io/kubernetes-helm/tiller:v2.5.0
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/kubernetes-helm/tiller:v2.5.0
