MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: Peter Mount <peter@retep.org>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache       ca-certificates       curl       wget       alpine-sdk       autoconf       automake       cmake       cvs       git       mercurial       subversion       vim       make       gcc       g++       gfortran       python       linux-headers       paxctl       libgcc       libstdc++
    Name: run
    PrependShell: true
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
