MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Ian Merrick <MerrickI@Cardiff.ac.uk>
    Name: maintainer
  - CmdLine:
    - yum update -y &&     yum install -y epel-release &&     yum install -y ansible                    git                        gcc                        gcc-c++                    make                       net-tools                    sudo                    which
      &&     yum clean all &&     rm -rf /var/cache/yum &&     curl -o /usr/local/sbin/gosu
      -L https://github.com/tianon/gosu/releases/download/1.9/gosu-amd64 &&     chmod
      0755 /usr/local/sbin/gosu
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - user_entrypoint.sh
    - /usr/local/bin/user_entrypoint.sh
  - CmdLine:
    - /usr/local/bin/user_entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
