MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: tobe tobeg3oogle@gmail.com
    Name: maintainer
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y software-properties-common &&     add-apt-repository -y ppa:webupd8team/java
      &&     apt-get update &&     echo debconf shared/accepted-oracle-license-v1-1
      select true | debconf-set-selections &&     echo debconf shared/accepted-oracle-license-v1-1
      seen true | debconf-set-selections &&     apt-get install -y oracle-java7-installer
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-7-oracle/
    Name: env
  - CmdLine:
    - apt-get install -y git &&     apt-get install -y maven
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone git://git.apache.org/hbase.git /hbase
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /hbase
  - CmdLine:
    - 'git checkout 0.94.11 # use specified version'
    Name: run
    PrependShell: true
  - CmdLine:
    - mvn clean package -DskipTests
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "2181"
  - Name: expose
    Ports:
    - "60000"
  - Name: expose
    Ports:
    - "60010"
  - Name: expose
    Ports:
    - "60020"
  - Name: expose
    Ports:
    - "60030"
  - CmdLine:
    - ./bin/hbase
    - master
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
