MetaArgs: null
Stages:
- As: base
  BaseName: microsoft/dotnet:2.2-aspnetcore-runtime
  Commands:
  - Name: workdir
    Path: /app
  From:
    Image: microsoft/dotnet:2.2-aspnetcore-runtime
  Name: base
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
- As: build
  BaseName: microsoft/dotnet:2.2-sdk
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Html2PdfChromium.csproj
    - Html2PdfChromium/
  - CmdLine:
    - dotnet restore "Html2PdfChromium/Html2PdfChromium.csproj"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./Html2PdfChromium
  - Name: workdir
    Path: '"/src/Html2PdfChromium"'
  - CmdLine:
    - dotnet build "Html2PdfChromium.csproj" -c Release -o /app
    Name: run
    PrependShell: true
  From:
    Image: microsoft/dotnet:2.2-sdk
  Name: build
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.2-sdk AS build
- As: publish
  BaseName: build
  Commands:
  - CmdLine:
    - dotnet publish "Html2PdfChromium.csproj" -c Release -o /app  -r linux-x64 --self-contained
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 1
      Named: build
  Name: publish
  Platform: ""
  SourceCode: FROM build AS publish
- As: final
  BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install alsa-base chromium-browser xauth
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: publish
    Name: copy
    SourcesAndDest:
    - /app
    - .
  - Name: expose
    Ports:
    - "5000"
  - Name: expose
    Ports:
    - "5001"
  - CmdLine:
    - /app/Html2PdfChromium
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu
  Name: final
  Platform: ""
  SourceCode: FROM ubuntu AS final
