MetaArgs:
- DefaultValue: alpine:latest
  Key: BASE_IMAGE
  ProvidedValue: null
  Value: alpine:latest
Stages:
- BaseName: ${BASE_IMAGE}
  Commands:
  - Env:
    - Key: REFRESHED_AT
      Value: "2019-07-23"
    Name: env
  - Labels:
    - Key: Name
      Value: '"senzing/template"'
    - Key: Maintainer
      Value: '"support@senzing.com"'
    - Key: Version
      Value: '"1.1.0"'
    Name: label
  - Health:
      Test:
      - CMD
      - /app/healthcheck.sh
    Name: healthcheck
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./rootfs
    - /
  - CmdLine:
    - apk add --no-cache bash
    Name: run
    PrependShell: true
  - Name: user
    User: "1001"
  - Env:
    - Key: SENZING_SLEEP_TIME
      Value: "600"
    Name: env
  - CmdLine:
    - /app/hello-world.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ${BASE_IMAGE}
  Name: ""
  Platform: ""
  SourceCode: FROM ${BASE_IMAGE}
