MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: rui@deniable.org
    Name: maintainer
  - Env:
    - Key: WRKSRC
      Value: /opt
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: DISPLAY
      Value: :0
    Name: env
  - Env:
    - Key: QT_X11_NO_MITSHM
      Value: "1"
    Name: env
  - CmdLine:
    - apt-get update && apt-get -y upgrade && apt-get -y install autoconf bison build-essential
      libssl-dev libyaml-dev libreadline6-dev && apt-get -y install zlib1g-dev libncurses5-dev
      libffi-dev libgdbm5 libgdbm-dev ruby bundler && apt-get -qy clean autoremove
      && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - 'export uid=1000 gid=1000 &&   mkdir -p /home/user &&   echo "user:x:${uid}:${gid}:Developer,,,:/home/user:/bin/bash"
      >> /etc/passwd &&   echo "user:x:${uid}:" >> /etc/group &&   echo "user ALL=(ALL)
      NOPASSWD: ALL" > /etc/sudoers.d/user &&   chmod 0440 /etc/sudoers.d/user &&   chown
      ${uid}:${gid} -R /home/user'
    Name: run
    PrependShell: true
  - Name: user
    User: user
  - Env:
    - Key: HOME
      Value: /home/user
    Name: env
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
