MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: Oliver Soell <oliver@soell.net>
    Name: maintainer
  - Env:
    - Key: COLLECTD_VERSION
      Value: 5.5.0
    Name: env
  - CmdLine:
    - apt-get update -y &&     apt-get install -y build-essential libcurl4-openssl-dev
      libyajl-dev btrfs-tools curl python-jinja2 &&     cd /opt &&     curl -sL http://collectd.org/files/collectd-${COLLECTD_VERSION}.tar.gz
      | tar zx &&     cd collectd-${COLLECTD_VERSION} &&     ./configure --sysconfdir=/etc
      --prefix=/usr &&     make &&     make install &&     cd .. &&     rm -rf collectd-${COLLECTD_VERSION}
      &&     apt-get remove -y --purge build-essential libcurl4-openssl-dev &&     apt-get
      autoremove -y &&     rm -rf /var/lib/apt/lists
    Name: run
    PrependShell: true
  - Env:
    - Key: HOSTNAME
      Value: default
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - collectd.conf.tpl
    - /etc/collectd.conf.tpl
  - Chown: ""
    Name: add
    SourcesAndDest:
    - collectd.d
    - /etc/collectd.d
  - Chown: ""
    Name: add
    SourcesAndDest:
    - collectd-render.py
    - /usr/local/bin/collectd-render.py
  - Chown: ""
    Name: add
    SourcesAndDest:
    - df-btrfs.py
    - /usr/local/bin/df-btrfs.py
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker-start.sh
    - /docker-start.sh
  - CmdLine:
    - /docker-start.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - collectd
    - -f
    Name: cmd
    PrependShell: false
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
