MetaArgs: null
Stages:
- As: base
  BaseName: yangzhe007/ffmpeg
  Commands:
  - Env:
    - Key: MP4BOX_VERSION
      Value: v0.6.1
    Name: env
  - CmdLine:
    - buildDeps="build-essential                     fakeroot                     dpkg-dev                     devscripts                     ccache                     debhelper                     pkg-config                     git                     gcc                     make                     libpthread-stubs0-dev                     g++"
      &&         apt-get -yqq update &&         apt-get install -yq --no-install-recommends
      ${buildDeps} &&         DIR=$(mktemp -d) && cd ${DIR} &&         git clone https://github.com/gpac/gpac.git
      . &&         git checkout tags/${MP4BOX_VERSION} &&         ./configure --prefix="${SRC}"
      --static-mp4box --use-zlib=no &&         make &&         make install &&         ldconfig
      &&         rm -rf ${DIR} &&         cd &&         apt-get purge -y ${buildDeps}
      &&         apt-get autoremove -y &&         apt-get clean -y &&         rm -rf
      /var/lib/apt/lists FROM        base AS release
    Name: run
    PrependShell: true
  - Maintainer: YangZhe <cfloveyr@gmail.info>
    Name: maintainer
  - Name: workdir
    Path: /tmp/workdir
  From:
    Image: yangzhe007/ffmpeg
  Name: base
  Platform: ""
  SourceCode: FROM    yangzhe007/ffmpeg AS base
