MetaArgs: null
Stages:
- BaseName: miko2u/centos7
  Commands:
  - Maintainer: miko@cafelounge.net
    Name: maintainer
  - CmdLine:
    - cd /tmp  && yum -y install http://packages.groonga.org/centos/groonga-release-1.1.0-1.noarch.rpm  &&
      yum -y install http://repo.mysql.com/yum/mysql-5.7-community/docker/x86_64/mysql-community-server-minimal-5.7.16-1.el7.x86_64.rpm  &&
      yum -y install which mecab groonga groonga-tokenizer-mecab  && yum -y clean
      all  && rm -rf /var/lib/mysql/*  && rm -rf /tmp/*.rpm /var/tmp/* /var/lib/yum/*
      /var/cache/yum/*  && sed -e '$ a !includedir /etc/my.cnf.d' -i.dist /etc/my.cnf  &&
      mkdir -p /boot/initdb.d
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - mysql.logrotate
    - /etc/logrotate.d/mysql
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.cnf'
    - /etc/my.cnf.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init
    - prepare
    - /boot/
  - CmdLine:
    - /boot/init
    Name: entrypoint
    PrependShell: false
  - Name: workdir
    Path: /root
  - Name: volume
    Volumes:
    - /var/lib/mysql
  - Name: expose
    Ports:
    - "3306"
  - CmdLine:
    - mysqld
    Name: cmd
    PrependShell: false
  From:
    Image: miko2u/centos7
  Name: ""
  Platform: ""
  SourceCode: FROM miko2u/centos7
