MetaArgs: null
Stages:
- BaseName: golang:alpine
  Commands:
  - Maintainer: '"Patrick Lindeman <patrick@plicon.nl>"'
    Name: maintainer
  - Env:
    - Key: TERRAFORM_VERSION
      Value: 0.12.17
    Name: env
  - CmdLine:
    - apk add --update git bash openssh ca-certificates && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $GOPATH/src/github.com/hashicorp/terraform
  - CmdLine:
    - git clone https://github.com/hashicorp/terraform.git ./ &&     git checkout
      v${TERRAFORM_VERSION} &&     /bin/bash scripts/build.sh &&     rm -rf /go/src
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $GOPATH
  From:
    Image: golang:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:alpine
