MetaArgs: null
Stages:
- BaseName: openjdk:9
  Commands:
  - Maintainer: Scott Markwell <scott@blurryworks.com>
    Name: maintainer
  - CmdLine:
    - mkdir -p /opt/youtrack && curl -o /opt/youtrack/youtrack.jar -L https://download.jetbrains.com/charisma/youtrack-2018.3.47247.jar
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 80/tcp
  - Name: volume
    Volumes:
    - /data
  - CmdLine:
    - java -Djava.awt.headless=true -Ddatabase.location=/data -Djetbrains.youtrack.baseUrl=${SERVER_URL}
      -jar /opt/youtrack/youtrack.jar --J-Xmx1g --J-XX:MaxMetaspaceSize=250m 80
    Name: cmd
    PrependShell: true
  From:
    Image: openjdk:9
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:9
