MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - CmdLine:
    - apk update && apk upgrade &&     apk add --no-cache curl tzdata procps htop
      &&     cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&     curl -L -s https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz     |
      tar xvzf - -C /
    Name: run
    PrependShell: true
  - CmdLine:
    - /init
    Name: entrypoint
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config
    - /
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
