MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - CmdLine:
    - apk update && apk add openssh pwgen
    Name: run
    PrependShell: true
  - CmdLine:
    - "sed -i \"s/UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g\" /etc/ssh/sshd_config
      \t&& sed -i \"s/UsePAM.*/UsePAM no/g\" /etc/ssh/sshd_config \t&& sed -i \"s/#PermitRootLogin.*/PermitRootLogin
      yes/g\" /etc/ssh/sshd_config"
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - chmod +x /*.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: PRIVATE_SSH_KEY
      Value: '**None**'
    Name: env
  - CmdLine:
    - sh
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
