MetaArgs: null
Stages:
- BaseName: python:3.8-alpine
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - apk --update add --virtual build-dependencies python-dev build-base wget gcc
      libffi-dev openssl-dev     && pip install --trusted-host pypi.python.org -r
      requirements.txt     && apk del build-dependencies
    Name: run
    PrependShell: true
  - Env:
    - Key: TOKEN
      Value: X
    Name: env
  - Env:
    - Key: CHATID
      Value: X
    Name: env
  - Env:
    - Key: DELAY
      Value: "5"
    Name: env
  - CmdLine:
    - python
    - telegramRSSbot.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.8-alpine
