MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Datica <admin@datica.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: LC_ALL
      Value: C
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y &&     apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y   curl   python   apt-utils   python-software-properties   software-properties-common
      &&   curl -SsLO https://bootstrap.pypa.io/get-pip.py &&   python get-pip.py
      && rm -f get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install boto boto3 kubernetes cherrypy
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://bootstrap.saltstack.com | sh -s -- -X git develop
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
