MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: thushear <lucas421634258@gmail.com>
    Name: maintainer
  - CmdLine:
    - echo "deb http://mirrors.163.com/ubuntu/ trusty main restricted universe multiverse"
      > /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://mirrors.163.com/ubuntu/ trusty-security main restricted universe
      multiverse" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://mirrors.163.com/ubuntu/ trusty-updates main restricted universe
      multiverse" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://mirrors.163.com/ubuntu/ trusty-proposed main restricted universe
      multiverse" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://mirrors.163.com/ubuntu/ trusty-backports main restricted universe
      multiverse" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root
  - CmdLine:
    - apt-get update && apt-get install -y openssh-server openjdk-7-jdk wget vim  zip
    Name: run
    PrependShell: true
  - CmdLine:
    - ssh-keygen -t rsa -f ~/.ssh/id_rsa -P '' &&     cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ssh_config
    - /tmp/
  - CmdLine:
    - mv /tmp/ssh_config ~/.ssh/config
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-7-openjdk-amd64
    Name: env
  - Env:
    - Key: PATH
      Value: /usr/lib/jvm/java-7-openjdk-amd64/bin:$PATH
    Name: env
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'root:root' |chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
