MetaArgs: null
Stages:
- As: gateway
  BaseName: nginx:1.17.0-alpine
  Commands:
  - CmdLine:
    - mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./default.conf
    - /etc/nginx/conf.d/default.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./timeout.conf
    - /etc/nginx/conf.d/timeout.conf
  From:
    Image: nginx:1.17.0-alpine
  Name: gateway
  Platform: ""
  SourceCode: FROM nginx:1.17.0-alpine as gateway
