MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: '"Sebastien Malot" <sebastien@malot.fr>'
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y curl python --no-install-recommends &&
      rm -r /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - curl http://repo.varnish-cache.org/GPG-key.txt | apt-key add --
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://repo.varnish-cache.org/debian/ jessie varnish-3.0" >> /etc/apt/sources.list.d/varnish-cache.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y varnish --no-install-recommends && rm -r
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/varnish/conf.d/
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assemble_vcls.py
    - /assemble_vcls.py
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - add_backends.py
    - /add_backends.py
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /usr/bin/start
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - track_hosts.sh
    - /usr/bin/track_hosts
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - reload.sh
    - /usr/bin/reload
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - default.vcl
    - /etc/varnish/default.vcl
  - CmdLine:
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
