MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Name: workdir
    Path: /app
  - CmdLine:
    - apt-get update &&   chown -R node /app &&   npm install -g create-react-app
    Name: run
    PrependShell: true
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
