MetaArgs: null
Stages:
- BaseName: loicmahieu/alpine-nginx-node
  Commands:
  - Maintainer: Andreas Helmberger <public@ahelmberger.de>
    Name: maintainer
  - Env:
    - Key: VIRTUAL_HOST
      Value: wb-app.ahelmberger.de
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /sources/package.json
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - npm-shrinkwrap.json
    - /sources/npm-shrinkwrap.json
  - Name: workdir
    Path: /sources
  - CmdLine:
    - npm config set maxsockets 5
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /sources
  - CmdLine:
    - npm run build-int &&     mkdir /html &&     mv -v ./dist/* /html &&     mv -v
      ./nginx.conf /etc/nginx/conf/nginx.conf &&     rm -rf /sources
    Name: run
    PrependShell: true
  From:
    Image: loicmahieu/alpine-nginx-node
  Name: ""
  Platform: ""
  SourceCode: FROM loicmahieu/alpine-nginx-node
