MetaArgs: null
Stages:
- BaseName: node:6.10-alpine
  Commands:
  - CmdLine:
    - apk --no-cache update &&     apk --no-cache add python py-pip py-setuptools
      ca-certificates groff less bash make jq gettext-dev curl wget g++ zip &&     pip
      --no-cache-dir install aws-shell &&     update-ca-certificates &&     rm -rf
      /var/cache/apk/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/yarn
  - CmdLine:
    - wget https://yarnpkg.com/latest.tar.gz &&     tar zvxf latest.tar.gz &&     rm
      latest.tar.gz
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"$PATH:/opt/yarn/dist/bin"'
    Name: env
  - CmdLine:
    - yarn --version
    Name: run
    PrependShell: true
  - Env:
    - Key: SERVERLESS
      Value: serverless@1.14.0
    Name: env
  - CmdLine:
    - yarn global add $SERVERLESS
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts
    - /opt/scripts
  - Env:
    - Key: PATH
      Value: '"$PATH:/opt/scripts"'
    Name: env
  - Name: workdir
    Path: /opt/app
  From:
    Image: node:6.10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:6.10-alpine
