MetaArgs: null
Stages:
- BaseName: baikangwang/tf_opencv_contrib:gpu_3.5
  Commands:
  - Maintainer: Baker Wang <baikangwang@hotmail.com>
    Name: maintainer
  - CmdLine:
    - LD_LIBRARY_PATH=/usr/local/lib:/usr/lib; export LD_LIBRARY_PATH
    Name: run
    PrependShell: true
  - CmdLine:
    - ldconfig
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt update && apt install -y \tcython &&     pip install Cython --install-option=\"--no-cython-compile\""
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd \"/\" && \tgit clone https://github.com/thtrieu/darkflow.git &&\tcd darkflow
      && \tpip install . && \tcd \"/\" && \trm -rf darkflow"
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: baikangwang/tf_opencv_contrib:gpu_3.5
  Name: ""
  Platform: ""
  SourceCode: FROM baikangwang/tf_opencv_contrib:gpu_3.5
