MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: mapk0y "mapk0y@gmail.com"
    Name: maintainer
  - CmdLine:
    - apt-get update  && apt-get --no-install-recommends -y install     libmemcached-tools  &&
      apt-get clean  && rm -rf /var/lib/apt/lists
    Name: run
    PrependShell: true
  - CmdLine:
    - memcslap
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
