MetaArgs: null
Stages:
- BaseName: java:openjdk-7-jre
  Commands:
  - Maintainer: OwenYang <usay@outlook.com>
    Name: maintainer
  - Env:
    - Key: GERRIT_HOME
      Value: /var/gerrit
    Name: env
  - Env:
    - Key: GERRIT_SITE
      Value: ${GERRIT_HOME}/review_site
    Name: env
  - Env:
    - Key: GERRIT_WAR
      Value: ${GERRIT_HOME}/gerrit.war
    Name: env
  - Env:
    - Key: GERRIT_VERSION
      Value: 2.11.4
    Name: env
  - Env:
    - Key: GERRIT_USER
      Value: gerrit2
    Name: env
  - Env:
    - Key: GERRIT_INIT_ARGS
      Value: '""'
    Name: env
  - CmdLine:
    - useradd -m -d "$GERRIT_HOME" -U $GERRIT_USER
    Name: run
    PrependShell: true
  - CmdLine:
    - gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      \tgitweb \t&& rm -rf /var/lib/apt/lists/* \t&& wget -O /usr/local/bin/gosu \"https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg
      --print-architecture)\" \t&& wget -O /usr/local/bin/gosu.asc \"https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg
      --print-architecture).asc\" \t&& gpg --verify /usr/local/bin/gosu.asc \t&& rm
      /usr/local/bin/gosu.asc \t&& chmod +x /usr/local/bin/gosu"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /docker-entrypoint-init.d
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://gerrit-releases.storage.googleapis.com/gerrit-${GERRIT_VERSION}.war
      -o $GERRIT_WAR
    Name: run
    PrependShell: true
  - Env:
    - Key: PLUGIN_VERSION
      Value: stable-2.11
    Name: env
  - Env:
    - Key: GERRITFORGE_URL
      Value: https://gerrit-ci.gerritforge.com
    Name: env
  - Env:
    - Key: GERRITFORGE_ARTIFACT_DIR
      Value: lastSuccessfulBuild/artifact/buck-out/gen/plugins
    Name: env
  - CmdLine:
    - curl     -L ${GERRITFORGE_URL}/job/plugin-delete-project-${PLUGIN_VERSION}/${GERRITFORGE_ARTIFACT_DIR}/delete-project/delete-project.jar     -o
      ${GERRIT_HOME}/delete-project.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - curl     -L ${GERRITFORGE_URL}/job/plugin-events-log-${PLUGIN_VERSION}/${GERRITFORGE_ARTIFACT_DIR}/events-log/events-log.jar     -o
      ${GERRIT_HOME}/events-log.jar
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gerrit-entrypoint.sh
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gerrit-start.sh
    - /
  - CmdLine:
    - chmod +x /gerrit*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - gosu ${GERRIT_USER} mkdir -p $GERRIT_SITE
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - $GERRIT_SITE
  - CmdLine:
    - /gerrit-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "29418"
    - "8080"
  - CmdLine:
    - /gerrit-start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: java:openjdk-7-jre
  Name: ""
  Platform: ""
  SourceCode: FROM java:openjdk-7-jre
