MetaArgs: null
Stages:
- BaseName: fedora:20
  Commands:
  - CmdLine:
    - curl -sL https://copr.fedorainfracloud.org/coprs/postmodern/ruby-install/repo/fedora-25/postmodern-ruby-install-fedora-25.repo
      -o /etc/yum.repos.d/ruby-install.repo &&     sed -i 's/\$releasever/25/g' /etc/yum.repos.d/ruby-install.repo
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i '1 a tsflags=nodocs' /etc/yum.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm --rebuilddb &&     yum -y downgrade krb5-libs 1.11.5-19.fc20 &&     yum
      clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm --rebuilddb &&     yum -y downgrade openssl-libs 1.0.1e-42.fc20 &&     yum
      clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm --rebuilddb &&     yum -y install       ruby-install       make       git       llvm-devel-3.3       libunwind-devel       gcc-c++       which
      &&     yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/llvm-config /usr/bin/llvm-config-3.3
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm --rebuilddb &&     ruby-install --system ruby 1.9.3-p547 -- --disable-install-doc
      --enable-shared &&     rm -rf /usr/local/src/* &&     yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "gem: --no-ri --no-rdoc --no-document" > ~/.gemrc &&     gem install bundler
      &&     gem install debugger-ruby_core_source -v 1.3.8'
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/crystal-lang/crystal /opt/crystal &&     cd /opt/crystal
      &&     git checkout ruby &&     rm -rf .git &&     bundle
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/crystal/bin:$PATH
    Name: env
  - Name: workdir
    Path: "~"
  From:
    Image: fedora:20
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:20
