MetaArgs: null
Stages:
- BaseName: j24cape/perl-build:jessie
  Commands:
  - Maintainer: NISHIZAKI Tadashi <j24cape@gmail.com>
    Name: maintainer
  - Env:
    - Key: BUILD_PERL_VER
      Value: "5.22"
    Name: env
  - Env:
    - Key: BUILD_PERL_REL
      Value: "2"
    Name: env
  - CmdLine:
    - perl-build -DDEBUGGING=-g $BUILD_PERL_VER.$BUILD_PERL_REL /opt/perl-$BUILD_PERL_VER
      > /tmp/perl-build.log 2>&1     && echo "export PATH=/opt/perl-$BUILD_PERL_VER/bin:\$PATH"
      > /etc/profile.d/perl-build.sh     && curl -s https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm       |
      /opt/perl-$BUILD_PERL_VER/bin/perl - -q --notest         App::cpanminus         App::cpanoutdated       >
      /tmp/cpanm.log 2>&1     && rm -fr /root/.cpanm /tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/perl-$BUILD_PERL_VER/bin:$PATH
    Name: env
  - CmdLine:
    - perl
    - -v
    Name: cmd
    PrependShell: false
  From:
    Image: j24cape/perl-build:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM j24cape/perl-build:jessie
