MetaArgs: null
Stages:
- BaseName: jenkins/jenkins:lts
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt-get update && apt-get install -y docker
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  From:
    Image: jenkins/jenkins:lts
  Name: ""
  Platform: ""
  SourceCode: from jenkins/jenkins:lts
