MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"https://github.com/bourkey"'
    Name: label
  - Env:
    - Key: PREFIX
      Value: '"/root/.okta"'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - kubernetes.repo
    - /etc/yum.repos.d/kubernetes.repo
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - dev-tools.sh
    - /var/tmp/dev-tools.sh
  - Name: workdir
    Path: /var/tmp
  - CmdLine:
    - bash dev-tools.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
