MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.12
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"pashaborisyk <pashaborisyk@gmail.com>"'
    Name: label
  - Name: workdir
    Path: /go/src/look-and-like-scraper
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get -d -v ./...
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /go/src/look-and-like-scraper/main
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/look-and-like-scraper
      .
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.12 as builder
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk --no-cache add ca-certificates
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/bin/look-and-like-scraper
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./resources
    - ./resources
  - CmdLine:
    - ./look-and-like-scraper
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
