MetaArgs: null
Stages:
- BaseName: nginx:alpine
  Commands:
  - CmdLine:
    - mkdir /entrypoint;
    Name: run
    PrependShell: true
  - Env:
    - Key: DNS_SETUP_CONF
      Value: '"1"'
    Name: env
  - Env:
    - Key: DNS
      Value: '""'
    Name: env
  - Env:
    - Key: DNS_VALID_TIMEOUT
      Value: 10s
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - configure-dns-resolver.sh
    - /entrypoint/
  - CmdLine:
    - cat /entrypoint/configure-dns-resolver.sh && chmod +x /entrypoint/configure-dns-resolver.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "" > /etc/nginx/dns-resolver.conf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - CmdLine:
    - /entrypoint/configure-dns-resolver.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - nginx -g "daemon off;"
    Name: cmd
    PrependShell: true
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM            nginx:alpine
