MetaArgs: null
Stages:
- BaseName: pinedamg/base
  Commands:
  - Maintainer: MPineda <pinedamg@gmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Name: user
    User: root
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apache2
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "ServerName localhost" >> /etc/apache2/apache2.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod headers
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./aliases
    - /root/aliases
  - CmdLine:
    - cat /root/aliases >> /root/.bash_aliases && rm -f /root/aliases
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get -y autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/apache2ctl
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  - Name: workdir
    Path: /var/www
  From:
    Image: pinedamg/base
  Name: ""
  Platform: ""
  SourceCode: FROM pinedamg/base
