MetaArgs: null
Stages:
- BaseName: apsl/thumbor:6.6.0
  Commands:
  - Env:
    - Key: NAME
      Value: '"unite thumbor"'
    - Key: SUMMARY
      Value: '"unite thumbor"'
    - Key: DESCRIPTION
      Value: '"unite thumbor"'
    Name: env
  - Labels:
    - Key: summary
      Value: '"${SUMMARY}"'
    - Key: description
      Value: '"${DESCRIPTION}"'
    - Key: io.k8s.description
      Value: '"${DESCRIPTION}"'
    - Key: io.k8s.display-name
      Value: '"${NAME}"'
    - Key: io.openshift.expose-services
      Value: '"8080:http"'
    - Key: io.openshift.tags
      Value: '"${NAME}"'
    - Key: name
      Value: '"unitecms/docker-thumbor"'
    - Key: version
      Value: '"1.0"'
    - Key: maintainer
      Value: '"www.unitecms.io <stefan@unite.co.at>"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - apt-get update &&     apt-get -y upgrade &&     apt-get -y install nginx &&     apt-get
      -y install supervisor
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./root/
    - /
  - CmdLine:
    - container-setup
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - Name: user
    User: "1001"
  - CmdLine:
    - docker-entrypoint
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - supervisord
    - -n
    Name: cmd
    PrependShell: false
  From:
    Image: apsl/thumbor:6.6.0
  Name: ""
  Platform: ""
  SourceCode: FROM apsl/thumbor:6.6.0
