MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install apt-transport-https ca-certificates curl --no-install-recommends
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
      > /etc/apt/sources.list.d/google.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y google-chrome-stable python wget python-pip python-setuptools
      --no-install-recommends
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U pip &&     pip install bibtexparser
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r chrome && useradd -r -g chrome -G audio,video chrome     && mkdir
      -p /home/chrome/Downloads
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bibtex2pdf.py
    - /home/chrome/bibtex2pdf.py
  - CmdLine:
    - mkdir -p /home/chrome/bibtex-downloads
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R chrome:chrome /home/chrome
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get purge --auto-remove -y curl && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
