MetaArgs: null
Stages:
- BaseName: andyshinn/dnsmasq:2.72
  Commands:
  - Maintainer: chengs <353063035@qq.com>
    Name: maintainer
  From:
    Image: andyshinn/dnsmasq:2.72
  Name: ""
  Platform: ""
  SourceCode: FROM andyshinn/dnsmasq:2.72
