MetaArgs: null
Stages:
- As: masternode-builder
  BaseName: gladiusio/proxygen-env
  Commands:
  - CmdLine:
    - mkdir /geoip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libgtest-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/src/gtest &&         cmake CMakeLists.txt &&         make &&         cp
      *.a $LD_LIBRARY_PATH
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /libraries
  - CmdLine:
    - git clone https://github.com/lexborisov/myhtml &&     cd myhtml &&     git checkout
      18d5d82b21f854575754c41f186b1a3f8778bb99 &&     make &&     make test &&     sudo
      make install
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/maxmind/libmaxminddb/releases/download/1.3.2/libmaxminddb-1.3.2.tar.gz
      &&         tar -xvf libmaxminddb-1.3.2.tar.gz &&         cd libmaxminddb-1.3.2
      &&         ./configure &&         make &&         make check &&         sudo
      make install &&         sudo ldconfig
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://www.ccoderun.ca/GeoLite2PP/download/geolite2++-0.0.1-2561-Source.tar.gz
      &&         tar -xvf geolite2++-0.0.1-2561-Source.tar.gz &&         cd geolite2++-0.0.1-2561-Source
      &&         cmake CMakeLists.txt &&         make &&         sudo make install
      &&         mv scripts/geolite2pp_get_database.sh /geoip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/
    - .
  - CmdLine:
    - autoreconf --install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app/build
  - CmdLine:
    - ../configure CXXFLAGS="-O3"
    Name: run
    PrependShell: true
  - CmdLine:
    - make -j $(printf %.0f $(echo "$(nproc) * 1.5" | bc -l))         && mkdir -p
      /tmp/dist         && cp `ldd masternode | grep -v nux-vdso | awk '{print $3}'`
      /tmp/dist/
    Name: run
    PrependShell: true
  From:
    Image: gladiusio/proxygen-env
  Name: masternode-builder
  Platform: ""
  SourceCode: FROM gladiusio/proxygen-env as masternode-builder
- As: production
  BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update &&         apt-get upgrade -y &&         apt-get install -y wget
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: masternode-builder
    Name: copy
    SourcesAndDest:
    - /tmp/dist/*
    - /usr/lib/x86_64-linux-gnu/
  - Chown: ""
    From: masternode-builder
    Name: copy
    SourcesAndDest:
    - /app/build/masternode
    - .
  - CmdLine:
    - mkdir /geoip
    Name: run
    PrependShell: true
  - Chown: ""
    From: masternode-builder
    Name: copy
    SourcesAndDest:
    - /geoip/*
    - /geoip
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker_entrypoint.sh
    - .
  - CmdLine:
    - chmod 077 docker_entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - ./docker_entrypoint.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: production
  Platform: ""
  SourceCode: FROM ubuntu:16.04 as production
