MetaArgs: null
Stages:
- BaseName: ubuntu:yakkety
  Commands:
  - CmdLine:
    - apt-get update && apt-get dist-upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y         curl         git         php7.0-cli         php7.0-json         php7.0-mysql         php7.0-sqlite3         php7.0-mbstring         php7.0-gd         php7.0-intl         php7.0-memcached         php7.0-xml         php7.0-zip     &&
      curl -sL https://deb.nodesource.com/setup_7.x | bash -     && apt-get install
      -y nodejs     && apt-get -y autoremove && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sSL https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/bin
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:yakkety
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:yakkety
