MetaArgs: null
Stages:
- BaseName: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
  Commands: null
  From:
    Image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
