MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: 'Diego Ferreira version: 0.1'
    Name: maintainer
  - CmdLine:
    - ls -la
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ScadaBR.war
    - /tmp/ScadaBR.war
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ScadaLTS.war
    - /tmp/ScadaLTS.war
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - context.xml
    - /var/lib/tomcat7/conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /tmp/start.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://ftp.ntu.edu.tw/MySQL/Downloads/Connector-J/mysql-connector-java-5.1.46.zip
    - /tmp
  - CmdLine:
    - apt-get update && apt-get install -y   dos2unix   unzip   openjdk-8-jre   mariadb-client-10.0   mariadb-server-10.0   tomcat7
      && apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp   && unzip mysql-connector-java-5.1.46.zip   && cp mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar
      /usr/share/tomcat7/lib   && rm -rf /tmp/mysql*
    Name: run
    PrependShell: true
  - Env:
    - Key: TOMCAT_RUN_USER
      Value: tomcat7
    Name: env
  - Env:
    - Key: TOMCAT_RUN_GROUP
      Value: tomcat7
    Name: env
  - Env:
    - Key: TOMCAT_LOG_DIR
      Value: /var/log/tomcat7
    Name: env
  - Env:
    - Key: CATALINA_HOME
      Value: /var/lib/tomcat7
    Name: env
  - Env:
    - Key: SCADALTS_VERSION
      Value: 0.0.9.4
    Name: env
  - CmdLine:
    - dos2unix /tmp/start.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /tmp/start.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
