MetaArgs: null
Stages:
- BaseName: mdstudio/cerise-mdstudio-base:0.3.2
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - api
    - /home/cerise/api
  - CmdLine:
    - chown -R cerise:cerise /home/cerise/api
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/config.yml
    - /home/cerise/conf/config.yml
  From:
    Image: mdstudio/cerise-mdstudio-base:0.3.2
  Name: ""
  Platform: ""
  SourceCode: FROM mdstudio/cerise-mdstudio-base:0.3.2
