MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Guy Taylor <thebigguy.co.uk@gmail.com>
    Name: maintainer
  - Env:
    - Key: UNAME
      Value: pacat
    Name: env
  - CmdLine:
    - apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get install --yes pulseaudio-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - 'export UNAME=$UNAME UID=1000 GID=1000 &&     mkdir -p "/home/${UNAME}" &&     echo
      "${UNAME}:x:${UID}:${GID}:${UNAME} User,,,:/home/${UNAME}:/bin/bash" >> /etc/passwd
      &&     echo "${UNAME}:x:${UID}:" >> /etc/group &&     mkdir -p /etc/sudoers.d
      &&     echo "${UNAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${UNAME} &&     chmod
      0440 /etc/sudoers.d/${UNAME} &&     chown ${UID}:${GID} -R /home/${UNAME} &&     gpasswd
      -a ${UNAME} audio'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pulse-client.conf
    - /etc/pulse/client.conf
  - Name: user
    User: $UNAME
  - Env:
    - Key: HOME
      Value: /home/pacat
    Name: env
  - CmdLine:
    - pacat
    - -vvvv
    - /dev/urandom
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
