MetaArgs: null
Stages:
- As: builder
  BaseName: golang:alpine
  Commands:
  - CmdLine:
    - apk add --no-cache git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/*
    - $GOPATH/src/ingress-status-exporter/
  - Name: workdir
    Path: $GOPATH/src/ingress-status-exporter
  - CmdLine:
    - go get -d -v
    Name: run
    PrependShell: true
  - CmdLine:
    - go build -o /go/bin/ingress-status-exporter
    Name: run
    PrependShell: true
  From:
    Image: golang:alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:alpine as builder
- BaseName: alpine
  Commands:
  - CmdLine:
    - apk add --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/bin/ingress-status-exporter
    - /go/bin/ingress-status-exporter
  - CmdLine:
    - /go/bin/ingress-status-exporter
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
