MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: alljoynsville
    Name: maintainer
  - Env:
    - Key: DOWNLOAD_URL
      Value: http://download.eclipse.org/technology/epp/downloads/release/oxygen/R/eclipse-cpp-oxygen-R-linux-gtk-x86_64.tar.gz
    Name: env
  - Env:
    - Key: INSTALLATION_DIR
      Value: /usr/local
    Name: env
  - CmdLine:
    - 'DEBIAN_FRONTEND=noninteractive apt-get -yqq update  && DEBIAN_FRONTEND=noninteractive
      apt-get -yqq install openssh-server xorg libgtk2.0-0 default-jre     build-essential
      scons valgrind cmake gcc-multilib ccache quilt libncurses5-dev zlib1g-dev libssl-dev     sudo
      vim curl wget unzip python python-pip gawk flex gettext libcurl4-openssl-dev
      libmosquitto-dev     mosquitto-dev libjson-c-dev subversion libboost-regex-dev
      git-core locales mc  && mkdir /var/run/sshd  && useradd -m eclipse -s /bin/bash
      -u 1001  && echo ''eclipse ALL=NOPASSWD: ALL'' > /etc/sudoers.d/eclipse  &&
      apt-get clean  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*'
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: '''en_US.UTF-8'''
    - Key: LANGUAGE
      Value: '''en_US:en'''
    - Key: LC_ALL
      Value: '''en_US.UTF-8'''
    Name: env
  - CmdLine:
    - echo "X11UseLocalhost no" >> /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -s -L "$DOWNLOAD_URL" | tar xz -C $INSTALLATION_DIR/  && ln -s $INSTALLATION_DIR/eclipse/eclipse
      /usr/bin/
    Name: run
    PrependShell: true
  - CmdLine:
    - eclipse -clean -purgeHistory -application org.eclipse.equinox.p2.director -noSplash
      -repository http://download.eclipse.org/releases/neon/,http://download.eclipse.org/technology/subversive/4.0/update-site/,http://community.polarion.com/projects/subversive/download/eclipse/6.0/neon-site/  -installIUs
      org.eclipse.team.svn.feature.group,org.polarion.eclipse.team.svn.connector.feature.group,org.eclipse.cdt.testsrunner.feature.feature.group,org.polarion.eclipse.team.svn.connector.svnkit18.feature.group
      -vmargs -Declipse.p2.mirrors=true -Djava.net.preferIPv4Stack=true
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R eclipse:eclipse $INSTALLATION_DIR/eclipse &&  chmod -R 775 $INSTALLATION_DIR/eclipse
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: from ubuntu:xenial
