MetaArgs: null
Stages:
- BaseName: andreptb/oracle-java:8
  Commands:
  - Env:
    - Key: SOLR_VERSION
      Value: 4.4.0
    Name: env
  - Env:
    - Key: SOLR
      Value: solr-$SOLR_VERSION
    Name: env
  - CmdLine:
    - export DEBIAN_FRONTEND=noninteractive &&   apt-get update &&   apt-get -y install
      lsof groovy2 &&   mkdir -p /opt &&   wget -nv --output-document=/opt/$SOLR.tgz
      http://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/$SOLR.tgz &&   tar
      -C /opt --extract --file /opt/$SOLR.tgz &&   rm /opt/$SOLR.tgz &&   ln -s /opt/$SOLR
      /opt/solr
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8983"
  - Name: workdir
    Path: /opt/solr
  - CmdLine:
    - /bin/bash
    - -c
    - /opt/solr/bin/solr -f
    Name: cmd
    PrependShell: false
  From:
    Image: andreptb/oracle-java:8
  Name: ""
  Platform: ""
  SourceCode: FROM andreptb/oracle-java:8
