MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Maintainer: Ando Roots <ando@sqroot.eu>
    Name: maintainer
  - CmdLine:
    - apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      namebench &&   rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - namebench
    - -x
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
