MetaArgs: null
Stages:
- BaseName: dmccloskey/glpk:latest
  Commands:
  - Maintainer: Douglas McCloskey <dmccloskey87@gmail.com>
    Name: maintainer
  - Name: user
    User: root
  - CmdLine:
    - "apt-get update && apt-get upgrade -y \t&& apt-get install -y \tpython \tpython-pip
      \tpython-scipy \tpython-numpy \tpython-pandas \tpython-lxml \tbuild-essential
      \tpython-dev \tswig \t--no-install-recommends \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/
  - CmdLine:
    - "wget http://cs.ru.nl/~wmegchel/optGpSampler/downloads/optGpSampler_1.1_Python_Linux64.tar.gz
      \t&& tar -zxvf optGpSampler_1.1_Python_Linux64.tar.gz"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/optGpSampler-1.1
  - CmdLine:
    - python2.7 setup.py install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/
  - CmdLine:
    - wget http://cs.ru.nl/~wmegchel/optGpSampler/downloads/optGpSampler_1.1_Python_Linux64_dependencies.tar.gz   &&
      tar -zxvf optGpSampler_1.1_Python_Linux64_dependencies.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/optGpSampler_1.1_Python_Linux64_dependencies
  - CmdLine:
    - mv libs /usr/local/lib/python2.7/dist-packages/optGpSampler   && mv models /usr/local/lib/python2.7/dist-packages/optGpSampler
    Name: run
    PrependShell: true
  - Env:
    - Key: PYTHONPATH
      Value: /usr/local/lib/python2.7/dist-packages/optGpSampler/libs:$PYTHONPATH
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/local/lib/python2.7/dist-packages/optGpSampler/libs:$LD_LIBRARY_PATH
    Name: env
  - Env:
    - Key: OPTGPSAMPLER_LIBS_DIR
      Value: /usr/local/lib/python2.7/dist-packages/optGpSampler/libs
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/local/lib:$LD_LIBRARY_PATH
    Name: env
  - CmdLine:
    - ldconfig
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - "rm -rf /usr/local/optGpSampler_1.1_Python_Linux64.tar.gz \t&& rm -rf /usr/local/optGpSampler-1.1
      \t&& rm -rf /usr/local/optGpSampler_1.1_Python_Linux64_dependencies.tar.gz \t&&
      rm -rf /usr/local/optGpSampler_1.1_Python_Linux64_dependencies"
    Name: run
    PrependShell: true
  - CmdLine:
    - "pip install python-libsbml \t&& pip install cobra \t&& pip install escher \t&&
      pip install --upgrade"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $HOME
  - Name: user
    User: user
  From:
    Image: dmccloskey/glpk:latest
  Name: ""
  Platform: ""
  SourceCode: FROM dmccloskey/glpk:latest
