MetaArgs: null
Stages:
- As: build
  BaseName: node:9.4.0
  Commands:
  - Key: COMMIT_HASH
    Name: arg
    Value: null
  - Key: DATE
    Name: arg
    Value: null
  - Name: workdir
    Path: ./src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Name: workdir
    Path: ./frontend
  - CmdLine:
    - if [ "$(uname -m)" = "ppc64le" ]; then         wget -O /tmp/phantomjs-2.1.1-linux-ppc64.tar.bz2
      https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs-2.1.1-linux-ppc64.tar.bz2         &&
      tar xf /tmp/phantomjs-2.1.1-linux-ppc64.tar.bz2 -C /usr/local/         && ln
      -s /usr/local/phantomjs-2.1.1-linux-ppc64/bin/phantomjs /usr/bin/phantomjs;     fi
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install && npm run postinstall
    Name: run
    PrependShell: true
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ./server/dist &&     echo ${COMMIT_HASH} > ./server/dist/COMMIT_HASH
      &&     echo ${DATE} > ./server/dist/BUILD_DATE
    Name: run
    PrependShell: true
  - CmdLine:
    - npm i -D license-checker
    Name: run
    PrependShell: true
  - CmdLine:
    - node gen_licenses . && node gen_licenses server &&     cat dependency-licenses.txt
      >> server/dependency-licenses.txt
    Name: run
    PrependShell: true
  From:
    Image: node:9.4.0
  Name: build
  Platform: ""
  SourceCode: FROM node:9.4.0 as build
- BaseName: node:9.4.0-alpine
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - ./src/frontend/server
    - /server
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - ./src/frontend/build
    - /client
  - Name: workdir
    Path: /server
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  - Env:
    - Key: API_SERVER_ADDRESS
      Value: http://localhost:3001
    Name: env
  - Env:
    - Key: MINIO_END_POINT
      Value: minio-service.kubeflow
    Name: env
  - Env:
    - Key: MINIO_PORT
      Value: "9000"
    Name: env
  - Env:
    - Key: MINIO_ACCESS_KEY
      Value: minio
    Name: env
  - Env:
    - Key: MINIO_SECRET_KEY
      Value: minio123
    Name: env
  - Env:
    - Key: MINIO_SECURE
      Value: "false"
    Name: env
  - Env:
    - Key: MINIO_REGION
      Value: ap-southeast-1
    Name: env
  - CmdLine:
    - node dist/server.js ../client/ 3000
    Name: cmd
    PrependShell: true
  From:
    Image: node:9.4.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:9.4.0-alpine
