MetaArgs: null
Stages:
- BaseName: alpine:3.1
  Commands:
  - CmdLine:
    - apk add --update python &&     rm /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/python
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.1
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.1
