MetaArgs: null
Stages:
- BaseName: node:7
  Commands:
  - Maintainer: Anders Hansson <anders@programlabbet.se>
    Name: maintainer
  - CmdLine:
    - apt-get update -y && apt-get install -y rsync && apt-get clean -y
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g yarn
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn global add elm@0.18.0
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn global add elm-github-install
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /app /app-sync
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: volume
    Volumes:
    - /app-sync
  - Name: workdir
    Path: /app-sync
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.sh'
    - /
  - CmdLine:
    - chmod 755 /*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - -c
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: node:7
  Name: ""
  Platform: ""
  SourceCode: FROM node:7
