MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - Env:
    - Key: RAILS_ENV
      Value: '"production"'
    - Key: NODE_ENV
      Value: '"production"'
    - Key: NPM_CONFIG_PRODUCTION
      Value: '"false"'
    - Key: RUNTIME_PACKAGES
      Value: '"bash ruby ruby-irb ruby-json ruby-rake ruby-bigdecimal ruby-io-console
        ruby-dev nodejs yarn libxml2-dev libxslt-dev mariadb-client-libs tzdata py-pip"'
    - Key: DEV_PACKAGES
      Value: '"build-base mariadb-dev"'
    Name: env
  - CmdLine:
    - apk add --update --no-cache $RUNTIME_PACKAGES &&     pip install --no-cache-dir
      awscli &&     mkdir /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - /app/Gemfile
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile.lock
    - /app/Gemfile.lock
  - CmdLine:
    - apk add --update --virtual build-dependencies --no-cache $DEV_PACKAGES &&     gem
      install bundler --no-document &&     bundle config build.nokogiri --use-system-libraries
      &&     bundle install --without development test heroku &&     apk del build-dependencies
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /app/package.json
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - yarn.lock
    - /app/yarn.lock
  - CmdLine:
    - yarn install --network-concurrency 1 &&     yarn cache clean
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - yarn run build &&     bundle exec rake assets:precompile DATABASE_URL=nulldb://localhost
      SECRET_KEY_BASE=secret_key_base
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - ./docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - bundle
    - exec
    - puma
    - -C
    - config/puma.rb
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
