MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - CmdLine:
    - apk upgrade -U &&     apk add --update --no-cache         curl bash &&     apk
      add --update --no-cache         autoconf         bison         make         g++         bison         libxml2-dev
    Name: run
    PrependShell: true
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
