MetaArgs: null
Stages:
- BaseName: python:3.6
  Commands:
  - Env:
    - Key: BUILD_PACKAGES
      Value: '"curl build-essential python3-dev ca-certificates libssl-dev libffi-dev"'
    Name: env
  - Env:
    - Key: PACKAGES
      Value: '"git gcc make build-essential python3-dev python3-reportlab"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /crypto/requirements.txt
  - CmdLine:
    - "apt-get update && apt-get install -y $BUILD_PACKAGES $PACKAGES     && pip3
      install --no-cache-dir -U -I -r /crypto/requirements.txt \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  From:
    Image: python:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6
