MetaArgs: null
Stages:
- BaseName: maciver40/ubuntu-base
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"robert@eisenmann.email"'
    Name: label
  - Name: expose
    Ports:
    - "14443"
  - CmdLine:
    - wget -O - https://repo.jotta.us/public.gpg | apt-key add - &&     echo "deb
      https://repo.jotta.us/debian debian main" | tee /etc/apt/sources.list.d/jotta-cli.list
      &&     apt-get update && apt-get install -y jotta-cli &&     cp /etc/jottad/config.ini.bak
      /etc/jottad/config.ini
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - Name: volume
    Volumes:
    - /mnt/user/backup
  From:
    Image: maciver40/ubuntu-base
  Name: ""
  Platform: ""
  SourceCode: FROM maciver40/ubuntu-base
