MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - Env:
    - Key: PYTHONIOENCODING
      Value: UTF-8
    Name: env
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - Env:
    - Key: DEBUG
      Value: "1"
    Name: env
  - CmdLine:
    - apk update && apk --no-cache upgrade && apk --no-cache add --virtual build-deps
      curl python3 py3-psycopg2 bash git diffutils libffi-dev py3-cffi python3-dev
      gcc musl-dev openssl-dev make gettext
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sfn /usr/bin/pip3 /usr/bin/pip
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sfn /usr/bin/python3 /usr/bin/python
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://sentry.io/get-cli/ | bash
    Name: run
    PrependShell: true
  - CmdLine:
    - pip --no-cache install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -e git+https://yourlabs.io/oss/processcontroller.git#egg=processcontroller
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -e git+https://yourlabs.io/oss/clilabs.git#egg=clilabs
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -e git+https://yourlabs.io/oss/autoplay.git#egg=autoplay
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /requirements.txt
  - CmdLine:
    - pip --no-cache install --upgrade -r /requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/*
    - /bin
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
