MetaArgs: null
Stages:
- BaseName: centos:centos7
  Commands:
  - CmdLine:
    - INSTALL_PKGS="omping" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS
      &&     yum clean all
    Name: run
    PrependShell: true
  From:
    Image: centos:centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7
