MetaArgs: null
Stages:
- BaseName: jjanzic/docker-python3-opencv:opencv-3.4.1
  Commands:
  - Key: SCENEDETECT_VERSION
    Name: arg
    Value: '""'
  - CmdLine:
    - "apt-get install -y python-pip &&     if [ \"$SCENEDETECT_VERSION\" = \"\" ];
      then       pip install scenedetect; \t  else       pip install scenedetect==\"$SCENEDETECT_VERSION\";
      \t  fi"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apt-transport-https     && wget -q -O - https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt
      | apt-key add -     && apt-get update     && apt-get install -y mkvtoolnix
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - scenedetect
    Name: entrypoint
    PrependShell: false
  From:
    Image: jjanzic/docker-python3-opencv:opencv-3.4.1
  Name: ""
  Platform: ""
  SourceCode: FROM jjanzic/docker-python3-opencv:opencv-3.4.1
