MetaArgs: null
Stages:
- BaseName: mprisco/ubuntu-java8-scala
  Commands:
  - Maintainer: Michele Prisco <michele.prisco@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g'
      -i /etc/pam.d/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -m -d /home/jenkins -s /bin/bash jenkins &&     echo "jenkins:jenkins"
      | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "jenkins  ALL=(ALL)  ALL" >> etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get clean
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    Name: cmd
    PrependShell: false
  From:
    Image: mprisco/ubuntu-java8-scala
  Name: ""
  Platform: ""
  SourceCode: FROM mprisco/ubuntu-java8-scala
