MetaArgs: null
Stages:
- As: download
  BaseName: alpine
  Commands:
  - Name: workdir
    Path: /root/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz
    - /root/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
    - /root/
  - CmdLine:
    - gzip -d GeoLite2-Country.mmdb.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - gzip -d GeoLite2-City.mmdb.gz
    Name: run
    PrependShell: true
  From:
    Image: alpine
  Name: download
  Platform: ""
  SourceCode: FROM alpine AS download
- BaseName: mpolden/echoip
  Commands:
  - Name: workdir
    Path: /opt/echoip
  - Chown: ""
    From: download
    Name: copy
    SourcesAndDest:
    - /root/GeoLite2*
    - /opt/echoip/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - index.html
    - /opt/echoip/index.html
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /opt/echoip/echoip
    - --country-db
    - /opt/echoip/GeoLite2-Country.mmdb
    - --city-db
    - /opt/echoip/GeoLite2-City.mmdb
    - --port-lookup
    - --reverse-lookup
    - --trusted-header
    - CF-Connecting-IP
    - --trusted-header
    - X-Forwarded-For
    - --template
    - /opt/echoip/index.html
    Name: cmd
    PrependShell: false
  From:
    Image: mpolden/echoip
  Name: ""
  Platform: ""
  SourceCode: FROM mpolden/echoip
