MetaArgs:
- DefaultValue: 0.12.19
  Key: TERRAFORM_VERSION
  ProvidedValue: null
  Value: 0.12.19
Stages:
- BaseName: hashicorp/terraform:${TERRAFORM_VERSION}
  Commands:
  - CmdLine:
    - apk update
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add     python3     docker     freetype     graphviz     npm     ttf-opensans     zip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install -U pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install awscli
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add     gcc     libffi-dev     musl-dev     openssl-dev     make     python3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install docker-compose
    Name: run
    PrependShell: true
  - CmdLine: null
    Name: entrypoint
    PrependShell: false
  From:
    Image: hashicorp/terraform:${TERRAFORM_VERSION}
  Name: ""
  Platform: ""
  SourceCode: FROM hashicorp/terraform:${TERRAFORM_VERSION}
