MetaArgs: null
Stages:
- BaseName: node:7.9
  Commands:
  - Maintainer: Milan Aleksic <milanaleksic@gmail.com>
    Name: maintainer
  - CmdLine:
    - npm install -g browserify@14.3.0
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install antlr4@4.7.0
    Name: run
    PrependShell: true
  - CmdLine:
    - browserify
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:7.9
  Name: ""
  Platform: ""
  SourceCode: FROM node:7.9
