MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: dewist s.r.o. dewist@dewist.com
    Name: maintainer
  - Name: workdir
    Path: /data
  - CmdLine:
    - "apt-get update && apt-get install -yy --no-install-recommends \tpython \tpython-pip
      \tpython-dev \tpython-wheel \tpython-setuptools     ssh \tvim \tgcc \tcurl \tzip
      \tunzip \t&& pip install \tboto \tboto3 \tawscli \tansible==2.4.1.0 \t&& apt-get
      clean"
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip /tmp/terraform.zip -d /usr/local/bin/
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/terraform
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ansible.cfg
    - /root/.ansible.cfg
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
