MetaArgs: null
Stages:
- As: static-docker-source
  BaseName: docker:latest
  Commands: null
  From:
    Image: docker:latest
  Name: static-docker-source
  Platform: ""
  SourceCode: FROM docker:latest as static-docker-source
- BaseName: debian:stretch
  Commands:
  - Chown: ""
    From: static-docker-source
    Name: copy
    SourcesAndDest:
    - /usr/local/bin/docker
    - /usr/bin/docker
  - CmdLine:
    - apt-get update && apt-get -y upgrade &&     apt-get -y install     apt-transport-https     ca-certificates     curl     gettext     gnupg2     software-properties-common     &&     rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stretch
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stretch
