MetaArgs: null
Stages:
- BaseName: php:7.3-apache
  Commands:
  - Name: volume
    Volumes:
    - /var/www/html/mods
  - Name: expose
    Ports:
    - "443"
    - "80"
  - CmdLine:
    - mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update     && apt-get install -y     libzip-dev zlib1g-dev     && docker-php-ext-install
      zip
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "LogLevel debug" >> apache2.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/
    - /var/www/html/
  - CmdLine:
    - mkdir -p /tmp/simple-modpack && chown www-data:www-data /tmp/simple-modpack
      && chmod a+rwx -R /tmp/simple-modpack
    Name: run
    PrependShell: true
  From:
    Image: php:7.3-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-apache
