MetaArgs: null
Stages:
- BaseName: debian:stable-slim
  Commands:
  - Maintainer: Gauthier C.
    Name: maintainer
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: OC_VERSION
      Value: '"v3.10.0"'
    Name: env
  - Env:
    - Key: OC_RELEASE
      Value: '"openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/openshift/origin/releases/download/$OC_VERSION/$OC_RELEASE.tar.gz
    - /opt/oc/release.tar.gz
  - CmdLine:
    - tar --strip-components=1 -xzvf  /opt/oc/release.tar.gz -C /opt/oc/ &&     mv
      /opt/oc/oc /usr/bin/ &&     rm -rf /opt/oc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y ca-certificates
    Name: run
    PrependShell: true
  From:
    Image: debian:stable-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stable-slim
