MetaArgs: null
Stages:
- As: build
  BaseName: golang:1.12
  Commands:
  - Name: workdir
    Path: $GOPATH/src/github.com/Harrison-Miller/xpack-license-monitor
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get -d -v ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o xpack-license-monitor -i -v
      ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - cp xpack-license-monitor / && cp -r templates /
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12
  Name: build
  Platform: ""
  SourceCode: FROM golang:1.12 AS build
- BaseName: alpine
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /xpack-license-monitor
    - /
  - CmdLine:
    - mkdir -p /config /templates
    Name: run
    PrependShell: true
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /templates/
    - /templates
  - Name: volume
    Volumes:
    - /config
  - Env:
    - Key: DOMAIN
      Value: '"example.com"'
    Name: env
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /xpack-license-monitor
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
