MetaArgs: null
Stages:
- BaseName: wlniao/dotnet:2.1.2
  Commands:
  - Env:
    - Key: WLN_LISTEN_PORT
      Value: "80"
    Name: env
  - CmdLine:
    - dotnet
    - proxy.dll
    Name: entrypoint
    PrependShell: false
  From:
    Image: wlniao/dotnet:2.1.2
  Name: ""
  Platform: ""
  SourceCode: FROM wlniao/dotnet:2.1.2
