MetaArgs: null
Stages:
- BaseName: golang:1.4.1
  Commands:
  - Name: workdir
    Path: /go/src/github.com/tonistiigi/dnsdock
  - CmdLine:
    - go get -v github.com/tools/godep
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Godeps
    - /go/src/github.com/tonistiigi/dnsdock/Godeps
  - CmdLine:
    - godep restore
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/tonistiigi/dnsdock/
  - CmdLine:
    - go install -ldflags "-X main.version `git describe --tags HEAD``[ $(git status
      --porcelain --untracked-files=no | wc -l) -gt 0 ] && echo "-dirty"`" ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - /go/bin/dnsdock
    Name: entrypoint
    PrependShell: false
  From:
    Image: golang:1.4.1
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.4.1
