MetaArgs: null
Stages:
- BaseName: yzotov/altlinux-sisyphus:20150602
  Commands:
  - Maintainer: Zotov Yuriy <yura.zotov@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y dist-upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y clean
    Name: run
    PrependShell: true
  From:
    Image: yzotov/altlinux-sisyphus:20150602
  Name: ""
  Platform: ""
  SourceCode: FROM yzotov/altlinux-sisyphus:20150602
