MetaArgs: null
Stages:
- BaseName: hugome/docker-dmp-ksp
  Commands:
  - Name: workdir
    Path: /DMPServer/Plugins/
  - CmdLine:
    - apt-get update &&     apt-get install -y wget &&     wget http://godarklight.info.tm/dmp/downloads/plugins/DMPServerListReporter2/DMPServerListReporter.dll
      &&     apt-get remove -y --purge wget &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  From:
    Image: hugome/docker-dmp-ksp
  Name: ""
  Platform: ""
  SourceCode: FROM hugome/docker-dmp-ksp
