MetaArgs: null
Stages:
- BaseName: php:7.2.6-apache-stretch
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - apache2.conf
    - /etc/apache2/apache2.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /usr/local/bin/entrypoint
  - CmdLine:
    - apt-get update &&     apt-get install -y zlib1g-dev dumb-init &&     docker-php-ext-install
      zip &&     apt-get install -y --no-install-recommends unzip libssl-dev libpcre3
      libpcre3-dev &&     cd /tmp &&     curl -sSL -o php7.zip https://github.com/websupport-sk/pecl-memcache/archive/php7.zip
      &&     unzip php7 &&     cd pecl-memcache-php7 &&     /usr/local/bin/phpize
      &&     ./configure --with-php-config=/usr/local/bin/php-config &&     make &&
      make install &&     echo "extension=memcache.so" > /usr/local/etc/php/conf.d/ext-memcache.ini
      &&     rm -rf /tmp/pecl-memcache-php7 php7.zip &&     apt-get install -y memcached
      netcat &&     service memcached start &&     chmod +x /usr/local/bin/entrypoint
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/html
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - dumb-init
    - entrypoint
    Name: entrypoint
    PrependShell: false
  From:
    Image: php:7.2.6-apache-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2.6-apache-stretch
