MetaArgs: null
Stages:
- BaseName: land007/ubuntu:latest
  Commands:
  - Maintainer: Yiqiu Jia <yiqiujia@hotmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: USER
      Value: ubuntu
    Name: env
  - Env:
    - Key: HOME
      Value: /home/$USER
    Name: env
  - CmdLine:
    - adduser $USER --disabled-password
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update     && apt-get install -y --no-install-recommends         ubuntu-desktop         unity-lens-applications         gnome-panel         metacity         nautilus         gedit         gnome-terminal         sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y         supervisor         net-tools         curl         git         pwgen         libtasn1-3-bin         libglu1-mesa     &&
      apt-get autoclean     && apt-get autoremove     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - tigervnc-1.8.0.x86_64
    - /
  - CmdLine:
    - git clone https://github.com/novnc/noVNC.git $HOME/noVNC
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/kanaka/websockify $HOME/noVNC/utils/websockify
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    - $HOME/ngrok/ngrok.zip
  - CmdLine:
    - unzip -o $HOME/ngrok/ngrok.zip -d $HOME/ngrok && rm $HOME/ngrok/ngrok.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisor.conf
    - /etc/supervisor/conf.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - xsession
    - $HOME/.xsession
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - startup.sh
    - $HOME
  - CmdLine:
    - chmod +x /usr/bin/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /home/ubuntu/startup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key
      add -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |
      sudo tee /etc/apt/sources.list.d/google-chrome.list
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get update  && sudo apt-get install -y google-chrome-stable
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/ubuntu/.config/google-chrome/Default
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /home/ubuntu/.config/google-chrome/Default /home/ubuntu/.config/google-chrome/Default_
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:hzwhuang/ss-qt5 &&   apt-get update &&   apt-get install
      -y shadowsocks-qt5
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - check.sh
    - /
  - CmdLine:
    - sed -i 's/\r$//' /check.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /check.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+x /etc/sudoers && echo "ubuntu    ALL=(ALL:ALL) ALL" >> /etc/sudoers
      && chmod u-x /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y fcitx fcitx-googlepinyin fcitx-table-wbpy fcitx-pinyin fcitx-sunpinyin
    Name: run
    PrependShell: true
  - CmdLine:
    - echo $(date "+%Y-%m-%d_%H:%M:%S") >> /.image_times
    Name: run
    PrependShell: true
  - CmdLine:
    - echo $(date "+%Y-%m-%d_%H:%M:%S") > /.image_time
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "land007/ubuntu-unity-novnc" >> /.image_names
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "land007/ubuntu-unity-novnc" > /.image_name
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4040"
    - "5901"
    - "6080"
  - CmdLine:
    - echo "/check.sh /home/ubuntu/.config/google-chrome/Default" >> /start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "nohup /home/ubuntu/startup.sh > /tmp/startup.out 2>&1 &" >> /start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "sleep 2" >> /start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "cat /home/ubuntu/password.txt || true" >> /start.sh
    Name: run
    PrependShell: true
  From:
    Image: land007/ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM land007/ubuntu:latest
