MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Marco van den Oever <marco@flyingpie.nl>
    Name: maintainer
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y   apt-transport-https   ca-certificates   curl   software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
      $(lsb_release -cs) stable"
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y   docker-ce   fish   libcurl3   libicu55   libunwind8   toilet
      toilet-fonts   vim   wget
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q $(curl -s https://api.github.com/repos/powershell/powershell/releases/latest
      | grep 'browser_' | grep 'ubuntu1.16' | cut -d\" -f4)
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg -i $(ls / | grep powershell)
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - image/root
    - /root
  - CmdLine:
    - chmod +x /root/bin/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - image/toolbox.sh
    - /toolbox.sh
  - CmdLine:
    - chmod +x /toolbox.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "Build: $(date) @ $HOSTNAME" >> /build-info.txt'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root"'
  - CmdLine:
    - /toolbox.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
