MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Sinevia  <info@sinevia.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -qq openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'root:root' | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install python-software-properties python g++ make -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install software-properties-common wget unzip -y
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:chris-lea/node.js -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install nodejs -y
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /site
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/app.js
    - /site/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/package.json
    - /site/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/run_site.sh
    - /
  - Name: workdir
    Path: /site
  - CmdLine:
    - cd /site
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Name: expose
    Ports:
    - "22"
    - "80"
  - CmdLine:
    - sh
    - /run_site.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
