MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: McMakler <admin@mcmakler.de>
    Name: maintainer
  - Env:
    - Key: HUGO_VERSION
      Value: 0.20.7
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - /tmp
  - CmdLine:
    - tar -xf /tmp/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C /tmp     && mkdir -p
      /usr/local/sbin     && mv /tmp/hugo /usr/local/sbin/hugo     && rm -rf /tmp/hugo_${HUGO_VERSION}_linux_amd64
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: workdir
    Path: /app
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
