MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Mickaël Perrin <dev@mickaelperrin.fr>
    Name: maintainer
  - CmdLine:
    - echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories;     echo
      "http://dl-3.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories;     echo
      "http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories;     echo
      "http://dl-5.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/
      shadow
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache curl &&     curl -L http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz
      | tar zxv -C /tmp &&     cd /tmp/PyYAML-3.11 &&     python setup.py --without-libyaml
      install &&     apk del curl
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache bash
    Name: run
    PrependShell: true
  - Key: UNISON_VERSION
    Name: arg
    Value: 2.48.4
  - CmdLine:
    - apk add --no-cache --virtual .build-dependencies build-base curl &&     apk
      add --no-cache inotify-tools &&     apk add --no-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/
      ocaml &&     curl -L https://github.com/bcpierce00/unison/archive/$UNISON_VERSION.tar.gz
      | tar zxv -C /tmp &&     cd /tmp/unison-${UNISON_VERSION} &&     sed -i -e 's/GLIBC_SUPPORT_INOTIFY
      0/GLIBC_SUPPORT_INOTIFY 1/' src/fsmonitor/linux/inotify_stubs.c &&     make
      UISTYLE=text NATIVE=true STATIC=true &&     cp src/unison src/unison-fsmonitor
      /usr/local/bin &&     apk del .build-dependencies ocaml &&     rm -rf /tmp/unison-${UNISON_VERSION}
    Name: run
    PrependShell: true
  - Env:
    - Key: DOCKERGEN_VERSION
      Value: 0.7.3
    Name: env
  - CmdLine:
    - apk add --no-cache curl &&     curl -L https://github.com/jwilder/docker-gen/releases/download/$DOCKERGEN_VERSION/docker-gen-linux-amd64-$DOCKERGEN_VERSION.tar.gz
      | tar -C /usr/local/bin -xzv &&     apk del curl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - mkdir -p /sync-entrypoint.d  && chmod +x /entrypoint.sh  && mkdir -p /etc/supervisor.conf.d
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - volumes.tmpl
    - /volumes.tmpl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_sync.py
    - /config_sync.py
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisord.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisor.unison.tpl.conf
    - /etc/supervisor.unison.tpl.conf
  - Env:
    - Key: TZ
      Value: '"Europe/Paris"'
    - Key: LANG
      Value: '"C.UTF-8"'
    Name: env
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
