MetaArgs: null
Stages:
- As: build
  BaseName: centos:7
  Commands:
  - CmdLine:
    - curl -Ls "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%2B28/OpenJDK11-jre_x64_linux_hotspot_11_28.tar.gz"
      | tar zx
    Name: run
    PrependShell: true
  - CmdLine:
    - mv "/jdk-"* /openjdk &&   pushd /openjdk &&   mkdir -m 777 app &&   mkdir -m
      777 tmp &&   pushd bin &&   find . ! -name 'java' -type f -exec rm -f {} + &&   popd
      &&   rm -rf     conf/security/{README.txt,limited}     include     legal     &&   true
    Name: run
    PrependShell: true
  From:
    Image: centos:7
  Name: build
  Platform: ""
  SourceCode: FROM centos:7 AS build
- BaseName: scratch
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /lib64/libz.so.1
    - /lib64/libpthread.so.0
    - /lib64/libdl.so.2
    - /lib64/libc.so.6
    - /lib64/ld-linux-x86-64.so.2
    - /lib64/libm.so.6
    - /lib64/librt.so.1
    - /lib64/
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /openjdk/
    - /
  - CmdLine:
    - /bin/java
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -version
    Name: cmd
    PrependShell: false
  - Name: user
    User: "1001"
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
