MetaArgs: null
Stages:
- BaseName: python:2.7-alpine
  Commands:
  - Maintainer: Chris Weyl <cweyl@alumni.drew.edu>
    Name: maintainer
  - CmdLine:
    - pip --no-cache-dir install vim-vint
    Name: run
    PrependShell: true
  - CmdLine:
    - vint
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:2.7-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7-alpine
