MetaArgs: null
Stages:
- BaseName: zenika/alpine-maven
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - ./
  - CmdLine:
    - mvn clean install -DskipTests
    Name: run
    PrependShell: true
  From:
    Image: zenika/alpine-maven
  Name: ""
  Platform: ""
  SourceCode: FROM zenika/alpine-maven
- BaseName: anapsix/alpine-java
  Commands:
  - CmdLine:
    - mkdir ./app/
    Name: run
    PrependShell: true
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /usr/src/app/UserService/target/release/
    - ./app/
  - Name: workdir
    Path: ./app
  - CmdLine:
    - /opt/jdk/bin/java
    - -Xmx2048m
    - -jar
    - UserService.jar
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "8082"
  From:
    Image: anapsix/alpine-java
  Name: ""
  Platform: ""
  SourceCode: FROM anapsix/alpine-java
