MetaArgs: null
Stages:
- BaseName: openjdk:8-jdk
  Commands:
  - Env:
    - Key: ANDROID_COMPILE_SDK
      Value: '"25"'
    Name: env
  - Env:
    - Key: ANDROID_BUILD_TOOLS
      Value: '"24.0.0"'
    Name: env
  - Env:
    - Key: ANDROID_SDK_TOOLS
      Value: '"24.4.1"'
    Name: env
  - Env:
    - Key: ANDROID_SDK_LICENSE
      Value: '"d56f5187479451eabf01fb78af6dfcb131a6481e"'
    Name: env
  - Env:
    - Key: ANDROID_SDK_PREVIEW_LICENSE
      Value: '"84831b9409646a918e30573bab4c9c91346d8abd"'
    Name: env
  - Env:
    - Key: ANDROID_HOME
      Value: /android-sdk-linux
    Name: env
  - CmdLine:
    - apt-get --quiet update --yes && apt-get --quiet install --yes wget tar unzip
      lib32stdc++6 lib32z1 && wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r${ANDROID_SDK_TOOLS}-linux.tgz
      && tar --extract --gzip --file=android-sdk.tgz && mkdir -p android-sdk-linux/licenses
      && echo ${ANDROID_SDK_LICENSE} >> android-sdk-linux/licenses/android-sdk-license
      && echo ${ANDROID_SDK_PREVIEW_LICENSE} >> android-sdk-linux/licenses/android-sdk-preview-license
      && echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all
      --filter android-${ANDROID_COMPILE_SDK} && echo y | android-sdk-linux/tools/android
      --silent update sdk --no-ui --all --filter platform-tools && echo y | android-sdk-linux/tools/android
      --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS}
      && echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all
      --filter extra-android-m2repository && echo y | android-sdk-linux/tools/android
      --silent update sdk --no-ui --all --filter extra-google-google_play_services
      && echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all
      --filter extra-google-m2repository && export PATH=$PATH:${ANDROID_HOME}/platform-tools/
      && rm android-sdk.tgz
    Name: run
    PrependShell: true
  From:
    Image: openjdk:8-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jdk
