MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - CmdLine:
    - rm -rf /var/cache/apk/* &&     rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apk update
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache git ruby python
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install node-sass
    Name: run
    PrependShell: true
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
