MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./idle.sh
    - /idle.sh
  - CmdLine:
    - sh
    - /idle.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
