MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Maintainer: Fabrizio Steiner <stffabi@users.noreply.github.com>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache postgresql tzdata su-exec openssl &&     mkdir /backup
    Name: run
    PrependShell: true
  - CmdLine:
    - GOCROND_VERSION=0.3.0     && wget -O /usr/local/bin/go-crond https://github.com/webdevops/go-crond/releases/download/$GOCROND_VERSION/go-crond-64-linux     &&
      chmod +x /usr/local/bin/go-crond
    Name: run
    PrependShell: true
  - Env:
    - Key: UID
      Value: "65534"
    - Key: GID
      Value: "65534"
    - Key: CRON_TIME
      Value: '"0 0 * * *"'
    - Key: PG_DB
      Value: '"postgres"'
    - Key: PG_HOST
      Value: '"postgres"'
    - Key: PG_PORT
      Value: '"5432"'
    - Key: PG_USER
      Value: '"root"'
    - Key: PG_PASS
      Value: '""'
    - Key: EXTRA_OPTS
      Value: '"--inserts"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /run.sh
  - Name: volume
    Volumes:
    - /backup
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
