MetaArgs: null
Stages:
- BaseName: bitriseio/docker-bitrise-base:latest
  Commands:
  - Name: workdir
    Path: /opt/meteor/deps
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mongod.service
    - .
  - CmdLine:
    - cp -f /opt/meteor/deps/mongod.service /lib/systemd/system/mongod.service
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927     &&
      echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2
      multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list     && curl -sS
      https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb https://dl.yarnpkg.com/debian/
      stable main" | tee /etc/apt/sources.list.d/yarn.list     && apt-get update     &&
      apt-get install -y yarn mongodb-org     && mkdir -p /data/db
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser --disabled-password --gecos '' meteor     && adduser meteor sudo     &&
      echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    Name: run
    PrependShell: true
  - Name: user
    User: meteor
  - CmdLine:
    - curl https://install.meteor.com/ | sh     && meteor create --full ~/prime_app     &&
      mkdir ~/prime_app_debug     && mkdir ~/prime_app_release     && cd ~/prime_app     &&
      meteor build ~/prime_app_debug --debug     && meteor build ~/prime_app_release
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ~/prime_app_release     && tar xf prime_app.tar.gz     && cd bundle     &&
      (cd programs/server && yarn install)
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/src
  - CmdLine:
    - rm -rf ~/prime*
    Name: run
    PrependShell: true
  From:
    Image: bitriseio/docker-bitrise-base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM bitriseio/docker-bitrise-base:latest
