MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  Commands: null
  From:
    Image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10
