MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Alexis Pereda <alexis@pereda.fr>"'
    Name: label
  - Labels:
    - Key: version
      Value: '"1.0"'
    Name: label
  - Labels:
    - Key: description
      Value: '"toolchain for Debian wheezy i386"'
    Name: label
  - CmdLine:
    - "apt-get update \t&& apt-get install -y --no-install-recommends --no-install-suggests
      \t\tmake cmake git gcc g++ curl \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - catch.hpp
    - /usr/include/catch.hpp
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
