MetaArgs: null
Stages:
- BaseName: centos:centos6
  Commands:
  - Maintainer: FURUSAWA MAKOTO violafuru@gmail.com
    Name: maintainer
  - CmdLine:
    - adduser nes
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /home/nes/.aws; chown nes:nes /home/nes/.aws ;    mkdir /home/nes/kumogata;
      chown nes:nes /home/nes/kumogata
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y git                    openssl openssl-devel                    pcre
      pcre-devel                    zlib zlib-devel                    libxml2 libxml2-devel
      libxslt-devel libffi-devel                    readline-devel                    gcc
      gcc-c++ make tar vim sudo                    nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -Uvh http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm
      ;    yum install -y postgresql.x86_64
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm ;    yum
      --enablerepo=mysql56-community install -y mysql-community-client.x86_64
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -ivh http://ftp.riken.jp/Linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
      ;    yum --enablerepo=epel update epel-release ;    yum install -y python-pip;
      pip install awscli
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./config
    - /home/nes/.aws/config
  - CmdLine:
    - chmod 600 /home/nes/.aws/config; chown nes:nes /home/nes/.aws/config ;    echo
      'complete -C aws_completer aws' >> /home/nes/.bash_profile
    Name: run
    PrependShell: true
  - Name: user
    User: nes
  - CmdLine:
    - git clone https://github.com/sstephenson/rbenv.git /home/nes/.rbenv ;    git
      clone https://github.com/sstephenson/ruby-build.git /home/nes/.rbenv/plugins/ruby-build
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /home/nes/.rbenv/bin:$PATH
    Name: env
  - CmdLine:
    - echo 'eval "$(rbenv init -)"' >> /home/nes/.bash_profile ;    rbenv install
      2.2.2; rbenv global 2.2.2
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo ''gem: --no-rdoc --no-ri'' >> /home/nes/.gemrc;     . /home/nes/.bash_profile;
      gem install bundler'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/nes/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./.gitconfig
    - /home/nes/.gitconfig
  - CmdLine:
    - git clone https://github.com/tonkachi/ryunosu.git;     echo 'set number' >>
      /home/nes/.vimrc;     . /home/nes/.bash_profile; cd /home/nes/ryunosu/; bundle
      install --path vendor/bundle
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: centos:centos6
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos6
