MetaArgs: null
Stages:
- BaseName: rcvn/centos:7.1
  Commands:
  - Maintainer: RCVN nguyen.tuankhanh@rivercrane.vn
    Name: maintainer
  - CmdLine:
    - rpm -Uvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum --enablerepo=remi,remi-php56 -y install php php-common
    Name: run
    PrependShell: true
  - CmdLine:
    - yum --enablerepo=remi,remi-php56 -y install php-mysql php-pear php-gd php-mcrypt
      php-ldap php-xcache php-devel php-mbstring php-pdo php-pecl-xdebug php-pecl-memcache
      php-xml php-process libcurl-devel libxml2-devel mod_ssl pcre-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y erase httpd
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: rcvn/centos:7.1
  Name: ""
  Platform: ""
  SourceCode: FROM rcvn/centos:7.1
