MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-alpine
  Commands:
  - Maintainer: nbarnum <nbarnum@users.noreply.github.com>
    Name: maintainer
  - Key: DRUID_HOME
    Name: arg
    Value: /usr/local/druid
  - Key: DRUID_VERSION
    Name: arg
    Value: 0.9.2
  - CmdLine:
    - mkdir -p $DRUID_HOME &&     wget -q -O - "http://static.druid.io/artifacts/releases/druid-$DRUID_VERSION-bin.tar.gz"       |
      tar zxf - --strip-components 1 -C $DRUID_HOME &&     wget -q -O - "http://static.druid.io/artifacts/releases/mysql-metadata-storage-$DRUID_VERSION.tar.gz"       |
      tar zxf - -C $DRUID_HOME/extensions &&     mkdir -p $DRUID_HOME/var/druid $DRUID_HOME/var/tmp
      &&     sed -i '/druid.extensions.loadList=/s/^/#/' $DRUID_HOME/conf/druid/_common/common.runtime.properties
      &&     sed -i '/druid.zk.service.host=/s/^/#/' $DRUID_HOME/conf/druid/_common/common.runtime.properties
      &&     sed -i '/druid.metadata.storage./s/^/#/' $DRUID_HOME/conf/druid/_common/common.runtime.properties
      &&     apk add --no-cache bash
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - $DRUID_HOME/bin/run.sh
  - Name: volume
    Volumes:
    - $DRUID_HOME/var/druid
  - Name: workdir
    Path: $DRUID_HOME
  - Name: expose
    Ports:
    - 8081-8083
    - "8090"
  - CmdLine:
    - bin/run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-alpine
