MetaArgs: null
Stages:
- BaseName: homeassistant/home-assistant:0.56.2
  Commands:
  - Name: volume
    Volumes:
    - /config
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - apt-get update -y && apt-get install -y python-pip telnet netcat
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_7.x |  bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - pip2 install docopt
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install ps4-waker -g
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install git+https://github.com/vkorn/pyvizio.git@master
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install -I .
    Name: run
    PrependShell: true
  From:
    Image: homeassistant/home-assistant:0.56.2
  Name: ""
  Platform: ""
  SourceCode: FROM homeassistant/home-assistant:0.56.2
