MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Name: expose
    Ports:
    - "9222"
  - CmdLine:
    - google-chrome --headless --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
      --no-sandbox
    Name: cmd
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y wget gnupg &&     wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub
      | apt-key add - &&     echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/
      stable main" >> /etc/apt/sources.list.d/google.list &&     apt-get update &&     apt-get
      install -y google-chrome-stable
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
