MetaArgs: null
Stages:
- BaseName: hunterchung/eg-website-docker
  Commands:
  - Maintainer: Hunter Chung <hchung@zymoresearch.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -yq     build-essential     rabbitmq-server     libxml2-dev     libxslt-dev     geoip-bin     libgeoip-dev     libgeoip1
      && rm -rf /var/lib/apt/lists/* && apt-get clean autoclean && apt-get autoremove
      -y
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U pysam==0.7.8
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U pip
    Name: run
    PrependShell: true
  - CmdLine:
    - hash -r
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U pyopenssl ndg-httpsclient pyasn1
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U django==1.6
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U     geoip     celery==3.1.18     biopython     xlwt     six     inlinestyler     lxml     beautifulsoup4     requests     stopit     pip     subprocess32     kombu==3.0.26     boto3     xlrd     openpyxl
    Name: run
    PrependShell: true
  - CmdLine:
    - pip2 install -U     mock     pandas     awscli
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install_primer3.sh
    - /tmp/install_primer3.sh
  - CmdLine:
    - chmod +x /tmp/install_primer3.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /tmp/install_primer3.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /scripts
  - Env:
    - Key: PYTHONPATH
      Value: ${PYTHONPATH}:/scripts
    Name: env
  - Env:
    - Key: PATH
      Value: ${PATH}:/usr/share/s3cmd:/usr/share/primer3/src
    Name: env
  - Env:
    - Key: DJANGO_SETTINGS_MODULE
      Value: Bisulfite_Primer_Seeker.settings
    Name: env
  - Env:
    - Key: C_FORCE_ROOT
      Value: "true"
    Name: env
  - Env:
    - Key: PRIMER3_PATH
      Value: /usr/share/primer3/src
    Name: env
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - python /scripts/manage.py runserver 0.0.0.0:8000
    Name: cmd
    PrependShell: true
  From:
    Image: hunterchung/eg-website-docker
  Name: ""
  Platform: ""
  SourceCode: FROM hunterchung/eg-website-docker
