MetaArgs: null
Stages:
- BaseName: shadowrobot/aurora-molecule:xenial
  Commands:
  - Maintainer: '"Shadow Robot''s Software Team <software@shadowrobot.com>"'
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Ubuntu Xenial image contains Ansible, Molecule and Docker driver"'
    - Key: Vendor
      Value: '"Shadow Robot"'
    - Key: Version
      Value: '"1.0"'
    Name: label
  - Key: ml_docker_aurora_branch
    Name: arg
    Value: null
  - Env:
    - Key: ml_docker_aurora_branch
      Value: ${ml_docker_aurora_branch:-"master"}
    Name: env
  - Env:
    - Key: ml_docker_aurora_script
      Value: '"https://raw.githubusercontent.com/shadow-robot/aurora/$ml_docker_aurora_branch/bin/run-ansible.sh"'
    Name: env
  - CmdLine:
    - set -x &&         echo "Installing Docker" &&     wget -O /tmp/oneliner "$(
      echo "$ml_docker_aurora_script" | sed 's/#/%23/g' )" &&     chmod 755 /tmp/oneliner
      &&     /tmp/oneliner install_software --debug-branch $ml_docker_aurora_branch
      software=[docker] &&         echo "Clean up" &&     apt-get clean &&     rm
      -rf         /var/lib/apt/lists/*         /tmp/*         /var/tmp/*         /root/.ansible         /root/.gitconfig         /root/.cache
    Name: run
    PrependShell: true
  From:
    Image: shadowrobot/aurora-molecule:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM shadowrobot/aurora-molecule:xenial
