MetaArgs: null
Stages:
- As: node
  BaseName: node:8.15
  Commands:
  - CmdLine:
    - apt-get update &&    apt-get install -y unzip &&    rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - wget -qnv https://chromedriver.storage.googleapis.com/LATEST_RELEASE -O - |
      wget -q "https://chromedriver.storage.googleapis.com/`cat`/chromedriver_linux64.zip"
      &&   unzip chromedriver_linux64.zip &&   chmod +x chromedriver && mv chromedriver
      /usr/bin/
    Name: run
    PrependShell: true
  From:
    Image: node:8.15
  Name: node
  Platform: ""
  SourceCode: FROM node:8.15 as node
- BaseName: ruby:2.5.3
  Commands:
  - CmdLine:
    - mkdir -p /var/log/supervisor
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
      add - &&   sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/
      stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&   apt-get update
      &&   apt-get install -y google-chrome-stable
    Name: run
    PrependShell: true
  - Chown: ""
    From: node
    Name: copy
    SourcesAndDest:
    - /usr/bin/chromedriver
    - /usr/bin/
  - Chown: ""
    From: node
    Name: copy
    SourcesAndDest:
    - /usr/local/bin/node
    - /usr/local/bin/
  - Env:
    - Key: RUBYOPT
      Value: -EUTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: ja_JP.UTF-8
    Name: env
  - CmdLine:
    - apt-get update &&    apt-get install -y mysql-client imagemagick jpegoptim optipng
      graphviz fonts-ipafont cron supervisor vim --no-install-recommends &&    rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - gem install bundler
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -0 -L http://npmjs.org/install.sh | sh
    Name: run
    PrependShell: true
  From:
    Image: ruby:2.5.3
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.3
