MetaArgs: null
Stages:
- BaseName: pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
  Commands:
  - CmdLine:
    - apt-get -y update && apt-get -y install redis-server
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install gym redis pillow atari-py visdom lz4
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/neka-nat/distributed_rl.git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/redis.conf
    - /etc/redis/
  - Name: workdir
    Path: /workspace/distributed_rl
  - CmdLine:
    - /etc/init.d/redis-server start && /bin/bash
    Name: entrypoint
    PrependShell: true
  From:
    Image: pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
  Name: ""
  Platform: ""
  SourceCode: FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
