MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: = matt@thetroutmans.net
    Name: maintainer
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - apt-get update && apt-get install -y python3 python3-pip nginx git nano sqlite3
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./
    - /hello
  - CmdLine:
    - pip3 install -r /hello/trtmn/config_files/requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /hello/trtmn/config_files/gunicorn.conf /etc/init/gunicorn.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /hello/trtmn/config_files/nginx /etc/nginx/sites-available/trtmn
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /hello/trtmn
  - CmdLine:
    - python3 manage.py makemigrations
    Name: run
    PrependShell: true
  - CmdLine:
    - python3 manage.py migrate
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin',
      'admin@example.com', 'admin')" | python3 manage.py shell
    Name: run
    PrependShell: true
  - CmdLine:
    - sqlite3 db.sqlite3 "INSERT INTO hello_contactinfo VALUES(1,'default','2016-06-17
      20:15:50','Matt','Troutman','Quality Assurance Engineer','Hi. Call me Fishy','m@trtmn.com','2025-01-01','4159934749','2025-01-01','trtmn','m.trtmn','trtmn','trtmn','Matt
      Troutman is a Quality Assurance Engineer that has been in the tech industry
      for over 10 years.','Python, Django, Docker, nginx, gunicorn, git',1);"
    Name: run
    PrependShell: true
  - CmdLine:
    - python3 manage.py collectstatic --noinput
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /etc/nginx/sites-available/trtmn /etc/nginx/sites-enabled
    Name: run
    PrependShell: true
  - CmdLine:
    - touch /var/log/nginx/access.log
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/nginx/sites-available/default
    Name: run
    PrependShell: true
  - CmdLine:
    - /hello/trtmn/config_files/startup.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
