MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - CmdLine:
    - "apt-get update  \t&& apt-get install -y software-properties-common"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-add-repository ppa:ansible/ansible
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update \t&& apt-get install -y ansible=2.4.2.0-1ppa~xenial \t&& rm
      -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /mnt/ansible
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /mnt/ansible
  - CmdLine:
    - ansible-playbook
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
