MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - CmdLine:
    - npm install express selenium-grid-status
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - webapp.js
    - /webapp.js
  - Name: expose
    Ports:
    - "4445"
  - CmdLine:
    - localhost
    - "4444"
    Name: cmd
    PrependShell: false
  - CmdLine:
    - node
    - /webapp.js
    Name: entrypoint
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
