MetaArgs: null
Stages:
- BaseName: kong:1.3.0-alpine
  Commands:
  - CmdLine:
    - apk update     && apk add -Uuv --no-cache --virtual build-deps git
    Name: run
    PrependShell: true
  - Env:
    - Key: GLUU_VERSION
      Value: version_4.1
    - Key: GG_DEPS
      Value: gluu-gateway-node-deps
    Name: env
  - CmdLine:
    - git clone --single-branch --branch ${GLUU_VERSION} https://github.com/GluuFederation/gluu-gateway.git
      /tmp/${GG_DEPS}
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gitmodules
    - /tmp/${GG_DEPS}
  - CmdLine:
    - cd /tmp/${GG_DEPS}     && cat gitmodules > .gitmodules     && git submodule
      update --init --recursive     && rm -rf Dockerfile .dockerignore .gitignore
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - install-plugins.sh
    - /tmp/
  - CmdLine:
    - sh /tmp/install-plugins.sh     && rm -rf /tmp/install-plugins.sh /tmp/${GG_DEPS}
    Name: run
    PrependShell: true
  - Labels:
    - Key: name
      Value: '"gluu-gateway"'
    - Key: maintainer
      Value: '"Gluu Inc. <support@gluu.org>"'
    - Key: vendor
      Value: '"Gluu Federation"'
    - Key: version
      Value: '"4.1.0"'
    - Key: release
      Value: '"dev"'
    - Key: summary
      Value: '"Gluu gateway "'
    - Key: description
      Value: '"Gluu Gateway (GG) is an API gateway that leverages the Gluu Server
        for central OAuth client management and access control"'
    Name: label
  - Env:
    - Key: KONG_PLUGINS
      Value: '"bundled,gluu-oauth-auth,gluu-uma-auth,gluu-uma-pep,gluu-oauth-pep,gluu-metrics,gluu-openid-connect,gluu-opa-pep"'
    - Key: KONG_NGINX_HTTP_LUA_SHARED_DICT
      Value: '"gluu_metrics 1M"'
    Name: env
  - Env:
    - Key: KONG_PROXY_ACCESS_LOG
      Value: /dev/stdout
    - Key: KONG_ADMIN_ACCESS_LOG
      Value: /dev/stdout
    - Key: KONG_PROXY_ERROR_LOG
      Value: /dev/stderr
    - Key: KONG_ADMIN_ERROR_LOG
      Value: /dev/stderr
    - Key: KONG_NGINX_HTTP_LARGE_CLIENT_HEADER_BUFFERS
      Value: '"8 16k"'
    Name: env
  - CmdLine:
    - apk del build-deps
    Name: run
    PrependShell: true
  From:
    Image: kong:1.3.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM kong:1.3.0-alpine
