MetaArgs: null
Stages:
- BaseName: ubuntu:17.04
  Commands:
  - CmdLine:
    - dpkg --add-architecture i386   && apt-get update -qqy && apt-get -qqy install     build-essential     g++     git     python     openjdk-8-jdk     wget     expect     unzip     vim     libstdc++6:i386
      libgcc1:i386 zlib1g:i386 libncurses5:i386   && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entry-point.sh
    - /opt/bin/entry-point.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - tools
    - /opt/tools
  - CmdLine:
    - mkdir -p /opt/android-sdk-linux
    Name: run
    PrependShell: true
  - Env:
    - Key: ANDROID_HOME
      Value: /opt/android-sdk-linux
    Name: env
  - CmdLine:
    - '"/opt/tools/android-sdk-update.sh"'
    Name: run
    PrependShell: true
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: info
    Name: env
  - Key: NODE_VERSION
    Name: arg
    Value: 8.9.0
  - CmdLine:
    - cd /opt/ && wget https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz   &&
      tar -zxf /opt/node-v${NODE_VERSION}-linux-x64.tar.gz -C /usr/local --strip-components=1   &&
      rm "/opt/node-v$NODE_VERSION-linux-x64.tar.gz"   && ln -s /usr/local/bin/node
      /usr/local/bin/nodejs
    Name: run
    PrependShell: true
  - Key: YARN_VERSION
    Name: arg
    Value: 1.3.2
  - CmdLine:
    - cd /opt/ && wget "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz"   &&
      mkdir -p /opt/yarn   && tar -xzf /opt/yarn-v$YARN_VERSION.tar.gz -C /opt/yarn
      --strip-components=1   && ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn   &&
      ln -s /opt/yarn/bin/yarn /usr/local/bin/yarnpkg   && rm /opt/yarn-v$YARN_VERSION.tar.gz   &&
      mkdir -p /opt/yarn-cache   && chown -R $USER:$USER /opt/yarn-cache   && chown
      -R $USER:$USER $HOME
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn global add react-native-cli
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - /opt/bin/entry-point.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - assembleDebug
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:17.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:17.04
