MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Sukru Uzel <sukru.uzel@gmail.com>
    Name: maintainer
  - Env:
    - Key: POSTGREST_VERSION
      Value: 0.3.0.3
    Name: env
  - Env:
    - Key: POSTGREST_DBHOST
      Value: host
    Name: env
  - Env:
    - Key: POSTGREST_DBPORT
      Value: "5432"
    Name: env
  - Env:
    - Key: POSTGREST_DBNAME
      Value: database
    Name: env
  - Env:
    - Key: POSTGREST_DBUSER
      Value: user
    Name: env
  - Env:
    - Key: POSTGREST_DBPASS
      Value: password
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y tar xz-utils wget libpq-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://github.com/begriffs/postgrest/releases/download/v${POSTGREST_VERSION}/postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar --xz -xvf postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
    Name: run
    PrependShell: true
  - CmdLine:
    - mv postgrest /usr/local/bin/postgrest
    Name: run
    PrependShell: true
  - CmdLine:
    - postgrest postgres://${POSTGREST_DBUSER}:${POSTGREST_DBPASS}@${POSTGREST_DBHOST}:${POSTGREST_DBPORT}/${POSTGREST_DBNAME}               --port
      3000               --schema public               --anonymous postgres               --pool
      200
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
