MetaArgs: null
Stages:
- BaseName: cloudezz/servicebase
  Commands:
  - Maintainer: bbytes  "info@beyondbytes.co.in"
    Name: maintainer
  - CmdLine:
    - apt-get update -qq && apt-get install -y mysql-server-5.5
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - my.cnf
    - /etc/mysql/conf.d/my.cnf
  - CmdLine:
    - chmod 664 /etc/mysql/conf.d/my.cnf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - setup_mysql.sh
    - /opt/cloudezz-config/setup_mysql.sh
  - CmdLine:
    - chmod +x /opt/cloudezz-config/setup_mysql.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start_mysql.sh
    - /opt/cloudezz-config/start_mysql.sh
  - CmdLine:
    - chmod +x /opt/cloudezz-config/start_mysql.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mysql.conf
    - /etc/supervisor/conf.d/
  - Name: volume
    Volumes:
    - /var/lib/mysql
  - Name: expose
    Ports:
    - "3306"
  - CmdLine:
    - cd /opt/cloudezz-config && ./setup_mysql.sh && ./start.sh
    Name: cmd
    PrependShell: true
  From:
    Image: cloudezz/servicebase
  Name: ""
  Platform: ""
  SourceCode: FROM cloudezz/servicebase
