MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: kevinosorus <kevin.caradant@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get upgrade -y && apt-get install -y software-properties-common
      tzdata debconf-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/lirc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'lirc lirc/remote select Windows Media Center Transceivers/Remotes (all)'
      > /etc/lirc/lirc_mce.seed
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'lirc lirc/transmitter select None' >> /etc/lirc/lirc_mce.seed
    Name: run
    PrependShell: true
  - CmdLine:
    - debconf-set-selections /etc/lirc/lirc_mce.seed
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --force-yes -q lirc
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -f /etc/lirc/lirc_mce.seed
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/lirc/
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/lircd /var/run/lirc/lircd
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:team-xbmc/ppa
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y kodi kodi-pvr-nextpvr
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime && dpkg-reconfigure -f
      noninteractive tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/kodi
    - --lircdev /dev/lircd
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
