MetaArgs: null
Stages:
- BaseName: hashicorp/terraform
  Commands:
  - Env:
    - Key: TF_VERSION
      Value: 0.11.14-mesosphere
    Name: env
  - Env:
    - Key: TF_DOCS_VERSION
      Value: 0.6.0
    Name: env
  - CmdLine:
    - apk add --update --no-cache openjdk8-jre
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/fatz/terraform/releases/download/v${TF_VERSION}/linux_amd64.zip
      -O ./temp.zip && unzip -o ./temp.zip -d /bin/ && rm -f ./temp.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/segmentio/terraform-docs/releases/download/v${TF_DOCS_VERSION}/terraform-docs-v${TF_DOCS_VERSION}-linux-amd64
      -O /usr/bin/terraform-docs;chmod +x /usr/bin/terraform-docs
    Name: run
    PrependShell: true
  From:
    Image: hashicorp/terraform
  Name: ""
  Platform: ""
  SourceCode: FROM hashicorp/terraform
