MetaArgs: null
Stages:
- BaseName: python:2.7-slim
  Commands:
  - Labels:
    - Key: base.image
      Value: '"python:2.7-slim"'
    Name: label
  - Labels:
    - Key: version
      Value: '"1"'
    Name: label
  - Labels:
    - Key: software
      Value: '"ucsc_pairwise_alignments_custom_scripts_python2"'
    Name: label
  - Labels:
    - Key: software.version
      Value: '"0.1"'
    Name: label
  - Labels:
    - Key: software.description
      Value: '"Custom scripts for ucsc alignments developed from Rafal Gumienny"'
    Name: label
  - Labels:
    - Key: software.website
      Value: '""'
    Name: label
  - Labels:
    - Key: software.documentation
      Value: '""'
    Name: label
  - Labels:
    - Key: software.license
      Value: '"link to license(file) of original software"'
    Name: label
  - Labels:
    - Key: software.tags
      Value: '"Genomics, Transcriptomics"'
    Name: label
  - Labels:
    - Key: maintainer
      Value: '"foivos.gypas@unibas.ch"'
    Name: label
  - Labels:
    - Key: maintainer.organisation
      Value: '"Biozentrum, University of Basel"'
    Name: label
  - Labels:
    - Key: maintainer.location
      Value: '"Klingelbergstrasse 50/70, CH-4056 Basel, Switzerland"'
    Name: label
  - Labels:
    - Key: maintainer.lab
      Value: '"Zavolan Lab"'
    Name: label
  - Labels:
    - Key: maintainer.license
      Value: '"https://spdx.org/licenses/Apache-2.0"'
    Name: label
  - Env:
    - Key: SOFTWARE_VERSION
      Value: "0.1"
    Name: env
  - CmdLine:
    - apt-get update -y   && apt-get autoremove -y && apt-get clean   && rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*   && pip install --no-cache-dir numpy pandas
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.py'
    - /usr/bin/
  From:
    Image: python:2.7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7-slim
