MetaArgs: null
Stages:
- BaseName: centos:6.8
  Commands:
  - Maintainer: Roman <sometime.developer@gmail.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sipxecs.repo
    - /etc/yum.repos.d/
  - CmdLine:
    - yum install -y yum-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y sipxtacklib sipxportlib unixODBC mongo-cxx-driver
    Name: run
    PrependShell: true
  - CmdLine:
    - yumdownloader sipxcommserverlib
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /var/tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y zeromq oss_core postgresql-odbc
    Name: run
    PrependShell: true
  - CmdLine:
    - yumdownloader sipxproxy
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -i --nodeps ./*.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/sipXproxy -C /etc/sipxpbx/sipXproxy-config
    Name: cmd
    PrependShell: true
  From:
    Image: centos:6.8
  Name: ""
  Platform: ""
  SourceCode: FROM centos:6.8
