MetaArgs: null
Stages:
- BaseName: prom/node-exporter:v0.15.2
  Commands:
  - Env:
    - Key: NODE_ID
      Value: none
    Name: env
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf
    - /etc/node-exporter/
  - CmdLine:
    - /etc/node-exporter/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /bin/node_exporter
    Name: cmd
    PrependShell: false
  From:
    Image: prom/node-exporter:v0.15.2
  Name: ""
  Platform: ""
  SourceCode: FROM prom/node-exporter:v0.15.2
