MetaArgs: null
Stages:
- As: builder
  BaseName: ubuntu:bionic
  Commands:
  - CmdLine:
    - apt-get update &&   apt-get install -y curl &&   mkdir -p /opt/hydrus &&   curl
      -s -L https://github.com/hydrusnetwork/hydrus/releases/download/v$(curl -s https://api.github.com/repos/hydrusnetwork/hydrus/releases/latest
      | grep 'tag_name' | cut -d\" -f4 | cut -c 2-)/Hydrus.Network.$(curl -s https://api.github.com/repos/hydrusnetwork/hydrus/releases/latest
      | grep 'tag_name' | cut -d\" -f4 | cut -c 2-).-.Linux.-.Executable.tar.gz |
      tar xzf - --strip-components=1 -C /opt/hydrus
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:bionic
  Name: builder
  Platform: ""
  SourceCode: FROM ubuntu:bionic as builder
- BaseName: ubuntu:bionic
  Commands:
  - Health:
      Interval: 60000000000
      Retries: 3
      Test:
      - CMD-SHELL
      - /bin/bash -c "exec 3<>/dev/tcp/127.0.0.1/45870"
      Timeout: 10000000000
    Name: healthcheck
  - Labels:
    - Key: git
      Value: '"https://github.com/hydrusnetwork/hydrus"'
    Name: label
  - CmdLine:
    - /opt/hydrus/server
    Name: cmd
    PrependShell: false
  - Name: volume
    Volumes:
    - /opt/hydrus/db
  - Name: workdir
    Path: /opt/hydrus
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /opt/hydrus
    - /opt/hydrus
  From:
    Image: ubuntu:bionic
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:bionic
