MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.11
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64
    - /usr/bin/dep
  - CmdLine:
    - chmod +x /usr/bin/dep
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $GOPATH/src/github.com/srgrn/SimpleAzureUploader-go
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gopkg.toml
    - Gopkg.lock
    - ./
  - CmdLine:
    - dep ensure --vendor-only
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o /azure-uploader
      .
    Name: run
    PrependShell: true
  From:
    Image: golang:1.11
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.11 AS builder
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /azure-uploader
    - ./
  - CmdLine:
    - /azure-uploader
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
