# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /templates/Dockerfile.erb

FROM fluent/fluentd:v0.12.33-debian

MAINTAINER Eduardo Silva <eduardo@treasure-data.com>
USER root
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev libffi-dev" \
     && apt-get update \
     && apt-get upgrade -y \
     && apt-get install \
     -y --no-install-recommends \
     $buildDeps \
     && gem install resolve-hostname -v 0.1.0 \
     && gem install proxifier -v 1.0.3 \
     && gem install fluent-plugin-secure-forward -v 0.4.5 \
     && gem install fluent-plugin-record-reformer -v 0.9.1 \
     && gem install excon -v 0.60.0 \
     && gem install multi_json -v 1.13.1 \
     && gem install multipart-post -v 2.0.0 \
     && gem install faraday -v 0.14.0 \
     && gem install elasticsearch-transport -v 6.0.1 \
     && gem install elasticsearch-api -v 6.0.1 \
     && gem install elasticsearch -v 6.0.1 \
     && gem install fluent-plugin-elasticsearch -v 1.13.1 \
     && gem install google-protobuf -v 3.5.1.2 \
     && gem install googleapis-common-protos-types -v 1.0.1 \
     && gem install little-plugger -v 1.1.4 \
     && gem install logging -v 2.2.2 \
     && gem install jwt -v 2.1.0 \
     && gem install memoist -v 0.16.0 \
     && gem install os -v 0.9.6 \
     && gem install public_suffix -v 3.0.1 \
     && gem install addressable -v 2.5.2 \
     && gem install signet -v 0.8.1 \
     && gem install googleauth -v 0.6.2 \
     && gem install grpc -v 1.8.3 \
     && gem install googleapis-common-protos -v 1.3.7 \
     && gem install uber -v 0.1.0 \
     && gem install declarative -v 0.0.10 \
     && gem install declarative-option -v 0.1.0 \
     && gem install representable -v 3.0.4 \
     && gem install retriable -v 3.1.1 \
     && gem install mime-types-data -v 3.2016.0521 \
     && gem install mime-types -v 3.1 \
     && gem install httpclient -v 2.8.3 \
     && gem install google-api-client -v 0.19.5 \
     && gem install google-cloud-env -v 1.0.1 \
     && gem install google-cloud-core -v 1.1.0 \
     && gem install stackdriver-core -v 1.2.0 \
     && gem install rly -v 0.2.3 \
     && gem install google-gax -v 1.0.1 \
     && gem install google-cloud-logging -v 1.4.0 \
     && gem install fluent-plugin-google-cloud -v 0.6.14 \
     && gem install lru_redux -v 1.1.0 \
     && gem install unf_ext -v 0.0.7.4 \
     && gem install unf -v 0.1.4 \
     && gem install domain_name -v 0.5.20170404 \
     && gem install http-cookie -v 1.0.3 \
     && gem install netrc -v 0.11.0 \
     && gem install rest-client -v 2.0.2 \
     && gem install concurrent-ruby -v 1.0.5 \
     && gem install i18n -v 0.9.3 \
     && gem install activesupport -v 5.1.4 \
     && gem install recursive-open-struct -v 1.0.0 \
     && gem install http-form_data -v 1.0.3 \
     && gem install http -v 0.9.8 \
     && gem install kubeclient -v 1.1.4 \
     && gem install fluent-plugin-kubernetes_metadata_filter -v 1.0.1 \
     && gem install ffi -v 1.9.18 \
     && gem install systemd-journal -v 1.3.1 \
     && gem install fluent-plugin-systemd -v 0.0.8 \
    && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
    && gem sources --clear-all \
    && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

# Copy configuration files
COPY ./conf/fluent.conf /fluentd/etc/
COPY ./conf/systemd.conf /fluentd/etc/
COPY ./conf/kubernetes.conf /fluentd/etc/

# Copy plugins
COPY plugins /fluentd/plugins/
COPY entrypoint.sh /fluentd/entrypoint.sh

# Environment variables
ENV FLUENTD_OPT=""
ENV FLUENTD_CONF="fluent.conf"

# jemalloc is memory optimization only available for td-agent
# td-agent is provided and QA'ed by treasuredata as rpm/deb/.. package
# -> td-agent (stable) vs fluentd (edge)
#ENV LD_PRELOAD="/usr/lib/libjemalloc.so.2"

# Run Fluentd
CMD ["/fluentd/entrypoint.sh"]
