MetaArgs: null
Stages:
- BaseName: alpine:3.6
  Commands:
  - Maintainer: AshDev <ashdevfr@gmail.com>
    Name: maintainer
  - Env:
    - Key: JAVA_VERSION_MAJOR
      Value: "8"
    - Key: JAVA_VERSION_MINOR
      Value: "112"
    - Key: JAVA_VERSION_BUILD
      Value: "15"
    - Key: JAVA_PACKAGE
      Value: server-jre
    - Key: JAVA_HOME
      Value: /opt/jdk
    - Key: PATH
      Value: ${PATH}:/opt/jdk/bin
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - apk upgrade --update &&     apk add --update wget curl ca-certificates openssl
      bash git screen util-linux sudo shadow &&     update-ca-certificates
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add openjdk8-jre
    Name: run
    PrependShell: true
  - Env:
    - Key: SPIGOT_HOME
      Value: /minecraft
    Name: env
  - CmdLine:
    - addgroup -g 1000 -S minecraft &&   adduser -u 1000 -S minecraft -G minecraft
      -h /minecraft
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "minecraft ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/minecraft
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./minecraft/ops.txt
    - /usr/local/etc/minecraft/ops.txt
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./minecraft/white-list.txt
    - /usr/local/etc/minecraft/white-list.txt
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./minecraft/server.properties
    - /usr/local/etc/minecraft/server.properties
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./lib/scripts/spigot_init.sh
    - /spigot_init.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./lib/scripts/spigot_run.sh
    - /spigot_run.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./lib/scripts/spigot_cmd.sh
    - /spigot_cmd.sh
  - CmdLine:
    - chmod +x /spigot_init.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /spigot_run.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /spigot_cmd.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "25565"
  - Name: expose
    Ports:
    - "8123"
  - Name: volume
    Volumes:
    - /minecraft
  - Env:
    - Key: UID
      Value: "1000"
    Name: env
  - Env:
    - Key: GUID
      Value: "1000"
    Name: env
  - Env:
    - Key: MOTD
      Value: A Minecraft Server Powered by Spigot & Docker
    Name: env
  - Env:
    - Key: REV
      Value: latest
    Name: env
  - Env:
    - Key: JVM_OPTS
      Value: -Xmx1024M -Xms1024M
    Name: env
  - Env:
    - Key: LEVEL
      Value: world
    - Key: PVP
      Value: "true"
    - Key: VDIST
      Value: "10"
    - Key: OPPERM
      Value: "4"
    - Key: NETHER
      Value: "true"
    - Key: FLY
      Value: "false"
    - Key: MAXBHEIGHT
      Value: "256"
    - Key: NPCS
      Value: "true"
    - Key: WLIST
      Value: "false"
    - Key: ANIMALS
      Value: "true"
    - Key: HC
      Value: "false"
    - Key: ONLINE
      Value: "true"
    - Key: RPACK
      Value: ''''''
    - Key: DIFFICULTY
      Value: "3"
    - Key: CMDBLOCK
      Value: "false"
    - Key: MAXPLAYERS
      Value: "20"
    - Key: MONSTERS
      Value: "true"
    - Key: STRUCTURES
      Value: "true"
    - Key: SPAWNPROTECTION
      Value: "16"
    Name: env
  - CmdLine:
    - /spigot_init.sh
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.6
