MetaArgs: null
Stages:
- As: fetch_cake
  BaseName: composer
  Commands:
  - Key: cake_version
    Name: arg
    Value: 2.10.*
  - CmdLine:
    - composer require cakephp/cakephp $cake_version
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bootstrap-suffix.php
    - .
  - Name: workdir
    Path: vendor/cakephp/cakephp/app
  - CmdLine:
    - cat /app/bootstrap-suffix.php >> Config/bootstrap.php
    Name: run
    PrependShell: true
  - CmdLine:
    - rm composer.json
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -r Vendor
    Name: run
    PrependShell: true
  From:
    Image: composer
  Name: fetch_cake
  Platform: ""
  SourceCode: FROM composer AS fetch_cake
- BaseName: php:7.3-alpine
  Commands:
  - CmdLine:
    - mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
    Name: run
    PrependShell: true
  - Chown: ""
    From: fetch_cake
    Name: copy
    SourcesAndDest:
    - /app/vendor/cakephp/cakephp
    - /cakephp
  - Name: workdir
    Path: /cakephp/app
  - CmdLine:
    - ln -s /plugin/Vendor
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add build-base autoconf
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug     && docker-php-ext-enable xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - apk del build-base autoconf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-alpine
