MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: graham@grahamc.com
    Name: maintainer
  - CmdLine:
    - sudo apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y icecast2
    Name: run
    PrependShell: true
  - Env:
    - Key: IC2_SOURCE_PASSWORD
      Value: hackme
    Name: env
  - Env:
    - Key: IC2_RELAY_PASSWORD
      Value: hackme
    Name: env
  - Env:
    - Key: IC2_ADMIN_USER
      Value: admin
    Name: env
  - Env:
    - Key: IC2_ADMIN_PASSWORD
      Value: hackme
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config.xml
    - /etc/icecast2/config.xml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /start.sh
  - Name: user
    User: icecast2
  - Name: volume
    Volumes:
    - /logs
  - Name: expose
    Ports:
    - "8000"
    - "8001"
  - CmdLine:
    - /usr/bin/icecast2
    - -c
    - /etc/icecast2/user-config.xml
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
