MetaArgs: null
Stages:
- BaseName: node:11.5.0-alpine
  Commands:
  - CmdLine:
    - apk update &&   apk add git python py-pip &&   pip install awscli
    Name: run
    PrependShell: true
  From:
    Image: node:11.5.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:11.5.0-alpine
