MetaArgs: null
Stages:
- BaseName: elasticsearch
  Commands:
  - Maintainer: Oleksii Dzhulai ice4ighter@gmail.com
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y supervisor curl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.d/elasticsearch.ini
    - /etc/supervisor/conf.d/elasticsearch.conf
  - CmdLine:
    - 'curl -s https://download.elasticsearch.org/kibana/kibana/kibana-4.0.2-linux-x64.tar.gz
      | tar -C /opt -xz &&     ln -s /opt/kibana-4.0.2-linux-x64 /opt/kibana &&     sed
      -i ''s/port: 5601/port: 80/'' /opt/kibana/config/kibana.yml'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.d/kibana.ini
    - /etc/supervisor/conf.d/kibana.conf
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/bin/supervisord
    - -n
    - -c
    - /etc/supervisor/supervisord.conf
    Name: entrypoint
    PrependShell: false
  From:
    Image: elasticsearch
  Name: ""
  Platform: ""
  SourceCode: FROM elasticsearch
