MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: Martin Meyer <martin.meyer@inftec.ch>
    Name: maintainer
  - Env:
    - Key: DOCK_MESSAGE
      Value: Hello My World
    Name: env
  - Env:
    - Key: DOCK_LOG_FILE_NAME
      Value: output.txt
    Name: env
  - Env:
    - Key: DOCK_PORT
      Value: "8080"
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts
    - /scripts
  - Name: volume
    Volumes:
    - /log
  - Name: expose
    Ports:
    - $DOCK_PORT
  - Name: workdir
    Path: /scripts
  - CmdLine:
    - bash
    - /scripts/echo-server.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
