MetaArgs: null
Stages:
- As: builder
  BaseName: golang
  Commands:
  - Name: workdir
    Path: /src/aws-signing/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.Version=`cat VERSION`" -a
      -installsuffix cgo -o dist/aws-reverse-proxy ./aws-reverse-proxy/
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.Version=`cat VERSION`" -a
      -installsuffix cgo -o dist/aws-curl ./aws-curl/
    Name: run
    PrependShell: true
  From:
    Image: golang
  Name: builder
  Platform: ""
  SourceCode: FROM golang AS builder
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk --no-cache add ca-certificates
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /src/aws-signing/dist/aws-curl
    - .
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /src/aws-signing/dist/aws-reverse-proxy
    - .
  - CmdLine:
    - chmod +x ./aws-curl
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x ./aws-reverse-proxy
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - ./aws-reverse-proxy
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --port=80
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
