MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Antonis Kalipetis <akaliipetis@gmail.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://dl.eff.org/certbot-auto
    - /usr/local/bin/certbot
  - CmdLine:
    - /usr/local/bin/certbot
    Name: entrypoint
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/certbot && yes | certbot --version
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
