MetaArgs: null
Stages:
- BaseName: docker.io/pandada8/alpine-python:3-tiny
  Commands:
  - Maintainer: f1yegor
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - chmod a+x aws-backup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --egg -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install grafcli awscli
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /db
  - CmdLine:
    - /app/aws-backup.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: docker.io/pandada8/alpine-python:3-tiny
  Name: ""
  Platform: ""
  SourceCode: FROM docker.io/pandada8/alpine-python:3-tiny
