MetaArgs: null
Stages:
- BaseName: phinz/typo3:7-latest
  Commands:
  - CmdLine:
    - pecl install xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - '{         echo ''zend_extension="xdebug.so"'';         echo ''xdebug.remote_enable=1'';         echo
      ''xdebug.remote_connect_back=1'';         echo ''xdebug.max_nesting_level=400'';         echo
      ''xdebug.remote_log="/var/log/xdebug.log"'';     } > /usr/local/etc/php/conf.d/xdebug.ini'
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: phinz/typo3:7-latest
  Name: ""
  Platform: ""
  SourceCode: FROM phinz/typo3:7-latest
