MetaArgs: null
Stages:
- BaseName: node:argon
  Commands:
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /usr/src/app/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - send.js
    - /usr/src/app
  - Name: expose
    Ports:
    - "8181"
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:argon
  Name: ""
  Platform: ""
  SourceCode: FROM node:argon
