MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Alex Yang <aleozlx@gmail.com>
    Name: maintainer
  - CmdLine:
    - 'apt -y update # 1'
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y build-essential wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y git sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -P /tmp --quiet https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
      && chmod +x /tmp/rustup-init && /tmp/rustup-init --default-toolchain nightly-2019-02-24-x86_64-unknown-linux-gnu
      -y
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
