MetaArgs: null
Stages:
- BaseName: java:8-jre
  Commands:
  - Maintainer: Apache NiFi <dev@nifi.apache.org>
    Name: maintainer
  - Key: UID
    Name: arg
    Value: "1000"
  - Key: GID
    Name: arg
    Value: "1000"
  - Key: NIFI_VERSION
    Name: arg
    Value: 1.3.0
  - Env:
    - Key: NIFI_BASE_DIR
      Value: /opt/nifi
    Name: env
  - Env:
    - Key: NIFI_HOME
      Value: $NIFI_BASE_DIR/nifi-${NIFI_VERSION}
    Name: env
  - Env:
    - Key: NIFI_BINARY_URL
      Value: https://archive.apache.org/dist/nifi/${NIFI_VERSION}/nifi-${NIFI_VERSION}-bin.tar.gz
    Name: env
  - CmdLine:
    - 'groupadd -g $GID nifi || groupmod -n nifi `getent group $GID | cut -d: -f1`     &&
      useradd --shell /bin/bash -u $UID -g $GID -m nifi     && mkdir -p $NIFI_HOME/conf/templates     &&
      chown -R nifi:nifi $NIFI_BASE_DIR'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - resources/nifi-toolkit-${NIFI_VERSION}-bin.tar.gz
    - /opt/nifi/
  - CmdLine:
    - curl -fSL $NIFI_BINARY_URL -o $NIFI_BASE_DIR/nifi-${NIFI_VERSION}-bin.tar.gz   &&
      echo "$(curl $NIFI_BINARY_URL.sha256) *$NIFI_BASE_DIR/nifi-${NIFI_VERSION}-bin.tar.gz"
      | sha256sum -c -   && tar -xvzf $NIFI_BASE_DIR/nifi-${NIFI_VERSION}-bin.tar.gz
      -C $NIFI_BASE_DIR   && rm $NIFI_BASE_DIR/nifi-${NIFI_VERSION}-bin.tar.gz   &&
      chown -R nifi:nifi ${NIFI_BASE_DIR}   && apt-get update   && apt-get install
      -y jq xmlstarlet
    Name: run
    PrependShell: true
  - Name: user
    User: nifi
  - Name: expose
    Ports:
    - "8080"
    - "8181"
    - "8443"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./sh/
    - /opt/nifi/sh
  - CmdLine:
    - ${NIFI_BASE_DIR}/sh/start.sh
    Name: cmd
    PrependShell: true
  From:
    Image: java:8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM java:8-jre
