MetaArgs: null
Stages:
- BaseName: python:3.6-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /
  - CmdLine:
    - pip3 install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Name: volume
    Volumes:
    - /data
  - Env:
    - Key: SQLITE_FILE
      Value: /data/db.sqlite
    Name: env
  - Env:
    - Key: DATA_JSON
      Value: /app/data.json
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app
    - /app
  - CmdLine:
    - python3
    - bot.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:3.6-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-alpine
