MetaArgs: null
Stages:
- BaseName: python:3.5.2-alpine
  Commands:
  - Env:
    - Key: ARCH
      Value: amd64
    Name: env
  - Env:
    - Key: DUMB_INIT_VERSION
      Value: 1.1.3
    Name: env
  - Env:
    - Key: GOSU_VERSION
      Value: "1.9"
    Name: env
  - Env:
    - Key: GOSU_SIGNING_KEY
      Value: B42F6819007F00F88E364FD4036A9C25BF357DD4
    Name: env
  - CmdLine:
    - set -ex -o pipefail;     apk add --no-cache --virtual .build-deps curl gnupg     &&
      cd $(mktemp -d)     && curl -fsSL -O "https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_${ARCH}"     &&
      curl -fsSL -O "https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/sha256sums"     &&
      cat sha256sums | tail -n 1 | sha256sum -c     && mv -v dumb-init_${DUMB_INIT_VERSION}_${ARCH}
      /usr/local/bin/dumb-init     && curl -fsSL -o /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${ARCH}"     &&
      curl -fsSL -o gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${ARCH}.asc"     &&
      export GNUPGHOME="$(mktemp -d)"     && gpg --keyserver ha.pool.sks-keyservers.net
      --recv-keys ${GOSU_SIGNING_KEY}     && gpg --batch --verify gosu.asc /usr/local/bin/gosu     &&
      chmod +x /usr/local/bin/dumb-init /usr/local/bin/gosu     && gosu nobody true     &&
      apk del .build-deps     && rm -rf /var/cache/apk/*     && pip3 install --upgrade
      pip     && pip3 install eve
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src
  - Name: volume
    Volumes:
    - /src
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - /usr/local/bin/dumb-init
    - --
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - python3
    - main.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.5.2-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.5.2-alpine
