MetaArgs: null
Stages:
- BaseName: nginx
  Commands:
  - CmdLine:
    - apt-get update -y     && apt-get install -y         apache2-utils     && rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: FORWARD_PORT
      Value: "80"
    Name: env
  - Name: workdir
    Path: /opt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - auth.conf
    - auth.htpasswd
    - launch.sh
    - ./
  - CmdLine:
    - chmod 0755 ./launch.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - ./launch.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nginx
  Name: ""
  Platform: ""
  SourceCode: FROM nginx
