MetaArgs: null
Stages:
- BaseName: anapsix/alpine-java:8u192b12_server-jre
  Commands:
  - Maintainer: bjddd192 <bjddd192@163.com>
    Name: maintainer
  - Key: NODE_VERSION
    Name: arg
    Value: 4.2.17
  - Key: INSTALL_URL
    Name: arg
    Value: https://github.com/alibaba/otter/releases/download/otter-${NODE_VERSION}/manager.deployer-${NODE_VERSION}.tar.gz
  - Env:
    - Key: TZ
      Value: '"Asia/Shanghai"'
    - Key: OTTER_MANAGER_DOMAIN_NAME
      Value: '"127.0.0.1"'
    - Key: OTTER_MANAGER_PORT
      Value: "80"
    - Key: OTTER_DATABASE_URL
      Value: '"jdbc:mysql://127.0.0.1:3306/otter"'
    - Key: OTTER_DATABASE_USERNAME
      Value: '"user"'
    - Key: OTTER_DATABASE_PASSWORD
      Value: '"password"'
    - Key: OTTER_ZOOKEEPER_CLUSTER_DEFAULT
      Value: '"127.0.0.1:2181"'
    - Key: OTTER_ZOOKEEPER_SESSIONTIMEOUT
      Value: "60000"
    - Key: OTTER_MANAGER_MONITOR_EMAIL_HOST
      Value: '"smtp@163.com"'
    - Key: OTTER_MANAGER_MONITOR_EMAIL_USERNAME
      Value: '"user"'
    - Key: OTTER_MANAGER_MONITOR_EMAIL_PASSWORD
      Value: '"password"'
    - Key: OTTER_MANAGER_MONITOR_EMAIL_STMP_PORT
      Value: "25"
    - Key: LOG_LEVEL
      Value: '"INFO"'
    - Key: LOG_APPENDER
      Value: '"STDOUT"'
    - Key: JAVA_XMS
      Value: '"256M"'
    - Key: JAVA_XMX
      Value: '"512M"'
    - Key: JAVA_XMN
      Value: '"128M"'
    Name: env
  - CmdLine:
    - "apk add --update curl bash aria2 file tzdata     && ln -sf /usr/share/zoneinfo/Asia/Shanghai
      /etc/localtime \t&& echo \"Asia/Shanghai\" > /etc/timezone     && mkdir -p /usr/local/otter/manager
      \    && curl -SL ${INSTALL_URL} -o manager.deployer.tar.gz     && gunzip manager.deployer.tar.gz
      \    && tar -xf manager.deployer.tar -C /usr/local/otter/manager     && rm manager.deployer.tar
      \    && rm /var/cache/apk/*"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/otter/manager
  - Chown: ""
    Name: add
    SourcesAndDest:
    - otter.properties
    - /usr/local/otter/manager/conf/otter.properties
  - Chown: ""
    Name: add
    SourcesAndDest:
    - logback.xml
    - /usr/local/otter/manager/conf/logback.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - startup.sh
    - /usr/local/otter/manager/bin/startup.sh
  - CmdLine:
    - chmod +x /usr/local/otter/manager/bin/startup.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1099"
  - CmdLine:
    - /usr/local/otter/manager/bin/startup.sh
    Name: cmd
    PrependShell: false
  From:
    Image: anapsix/alpine-java:8u192b12_server-jre
  Name: ""
  Platform: ""
  SourceCode: FROM anapsix/alpine-java:8u192b12_server-jre
