MetaArgs: null
Stages:
- BaseName: golang:alpine
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/thngkaiyuan/look-at-my-site
  - CmdLine:
    - apk add --no-cache git
    Name: run
    PrependShell: true
  - CmdLine:
    - go get golang.org/x/net/idna
    Name: run
    PrependShell: true
  - CmdLine:
    - go install github.com/thngkaiyuan/look-at-my-site
    Name: run
    PrependShell: true
  - CmdLine:
    - /go/bin/look-at-my-site
    Name: entrypoint
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: golang:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:alpine
