MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk add socat
    Name: run
    PrependShell: true
  - CmdLine:
    - socat -d -d -u TCP:decoder:30005 TCP:feed.adsbexchange.com:${RECEIVER_PORT:-30005}
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
