MetaArgs: null
Stages:
- BaseName: elasticsearch:7.1.1
  Commands:
  - Env:
    - Key: discovery.type
      Value: single-node
    Name: env
  From:
    Image: elasticsearch:7.1.1
  Name: ""
  Platform: ""
  SourceCode: FROM elasticsearch:7.1.1
