MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -y install make gcc libssl-dev
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /opt/nicedocker
  - CmdLine:
    - cd /opt/nicedocker/src && make TARGET=linux2628 USE_OPENSSL=1 && make PREFIX=/usr/local/haproxy
      install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - myssl.pem
    - /etc/ssl/myssl.pem
  - Chown: ""
    Name: add
    SourcesAndDest:
    - haproxy.cfg
    - /etc/haproxy/haproxy.cfg
  - Name: expose
    Ports:
    - "443"
    - "80"
  - CmdLine:
    - /opt/nicedocker/run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
