MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Labels:
    - Key: maintainer
      Value: s5550055.minimum@gmail.com
    Name: label
  - CmdLine:
    - rpm --import https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7   && yum -y -q
      install epel-release   && rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7   &&
      yum -y -q install vim python34 python34-pip jq   && pip3 install -q awscli
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/aws
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
