MetaArgs: null
Stages:
- BaseName: phusion/baseimage
  Commands:
  - Maintainer: Nil Portugués Calderó <contact@nilportugues.com>
    Name: maintainer
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-add-repository -y ppa:ansible/ansible
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install ansible openssh-client rsync
    Name: run
    PrependShell: true
  - CmdLine:
    - ansible-galaxy install --force carlosbuenosvinos.ansistrano-deploy carlosbuenosvinos.ansistrano-rollback
      --roles-path=/usr/share/ansible/roles
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser --disabled-password --gecos '' ansistrano
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser ansistrano sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/ansistrano/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /home/ansistrano/.ssh/ && ssh-keygen -t rsa -b 4096 -C '' -f /home/ansistrano/.ssh/id_rsa
    Name: run
    PrependShell: true
  - CmdLine:
    - chown ansistrano:ansistrano -Rf /home/ansistrano/
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/ansistrano/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /start.sh
  - CmdLine:
    - /start.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ansible
    Name: cmd
    PrependShell: false
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: phusion/baseimage
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage
