MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - CmdLine:
    - apk add --no-cache --update tinyproxy nghttp2  &&  mkdir -m 777 /config
    Name: run
    PrependShell: true
  - Env:
    - Key: SERVER_CRT
      Value: none
    - Key: SERVER_KEY
      Value: none
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - tinyproxy.conf
    - /config/tinyproxy.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nghttpx.conf
    - /config/nghttpx.conf
  - CmdLine:
    - chmod +x /entrypoint.sh  &&  chgrp -R 0 /config  &&  chmod -R g+rwX /config
    Name: run
    PrependShell: true
  - CmdLine:
    - sh /entrypoint.sh
    Name: entrypoint
    PrependShell: true
  - Name: expose
    Ports:
    - "8443"
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
