MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Labels:
    - Key: name
      Value: '"Docker ETCD"'
    Name: label
  - Labels:
    - Key: version
      Value: '"1.0.0"'
    Name: label
  - Labels:
    - Key: maintainer
      Value: '"Lee Keitel <lfkeitel@usi.edu>"'
    Name: label
  - Key: ETCD_VERSION
    Name: arg
    Value: 3.1.0
  - CmdLine:
    - apk add --update ca-certificates openssl tar drill &&     wget https://github.com/coreos/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
      &&     tar xzvf etcd-v${ETCD_VERSION}-linux-amd64.tar.gz &&     mv etcd-v${ETCD_VERSION}-linux-amd64/etcd*
      /bin/ &&     apk del --purge tar openssl &&     rm -Rf etcd-v${ETCD_VERSION}-linux-amd64*
      /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /bin/run.sh
  - Name: volume
    Volumes:
    - /data
  - Name: expose
    Ports:
    - "2379"
    - "2380"
  - CmdLine:
    - /bin/run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
