MetaArgs: null
Stages:
- BaseName: minio/mc:RELEASE.2018-02-09T23-07-36Z
  Commands:
  - CmdLine:
    - apk add --no-cache bash
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --update --no-cache coreutils
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - .
  - CmdLine:
    - chmod a+x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - ./entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: minio/mc:RELEASE.2018-02-09T23-07-36Z
  Name: ""
  Platform: ""
  SourceCode: FROM minio/mc:RELEASE.2018-02-09T23-07-36Z
