MetaArgs: null
Stages:
- BaseName: owasp/modsecurity:v2-fedora-apache
  Commands:
  - Maintainer: Rodrigo Martinez rm1000@gmail.com
    Name: maintainer
  - CmdLine:
    - dnf -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - dnf -y install java
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt &&   git clone -b master https://gitlab.fing.edu.uy/gsi/modsec-ml.git
      modsec-ml &&   cp -R /opt/modsec-ml/ /etc/httpd/modsecurity.d/ml/ &&   cd /etc/httpd/modsecurity.d
      &&   printf "IncludeOptional modsecurity.d/ml/*.conf\n" > include.conf &&   sed
      -i -e 's/SecRuleEngine DetectionOnly/SecRuleEngine On/g' /etc/httpd/modsecurity.d/modsecurity.conf
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - httpd
    - -k
    - start
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: owasp/modsecurity:v2-fedora-apache
  Name: ""
  Platform: ""
  SourceCode: FROM owasp/modsecurity:v2-fedora-apache
