MetaArgs: null
Stages:
- As: build-env
  BaseName: centos:7
  Commands:
  - Maintainer: <pahudnet@gmail.com>
    Name: maintainer
  - CmdLine:
    - yum update -y && yum groupinstall "Development Tools"  -y && yum install openssl-devel
      svn net-tools -y
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root
  - CmdLine:
    - svn co https://shop.ntop.org/svn/ntop/trunk/n2n && cd n2n/n2n_v2 && make &&
      make install
    Name: run
    PrependShell: true
  From:
    Image: centos:7
  Name: build-env
  Platform: ""
  SourceCode: FROM centos:7 AS build-env
- BaseName: centos:7
  Commands:
  - Chown: ""
    From: build-env
    Name: copy
    SourcesAndDest:
    - /usr/sbin/supernode
    - /usr/sbin/
  - Chown: ""
    From: build-env
    Name: copy
    SourcesAndDest:
    - /usr/sbin/edge
    - /usr/sbin/
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
