MetaArgs: null
Stages:
- BaseName: mgibio/tabix:1.3.1
  Commands:
  - CmdLine: null
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /usr/bin/tabix
    Name: cmd
    PrependShell: false
  From:
    Image: mgibio/tabix:1.3.1
  Name: ""
  Platform: ""
  SourceCode: FROM mgibio/tabix:1.3.1
