MetaArgs: null
Stages:
- BaseName: bash:5.0.11
  Commands:
  - Name: workdir
    Path: /opt/es-utils
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src
    - /opt/es-utils
  - CmdLine:
    - chmod +x -R /opt/es-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - bash
    - /opt/es-utils/main.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: bash:5.0.11
  Name: ""
  Platform: ""
  SourceCode: FROM bash:5.0.11
