MetaArgs: null
Stages:
- BaseName: minity/php54-webapp
  Commands:
  - CmdLine:
    - apt-get -yq update
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -yq install php5-xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'xdebug.remote_enable = 1\nxdebug.remote_connect_back=1\nxdebug.max_nesting_level=300'
      > /etc/php5/conf.d/xdebug-debugger-enable.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -yq install graphviz
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://dl.dropboxusercontent.com/u/19430078/php54-xhprof.tar.bz2
    - /tmp/
  - CmdLine:
    - tar xjf /tmp/php54-xhprof.tar.bz2 -C /tmp     && cp /tmp/xhprof/xhprof.so /usr/lib/php5/20100525/     &&
      mkdir -p /usr/share/php     && cp -R /tmp/xhprof/xhprof_* /usr/share/php     &&
      rm /tmp/php54-xhprof.tar.bz2     && rm -R /tmp/xhprof
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /tmp/xhprofiles
  - CmdLine:
    - echo 'extension=xhprof.so\nxhprof.output_dir=/tmp/xhprofiles' > /etc/php5/conf.d/xhprof.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'location /.xhp/ {alias /usr/share/php/xhprof_html/; fastcgi_split_path_info
      ^/.xhp(/.+\.php)(.*)$; location ~ \.php$ {fastcgi_index index.php; fastcgi_pass
      unix:/var/run/php.sock; include fastcgi_params; fastcgi_param SCRIPT_FILENAME
      $document_root$fastcgi_script_name; access_log /dev/stdout fcgi;}}' > /etc/nginx/default.d/xhprof.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'chown user:user /tmp/xhprofiles' > /init.d/xhprof
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean all && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: minity/php54-webapp
  Name: ""
  Platform: ""
  SourceCode: FROM minity/php54-webapp
