MetaArgs: null
Stages:
- BaseName: rocker/ropensci
  Commands:
  - Maintainer: Hector Corrada Bravo <hcorrada@gmail.com>
    Name: maintainer
  - CmdLine:
    - install2.r --error     ISLR     gapminder     cvTools     tree     e1071     ROCR     randomForest
    Name: run
    PrependShell: true
  - CmdLine:
    - installGithub.r     hadley/readxl
    Name: run
    PrependShell: true
  - CmdLine:
    - install2.r --error     quantmod     swirl
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/ids_materials/tidy_unit && chown -R rstudio /home/ids_materials
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /home/ids_materials/tidy_unit &&   git clone https://github.com/hadley/tidyr.git
      &&   mv tidyr/vignettes example_data &&   rm -rf tidyr
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update       && apt-get install -y --no-install-recommends         sqlite3         libsqlite3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/ids_materials/lahman_sqlite   && wget -O /home/ids_materials/lahman_sqlite/readme2014.txt
      http://seanlahman.com/files/database/readme2014.txt   && git clone https://github.com/jknecht/baseball-archive-sqlite.git
      /tmp/lahman_sqlite   && cp /tmp/lahman_sqlite/lahman2014.sqlite /home/ids_materials/lahman_sqlite
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+w -R /home/ids_materials/lahman_sqlite
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - example_data/geno_data.rda
    - /home/ids_materials/
  From:
    Image: rocker/ropensci
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/ropensci
