MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Joey Fang <josudoey@gmail.com>
    Name: maintainer
  - Env:
    - Key: HOME
      Value: /bitcoin
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends         software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:bitcoin/bitcoin
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends                 bitcoind=0.18.0-xenial1         &&
      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "18332"
    - "18333"
    - "28332"
    - "28333"
    - "8332"
    - "8333"
  - Name: workdir
    Path: /bitcoin
  - Name: volume
    Volumes:
    - /bitcoin/
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
