MetaArgs: null
Stages:
- As: buildstep
  BaseName: hyperknot/baseimage16:1.0.6
  Commands:
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    - Key: LANG
      Value: en_US.UTF-8
    - Key: LANGUAGE
      Value: en_US.UTF-8
    - Key: TERM
      Value: xterm
    - Key: container
      Value: docker
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    - Key: NGINX_DEVEL_KIT_VERSION
      Value: 0.3.0
    - Key: NGINX_SET_MISC_MODULE_VERSION
      Value: "0.31"
    - Key: NGINX_VERSION
      Value: 1.14.2
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./build/src/
    - /tmp/
  - CmdLine:
    - bash /tmp/ubuntu.sh
    Name: run
    PrependShell: true
  From:
    Image: hyperknot/baseimage16:1.0.6
  Name: buildstep
  Platform: ""
  SourceCode: FROM hyperknot/baseimage16:1.0.6 AS buildstep
- BaseName: hyperknot/baseimage16:1.0.6
  Commands:
  - Maintainer: friends@niiknow.org
    Name: maintainer
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    - Key: LANG
      Value: en_US.UTF-8
    - Key: LANGUAGE
      Value: en_US.UTF-8
    - Key: TERM
      Value: xterm
    - Key: container
      Value: docker
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    - Key: NGINX_VERSION
      Value: _1.14.2-1~xenial_amd64.deb
    - Key: NGINX_DEBUG
      Value: -dbg${NGINX_VERSION}
    Name: env
  - Chown: ""
    From: buildstep
    Name: copy
    SourcesAndDest:
    - /usr/src/nginx/nginx${NGINX_VERSION}
    - /tmp
  - CmdLine:
    - cd /tmp     && echo "\n\n* soft nofile 800000\n* hard nofile 800000\n\n" >>
      /etc/security/limits.conf     && curl -s https://nginx.org/keys/nginx_signing.key
      | apt-key add -     && cp /etc/apt/sources.list /etc/apt/sources.list.bak     &&
      echo "deb http://nginx.org/packages/ubuntu/ xenial nginx" | tee -a /etc/apt/sources.list     &&
      echo "deb-src http://nginx.org/packages/ubuntu/ xenial nginx" | tee -a /etc/apt/sources.list     &&
      apt-get update -y && apt-get upgrade -y --no-install-recommends --no-install-suggests     &&
      apt-get install -y --no-install-recommends --no-install-suggests        nano
      libgd3 gettext-base unzip rsync     && dpkg --configure -a     && dpkg -i nginx${NGINX_VERSION}     &&
      rm -rf /etc/nginx/conf.d/default.conf     && rm -f /etc/service/syslog-forwarder/down     &&
      rm -f /etc/service/cron/down     && rm -f /etc/service/syslog-ng/down     &&
      rm -f /core     && ln -sf /dev/stdout /var/log/nginx/access.log     && ln -sf
      /dev/stderr /var/log/nginx/error.log     && service nginx stop && update-rc.d
      -f nginx disable     && apt-get clean -y && apt-get autoclean -y     && apt-get
      autoremove --purge -y     && rm -rf /var/lib/apt/lists/* /var/lib/log/* /tmp/*
      /var/tmp/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files
    - /
  - CmdLine:
    - bash /root/bin/placeholder-ssl.sh     && mkdir -p /app-start/etc     && mv /etc/nginx
      /app-start/etc/nginx     && rm -rf /etc/nginx     && ln -s /app/etc/nginx /etc/nginx     &&
      mkdir -p /app-start/var/log     && mv /var/log/nginx /app-start/var/log/nginx     &&
      rm -rf /var/log/nginx     && ln -s /app/var/log/nginx /var/log/nginx
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Name: volume
    Volumes:
    - /app
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  From:
    Image: hyperknot/baseimage16:1.0.6
  Name: ""
  Platform: ""
  SourceCode: FROM hyperknot/baseimage16:1.0.6
