MetaArgs: null
Stages:
- BaseName: python:3.6-slim
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - Env:
    - Key: NAME
      Value: World
    Name: env
  - CmdLine:
    - python
    - data-analysis-app.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-slim
