MetaArgs: null
Stages:
- BaseName: debian:9
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y python                        python3                        python-pip                        python3-pip                        python-tk                        python3-tk                        sudo
      &&     useradd -ms /bin/bash python &&     usermod -aG sudo python
    Name: run
    PrependShell: true
  - Name: user
    User: python
  - Name: workdir
    Path: /app
  From:
    Image: debian:9
  Name: ""
  Platform: ""
  SourceCode: FROM debian:9
