MetaArgs: null
Stages:
- BaseName: mhart/alpine-node:latest
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/node-urandom-server
  - Name: workdir
    Path: /usr/src/node-urandom-server
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: mhart/alpine-node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM mhart/alpine-node:latest
