MetaArgs: null
Stages:
- BaseName: miko2u/centos6
  Commands:
  - Maintainer: miko@cafelounge.net
    Name: maintainer
  - CmdLine:
    - cd /etc/yum.repos.d  && curl -OL http://pkg.jenkins-ci.org/redhat/jenkins.repo  &&
      rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key  && yum -y
      update  && yum -y install java-1.8.0-openjdk jenkins subversion git  && yum
      clean all  && find / -group jenkins | xargs chgrp 467; groupmod -g 467 jenkins  &&
      find / -user jenkins | xargs chown 467; usermod -u 467 jenkins
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - boot/*
    - /boot/
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: miko2u/centos6
  Name: ""
  Platform: ""
  SourceCode: FROM miko2u/centos6
