MetaArgs: null
Stages:
- BaseName: kalilinux/kali-linux-docker
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: INITRD
      Value: "No"
    Name: env
  - CmdLine:
    - echo 'deb http://old.kali.org/kali sana main non-free contrib' >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y locales
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/\# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_CTYPE
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - locale-gen
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y vim curl silversearcher-ag apt-file git zsh ncdu
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/ston3o/oh-my-zsh ~/.oh-my-zsh
    Name: run
    PrependShell: true
  - CmdLine:
    - cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/ZSH_THEME="robbyrussell"/ZSH_THEME="red"/g' ~/.zshrc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-file update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y zenity mingw32 monodevelop xterm gnome-terminal default-jre
      default-jdk aapt dex2jar zlib1g-dev libmagickwand-dev imagemagick zipalign cowpatty
      bully lighttpd macchanger php-cgi isc-dhcp-server python3-dev python3-setuptools
      python-pip libssl-dev xprobe2 golang-go
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wine
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install3 pip
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/noxxi/p5-io-socket-ssl && cd p5-io-socket-ssl &&
      perl Makefile.PL && make && make install && rm -r /p5-io-socket-ssl
    Name: run
    PrependShell: true
  - CmdLine:
    - echo '[ ! -z "$TERM" -a -r /etc/motd ] && cat /etc/motd' >> ~/.zshrc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y figlet
    Name: run
    PrependShell: true
  - CmdLine:
    - figlet -f small "HACKLAB" > /etc/motd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i '$ d' /etc/motd && echo "https://github.com/ston3o/docker-hacklab" >>
      /etc/motd && echo '\n' >> /etc/motd
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y hping3 scapy
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y metasploit-framework websploit
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/x3omdax/PenBox /opt/PenBox &&     git clone https://github.com/golismero/golismero.git
      /opt/golismero && cd /opt/golismero && pip install -r requirements.txt &&     git
      clone https://github.com/nil0x42/phpsploit /opt/phpsploit &&     git clone https://github.com/C0reL0ader/EaST
      /opt/EaST &&     git clone https://github.com/leviathan-framework/leviathan
      /opt/leviathan &&     git clone https://github.com/Ekultek/Pybelt /opt/Pybelt
      &&     git clone https://github.com/nccgroup/redsnarf /opt/redsnarf &&     git
      clone https://github.com/FreelancePentester/ddos-script /opt/ddos-script
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pwntools
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/empty
    - /usr/local/bin/empty
  - CmdLine:
    - apt-get install -y mitmproxy dsniff mitmf tcpdump ngrep
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/r00t-3xp10it/morpheus /opt/morpheus &&     git
      clone https://github.com/evilsocket/bettercap &&     git clone https://github.com/LionSec/xerosploit
      /opt/xerosploit
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sendemail
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/BishopFox/spoofcheck /opt/spoofcheck
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y hydra john crunch cewl
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/Mebus/cupp /opt/cupp &&     git clone https://github.com/k4m4/dymerge.git
      /opt/dymerge &&     git clone https://github.com/LandGrey/pydictor.git /opt/pydictor
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/ekultek/dagon.git /opt/dagon
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nikto wpscan wapiti w3af
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sqlmap themole
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y fimap
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/v3n0m-Scanner/V3n0M-Scanner /opt/V3n0M-Scanner
      && cd /opt/V3n0M-Scanner && python3.5 setup.py install &&     git clone https://github.com/D35m0nd142/LFISuite
      /opt/LFISuite &&     git clone https://github.com/P0cL4bs/Kadimus /opt/Kadimus
      &&     git clone https://github.com/WhitewidowScanner/whitewidow /opt/whitewidow
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y httrack
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/kgretzky/evilginx /opt/evilginx
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -o /usr/local/bin/slowloris https://raw.githubusercontent.com/ston3o/dotfiles/master/bin/slowloris.pl
      && chmod +x /usr/local/bin/slowloris
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install t50
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/Souhardya/Warchild /opt/Warchild
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/k4m4/kickthemout /opt/kickthemout &&     cd /opt/kickthemout/
      &&     python -m pip install -r requirements.txt &&     ln -s /opt/kickthemout/kickthemout.py
      /usr/local/bin/kickthemout &&     chmod +x kickthemout.py
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -s http://www.computec.ch/projekte/vulscan/download/nmap_nse_vulscan-2.0.tar.gz
      | tar xzvf - -C /usr/share/nmap/scripts/
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y whois dnsutils dnsmap nmap theharvester dmitry knockpy netdiscover
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/1N3/Sn1per.git /opt/Sn1per && cd /opt/Sn1per &&
      chmod +x install.sh && ./install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -o /usr/local/bin/googler https://raw.githubusercontent.com/jarun/googler/v2.3/googler
      && chmod +x /usr/local/bin/googler
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/maurosoria/dirsearch /opt/dirsearch &&     git
      clone https://github.com/seifreed/dirb /opt/dirb &&     git clone https://github.com/penafieljlm/inquisitor
      /opt/inquisitor &&     git clone https://github.com/maldevel/EmailHarvester
      /opt/EmailHarvester &&     git clone https://github.com/killswitch-GUI/SimplyEmail/
      /opt/SimplyEmail &&     git clone https://github.com/HatBashBR/ShodanHat /opt/ShodanHat
      &&     git clone https://github.com/graniet/operative-framework /opt/operative-framework
      &&     git clone https://github.com/m4ll0k/Infoga.git /opt/Infoga &&     git
      clone https://github.com/kahunalu/pwnbin.git /opt/pwnbin &&     git clone https://github.com/vesche/scanless
      /opt/scanless &&     git clone https://github.com/techgaun/github-dorks /opt/github-dorks
      &&     git clone https://github.com/aboul3la/Sublist3r /opt/Sublist3r &&     git
      clone https://github.com/TheRook/subbrute /opt/subbrute &&     git clone https://github.com/aancw/Belati
      /opt/Belati
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y metagoofil
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/gathering
    - /usr/local/bin/gathering
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/crawler.py
    - /usr/local/bin/crawler.py
  - CmdLine:
    - apt-get install -y wifite wifiphisher mdk3 tshark
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/kylemcdonald/FreeWifi /opt/FreeWifi && cd /opt/FreeWifi
      && pip install -r requirements.txt &&     git clone https://github.com/FluxionNetwork/fluxion
      /opt/fluxion &&     git clone https://github.com/chrizator/netattack /opt/netattack
      &&     git clone https://github.com/s0lst1c3/eaphammer /opt/eaphammer &&     git
      clone https://github.com/P0cL4bs/WiFi-Pumpkin /opt/Wifi-Pumpkin &&     git clone
      https://github.com/M1ND-B3ND3R/BoopSuite /opt/BoopSuite
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apktool set
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/radare/radare2 /opt/radare2
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/Screetsec/TheFatRat.git /opt/TheFatRat
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "*\n*\n*\n*\nmsfconsole\nmsfvenom\nbackdoor-factory\nsearchsploit" > /opt/TheFatRat/config/config.path
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /opt/TheFatRat/fatrat
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/dana-at-cp/backdoor-apk /opt/backdoor-apk
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/jbreed/apkinjector /opt/apkinjector && chmod +x
      /opt/apkinjector/apkinjector
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/ZIPALIGN=.*$/ZIPALIGN=\/usr\/bin\/zipalign/g' /opt/backdoor-apk/backdoor-apk/backdoor-apk.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/r00t-3xp10it/backdoorppt /opt/backdoorppt
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/BASH_TRANSFORMATION=NO/BASH_TRANSFORMATION=YES/g' /opt/backdoorppt/settings
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/RESOURCEHACKER_BYPASS=NO/RESOURCEHACKER_BYPASS=YES/g' /opt/backdoorppt/settings
    Name: run
    PrependShell: true
  - CmdLine:
    - 'git clone https://github.com/Screetsec/microsploit /opt/microsploit # For Microsoft'
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/nccgroup/Winpayloads /opt/Winpayloads
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/tiagorlampert/CHAOS /opt/CHAOS
    Name: run
    PrependShell: true
  - CmdLine:
    - 'apt-get install -y exploitdb # `searchsploit`'
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/vulnersCom/getsploit /opt/getsploit &&     git
      clone https://github.com/1N3/findsploit /opt/findsploit
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/lightos/credmap /opt/credmap
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/vesche/basicRAT /opt/basicRAT
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/nathanlopez/Stitch /opt/Stitch &&     git clone
      https://github.com/putterpanda/mimikittenz /opt/mimikittenz &&     git clone
      https://github.com/huntergregal/mimipenguin /opt/mimipenguin
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/ngalongc/AutoLocalPrivilegeEscalation /opt/AutoLocalPrivilegeEscalation
      &&     git clone https://github.com/rasta-mouse/Sherlock /opt/Sherlock &&     git
      clone https://github.com/AlessandroZ/BeRoot /opt/BeRoot &&     git clone https://github.com/nilotpalbiswas/Auto-Root-Exploit
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y extract
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/maldevel/IPGeoLocation /opt/IPGeoLocation
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/IPGeoLocation && pip3 install -r requirements.txt && chmod +x /opt/IPGeoLocation/ipgeolocation.py
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/reyammer/shellnoob /opt/shellnoob
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/n00py/WPForce /opt/WPForce
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/m4ll0k/WPSeku /opt/WPSeku
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/HatBashBR/HatCloud /opt/HatCloud
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/m0rtem/CloudFail /opt/CloudFail
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/solusipse/spectrology /opt/spectrology
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install hashdata
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/droberson/ssh-honeypot /opt/ssh-honeypot
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y netcat
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/EnableSecurity/wafw00f /opt/wafw00f
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y mat
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/jbreed/apkwash /opt/apkwash
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/D4Vinci/Dr0p1t-Framework /opt/Dr0p1t-Framework
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install cheat
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .cheat/
    - /root/.cheat/
  - CmdLine:
    - echo "_cmpl_cheat() {\n    reply=($(cheat -l | cut -d' ' -f1))\n}\ncompctl -K
      _cmpl_cheat cheat\n">> /root/.zshrc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs-legacy npm &&     npm cache clean -f &&     npm install
      -g n &&     n stable &&     npm i -g Brosec
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get autoremove -y
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/{apt,dpkg,cache,log,tmp}/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - wordlists
    - /usr/share/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - README.md
    - /root/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Dockerfile
    - /root/
  - Name: workdir
    Path: /root
  From:
    Image: kalilinux/kali-linux-docker
  Name: ""
  Platform: ""
  SourceCode: FROM kalilinux/kali-linux-docker
