MetaArgs: null
Stages:
- BaseName: asciidoctor/docker-asciidoctor:latest
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/thawk/asciidoctor.git"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.schema-version
      Value: '"1.0.0-rc1"'
    Name: label
  - CmdLine:
    - apk add --no-cache     cabal &&  apk add --no-cache --virtual .makedepends     git     ghc     build-base     libxml2-dev     python2-dev     py2-pip     ruby-dev     zlib-dev
      &&  cabal update &&  cabal install graphviz parsec text &&  cd /tmp/ && git
      clone git://github.com/BurntSushi/erd &&  cd erd &&  cabal configure &&  cabal
      build &&  mv dist/build/erd/erd /usr/bin/ && cd ../ && rm -rf erd &&  apk del
      -r --no-cache .makedepends
    Name: run
    PrependShell: true
  From:
    Image: asciidoctor/docker-asciidoctor:latest
  Name: ""
  Platform: ""
  SourceCode: FROM asciidoctor/docker-asciidoctor:latest
