MetaArgs: null
Stages:
- BaseName: google/cloud-sdk:224.0.0-alpine
  Commands:
  - CmdLine:
    - apk add --update --no-cache     postgresql
    Name: run
    PrependShell: true
  - CmdLine:
    - ash
    Name: cmd
    PrependShell: false
  From:
    Image: google/cloud-sdk:224.0.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM google/cloud-sdk:224.0.0-alpine
