MetaArgs: null
Stages:
- BaseName: ubuntu:15.10
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - 'apt-get update     && apt-get install -y wget openssl ca-certificates     &&
      cd /tmp     && wget -qO jdk8.tar.gz        --header "Cookie: oraclelicense=accept-securebackup-cookie"        http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.tar.gz     &&
      tar xzf jdk8.tar.gz -C /opt     && mv /opt/jdk* /opt/java     && rm /tmp/jdk8.tar.gz     &&
      update-alternatives --install /usr/bin/java java /opt/java/bin/java 100     &&
      update-alternatives --install /usr/bin/javac javac /opt/java/bin/javac 100'
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /opt/java
    Name: env
  - CmdLine:
    - "apt-get update && apt-get install -y --no-install-recommends \t\tca-certificates
      \t\tcurl \t\twget \t\tunzip \t\tgit \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:15.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:15.10
