MetaArgs: null
Stages:
- BaseName: unisis/base
  Commands:
  - Maintainer: Unisis <contacto@unisis.com.ar>
    Name: maintainer
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Name: volume
    Volumes:
    - /etc/nginx/certs
    - /var/log/nginx
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --no-install-recommends     openssh-server     nginx
    Name: run
    PrependShell: true
  - Env:
    - Key: CONF_REFRESHED_AT
      Value: "2016_04_25"
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config/nginx.conf
    - /root/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config/nginx-vhost.conf
    - /root/nginx-vhost.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts/nginx-setup
    - /usr/sbin/nginx-setup
  - CmdLine:
    - chmod +x /usr/sbin/nginx-setup
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts/nginx-service
    - /etc/init.d/nginx
  - CmdLine:
    - chmod +x /etc/init.d/nginx
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts/start.sh
    - /root/start.sh
  - CmdLine:
    - chmod +x /root/start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: unisis/base
  Name: ""
  Platform: ""
  SourceCode: FROM unisis/base
