MetaArgs: null
Stages:
- BaseName: php:cli
  Commands:
  - Env:
    - Key: VERSION
      Value: "20150912"
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y libssl-dev libicu-dev git
    Name: run
    PrependShell: true
  - CmdLine:
    - yes 'no' | pecl install mongo   && docker-php-ext-enable mongo
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install intl
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install zip
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'date.timezone="UTC"' > /usr/local/etc/php/conf.d/date-timezone.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer?nocache=$VERSION | php   && mv composer.phar
      /usr/local/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - composer --version
    Name: run
    PrependShell: true
  - CmdLine:
    - composer
    - --ansi
    Name: cmd
    PrependShell: false
  From:
    Image: php:cli
  Name: ""
  Platform: ""
  SourceCode: FROM php:cli
