MetaArgs: null
Stages:
- BaseName: python:3.7-alpine
  Commands:
  - Env:
    - Key: PYTHONDONTWRITEBYTECODE
      Value: "1"
    Name: env
  - CmdLine:
    - apk add --no-cache build-base
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache git
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache postgresql-dev
    Name: run
    PrependShell: true
  From:
    Image: python:3.7-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-alpine
