MetaArgs: null
Stages:
- BaseName: pinver/ldc_lin:1.7.0
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y     wget `# to download`     software-properties-common
      `# ` &&     wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add
      - &&     apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0
      main" &&     apt-get update && apt-get install -y lld-6.0
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - lib/v1.7.0
    - /root/dlang/ldc-1.7.0/lib_win
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  From:
    Image: pinver/ldc_lin:1.7.0
  Name: ""
  Platform: ""
  SourceCode: FROM pinver/ldc_lin:1.7.0
