MetaArgs: null
Stages:
- BaseName: ubuntu:artful
  Commands:
  - Maintainer: Vincent Beffara <vbeffara@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python-pip cmake gcc g++ ccache lcov git ninja-build xvfb
      ruby
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libcairo2-dev libfplll-dev libgmp-dev libmpfr-dev libgl1-mesa-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libcln-dev libgsl-dev libeigen3-dev libpng++-dev mesa-common-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install codecov conan
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install coveralls-lcov
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:artful
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:artful
