MetaArgs: null
Stages:
- BaseName: dynverse/dynwrap:r
  Commands:
  - CmdLine:
    - apt-get -y install libudunits2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e 'devtools::install_cran("udunits2", configure.args =  c(udunits2
      = "--with-udunits2-include=/usr/include/udunits2"))'
    Name: run
    PrependShell: true
  - CmdLine:
    - R -e "devtools::install_github('Albluca/ElPiGraph.R')"
    Name: run
    PrependShell: true
  - Labels:
    - Key: version
      Value: 0.1.5
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code
  - CmdLine:
    - Rscript /code/run.R
    Name: entrypoint
    PrependShell: true
  From:
    Image: dynverse/dynwrap:r
  Name: ""
  Platform: ""
  SourceCode: FROM dynverse/dynwrap:r
