MetaArgs: null
Stages:
- BaseName: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: Ilija Vukotic <ivukotic@cern.ch>
    Name: label
  - CmdLine:
    - echo "/usr/local/cuda-10.2/lib64/" >/etc/ld.so.conf.d/cuda.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "/usr/local/cuda/extras/CUPTI/lib64/" >>/etc/ld.so.conf.d/cuda.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /host-libs &&     echo "/host-libs/" >/etc/ld.so.conf.d/000-host-libs.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install curl wget -y
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
      >/etc/apt/sources.list.d/bazel.list &&     curl https://bazel.build/bazel-release.pub.gpg
      | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - export DEBIAN_FRONTEND=noninteractive &&     apt-get update && apt-get install
      -y --allow-unauthenticated     build-essential     git     module-init-tools     pkg-config     python3     python3-pip     rsync     software-properties-common     unzip     zip     vim     libopenmpi-dev     bazel     &&     apt-get
      clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 --no-cache-dir install     requests     elasticsearch     h5py     matplotlib     numpy     pandas
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 --no-cache-dir install     tables     scipy     sklearn     keras
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 --no-cache-dir install     tqdm     tensorflow-gpu     gym     baselines
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - environment.sh
    - /.environment.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.py'
    - /
  - CmdLine:
    - echo "Timestamp:" `date --utc` | tee /image-build-info.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - /.environment.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
  Name: ""
  Platform: ""
  SourceCode: FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
