MetaArgs: null
Stages:
- BaseName: node:10
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /connection-database
  - CmdLine:
    - cd ./connection-database
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - node
    - /connection-database/test.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:10
  Name: ""
  Platform: ""
  SourceCode: FROM node:10
