MetaArgs: null
Stages:
- As: builder
  BaseName: blcksync/alpine-node:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"matr1xc0in"'
    Name: label
  - Env:
    - Key: SHELL
      Value: /bin/bash
    Name: env
  - Name: user
    User: root
  - Name: workdir
    Path: /root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /root/package.json
  - CmdLine:
    - cd /root;     apk update && apk upgrade &&     apk add --no-cache bash git     busybox-extras     python     python-dev     py-pip     libtool     autoconf     automake     build-base     make
      gcc musl-dev linux-headers     ca-certificates     python2     py-setuptools     &&
      rm -rf /var/cache/apk/*     && if [[ ! -e /usr/bin/python ]];        then ln
      -sf /usr/bin/python2.7 /usr/bin/python; fi     && if [[ ! -e /usr/bin/python-config
      ]]; then ln -sf /usr/bin/python2.7-config /usr/bin/python-config; fi     &&
      if [[ ! -e /usr/bin/easy_install ]];  then ln -sf /usr/bin/easy_install-2.7
      /usr/bin/easy_install; fi ;     npm install -g tar@4.4.8 node-gyp@3.8.0 && npm
      install --python=/usr/bin/python &&     npm install -g       @dexon-foundation/truffle@5.0.12       @dexon-foundation/dsolc@0.5.2       @dexon-foundation/ganache-cli@6.2.5       @dexon-foundation/truffle-hdwallet-provider@1.0.11       truffle-hdwallet-provider@1.0.5       web3@1.0.0-beta.49
    Name: run
    PrependShell: true
  From:
    Image: blcksync/alpine-node:latest
  Name: builder
  Platform: ""
  SourceCode: FROM blcksync/alpine-node:latest as builder
- As: runtime
  BaseName: blcksync/alpine-node:latest
  Commands:
  - Name: user
    User: root
  - Name: workdir
    Path: /root
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/bin/python2.7
    - /usr/bin/python2.7
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/lib/node_modules
    - /usr/lib/node_modules
  - CmdLine:
    - cd /root;     apk update && apk upgrade &&     apk add --no-cache bash       git       busybox-extras       ca-certificates     &&
      rm -rf /var/cache/apk/* ;     cd /usr/bin ;     ln -sf ../lib/node_modules/@dexon-foundation/dsolc/dsolcjs
      dsolcjs ;     ln -sf ../lib/node_modules/@dexon-foundation/truffle/build/cli.bundled.js
      dexon-truffle ;     mkdir /root/node_modules ; cd /root/node_modules ;     ln
      -s /usr/lib/node_modules/truffle-hdwallet-provider
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /root/package.json
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - secret.js
    - /root/secret.js
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - truffle.js
    - /root/truffle.js
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  From:
    Image: blcksync/alpine-node:latest
  Name: runtime
  Platform: ""
  SourceCode: FROM blcksync/alpine-node:latest as runtime
