MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: filipe cristian (ambiente PHP / nginx)
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y iputils-ping     software-properties-common     python-software-properties     curl     composer     vim
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install nginx -y &&     apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y php7.2-fpm php7.2-cli php7.2-fpm php7.2-mysql     php7.2-curl
      php-memcached  php7.2-dev php7.2-sqlite3 php7.2-mbstring     php7.2-gd php7.2-json
      php7.2-xmlrpc php7.2-xml php7.2-zip php7.2-mongodb php-xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_12.x | bash - &&     apt-get install
      -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stdout /var/log/nginx/access.log
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stderr /var/log/nginx/error.log
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./php/php.ini
    - /etc/php/7.2/fpm
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./nginx/default
    - /etc/nginx/sites-available
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./start.sh
    - /
  - CmdLine:
    - chmod +x /start.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/app"'
  - CmdLine:
    - /start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
