MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Carles Amigó, fr3nd@fr3nd.net
    Name: maintainer
  - CmdLine:
    - echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" > /etc/apt/sources.list.d/webupd8team-java.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true
      | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y --force-yes       curl       maven       oracle-java8-installer
      &&       rm -rf /usr/share/doc/* &&       rm -rf /usr/share/info/* &&       rm
      -rf /tmp/* &&       rm -rf /var/tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-oracle
    Name: env
  - Env:
    - Key: SPARK_VERSION
      Value: 1.2.0
    Name: env
  - Env:
    - Key: SPARK_HOME
      Value: /opt/spark
    Name: env
  - CmdLine:
    - curl http://d3kbcqa49mib13.cloudfront.net/spark-${SPARK_VERSION}.tgz | tar -xz
      -C /opt/
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/spark-${SPARK_VERSION} /opt/spark
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/spark
  - CmdLine:
    - ./make-distribution.sh --skip-java-test
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:$SPARK_HOME/bin
    Name: env
  - Name: workdir
    Path: /
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
