MetaArgs: null
Stages:
- BaseName: mongo:3.2
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init.sh
    - /tmp/init.sh
  - CmdLine:
    - chmod +x /tmp/init.sh
    Name: run
    PrependShell: true
  - Labels:
    - Key: maintainer
      Value: '"Eric Smalling <smalls@docker.com>"'
    Name: label
  - CmdLine:
    - /tmp/init.sh
    Name: cmd
    PrependShell: true
  From:
    Image: mongo:3.2
  Name: ""
  Platform: ""
  SourceCode: FROM mongo:3.2
