MetaArgs: null
Stages:
- BaseName: docker:18.09.6
  Commands:
  - CmdLine:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
      &&       pip install docker-compose==1.24.0
    Name: run
    PrependShell: true
  From:
    Image: docker:18.09.6
  Name: ""
  Platform: ""
  SourceCode: FROM docker:18.09.6
