MetaArgs: null
Stages:
- BaseName: tiangolo/uwsgi-nginx:python3.6-alpine3.9
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"poipoii <earth.sama@gmail.com>"'
    Name: label
  - Env:
    - Key: WKHTMLTOIMAGE
      Value: /usr/bin/wkhtmltoimage
    Name: env
  - CmdLine:
    - apk --update add --no-cache             xvfb             wkhtmltopdf             ttf-freefont             fontconfig             dbus     &&     mv
      /usr/bin/wkhtmltopdf /usr/bin/wkhtmltopdf-origin &&     echo $'#!/usr/bin/env
      sh\nXvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset & \nDISPLAY=:0.0
      wkhtmltopdf-origin $@ \nkillall Xvfb' > /usr/bin/wkhtmltopdf &&     chmod +x
      /usr/bin/wkhtmltopdf
    Name: run
    PrependShell: true
  - CmdLine:
    - apk update;     apk add --no-cache git &&     python -m ensurepip &&     rm
      -r /usr/lib/python*/ensurepip &&     pip install --upgrade pip setuptools flask
      &&     pip install git+git://github.com/poipoii/eml2png.git@master#egg=eml2png
      &&     rm -r /root/.cache
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker/supervisord.ini
    - /etc/supervisor.d/supervisord.ini
  - Env:
    - Key: STATIC_URL
      Value: /static
    Name: env
  - Env:
    - Key: STATIC_PATH
      Value: /app/static
    Name: env
  - Env:
    - Key: STATIC_INDEX
      Value: "0"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker/app
    - /app
  - Name: workdir
    Path: /app
  - Env:
    - Key: PYTHONPATH
      Value: /app
    Name: env
  - CmdLine:
    - mv /entrypoint.sh /uwsgi-nginx-entrypoint.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker/entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: tiangolo/uwsgi-nginx:python3.6-alpine3.9
  Name: ""
  Platform: ""
  SourceCode: FROM tiangolo/uwsgi-nginx:python3.6-alpine3.9
