MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Env:
    - Key: MOSQUITTO_VERSION
      Value: 1.4.5
    Name: env
  - CmdLine:
    - "set -x; \tapt-get update && apt-get install -y --no-install-recommends \t\tlibc-ares-dev
      git libmysqlclient-dev libssl-dev uuid-dev build-essential wget ca-certificates
      \t&& cd /tmp \t&& wget http://mosquitto.org/files/source/mosquitto-$MOSQUITTO_VERSION.tar.gz
      -O mosquitto.tar.gz \t&& wget http://mosquitto.org/files/source/mosquitto-$MOSQUITTO_VERSION.tar.gz.asc
      -O mosquitto.tar.gz.asc \t&& gpg --keyserver pgp.mit.edu --recv B3E717B7 \t&&
      gpg --verify mosquitto.tar.gz.asc \t&& mkdir mosquitto-src && tar xfz mosquitto.tar.gz
      --strip-components=1 -C mosquitto-src \t&& cd mosquitto-src && make && make
      install && ldconfig \t&& git clone https://github.com/jpmens/mosquitto-auth-plug.git
      \t&& cd mosquitto-auth-plug \t&& cp config.mk.in config.mk \t&& echo \"MOSQUITTO_SRC
      = /tmp/mosquitto-src\" >> config.mk \t&& make \t&& cp np /usr/bin/np \t&& mkdir
      /mqtt && cp auth-plug.so /mqtt/ \t&& useradd -r mosquitto \t&& apt-get purge
      -y build-essential git wget ca-certificates \t&& apt-get autoremove -y \t&&
      rm -rf /var/lib/apt/lists/* /tmp/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - Name: volume
    Volumes:
    - /var/lib/mosquitto
  - Name: expose
    Ports:
    - "1883"
    - "9001"
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - mosquitto
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
