MetaArgs: null
Stages:
- BaseName: centos:centos7
  Commands:
  - CmdLine:
    - yum -y update; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install epel-release; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install wget logrotate rabbitmq-server; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run-rabbitmq-server.sh
    - /run-rabbitmq-server.sh
  - CmdLine:
    - chmod 750 ./run-rabbitmq-server.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: RABBITMQ_LOG_BASE
      Value: /data/log
    Name: env
  - Env:
    - Key: RABBITMQ_MNESIA_BASE
      Value: /data/mnesia
    Name: env
  - Name: volume
    Volumes:
    - /data/log
    - /data/mnesia
  - Name: expose
    Ports:
    - "15672"
    - "5672"
  - CmdLine:
    - /run-rabbitmq-server.sh
    Name: cmd
    PrependShell: false
  From:
    Image: centos:centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7
