MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: kev <noreply@easypi.pro>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache iptables tinc
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init.sh
    - /init.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - peer.sh
    - /usr/local/bin/peer.sh
  - Name: volume
    Volumes:
    - /etc/tinc
  - Env:
    - Key: NETNAME
      Value: netname
    - Key: KEYSIZE
      Value: "4096"
    - Key: VERBOSE
      Value: "2"
    Name: env
  - Env:
    - Key: IP_ADDR
      Value: 1.2.3.4
    - Key: ADDRESS
      Value: 10.20.30.1
    - Key: NETMASK
      Value: 255.255.255.0
    - Key: NETWORK
      Value: 10.20.30.0/24
    - Key: RUNMODE
      Value: server
    Name: env
  - Name: expose
    Ports:
    - 655/tcp
    - 655/udp
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
