MetaArgs: null
Stages:
- BaseName: wordpress:php7.0
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ports.conf
    - /etc/apache2/ports.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - site.conf
    - /etc/apache2/sites-available/000-default.conf
  From:
    Image: wordpress:php7.0
  Name: ""
  Platform: ""
  SourceCode: FROM wordpress:php7.0
