MetaArgs: null
Stages:
- As: builder
  BaseName: openjdk:8-jdk-slim
  Commands:
  - Name: workdir
    Path: /opt/gatling
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - build.gradle
    - gradlew
    - settings.gradle
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gradle
    - gradle
  - CmdLine:
    - ./gradlew shadowJar
    Name: run
    PrependShell: true
  From:
    Image: openjdk:8-jdk-slim
  Name: builder
  Platform: ""
  SourceCode: FROM openjdk:8-jdk-slim AS builder
- BaseName: openjdk:8-jre-slim
  Commands:
  - Name: workdir
    Path: /opt/gatling
  - Env:
    - Key: GATLING_JAR
      Value: /opt/gatling/pelias-server-stress.jar
    Name: env
  - Env:
    - Key: SERVER_URL
      Value: '""'
    - Key: REGIONS_FILE
      Value: '""'
    - Key: SEEDS_FILE
      Value: '""'
    - Key: USERS_COUNT
      Value: '""'
    - Key: USERS_RAMP_TIME
      Value: '""'
    - Key: GENERATE_SEEDS
      Value: '""'
    - Key: AUTO_GENERATE_SEEDS
      Value: '""'
    Name: env
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /opt/gatling/build/libs/pelias-server-stress-all.jar
    - $GATLING_JAR
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/pelias-server-stress
    - /bin/
  - CmdLine:
    - /bin/pelias-server-stress
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-jre-slim
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-slim
