MetaArgs: null
Stages:
- BaseName: ruby:2.5.1
  Commands:
  - CmdLine:
    - apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/www/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - Gemfile
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile.lock
    - Gemfile.lock
  - CmdLine:
    - bundle install --jobs 20 --retry 5
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - bundle exec rails assets:precompile
    Name: run
    PrependShell: true
  - CmdLine:
    - bundle
    - exec
    - puma
    - -C
    - config/puma.rb
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.5.1
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.1
