MetaArgs: null
Stages:
- BaseName: mongo:4.0.10
  Commands:
  - Maintainer: Alexandre Ferland <aferlandqc@gmail.com>
    Name: maintainer
  - CmdLine:
    - set -x     && apt-get update     && apt-get install -y --no-install-recommends         ca-certificates         curl         lsb-release     &&
      rm -rf /var/lib/apt/lists/*     && curl -O "https://repo.stackdriver.com/stack-install.sh"     &&
      bash stack-install.sh --write-gcm     && (cd /opt/stackdriver/collectd/etc/collectd.d/
      && curl -O https://raw.githubusercontent.com/Stackdriver/stackdriver-agent-service-configs/master/etc/collectd.d/mongodb.conf)
    Name: run
    PrependShell: true
  From:
    Image: mongo:4.0.10
  Name: ""
  Platform: ""
  SourceCode: FROM mongo:4.0.10
