MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.18
  Commands:
  - Maintainer: Giulio De Pasquale <me@krishath.it>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /docker
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - CmdLine:
    - apt-get update && apt-get install -y lib32gcc1 wget
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /docker/install_steamcmd.sh && useradd -m steam
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/steam/csgo/csgo/cfg
    Name: run
    PrependShell: true
  - CmdLine:
    - chown steam:steam /home/steam -R
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /home/steam/csgo/csgo/cfg
  - Name: user
    User: steam
  - CmdLine:
    - /docker/install_steamcmd.sh
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "27015"
  - Name: expose
    Ports:
    - 27015/udp
  From:
    Image: phusion/baseimage:0.9.18
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.9.18
