MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - CmdLine:
    - "apt-get update \t&& apt-get install -y --no-install-recommends \t\tbzip2 \t\tca-certificates
      \t\tlibffi-dev \t\tlibgdbm3 \t\tlibssl-dev \t\tlibyaml-dev \t\tprocps \t\tzlib1g-dev
      \    build-essential     libcurl3-gnutls     libcurl4-openssl-dev     libxrender1
      \    libjpeg8     libfontconfig1     wget     autoconf     libreadline-dev \t&&
      rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: RUBY_MAJOR
      Value: "2.6"
    Name: env
  - Env:
    - Key: RUBY_VERSION
      Value: 2.6.2
    Name: env
  - Env:
    - Key: RUBY_DOWNLOAD_SHA256
      Value: 91fcde77eea8e6206d775a48ac58450afe4883af1a42e5b358320beb33a445fa
    Name: env
  - CmdLine:
    - "set -ex \t\t&& buildDeps=' \t\tbison \t\tdpkg-dev \t\tlibgdbm-dev \t\truby
      \t' \t&& apt-get update \t&& apt-get install -y --no-install-recommends $buildDeps
      \t&& rm -rf /var/lib/apt/lists/* \t\t&& wget -O ruby.tar.xz \"https://cache.ruby-lang.org/pub/ruby/${RUBY_MAJOR%-rc}/ruby-$RUBY_VERSION.tar.xz\"
      \t&& echo \"$RUBY_DOWNLOAD_SHA256 *ruby.tar.xz\" | sha256sum -c - \t\t&& mkdir
      -p /usr/src/ruby \t&& tar -xJf ruby.tar.xz -C /usr/src/ruby --strip-components=1
      \t&& rm ruby.tar.xz \t\t&& cd /usr/src/ruby \t\t&& { \t\techo '#define ENABLE_PATH_CHECK
      0'; \t\techo; \t\tcat file.c; \t} > file.c.new \t&& mv file.c.new file.c \t\t&&
      autoconf \t&& gnuArch=\"$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)\" \t&&
      ./configure \t\t--build=\"$gnuArch\" \t\t--disable-install-doc \t\t--enable-shared
      \t&& make -j \"$(nproc)\" \t&& make install \t\t&& apt-get purge -y --auto-remove
      $buildDeps \t&& cd / \t&& rm -r /usr/src/ruby \t&& ruby --version && gem --version
      && bundle --version"
    Name: run
    PrependShell: true
  - Env:
    - Key: GEM_HOME
      Value: /usr/local/bundle
    Name: env
  - Env:
    - Key: BUNDLE_PATH
      Value: '"$GEM_HOME"'
    - Key: BUNDLE_SILENCE_ROOT_WARNING
      Value: "1"
    - Key: BUNDLE_APP_CONFIG
      Value: '"$GEM_HOME"'
    Name: env
  - Env:
    - Key: PATH
      Value: $GEM_HOME/bin:$BUNDLE_PATH/gems/bin:$PATH
    Name: env
  - CmdLine:
    - mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME"
    Name: run
    PrependShell: true
  - CmdLine:
    - irb
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
