MetaArgs: null
Stages:
- BaseName: mongo:latest
  Commands:
  - CmdLine:
    - "apt-get update \t&& apt-get install -y --no-install-recommends \t\tca-certificates
      \t\tpython3-minimal \t\tpython3-pip \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.py'
    - /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - geoservice.conf
    - /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.csv'
    - /root/
  - Env:
    - Key: LC_ALL
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - pip3 install -r /root/requirements.txt
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root
  - CmdLine:
    - python3 -m unittest -v
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  From:
    Image: mongo:latest
  Name: ""
  Platform: ""
  SourceCode: FROM mongo:latest
