MetaArgs: null
Stages:
- BaseName: land007/golang-node:latest
  Commands:
  - Maintainer: Yiqiu Jia <yiqiujia@hotmail.com>
    Name: maintainer
  - CmdLine:
    - ". $HOME/.nvm/nvm.sh && cd / && npm install @tensorflow/tfjs @tensorflow/tfjs-node
      socket.io-client && \tcd /node_ && git clone https://github.com/justadudewhohacks/face-api.js.git
      && \t. $HOME/.nvm/nvm.sh && cd /node_/face-api.js/ && npm i && cd /node_/face-api.js/examples/examples-nodejs/
      && npm i && npm install -g ts-node && npm install -g typescript && \techo $(date
      \"+%Y-%m-%d_%H:%M:%S\") >> /.image_times && \techo $(date \"+%Y-%m-%d_%H:%M:%S\")
      > /.image_time && \techo \"land007/golang-tfjs-face\" >> /.image_names && \techo
      \"land007/golang-tfjs-face\" > /.image_name"
    Name: run
    PrependShell: true
  From:
    Image: land007/golang-node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM land007/golang-node:latest
