MetaArgs: null
Stages:
- As: build
  BaseName: node:8-alpine
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /build
  - Name: workdir
    Path: /build
  - CmdLine:
    - yarn install &&     yarn run test &&     yarn run tsc &&     rm -rf node_modules/
      &&     yarn install --production=true
    Name: run
    PrependShell: true
  From:
    Image: node:8-alpine
  Name: build
  Platform: ""
  SourceCode: FROM node:8-alpine AS build
- As: runtime
  BaseName: node:8-alpine
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /build
    - /app
  - CmdLine:
    - apk update && apk add -y iptables iproute2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Name: volume
    Volumes:
    - /data
  - Env:
    - Key: NODES
      Value: 169.254.123.125 169.254.123.126 169.254.123.127
    Name: env
  - Env:
    - Key: INTERFACE
      Value: eth0
    Name: env
  - Env:
    - Key: IPPOOL_PREFIX
      Value: 169.254.123.
    Name: env
  - Env:
    - Key: IPPOOL_HOSTMIN
      Value: "100"
    Name: env
  - Env:
    - Key: IPPOOL_HOSTMAX
      Value: "200"
    Name: env
  - Env:
    - Key: DOMAIN
      Value: cheap-ingress.local
    Name: env
  - Env:
    - Key: DEBUG
      Value: util cheap-ingress:*
    Name: env
  - Env:
    - Key: PORT
      Value: "80"
    Name: env
  - Env:
    - Key: STATE_FILENAME
      Value: /data/state.json
    Name: env
  - CmdLine:
    - node dist
    Name: cmd
    PrependShell: true
  From:
    Image: node:8-alpine
  Name: runtime
  Platform: ""
  SourceCode: FROM node:8-alpine AS runtime
