MetaArgs: null
Stages:
- BaseName: hilbert/dd
  Commands:
  - Maintainer: Oleksandr Motsak <malex984+hilbert.main@gmail.com>
    Name: maintainer
  - CmdLine:
    - update.sh && install.sh xauth && clean.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - main.sh
    - menu.sh
    - run.sh
    - runback.sh
    - sv.sh
    - A.sh
    - generate_ogl.sh
    - settings
    - /usr/local/bin/
  - Key: IMAGE_VERSION
    Name: arg
    Value: latest
  - Key: GIT_NOT_CLEAN_CHECK
    Name: arg
    Value: null
  - Key: BUILD_DATE
    Name: arg
    Value: someday
  - Key: VCS_REF
    Name: arg
    Value: HEAD
  - Key: VCS_URL
    Name: arg
    Value: '"https://github.com/hilbert/hilbert-docker-images"'
  - Key: DOCKERFILE
    Name: arg
    Value: '"/images/main/Dockerfile"'
  - Labels:
    - Key: org.label-schema.description
      Value: '"choice menu with a selection of legacy DEMO actions (some of which
        require text mode)"'
    - Key: org.label-schema.build-date
      Value: '"${BUILD_DATE}"'
    - Key: org.label-schema.vcs-ref
      Value: '"${VCS_REF}"'
    - Key: org.label-schema.vcs-url
      Value: '"${VCS_URL}"'
    - Key: org.label-schema.version
      Value: '"${IMAGE_VERSION}"'
    - Key: com.microscaling.docker.dockerfile
      Value: '"${DOCKERFILE}"'
    - Key: IMAGE_VERSION
      Value: '"${IMAGE_VERSION}"'
    - Key: GIT_NOT_CLEAN_CHECK
      Value: '"${GIT_NOT_CLEAN_CHECK}"'
    - Key: org.label-schema.name
      Value: '"Hilbert"'
    - Key: org.label-schema.vendor
      Value: '"IMAGINARY gGmbH"'
    - Key: org.label-schema.url
      Value: '"https://hilbert.github.io"'
    - Key: org.label-schema.schema-version
      Value: '"1.0"'
    - Key: com.microscaling.license
      Value: '"Apache-2.0"'
    Name: label
  - Expression: LABEL org.label-schema.build-date=""       org.label-schema.name=""       org.label-schema.description=""       org.label-schema.vendor=""       org.label-schema.url=""       org.label-schema.vcs-ref=""       org.label-schema.vcs-url=""       org.label-schema.version=""       org.label-schema.schema-version=""       com.microscaling.license=""       com.microscaling.docker.dockerfile=""       IMAGE_VERSION=""       GIT_NOT_CLEAN_CHECK=""
    Name: onbuild
  From:
    Image: hilbert/dd
  Name: ""
  Platform: ""
  SourceCode: FROM hilbert/dd
