MetaArgs: null
Stages:
- BaseName: node:8.3
  Commands:
  - Maintainer: Anthony Smith <anthony@sticksnleaves.com>
    Name: maintainer
  - Env:
    - Key: GRAPHDOC_VERSION
      Value: 2.4.0
    Name: env
  - CmdLine:
    - npm install -g @2fd/graphdoc@$GRAPHDOC_VERSION
    Name: run
    PrependShell: true
  From:
    Image: node:8.3
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.3
