MetaArgs: null
Stages:
- BaseName: lheinlen/geminabox
  Commands:
  - Maintainer: Joe Eli McIlvain <joe.eli.mac@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-key update &&    apt-get update &&    apt-get install -y openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'root:password' | chpasswd
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - bash
    - -c
    - /usr/sbin/sshd && /usr/local/bin/rackup
    Name: cmd
    PrependShell: false
  From:
    Image: lheinlen/geminabox
  Name: ""
  Platform: ""
  SourceCode: FROM        lheinlen/geminabox
