MetaArgs: null
Stages:
- BaseName: composer/composer:1.1-php5-alpine
  Commands:
  - CmdLine:
    - composer global require "fxp/composer-asset-plugin:1.1.4"
    Name: run
    PrependShell: true
  From:
    Image: composer/composer:1.1-php5-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM composer/composer:1.1-php5-alpine
