MetaArgs: null
Stages:
- BaseName: fcat/ubuntu-universe:12.04
  Commands:
  - Maintainer: Mike Mooring <mdmooring@rentalgeek.com>
    Name: maintainer
  - CmdLine:
    - apt-key update -y && apt-get update -y && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl git htop unzip nano wget
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz
    - /tmp/
  - CmdLine:
    - apt-get -y install build-essential zlib1g-dev libssl-dev libreadline6-dev libyaml-dev
      &&     tar -xzf /tmp/ruby-2.1.1.tar.gz &&     (cd ruby-2.1.1/ && ./configure
      --disable-install-doc && make && make install) &&     rm -rf ruby-2.1.1/ &&     rm
      -f /tmp/ruby-2.1.1.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - gem update --system
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install bundler
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile
    - Gemfile
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile.lock
    - Gemfile.lock
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /opt/rails_app
  - CmdLine:
    - rm -rf /opt/rails_app/.bundle
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /opt/rails_app/vendor/bundle
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /opt/rails_app/log/*
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /opt/rails_app/tmp/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/rails_app
  - CmdLine:
    - adduser --disabled-password --home=/rails --gecos "" rails
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts/start
    - /start
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts/setup
    - /setup
  - Name: expose
    Ports:
    - "3000"
  - Name: user
    User: rails
  - CmdLine:
    - /start
    Name: cmd
    PrependShell: true
  From:
    Image: fcat/ubuntu-universe:12.04
  Name: ""
  Platform: ""
  SourceCode: FROM fcat/ubuntu-universe:12.04
