MetaArgs: null
Stages:
- BaseName: node:12.1.0-stretch
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"cedric.penas@gmail.com"'
    Name: label
  - CmdLine:
    - apt-get update     && apt-get install -y ruby-full rubygems curl wget     &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install sass
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  From:
    Image: node:12.1.0-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM node:12.1.0-stretch
