MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get -y install libxdamage1 libgtk-3-0 libasound2 libnss3
      libxss1 sudo bzip2 wget expect
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp && wget https://s3.amazonaws.com/a280ccaaf904330a389db759e6275285/acunetix_trial.sh
      && chmod +x /tmp/acunetix_trial.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.expect
    - /tmp/install.expect
  - CmdLine:
    - cd /tmp && chmod +x /tmp/install.expect && /tmp/install.expect
    Name: run
    PrependShell: true
  - CmdLine:
    - su -l acunetix -c /home/acunetix/.acunetix_trial/start.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
