MetaArgs: null
Stages:
- As: builder
  BaseName: golang:alpine
  Commands:
  - CmdLine:
    - apk --no-cache add ca-certificates && apk update && apk add --no-cache git
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /build
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /build/
  - Name: workdir
    Path: /build
  - CmdLine:
    - go get -d -v ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - GOOS=linux GOARCH=386 go build -o worker
    Name: run
    PrependShell: true
  From:
    Image: golang:alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:alpine as builder
- BaseName: scratch
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /etc/ssl/certs/ca-certificates.crt
    - /etc/ssl/certs/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /build/worker
    - /app/
  - CmdLine:
    - /app/worker
    Name: cmd
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
