MetaArgs: null
Stages:
- BaseName: debian:stable
  Commands:
  - Maintainer: Jesper Wermuth<jwermuth@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y graphviz && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: user
    User: "1000"
  - Name: workdir
    Path: /input
  - CmdLine:
    - dot
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -?
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stable
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stable
