MetaArgs: null
Stages:
- BaseName: anapsix/alpine-java
  Commands:
  - Maintainer: Ricardo Bravo <rbravo@datiobd.com>
    Name: maintainer
  - CmdLine:
    - apk add --update unzip wget curl docker jq coreutils
    Name: run
    PrependShell: true
  - Env:
    - Key: KAFKA_VERSION
      Value: '"0.9.0.1"'
    - Key: SCALA_VERSION
      Value: '"2.11"'
    Name: env
  - CmdLine:
    - wget -q http://apache.mirrors.spacedump.net/kafka/"$KAFKA_VERSION"/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz
      -O /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz &&      tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
      -C /opt &&      rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /kafka
  - Env:
    - Key: KAFKA_HOME
      Value: /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start-kafka.sh
    - /usr/bin/start-kafka.sh
  - CmdLine:
    - start-kafka.sh
    Name: cmd
    PrependShell: false
  From:
    Image: anapsix/alpine-java
  Name: ""
  Platform: ""
  SourceCode: FROM anapsix/alpine-java
