MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.19
  Commands:
  - Maintainer: Jens Erat <email@jenserat.de>
    Name: maintainer
  - CmdLine:
    - echo "deb http://packages.inverse.ca/SOGo/nightly/3/ubuntu xenial xenial" >
      /etc/apt/sources.list.d/inverse.list &&     apt-key adv --keyserver pool.sks-keyservers.net
      --recv-key FE9E84327B18FF82B0378B6719CDA6A9810273C4 &&     apt-get update &&     apt-get
      install -y --no-install-recommends gettext-base iproute2 apache2 sogo sogo-activesync
      sope4.9-gdl1-mysql memcached &&     apt-get clean && rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod headers proxy proxy_http rewrite ssl
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod --home /srv/lib/sogo sogo
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/^-l.*/-l localhost/' /etc/memcached.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/service/sogod /etc/service/apache2 /etc/service/memcached
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sogod.sh
    - /etc/service/sogod/run
  - Chown: ""
    Name: add
    SourcesAndDest:
    - apache2.sh
    - /etc/service/apache2/run
  - Chown: ""
    Name: add
    SourcesAndDest:
    - memcached.sh
    - /etc/service/memcached/run
  - CmdLine:
    - mkdir -p /etc/my_init.d
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - gateway.sh
    - control.sh
    - /etc/my_init.d/
  - Name: volume
    Volumes:
    - /srv
  - Name: expose
    Ports:
    - "20000"
    - "443"
    - "80"
    - "8800"
  - CmdLine:
    - /sbin/my_init
    Name: entrypoint
    PrependShell: false
  From:
    Image: phusion/baseimage:0.9.19
  Name: ""
  Platform: ""
  SourceCode: FROM            phusion/baseimage:0.9.19
