MetaArgs: null
Stages:
- BaseName: centos:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Landon Manning <lmanning17@gmail.com>"'
    Name: label
  - Key: LUAROCKS_VERSION
    Name: arg
    Value: '"3.0.4"'
  - Env:
    - Key: SERVER_MODE
      Value: '"production"'
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:/usr/local/openresty/luajit/bin/:/usr/local/openresty/nginx/sbin/:/usr/local/openresty/bin/
    Name: env
  - Name: volume
    Volumes:
    - /var/data
  - Name: volume
    Volumes:
    - /var/www
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/docker-entrypoint.sh
  - CmdLine:
    - chmod +x /usr/local/bin/docker-entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo;
      yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y update; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install epel-release; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install       gcc       git       make       openresty       openssl       openssl-devel       unzip;     yum
      clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp   && curl -fSL http://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
      -o luarocks-${LUAROCKS_VERSION}.tar.gz  && tar xzf luarocks-${LUAROCKS_VERSION}.tar.gz
      \ && cd luarocks-${LUAROCKS_VERSION}  && ./configure       --prefix=/usr       --lua-suffix=jit
      \t\t--with-lua=/usr/local/openresty/luajit       --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
      \ && make build  && make install  && cd /"
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install luasec
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install bcrypt
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install busted
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install i18n
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install lapis
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install luacov
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install mailgun
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install markdown
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stdout /usr/local/openresty/nginx/logs/access.log
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stderr /usr/local/openresty/nginx/logs/error.log
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /tmp/* -r
    Name: run
    PrependShell: true
  - CmdLine:
    - "yum -y remove       gcc       git       make       openssl       openssl-devel
      \t\tperl       unzip;     yum clean all"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/local/bin/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM centos:latest
