MetaArgs: null
Stages:
- BaseName: arm32v7/golang:stretch
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - qemu-arm-static
    - /usr/bin/
  - Name: workdir
    Path: /go/src/github.com/automatedhome/circulation
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - make build
    Name: run
    PrependShell: true
  From:
    Image: arm32v7/golang:stretch
  Name: ""
  Platform: ""
  SourceCode: FROM arm32v7/golang:stretch
- BaseName: arm32v7/busybox:1.30-glibc
  Commands:
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/automatedhome/circulation/circulation
    - /usr/bin/circulation
  - CmdLine:
    - /usr/bin/circulation
    Name: entrypoint
    PrependShell: false
  From:
    Image: arm32v7/busybox:1.30-glibc
  Name: ""
  Platform: ""
  SourceCode: FROM arm32v7/busybox:1.30-glibc
