MetaArgs: null
Stages:
- BaseName: node:4.4.3
  Commands:
  - CmdLine:
    - apt-get update   && apt-get install -y ruby sudo   && gem install dpl heroku-api
      rendezvous   && wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh   &&
      heroku --version   && apt-get clean   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /etc/hosts /tmp/hosts
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p -- /lib-override && cp /lib/x86_64-linux-gnu/libnss_files.so.2 /lib-override
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "10.1.4.67        gl.maps.utp.edu.co" >> /tmp/hosts
    Name: run
    PrependShell: true
  - CmdLine:
    - perl -pi -e 's:/etc/hosts:/tmp/hosts:g' /lib-override/libnss_files.so.2
    Name: run
    PrependShell: true
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /lib-override
    Name: env
  From:
    Image: node:4.4.3
  Name: ""
  Platform: ""
  SourceCode: FROM node:4.4.3
