MetaArgs: null
Stages:
- BaseName: alpine:3.6
  Commands:
  - CmdLine:
    - apk --no-cache add mongodb
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -v /app
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./mongodb-entrypoint.sh
    - /app/run.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - mongodb-entrypoint_firstrun.sh
    - /app/first_run.sh
  - CmdLine:
    - chmod +x /app/*.sh      && touch /.firstrun      &&  chown -R mongodb /app
    Name: run
    PrependShell: true
  - CmdLine:
    - /app/run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.6
