MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python3
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - tags/
    - /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - server.py
    - /src/server.py
  - Name: workdir
    Path: /src
  - Name: expose
    Ports:
    - "4010"
  - CmdLine:
    - python3
    - server.py
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
