MetaArgs: null
Stages:
- BaseName: r-base:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends apt-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install aptitude -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install curl libcurl4-gnutls-dev -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install libssl-dev -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install libxml2-dev -y
    Name: run
    PrependShell: true
  - CmdLine:
    - aptitude install libglib2.0-0=2.54.1-1 -y
    Name: run
    PrependShell: true
  - CmdLine:
    - aptitude install libglib2.0-dev -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install libcairo2-dev -y
    Name: run
    PrependShell: true
  - CmdLine:
    - aptitude install libpango-1.0-0=1.40.12-1 -y
    Name: run
    PrependShell: true
  - CmdLine:
    - aptitude install libpangocairo-1.0-0=1.40.12-1 -y
    Name: run
    PrependShell: true
  - CmdLine:
    - aptitude install libpangoft2-1.0-0=1.40.12-1 -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install libpango1.0-dev libgtk2.0-dev xvfb xauth xfonts-base libxt-dev
      -y
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/docker
  - CmdLine:
    - curl -o AQM.R https://raw.githubusercontent.com/alexiswl/rnaseq_singularity_containers/master/arrayQualityMetrics_report/AQM.R
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite(c('DESeq2',
      'arrayQualityMetrics'))"
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript
    - /home/docker/AQM.R
    Name: entrypoint
    PrependShell: false
  From:
    Image: r-base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM r-base:latest
