MetaArgs: null
Stages:
- BaseName: sonarqube
  Commands:
  - Maintainer: '"vast0906" <vast0906@gmail.com>'
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sonar-l10n-zh-plugin-1.16.jar
    - /opt/sonarqube/extensions/plugins/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sonar-golang-plugin-1.2.11-rc-reubentfix.jar
    - /opt/sonarqube/extensions/plugins/
  From:
    Image: sonarqube
  Name: ""
  Platform: ""
  SourceCode: FROM sonarqube
