MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Labels:
    - Key: de.innoq.opencv-haar-training.maintainer
      Value: '"Bjoern.Makowe@innoq.com"'
    - Key: de.innoq.opencv-haar-training.vendor
      Value: '"innoQ Deutschland GmbH"'
    - Key: de.innoq.opencv-haar-training.name
      Value: '"OpenCV HAAR classifier training"'
    - Key: de.innoq.opencv-haar-training.description
      Value: '"Image for automated OpenCV HAAR classifier training"'
    - Key: de.innoq.opencv-haar-training.version
      Value: '"1.0"'
    Name: label
  - Env:
    - Key: VERSION
      Value: 3.2.0
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - apt-get update              && apt-get install --yes                     git                     curl                     python                     perl                     build-essential                     cmake                     pkg-config                     libjpeg8-dev                     libtiff5-dev                     libjasper-dev                     libpng12-dev                     libavcodec-dev                     libavformat-dev                     libswscale-dev                     libv4l-dev                     libxvidcore-dev                     libx264-dev                     libatlas-base-dev                     gfortran              &&
      cd /home              && curl -o opencv.tar.gz -L https://github.com/opencv/opencv/archive/${VERSION}.tar.gz              &&
      tar -zxf opencv.tar.gz              && rm -f opencv.tar.gz              && mv
      opencv-* opencv              && cd opencv              && mkdir build              &&
      cd build              && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local
      ..              && make -j7              && make clean              && make              &&
      make install              && ldconfig              && cd /home              &&
      git clone https://github.com/mrnugget/opencv-haar-classifier-training.git              &&
      ln -s /home/opencv-haar-classifier-training/positive_images /positive_images              &&
      ln -s /home/opencv-haar-classifier-training/negative_images /negative_images              &&
      ln -s /home/opencv-haar-classifier-training/classifier /classifier              &&
      rm -rf /var/lib/apt/lists/*              && ln -s usr/local/bin/docker-entrypoint.sh
      /docker-entrypoint.sh              && chmod +x /docker-entrypoint.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /positive_images
    - /negative_images
    - /classifier
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM            ubuntu:latest
