MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: y_uuki
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - echo "deb http://cdn.debian.net/debian/ wheezy main contrib non-free" > /etc/apt/sources.list.d/mirror.jp.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://cdn.debian.net/debian/ wheezy-updates main contrib" >> /etc/apt/sources.list.d/mirror.jp.list
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update && apt-get -yq --no-install-recommends --force-yes install
      libc6=2.13-38+deb7u6 libc-bin=2.13-38+deb7u6 libc6-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update &&     apt-get -yq --no-install-recommends install curl ca-certificates
      tar git build-essential &&     apt-get clean &&     rm -rf /var/cache/apt/archives/*
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - Env:
    - Key: GOROOT
      Value: /opt/local/go
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:/opt/local/go/bin:/go/bin
    Name: env
  - Env:
    - Key: GOOS
      Value: linux
    Name: env
  - Env:
    - Key: GOARCH
      Value: amd64
    Name: env
  - CmdLine:
    - mkdir -p /opt/local
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://storage.googleapis.com/golang/go1.3.3.linux-amd64.tar.gz -o
      /tmp/go.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -C /opt/local -xzf /tmp/go.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd /opt/local/go/src; ./make.bash --no-clean)
    Name: run
    PrependShell: true
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
