MetaArgs: null
Stages:
- As: build-env
  BaseName: golang:1.12-alpine
  Commands:
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - ./
  - CmdLine:
    - apk update && apk add git
    Name: run
    PrependShell: true
  - CmdLine:
    - go mod tidy && GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12-alpine
  Name: build-env
  Platform: ""
  SourceCode: FROM golang:1.12-alpine AS build-env
- As: runtime-env
  BaseName: alpine:3.10
  Commands:
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: build-env
    Name: copy
    SourcesAndDest:
    - /root/jimeagle
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets
    - ./assets
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - templates
    - ./templates
  - CmdLine:
    - apk update && apk add ca-certificates curl bash
    Name: run
    PrependShell: true
  - CmdLine:
    - ./jimeagle
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.10
  Name: runtime-env
  Platform: ""
  SourceCode: FROM alpine:3.10 AS runtime-env
