MetaArgs: null
Stages:
- BaseName: vixns/base
  Commands:
  - Maintainer: Stéphane Cottin <stephane.cottin@vixns.com>
    Name: maintainer
  - Env:
    - Key: OPENSMTPD_VERSION
      Value: 5.7.3p1-1.1
    Name: env
  - CmdLine:
    - export DEBIAN_FRONTEND=noninteractive &&   apt-get update &&   apt-get install
      --no-install-recommends --auto-remove -y opensmtpd=${OPENSMTPD_VERSION} ca-certificates
      &&   rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - smtpd.conf
    - /etc/smtpd.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - opensmtpd.sh
    - /usr/local/bin/opensmtpd
  - Name: expose
    Ports:
    - "25"
  - CmdLine:
    - /usr/local/bin/opensmtpd
    Name: entrypoint
    PrependShell: false
  From:
    Image: vixns/base
  Name: ""
  Platform: ""
  SourceCode: FROM vixns/base
