MetaArgs: null
Stages:
- BaseName: postgres:10-alpine
  Commands:
  - Maintainer: artb1sh ix (https://www.artbitika.ru)
    Name: maintainer
  - Env:
    - Key: PG_WAL_KEEP_SEGMENTS
      Value: "8"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /docker-entrypoint.sh
  - CmdLine:
    - chmod +x /docker-entrypoint.sh
    Name: run
    PrependShell: true
  From:
    Image: postgres:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:10-alpine
