MetaArgs: null
Stages:
- BaseName: cm2network/steamcmd
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - "apt-get update -y && \tapt-get install -y wget unzip nano sudo lib32tinfo5
      locales locales-all && \trm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    - Key: LANGUAGE
      Value: en_US.UTF-8
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Name: user
    User: steam
  - CmdLine:
    - "mkdir /home/steam/css-dedicated && \t./home/steam/steamcmd/steamcmd.sh +login
      anonymous \t+force_install_dir /home/steam/css-dedicated \t+app_update 232330
      validate \t+quit"
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://raw.githubusercontent.com/Laynezilla/docker-css-server/master/css-update.txt
      -o /home/steam/css-dedicated/css_update.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - "mkdir /home/steam/.steam/sdk32 && \tln -s /home/steam/css-dedicated/bin/steamclient.so
      /home/steam/.steam/sdk32/steamclient.so"
    Name: run
    PrependShell: true
  - CmdLine:
    - "curl https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git968-linux.tar.gz
      -o /home/steam/mmsource.tar.gz && \ttar -xzvf /home/steam/mmsource.tar.gz -C
      /home/steam/css-dedicated/cstrike && \trm /home/steam/mmsource.tar.gz && \tcurl
      https://sm.alliedmods.net/smdrop/1.9/sourcemod-1.9.0-git6269-linux.tar.gz -o
      /home/steam/sourcemod.tar.gz && \ttar -xzvf /home/steam/sourcemod.tar.gz -C
      /home/steam/css-dedicated/cstrike && \trm /home/steam/sourcemod.tar.gz && \twget
      -O /home/steam/sm_noblock.zip \"https://forums.alliedmods.net/attachment.php?attachmentid=74064&d=1285431495\"
      && \tunzip -o /home/steam/sm_noblock.zip -d /home/steam/css-dedicated/cstrike
      && \trm /home/steam/sm_noblock.zip && \twget -O /home/steam/sm_teamchange.zip
      \"https://forums.alliedmods.net/attachment.php?attachmentid=110542&d=1349628533\"
      && \tunzip -o /home/steam/sm_teamchange.zip -d /home/steam/css-dedicated/cstrike
      && \trm /home/steam/sm_teamchange.zip"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "27015"
  - CmdLine:
    - /home/steam/css-dedicated/srcds_run -game cstrike -console +map cs_italy
    Name: cmd
    PrependShell: true
  From:
    Image: cm2network/steamcmd
  Name: ""
  Platform: ""
  SourceCode: FROM cm2network/steamcmd
