MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Env:
    - Key: KUBE_LATEST_VERSION
      Value: '"v1.12.2"'
    Name: env
  - Env:
    - Key: HELM_LATEST_VERSION
      Value: '"v2.11.0"'
    Name: env
  - CmdLine:
    - apk add --update ca-certificates  && apk add --update -t deps curl wget  &&
      curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl
      -o /usr/local/bin/kubectl  && chmod +x /usr/local/bin/kubectl  && wget https://storage.googleapis.com/kubernetes-helm/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz  &&
      tar -xvf helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz  && mv linux-amd64/helm
      /usr/local/bin  && rm -f /helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz  &&
      rm -rf linux-amd64 && apk del --purge deps  && rm /var/cache/apk/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
