MetaArgs: null
Stages:
- BaseName: dockerfile/python
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - Name: expose
    Ports:
    - "25"
  - CmdLine:
    - python
    - -m
    - smtpd
    - -n
    - -c
    - DebuggingServer
    - 0.0.0.0:25
    Name: entrypoint
    PrependShell: false
  From:
    Image: dockerfile/python
  Name: ""
  Platform: ""
  SourceCode: FROM dockerfile/python
