MetaArgs: null
Stages:
- BaseName: lab41/cdh5-hadoop
  Commands:
  - Maintainer: Kyle F <kylef@lab41.org>
    Name: maintainer
  - Env:
    - Key: REFRESHED_AT
      Value: "2015-07-29"
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install --assume-yes vim less net-tools inetutils-ping curl git telnet
      nmap socat dnsutils netcat tree htop unzip sudo software-properties-common pkg-config
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes build-essential
      python-dev python-pip liblapack-dev libatlas-dev gfortran libfreetype6 libfreetype6-dev
      libpng12-dev python-lxml libyaml-dev g++ libffi-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&     wget http://download.zeromq.org/zeromq-4.0.3.tar.gz &&     tar
      xvfz zeromq-4.0.3.tar.gz &&     cd zeromq-4.0.3 &&     ./configure &&     make
      install &&     ldconfig &&     rm -rf /tmp/zeromq-4.0.3*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U setuptools
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U distribute
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install numpy==1.7.1
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pandas
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install cython
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install jinja2 pyzmq tornado
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install numexpr bottleneck scipy pygments
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install matplotlib
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install sympy pymc
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install patsy
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install statsmodels
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install beautifulsoup4 html5lib
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --allow-external pattern
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pyyaml nltk
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install networkx
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install biopython
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install requests bokeh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb http://cran.rstudio.com/bin/linux/ubuntu trusty/' > /etc/apt/sources.list.d/r.list
      &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install --assume-yes r-base r-base-core r-base-html
      r-recommended
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install rpy2
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install vincent
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install seaborn
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install scikit-learn
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp; git clone https://github.com/mdp-toolkit/mdp-toolkit.git &&     cd
      /tmp/mdp-toolkit; python setup.py install &&     cd / &&     rm -rf /tmp/mdp-toolkit
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install MDP
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install ipython jsonschema jupyter
    Name: run
    PrependShell: true
  - Env:
    - Key: IPYTHONDIR
      Value: /ipython
    Name: env
  - CmdLine:
    - mkdir $IPYTHONDIR &&     ipython profile create nbserver
    Name: run
    PrependShell: true
  - CmdLine:
    - python2.7
    Name: cmd
    PrependShell: false
  From:
    Image: lab41/cdh5-hadoop
  Name: ""
  Platform: ""
  SourceCode: FROM lab41/cdh5-hadoop
