MetaArgs: null
Stages:
- BaseName: python:3.6-alpine3.6
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Benjamin Mort <ben.mort@gmail.com>"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app/requirements.txt
  - CmdLine:
    - apk add --no-cache --virtual build-dependencies g++ musl-dev libev-dev &&     apk
      add --no-cache libstdc++ curl libev &&     pip install -r /app/requirements.txt
      &&     find /usr/local/lib/python3.6/ -name 'tests' -exec rm -r '{}' + &&     rm
      -r /root/.cache &&     apk del build-dependencies
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9020"
  - Name: expose
    Ports:
    - "5555"
  - Name: expose
    Ports:
    - "9030"
  - Name: workdir
    Path: /app
  - Health:
      Interval: 5000000000
      Retries: 3
      StartPeriod: 5000000000
      Test:
      - CMD-SHELL
      - curl -f http://localhost:5555/healthcheck || exit 1
      Timeout: 2000000000
    Name: healthcheck
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app/sip/zla
  - CmdLine:
    - python3
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -m
    - sip.zla
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-alpine3.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-alpine3.6
