MetaArgs: null
Stages:
- BaseName: agideo/ruby:2.3-f
  Commands:
  - Env:
    - Key: RAILS_ENV
      Value: production
    Name: env
  - Env:
    - Key: SECRET_KEY_BASE
      Value: 61de0a139d3c55461c
    Name: env
  - CmdLine:
    - set -ex   && cd /opt/   && curl -L -O https://github.com/alvin2ye/brimir/archive/0.7.3b.zip   &&
      apt-get update   && apt-get install unzip   && unzip 0.7.3b.zip   && mv brimir-0.7.3b
      brimir   && rm -rf 0.7.3b.zip   && cd brimir   && bundle install   && bin/rake
      assets:precompile
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - app/database.yml
    - /opt/brimir/config/database.yml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/nginx.conf
    - /etc/nginx/conf.d/default.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - app/boot.bash
    - /opt/brimir/boot.bash
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/app.conf
    - /etc/supervisor/conf.d/app.conf
  - Name: workdir
    Path: /opt/brimir
  From:
    Image: agideo/ruby:2.3-f
  Name: ""
  Platform: ""
  SourceCode: FROM agideo/ruby:2.3-f
