MetaArgs: null
Stages:
- BaseName: buildpack-deps:buster
  Commands:
  - Name: workdir
    Path: /root
  - CmdLine:
    - set -x  && apt-get update && apt-get install -y --no-install-recommends liblz4-dev  &&
      rm -rf /var/lib/apt/lists/*  && git clone -b v1.4.4 --depth 1 https://github.com/facebook/zstd.git  &&
      cd zstd  && git log -5  && make  && ./zstd --help
    Name: run
    PrependShell: true
  From:
    Image: buildpack-deps:buster
  Name: ""
  Platform: ""
  SourceCode: FROM buildpack-deps:buster
- BaseName: debian:buster-slim
  Commands:
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /root/zstd/zstd
    - /usr/local/bin/
  - CmdLine:
    - zstd
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:buster-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:buster-slim
