MetaArgs: null
Stages:
- BaseName: debian:stretch
  Commands:
  - CmdLine:
    - apt-get update && apt-get -y install         apt-utils         inkscape         fonts-liberation         fonts-font-awesome
      &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home
  - CmdLine:
    - inkscape
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:stretch
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stretch
