MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: IgorSh
    Name: maintainer
  - CmdLine:
    - groupadd -r -g 1000 crawl && useradd -r -m -g crawl -u 1000 crawl
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update \t&& apt-get install --no-install-recommends --no-install-suggests
      -y     ca-certificates locales wget git python-pip"
    Name: run
    PrependShell: true
  - Env:
    - Key: GOSU_VERSION
      Value: "1.7"
    Name: env
  - CmdLine:
    - set -x         && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg
      --print-architecture)"         && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg
      --print-architecture).asc"         && export GNUPGHOME="$(mktemp -d)"         &&
      gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4         &&
      gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu         &&
      rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc         && chmod +x /usr/local/bin/gosu         &&
      gosu nobody true
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_CTYPE
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - "touch /etc/locale.conf \t&& echo -e \"LANG=en_US.UTF-8 \\nLANGUAGE=en_US.UTF-8
      \\nLC_CTYPE=en_US.UTF-8 \\nLC_ALL=en_US.UTF-8 \\n\" > /etc/locale.conf \t&&
      locale-gen en_US.UTF-8 \t&& echo \"146\\n3\\n\" | dpkg-reconfigure locales"
    Name: run
    PrependShell: true
  - CmdLine:
    - "git clone https://github.com/crawl/crawl.git && cd /crawl \t&& git checkout
      0.18.1         && git submodule update --init \t&& mkdir -p /crawl/crawl-ref/source/rcs
      \t&& mkdir -p /crawl/crawl-ref/source/saves"
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update \t&& apt-get install --no-install-recommends --no-install-suggests
      -y     build-essential     libncursesw5-dev     bison     flex     liblua5.1-0-dev
      \    libsqlite3-dev     libz-dev     pkg-config     libsdl2-image-dev     libsdl2-mixer-dev
      \    libsdl2-dev     libfreetype6-dev     libpng-dev     ttf-dejavu-core         &&
      rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U pip && pip install 'tornado>=3.0,<4.0'
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /crawl/crawl-ref/source && make WEBTILES=y
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - "chown -R crawl:crawl /entrypoint.sh \t&& chmod 777 /entrypoint.sh \t&& chown
      -R crawl:crawl /crawl"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /crawl/crawl-ref/source
  - Name: volume
    Volumes:
    - /crawl
  - Name: volume
    Volumes:
    - /crawl/crawl-ref/source/saves
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - python
    - ./webserver/server.py
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
