MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends     gdal-bin     postgresql-client  &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /output
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /usr/src/app
  - CmdLine:
    - ./export-geojson.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
