MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Key: RUNDECK_VERSION
    Name: arg
    Value: 2.6.8
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openjdk-7-jre
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get install -y \t\tapt-transport-https \t\tca-certificates \t\tsubversion
      \t\tgit \t\tpython   \tpython-pip   \tcurl   \t&& curl -sLo /usr/local/bin/ep
      \t\t'https://github.com/kreuzwerker/envplate/releases/download/1.0.0-RC1/ep-linux'
      \t&& chmod +x /usr/local/bin/ep \t&& apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80
      --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \t&& echo \"deb https://apt.dockerproject.org/repo
      ubuntu-trusty main\" > /etc/apt/sources.list.d/docker.list"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get install -y docker-engine \t&& pip install docker-compose"
    Name: run
    PrependShell: true
  - CmdLine:
    - "curl -sLo /tmp/rundeck.deb http://dl.bintray.com/rundeck/rundeck-deb/rundeck-${RUNDECK_VERSION}-1-GA.deb
      \t&& sudo dpkg -i /tmp/rundeck.deb \t&& rm -f /tmp/rundeck.deb"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files
    - /etc/rundeck
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rundeck.sh
    - /rundeck.sh
  - CmdLine:
    - "find /etc/rundeck -type f -exec chmod 644 {} \\;;find /etc/rundeck -type d
      -exec chmod 755 {} \\;; chown -R rundeck:rundeck /var/lib/rundeck/* \t&& chmod
      +x /rundeck.sh"
    Name: run
    PrependShell: true
  - Name: stopsignal
    Signal: SIGKILL
  - Name: expose
    Ports:
    - "4440"
  - Name: volume
    Volumes:
    - /etc/rundeck
    - /var/rundeck/projects
    - /var/lib/rundeck/var
    - /var/lib/rundeck/logs
    - /opt/rundeck-plugins
  - CmdLine:
    - /rundeck.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
