MetaArgs: null
Stages:
- BaseName: node:8.11.3
  Commands:
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: warn
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn start
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: node:8.11.3
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.11.3
