MetaArgs: null
Stages:
- BaseName: dev3170/docker_base:nginx-1.16_aspnetcore-3.0_alpine-3.10
  Commands:
  - Name: workdir
    Path: /home/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /config/etc/
    - /etc/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /config/nginx/
    - /etc/nginx/
  From:
    Image: dev3170/docker_base:nginx-1.16_aspnetcore-3.0_alpine-3.10
  Name: ""
  Platform: ""
  SourceCode: FROM dev3170/docker_base:nginx-1.16_aspnetcore-3.0_alpine-3.10
