MetaArgs: null
Stages:
- BaseName: dannyben/alpine-ruby
  Commands:
  - Name: workdir
    Path: /app
  - CmdLine:
    - gem install json loadrunner
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine: []
    Name: cmd
    PrependShell: false
  - CmdLine:
    - loadrunner
    Name: entrypoint
    PrependShell: false
  From:
    Image: dannyben/alpine-ruby
  Name: ""
  Platform: ""
  SourceCode: FROM dannyben/alpine-ruby
