MetaArgs: null
Stages:
- BaseName: kerlak/amazonlinux-elixir
  Commands:
  - Maintainer: Juan Carlos Pazos Mandiá <jucapaman@gmail.com>
    Name: maintainer
  - CmdLine:
    - yes | mix local.hex &&     yes | mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
      &&     wget https://nodejs.org/dist/v6.11.1/node-v6.11.1-linux-x64.tar.xz &&     tar
      xJf node-v6.11.1-linux-x64.tar.xz && rm node-v6.11.1-linux-x64.tar.xz
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:/node-v6.11.1-linux-x64/bin:/usr/bin/
    Name: env
  - CmdLine:
    - npm install brunch -g
    Name: run
    PrependShell: true
  From:
    Image: kerlak/amazonlinux-elixir
  Name: ""
  Platform: ""
  SourceCode: FROM kerlak/amazonlinux-elixir
