MetaArgs: null
Stages:
- BaseName: quay.io/danimaribeiro/docker-odoo-base:11.0
  Commands:
  - Name: workdir
    Path: /opt/odoo
  - CmdLine:
    - apt-get install -y unzip git wget gettext-base
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/Trust-Code/odoo-product-configurator/archive/11.0.zip
      -O odoo-product-configurator.zip &&     wget https://github.com/Trust-Code/trustcode-addons/archive/11.0.zip
      -O trustcode-addons.zip &&     wget https://github.com/Trust-Code/odoo-brasil/archive/11.0.zip
      -O odoo-brasil.zip &&     wget https://github.com/Trust-Code/odoo/archive/11.0.zip
      -O odoo.zip &&     wget https://github.com/Trust-Code/stock-logistics-warehouse/archive/11.0.zip
      -O stock-logistics-warehouse.zip &&     wget https://github.com/Trust-Code/queue/archive/11.0.zip
      -O queue.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip -q odoo-brasil.zip && rm odoo-brasil.zip && mv odoo-brasil-11.0 odoo-brasil
      &&     unzip -q odoo.zip && rm odoo.zip && mv odoo-11.0 odoo &&     unzip -q
      trustcode-addons.zip && rm trustcode-addons.zip && mv trustcode-addons-11.0
      trustcode-addons &&     unzip -q odoo-product-configurator.zip && rm odoo-product-configurator.zip
      && mv odoo-product-configurator-11.0 odoo-product-configurator &&     unzip
      -q stock-logistics-warehouse.zip && rm stock-logistics-warehouse.zip && mv stock-logistics-warehouse-11.0
      stock-logistics-warehouse &&     unzip -q queue.zip && rm queue.zip && mv queue-11.0
      queue &&     cd odoo && find . -name "*.po" -not -name "pt_BR.po" -not -name
      "pt.po"  -type f -delete &&     find . -path "*l10n_*" -delete &&     rm -R
      debian && rm -R doc && rm -R setup && cd ..
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --no-cache-dir pytrustnfe3 python3-cnab python3-boleto pycnab240
      python-sped
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/odoo.conf
    - /etc/odoo/
  - CmdLine:
    - chown -R odoo:odoo /opt &&     chown -R odoo:odoo /etc/odoo/odoo.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/.ssh &&     chown -R odoo:odoo /opt/.ssh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/autoupdate
    - /opt/odoo
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/entrypoint.sh
    - /opt/odoo
  - CmdLine:
    - chown odoo:odoo /opt/odoo/autoupdate &&     chmod +x /opt/odoo/autoupdate &&     chmod
      +x /opt/odoo/entrypoint.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/odoo
  - Env:
    - Key: PG_HOST
      Value: localhost
    Name: env
  - Env:
    - Key: PG_PORT
      Value: "5432"
    Name: env
  - Env:
    - Key: PG_USER
      Value: odoo
    Name: env
  - Env:
    - Key: PG_PASSWORD
      Value: odoo
    Name: env
  - Env:
    - Key: PG_DATABASE
      Value: "False"
    Name: env
  - Env:
    - Key: ODOO_PASSWORD
      Value: senha_admin
    Name: env
  - Env:
    - Key: PORT
      Value: "8069"
    Name: env
  - Env:
    - Key: LOG_FILE
      Value: /var/log/odoo/odoo.log
    Name: env
  - Env:
    - Key: LONGPOLLING_PORT
      Value: "8072"
    Name: env
  - Env:
    - Key: WORKERS
      Value: "3"
    Name: env
  - Env:
    - Key: DISABLE_LOGFILE
      Value: "0"
    Name: env
  - Env:
    - Key: USE_SPECIFIC_REPO
      Value: "0"
    Name: env
  - Env:
    - Key: TRUSTCODE_APPS
      Value: "0"
    Name: env
  - Env:
    - Key: TRUSTCODE_ENTERPRISE
      Value: "0"
    Name: env
  - Env:
    - Key: TRUSTCODE_ONLY
      Value: "0"
    Name: env
  - Env:
    - Key: TIME_CPU
      Value: "600"
    Name: env
  - Env:
    - Key: TIME_REAL
      Value: "720"
    Name: env
  - Name: volume
    Volumes:
    - /opt/
    - /etc/odoo
  - CmdLine:
    - /opt/odoo/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: quay.io/danimaribeiro/docker-odoo-base:11.0
  Name: ""
  Platform: ""
  SourceCode: FROM quay.io/danimaribeiro/docker-odoo-base:11.0
