MetaArgs: null
Stages:
- BaseName: nginx
  Commands:
  - Name: expose
    Ports:
    - "9200"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - CmdLine:
    - /entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nginx
  Name: ""
  Platform: ""
  SourceCode: FROM nginx
