MetaArgs:
- DefaultValue: "8.5"
  Key: TOMCAT_VERSION
  ProvidedValue: null
  Value: "8.5"
- DefaultValue: jre8
  Key: TOMCAT_JRE
  ProvidedValue: null
  Value: jre8
Stages:
- As: builder
  BaseName: maven:3-jdk-8
  Commands:
  - Key: BUILD_PROFILE
    Name: arg
    Value: null
  - Env:
    - Key: BUILD_DIR
      Value: /tmp/guacamole-docker-BUILD
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - guacamole-docker/bin/
    - /opt/guacamole/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - '"$BUILD_DIR"'
  - CmdLine:
    - /opt/guacamole/bin/build-guacamole.sh "$BUILD_DIR" /opt/guacamole "$BUILD_PROFILE"
    Name: run
    PrependShell: true
  From:
    Image: maven:3-jdk-8
  Name: builder
  Platform: ""
  SourceCode: FROM maven:3-jdk-8 AS builder
- BaseName: tomcat:${TOMCAT_VERSION}-${TOMCAT_JRE}
  Commands:
  - Name: workdir
    Path: /opt/guacamole
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /opt/guacamole/
    - .
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /opt/guacamole/bin/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: tomcat:${TOMCAT_VERSION}-${TOMCAT_JRE}
  Name: ""
  Platform: ""
  SourceCode: FROM tomcat:${TOMCAT_VERSION}-${TOMCAT_JRE}
