MetaArgs: null
Stages:
- BaseName: elasticsearch:1
  Commands:
  - Maintainer: Dmitriy Belyaev "dimabelyaev27@gmail.com"
    Name: maintainer
  - CmdLine:
    - /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head/1.x
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/share/elasticsearch/bin/plugin -install polyfractal/elasticsearch-inquisitor
    Name: run
    PrependShell: true
  From:
    Image: elasticsearch:1
  Name: ""
  Platform: ""
  SourceCode: FROM elasticsearch:1
