MetaArgs: null
Stages:
- BaseName: fernandoenzo/debian:10s-min
  Commands:
  - Maintainer: Fernando Enzo Guarini (fernandoenzo@gmail.com)
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/basics
    - /tmp
  - CmdLine:
    - bash /tmp/basics
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/boot
    - /usr/local/boot
  - Name: volume
    Volumes:
    - /srv
  From:
    Image: fernandoenzo/debian:10s-min
  Name: ""
  Platform: ""
  SourceCode: FROM fernandoenzo/debian:10s-min
