MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-get update   && apt-get install -y --no-install-recommends         apt-transport-https         ca-certificates         curl         bzip2         fontconfig         gnupg         libfontconfig         lsb-release         python   &&
      apt-get clean   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x   && curl -fLs https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
      |     tar xjf - -C /usr --strip-components=1 phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x   && curl -sL https://deb.nodesource.com/setup_6.x | bash -   && apt-get
      install -y --no-install-recommends     nodejs   && apt-get clean   && rm -rf
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x   && npm install -g casperjs   && echo /usr/lib/node_modules/casperjs/bin/casperjs
      selftest
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - /usr/bin/casperjs
    Name: entrypoint
    PrependShell: false
  - Labels:
    - Key: version
      Value: '"1.0.0"'
    - Key: maintainer
      Value: '"stb@lassitu.de"'
    - Key: phantomjs.version
      Value: '"2.1.1"'
    - Key: casperjs.version
      Value: '"1.1.4"'
    Name: label
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
