MetaArgs: null
Stages:
- BaseName: node:6-alpine
  Commands:
  - Name: workdir
    Path: /var/www
  - CmdLine:
    - npm install -g gulp
    Name: run
    PrependShell: true
  - CmdLine:
    - node
    Name: cmd
    PrependShell: false
  From:
    Image: node:6-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:6-alpine
