MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends git python3.7-dev
      python3-pip build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - python3.7 -m pip install setuptools wheel
    Name: run
    PrependShell: true
  - CmdLine:
    - python3.7 -m pip install gunicorn uvicorn
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://api.github.com/repos/TenteEEEE/quiche_pantie_patch/git/refs/heads/master
    - version.json
  - CmdLine:
    - git clone https://github.com/TenteEEEE/quiche_pantie_patch.git --depth 1
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /quiche_pantie_patch
  - CmdLine:
    - python3.7 -m pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - git pull ; gunicorn --bind 0.0.0.0:5000 restapi:app -k uvicorn.workers.UvicornWorker
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
