MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Quinn Yost <qyost@discover.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y netcat
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'Hi, I am in your container'     >/tmp/index.html
    Name: run
    PrependShell: true
  - CmdLine:
    - netcat
    - -l
    - -p 8080 < /tmp/index.html;
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
