MetaArgs: null
Stages:
- BaseName: purmode/hubcms
  Commands:
  - Maintainer: Purmode R <prdev@outlook.com>
    Name: maintainer
  - Env:
    - Key: HUBSITE
      Value: '''myhubsite'''
    Name: env
  - CmdLine:
    - "touch /hub_install_script.sh \t&& chmod +x /hub_install_script.sh \t&& echo
      \"#!/bin/bash\" > /hub_install_script.sh \t&& echo \"service mysql start; sleep
      3\" >> /hub_install_script.sh \t&& echo \"service apache2 start; sleep 3\" >>
      /hub_install_script.sh \t&& echo \"hzcms install \\$HUBSITE\" >> /hub_install_script.sh
      \t&& echo \"hzcms update\" >> /hub_install_script.sh \t&& echo \"a2dissite default
      default-ssl\" >> /hub_install_script.sh \t&& echo \"a2ensite \\$HUBSITE \\$HUBSITE-ssl\"
      >> /hub_install_script.sh \t&& echo \"service apache2 restart\" >> /hub_install_script.sh
      \t&& echo \"apt-get update\" >> /hub_install_script.sh \t&& echo \"apt-get install
      -y hubzero-cms-2.1.0\" >> /hub_install_script.sh \t&& echo \"hzcms update\"
      >> /hub_install_script.sh \t&& echo \"apt-get purge -y hubzero-cms-2.0.0 &&
      apt-get clean\" >> /hub_install_script.sh \t&& echo \"mv /hub_install_script.sh
      /hub_install_tmp.sh\" >> /hub_install_script.sh \t&& echo \"echo \\\"#!/bin/bash\\\"
      > /hub_install_tmp.sh\" >> /hub_install_script.sh \t&& echo \"echo \\\"mv /hub_install_tmp.sh
      /hub_install_script.sh\\\" >> /hub_install_tmp.sh\" >> /hub_install_script.sh
      \t&& echo \"echo \\\"echo \\\\\\\"#!/bin/bash\\\\\\\" > /hub_install_script.sh\\\"
      >> /hub_install_tmp.sh\" >> /hub_install_script.sh \t&& echo \"echo \\\"echo
      \\\\\\\"service mysql start\\\\\\\" >> /hub_install_script.sh\\\" >> /hub_install_tmp.sh\"
      >> /hub_install_script.sh \t&& echo \"echo \\\"echo \\\\\\\"service apache2
      start\\\\\\\" >> /hub_install_script.sh\\\" >> /hub_install_tmp.sh\" >> /hub_install_script.sh
      \t&& echo \"echo \\\"echo \\\\\\\"/bin/bash\\\\\\\" >> /hub_install_script.sh\\\"
      >> /hub_install_tmp.sh\" >> /hub_install_script.sh \t&& echo \"echo \\\"sh /hub_install_script.sh\\\"
      >> /hub_install_tmp.sh\" >> /hub_install_script.sh \t&& echo \"sh /hub_install_tmp.sh\"
      >> /hub_install_script.sh"
    Name: run
    PrependShell: true
  - CmdLine:
    - /hub_install_script.sh
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "443"
    - "80"
  From:
    Image: purmode/hubcms
  Name: ""
  Platform: ""
  SourceCode: FROM purmode/hubcms
