MetaArgs: null
Stages:
- BaseName: ubuntu:17.10
  Commands:
  - CmdLine:
    - groupadd -g 1001 user
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -r -u 1001 -g user --create-home user
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i     s/archive\.ubuntu\.com/la-mirrors.evowise.com/g /etc/apt/sources.list
      &&   apt-get update &&   apt-get install --no-install-recommends -y     texlive     texlive-latex-recommended     texlive-latex-extra     texlive-lang-spanish     texlive-xetex     lmodern     ttf-ubuntu-font-family     openjdk-8-jre     python3.7     virtualenv
      python-virtualenv     locales     plantuml     curl &&   rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen es_AR.UTF-8 && update-locale
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -LO   https://github.com/jgm/pandoc/releases/download/2.7/pandoc-2.7-1-amd64.deb
      &&   dpkg -i pandoc-2.7-1-amd64.deb &&   rm pandoc-2.7-1-amd64.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/local/bin
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /tmp
  - CmdLine:
    - sed 's/USERNAME/${USERNAME}/g' </tmp/entrypoint.sh >/usr/local/bin/entrypoint
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /usr/local/bin/entrypoint
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - plantuml
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - plantuml.jar
    - /usr/local/bin/
  - Name: user
    User: ${USERNAME}
  - CmdLine:
    - virtualenv -p python3 /home/${USERNAME}/env
    Name: run
    PrependShell: true
  - CmdLine:
    - . /home/${USERNAME}/env/bin/activate &&   curl -L -o /tmp/requirements.txt      https://raw.githubusercontent.com/bmc/ebook-template/master/requirements.txt
      &&   pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt &&   pip
      install WeasyPrint
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/${USERNAME}/book
  - Name: volume
    Volumes:
    - /home/${USERNAME}/book
  - CmdLine:
    - /usr/local/bin/entrypoint
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:17.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:17.10
