MetaArgs: null
Stages:
- BaseName: golang
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y libwebkit2gtk-3.0-dev xvfb
    Name: run
    PrependShell: true
  - CmdLine:
    - go get github.com/sourcegraph/go-webkit2/...
    Name: run
    PrependShell: true
  From:
    Image: golang
  Name: ""
  Platform: ""
  SourceCode: FROM golang
