MetaArgs: null
Stages:
- BaseName: maven:3
  Commands:
  - CmdLine:
    - apt-get update && apt-get -y install git
    Name: run
    PrependShell: true
  From:
    Image: maven:3
  Name: ""
  Platform: ""
  SourceCode: FROM maven:3
