MetaArgs: null
Stages:
- BaseName: mhart/alpine-node:latest
  Commands:
  - CmdLine:
    - apk add --update tini unzip
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/plouc/mozaik-demo/archive/master.zip
    - /
  - CmdLine:
    - unzip master.zip &&     mv mozaik-demo-master mozaik
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /mozaik
  - CmdLine:
    - npm install &&     npm install mozaik-ext-jenkins &&     npm install mozaik-ext-json
      &&     npm install mozaik-ext-value &&     npm run build-assets &&     mv /mozaik/config.js
      /mozaik/config.js.bak
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - '"/mozaik"'
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - /sbin/tini
    - --
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /bin/sh
    - /entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: mhart/alpine-node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM mhart/alpine-node:latest
