MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"citraemu"'
    Name: label
  - CmdLine:
    - apt-get update && apt-get -y full-upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y p7zip-full wget git flatpak flatpak-builder ca-certificates
      sshfs curl fuse dnsutils gnupg2 sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    Name: run
    PrependShell: true
  - CmdLine:
    - flatpak install -y flathub org.kde.Platform//5.12 org.kde.Sdk//5.12
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
