MetaArgs: null
Stages:
- As: builder
  BaseName: openjdk:8-jdk
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Peter Stadler"'
    Name: label
  - CmdLine:
    - apt-get update     && apt-get install --yes --no-install-recommends --no-install-suggests
      ant
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/builder
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - ant
    Name: run
    PrependShell: true
  From:
    Image: openjdk:8-jdk
  Name: builder
  Platform: ""
  SourceCode: FROM openjdk:8-jdk as builder
- BaseName: nginx:alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Daniel Röwenstrunk for the FreiDi"'
    Name: label
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /opt/builder/dist/
    - /usr/share/nginx/html/
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
