MetaArgs: null
Stages:
- As: build
  BaseName: debian:stretch-slim
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Pavel Volkovitskiy <olfway@olfway.net>"'
    Name: label
  - Env:
    - Key: LANG
      Value: '''C.UTF-8'''
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Key: QEMU_RELEASE
    Name: arg
    Value: 2.12.0
  - Key: QEMU_RELEASE_SUM
    Name: arg
    Value: e69301f361ff65bf5dabd8a19196aeaa5613c1b5ae1678f0823bdf50e7d5c6fc
  - CmdLine:
    - set -x     && echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/zz-no-install-recommends
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x     && apt-get update     && apt-get dist-upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x     && apt-get install -y        bison        build-essential        ca-certificates        curl        file        flex        gnupg        libglib2.0-dev        libpixman-1-dev        pkg-config        python        rename        zlib1g-dev
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src
  - CmdLine:
    - set -x     && curl -s -o "qemu-${QEMU_RELEASE}.tar.xz" "https://download.qemu.org/qemu-${QEMU_RELEASE}.tar.xz"     &&
      echo "${QEMU_RELEASE_SUM} qemu-${QEMU_RELEASE}.tar.xz" | sha256sum --check     &&
      tar -axf "qemu-${QEMU_RELEASE}.tar.xz"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/qemu
  - CmdLine:
    - set -x     && /usr/src/qemu-${QEMU_RELEASE}/configure         --prefix=/usr         --disable-blobs         --disable-system         --disable-tools         --disable-guest-agent         --static         --target-list=arm-linux-user,aarch64-linux-user     &&
      make     && make install DESTDIR=/usr/src/qemu-root/     && rename 's/$/-static/'
      /usr/src/qemu-root/usr/bin/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stretch-slim
  Name: build
  Platform: ""
  SourceCode: FROM debian:stretch-slim as build
- BaseName: scratch
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Pavel Volkovitskiy <olfway@olfway.net>"'
    Name: label
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /usr/src/qemu-root/usr/bin/*
    - /
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
