MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get -y dist-upgrade -y &&     apt-get -y autoremove
      &&     apt-get -y install php7.0 php7.0-cli php7.0-mcrypt php7.0-mysql nginx
      curl openssl wget git php7.0-curl php7.0-xml php7.0-intl php7.0-gd php7.0-mbstring
      php7.0-fpm ssl-cert unzip zip &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/lib/nginx
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www && chmod -R 0755 /var/www
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dist/php.ini
    - /etc/php/7.0/fpm/php.ini
  - CmdLine:
    - service php7.0-fpm start
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dist/nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dist/default
    - /etc/nginx/sites-available/default
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dist/install-composer.sh
    - .
  - CmdLine:
    - ./install-composer.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/www/html/index.nginx-debian.html
    Name: run
    PrependShell: true
  - CmdLine:
    - service php7.0-fpm start && nginx
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
