MetaArgs: null
Stages:
- BaseName: boot2docker/boot2docker:latest
  Commands:
  - Maintainer: Vrakfall <jeremy@artphotolaurent.be>
    Name: maintainer
  - CmdLine:
    - rm $ROOTFS/etc/rc.d/automount-shares &&   WHITELINETOREMOVE=$(( $(sed -n -r
      '/\/etc\/rc.d\/automount-shares/ =' $ROOTFS/opt/bootscript.sh) + 1)) &&   sed
      -i -r $WHITELINETOREMOVE'{/^$/d}' $ROOTFS/opt/bootscript.sh $ROOTFS/opt/bootscript.sh
      &&   sed -i -r '/# Automount Shared Folders \(VirtualBox, etc\.\)/d' $ROOTFS/opt/bootscript.sh
      $ROOTFS/opt/bootscript.sh &&   sed -i -r '/\/etc\/rc.d\/automount-shares/d'
      $ROOTFS/opt/bootscript.sh $ROOTFS/opt/bootscript.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir $ROOTFS/Users &&   echo "192.168.59.3:/Users /Users nfs rw,async,noatime,rsize=32768,wsize=32768,proto=tcp
      0 0" >> $ROOTFS/etc/fstab &&   echo "\n# Start the nfs client\n/usr/local/etc/init.d/nfs-client
      start" >> $ROOTFS/opt/bootscript.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /make_iso.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - cat
    - boot2docker.iso
    Name: cmd
    PrependShell: false
  From:
    Image: boot2docker/boot2docker:latest
  Name: ""
  Platform: ""
  SourceCode: FROM boot2docker/boot2docker:latest
