MetaArgs: null
Stages:
- BaseName: google/nodejs-runtime
  Commands:
  - Name: volume
    Volumes:
    - /root/.npm_lazy
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - --show-config
    - --external-url=http://strategenics__npm_lazy:8080
    Name: cmd
    PrependShell: false
  - CmdLine:
    - /nodejs/bin/node
    - index.js
    Name: entrypoint
    PrependShell: false
  From:
    Image: google/nodejs-runtime
  Name: ""
  Platform: ""
  SourceCode: FROM google/nodejs-runtime
