MetaArgs: null
Stages:
- BaseName: python:3.7
  Commands:
  - Maintainer: PEI-i1
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y     gcc     gfortran     libblas-dev     liblapack-dev     libhdf5-dev     git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/PEI-I1/Chat_Processor.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: Chat_Processor
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - python -m deeppavlov install ner_ontonotes_bert_mult
    Name: run
    PrependShell: true
  - CmdLine:
    - python
    - chat_processor/app.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7
