MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - CmdLine:
    - apk add --no-cache ansible=2.4.1.0-r0 openssh-client &&     apk add --no-cache
      --virtual .deps py2-pip &&     pip2 install awscli boto boto3 &&     apk del
      .deps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /root/
  - CmdLine:
    - /root/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
