MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - CmdLine:
    - curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - &&     yum
      install -y rpmdevtools sudo nodejs git
    Name: run
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
