MetaArgs: null
Stages:
- BaseName: python:3.7.4-buster
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Davis Templeton <davistempleton3@gmail.com>"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /
  - CmdLine:
    - "pip install \t\t--requirement requirements.txt \t\t--upgrade; \tcd /var/local/
      && \tdjango-admin startproject \t\t--template https://github.com/BashfulBandit/django-project-template/archive/v2.2.zip
      \t\twebsite;"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/local/website/
  - Name: expose
    Ports:
    - "8000"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - wait-for-it.sh
    - /usr/local/bin/
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - gunicorn
    - --config
    - config.py
    - website.wsgi:application
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.7.4-buster
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7.4-buster
