MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: Marc Villacorta Morera <marc.villacorta@gmail.com>
    Name: maintainer
  - Env:
    - Key: VERSION
      Value: '"1.0.7"'
    - Key: REPO
      Value: '"https://github.com/janeczku/go-dnsmasq"'
    - Key: DNSMASQ_LISTEN
      Value: '"0.0.0.0"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ${REPO}/releases/download/${VERSION}/go-dnsmasq-min_linux-amd64
    - /go-dnsmasq
  - CmdLine:
    - chmod +x /go-dnsmasq
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "53"
    - 53/udp
  - CmdLine:
    - /go-dnsmasq
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
