MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sorah-ruby.gpg.key
    - /root/sorah-ruby.gpg.key
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nodesource.gpg.key
    - /root/nodesource.gpg.key
  - CmdLine:
    - apt-key add /root/nodesource.gpg.key && apt-key add /root/sorah-ruby.gpg.key
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&   apt-get install -y curl git-core build-essential apt-transport-https
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb [arch=amd64] https://cache.ruby-lang.org/lab/sorah/deb/ xenial main"
      > /etc/apt/sources.list.d/sorah-ruby.list
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nodesource.list.xenial
    - /etc/apt/sources.list.d/nodesource.list
  - CmdLine:
    - apt-get update &&   apt-get install -y   ruby=1:2.4.0+0nkmi1~xenial   ruby2.4=2.4.1-0nkmi1~xenial   libruby2.4=2.4.1-0nkmi1~xenial   ruby2.4-dev=2.4.1-0nkmi1~xenial   ruby2.4-gems=2.4.1-0nkmi1~xenial   libxml2-dev
      libxslt-dev zlib1g-dev &&   env DEBIAN_FRONTEND=noninteractive apt-get install
      -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install bundler
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/unicorn
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - unicorn.conf.rb
    - /etc/unicorn/unicorn.conf.rb
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
