MetaArgs: null
Stages:
- BaseName: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
  Commands:
  - CmdLine:
    - yum -y install unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - bin/elasticsearch-plugin install --batch repository-gcs
    Name: run
    PrependShell: true
  From:
    Image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
  Name: ""
  Platform: ""
  SourceCode: FROM docker.elastic.co/elasticsearch/elasticsearch:7.4.0
