MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - Maintainer: dev@adex.network
    Name: maintainer
  - Env:
    - Key: PORT
      Value: ""
    Name: env
  - Env:
    - Key: ADAPTER
      Value: ""
    Name: env
  - Env:
    - Key: IDENTITY
      Value: ""
    Name: env
  - Env:
    - Key: DB_MONGO_URL
      Value: ""
    Name: env
  - Env:
    - Key: DB_MONGO_NAME
      Value: ""
    Name: env
  - Env:
    - Key: KEYSTORE_FILE
      Value: ""
    Name: env
  - Env:
    - Key: KEYSTORE_PASSWORD
      Value: ""
    Name: env
  - CmdLine:
    - echo 'http://dl-3.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
      &&     apk upgrade --update
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --update alpine-sdk
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --update python
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cloudflare_origin.crt
    - /usr/local/share/ca-certificates/
  - CmdLine:
    - update-ca-certificates
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_EXTRA_CA_CERTS
      Value: /usr/local/share/ca-certificates/cloudflare_origin.crt
    Name: env
  - Name: workdir
    Path: /app
  - Name: expose
    Ports:
    - ${PORT}
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - CmdLine:
    - PORT=${PORT} node bin/sentry.js --adapter=${ADAPTER} --keystoreFile=${KEYSTORE_FILE}
      --clustered
    Name: cmd
    PrependShell: true
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
