MetaArgs: null
Stages:
- BaseName: python:3.5-buster
  Commands:
  - Env:
    - Key: PYPI_REPO
      Value: https://pypi.python.org/simple/
    Name: env
  - CmdLine:
    - "apt-get update && apt-get install -y --no-install-recommends \t\tnginx \t&&
      rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - documents
    - /tmp/documents
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /tmp
  - CmdLine:
    - pip install --no-cache-dir -r /tmp/requirements.txt -i ${PYPI_REPO}
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - templates
    - /tmp/templates
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - action.yaml
    - .
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /bin/bash
    - entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.5-buster
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.5-buster
