MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --no-install-recommends nodejs npm nodejs-legacy graphicsmagick
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: node_modules/.bin:$PATH
    Name: env
  - Name: workdir
    Path: /opt/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /opt/package.json
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app.js
    - /opt/app.js
  - CmdLine:
    - node
    - app.js
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
