MetaArgs: null
Stages:
- BaseName: justincormack/rumprun-nginx-lua
  Commands:
  - Maintainer: Justin Cormack <justin@specialbusservice.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/rump-nginx-lua-test
  - Name: workdir
    Path: /usr/src/rump-nginx-lua-test
  - CmdLine:
    - genisoimage -l -r -o etc.iso etc &&   genisoimage -l -r -o data.iso data
    Name: run
    PrependShell: true
  - CmdLine:
    - rumprun qemu -i -I 'qnet0,vioif,-net tap,ifname=tap0' -W qnet0,inet,dhcp -b
      etc.iso,/etc -b data.iso,/data /usr/local/bin/nginx.hw_virtio -- -c /data/conf/nginx.conf
    Name: cmd
    PrependShell: true
  From:
    Image: justincormack/rumprun-nginx-lua
  Name: ""
  Platform: ""
  SourceCode: FROM justincormack/rumprun-nginx-lua
