MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Michaela Böckler
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - "apt-get update && apt-get install -y  \tlibgl1-mesa-dri \tlibgl1-mesa-glx \topenssh-client
      \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sshclient.sh
    - /opt/
  - CmdLine:
    - chmod +x /opt/sshclient.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/sshclient.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
