MetaArgs: null
Stages:
- BaseName: php:5.6-fpm-alpine3.4
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/php/5.6
    - /etc/php/5.6
  - CmdLine:
    - "echo http://dl-cdn.alpinelinux.org/alpine/v3.5/community >> /etc/apk/repositories
      && \tapk add --no-cache --virtual php-deps \t\tgettext \t\tlibxml2 \t\tlibxslt
      \t\topenssl \t\tpcre \t\treadline \t\tshadow && \tgroupmod -o -g 33 www-data
      && usermod -o -u 33 www-data"
    Name: run
    PrependShell: true
  - Key: CONFIGURE_PARAMS
    Name: arg
    Value: "\"\t\t--datadir=/usr/share/php/5.6 \t\t--disable-all \t\t--disable-cgi
      \t\t--disable-debug \t\t--disable-phpdbg \t\t--disable-rpath \t\t--disable-static
      \t\t--enable-calendar=shared \t\t--enable-ctype=shared \t\t--enable-dom=shared
      \t\t--enable-exif=shared \t\t--enable-fileinfo=shared \t\t--enable-filter \t\t--enable-ftp=shared
      \t\t--enable-json=shared \t\t--enable-libxml \t\t--enable-mysqlnd=shared \t\t--enable-opcache=shared
      \t\t--enable-pdo=shared \t\t--enable-phar=shared \t\t--enable-posix=shared \t\t--enable-session
      \t\t--enable-shmop=shared \t\t--enable-simplexml=shared \t\t--enable-sockets=shared
      \t\t--enable-sysvmsg=shared \t\t--enable-sysvsem=shared \t\t--enable-sysvshm=shared
      \t\t--enable-tokenizer=shared \t\t--enable-wddx=shared \t\t--enable-xml=shared
      \t\t--enable-xmlreader=shared \t\t--enable-xmlwriter=shared \t\t--includedir=/usr/include
      \t\t--infodir=/usr/share/info \t\t--libdir=/usr/lib/php \t\t--libexecdir=/usr/lib/php
      \t\t--localstatedir=/var \t\t--mandir=/usr/share/man \t\t--prefix=/usr \t\t--sysconfdir=/etc
      \t\t--with-gettext=shared \t\t--with-iconv=shared \t\t--with-mhash=/usr \t\t--with-openssl=yes
      \t\t--with-pcre-regex=/usr \t\t--with-pic \t\t--with-readline=shared \t\t--with-xsl=shared
      \t\t--with-zlib-dir=/usr \t\t--with-zlib=/usr \t\t--without-pear\""
  - CmdLine:
    - "rm -f \t\t/usr/local/bin/pear \t\t/usr/local/bin/peardev \t\t/usr/local/bin/pecl
      \t\t/usr/local/bin/phar \t\t/usr/local/bin/phar.phar \t\t/usr/local/bin/php
      \t\t/usr/local/bin/php-config \t\t/usr/local/bin/phpize \t\t/usr/local/sbin/php-fpm"
    Name: run
    PrependShell: true
  - CmdLine:
    - "apk add --no-cache --virtual php-build-deps \t\tautoconf \t\tg++ \t\tgcc \t\tgettext-dev
      \t\tlibxml2-dev \t\tlibxslt-dev \t\tmake \t\tmariadb-dev \t\topenssl-dev \t\tpcre-dev
      \t\treadline-dev && \tdocker-php-source extract && \tcd /usr/src/php && \texport
      CFLAGS=\"-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security
      -O2 -Wall -pedantic -fsigned-char -fno-strict-aliasing -g\" && \texport CPPFLAGS=\"-Wdate-time
      -D_FORTIFY_SOURCE=2\" && \texport CXXFLAGS=\"-g -O2 -fPIE -fstack-protector-strong
      -Wformat -Werror=format-security\" && \texport LDFLAGS=\"-Wl,-Bsymbolic-functions
      -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed\" && \t./configure $CONFIGURE_PARAMS
      \t\t--with-config-file-path=/etc/php/5.6/fpm \t\t--with-config-file-scan-dir=/etc/php/5.6/fpm/conf.d
      \t\t--disable-cli \t\t--disable-pcntl \t\t--enable-fpm \t\t--with-fpm-user=www-data
      \t\t--with-fpm-group=www-data && \tmake && \tmake install && \t./configure $CONFIGURE_PARAMS
      \t\t--with-config-file-path=/etc/php/5.6/cli \t\t--with-config-file-scan-dir=/etc/php/5.6/cli/conf.d
      \t\t--enable-pcntl \t\t--enable-cli && \tgrep -rl '5.6/fpm' . | sort -u | while
      read file; do sed -i -r -e 's!5.6/fpm!5.6/cli!g' ${file}; done && \tmake &&
      \tmake install && \tdocker-php-source delete && \tapk del php-build-deps"
    Name: run
    PrependShell: true
  - CmdLine:
    - "php -r 'copy(\"http://pear.php.net/install-pear-nozlib.phar\", \"/tmp/install-pear-nozlib.phar\");'
      && \tPHP_PEAR_SYSCONF_DIR=/etc/pear php -n -dshort_open_tag=0 -dopen_basedir=
      -derror_reporting=1803 -dmemory_limit=-1 -ddetect_unicode=0 -f /tmp/install-pear-nozlib.phar
      -- \t\t--dir /usr/share/php \t\t--bin $(dirname $(which php)) \t\t--config /usr/share/php/cfg
      \t\t--www /usr/share/php/www \t\t--php $(which php) \t\t--download /tmp/pear/download
      \t\t--temp /tmp/pear/temp \t\t--data /usr/share/php/data \t\t--doc /usr/share/php/docs
      \t\t--test /usr/share/php/tests \t\t--man /usr/share/man && \tsed -i -r -e \"s!PHP_SYSCONFDIR\\);!PHP_SYSCONFDIR
      . '/pear');!g\" /usr/share/php/PEAR/Config.php && \tsed -i \"$ s|\\-n||g\" /usr/bin/pecl
      && \trm /tmp/install-pear-nozlib.phar"
    Name: run
    PrependShell: true
  - Key: LOGFILES
    Name: arg
    Value: '"/var/log/php5.6-fpm.log"'
  - Env:
    - Key: LOGFILES
      Value: $LOGFILES
    Name: env
  - CmdLine:
    - "rm $LOGFILES || :; \tmkdir -p /run/php"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - usr/local
    - /usr/local
  - CmdLine:
    - /usr/local/bin/logged-stdout
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php-fpm
    - -F
    - -y/etc/php/5.6/fpm/php-fpm.conf
    - -c/etc/php/5.6/fpm/
    Name: cmd
    PrependShell: false
  From:
    Image: php:5.6-fpm-alpine3.4
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6-fpm-alpine3.4
