MetaArgs: null
Stages:
- BaseName: centos:6
  Commands:
  - Maintainer: Ryan Bauman <ryanbauman@gmail.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - redhawk.repo
    - /etc/yum.repos.d/
  - CmdLine:
    - yum update -y &&     yum install -y epel-release &&     yum install -y omniORB-servers                    omniEvents-server                    supervisor
      && yum clean all
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord.conf
    - /etc/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - omniORB.cfg
    - /etc/
  - CmdLine:
    - mkdir -p /var/log/omniEvents
    Name: run
    PrependShell: true
  - CmdLine:
    - chown omniORB /var/log/omniEvents
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "2809"
  - Name: expose
    Ports:
    - "11169"
  - CmdLine:
    - /usr/bin/supervisord
    - -n
    Name: cmd
    PrependShell: false
  From:
    Image: centos:6
  Name: ""
  Platform: ""
  SourceCode: FROM centos:6
