MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --update openssl openjdk8
    Name: run
    PrependShell: true
  - CmdLine:
    - wget "https://downloads.gradle.org/distributions/gradle-3.5-bin.zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip gradle-3.5-bin.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - rm gradle-3.5-bin.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - mv gradle-3.5 /gradle
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /gradle/bin/gradle /usr/bin/gradle
    Name: run
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
