MetaArgs: null
Stages:
- BaseName: centos:centos8
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"info@catapult.cx"'
    Name: label
  - Labels:
    - Key: org.label-schema.description
      Value: '"Base Centos 8 image"'
    Name: label
  - CmdLine:
    - yum update -y &&     yum install -y curl langpacks-en_GB &&     echo "alias
      ll='ls -h -l --color'" >> /etc/bashrc &&     echo "LANG=\"en_GB.UTF-8\"" > /etc/sysconfig/i18n
      &&     echo "LANG=en_GB.UTF-8" > /etc/locale.conf &&     rm -rf /tmp/* &&     yum
      clean all &&     rm -rf /var/cache/yum
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: centos:centos8
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos8
