MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Helmuth Angerer<helmut.angerer@googlemail.com>
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Simple and lightweight nzbget docker container, based on Alpine Linux."'
    - Key: Version
      Value: '"0.3"'
    Name: label
  - CmdLine:
    - mkdir /setup
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - setup/*
    - /setup/
  - CmdLine:
    - chmod -v +x /setup/*.sh && sh /setup/setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -r /setup/
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
    - /downloads
  - Name: expose
    Ports:
    - "6789"
  - Name: user
    User: nzbget
  - CmdLine:
    - /nzbget/nzbget
    - -s
    - -o
    - outputmode=log
    - -c
    - /config/nzbget.conf
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
