MetaArgs: null
Stages:
- BaseName: openjdk:8
  Commands:
  - CmdLine:
    - sed -i 's+http://security.ubuntu.com/+http://archive.ubuntu.com/+g' /etc/apt/sources.list  &&
      sed -i 's+http://archive.ubuntu.com/+http://us-east-1.ec2.archive.ubuntu.com/+g'
      /etc/apt/sources.list  && apt-get update  && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update  && apt-get install -y git ssh-client  && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update  && apt-get install -y tree gradle  && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: SDK_URL
      Value: '"https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip"'
    - Key: ANDROID_HOME
      Value: '"/usr/local/android-sdk"'
    - Key: ANDROID_VERSION
      Value: "26"
    - Key: ANDROID_BUILD_TOOLS_VERSION
      Value: 26.0.2
    Name: env
  - CmdLine:
    - mkdir "$ANDROID_HOME" .android  && cd "$ANDROID_HOME"  && curl -o sdk.zip $SDK_URL  &&
      unzip sdk.zip  && rm sdk.zip  && yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses  &&
      $ANDROID_HOME/tools/bin/sdkmanager --update  && $ANDROID_HOME/tools/bin/sdkmanager
      "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"     "platforms;android-${ANDROID_VERSION}"     "platform-tools"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /application
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /application
  From:
    Image: openjdk:8
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8
