MetaArgs: null
Stages:
- BaseName: php:7.1-fpm
  Commands:
  - Labels:
    - Key: vendor
      Value: '"Mautic"'
    Name: label
  - Labels:
    - Key: maintainer
      Value: '"Luiz Eduardo Oliveira Fonseca <luiz@powertic.com>"'
    Name: label
  - CmdLine:
    - set -ex;     apt-get update && apt-get install --no-install-recommends -y         cron         git         wget         sudo         libc-client-dev         libicu-dev         libkrb5-dev         libmcrypt-dev         libssl-dev         libz-dev         unzip         zip     ;     apt-get
      purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;     rm
      -rf /var/lib/apt/lists/*;     rm /etc/cron.daily/*;     docker-php-ext-configure
      imap --with-imap --with-imap-ssl --with-kerberos;     docker-php-ext-configure
      opcache --enable-opcache;     docker-php-ext-install         imap         intl         mbstring         mcrypt         mysqli         pdo_mysql         zip         opcache         bcmath     ;     docker-php-ext-enable         imap         intl         mbstring         mcrypt         mysqli         pdo_mysql         zip         opcache         bcmath     ;
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/www/html
  - Env:
    - Key: MAUTIC_VERSION
      Value: 2.15.3
    - Key: MAUTIC_SHA1
      Value: d6ec21376ceacd8bbb8d9ee58e81d8050a79c0b8
    - Key: MAUTIC_SRC_SHA1
      Value: e9d64733c55122a454ebe402ccb00d599b72b341
    - Key: MAUTIC_RUN_CRON_JOBS
      Value: "true"
    - Key: MAUTIC_DB_USER
      Value: root
    - Key: MAUTIC_DB_NAME
      Value: mautic
    - Key: PHP_INI_DATE_TIMEZONE
      Value: '''UTC'''
    - Key: PHP_MEMORY_LIMIT
      Value: 512M
    - Key: PHP_MAX_UPLOAD
      Value: 128M
    - Key: PHP_MAX_EXECUTION_TIME
      Value: "300"
    Name: env
  - CmdLine:
    - set -ex;     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
      --filename=composer;     curl -o mautic-src.zip -SL https://github.com/mautic/mautic/archive/${MAUTIC_VERSION}.zip;     echo
      "$MAUTIC_SRC_SHA1 *mautic-src.zip" | sha1sum -c -;     mkdir -p /usr/src/mautic-src;     unzip
      mautic-src.zip -d /usr/src/mautic-src;     rm mautic-src.zip;     chown -R www-data:www-data
      /usr/src/mautic-src;
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex;     curl -o mautic.zip -SL https://github.com/mautic/mautic/releases/download/${MAUTIC_VERSION}/${MAUTIC_VERSION}.zip;     echo
      "$MAUTIC_SHA1 *mautic.zip" | sha1sum -c -;     mkdir /usr/src/mautic;     unzip
      mautic.zip -d /usr/src/mautic;     rm mautic.zip;     chown -R www-data:www-data
      /usr/src/mautic;
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - makeconfig.php
    - makedb.php
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - mautic.crontab
    - /etc/cron.d/mautic
  - CmdLine:
    - chmod 644 /etc/cron.d/mautic
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod
    - +x
    - /entrypoint.sh
    Name: run
    PrependShell: false
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - php-fpm
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.1-fpm
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.1-fpm
