MetaArgs: null
Stages:
- BaseName: python:3
  Commands:
  - Name: workdir
    Path: /usr/local
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - AnnoMathTeX
  - Name: workdir
    Path: ./AnnoMathTeX
  - CmdLine:
    - python3 -m venv --system-site-packages env/ && . env/bin/activate
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ./usr/local/nltk_data
    Name: run
    PrependShell: true
  - CmdLine:
    - python -m nltk.downloader punkt
    Name: run
    PrependShell: true
  - CmdLine:
    - python -m nltk.downloader stopwords
    Name: run
    PrependShell: true
  - CmdLine:
    - python -m nltk.downloader averaged_perceptron_tagger
    Name: run
    PrependShell: true
  - CmdLine:
    - python3 annomathtex/manage.py migrate
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - python3
    - annomathtex/manage.py
    - runserver
    - 0.0.0.0:8000
    Name: cmd
    PrependShell: false
  From:
    Image: python:3
  Name: ""
  Platform: ""
  SourceCode: FROM python:3
