MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Brent Salisbury <brent.salisbury@gmail.com>
    Name: maintainer
  - CmdLine:
    - /usr/bin/telnet
    - nyancat.dakko.us
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
