MetaArgs: null
Stages:
- BaseName: mbeddr/mbeddr.build.docker
  Commands:
  - Maintainer: Sergej Koscejev <sergej@koscejev.cz>
    Name: maintainer
  - Env:
    - Key: ANDROID_TOOLS_VERSION_ID
      Value: "4333796"
    Name: env
  - Env:
    - Key: ANDROID_HOME
      Value: /opt/android
    Name: env
  - Env:
    - Key: ANDROID_NDK_VERSION
      Value: "19"
    Name: env
  - Env:
    - Key: ANDROID_NDK_HOME
      Value: /opt/android-ndk
    Name: env
  - CmdLine:
    - "curl --silent --show-error --output /tmp/tools.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_TOOLS_VERSION_ID}.zip
      && \tunzip -q /tmp/tools.zip -d ${ANDROID_HOME} && rm /tmp/tools.zip"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - licenses
    - ${ANDROID_HOME}/licenses
  - CmdLine:
    - "curl  --silent --show-error --output /tmp/ndk.zip https://dl.google.com/android/repository/android-ndk-r${ANDROID_NDK_VERSION}-linux-x86_64.zip
      && \tunzip -q /tmp/ndk.zip -d /tmp && mv /tmp/android-ndk-r${ANDROID_NDK_VERSION}
      ${ANDROID_NDK_HOME} && rm /tmp/ndk.zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y doxygen graphviz
    Name: run
    PrependShell: true
  From:
    Image: mbeddr/mbeddr.build.docker
  Name: ""
  Platform: ""
  SourceCode: FROM mbeddr/mbeddr.build.docker
