MetaArgs: null
Stages:
- BaseName: python:3.6
  Commands:
  - Env:
    - Key: FLASK_APP
      Value: app.py
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - app.py
    - gunicorn.py
    - requirements.txt
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - swap
    - swap
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - migrations
    - migrations
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - gunicorn
    - --config
    - gunicorn.py
    - app:app
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6
