MetaArgs: null
Stages:
- As: build
  BaseName: microsoft/dotnet:2.1-sdk
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.csproj'
    - ./Test/
  - Name: workdir
    Path: /app/Test
  - CmdLine:
    - dotnet restore
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./Test/
  - Name: workdir
    Path: /app/Test
  - CmdLine:
    - dotnet publish -c Release -o out
    Name: run
    PrependShell: true
  From:
    Image: microsoft/dotnet:2.1-sdk
  Name: build
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.1-sdk AS build
- As: runtime
  BaseName: microsoft/dotnet:2.1-aspnetcore-runtime
  Commands:
  - CmdLine:
    - apt-get
    - update
    Name: run
    PrependShell: false
  - CmdLine:
    - apt-get
    - install
    - -y
    - apt-file
    Name: run
    PrependShell: false
  - CmdLine:
    - apt-get
    - update
    Name: run
    PrependShell: false
  - CmdLine:
    - apt-get
    - install
    - -y
    - vim
    Name: run
    PrependShell: false
  - Name: workdir
    Path: /app
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /app/Test/out
    - ./
  - CmdLine:
    - dotnet
    - Test.dll
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "8080"
  - Env:
    - Key: ASPNETCORE_URLS
      Value: http://+:8080
    Name: env
  - Env:
    - Key: classname
      Value: $classname
    Name: env
  From:
    Image: microsoft/dotnet:2.1-aspnetcore-runtime
  Name: runtime
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
