MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - Env:
    - Key: LIBRARY_PATH
      Value: /lib:/usr/lib
    Name: env
  - CmdLine:
    - "apk add --update --no-cache \tbash \ttree \tgcc \tg++ \tmake \truby-dev \truby
      \tasciidoctor \tpython &&     gem install --no-ri --no-rdoc asciidoctor-pdf
      --pre &&     gem install --no-ri --no-rdoc coderay pygments.rb &&     gem cleanup
      &&     apk del     \tgcc     \tg++     \tmake     \truby-dev &&     rm -rf /tmp/*
      /var/cache/apk/* ~/.cache/pip"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /documents
  - Name: volume
    Volumes:
    - /documents
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
