MetaArgs: null
Stages:
- BaseName: chilio/laravel-dusk-ci:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y libpng-dev
    Name: run
    PrependShell: true
  From:
    Image: chilio/laravel-dusk-ci:latest
  Name: ""
  Platform: ""
  SourceCode: FROM chilio/laravel-dusk-ci:latest
