MetaArgs: null
Stages:
- BaseName: python:3.7.3-slim-stretch
  Commands:
  - CmdLine:
    - apt-get -y update     && apt-get -y upgrade     && apt-get clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /pyssher/build /pyssher/keys
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /pyssher/build/
  - CmdLine:
    - cd /pyssher/build     && python3 setup.py sdist     && cd dist     && pip install
      -U $(ls)      && rm -r /pyssher/build
    Name: run
    PrependShell: true
  - CmdLine:
    - pyssher
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:3.7.3-slim-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7.3-slim-stretch
