MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - CmdLine:
    - apk update &&     apk add ruby ruby-dev ruby-rake ruby-rdoc cmake bash openssh-client         libffi-dev
      build-base git zlib-dev icu-dev &&     gem install --no-ri --no-rdoc gollum
      github-markdown redcarpet &&     apk del build-base ruby-dev &&     rm -rf /root/src
      /tmp/* /usr/share/man /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /root/wikidata
    Name: run
    PrependShell: true
  - CmdLine:
    - git init /root/wikidata
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4567"
  - Name: workdir
    Path: /root/wikidata
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./init_wiki.sh
    - /root/
  - CmdLine:
    - chmod 777 /root/init_wiki.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./post-commit.sh
    - /root/wikidata/.git/hooks/post-commit
  - CmdLine:
    - chmod a+x /root/wikidata/.git/hooks/post-commit
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./config.rb
    - /root/config.rb
  - CmdLine:
    - /root/init_wiki.sh "$SUB_MODULE_NAME"
    Name: entrypoint
    PrependShell: true
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
