MetaArgs: null
Stages:
- BaseName: php:7.2-fpm-alpine
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Env:
    - Key: COMPOSER_ALLOW_SUPERUSER
      Value: "1"
    Name: env
  - Env:
    - Key: PHALCON_VERSION
      Value: 3.4.5
    Name: env
  - Env:
    - Key: PHALCON_EXT_PATH
      Value: php7/64bits
    Name: env
  - Labels:
    - Key: Maintainer
      Value: '"Tobias Sjösten <tobias.sjosten@stim.se>"'
    - Key: Description
      Value: '"PHP 7.2 image with batteries included"'
    - Key: org.label-schema.name
      Value: '"stimtech/builder-php"'
    - Key: org.label-schema.description
      Value: '"PHP 7.2 image with batteries included"'
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.vcs-url
      Value: '"https://bitbucket.org/stimtech/docker-builder-php"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.schema-version
      Value: '"1.0.0"'
    Name: label
  - Name: shell
    Shell:
    - /bin/ash
    - -eo
    - pipefail
    - -c
  - CmdLine:
    - set -ex     && apk update     && apk add --no-cache alpine-sdk=1.0-r0 autoconf=2.69-r2
      git=2.22.0-r0 icu-dev=64.2-r0 libpng-dev=1.6.37-r1     libxml2-dev=2.9.9-r2
      openssh-client=8.1_p1-r0     && pecl install xdebug ast     && docker-php-ext-enable
      xdebug ast     && curl -sSL "https://codeload.github.com/phalcon/cphalcon/tar.gz/v${PHALCON_VERSION}"
      | tar -xz     && docker-php-ext-install -j"$(nproc)" gd intl soap zip "${PWD}/cphalcon-${PHALCON_VERSION}/build/${PHALCON_EXT_PATH}"     &&
      rm -r "${PWD}/cphalcon-${PHALCON_VERSION}"     && curl -sS https://getcomposer.org/installer
      | php -- --install-dir=/usr/local/bin --filename=composer     && curl -sSo /usr/local/bin/phpcov
      https://phar.phpunit.de/phpcov.phar     && chmod +x /usr/local/bin/phpcov     &&
      apk del alpine-sdk autoconf     && rm -rf /tmp/*
    Name: run
    PrependShell: true
  From:
    Image: php:7.2-fpm-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2-fpm-alpine
