MetaArgs: null
Stages:
- As: builder
  BaseName: debian:stable
  Commands:
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive; apt-get update &&  apt-get install -y build-essential                        automake                        libtool                        autoconf                        git
      &&  git clone --depth 1 https://github.com/kmein/traadfri.git &&  git clone
      --depth 1 --recursive -b dtls https://github.com/home-assistant/libcoap.git
      &&  cd /libcoap &&  ./autogen.sh &&  ./configure --disable-documentation --disable-shared
      --without-debug CFLAGS="-D COAP_DEBUG_FD=stderr" &&  make
    Name: run
    PrependShell: true
  From:
    Image: debian:stable
  Name: builder
  Platform: ""
  SourceCode: FROM debian:stable AS builder
- BaseName: python:3.7-stretch
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /libcoap
    - /libcoap
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /traadfri
    - /traadfri
  - CmdLine:
    - cd traadfri &&  python3 setup.py install &&  cd /libcoap &&  make install
    Name: run
    PrependShell: true
  - CmdLine:
    - traadfri
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:3.7-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-stretch
