MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.16
  Commands:
  - Maintainer: Kevin Delfour <kevin@delfour.eu>
    Name: maintainer
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - CmdLine:
    - apt-get update && apt-get dist-upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -yq wget git unzip nginx fontconfig-config
      fonts-dejavu-core     php5-fpm php5-common php5-json php5-cli php5-common php5-mysql    php5-gd
      php5-json php5-mcrypt php5-readline php5-imagick psmisc ssl-cert     ufw php-pear
      libgd-tools libmcrypt-dev mcrypt mysql-client
    Name: run
    PrependShell: true
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - locale-gen cs_CZ.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen de_DE.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen es_ES.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen fr_FR.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen it_IT.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen pl_PL.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen pt_BR.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen ru_RU.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen sl_SI.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen uk_UA.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "cgi.fix_pathinfo = 0" >> /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s/output_buffering\s*=\s*4096/output_buffering = Off/g" /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 1G/g" /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 1G/g" /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s/max_execution_time\s*=\s*30/max_execution_time = 1000/g" /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s/memory_limit\s*=\s*128M/memory_limit = 1G/g" /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e "s:;\s*session.save_path\s*=\s*\"N;/path\":session.save_path = /tmp:g"
      /etc/php5/fpm/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - php5enmod mcrypt
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/www
    Name: run
    PrependShell: true
  - CmdLine:
    - chown www-data:www-data /var/www
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/nginx/sites-enabled/*
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/nginx/sites-available/*
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e"s/keepalive_timeout\s*65/keepalive_timeout 2/" /etc/nginx/nginx.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e"s/keepalive_timeout 2/keepalive_timeout 2;\n\tclient_max_body_size
      100m/" /etc/nginx/nginx.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "daemon off;" >> /etc/nginx/nginx.conf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/php.conf
    - /etc/nginx/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/lychee
    - /etc/nginx/sites-enabled/
  - Name: workdir
    Path: /var/www
  - CmdLine:
    - git clone https://github.com/electerious/Lychee.git lychee
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/lychee
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod -R 770 /var/www/lychee
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod -R 777 /var/www/lychee/uploads/
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod -R 777 /var/www/lychee/data/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/service/php5-fpm
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/php5-fpm.sh
    - /etc/service/php5-fpm/run
  - CmdLine:
    - chmod a+x /etc/service/php5-fpm/run
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/service/nginx
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/nginx.sh
    - /etc/service/nginx/run
  - CmdLine:
    - chmod a+x /etc/service/nginx/run
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: workdir
    Path: /
  - CmdLine:
    - ln -s /var/www/lychee/uploads uploads
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /var/www/lychee/data data
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /var/www/lychee/plugins plugins
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /uploads
  - Name: volume
    Volumes:
    - /data
  - Name: volume
    Volumes:
    - /plugins
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: phusion/baseimage:0.9.16
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.9.16
