MetaArgs: null
Stages:
- BaseName: jekyll/jekyll
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - skellyio-jekyll
    - /srv/jekyll
  From:
    Image: jekyll/jekyll
  Name: ""
  Platform: ""
  SourceCode: FROM jekyll/jekyll
