MetaArgs: null
Stages:
- BaseName: deanunnotech/django-image-sample:latest
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - django-admin startproject project .; exit 0
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 8000:8000
  - CmdLine:
    - supervisord -c supervisord.conf --nodaemon
    Name: cmd
    PrependShell: true
  From:
    Image: deanunnotech/django-image-sample:latest
  Name: ""
  Platform: ""
  SourceCode: FROM deanunnotech/django-image-sample:latest
