MetaArgs: null
Stages:
- BaseName: golang:1.6.2
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/dnsdock
  - Name: workdir
    Path: /go/src/github.com/dnsdock
  - CmdLine:
    - go get -v github.com/tools/godep
    Name: run
    PrependShell: true
  - CmdLine:
    - godep restore
    Name: run
    PrependShell: true
  - CmdLine:
    - bash -c 'go install -ldflags "-X main.version `git describe --tags HEAD``if
      [[ -n $(command git status --porcelain --untracked-files=no 2>/dev/null) ]];
      then echo "-dirty"; fi`"'
    Name: run
    PrependShell: true
  - CmdLine:
    - /go/bin/dnsdock
    Name: entrypoint
    PrependShell: false
  From:
    Image: golang:1.6.2
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.6.2
