MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: bibi21000 <bibi21000@gmail.com>
    Name: maintainer
  - Env:
    - Key: PYOZW_DOCKER
      Value: "1"
    Name: env
  - CmdLine:
    - apt-get update && apt-get dist-upgrade -y >/dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --no-install-recommends make sudo apt-utils >/dev/null
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /home/pyozw
  - Name: workdir
    Path: /home/pyozw
  - CmdLine:
    - make docker-deps >/dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - make openzwave.gzip >/dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - make venv-dev-autobuild-tests
    Name: run
    PrependShell: true
  - CmdLine:
    - make venv-pypilive-autobuild-tests
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
