MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: Stas Rudakou "stas@garage22.net"
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cobalt
    - /usr/bin/cobalt
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - /usr/bin/cobalt
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
