MetaArgs: null
Stages:
- BaseName: debian:stretch-slim
  Commands:
  - Maintainer: hy2900822@126.com
    Name: maintainer
  - Key: DEBIAN_FRONTEND
    Name: arg
    Value: noninteractive
  - Env:
    - Key: KIBANA_VERSION
      Value: 6.2.2
    - Key: KIBANA_PATH
      Value: /opt/kibana/
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - clean-apt
    - /usr/bin
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - clean-install
    - /usr/bin
  - CmdLine:
    - clean-install curl
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp     && mkdir -p ${KIBANA_PATH}     && curl -OLk "http://artifacts.elastic.co/downloads/kibana/kibana-${KIBANA_VERSION}-linux-x86_64.tar.gz"     &&
      tar -xzf kibana-${KIBANA_VERSION}-linux-x86_64.tar.gz     && mv kibana-${KIBANA_VERSION}-linux-x86_64/*
      ${KIBANA_PATH}     && rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/kibana/bin/kibana
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stretch-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stretch-slim
