MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - CmdLine:
    - "apk add --no-cache ruby ruby-rdoc ruby-irb \t && gem install mustache"
    Name: run
    PrependShell: true
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
