MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.13-alpine
  Commands:
  - Key: upx_params
    Name: arg
    Value: null
  - Env:
    - Key: upx_params
      Value: ${upx_params:--7}
    Name: env
  - CmdLine:
    - apk add --no-cache upx
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./src
    - /src
  - Name: workdir
    Path: /src
  - CmdLine:
    - set -x     && upx -V     && go version     && go build -ldflags='-s -w' -o /tmp/tinifier
      .     && upx ${upx_params} /tmp/tinifier     && /tmp/tinifier -V     && /tmp/tinifier
      -h
    Name: run
    PrependShell: true
  From:
    Image: golang:1.13-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.13-alpine as builder
- BaseName: alpine:latest
  Commands:
  - Labels:
    - Key: Description
      Value: '"Docker image with tinifier"'
    - Key: Vendor
      Value: '"Tarampampam"'
    Name: label
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /tmp/tinifier
    - /bin/tinifier
  - CmdLine:
    - /bin/tinifier
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
