MetaArgs: null
Stages:
- BaseName: node:latest
  Commands:
  - Env:
    - Key: NEXE_VERSION
      Value: 1.1.2
    Name: env
  - Env:
    - Key: NODEJS_VERSION
      Value: latest
    Name: env
  - Env:
    - Key: LDFLAGS
      Value: '"-static-libgcc -static-libstdc++"'
    Name: env
  - CmdLine:
    - npm install -g nexe@${NEXE_VERSION}
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/bin/nodejs /usr/bin/node
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - '"nexe"'
    Name: cmd
    PrependShell: true
  From:
    Image: node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM node:latest
