MetaArgs: null
Stages:
- BaseName: datmo/keras-theano:gpu
  Commands:
  - Maintainer: Dmitry Momot <mail@dmomot.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade nltk
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /workspace
  - CmdLine:
    - chmod -R a+w /workspace
    Name: run
    PrependShell: true
  From:
    Image: datmo/keras-theano:gpu
  Name: ""
  Platform: ""
  SourceCode: FROM datmo/keras-theano:gpu
