MetaArgs: null
Stages:
- BaseName: php:5.6-apache
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Leonardo Fernandez <lyonn19@gmail.com>"'
    Name: label
  - CmdLine:
    - "apt-get update \t&& apt-get install -y libmcrypt-dev \t\tlibjpeg62-turbo-dev
      \t\tlibpcre3-dev \t\tlibpng-dev \t\tlibfreetype6-dev \t\tlibxml2-dev \t\tlibicu-dev
      \t\tlibzip-dev \t\tmysql-client \t\twget \t\tunzip     && rm -rf /var/lib/apt/lists/*
      \    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      \    && docker-php-ext-install iconv intl pdo_mysql mbstring soap gd zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - "docker-php-source extract   && if [ -d \"/usr/src/php/ext/mysql\" ]; then docker-php-ext-install
      mysql; fi   && if [ -d \"/usr/src/php/ext/mcrypt\" ]; then docker-php-ext-install
      mcrypt; fi \t&& if [ -d \"/usr/src/php/ext/opcache\" ]; then docker-php-ext-install
      opcache; fi \t&& docker-php-source delete"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_files/php.ini
    - /usr/local/etc/php/
  From:
    Image: php:5.6-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6-apache
