MetaArgs: null
Stages:
- BaseName: fakereto/docker-phpnginx
  Commands:
  - CmdLine:
    - curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh"
      | bash  && apt-get update  && apt-get install -y php7.3-phalcon
    Name: run
    PrependShell: true
  From:
    Image: fakereto/docker-phpnginx
  Name: ""
  Platform: ""
  SourceCode: FROM fakereto/docker-phpnginx
