MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y &&     apt-get autoremove -y &&     apt-get
      install -y         nginx         curl         fail2ban         unzip         apache2-utils         mysql-client         iputils-ping         nano         software-properties-common         nginx-extras         &&     add-apt-repository
      ppa:certbot/certbot &&         apt-get update &&         apt-get install -y
      python-certbot-nginx         &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - '"nginx -g ''daemon off;''"'
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
