MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: xun "me@xun.my"
    Name: maintainer
  - CmdLine:
    - "apk --update add     python     py-pip     jq \t\tcoreutils \t\tgroff     curl
      \    bash     && pip install awscli     && curl -L \"https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl\"
      -o \"/usr/local/bin/kubectl\"     && chmod +x \"/usr/local/bin/kubectl\"     &&
      apk del py-pip     && rm -rf /var/cache/apk/*"
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
