MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Juan Luis Baptiste <juan.baptiste@gmail.com>
    Name: maintainer
  - Env:
    - Key: OTRS_VERSION
      Value: 6.0.24-01
    Name: env
  - Env:
    - Key: OTRS_ROOT
      Value: '"/opt/otrs/"'
    Name: env
  - Env:
    - Key: OTRS_BACKUP_DIR
      Value: '"/var/otrs/backups"'
    Name: env
  - Env:
    - Key: OTRS_CONFIG_DIR
      Value: '"${OTRS_ROOT}Kernel"'
    Name: env
  - Env:
    - Key: OTRS_CONFIG_MOUNT_DIR
      Value: '"/config/"'
    Name: env
  - Env:
    - Key: OTRS_SKINS_MOUNT_DIR
      Value: '"/skins/"'
    Name: env
  - Env:
    - Key: SKINS_PATH
      Value: '"${OTRS_ROOT}/var/httpd/htdocs/skins/"'
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - yum install -y yum-plugin-fastestmirror &&     yum install -y epel-release &&     yum
      update -y &&     yum -y install bzip2 cronie httpd mysql mod_perl     perl-core
      "perl(Crypt::SSLeay)" "perl(Net::LDAP)" "perl(URI)"     procmail "perl(Date::Format)"
      "perl(LWP::UserAgent)"     "perl(Net::DNS)" "perl(IO::Socket::SSL)" "perl(XML::Parser)"     "perl(Apache2::Reload)"
      "perl(Crypt::Eksblowfish::Bcrypt)"     "perl(Encode::HanExtra)" "perl(GD)" "perl(GD::Text)"
      "perl(GD::Graph)"     "perl(JSON::XS)" "perl(Mail::IMAPClient)" "perl(PDF::API2)"
      "perl(DateTime)"     "perl(Text::CSV_XS)" "perl(YAML::XS)" "perl(Text::CSV_XS)"
      "perl(DBD::mysql)"     rsyslog supervisor tar which &&     yum install -y http://ftp.otrs.org/pub/otrs/RPMS/rhel/7/otrs-${OTRS_VERSION}.noarch.rpm
      &&     /opt/otrs/bin/otrs.CheckModules.pl &&     yum clean all
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.sh'
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/supervisord.d/otrs.ini
    - /etc/supervisord.d/
  - CmdLine:
    - 'chmod 755 /*.sh  &&     cp ${OTRS_ROOT}/var/httpd/htdocs/index.html /var/www/html
      &&     chmod 644 /var/www/html/index.html &&     sed -i ''s/\bindex.html\b/&
      index.pl/'' /etc/httpd/conf/httpd.conf &&     echo "+ : otrs : cron crond" |cat
      >> /etc/security/access.conf                &&     sed -i -e ''/pam_loginuid.so/
      s/^#*/#/'' /etc/pam.d/crond                       &&     sed -i -e "s/^nodaemon=false/nodaemon=true/"
      /etc/supervisord.conf &&     cat /etc/supervisord.d/otrs.ini >> etc/supervisord.conf
      &&     sed -i -e ''/<ValidateModule>Kernel::System::SysConfig::StateValidate<\/ValidateModule>/
      s/^#*/#/''         ${OTRS_ROOT}Kernel/Config/Files/XML/Ticket.xml  &&     mkdir
      -p ${OTRS_ROOT}var/{run,tmp}/ &&     perl -cw ${OTRS_ROOT}bin/cgi-bin/index.pl
      &&     perl -cw ${OTRS_ROOT}bin/cgi-bin/customer.pl &&     perl -cw ${OTRS_ROOT}bin/otrs.Console.pl
      &&     sed -i -e ''/\$ModLoad imjournal/ s/^#*/#/'' /etc/rsyslog.conf &&     sed
      -i -e ''/\$IMJournalStateFile imjournal.state/ s/^#*/#/'' /etc/rsyslog.conf
      &&     sed -i ''s/\(^\$OmitLocalLogging \).*/\1off/'' /etc/rsyslog.conf &&     rm
      /etc/rsyslog.d/listen.conf'
    Name: run
    PrependShell: true
  - CmdLine:
    - mv ${OTRS_CONFIG_DIR} / &&     mv ${SKINS_PATH} / &&     touch ${OTRS_ROOT}var/tmp/firsttime
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
