MetaArgs: null
Stages:
- As: builder
  BaseName: golang:alpine
  Commands:
  - Name: workdir
    Path: /build
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go build -o absol -v github.com/lordralex/absol/core
    Name: run
    PrependShell: true
  From:
    Image: golang:alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:alpine AS builder
- BaseName: alpine
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /build/absol
    - /go/bin/absol
  - CmdLine:
    - /go/bin/absol
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - alert
    - cleaner
    - factoids
    - log
    - twitch
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
