MetaArgs: null
Stages:
- BaseName: nvidia/cuda:9.0-cudnn7-runtime
  Commands:
  - CmdLine:
    - apt update &&   apt install -y  python3-dev python3-pip  && pip3 --no-cache-dir
      install tensorflow-gpu keras && apt clean all
    Name: run
    PrependShell: true
  From:
    Image: nvidia/cuda:9.0-cudnn7-runtime
  Name: ""
  Platform: ""
  SourceCode: from nvidia/cuda:9.0-cudnn7-runtime
