MetaArgs: null
Stages:
- As: release
  BaseName: alpine:3.8
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: '""'
  - Key: VCS_REF
    Name: arg
    Value: '""'
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/sevenval/dockerfiles.git"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.schema-version
      Value: '"1.0.0-rc1"'
    Name: label
  - Key: SLOPPY_CLI_VERSION
    Name: arg
    Value: v1.12.0
  - Env:
    - Key: SLOPPY_CLI_VERSION
      Value: ${SLOPPY_CLI_VERSION}
    Name: env
  - Env:
    - Key: SLOPPY_APITOKEN
      Value: '""'
    Name: env
  - Name: workdir
    Path: /work
  - CmdLine:
    - apk add --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/sloppyio/cli/releases/download/${SLOPPY_CLI_VERSION}/sloppy-linux-amd64
    - /bin/sloppy
  - CmdLine:
    - chmod +x /bin/sloppy &&     mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1
      /lib64/ld-linux-x86-64.so.2
    Name: run
    PrependShell: true
  - CmdLine:
    - sloppy version
    Name: run
    PrependShell: true
  - CmdLine:
    - sloppy
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - version
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: release
  Platform: ""
  SourceCode: FROM alpine:3.8 as release
