MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get -y install curl
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://ftp.debian.org/debian jessie-backports main" | tee -a /etc/apt/sources.list.d/jessie-backports.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install gunicorn
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install python-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install Flask
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install cron
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/crontab
    - /app/crontab
  - CmdLine:
    - crontab /app/crontab
    Name: run
    PrependShell: true
  - Env:
    - Key: PROJECT_HOME
      Value: /Preco
    Name: env
  - CmdLine:
    - mkdir /Preco
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /Preco/src
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /Preco/data
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - /Preco/src/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data
    - /Preco/data/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - README.md
    - /Preco/
  - CmdLine:
    - chmod u+x /Preco/src/main/script/autostart.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install snowplow-tracker
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install requests==2.6.0
    Name: run
    PrependShell: true
  - CmdLine:
    - /Preco/src/main/script/autostart.sh
    Name: entrypoint
    PrependShell: false
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Key: VERSION
    Name: arg
    Value: null
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.name
      Value: '"snowplow-webhook"'
    - Key: org.label-schema.description
      Value: '"Webhook based on python tracker"'
    - Key: org.label-schema.url
      Value: '"http://kolibero.eu"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/goliasz/snowplow-webhook"'
    - Key: org.label-schema.vendor
      Value: '"KOLIBERO"'
    - Key: org.label-schema.version
      Value: $VERSION
    - Key: org.label-schema.schema-version
      Value: '"1.0"'
    Name: label
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
