MetaArgs: null
Stages:
- BaseName: uniqrn/node:12
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"unicorn research Ltd"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /root/npm/package.json
  - Name: workdir
    Path: /root/npm
  - CmdLine:
    - npm install     && ln -s /root/npm/node_modules /node_modules
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - Env:
    - Key: PATH
      Value: /root/npm/node_modules/.bin:$PATH
    Name: env
  - Env:
    - Key: NODE_PATH
      Value: /root/npm/node_modules
    Name: env
  From:
    Image: uniqrn/node:12
  Name: ""
  Platform: ""
  SourceCode: FROM uniqrn/node:12
