MetaArgs: null
Stages:
- BaseName: ubuntu:18.10
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt upgrade -y && apt clean
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y git curl xz-utils && apt clean
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root
  - CmdLine:
    - curl https://download.qemu.org/qemu-3.1.0.tar.xz | tar -xJ
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://busybox.net/downloads/busybox-1.29.2.tar.bz2 | tar -xj
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth=1 https://github.com/riscv/riscv-gnu-toolchain
    Name: run
    PrependShell: true
  - CmdLine:
    - cd riscv-gnu-toolchain && git submodule update --init --recursive --depth=1
      riscv-binutils
    Name: run
    PrependShell: true
  - CmdLine:
    - cd riscv-gnu-toolchain && git submodule update --init --recursive --depth=1
      riscv-gcc
    Name: run
    PrependShell: true
  - CmdLine:
    - cd riscv-gnu-toolchain && git submodule update --init --recursive --depth=1
      riscv-gdb
    Name: run
    PrependShell: true
  - CmdLine:
    - cd riscv-gnu-toolchain && git submodule update --init --recursive --depth=1000
      riscv-glibc
    Name: run
    PrependShell: true
  - CmdLine:
    - cd riscv-gnu-toolchain && git submodule update --init --recursive --depth=1000
      riscv-newlib
    Name: run
    PrependShell: true
  - CmdLine:
    - cd riscv-gnu-toolchain && git submodule update --init --recursive riscv-qemu
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/torvalds/linux.git && cd linux && git checkout
      v4.20
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth=1 https://github.com/riscv/riscv-fesvr.git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth=1 https://github.com/riscv/riscv-isa-sim.git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth=1 https://github.com/riscv/riscv-pk.git
    Name: run
    PrependShell: true
  - Env:
    - Key: RISCV
      Value: /usr/local
    Name: env
  - Env:
    - Key: PATH
      Value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    Name: env
  From:
    Image: ubuntu:18.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.10
