MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - mkdir -p /Frontend/web
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /Frontend/web/package.json
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bower.json
    - /Frontend/web/bower.json
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs nodejs-legacy
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y npm
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nginx
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g bower
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g gulp
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /Frontend/web && ls && npm install && bower install --allow-root && cd ~
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
