MetaArgs: null
Stages:
- BaseName: josedeng/jdk:jdk-1.8.0_162
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start.sh
    - /start.sh
  - Env:
    - Key: GRADLE_VERSION
      Value: gradle-4.6
    Name: env
  - CmdLine:
    - dos2unix /start.sh &&     chmod a+x /start.sh &&     apt-get -q update &&     apt-get
      -q -y install wget unzip libaio1 &&     wget -q -O /tmp/installer.tar.gz          --no-check-certificate          --no-cookies          https://services.gradle.org/distributions/${GRADLE_VERSION}-all.zip
      &&     unzip /tmp/installer.tar.gz -d /opt &&     chown -R developer:developer
      /opt/$GRADLE_VERSION &&     apt-get autoremove wget unzip --purge -y &&     rm
      -rf /var/lib/apt/lists/* &&     rm -rf /tmp/*
    Name: run
    PrependShell: true
  - Name: user
    User: developer
  - Name: volume
    Volumes:
    - /opt/$GRADLE_VERSION
  - CmdLine:
    - /start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: josedeng/jdk:jdk-1.8.0_162
  Name: ""
  Platform: ""
  SourceCode: FROM josedeng/jdk:jdk-1.8.0_162
