MetaArgs: null
Stages:
- BaseName: python:3.6-slim
  Commands:
  - Maintainer: Agriness
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y curl zip python3-dev build-essential python3-dev
      python3-pip python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0
      libffi-dev shared-mime-info jq libltdl7 git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - curl --insecure -OL https://github.com/SonarSource/sonar-scanner-cli/archive/3.2.0.1227.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip 3.2.0.1227.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - rm 3.2.0.1227.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install boto3 botocore awscli
    Name: run
    PrependShell: true
  From:
    Image: python:3.6-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-slim
