MetaArgs: null
Stages:
- BaseName: nvidia/cuda:9.0-devel-ubuntu16.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Unsalted"'
    Name: label
  - Key: DEBIAN_FRONTEND
    Name: arg
    Value: noninteractive
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends   ca-certificates   wget   g++   git   cuda-core-$CUDA_PKG_VERSION   cuda-misc-headers-$CUDA_PKG_VERSION   cuda-command-line-tools-$CUDA_PKG_VERSION   cuda-driver-dev-$CUDA_PKG_VERSION   &&
      rm -rf /var/lib/apt/lists/*   && apt-get clean -y
    Name: run
    PrependShell: true
  - Env:
    - Key: LIBRARY_PATH
      Value: /usr/local/cuda/lib64/stubs:${LIBRARY_PATH}
    Name: env
  - Name: workdir
    Path: /tmp
  - Key: boost_version
    Name: arg
    Value: 1.62.0
  - Key: boost_dir
    Name: arg
    Value: boost_1_62_0
  - Key: boost_sha256_sum
    Name: arg
    Value: 440a59f8bc4023dbe6285c9998b0f7fa288468b889746b1ef00e8b36c559dce1
  - Env:
    - Key: boost_version
      Value: ${boost_version}
    Name: env
  - Key: boost_libs
    Name: arg
    Value: '"   --with-atomic   --with-chrono   --with-date_time   --with-filesystem   --with-log   --with-regex   --with-system   --with-thread"'
  - CmdLine:
    - wget http://downloads.sourceforge.net/project/boost/boost/${boost_version}/${boost_dir}.tar.gz   &&
      echo "${boost_sha256_sum}  ${boost_dir}.tar.gz" | sha256sum -c   && tar xfz
      ${boost_dir}.tar.gz   && rm ${boost_dir}.tar.gz   && cd ${boost_dir}   && ./bootstrap.sh
      --prefix=/usr   && ./b2 -j 4 stage $boost_libs   && ./b2 -j 4 install $boost_libs   &&
      cd .. && rm -rf ${boost_dir} && ldconfig
    Name: run
    PrependShell: true
  - CmdLine:
    - wget   https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz   https://cmake.org/files/v3.7/cmake-3.7.2-SHA-256.txt   https://cmake.org/files/v3.7/cmake-3.7.2-SHA-256.txt.asc   &&
      gpg --keyserver pgp.mit.edu --recv 7BFB4EDA   && gpg --verbose --verify cmake-3.7.2-SHA-256.txt.asc
      cmake-3.7.2-SHA-256.txt   && grep cmake-3.7.2.tar.gz cmake-3.7.2-SHA-256.txt
      | sha256sum --check   && tar xzvf cmake-3.7.2.tar.gz   && cd cmake-3.7.2/   &&
      ./bootstrap   && make -j4   && make install   && cd ../
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/nicehash/nheqminer.git   && chmod +x nheqminer/cpu_xenoncat/asm_linux/*   &&
      cd nheqminer/cpu_xenoncat/asm_linux   && sh assemble.sh   && cd /tmp   && mkdir
      build/   && cd build/   && cmake ../nheqminer   && make -j $(nproc)   && cp
      ./nheqminer /usr/local/bin/nheqminer   && chmod +x /usr/local/bin/nheqminer
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash nheqminer
    Name: run
    PrependShell: true
  - Name: user
    User: nheqminer
  - Name: workdir
    Path: /home/nheqminer
  - CmdLine:
    - /usr/local/bin/nheqminer
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -h
    Name: cmd
    PrependShell: false
  From:
    Image: nvidia/cuda:9.0-devel-ubuntu16.04
  Name: ""
  Platform: ""
  SourceCode: FROM nvidia/cuda:9.0-devel-ubuntu16.04
