MetaArgs:
- DefaultValue: 3.5.1
  Key: R_VERSION
  ProvidedValue: null
  Value: 3.5.1
- DefaultValue: rocker/shiny-verse:${R_VERSION}
  Key: BASE_IMAGE
  ProvidedValue: null
  Value: rocker/shiny-verse:${R_VERSION}
Stages:
- BaseName: ${BASE_IMAGE}
  Commands:
  - Key: BASE_IMAGE
    Name: arg
    Value: null
  - Key: BASE_R_LIBS
    Name: arg
    Value: null
  - Env:
    - Key: BASE_R_LIBS
      Value: '"${BASE_R_LIBS:-caTools datasets dplyr devtools formatR remotes rmarkdown
        selectr shiny tidyverse}"'
    Name: env
  - CmdLine:
    - 'echo "Using BASE_IMAGE=''${BASE_IMAGE}'' with pre-installed R-libs: ${BASE_R_LIBS}"'
    Name: run
    PrependShell: true
  - Env:
    - Key: SCRIPT_DIR
      Value: '"/srv/scripts"'
    Name: env
  - CmdLine:
    - mkdir -p "${SCRIPT_DIR}"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./scripts/*.sh
    - '"${SCRIPT_DIR}/"'
  - CmdLine:
    - chmod 755 "${SCRIPT_DIR}"/*.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: SHINY_APPS_DIR
      Value: '"/srv/shiny-server"'
    Name: env
  - Env:
    - Key: SHINY_THEME_DIR
      Value: '"${SHINY_APPS_DIR}/www"'
    Name: env
  - Env:
    - Key: SHINY_BOOKMARKS_DIR
      Value: '"/var/lib/shiny-server/bookmarks"'
    Name: env
  - Env:
    - Key: SHINY_LOGS_DIR
      Value: '"/var/log/shiny-server"'
    Name: env
  - Env:
    - Key: SHINY_USER
      Value: '"shiny"'
    Name: env
  - Expression: ARG SHINY_APP_SRC
    Name: onbuild
  - Expression: ENV SHINY_APP_SRC="${SHINY_APP_SRC:-.}"
    Name: onbuild
  - Expression: ARG SHINY_THEME_SRC
    Name: onbuild
  - Expression: ENV SHINY_THEME_SRC="${SHINY_THEME_SRC:-$SHINY_APP_SRC/www}"
    Name: onbuild
  - Expression: ARG SHINY_ENV_VARS
    Name: onbuild
  - Expression: ENV SHINY_ENV_VARS="${SHINY_ENV_VARS:-}"
    Name: onbuild
  - Expression: ARG GITHUB_R_LIBS
    Name: onbuild
  - Expression: ENV GITHUB_R_LIBS="${GITHUB_R_LIBS:-}"
    Name: onbuild
  - Expression: RUN echo "SHINY_APP_SRC='${SHINY_APP_SRC}'"
    Name: onbuild
  - Expression: COPY "${SHINY_APP_SRC}/" "${SHINY_APPS_DIR}/"
    Name: onbuild
  - Expression: RUN R_LIBS_INSTALLED="${BASE_R_LIBS}"             R_LIBS_GITHUB="${GITHUB_R_LIBS}"             "${SCRIPT_DIR}/install-r-libs.sh"
      "${SHINY_APPS_DIR}"
    Name: onbuild
  - Expression: RUN echo "SHINY_THEME_SRC='${SHINY_THEME_SRC}'"
    Name: onbuild
  - Expression: COPY "${SHINY_THEME_SRC}/" "${SHINY_THEME_DIR}/"
    Name: onbuild
  - CmdLine:
    - /srv/scripts/init-r-env.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - su
    - '-'
    - shiny
    - -c
    - /usr/bin/shiny-server.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ${BASE_IMAGE}
  Name: ""
  Platform: ""
  SourceCode: FROM ${BASE_IMAGE}
