MetaArgs: null
Stages:
- BaseName: homeassistant/home-assistant:latest
  Commands:
  - Maintainer: Henrik Nicolaisen <henrik@nicolaisen.co>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y jq nmap lsof apt-transport-https netcat
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - bash nodesource_setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install ps4-waker@1.1.1 -g
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --fix-missing     build-essential     cmake     gfortran     git     wget     curl     graphicsmagick     libgraphicsmagick1-dev     libatlas-dev     libavcodec-dev     libavformat-dev     libboost-all-dev     libgtk2.0-dev     libjpeg-dev     liblapack-dev     libswscale-dev     pkg-config     python3-dev     python3-numpy     software-properties-common     zip     &&
      apt-get clean && rm -rf /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ~ &&     mkdir -p dlib &&     git clone -b 'v19.4' --single-branch https://github.com/davisking/dlib.git
      dlib/ &&     cd  dlib/ &&     python3 setup.py install --yes
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 8123:8123
  From:
    Image: homeassistant/home-assistant:latest
  Name: ""
  Platform: ""
  SourceCode: FROM homeassistant/home-assistant:latest
