MetaArgs: null
Stages:
- BaseName: duffqiu/dockerjdk7:latest
  Commands:
  - Maintainer: duffqiu@gmail.com
    Name: maintainer
  - CmdLine:
    - rpm --import http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y  update
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install cppunit git gcc ant
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install python-setuptools
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install automake pkgconfig libtool
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install hostname make pcre-devel openssl openssl-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install net-snmp net-snmp-utils net-snmp-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -u install bzip2
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -u install pacemaker
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /workspace
  - Name: volume
    Volumes:
    - /workspace
  - CmdLine:
    - /bin/bash
    - -c
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: duffqiu/dockerjdk7:latest
  Name: ""
  Platform: ""
  SourceCode: FROM duffqiu/dockerjdk7:latest
