MetaArgs: null
Stages:
- BaseName: fluent/fluentd:v1.7-debian
  Commands:
  - Maintainer: devops@broadinstitute.org
    Name: maintainer
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - /Gemfile
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Dockerfile
    - /Dockerfile
  - CmdLine:
    - apt-get update  && buildDeps="       make gcc g++ libc-dev       wget bzip2
      gnupg dirmngr     "  && apt-get install -y --no-install-recommends $buildDeps  &&
      gem install --file /Gemfile  && gem sources --clear-all  && apt-get purge -y
      --auto-remove                   -o APT::AutoRemove::RecommendsImportant=false                   $buildDeps  &&
      rm -rf /var/lib/apt/lists/*  && rm -rf /home/fluent/.gem/ruby/2.5.0/cache/*.gem
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - fluent.conf
    - /fluentd/etc/fluent.conf
  From:
    Image: fluent/fluentd:v1.7-debian
  Name: ""
  Platform: ""
  SourceCode: FROM fluent/fluentd:v1.7-debian
