MetaArgs: null
Stages:
- BaseName: softwareperonista/archlinux-mingw-w64:latest
  Commands:
  - Maintainer: tarmaciltur
    Name: maintainer
  - CmdLine:
    - pacman -Syu --noconfirm --noprogressbar
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -Syu --noconfirm --noprogressbar gtk3 mingw-w64-gtk3
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -Scc --noconfirm
    Name: run
    PrependShell: true
  From:
    Image: softwareperonista/archlinux-mingw-w64:latest
  Name: ""
  Platform: ""
  SourceCode: FROM softwareperonista/archlinux-mingw-w64:latest
