MetaArgs: null
Stages:
- BaseName: wnameless/oracle-xe-11g
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - echo.sh
    - /docker-entrypoint-initdb.d/
  From:
    Image: wnameless/oracle-xe-11g
  Name: ""
  Platform: ""
  SourceCode: FROM wnameless/oracle-xe-11g
