MetaArgs: null
Stages:
- BaseName: node:4-onbuild
  Commands:
  - Name: expose
    Ports:
    - "4200"
  - CmdLine:
    - apt-get -y update &&     apt-get -y install graphicsmagick &&     mkdir -p images/screenshots
      &&     mkdir -p images/thumbs &&     mkdir -p sources &&     npm install -g
      bower &&     bower --allow-root install
    Name: run
    PrependShell: true
  From:
    Image: node:4-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM node:4-onbuild
