MetaArgs: null
Stages:
- BaseName: python:2.7
  Commands:
  - CmdLine:
    - "apt-get update \t\t&& apt-get install -y tcsh lib32z1 \t\t&& rm -rf /var/lib/apt/lists/"
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install hashlib
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install sqlalchemy Flask-API mysql-python
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - cd /home && curl http://www.compbio.dundee.ac.uk/jpred3/legacy/jnet/download/jnet.linux.tar.gz
      |  tar xz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - models
    - /app/models
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.py'
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - library.py
    - /app/
  - CmdLine:
    - chmod +x *.py
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - runSingleJnet.sh
    - /home/jnet/jnet.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.py
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - library.py
    - /app/
  - CmdLine:
    - chmod +x /home/jnet/jnet.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /app/*.py
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /home/jnet/output
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "latest" >> /home/jnet/VERSION
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
    - "80"
  - Env:
    - Key: FLASK_APP
      Value: run.py
    Name: env
  - CmdLine:
    - flask
    - run
    - --host=0.0.0.0
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:2.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7
