MetaArgs: null
Stages:
- BaseName: tjanczuk/edgejs:6.5.1
  Commands:
  - Maintainer: Michael Lawrence <mlawrence@aurlaw.com>
    Name: maintainer
  - Key: OPENCV_VERSION
    Name: arg
    Value: null
  - Env:
    - Key: OPENCV_VERSION
      Value: ${OPENCV_VERSION:-2.4.13}
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends     git     unzip     cmake     libv4l-dev     opencl-headers       &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local
  - CmdLine:
    - curl -SLO "https://github.com/Itseez/opencv/archive/${OPENCV_VERSION}.zip"   &&
      unzip ${OPENCV_VERSION}.zip   && mv /usr/local/opencv-${OPENCV_VERSION} /usr/local/opencv   &&
      rm ${OPENCV_VERSION}.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /usr/local/opencv/build
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/opencv/build
  - CmdLine:
    - cmake -D CMAKE_BUILD_TYPE=RELEASE       -D BUILD_PYTHON_SUPPORT=ON       -D
      CMAKE_INSTALL_PREFIX=/usr/local       -D WITH_OPENGL=ON       -D WITH_TBB=OFF       -D
      BUILD_EXAMPLES=ON       -D BUILD_NEW_PYTHON_SUPPORT=ON       -D WITH_V4L=ON       -D
      WITH_OPENCL=ON       ..
    Name: run
    PrependShell: true
  - CmdLine:
    - make -j7
    Name: run
    PrependShell: true
  - CmdLine:
    - make install
    Name: run
    PrependShell: true
  From:
    Image: tjanczuk/edgejs:6.5.1
  Name: ""
  Platform: ""
  SourceCode: FROM tjanczuk/edgejs:6.5.1
