MetaArgs: null
Stages:
- BaseName: gcr.io/istio-release/pilot:1.0.0
  Commands:
  - Maintainer: libertinus
    Name: maintainer
  From:
    Image: gcr.io/istio-release/pilot:1.0.0
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/istio-release/pilot:1.0.0
