MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: Roman Tarnavski
    Name: maintainer
  - CmdLine:
    - apk add --update nginx
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./dist/
    - /usr/share/nginx/html
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - nginx -g 'daemon off;'
    Name: cmd
    PrependShell: true
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
