MetaArgs: null
Stages:
- BaseName: openjdk:8-jdk
  Commands:
  - Maintainer: imtianx "imtianx@gmail.com"
    Name: maintainer
  - Key: SDK_TOOLS_VERSION
    Name: arg
    Value: "4333796"
  - Key: COMPILE_SDK_VERSION
    Name: arg
    Value: "28"
  - Key: BUILD_TOOLS_VERSION
    Name: arg
    Value: 28.0.3
  - Name: workdir
    Path: /workspace_android
  - Env:
    - Key: ANDROID_HOME
      Value: /workspace_android/sdk
    Name: env
  - CmdLine:
    - mkdir  sdk &&     wget http://dl.google.com/android/repository/sdk-tools-linux-${SDK_TOOLS_VERSION}.zip
      &&     unzip -qd sdk sdk-tools-linux-${SDK_TOOLS_VERSION}.zip &&     rm -f sdk-tools-linux-${SDK_TOOLS_VERSION}.zip
      &&     (yes | ./sdk/tools/bin/sdkmanager --no_https --update) &&     (yes |
      ./sdk/tools/bin/sdkmanager --no_https "build-tools;${BUILD_TOOLS_VERSION}")
      &&     (yes | ./sdk/tools/bin/sdkmanager --no_https "platform-tools") &&     (yes
      | ./sdk/tools/bin/sdkmanager --no_https "platforms;android-${COMPILE_SDK_VERSION}")
      &&     (yes | ./sdk/tools/bin/sdkmanager --no_https "extras;google;m2repository")
      &&     (yes | ./sdk/tools/bin/sdkmanager --no_https "extras;android;m2repository")
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -y && apt-get install -y bash git openssh-client &&     rm -rf
      /var/lib/apt/lists/* &&     echo "android builder install completed!"
    Name: run
    PrependShell: true
  From:
    Image: openjdk:8-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jdk
