MetaArgs: null
Stages:
- BaseName: node:8.1-slim
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /tmp/app-dev/package.json
  - CmdLine:
    - cd /tmp/app-dev && npm install --only=dev
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /tmp/app && cp /tmp/app-dev/package.json /tmp/app/ &&   cd /tmp/app &&
      npm install --only=production
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./src
    - /tmp/app-dev/src
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./.babelrc
    - /tmp/app-dev/.babelrc
  - CmdLine:
    - /tmp/app-dev/node_modules/.bin/babel /tmp/app-dev/src/ -d /tmp/app/dist --copy-files
      --ignore public/ &&   cp -r /tmp/app-dev/src/endpoints/directory_gui/public
      /tmp/app/dist/endpoints/directory_gui &&   rm /tmp/app/package-lock.json
    Name: run
    PrependShell: true
  From:
    Image: node:8.1-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.1-slim
- BaseName: node:8.1-slim
  Commands:
  - Name: expose
    Ports:
    - "3000"
    - "4000"
  - Name: workdir
    Path: /opt/app
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: warn
    Name: env
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /tmp/app/
    - /opt/app
  - CmdLine:
    - npm start
    Name: cmd
    PrependShell: true
  From:
    Image: node:8.1-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.1-slim
