MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - apt update && apt install -y backupninja ssh rdiff rdiff-backup mysql-client
      && apt clean
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/entrypoint.sh
    - /usr/local/bin/entrypoint.sh
  - Name: volume
    Volumes:
    - /etc/backup.d
  - CmdLine:
    - /usr/local/bin/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /usr/sbin/backupninja
    - -d
    - -n
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
