MetaArgs: null
Stages:
- BaseName: mongo
  Commands:
  - Name: workdir
    Path: /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./replicate.js
    - /replicate.js
  - CmdLine:
    - mongod
    - --replSet
    - rs0
    - --bind_ip_all
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "27017"
  From:
    Image: mongo
  Name: ""
  Platform: ""
  SourceCode: FROM mongo
