MetaArgs: null
Stages:
- BaseName: node:latest
  Commands:
  - CmdLine:
    - npm install turf-cli -g
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - Name: volume
    Volumes:
    - /data
  - Name: user
    User: nobody
  - CmdLine:
    - turf -help
    Name: cmd
    PrependShell: true
  From:
    Image: node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM node:latest
