MetaArgs: null
Stages:
- BaseName: php:7
  Commands:
  - CmdLine:
    - apt-get update -y   && apt-get install -y   openssl   zip   unzip   git   mysql-client   &&
      docker-php-ext-install pdo_mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php -- --quiet
    Name: run
    PrependShell: true
  - CmdLine:
    - mv composer.phar /usr/local/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo mbstring
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/api
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - composer.json
    - /usr/src/api
  - CmdLine:
    - composer update --no-scripts --no-autoloader
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .env.example
    - .env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/api
  - CmdLine:
    - composer dump-autoload --optimize
    Name: run
    PrependShell: true
  - CmdLine:
    - php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"
    Name: run
    PrependShell: true
  - CmdLine:
    - php artisan key:generate
    Name: run
    PrependShell: true
  - CmdLine:
    - php artisan jwt:secret
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - php artisan serve --host=0.0.0.0 --port=8080
    Name: cmd
    PrependShell: true
  From:
    Image: php:7
  Name: ""
  Platform: ""
  SourceCode: FROM php:7
