MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/hyperkube-amd64:v1.13.3
  Commands: null
  From:
    Image: gcr.io/google_containers/hyperkube-amd64:v1.13.3
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/hyperkube-amd64:v1.13.3
