MetaArgs: null
Stages:
- As: builder
  BaseName: node:9-alpine
  Commands:
  - Key: env
    Name: arg
    Value: production
  - Key: config
    Name: arg
    Value: /config/landing-page.config.json
  - Env:
    - Key: CONFIG
      Value: $config_uri
    Name: env
  - Name: workdir
    Path: /tmp
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - yarn.lock
    - /tmp/
  - CmdLine:
    - yarn install --pure-lockfile
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /opt/app/
  - CmdLine:
    - cp -a /tmp/node_modules /opt/app/
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn run build:$env
    Name: run
    PrependShell: true
  From:
    Image: node:9-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM node:9-alpine as builder
- BaseName: nginx:alpine
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /opt/app/public
    - /usr/share/nginx/html/
  - Name: expose
    Ports:
    - "80"
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
