MetaArgs: null
Stages:
- BaseName: jrottenberg/ffmpeg:3.4
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y git gcc make build-essential &&     git
      clone https://github.com/gpac/gpac.git &&     cd gpac &&     git checkout v0.7.1
      &&     ./configure --static-mp4box --use-zlib=no &&     make -j4 &&     make
      install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./scripts/
    - /scripts/
  - CmdLine:
    - /bin/bash
    Name: entrypoint
    PrependShell: false
  From:
    Image: jrottenberg/ffmpeg:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM jrottenberg/ffmpeg:3.4
