MetaArgs: null
Stages:
- BaseName: postgres:9.4
  Commands:
  - Maintainer: Karsten Westra <karstenwestra@gmail.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - options/auth_all.sh
    - /docker-entrypoint-initdb.d/auth_all.sh
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y postgresql-contrib                         postgis                         postgresql-9.4-postgis-2.1
    Name: run
    PrependShell: true
  From:
    Image: postgres:9.4
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.4
