MetaArgs: null
Stages:
- As: build
  BaseName: kbase/kb_jre:latest
  Commands:
  - CmdLine:
    - apt-get -y update && apt-get -y install ant git openjdk-8-jdk
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&     git clone https://github.com/kbase/jars
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /tmp/user_profile
  - CmdLine:
    - cd /tmp/user_profile &&     ant compile &&     ant buildwar
    Name: run
    PrependShell: true
  From:
    Image: kbase/kb_jre:latest
  Name: build
  Platform: ""
  SourceCode: FROM kbase/kb_jre:latest AS build
- BaseName: kbase/kb_jre:latest
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Key: BRANCH
    Name: arg
    Value: develop
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - deployment/
    - /kb/deployment/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jettybase/
    - /kb/deployment/jettybase/
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /tmp/user_profile/dist/UserProfileService.war
    - /kb/deployment/jettybase/webapps/ROOT.war
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/kbase/user_profile.git"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.schema-version
      Value: '"1.0.0-rc1"'
    - Key: us.kbase.vcs-branch
      Value: $BRANCH
    - Key: maintainer
      Value: '"Steve Chan sychan@lbl.gov"'
    Name: label
  - Name: workdir
    Path: /kb/deployment/jettybase
  - Env:
    - Key: KB_DEPLOYMENT_CONFIG
      Value: /kb/deployment/conf/deployment.cfg
    Name: env
  - CmdLine:
    - /kb/deployment/bin/dockerize
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -env
    - /kb/deployment/conf/example.ini
    - -template
    - /kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg
    - -template
    - /kb/deployment/conf/.templates/http.ini.templ:/kb/deployment/jettybase/start.d/http.ini
    - -template
    - /kb/deployment/conf/.templates/server.ini.templ:/kb/deployment/jettybase/start.d/server.ini
    - -template
    - /kb/deployment/conf/.templates/start-server.sh.templ:/kb/deployment/bin/start-server.sh
    - -stdout
    - /kb/deployment/jettybase/logs/request.log
    - -poll
    - /bin/sh
    - -x
    - /kb/deployment/bin/start-server.sh
    Name: cmd
    PrependShell: false
  From:
    Image: kbase/kb_jre:latest
  Name: ""
  Platform: ""
  SourceCode: FROM kbase/kb_jre:latest
