MetaArgs: null
Stages:
- BaseName: asosso/maxscale:2.2.5
  Commands:
  - Maintainer: toughiq@gmail.com
    Name: maintainer
  - Env:
    - Key: MAX_THREADS
      Value: "4"
    - Key: MAX_USER
      Value: '"maxscale"'
    - Key: MAX_PASS
      Value: '"maxscalepass"'
    - Key: ENABLE_ROOT_USER
      Value: "0"
    - Key: SPLITTER_PORT
      Value: "3306"
    - Key: ROUTER_PORT
      Value: "3307"
    - Key: ROUTER_OPTIONS
      Value: '"synced"'
    - Key: CLI_PORT
      Value: "6603"
    - Key: CONNECTION_TIMEOUT
      Value: "600"
    - Key: PERSIST_POOLMAX
      Value: "0"
    - Key: PERSIST_MAXTIME
      Value: "3600"
    - Key: BACKEND_SERVER_LIST
      Value: '"server1 server2 server3"'
    - Key: BACKEND_SERVER_PORT
      Value: '"3306"'
    - Key: USE_SQL_VARIABLES_IN
      Value: '"all"'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - Name: expose
    Ports:
    - $CLI_PORT
    - $ROUTER_PORT
    - $SPLITTER_PORT
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /usr/bin/maxscale
    - --nodaemon
    Name: cmd
    PrependShell: false
  From:
    Image: asosso/maxscale:2.2.5
  Name: ""
  Platform: ""
  SourceCode: FROM asosso/maxscale:2.2.5
