MetaArgs: null
Stages:
- BaseName: library/ubuntu:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"vasilevici777@gmail.com"'
    Name: label
  - CmdLine:
    - groupadd -r play -g 1000 && useradd -u 1000 -r -g play -m -d /opt/play -s /bin/nologin
      -c "Play Framework user" play && chmod 755 /opt/play
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - apt-get update; apt-get install -y software-properties-common unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apt-transport-https
    Name: run
    PrependShell: true
  - CmdLine:
    - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
      &&     echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
      &&     add-apt-repository -y ppa:webupd8team/java &&     apt-get update &&     apt-get
      install -y oracle-java8-installer
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - Name: user
    User: play
  From:
    Image: library/ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM library/ubuntu:latest
