MetaArgs: null
Stages:
- BaseName: debian:7.3
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/sources.d
    - /etc/apt/sources.list.d
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/bin
    - /opt/bin
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/bin/install-nginx
    Name: run
    PrependShell: true
  - CmdLine:
    - "rm -rf /usr/share/doc/ && \tapt-get clean && apt-get clean all && \trm -rf
      /tmp/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/bin/start
    Name: cmd
    PrependShell: true
  From:
    Image: debian:7.3
  Name: ""
  Platform: ""
  SourceCode: FROM debian:7.3
