MetaArgs: null
Stages:
- BaseName: golang:alpine
  Commands:
  - Maintainer: jriddick
    Name: maintainer
  - CmdLine:
    - apk update && apk add git   make   bzr   mercurial   subversion   sqlite-dev   curl   &&
      rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/Masterminds/glide
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/onsi/ginkgo/ginkgo
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/canthefason/go-watcher/cmd/watcher
    Name: run
    PrependShell: true
  - Env:
    - Key: GO15VENDOREXPERIMENT
      Value: "1"
    Name: env
  From:
    Image: golang:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:alpine
