MetaArgs: null
Stages:
- As: artifact
  BaseName: golang:1.9.3-alpine3.7
  Commands:
  - Name: workdir
    Path: /go
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go
  - CmdLine:
    - apk add --no-cache git
    Name: run
    PrependShell: true
  - Env:
    - Key: GOBIN
      Value: '"/go/bin"'
    Name: env
  - CmdLine:
    - go env
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -v && rm bin/go
    Name: run
    PrependShell: true
  - CmdLine:
    - go build -v -o bow
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x bow
    Name: run
    PrependShell: true
  From:
    Image: golang:1.9.3-alpine3.7
  Name: artifact
  Platform: ""
  SourceCode: FROM golang:1.9.3-alpine3.7 AS artifact
- BaseName: alpine:3.7
  Commands:
  - CmdLine:
    - apk add --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /evedel
  - Chown: ""
    From: artifact
    Name: copy
    SourcesAndDest:
    - /go/bow
    - /evedel/bow
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./templates
    - /evedel/templates
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./resources
    - /evedel/resources
  - CmdLine:
    - /evedel/bow
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
