MetaArgs: null
Stages:
- BaseName: busybox
  Commands:
  - Maintainer: bbytes  "info@beyondbytes.co.in"
    Name: maintainer
  - CmdLine:
    - mkdir -p /cloudezz
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /cloudezz/app
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /cloudezz/data
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/true
    Name: cmd
    PrependShell: false
  From:
    Image: busybox
  Name: ""
  Platform: ""
  SourceCode: FROM  busybox
