MetaArgs: null
Stages:
- BaseName: java:openjdk-8u40
  Commands:
  - Maintainer: Fabian Stäber, fabian@fstab.de
    Name: maintainer
  - Name: expose
    Ports:
    - "8443"
  - CmdLine:
    - 'echo "Package: openjdk-8-jdk"          >> /etc/apt/preferences &&     echo
      "Pin: version 8u40-b27-1"         >> /etc/apt/preferences &&     echo "Pin-Priority:
      1001"              >> /etc/apt/preferences &&     echo                                   >>
      /etc/apt/preferences &&     echo "Package: openjdk-8-jre"          >> /etc/apt/preferences
      &&     echo "Pin: version 8u40-b27-1"         >> /etc/apt/preferences &&     echo
      "Pin-Priority: 1001"              >> /etc/apt/preferences &&     echo                                   >>
      /etc/apt/preferences &&     echo "Package: openjdk-8-jre-headless" >> /etc/apt/preferences
      &&     echo "Pin: version 8u40-b27-1"         >> /etc/apt/preferences &&     echo
      "Pin-Priority: 1001"              >> /etc/apt/preferences'
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install vim
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y locales &&     echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
      &&     locale-gen en_US.UTF-8 &&     update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US:en
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - echo "Europe/Berlin" | tee /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-reconfigure --frontend noninteractive tzdata
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    Name: env
  - Env:
    - Key: PATH
      Value: '"$JAVA_HOME/bin:$PATH"'
    Name: env
  - CmdLine:
    - adduser --disabled-login --gecos '' wildfly
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/wildfly
  - CmdLine:
    - wget http://download.jboss.org/wildfly/9.0.1.Final/wildfly-9.0.1.Final.tar.gz
      &&     tar xfz wildfly-9.0.1.Final.tar.gz
    Name: run
    PrependShell: true
  - Env:
    - Key: JBOSS_HOME
      Value: /home/wildfly/wildfly-9.0.1.Final
    Name: env
  - Name: workdir
    Path: /home/wildfly/wildfly-9.0.1.Final/standalone/configuration
  - CmdLine:
    - wget https://raw.githubusercontent.com/undertow-io/undertow/master/core/src/test/resources/server.keystore
      &&     wget https://raw.githubusercontent.com/undertow-io/undertow/master/core/src/test/resources/server.truststore
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/wildfly/wildfly-9.0.1.Final/bin
  - CmdLine:
    - wget http://central.maven.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.3.v20150130/alpn-boot-8.1.3.v20150130.jar
      &&     echo 'JAVA_OPTS="$JAVA_OPTS' " -Xbootclasspath/p:$JBOSS_HOME/bin/alpn-boot-8.1.3.v20150130.jar"
      '"' >> /home/wildfly/wildfly-9.0.1.Final/bin/standalone.conf
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/wildfly/wildfly-9.0.1.Final/standalone/configuration
  - CmdLine:
    - 'echo                                          >> mgmt-users.properties &&     echo
      ''# username: admin, password: admin''     >> mgmt-users.properties &&     echo
      ''admin=c22052286cd5d72239a90fe193737253'' >> mgmt-users.properties'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - add-https-connector.sh
    - /home/wildfly/add-https-connector.sh
  - CmdLine:
    - chown -R wildfly.wildfly /home/wildfly/wildfly-9.0.1.Final &&     chown wildfly.wildfly
      /home/wildfly/add-https-connector.sh
    Name: run
    PrependShell: true
  - Name: user
    User: wildfly
  - Name: workdir
    Path: /home/wildfly/wildfly-9.0.1.Final
  - CmdLine:
    - bash -c '/home/wildfly/add-https-connector.sh & ./bin/standalone.sh'
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /home/wildfly/wildfly-9.0.1.Final/standalone/configuration/standalone_xml_history/current
      /home/wildfly/wildfly-9.0.1.Final/standalone/configuration/standalone_xml_history/DOCKER-BUILD
    Name: run
    PrependShell: true
  - CmdLine:
    - bash -c './bin/standalone.sh'
    Name: entrypoint
    PrependShell: true
  From:
    Image: java:openjdk-8u40
  Name: ""
  Platform: ""
  SourceCode: FROM java:openjdk-8u40
