MetaArgs: null
Stages:
- As: base
  BaseName: mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim
  Commands:
  - Name: workdir
    Path: /app
  From:
    Image: mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim
  Name: base
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
- As: build
  BaseName: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.Api/DatingAppCore.Api.csproj
    - DatingAppCore.Api/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.BLL/DatingAppCore.BLL.csproj
    - DatingAppCore.BLL/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.Repo/DatingAppCore.Repo.csproj
    - DatingAppCore.Repo/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.Dto/DatingAppCore.Dto.csproj
    - DatingAppCore.Dto/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.Interfaces/DatingAppCore.Interfaces.csproj
    - DatingAppCore.Interfaces/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.Test/DatingAppCore.Test.csproj
    - DatingAppCore.Test/
  - CmdLine:
    - dotnet restore "DatingAppCore.Api/DatingAppCore.Api.csproj"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Name: workdir
    Path: '"/src/DatingAppCore.Api"'
  - CmdLine:
    - dotnet build "DatingAppCore.Api.csproj" -c Release -o /app
    Name: run
    PrependShell: true
  - Env:
    - Key: ASPNETCORE_URLS
      Value: https://+:443;http://+:80;https://+:5001
    Name: env
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  - Name: expose
    Ports:
    - "5000"
  - Name: expose
    Ports:
    - "5001"
  From:
    Image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
  Name: build
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
- As: publish
  BaseName: build
  Commands:
  - CmdLine:
    - dotnet publish "DatingAppCore.Api.csproj" -c Release -o /app
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 1
      Named: build
  Name: publish
  Platform: ""
  SourceCode: FROM build AS publish
- As: final
  BaseName: base
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - DatingAppCore.Api/bundle.pfx
    - bundle.pfx
  - CmdLine:
    - find -name "bundle.pfx"
    Name: run
    PrependShell: true
  - CmdLine:
    - ls
    Name: run
    PrependShell: true
  - Chown: ""
    From: publish
    Name: copy
    SourcesAndDest:
    - /app
    - .
  - CmdLine:
    - dotnet
    - DatingAppCore.Api.dll
    - --urls
    - http://*:5000;https://*:5001
    Name: entrypoint
    PrependShell: false
  From:
    Stage:
      Index: 0
      Named: base
  Name: final
  Platform: ""
  SourceCode: FROM base AS final
