MetaArgs: null
Stages:
- BaseName: ehazlett/interlock:1.2.0
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - custom_template/nginx.conf.template
    - /etc/interlock/nginx.conf.template
  From:
    Image: ehazlett/interlock:1.2.0
  Name: ""
  Platform: ""
  SourceCode: FROM ehazlett/interlock:1.2.0
