MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Maintainer: Mike Barrett
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/docker-stacker
    - /bin/docker-stacker
  - Name: workdir
    Path: /stacks
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /tmp/stacker
  - CmdLine:
    - apk --no-cache update &&     apk --no-cache add python2 py2-pip py-yaml build-base
      &&     mkdir -p /stacks &&     pip install --upgrade setuptools &&     pip install
      yamllint &&     cd /tmp/stacker &&     python setup.py install &&     rm -rf
      /tmp/stacker &&     apk --no-cache del build-base &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-stacker
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -h
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
