MetaArgs: null
Stages:
- BaseName: node:latest
  Commands:
  - Maintainer: Daniel Atkinson <hourd.tasa@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y vim
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /blog
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./startup.sh
    - /bin/startup
  - CmdLine:
    - chmod +x /bin/startup && npm install hexo-cli -g
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4000"
  - CmdLine:
    - /bin/startup
    Name: cmd
    PrependShell: false
  From:
    Image: node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM node:latest
