MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Bitworks Software info@bitworks.software
    Name: maintainer
  - Env:
    - Key: INFLUX_HOST
      Value: influxhost.com
    Name: env
  - Env:
    - Key: INFLUX_PORT
      Value: "8086"
    Name: env
  - Env:
    - Key: INFLUX_DB
      Value: puls
    Name: env
  - Env:
    - Key: INFLUX_USER
      Value: puls
    Name: env
  - Env:
    - Key: INFLUX_PASSWORD
      Value: secret
    Name: env
  - Env:
    - Key: KAFKA_BOOTSTRAP
      Value: localhost:9092
    Name: env
  - Env:
    - Key: KAFKA_TOPIC
      Value: kvm-metrics
    Name: env
  - Env:
    - Key: KAFKA_GROUP
      Value: group
    Name: env
  - Env:
    - Key: PAUSE
      Value: "20"
    Name: env
  - Env:
    - Key: GATHER_HOST_STATS
      Value: "true"
    Name: env
  - Env:
    - Key: DEBUG
      Value: "true"
    Name: env
  - CmdLine:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -q python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install kafka-python
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install influxdb
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src
    - /opt
  - Name: workdir
    Path: /opt
  - CmdLine:
    - /bin/bash
    - /opt/import-data
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
