MetaArgs: null
Stages:
- BaseName: neubiaswg5/icy-base:latest
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - protocol.protocol
    - /icy/protocols/protocol.protocol
  - Chown: ""
    Name: add
    SourcesAndDest:
    - wrapper.py
    - /app/wrapper.py
  - CmdLine:
    - python
    - /app/wrapper.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: neubiaswg5/icy-base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM neubiaswg5/icy-base:latest
