MetaArgs: null
Stages:
- BaseName: php:7.2-fpm
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y         libicu-dev         apt-utils         curl         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev     &&
      docker-php-ext-install -j$(nproc) gd     && docker-php-ext-install -j$(nproc)
      intl     && docker-php-ext-install -j$(nproc) mbstring     && docker-php-ext-install
      -j$(nproc) opcache
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer |             php -- --install-dir=/usr/bin/
      --filename=composer
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "22"
  From:
    Image: php:7.2-fpm
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2-fpm
