MetaArgs: null
Stages:
- BaseName: obedmr/archlinux
  Commands:
  - Maintainer: obed.n.munoz@gmail.com
    Name: maintainer
  - CmdLine:
    - pacman -Sy --noconfirm opencv cmake unzip opencv-samples python-numpy
    Name: run
    PrependShell: true
  From:
    Image: obedmr/archlinux
  Name: ""
  Platform: ""
  SourceCode: FROM obedmr/archlinux
