MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: elarasu@outlook.com
    Name: maintainer
  - CmdLine:
    - locale-gen --no-purge en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update   && apt-get install -yq wget curl netcat openssl unzip sysstat
      lsof strace tcpdump dnsutils vim-tiny git --no-install-recommends   && sed -i
      '/ENABLED/ s/false/true/' /etc/default/sysstat   && apt-get autoremove -y   &&
      apt-get clean -y   && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
