MetaArgs: null
Stages:
- BaseName: python:3.6-slim
  Commands:
  - Env:
    - Key: VERSION
      Value: 1.1.1
    - Key: REPO
      Value: https://github.com/wosc/schlund-ddns
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y curl
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -SLO "${REPO}/archive/${VERSION}.tar.gz"     && tar xzf ${VERSION}.tar.gz     &&
      mv /schlund-ddns-${VERSION} /schlund-ddns     && rm *.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /schlund-ddns
  - CmdLine:
    - pip install .
    Name: run
    PrependShell: true
  - Env:
    - Key: FLASK_APP
      Value: src/ws/ddns/web.py
    Name: env
  - Env:
    - Key: FLASK_RUN_HOST
      Value: 0.0.0.0
    Name: env
  - CmdLine:
    - flask
    - run
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-slim
