MetaArgs: null
Stages:
- BaseName: python:3-alpine
  Commands:
  - Labels:
    - Key: authors
      Value: '"Vašek Dohnal <vaclav.dohnal@gmail.com>"'
    Name: label
  - CmdLine:
    - pip install --upgrade --ignore-installed --isolated --no-input --compile --exists-action=a
      --disable-pip-version-check --no-cache-dir       awscli
    Name: run
    PrependShell: true
  - CmdLine:
    - '[''awscli'']'
    Name: cmd
    PrependShell: true
  From:
    Image: python:3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3-alpine
