MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: <https://github.com/FuntwoX>
    Name: maintainer
  - CmdLine:
    - echo "deb http://ftp.us.debian.org/debian/ stretch main contrib non-free"         >>
      /etc/apt/sources.list     && apt-get update     && apt-get install --no-install-recommends
      -y         vim         ca-certificates         python         python-dev         curl         git         nginx         unzip         unrar         supervisor         bzip2     &&
      apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -y     && apt-get install -y build-essential curl     && curl
      -sL https://deb.nodesource.com/setup_10.x | bash -     && apt-get install -y
      nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update     && apt-get install -y --force-yes supervisor     && apt-get
      install --no-install-recommends -y python-cheetah     && git clone --depth=1         https://github.com/SickChill/SickChill.git         /opt/sickrage     &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /torrents
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /torrents /downloads
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - createUsersAndStart.sh
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - template/*
    - /template/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rules-htpasswd
    - /etc/nginx/.htpasswd
  - Name: volume
    Volumes:
    - /config
  - Name: expose
    Ports:
    - "8081"
  - CmdLine:
    - chmod +x createUsersAndStart.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /createUsersAndStart.sh
    - /etc/nginx/.htpasswd
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
