MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - Maintainer: Rodrigo Mata <rodrigo.mata.ib@gmail.com>
    Name: maintainer
  - CmdLine:
    - apk add --update curl &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
