MetaArgs: null
Stages:
- BaseName: node:onbuild
  Commands:
  - CmdLine:
    - npm run postinstall
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /usr/src/app/configs
    - /usr/src/app/files
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: node:onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM node:onbuild
