MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  Commands:
  - Maintainer: liangqingxiang
    Name: maintainer
  From:
    Image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8
