MetaArgs: null
Stages:
- BaseName: postgres:9.5.1
  Commands:
  - Env:
    - Key: PGDATA
      Value: /var/lib/postgresql/data/pgdata
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - configs/*
    - /configs/
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - postgres
    - -c
    - config_file=/configs/1gb-ram.conf
    Name: cmd
    PrependShell: false
  From:
    Image: postgres:9.5.1
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.5.1
