MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: Andrew Wharton <andrew@deciduouspress.com.au>
    Name: maintainer
  - Env:
    - Key: METEORD_DIR
      Value: /opt/meteord
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts
    - $METEORD_DIR
  - CmdLine:
    - bash $METEORD_DIR/init.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - bash $METEORD_DIR/run_app.sh
    Name: entrypoint
    PrependShell: true
  - Expression: COPY ./ /app
    Name: onbuild
  - Expression: RUN bash $METEORD_DIR/on_build.sh
    Name: onbuild
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
