MetaArgs: null
Stages:
- BaseName: openjdk:8-jre
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Rodolphe CHAIGNEAU <rodolphe.chaigneau@gmail.com>"'
    Name: label
  - Env:
    - Key: WIREMOCK_VERSION
      Value: 2.23.2
    Name: env
  - Env:
    - Key: GOSU_VERSION
      Value: "1.10"
    Name: env
  - CmdLine:
    - "set -x \t&& wget -O /usr/local/bin/gosu \"https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg
      --print-architecture)\" \t&& wget -O /usr/local/bin/gosu.asc \"https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg
      --print-architecture).asc\" \t&& export GNUPGHOME=\"$(mktemp -d)\" \t&& for
      server in $(shuf -e ha.pool.sks-keyservers.net         hkp://p80.pool.sks-keyservers.net:80
      \        keyserver.ubuntu.com         hkp://keyserver.ubuntu.com:80         pgp.mit.edu)
      ; do         gpg --batch --keyserver \"$server\" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
      && break || : ;         done \t&& gpg --batch --verify /usr/local/bin/gosu.asc
      /usr/local/bin/gosu \t&& rm -rf \"$GNUPGHOME\" /usr/local/bin/gosu.asc \t&&
      chmod +x /usr/local/bin/gosu \t&& gosu nobody true"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/wiremock/lib/   && wget https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/$WIREMOCK_VERSION/wiremock-jre8-standalone-$WIREMOCK_VERSION.jar     -O
      /var/wiremock/lib/wiremock-jre8-standalone.jar
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/wiremock
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - Name: volume
    Volumes:
    - /home/wiremock
  - Name: expose
    Ports:
    - "8080"
    - "8443"
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - java $JAVA_OPTS -cp /var/wiremock/lib/*:/var/wiremock/extensions/* com.github.tomakehurst.wiremock.standalone.WireMockServerRunner
    Name: cmd
    PrependShell: true
  From:
    Image: openjdk:8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre
