MetaArgs: null
Stages:
- As: go-builder
  BaseName: golang
  Commands:
  - Name: workdir
    Path: $GOPATH/src/app
  - Env:
    - Key: GO111MODULE
      Value: "on"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - go.mod
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - go.sum
    - .
  - CmdLine:
    - go mod download
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cmd
    - cmd
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - internal
    - internal
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pkg
    - pkg
  - CmdLine:
    - CGO_ENABLED=0 go build -tags debug -o /dist/server -v -i -ldflags="-s -w" ./cmd/server
    Name: run
    PrependShell: true
  From:
    Image: golang
  Name: go-builder
  Platform: ""
  SourceCode: FROM golang AS go-builder
- BaseName: ubuntu:16.04
  Commands:
  - Name: workdir
    Path: /app
  - CmdLine:
    - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >>  /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list
      &&     apt-get update &&     apt-get install -y pulseaudio xvfb wget gnupg htop
      --no-install-recommends &&     wget https://dl.google.com/linux/linux_signing_key.pub
      --no-check-certificate &&     apt-key add linux_signing_key.pub &&     apt-get
      update &&     apt-get install -y google-chrome-stable --no-install-recommends
      &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/run-chrome.sh
    - run-chrome.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/start-server.sh
    - start-server.sh
  - CmdLine:
    - /bin/sh run-chrome.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: DISPLAY
      Value: :99
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/local/lib
    Name: env
  - Chown: ""
    From: go-builder
    Name: copy
    SourcesAndDest:
    - /dist
    - /bin/
  - CmdLine:
    - /app/start-server.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
