MetaArgs: null
Stages:
- BaseName: ruby:2.3
  Commands:
  - Maintainer: David Kelley <david@stockflare.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: CONFD_VERSION
      Value: 0.10.0
    Name: env
  - Env:
    - Key: INTERVAL
      Value: "60"
    Name: env
  - Name: workdir
    Path: /stockflare
  - CmdLine:
    - gem install localeapp deep_merge
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/confd
    - /etc/confd
  - Chown: ""
    Name: add
    SourcesAndDest:
    - confd/confd-0.10.0-linux-amd64
    - /bin/confd
  - CmdLine:
    - mkdir /stockflare/.localeapp && mkdir /stockflare/locales
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /stockflare/locales/v1
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /stockflare/locales/v2
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /stockflare/locales/v3
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /stockflare/locales/v4
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /stockflare/locales/v5
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /stockflare/locales
  - Chown: ""
    Name: add
    SourcesAndDest:
    - boot
    - boot
  - Chown: ""
    Name: add
    SourcesAndDest:
    - merge.rb
    - merge.rb
  - CmdLine:
    - ./boot
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.3
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3
