MetaArgs: null
Stages:
- BaseName: sfiligoi/prp-osg-cvmfs:cvmfs-autofs
  Commands:
  - Env:
    - Key: CSI_ENDPOINT
      Value: unix://var/lib/kubelet/plugins/csi-cvmfsplugin/csi.sock
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/csi-cvmfsplugin
    - /usr/sbin/csi-cvmfsplugin
  - Chown: ""
    Name: add
    SourcesAndDest:
    - create_supervisor_csi_conf.sh
    - /etc/osg/image-config.d/99_create_supervisor_csi_conf.sh
  From:
    Image: sfiligoi/prp-osg-cvmfs:cvmfs-autofs
  Name: ""
  Platform: ""
  SourceCode: FROM sfiligoi/prp-osg-cvmfs:cvmfs-autofs
