MetaArgs: null
Stages:
- BaseName: openjdk:8-alpine
  Commands:
  - Key: SBT_VERSION
    Name: arg
    Value: null
  - Env:
    - Key: SBT_VERSION
      Value: ${SBT_VERSION:-0.13.12}
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar
    - /usr/bin/sbt-launch.jar
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sbt.sh
    - /usr/bin/sbt
  - CmdLine:
    - echo "==> [CAUTION] This may take several minutes!!!"     && sbt
    Name: run
    PrependShell: true
  - CmdLine:
    - sbt
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - help
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-alpine
