MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.12.5
  Commands:
  - Name: workdir
    Path: /workspace
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - go.mod
    - go.mod
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - go.sum
    - go.sum
  - CmdLine:
    - go mod download
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - main.go
    - main.go
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - api/
    - api/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - controllers/
    - controllers/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - backend/
    - backend/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - errors/
    - errors/
  - Key: SECRETS_MANAGER_VERSION
    Name: arg
    Value: v1.0.1
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - hack/
    - hack/
  - CmdLine:
    - go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.2
    Name: run
    PrependShell: true
  - CmdLine:
    - /go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -ldflags "-X main.version=${SECRETS_MANAGER_VERSION}"
      -a -o secrets-manager main.go
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12.5
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.12.5 as builder
- BaseName: gcr.io/distroless/static:latest
  Commands:
  - Name: workdir
    Path: /
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /workspace/secrets-manager
    - .
  - CmdLine:
    - /secrets-manager
    Name: entrypoint
    PrependShell: false
  From:
    Image: gcr.io/distroless/static:latest
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/distroless/static:latest
