MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends   build-essential   curl   ca-certificates   ssh   nano   htop   libpq-dev
    Name: run
    PrependShell: true
  - Env:
    - Key: PYTHON_VERSION
      Value: "3.6"
    Name: env
  - CmdLine:
    - curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&   chmod
      +x ~/miniconda.sh &&   ~/miniconda.sh -b -p /opt/conda &&   rm ~/miniconda.sh
      &&   /opt/conda/bin/conda install conda-build &&   /opt/conda/bin/conda install
      python=$PYTHON_VERSION &&   /opt/conda/bin/conda clean -ya
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/conda/bin/conda init bash && exec bash
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/conda/bin:/opt/conda/envs/py$PYTHON_VERSION/bin:$PATH
    Name: env
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
