MetaArgs: null
Stages:
- BaseName: jupyter/tensorflow-notebook
  Commands:
  - Name: workdir
    Path: /home/jovyan
  - Name: user
    User: root
  - CmdLine:
    - sudo apt-get update && apt-get install -y    vim    tig && apt-get clean &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - ./
  - CmdLine:
    - pip install --no-cache-dir -r requirements.txt
    Name: run
    PrependShell: true
  - Name: user
    User: jovyan
  - CmdLine:
    - jupyter contrib nbextension install --user
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/lambdalisue/jupyter-vim-binding.git ./.local/share/jupyter/nbextensions/usability/vim_binding
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - chmod -R go-w ./.local/share/jupyter/nbextensions/usability/vim_binding
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./jupyter_notebook_config.py
    - ./.jupyter/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./nbconfig
    - ./.jupyter/nbconfig
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements_option.txt
    - ./
  - CmdLine:
    - pip install --no-cache-dir -r requirements_option.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get update && apt-get install -y    graphviz && apt-get clean && rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/jovyan/jupyter
  From:
    Image: jupyter/tensorflow-notebook
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/tensorflow-notebook
