MetaArgs: null
Stages:
- BaseName: quay.io/quarkus/centos-quarkus-maven:19.2.1
  Commands:
  - Name: user
    User: root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./pom.xml
    - /project/pom.xml
  - CmdLine:
    - mvn -B -e -C -T 1C dependency:go-offline
    Name: run
    PrependShell: true
  From:
    Image: quay.io/quarkus/centos-quarkus-maven:19.2.1
  Name: ""
  Platform: ""
  SourceCode: FROM quay.io/quarkus/centos-quarkus-maven:19.2.1
