MetaArgs: null
Stages:
- BaseName: php:7.3-apache
  Commands:
  - Maintainer: Malitta Nanayakkara <malitta@gmail.com>
    Name: maintainer
  - CmdLine:
    - "apt-get update && apt-get install -y \tcurl \tsupervisor \tvim \tzip \twget"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files/supervisor-apache.conf
    - /etc/supervisor/conf.d/apache2.conf
  - CmdLine:
    - rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - "curl -sS https://getcomposer.org/installer | \tphp -- --install-dir=/usr/local/bin
      --filename=composer"
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/www/html
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files/public
    - /var/www/public
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files/000-default.conf
    - /etc/apache2/sites-available/000-default.conf
  - CmdLine:
    - a2enmod rewrite headers
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Name: workdir
    Path: /var/www
  - CmdLine:
    - /usr/bin/supervisord
    - -n
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.3-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-apache
