MetaArgs: null
Stages:
- BaseName: busybox
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - build.sh
    - /
  - CmdLine:
    - /build.sh
    Name: run
    PrependShell: true
  From:
    Image: busybox
  Name: ""
  Platform: ""
  SourceCode: FROM busybox
