MetaArgs: null
Stages:
- BaseName: tiredofit/nodejs:8-latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Dave Conroy (dave at tiredofit dot ca)"'
    Name: label
  - Env:
    - Key: ENABLE_SMTP
      Value: "false"
    Name: env
  - CmdLine:
    - addgroup haraka &&         adduser -S                 -D -G haraka                 -h
      /data/             haraka &&         apk upgrade &&         apk add --virtual
      haraka-build-dependencies             gcc             g++             libpcap-dev             libtool             make             musl-dev             &&         apk
      add             curl             libpcap             libressl             python             tar             wget             &&         mkdir
      -p /usr/src/iconv &&         curl http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
      | tar xfz - --strip 1 -C /usr/src/iconv &&         cd /usr/src/iconv &&         sed
      -i 's/_GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");/#if
      HAVE_RAW_DECL_GETS\n_GL_WARN_ON_USE (gets, "gets is a security hole - use fgets
      instead");\n#endif/g' srclib/stdio.in.h &&         ./configure --prefix=/usr/local
      &&         make &&         make install &&         libtool --finish /usr/local/lib
      &&         cd /usr/src &&             npm -g install --unsafe-perm --production             express             Haraka             haraka-plugin-geoip             haraka-plugin-ldap             haraka-plugin-limit             haraka-plugin-p0f             iconv             maxmind-geolite-mirror             mkdirp             sqlite3             toobusy-js             tmp             &&         mkdir
      -p /usr/src/p0f &&         curl http://lcamtuf.coredump.cx/p0f3/releases/p0f-3.09b.tgz
      | tar xzf - --strip 1 -C /usr/src/p0f &&         cd /usr/src/p0f &&         ./build.sh
      &&         cp p0f /usr/sbin/ &&         cp p0f.fp /etc/p0f.fp &&             ln
      -s /data/geoip /usr/local/share/GeoIP &&             apk del --purge haraka-build-dependencies
      &&             rm -rf /var/cache/apk/* /usr/src/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install
    - /
  - Name: expose
    Ports:
    - "25"
    - "587"
  From:
    Image: tiredofit/nodejs:8-latest
  Name: ""
  Platform: ""
  SourceCode: FROM tiredofit/nodejs:8-latest
