MetaArgs: null
Stages:
- BaseName: gcc
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /usr/src/ostiary
  - Name: workdir
    Path: /usr/src/ostiary
  - CmdLine:
    - ./configure &&   make all &&   make install &&   mv -vi     /usr/local/etc/ostiary.cfg     /usr/local/etc/ostiary.cfg.default
    Name: run
    PrependShell: true
  From:
    Image: gcc
  Name: ""
  Platform: ""
  SourceCode: FROM gcc
