MetaArgs: null
Stages:
- BaseName: nginx
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./conf/django.conf
    - /etc/nginx/conf.d/
  - CmdLine:
    - echo "Asia/Tokyo" > /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-reconfigure -f noninteractive tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /src
    Name: run
    PrependShell: true
  From:
    Image: nginx
  Name: ""
  Platform: ""
  SourceCode: FROM nginx
