MetaArgs: null
Stages:
- BaseName: php:7.3-fpm-alpine
  Commands:
  - CmdLine:
    - apk update
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add php7-json php7-session php7-ctype
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add php7-tokenizer php7-simplexml php7-dom
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add php7-mbstring php7-zip php7-pdo_mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add pcre
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add zlib-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add libzip-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./pagekit/
    - /pagekit/
  - Name: volume
    Volumes:
    - /pagekit/storage
    - pagekit
  - Name: expose
    Ports:
    - 80/tcp
  From:
    Image: php:7.3-fpm-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-fpm-alpine
