MetaArgs: null
Stages:
- BaseName: liuchong/rustup:nightly
  Commands:
  - CmdLine:
    - apt-get update     && apt-get install -y --no-install-recommends ca-certificates
      zlib1g-dev libc6 libgcc1 cmake libssh2-1-dev git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /build
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /build
  - CmdLine:
    - cargo build --release --verbose
    Name: run
    PrependShell: true
  From:
    Image: liuchong/rustup:nightly
  Name: ""
  Platform: ""
  SourceCode: FROM liuchong/rustup:nightly
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update     && apt-get install -y --no-install-recommends ca-certificates
      libssl1.0.2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/lib/grapple
  - Env:
    - Key: ROCKET_ENV
      Value: prod
    Name: env
  - Env:
    - Key: ROCKET_PORT
      Value: "8000"
    Name: env
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /build/target/release/grapple
    - /bin/grapple
  - CmdLine:
    - /bin/grapple
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
