MetaArgs: null
Stages:
- BaseName: cooptilleuls/varnish:6.2.0-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Aplyca"'
    - Key: description
      Value: '"Varnish image with VMOD dynamic"'
    Name: label
  - Env:
    - Key: PKG_CONFIG_PATH
      Value: /usr/local/lib/pkgconfig
    Name: env
  - Env:
    - Key: ACLOCAL_PATH
      Value: /usr/local/share/aclocal
    Name: env
  - CmdLine:
    - set -eux;     apk add --quiet --progress --update --no-cache --virtual .vmod-build-deps
      autoconf automake libexecinfo-dev libtool make pcre-dev pkgconf py-docutils
      python3 &&     wget "https://github.com/nigoroll/libvmod-dynamic/archive/6.2.zip"
      -O /tmp/libvmod-dynamic.zip &&     unzip -d /tmp /tmp/libvmod-dynamic.zip &&     cd
      "/tmp/libvmod-dynamic-6.2" &&     chmod +x ./autogen.sh &&     ./autogen.sh
      &&     ./configure --prefix=/usr/local &&     make -j "$(nproc)" &&     make
      install &&     cd / &&     rm -rf /tmp/libvmod-dynamic* &&     apk del --purge
      .vmod-build-deps autoconf automake make libexecinfo-dev pcre-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/sh
    - -o
    - pipefail
    - -c
    - varnishd -F -f /usr/local/share/varnish/vcl/default.vcl -s malloc,${VARNISH_MEMORY:-80M}
      ${VARNISH_PARAMS} | varnishncsa -F '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i"
      "%{Varnish:handling}x"'
    Name: cmd
    PrependShell: false
  From:
    Image: cooptilleuls/varnish:6.2.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM cooptilleuls/varnish:6.2.0-alpine
