MetaArgs: null
Stages:
- BaseName: node:lts-alpine
  Commands:
  - Name: workdir
    Path: /api
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /api
    - /api/
  - CmdLine:
    - npm install -qy
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:lts-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:lts-alpine
