MetaArgs: null
Stages:
- BaseName: mhart/alpine-node:6.10
  Commands:
  - Maintainer: chief@beefdisciple.com
    Name: maintainer
  - Env:
    - Key: WD
      Value: /opt/hubot
    Name: env
  - Name: workdir
    Path: $WD
  - CmdLine:
    - mkdir -p $WD
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - $WD
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - CmdLine:
    - bin/hubot -a slack
    Name: cmd
    PrependShell: true
  From:
    Image: mhart/alpine-node:6.10
  Name: ""
  Platform: ""
  SourceCode: FROM mhart/alpine-node:6.10
