MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: PhenoMeNal-H2020 Project ( phenomenal-h2020-users@googlegroups.com
      )
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"MetFrag command line interface."'
    Name: label
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y dist-upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install git wget default-jre-headless
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y clean && apt-get -y autoremove && rm -rf /var/lib/{cache,log}/ /tmp/*
      /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O /usr/local/bin/MetFragCLI.jar http://msbi.ipb-halle.de/~cruttkie/92f73acb731145c73ffa3dfb8fd59581bee0d844963889338c3ec173874b5a5f/MetFrag-2.4.jar
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
