MetaArgs: null
Stages:
- BaseName: php:7.4.0-apache-buster
  Commands:
  - CmdLine:
    - apt-get update &&    apt-get install -y     mariadb-client     git     zip     unzip     iputils-ping
      &&    apt-get clean &&    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng-dev         libicu-dev         libgmp-dev         libsodium-dev     &&
      pecl install libsodium mcrypt mongodb     && docker-php-ext-configure opcache
      --enable-opcache     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/
      --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gmp gd
      opcache iconv intl pdo_mysql pcntl bcmath     && docker-php-ext-enable mcrypt
      mongodb     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/opcache.ini
    - $PHP_INI_DIR/conf.d/
  - CmdLine:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    Name: run
    PrependShell: true
  - CmdLine:
    - php composer-setup.php
    Name: run
    PrependShell: true
  - CmdLine:
    - php -r "unlink('composer-setup.php');"
    Name: run
    PrependShell: true
  - CmdLine:
    - mv composer.phar /usr/local/bin/composer
    Name: run
    PrependShell: true
  From:
    Image: php:7.4.0-apache-buster
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.4.0-apache-buster
