MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.10.0
  Commands:
  - Labels:
    - Key: author
      Value: '"kevinqq"'
    Name: label
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - CmdLine:
    - mkdir /code
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:jonathonf/python-3.6
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python3.6
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://bootstrap.pypa.io/get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - python3.6 get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
    Name: run
    PrependShell: true
  - CmdLine:
    - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
    Name: run
    PrependShell: true
  - CmdLine:
    - update-alternatives --config python3
    Name: run
    PrependShell: true
  - Env:
    - Key: PYTHONIOENCODING
      Value: utf-8
    Name: env
  - CmdLine:
    - pip3 install flask
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: phusion/baseimage:0.10.0
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.10.0
