MetaArgs: null
Stages:
- BaseName: omniscient/base
  Commands:
  - CmdLine:
    - apt-get update   && apt-get install -y curl   && curl -sL https://deb.nodesource.com/setup_8.x
      | bash -   && apt-get install -y     git     nodejs
    Name: run
    PrependShell: true
  From:
    Image: omniscient/base
  Name: ""
  Platform: ""
  SourceCode: FROM omniscient/base
