MetaArgs: null
Stages:
- BaseName: centos:latest
  Commands:
  - Maintainer: Faidev <25056592@qq.com>
    Name: maintainer
  - CmdLine:
    - yum install -y mariadb mariadb-server && yum clean all && chgrp -R 0 /var/lib/mysql/
      /var/log/mariadb/ /var/run/ && chmod -R g+rw /var/lib/mysql/ /var/log/mariadb/
      /var/run/ && find /var/lib/mysql/ /var/log/mariadb/ /var/run/ -type d -exec
      chmod g+x {} + && curl -o docker-entrypoint.sh https://raw.githubusercontent.com/faidev/dockerfile/master/mariadb/docker-entrypoint.sh
      && chmod +x docker-entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: volume
    Volumes:
    - /var/lib/mysql
  - Name: user
    User: "27"
  - Name: expose
    Ports:
    - "3306"
  - CmdLine:
    - mysqld_safe
    Name: cmd
    PrependShell: false
  From:
    Image: centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM centos:latest
