MetaArgs: null
Stages:
- BaseName: drupal:7
  Commands:
  - Env:
    - Key: FARMOS_VERSION
      Value: 7.x-1.x-dev
    Name: env
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install bcmath
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL 'http://git.php.net/?p=pecl/php/uploadprogress.git;a=snapshot;h=95d8a0fd4554e10c215d3ab301e901bd8f99c5d9;sf=tgz'
      -o php-uploadprogress.tar.gz   && tar -xzf php-uploadprogress.tar.gz   && rm
      php-uploadprogress.tar.gz   && (     cd uploadprogress-95d8a0f     && phpize     &&
      ./configure --enable-uploadprogress     && make     && make install   )   &&
      rm -r uploadprogress-95d8a0f
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-enable uploadprogress
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y libgeos-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL 'https://git.osgeo.org/gitea/geos/php-geos/archive/1.0.0.tar.gz'
      -o php-geos.tar.gz   && tar -xzf php-geos.tar.gz   && rm php-geos.tar.gz   &&
      (     cd php-geos     && ./autogen.sh     && ./configure     && make     &&
      make install   )   && rm -r php-geos
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-enable geos
    Name: run
    PrependShell: true
  - CmdLine:
    - '{     echo ''memory_limit=256M'';     echo ''max_execution_time=240'';     echo
      ''max_input_time=240'';     echo ''max_input_vars=5000'';   } > /usr/local/etc/php/conf.d/farmOS-recommended.ini'
    Name: run
    PrependShell: true
  - CmdLine:
    - '{     echo ''realpath_cache_size=256K'';     echo ''realpath_cache_ttl=3600'';   }
      > /usr/local/etc/php/conf.d/realpath_cache-recommended.ini'
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -SL "http://ftp.drupal.org/files/projects/farm-${FARMOS_VERSION}-core.tar.gz"
      -o /tmp/farm-${FARMOS_VERSION}-core.tar.gz &&   tar -xvzf /tmp/farm-${FARMOS_VERSION}-core.tar.gz
      -C /var/www/html/ --strip-components=1 &&   chown -R www-data:www-data /var/www/html
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -rp /var/www/html/sites /tmp/sites
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - chmod u+x /usr/local/bin/docker-entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apache2-foreground
    Name: cmd
    PrependShell: false
  From:
    Image: drupal:7
  Name: ""
  Platform: ""
  SourceCode: FROM drupal:7
