MetaArgs: null
Stages:
- BaseName: continuumio/anaconda3:5.3.0
  Commands:
  - Maintainer: kraus1049
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./numpy-site.cfg
    - ~/.numpy-site.cfg
  - CmdLine:
    - rm -rf ~/.cache/matplotlib &&     apt-get update && apt-get install -y fonts-ipa*
      git ssh && apt-get autoremove &&     fc-cache &&     ldconfig &&     git clone
      -b develop https://fec1d7246bc38dbb90422f2f9ff28c11f8f68e50:x-oauth-basic@github.com/kraus1049/opt_sim
      /opt/conda/lib/python3.7/site-packages/opt_sim
    Name: run
    PrependShell: true
  - CmdLine:
    - conda install -c conda-forge nodejs opencv &&     conda update jupyter jupyterlab
      &&     jupyter labextension install jupyterlab_vim &&     mkdir -p /home/jovyan/libs/
      &&     mkdir /home/jovyan/current_dir &&     conda update scipy numpy
    Name: run
    PrependShell: true
  From:
    Image: continuumio/anaconda3:5.3.0
  Name: ""
  Platform: ""
  SourceCode: FROM continuumio/anaconda3:5.3.0
