MetaArgs: null
Stages:
- BaseName: qinyuguang/yafbase:latest
  Commands:
  - Name: volume
    Volumes:
    - /www/dataflow
    - /home/logs/project/dataflow
    - /home/logs/php/dataflow
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /www/dataflow/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./conf/online/php.ini
    - /usr/local/etc/php/php.ini
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./conf/online/fpm.conf
    - /usr/local/etc/php-fpm.d/dataflow.conf
  - Name: workdir
    Path: /www/dataflow
  - CmdLine:
    - /www/dataflow/start.sh
    Name: cmd
    PrependShell: true
  From:
    Image: qinyuguang/yafbase:latest
  Name: ""
  Platform: ""
  SourceCode: FROM qinyuguang/yafbase:latest
