MetaArgs: null
Stages:
- BaseName: docker.elastic.co/kibana/kibana:5.6.15
  Commands:
  - Maintainer: tomas.hejatko@gmail.com
    Name: maintainer
  - Chown: kibana:kibana
    From: ""
    Name: copy
    SourcesAndDest:
    - kibana.yml
    - /usr/share/kibana/config/
  - CmdLine:
    - rm -Rf /usr/share/kibana/plugins/x-pack*
    Name: run
    PrependShell: true
  From:
    Image: docker.elastic.co/kibana/kibana:5.6.15
  Name: ""
  Platform: ""
  SourceCode: FROM docker.elastic.co/kibana/kibana:5.6.15
