MetaArgs: null
Stages:
- As: builder
  BaseName: mcr.microsoft.com/dotnet/core/sdk:2.2
  Commands:
  - Name: workdir
    Path: /workdir
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /workdir
  - CmdLine:
    - set -ex &&     dotnet restore DotNetCoreSqlDb.csproj --verbosity Detailed &&     dotnet
      build DotNetCoreSqlDb.csproj --configuration Release &&     dotnet publish DotNetCoreSqlDb.csproj
      --configuration Release
    Name: run
    PrependShell: true
  From:
    Image: mcr.microsoft.com/dotnet/core/sdk:2.2
  Name: builder
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as builder
- BaseName: mcr.microsoft.com/dotnet/core/aspnet:2.2
  Commands:
  - Name: workdir
    Path: /workdir
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /workdir/bin/Release/netcoreapp2.2/publish
    - .
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - dotnet
    - DotNetCoreSqlDb.dll
    Name: cmd
    PrependShell: false
  From:
    Image: mcr.microsoft.com/dotnet/core/aspnet:2.2
  Name: ""
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
