MetaArgs: null
Stages:
- BaseName: python:3.6.4-alpine3.6
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"https://github.com/lyremelody"'
    Name: label
  - Env:
    - Key: TARGET_HOST
      Value: '"elasticseach.host:9200"'
    Name: env
  - Env:
    - Key: REPORT_FORMAT
      Value: '"markdown"'
    Name: env
  - Env:
    - Key: TRACK
      Value: '"geopoint"'
    Name: env
  - CmdLine:
    - apk add --update --no-cache --no-install-recommends git build-base linux-headers
      python-dev && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install esrally==0.9.0
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rally.ini
    - /root/.rally/
  - CmdLine:
    - esrally --pipeline=benchmark-only --target-hosts=$TARGET_HOST --track=$TRACK
      --report-format=$REPORT_FORMAT
    Name: cmd
    PrependShell: true
  From:
    Image: python:3.6.4-alpine3.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6.4-alpine3.6
