MetaArgs: null
Stages:
- BaseName: jruby:9.1.7
  Commands:
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: TZ
      Value: Asia/Tokyo
    Name: env
  - Env:
    - Key: EMBULK_VERSION
      Value: 0.8.15
    Name: env
  - CmdLine:
    - wget https://dl.bintray.com/embulk/maven/embulk-${EMBULK_VERSION}.jar -O /usr/local/bin/embulk
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/embulk
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /usr/local/bin/embulk:$PATH
    Name: env
  - CmdLine:
    - apt-get update -y &&     apt-get install -y git python-dev &&     wget https://bootstrap.pypa.io/get-pip.py
      &&     python get-pip.py &&     pip install awscli
    Name: run
    PrependShell: true
  From:
    Image: jruby:9.1.7
  Name: ""
  Platform: ""
  SourceCode: FROM jruby:9.1.7
