MetaArgs: null
Stages:
- BaseName: gitlab/gitlab-runner:latest
  Commands:
  - Maintainer: Philipp Hossner <philipp.hossner@posteo.de>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - assets/entrypoint
    - /
  - CmdLine:
    - chmod +x /entrypoint
    Name: run
    PrependShell: true
  From:
    Image: gitlab/gitlab-runner:latest
  Name: ""
  Platform: ""
  SourceCode: FROM gitlab/gitlab-runner:latest
