MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Labels:
    - Key: com.frapsoft.maintainer
      Value: '"Maik Ellerbrock"'
    - Key: com.frapsoft.version
      Value: '"0.1.0"'
    Name: label
  - Key: SERVICE_USER
    Name: arg
    Value: null
  - Key: SERVICE_HOME
    Name: arg
    Value: null
  - Env:
    - Key: SERVICE_USER
      Value: ${SERVICE_USER:-office}
    Name: env
  - Env:
    - Key: SERVICE_HOME
      Value: ${SERVICE_HOME:-/home/${SERVICE_USER}}
    Name: env
  - CmdLine:
    - adduser -h ${SERVICE_HOME} -s /sbin/nologin -u 1000 -D ${SERVICE_USER} &&   apk
      add --no-cache     dumb-init     openjdk8     libreoffice     libreoffice-base     libreoffice-lang-de     mesa-gl     ttf-freefont
    Name: run
    PrependShell: true
  - Name: user
    User: ${SERVICE_USER}
  - Name: workdir
    Path: ${SERVICE_HOME}
  - Name: volume
    Volumes:
    - ${SERVICE_HOME}
  - CmdLine:
    - /usr/bin/dumb-init
    - /usr/bin/libreoffice
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
