MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Name: expose
    Ports:
    - 1080/tcp
  - CmdLine:
    - apt-get update &&     apt-get install -y         gnupg2         ca-certificates         apt-utils
      debconf-utils dialog         iptables         dos2unix         openssh-server         curl         &&     echo
      'debconf debconf/frontend select Noninteractive' | debconf-set-selections &&     echo
      "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections
      &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-key FDC247B7 &&     echo
      'deb https://repo.windscribe.com/ubuntu zesty main' | tee /etc/apt/sources.list.d/windscribe-repo.list
      &&     apt-get update &&     apt-get install -y windscribe-cli &&     apt-get
      clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chsh --shell /bin/false
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - docker-healthcheck.sh
    - /
  - CmdLine:
    - dos2unix /docker-*.sh &&     chmod +x /docker-*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Health:
      Interval: 120000000000
      Retries: 3
      StartPeriod: 15000000000
      Test:
      - CMD-SHELL
      - '"/docker-healthcheck.sh"'
      Timeout: 30000000000
    Name: healthcheck
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
