MetaArgs: null
Stages:
- BaseName: oshanrube/base-nginx
  Commands:
  - Maintainer: Oshan Rube <oshanrube@gmail.com>
    Name: maintainer
  - Labels:
    - Key: io.k8s.description
      Value: '"Platform for building symfony"'
    - Key: io.k8s.display-name
      Value: '"builder 0.0.1"'
    - Key: io.openshift.expose-services
      Value: '"80:http"'
    - Key: io.openshift.tags
      Value: '"builder,0.0.1,nginx,etc."'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/vhost.conf
    - /etc/nginx/conf.d/vhost.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./.s2i/bin/
    - $STI_SCRIPTS_PATH
  - Name: user
    User: "1001"
  From:
    Image: oshanrube/base-nginx
  Name: ""
  Platform: ""
  SourceCode: FROM oshanrube/base-nginx
