MetaArgs:
- DefaultValue: latest
  Key: TAG
  ProvidedValue: null
  Value: latest
Stages:
- BaseName: cnarf/buster:${TAG}
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"cnarf@charline"'
    Name: label
  - Labels:
    - Key: description
      Value: '"The graal?"'
    Name: label
  - CmdLine:
    - apt-get install --no-install-recommends -y     make     g++-8 libstdc++6-8-dbg
      gcc-8-locales libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg
      libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg     lcov     curl ca-certificates
      && apt-get clean && /root/finalize.sh;
    Name: run
    PrependShell: true
  From:
    Image: cnarf/buster:${TAG}
  Name: ""
  Platform: ""
  SourceCode: FROM cnarf/buster:${TAG}
