MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: ashok.satyanarayana@gmail.com
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y build-essential    && apt-get install -y wget
    Name: run
    PrependShell: true
  - Env:
    - Key: REDIS_VERSION
      Value: 3.2.3
    Name: env
  - CmdLine:
    - wget --output-document redis-$REDIS_VERSION.tar.gz http://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xzf redis-$REDIS_VERSION.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - cd redis-$REDIS_VERSION && make
    Name: run
    PrependShell: true
  - CmdLine:
    - cd redis-$REDIS_VERSION && make install
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
