MetaArgs:
- DefaultValue: 2.6.5
  Key: RUBY_VERSION
  ProvidedValue: null
  Value: 2.6.5
Stages:
- As: build
  BaseName: ruby:${RUBY_VERSION}-alpine
  Commands:
  - CmdLine:
    - apk add   --no-cache   build-base git postgresql-dev curl python tzdata less
      bash nodejs yarn openssl
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/build   && addgroup -S www   && adduser -G www -S www   &&
      chown www:www /usr/src/build
    Name: run
    PrependShell: true
  - Name: user
    User: www
  - Name: workdir
    Path: /usr/src/build
  From:
    Image: ruby:${RUBY_VERSION}-alpine
  Name: build
  Platform: ""
  SourceCode: FROM ruby:${RUBY_VERSION}-alpine as build
