MetaArgs: null
Stages:
- BaseName: node:latest
  Commands:
  - Name: expose
    Ports:
    - "8081"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /src/package.json
  - CmdLine:
    - cd /src; npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /src
  - Name: workdir
    Path: /src
  - CmdLine:
    - ./node_modules/.bin/gulp build
    Name: run
    PrependShell: true
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:latest
  Name: ""
  Platform: ""
  SourceCode: FROM node:latest
