MetaArgs: null
Stages:
- BaseName: resin/rpi-raspbian:latest
  Commands:
  - Maintainer: Søren Schmidt Kriegbaum "comzone5@gmail.com"
    Name: maintainer
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-divert --local --rename --add /sbin/initctl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y locales dialog
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US en_US.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-reconfigure -f noninteractive locales
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "mysql-server-5.5 mysql-server/root_password password root123" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "mysql-server-5.5 mysql-server/root_password_again password root123" |
      debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "mysql-server-5.5 mysql-server/root_password seen true" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "mysql-server-5.5 mysql-server/root_password_again seen true" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apache2 php5 php5-gd php-xml-parser php5-intl php5-sqlite
      mysql-server-5.5 smbclient curl libcurl3 php5-mysql php5-curl bzip2 wget vim
      openssl ssl-cert sharutils
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - http://download.owncloud.org/community/owncloud-6.0.0a.tar.bz2
      | tar jx -C /var/www/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/apache2/ssl
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "test1"
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - resources/cfgmysql.sh
    - /tmp/
  - CmdLine:
    - chmod +x /tmp/cfgmysql.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /tmp/cfgmysql.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /tmp/cfgmysql.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - resources/001-owncloud.conf
    - /etc/apache2/sites-available/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - resources/000-default.conf
    - /etc/apache2/sites-available/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - resources/start.sh
    - /
  - CmdLine:
    - a2ensite 001-owncloud.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2ensite 000-default.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite ssl
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/owncloud
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /start.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: resin/rpi-raspbian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM resin/rpi-raspbian:latest
