MetaArgs: null
Stages:
- BaseName: ruby:2.2-jessie
  Commands:
  - Name: workdir
    Path: /app/
  - CmdLine:
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" >
      /etc/apt/sources.list.d/mongodb-org-3.6.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y         locales         mongodb-org         &&     rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile
    - /app/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile.lock
    - /app/
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - backup_mongodb.rb
    - /app/
  - CmdLine:
    - mkdir /out
    Name: run
    PrependShell: true
  - CmdLine:
    - ruby
    - /app/backup_mongodb.rb
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.2-jessie
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.2-jessie
