MetaArgs: null
Stages:
- BaseName: buildpack-deps:jessie
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Ioannis Poulakas <giannis.p@gmail.com>"'
    Name: label
  - CmdLine:
    - apt-get update && apt-get install -y     apt-transport-https     ca-certificates     curl     gnupg2     software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository     "deb [arch=amd64] https://download.docker.com/linux/debian     $(lsb_release
      -cs)     stable"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y     docker-ce     awscli
    Name: run
    PrependShell: true
  From:
    Image: buildpack-deps:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM buildpack-deps:jessie
