MetaArgs: null
Stages:
- BaseName: node:8
  Commands:
  - CmdLine:
    - mkdir -p /usr/src/Integarations
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/Integarations
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/Integarations
  - CmdLine:
    - WITH_SASL=0 npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - node
    - integrations.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:8
  Name: ""
  Platform: ""
  SourceCode: FROM node:8
