MetaArgs: null
Stages:
- BaseName: node:12-alpine
  Commands:
  - CmdLine:
    - apk add --no-cache --update    python     make     g++     git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /server
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package*.json
    - ./
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  - CmdLine:
    - npm
    - run
    - serve
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "3001"
  From:
    Image: node:12-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:12-alpine
