MetaArgs: null
Stages:
- BaseName: python:2
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /usr/src/app/
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y ca-certificates curl
    Name: run
    PrependShell: true
  - CmdLine:
    - gpg --keyserver pgp.mit.edu --recv-keys 7937DFD2AB06298B2293C3187D33FF9D0246406D
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_VERSION
      Value: 0.10.32
    Name: env
  - CmdLine:
    - curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"     &&
      curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc"     &&
      gpg --verify SHASUMS256.txt.asc     && grep " node-v$NODE_VERSION-linux-x64.tar.gz\$"
      SHASUMS256.txt.asc | sha256sum -c -     && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz"
      -C /usr/local --strip-components=1     && rm "node-v$NODE_VERSION-linux-x64.tar.gz"
      SHASUMS256.txt.asc
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g bower
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g grunt-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g karma
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /usr/src/app/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bower.json
    - /usr/src/app/
  - CmdLine:
    - bower install --config.interactive=false --allow-root
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /usr/src/app/
  - CmdLine:
    - grunt prebuild
    Name: run
    PrependShell: true
  - CmdLine:
    - grunt build
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - python ./manager.py $DB_1_PORT_27017_TCP_ADDR
    Name: cmd
    PrependShell: true
  From:
    Image: python:2
  Name: ""
  Platform: ""
  SourceCode: FROM python:2
