MetaArgs: null
Stages:
- BaseName: bitnami/minideb:jessie
  Commands:
  - Maintainer: rbravo@datiobd.com
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app/
    - /app/
  - CmdLine:
    - apt-get update && apt-get install -y python3 python-dev python3-dev python-pip
      libzookeeper-mt-dev     && pip install virtualenv     && mkdir -p /venv/     &&
      virtualenv -p /usr/bin/python$VERSION /venv     &&  /bin/bash -c "source /venv/bin/activate"     &&
      /venv/bin/pip install /app/lib/pymesos-0.2.13.tar.gz     && chmod +x /app/init.sh     &&
      apt-get clean -y &&     apt-get autoclean -y &&     apt-get autoremove -y &&     rm
      -rf /usr/share/locale/* &&     rm -rf /var/cache/debconf/*-old &&     rm -rf
      /var/lib/apt/lists/* &&     rm -rf /usr/share/doc/*
    Name: run
    PrependShell: true
  From:
    Image: bitnami/minideb:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM bitnami/minideb:jessie
