MetaArgs: null
Stages:
- As: build
  BaseName: golang
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/Kugelschieber/squadxml
  - Name: workdir
    Path: /go/src/github.com/Kugelschieber/squadxml
  - CmdLine:
    - "apt update && \tapt upgrade -y"
    Name: run
    PrependShell: true
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-s -w" main.go
    Name: run
    PrependShell: true
  From:
    Image: golang
  Name: build
  Platform: ""
  SourceCode: FROM golang AS build
- BaseName: alpine
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/Kugelschieber/squadxml
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - apk update &&     apk upgrade &&     apk add --no-cache &&     apk add ca-certificates
      &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /squadxml
    Name: run
    PrependShell: true
  - Env:
    - Key: SQUADXML_PATH
      Value: /squadxml
    Name: env
  - Env:
    - Key: SQUADXML_HOST
      Value: 0.0.0.0:80
    Name: env
  - Env:
    - Key: SQUADXML_DB_USER
      Value: user
    Name: env
  - Env:
    - Key: SQUADXML_DB_PASSWORD
      Value: password
    Name: env
  - Env:
    - Key: SQUADXML_DB_HOST
      Value: host
    Name: env
  - Env:
    - Key: SQUADXML_DB
      Value: db
    Name: env
  - Name: expose
    Ports:
    - "80"
  - Name: volume
    Volumes:
    - /squadxml
  - CmdLine:
    - /app/main
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
