MetaArgs: null
Stages:
- BaseName: node:4.2
  Commands:
  - Maintainer: Deni Bertovic <deni@denibertovic.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get -y --no-install-suggests install     pandoc     texlive-fonts-recommended     texlive-latex-base     texlive-latex-extra     texlive-latex-recommended
    Name: run
    PrependShell: true
  - Env:
    - Key: PID1_VERSION
      Value: 0.1.2.0
    Name: env
  - CmdLine:
    - curl -sSL "https://github.com/fpco/pid1/releases/download/v${PID1_VERSION}/pid1-${PID1_VERSION}-linux-x86_64.tar.gz"
      | tar xzf - -C /usr/local &&     chown root:root /usr/local/sbin &&     chown
      root:root /usr/local/sbin/pid1
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: REVEALJS_VERSION
      Value: 3.2.0
    Name: env
  - CmdLine:
    - wget https://github.com/hakimel/reveal.js/archive/$REVEALJS_VERSION.tar.gz     -O
      /tmp/$REVEALJS_VERSION.tar.gz 2> /dev/null     && mkdir /opt/slides     && tar
      zxvf /tmp/$REVEALJS_VERSION.tar.gz -C /opt/slides     && rm /tmp/$REVEALJS_VERSION.tar.gz     &&
      mv /opt/slides/reveal.js-$REVEALJS_VERSION /opt/slides/reveal.js
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/slides/reveal.js && mkdir -p /opt/slides/reveal.js/md
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/slides/reveal.js
  - CmdLine:
    - npm install -g grunt-cli && npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - 'sed -i Gruntfile.js -e ''s/port: port,/port: port, hostname: "",/'''
    Name: run
    PrependShell: true
  - CmdLine:
    - grunt --force
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - index.html
    - /opt/slides/reveal.js/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - example/md
    - /opt/slides/reveal.js/md
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pandoc_templates/default.revealjs
    - /usr/share/pandoc/data/templates/default.revealjs
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pandoc_templates/default.latex
    - /usr/share/pandoc/data/templates/default.latex
  - Name: expose
    Ports:
    - "8000"
  - Name: expose
    Ports:
    - "35729"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /usr/local/bin/entrypoint.sh
  - CmdLine:
    - /usr/local/bin/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - grunt
    - serve
    Name: cmd
    PrependShell: false
  From:
    Image: node:4.2
  Name: ""
  Platform: ""
  SourceCode: FROM node:4.2
