MetaArgs: null
Stages:
- BaseName: crashsystems/node
  Commands:
  - CmdLine:
    - apt-get -y install git-core
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g hipache
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /config
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /build
  - CmdLine:
    - /build/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: crashsystems/node
  Name: ""
  Platform: ""
  SourceCode: FROM crashsystems/node
