MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: GIT_SHA1
    Name: arg
    Value: null
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.git-sha1
      Value: $GIT_SHA1
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - pwd_file
    - /
  - Chown: ""
    Name: add
    SourcesAndDest:
    - build.files
    - /
  - Chown: ""
    Name: add
    SourcesAndDest:
    - build.env
    - /
  - CmdLine:
    - echo ${BUILD_DATE}   > blubb  && echo ${GIT_SHA1}    >> blubb
    Name: run
    PrependShell: true
  - CmdLine:
    - cat
    - blubb
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
