MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -yq --no-install-recommends     apt-utils     curl     apache2     libapache2-mod-php7.2     php7.2-cli     php7.2-json     php7.2-curl     php7.2-fpm     php7.2-gd     php7.2-ldap     php7.2-mbstring     php7.2-mysql     php7.2-soap     php7.2-sqlite3     php7.2-xml     php7.2-zip     php7.2-intl     php-imagick     &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://wordpress.org/latest.tar.gz
    - /var/www/html/
  - Env:
    - Key: APACHE_DOCUMENT_ROOT
      Value: /var/www/html/wordpress/
    Name: env
  - CmdLine:
    - sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf
      /etc/apache2/conf-available/*.conf
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/html
  - CmdLine:
    - tar -xzf latest.tar.gz   && rm latest.tar.gz && rm index.html
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
