MetaArgs: null
Stages:
- BaseName: httpd:2.4.18
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - v0.3.0.tar.gz
    - /usr/local/
  - CmdLine:
    - cd /usr/local/letsencrypt-0.3.0   && ./letsencrypt-auto; exit 0
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /root/.local/share/letsencrypt/bin/letsencrypt /usr/local/bin/letsencrypt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cert-sync
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - httpd-foreground
    - /usr/local/bin/
  - Env:
    - Key: cert_delay
      Value: "1"
    Name: env
  From:
    Image: httpd:2.4.18
  Name: ""
  Platform: ""
  SourceCode: FROM httpd:2.4.18
