MetaArgs: null
Stages:
- BaseName: haproxy:latest
  Commands:
  - Maintainer: kuji
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install rsyslog -y &&     sed -i 's/#$ModLoad imudp/$ModLoad
      imudp/g' /etc/rsyslog.conf &&     sed -i 's/#$UDPServerRun 514/$UDPServerRun
      514/g' /etc/rsyslog.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update     && apt-get install -y   vim                                   net-tools                             dnsutils                              curl                                  wget          &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - rsyslog/haproxy.conf
    - /etc/rsyslog.d
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ll
    - /usr/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - haproxy -f /usr/local/etc/haproxy/haproxy.cfg -Ds -dr -V -d
    Name: cmd
    PrependShell: false
  From:
    Image: haproxy:latest
  Name: ""
  Platform: ""
  SourceCode: FROM haproxy:latest
