MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Env:
    - Key: KAFKA_USER
      Value: kafka
    - Key: KAFKA_DATA_DIR
      Value: /var/lib/kafka/data
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-openjdk-amd64
    - Key: KAFKA_HOME
      Value: /opt/kafka
    - Key: PATH
      Value: $PATH:/opt/kafka/bin
    Name: env
  - Key: KAFKA_VERSION
    Name: arg
    Value: 2.1.1
  - Key: KAFKA_DIST
    Name: arg
    Value: kafka_2.11-2.1.1
  - CmdLine:
    - "set -x     && apt-get update     && apt-get install -y openjdk-8-jre-headless
      wget \t&& wget -q \"http://www.apache.org/dist/kafka/$KAFKA_VERSION/$KAFKA_DIST.tgz\"
      \    && wget -q \"http://www.apache.org/dist/kafka/$KAFKA_VERSION/$KAFKA_DIST.tgz.asc\"
      \    && wget -q \"http://kafka.apache.org/KEYS\"     && export GNUPGHOME=\"$(mktemp
      -d)\"     && gpg --import KEYS     && gpg --batch --verify \"$KAFKA_DIST.tgz.asc\"
      \"$KAFKA_DIST.tgz\"     && tar -xzf \"$KAFKA_DIST.tgz\" -C /opt     && rm -r
      \"$GNUPGHOME\" \"$KAFKA_DIST.tgz\" \"$KAFKA_DIST.tgz.asc\""
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - log4j.properties
    - /opt/$KAFKA_DIST/config/
  - CmdLine:
    - set -x     && ln -s /opt/$KAFKA_DIST $KAFKA_HOME     && useradd $KAFKA_USER     &&
      [ `id -u $KAFKA_USER` -eq 1000 ]     && [ `id -g $KAFKA_USER` -eq 1000 ]     &&
      mkdir -p $KAFKA_DATA_DIR     && chown -R "$KAFKA_USER:$KAFKA_USER"  /opt/$KAFKA_DIST     &&
      chown -R "$KAFKA_USER:$KAFKA_USER"  $KAFKA_DATA_DIR
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
