MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - CmdLine:
    - apk --update add wget ca-certificates && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/lair-framework/drone-nessus/releases/download/v2.2.1/drone-nessus_linux_amd64     &&
      mv drone-nessus_linux_amd64 /usr/bin/drone-nessus     && chmod +x /usr/bin/drone-nessus
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/drone-nessus
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -h
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
