MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: Jesse Reynolds @jessereynolds
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y     git     curl     build-essential     ruby1.9.1-full     libssl-dev     libreadline-dev     libxslt1-dev     libxml2-dev     libcurl4-openssl-dev     zlib1g-dev     libexpat1-dev     libicu-dev     cmake
    Name: run
    PrependShell: true
  - CmdLine:
    - git config --global user.email "docker@flapjack.io" &&     git config --global
      user.name "Flapjack Docker Packager"
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install bundler --no-ri --no-rdoc
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -o /tmp/go1.3.1.linux-amd64.tar.gz https://storage.googleapis.com/golang/go1.3.1.linux-amd64.tar.gz
      &&     tar -C /usr/local -xzf /tmp/go1.3.1.linux-amd64.tar.gz &&     echo "PATH=$PATH:/usr/local/go/bin"
      | tee /etc/profile.d/go.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - git config --global user.email "docker@flapjack.io" &&     git config --global
      user.name "Flapjack Docker Packager"
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/flapjack/omnibus-flapjack.git &&     cd omnibus-flapjack
      &&     bundle install --binstubs
    Name: run
    PrependShell: true
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
