MetaArgs: null
Stages:
- BaseName: library/python:3.5.3
  Commands:
  - Maintainer: Tomasz Szymański <tomasz.szymanski@stxnext.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -y && apt-get install --no-install-recommends -y -q curl python
      build-essential git ca-certificates
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_7.x -o nodesource_setup.sh && bash
      nodesource_setup.sh && apt-get install nodejs && npm install -g yarn
    Name: run
    PrependShell: true
  From:
    Image: library/python:3.5.3
  Name: ""
  Platform: ""
  SourceCode: FROM library/python:3.5.3
