MetaArgs: null
Stages:
- As: mc
  BaseName: minio/mc
  Commands: null
  From:
    Image: minio/mc
  Name: mc
  Platform: ""
  SourceCode: FROM minio/mc as mc
- BaseName: minio/minio
  Commands:
  - Chown: ""
    From: mc
    Name: copy
    SourcesAndDest:
    - /usr/bin/mc
    - /usr/bin/mc
  From:
    Image: minio/minio
  Name: ""
  Platform: ""
  SourceCode: FROM minio/minio
