MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Łukasz Górski <l.gorski@trojmiasto.pl>"'
    Name: label
  - CmdLine:
    - apt-get update       && apt-get install -y         software-properties-common         unzip         curl         apt-transport-https       &&
      apt-key adv --fetch-keys https://pkg.trojmiasto.pl/public.key       && echo
      'deb [arch=amd64] https://pkg.trojmiasto.pl/ xenial main' > /etc/apt/sources.list.d/pkg-trojmiasto-pl.list       &&
      apt-get update       && apt install -y         ripgrep         jq         netcat-openbsd       &&
      rm -r /var/lib/apt/lists/*       && rm -r /var/cache/apt/archives/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ajax-count
    - /usr/local/bin/ajax-count
  - Name: shell
    Shell:
    - /bin/bash
    - -c
  - CmdLine:
    - /usr/local/bin/ajax-count
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
