MetaArgs: null
Stages:
- BaseName: docker:17.05
  Commands:
  - Maintainer: Viktor Farcic <viktor@farcic.com>
    Name: maintainer
  - Key: '"version'
    Name: arg
    Value: 0.1.0-dev"
  - Key: '"build_date'
    Name: arg
    Value: unknown"
  - Key: '"commit_hash'
    Name: arg
    Value: unknown"
  - Key: '"vcs_url'
    Name: arg
    Value: unknown"
  - Key: '"vcs_branch'
    Name: arg
    Value: unknown"
  - Labels:
    - Key: org.label-schema.vendor
      Value: '"vfarcic"'
    - Key: org.label-schema.name
      Value: '"jenkins-swarm-agent"'
    - Key: org.label-schema.description
      Value: '"Jenkins agent based on the Swarm plugin"'
    - Key: org.label-schema.usage
      Value: '"/src/README.md"'
    - Key: org.label-schema.url
      Value: '"https://github.com/vfarcic/docker-jenkins-slave-dind/blob/master/README.md"'
    - Key: org.label-schema.vcs-url
      Value: $vcs_url
    - Key: org.label-schema.vcs-branch
      Value: $vcs_branch
    - Key: org.label-schema.vcs-ref
      Value: $commit_hash
    - Key: org.label-schema.version
      Value: $version
    - Key: org.label-schema.schema-version
      Value: '"1.0"'
    - Key: org.label-schema.build-date
      Value: $build_date
    Name: label
  - Env:
    - Key: '"PATH'
      Value: /root/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - Key: '"SWARM_CLIENT_VERSION'
      Value: 3.3"
    - Key: '"DOCKER_COMPOSE_VERSION'
      Value: 1.13.0"
    - Key: '"COMMAND_OPTIONS'
      Value: '"'
    - Key: '"USER_NAME_SECRET'
      Value: '"'
    - Key: '"PASSWORD_SECRET'
      Value: '"'
    Name: env
  - CmdLine:
    - adduser -G root -D jenkins  && apk --update --no-cache add openjdk8-jre python
      py-pip git openssl  && wget -q https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/${SWARM_CLIENT_VERSION}/swarm-client-${SWARM_CLIENT_VERSION}.jar
      -P /home/jenkins/  && pip install docker-compose
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache bash sudo curl
    Name: run
    PrependShell: true
  - CmdLine:
    - export CLOUDSDK_CORE_DISABLE_PROMPTS=1  && curl https://sdk.cloud.google.com
      | bash  && /root/google-cloud-sdk/bin/gcloud --quiet components update kubectl  &&
      apk add --no-cache sudo  && curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
      | bash
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: docker:17.05
  Name: ""
  Platform: ""
  SourceCode: FROM docker:17.05
