MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Adelin <eclipse.magick@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B42317285E12C7CF
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://apt.tvheadend.org/unstable/ jessie main" > /etc/apt/sources.list.d/tvheadend.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apt-utils debconf-utils debhelper libhdhomerun1 libnfs4 hdhomerun-config
      xmltv-util dvb-apps
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "tvheadend tvheadend/admin_password password 1234" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "tvheadend tvheadend/admin_username string admin" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y tvheadend
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -f && apt-get remove --purge -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /home/hts/videos && chown -R hts:video /home/hts/videos
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9981"
    - "9982"
  - Name: volume
    Volumes:
    - /home/hts/videos
  - CmdLine:
    - /usr/bin/tvheadend
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -C
    - -u
    - hts
    - -g
    - hts
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
