MetaArgs: null
Stages:
- BaseName: alpine:3.11.2
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"github.com/robertbeal"'
    Name: label
  - CmdLine:
    - apk add --no-cache         nodejs         nodejs-npm       && npm install -g
      markdown-link-check       && adduser -D -s /bin/false -H tester
    Name: run
    PrependShell: true
  - Name: user
    User: tester
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - CmdLine:
    - markdown-link-check
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.11.2
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.11.2
