MetaArgs: null
Stages:
- BaseName: sonarqube:latest
  Commands:
  - Maintainer: Philipp Klautke "philipp.klautke@makonis.de"
    Name: maintainer
  - Env:
    - Key: PLUGIN_DOWNLOAD_LOCATION
      Value: /opt/plugins-download
    Name: env
  - CmdLine:
    - mkdir -p $PLUGIN_DOWNLOAD_LOCATION
    Name: run
    PrependShell: true
  - Name: workdir
    Path: ${PLUGIN_DOWNLOAD_LOCATION}
  - CmdLine:
    - wget https://sonarsource.bintray.com/Distribution/sonar-csharp-plugin/sonar-csharp-plugin-6.4.1.3596.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://sonarsource.bintray.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-3.2.0.5506.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/kalidasya/sonar-css-plugin/releases/download/3.1/sonar-css-plugin-3.1.jar
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /opt/docker-entrypoint.sh
  - CmdLine:
    - chmod +x /opt/docker-entrypoint.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: ${SONARQUBE_HOME}
  - CmdLine:
    - /opt/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: sonarqube:latest
  Name: ""
  Platform: ""
  SourceCode: FROM sonarqube:latest
