MetaArgs: null
Stages:
- BaseName: streamsets/datacollector:3.5.0
  Commands:
  - Maintainer: Rob Wetzeler <rob.wetzeler@gmail.com>
    Name: maintainer
  - Key: SDC_USER
    Name: arg
    Value: sdc
  - Key: ADD_LIBS
    Name: arg
    Value: streamsets-datacollector-jdbc-lib,streamsets-datacollector-apache-kafka_1_0-lib,streamsets-datacollector-azure-lib,streamsets-datacollector-elasticsearch_5-lib,streamsets-datacollector-jython_2_7-lib,streamsets-datacollector-redis-lib
  - Env:
    - Key: ADD_LIBS
      Value: $ADD_LIBS
    Name: env
  - Name: user
    User: root
  - CmdLine:
    - apk --no-cache add bash   curl   krb5-libs   libstdc++   sed   cifs-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/run sha1sum --status/run sha1sum -s/g'  ${SDC_DIST}/libexec/_stagelibs
    Name: run
    PrependShell: true
  - CmdLine:
    - if [[ ! -z $ADD_LIBS ]]; then $SDC_DIST/bin/streamsets stagelibs -install=$ADD_LIBS
      ; fi
    Name: run
    PrependShell: true
  - Env:
    - Key: SDC_DATA
      Value: /usr/share/streamsets/data
    Name: env
  - Env:
    - Key: REMOTE_SHARE
      Value: /mnt/remoteshare
    Name: env
  - CmdLine:
    - mkdir -p ${STREAMSETS_LIBRARIES_EXTRA_DIR}/streamsets-datacollector-jdbc-lib/lib   &&
      mkdir -p ${SDC_DATA}   && mkdir -p ${REMOTE_SHARE}
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i  "/xmail.from.address=/c\xmail.from.address=streamsets_alert" /etc/sdc/sdc.properties   &&
      sed -i -e 's/localhost/apps-outbound.emailserver.com/1' /etc/sdc/sdc.properties
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R "${SDC_USER}:${SDC_USER}" "${STREAMSETS_LIBRARIES_EXTRA_DIR}"   "${SDC_CONF}"   "${SDC_DATA}"   "${SDC_LOG}"   "${REMOTE_SHARE}"   "${SDC_RESOURCES}"   "/etc/hostname"   "${SDC_DIST}"
    Name: run
    PrependShell: true
  - CmdLine:
    - if [[ ! -z $COPY_CONFIG ]]; then cp ${COPY_CONFIG} /etc/sdc; fi
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&   curl -O -L "https://raw.github.com/rwetzeler/streamsets-dockerfile/master/jdbc_drivers/mssql-jdbc-7.0.0.jre10.jar"
      &&   mv mssql-jdbc-7.0.0.jre10.jar "${STREAMSETS_LIBRARIES_EXTRA_DIR}/streamsets-datacollector-jdbc-lib/lib"
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&   curl -O -L "https://raw.github.com/rwetzeler/streamsets-dockerfile/master/jdbc_drivers/dremio-jdbc-driver-3.1.1.jar"
      &&   mv dremio-jdbc-driver-3.1.1.jar "${STREAMSETS_LIBRARIES_EXTRA_DIR}/streamsets-datacollector-jdbc-lib/lib"
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&   curl -O -L "https://raw.github.com/rwetzeler/streamsets-dockerfile/master/jdbc_drivers/postgres-42.2.5.jre7.jar"
      &&   mv postgres-42.2.5.jre7.jar "${STREAMSETS_LIBRARIES_EXTRA_DIR}/streamsets-datacollector-jdbc-lib/lib"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - CmdLine:
    - chmod o+x /docker-entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "18630"
  - Name: user
    User: ${SDC_USER}
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - dc
    - -exec
    Name: cmd
    PrependShell: false
  From:
    Image: streamsets/datacollector:3.5.0
  Name: ""
  Platform: ""
  SourceCode: FROM streamsets/datacollector:3.5.0
