MetaArgs: null
Stages:
- BaseName: bzohdy/sdkman:centos-jdk7
  Commands:
  - Maintainer: bzohdy
    Name: maintainer
  - CmdLine:
    - "source \"$SDKMAN_DIR/bin/sdkman-init.sh\" \t&& sdk install groovy \t&& sdk
      flush temp \t&& sdk flush archives;"
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: bzohdy/sdkman:centos-jdk7
  Name: ""
  Platform: ""
  SourceCode: FROM bzohdy/sdkman:centos-jdk7
