MetaArgs: null
Stages:
- BaseName: node:8
  Commands:
  - CmdLine:
    - mkdir -p /server
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /server
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /server
  - CmdLine:
    - npm install -g -s --no-progress yarn &&     yarn &&     yarn install &&     yarn
      cache clean
    Name: run
    PrependShell: true
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: node:8
  Name: ""
  Platform: ""
  SourceCode: FROM node:8
