MetaArgs: null
Stages:
- BaseName: haproxy:alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Meik Minks <mminks@inox.io>"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  From:
    Image: haproxy:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM haproxy:alpine
