MetaArgs: null
Stages:
- BaseName: ppschweiz/wordpress
  Commands:
  - Env:
    - Key: CIVICRM_VERSION
      Value: 4.6.16
    Name: env
  - CmdLine:
    - apt-get remove -y php5-xcache
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -SL https://download.civicrm.org/civicrm-${CIVICRM_VERSION}-wordpress.zip
      > /civicrm-wordpress.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apache2
    - -DFOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: ppschweiz/wordpress
  Name: ""
  Platform: ""
  SourceCode: FROM ppschweiz/wordpress
