MetaArgs: null
Stages:
- BaseName: aviata/ubuntu-java8
  Commands:
  - CmdLine:
    - date -u +"%Y-%m-%d %H:%M%S?" && wget -q http://mirrors.sonic.net/apache/storm/apache-storm-0.9.4/apache-storm-0.9.4.tar.gz
      -O tmp.gz && tar -xzf tmp.gz -C /opt
    Name: run
    PrependShell: true
  - Env:
    - Key: STORM_HOME
      Value: /opt/apache-storm-0.9.4
    Name: env
  - Env:
    - Key: SUPER_CONFIG
      Value: /etc/supervisor/supervisord.conf
    Name: env
  - CmdLine:
    - date -u +"%Y-%m-%d %H:%M%S?" && groupadd storm; useradd --gid storm --home-dir
      /home/storm --create-home --shell /bin/bash storm; chown -R storm:storm $STORM_HOME;
      mkdir /var/log/storm ; chown -R storm:storm /var/log/storm
    Name: run
    PrependShell: true
  - CmdLine:
    - date -u +"%Y-%m-%d %H:%M%S?" && rm -rf /usr/bin/storm && ln -s $STORM_HOME/bin/storm
      /usr/bin/storm
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - storm.yaml
    - $STORM_HOME/conf/storm.yaml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - cluster.xml
    - $STORM_HOME/logback/cluster.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config-supervisord.sh
    - /usr/bin/config-supervisord.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start-supervisor.sh
    - /usr/bin/start-supervisor.sh
  - CmdLine:
    - date -u +"%Y-%m-%d %H:%M%S?" && mkdir -p "$(dirname "$SUPER_CONFIG")" && echo
      [supervisord] | tee -a /etc/supervisor/supervisord.conf ; echo nodaemon=true
      | tee -a /etc/supervisor/supervisord.conf
    Name: run
    PrependShell: true
  From:
    Image: aviata/ubuntu-java8
  Name: ""
  Platform: ""
  SourceCode: FROM aviata/ubuntu-java8
