MetaArgs: null
Stages:
- BaseName: alpine:3.2
  Commands:
  - CmdLine:
    - apk --update add openjdk7-jre
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/java
    - -version
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.2
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.2
