MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - VERSION
    - /app/VERSION
  - CmdLine:
    - apk add --no-cache curl &&     RELEASE_VERSION=$(cat /app/VERSION) &&     echo
      $RELEASE_VERSION &&     mkdir -p /app &&     wget -O /app/moni "https://github.com/adrian-gheorghe/moni/releases/download/${RELEASE_VERSION}/moni-linux"
      &&     chmod +x /app/moni &&     cp /app/moni /usr/local/bin/moni
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sample.docker.config.yml
    - /app/config.yml
  - Env:
    - Key: CONFIG_PATH
      Value: /app/config.yml
    Name: env
  - CmdLine:
    - sh
    - -c
    - moni --config ${CONFIG_PATH}
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
