MetaArgs: null
Stages:
- BaseName: node:10.14.0-alpine
  Commands:
  - CmdLine:
    - set -ex;     adduser -D codewarrior;     ln -s /home/codewarrior /workspace;
    Name: run
    PrependShell: true
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: warn
    Name: env
  - Chown: codewarrior:codewarrior
    From: ""
    Name: copy
    SourcesAndDest:
    - rootfs/workspace/solidity/package.json
    - /workspace/solidity/package.json
  - Chown: codewarrior:codewarrior
    From: ""
    Name: copy
    SourcesAndDest:
    - rootfs/workspace/solidity/package-lock.json
    - /workspace/solidity/package-lock.json
  - CmdLine:
    - set -ex;     apk add --no-cache --virtual .build-deps         su-exec         bash         build-base         git         python     ;     cd
      /workspace/solidity;     su-exec codewarrior npm install;     apk del --purge
      .build-deps;     rm -rf /var/cache/apk/* /tmp/* /home/codewarrior/.npm;
    Name: run
    PrependShell: true
  - Name: user
    User: codewarrior
  - Chown: codewarrior:codewarrior
    From: ""
    Name: copy
    SourcesAndDest:
    - rootfs/workspace/solidity
    - /workspace/solidity
  - Name: workdir
    Path: /workspace/solidity
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - CmdLine:
    - set -ex;     npx truffle test;     rm contracts/*.sol;     rm test/*.js;
    Name: run
    PrependShell: true
  From:
    Image: node:10.14.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10.14.0-alpine
