MetaArgs: null
Stages:
- BaseName: python:2.7-alpine3.7
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"tom@thomaslorentsen.co.uk"'
    Name: label
  - CmdLine:
    - pip install --no-cache-dir todoist-python
    Name: run
    PrependShell: true
  From:
    Image: python:2.7-alpine3.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7-alpine3.7
