MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - Env:
    - Key: TINI_VERSION
      Value: v0.9.0
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini
    - /tini
  - CmdLine:
    - chmod +rx /tini
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.sh
    - /tmp/install.sh
  - CmdLine:
    - sh -e /tmp/install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US:en
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - curl -O https://bootstrap.pypa.io/get-pip.py &&     python3 get-pip.py &&     rm
      get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install numpy>=1.11.0
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install scipy>=0.17.0
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /tmp/requirements.txt
  - CmdLine:
    - pip3 install -r /tmp/requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --upgrade git+git://github.com/lefant/hyperopt.git
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install git+git://github.com/msmbuilder/osprey.git
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
