MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y wget &&     wget http://dl.ubnt.com/unifi/5.5.20/unifi_sysvinit_all.deb
      &&     apt-get install -y ./unifi_sysvinit_all.deb &&     rm unifi_sysvinit_all.deb
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/unifi
  - Name: expose
    Ports:
    - 10001/udp
    - 3478/udp
    - "6789"
    - "8080"
    - "8443"
    - "8843"
    - "8880"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /start.sh
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
