MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Daniel Weisser <daniel.weisser@gmail.com>"'
    Name: label
  - Labels:
    - Key: Description
      Value: '"Docker Container for generating documentation with docToolchain"'
    Name: label
  - CmdLine:
    - apt-get -qq update && apt-get install -qq -y apt-transport-https ca-certificates
      curl software-properties-common git graphviz openjdk-8-jdk gradle
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --recursive https://github.com/docToolchain/docToolchain.git &&       cd
      docToolchain &&       rm -rf .git &&       rm -rf resources/asciidoctor-reveal.js/.git
      &&       rm -rf resources/reveal.js/.git
    Name: run
    PrependShell: true
  - CmdLine:
    - update-java-alternatives -s java-1.8.0-openjdk-amd64
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
