MetaArgs: null
Stages:
- BaseName: redmine:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends                 gcc                 libmagickcore-dev                 libmagickwand-dev                 libmysqlclient-dev                 libpq-dev                 libsqlite3-dev                 make                 patch         &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - rails
    - server
    - -b
    - 0.0.0.0
    Name: cmd
    PrependShell: false
  From:
    Image: redmine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM redmine:latest
