MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - echo "Hallo world (built by Docker Hub). New version." > hallo.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "SHA-256: $(sha256sum hallo.txt)"'
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
