MetaArgs: null
Stages:
- BaseName: ufoym/deepo:all-jupyter
  Commands:
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - "pip install \tjupyterlab \tpymc3 \tstatsmodels \tplotnine \tseaborn \tbambi"
    Name: run
    PrependShell: true
  From:
    Image: ufoym/deepo:all-jupyter
  Name: ""
  Platform: ""
  SourceCode: FROM ufoym/deepo:all-jupyter
