MetaArgs: null
Stages:
- BaseName: alpine:3.3
  Commands:
  - Maintainer: Erik Veld "erik@nauts.io"
    Name: maintainer
  - Env:
    - Key: CONSUL_ADDR
      Value: consul:8500
    Name: env
  - Env:
    - Key: CONSUL_PATH
      Value: vault
    Name: env
  - Env:
    - Key: CONSUL_SCHEME
      Value: http
    Name: env
  - Env:
    - Key: VAULT_VERSION
      Value: 0.5.1
    Name: env
  - Name: expose
    Ports:
    - "8200"
  - CmdLine:
    - apk add --update openssl     && wget -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip     &&
      wget -qO - https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS     |
      grep linux_amd64     | sha256sum -c     && unzip vault_${VAULT_VERSION}_linux_amd64.zip
      -d /usr/local/bin     && rm vault_${VAULT_VERSION}_linux_amd64.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/*.hcl
    - /etc/vault.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod 755 /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.3
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.3
