MetaArgs: null
Stages:
- BaseName: evarga/jenkins-slave
  Commands:
  - Maintainer: Aaron Walker <a.walker@base2services.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update -qq && apt-get install -qqy apt-transport-https ca-certificates
      git lxc iptables curl bison build-essential zlib1g-dev libssl-dev libxml2-dev
      git-core git-flow python-pip npm unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
      | bash &&     apt-get install -y --no-install-recommends git-lfs &&     git
      lfs install
    Name: run
    PrependShell: true
  - CmdLine:
    - 'curl -L https://opscode-omnibus-packages.s3.amazonaws.com/debian/6/x86_64/chefdk_0.10.0-1_amd64.deb
      > /tmp/chefdk_0.10.0-1_amd64.deb  &&   dpkg -i /tmp/chefdk_0.10.0-1_amd64.deb
      &&   export LC_CTYPE=en_US.UTF-8 &&   locale-gen en_US.UTF-8 &&   curl -L https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
      > /tmp/packer.zip &&   unzip -o /tmp/packer.zip -d /opt/packer &&   pip install
      awscli &&   ln -s /usr/bin/nodejs /usr/bin/node &&   npm install -g azure-cli
      &&   echo "jenkins ALL = NOPASSWD: ALL" > /etc/sudoers.d/jenkins &&   curl -sSL
      https://get.docker.com/ | sh'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - wrapdocker
    - /usr/local/bin/wrapdocker
  - CmdLine:
    - chmod +x /usr/local/bin/wrapdocker
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/docker
  - CmdLine:
    - usermod -a -G docker jenkins
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  - CmdLine:
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    Name: run
    PrependShell: true
  - CmdLine:
    - \curl -sSL https://get.rvm.io | bash -s stable --ruby
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Name: volume
    Volumes:
    - /home/jenkins
  - Name: expose
    Ports:
    - "22"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - jenkins-slave-startup.sh
    - /
  - CmdLine:
    - /jenkins-slave-startup.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: evarga/jenkins-slave
  Name: ""
  Platform: ""
  SourceCode: FROM evarga/jenkins-slave
