MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Bharat Parsiya <bnap00@gmail.com>
    Name: maintainer
  - CmdLine:
    - export GNUPGHOME="$(mktemp -d)"     && gpg --keyserver "hkp://pgp.mit.edu" --recv-keys
      '3050AC3CD2AE6F03'     && gpg -a --export --armor '3050AC3CD2AE6F03' | apt-key
      add -     && rm -r "$GNUPGHOME"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04/
      /" >> /etc/apt/sources.list     && apt-get update     && DEBIAN_FRONTEND=noninteractive
      apt-get       -o Dpkg::Options::="--force-confmiss"       -o Dpkg::Options::="--force-confold"       -y
      install nginx-custom nginx-ee     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt update && apt install -y curl nfs-common
    Name: run
    PrependShell: true
  - CmdLine:
    - "ln -sf /dev/stdout /var/log/nginx/access.log \t&& ln -sf /dev/stderr /var/log/nginx/error.log"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mountefs.sh
    - /usr/local/bin/run.sh
  - CmdLine:
    - chmod +x /usr/local/bin/run.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/run.sh
    Name: cmd
    PrependShell: false
  - CmdLine:
    - nginx
    - -g
    - daemon off;
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
