MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: devagorilla <devagorilla [at] gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get upgrade -q -y &&     apt-get install -q -y --no-install-recommends
      openjdk-7-jre-headless &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/modelergy/gitbucket/releases/download/3.9-COTS-alpha/gitbucket.war
    - /opt/gitbucket.war
  - CmdLine:
    - ln -s /gitbucket /root/.gitbucket
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /gitbucket
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "29418"
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
