MetaArgs: null
Stages:
- BaseName: openhab/openhab:latest
  Commands:
  - CmdLine:
    - apt-get update -y && apt-get install samba-common -y
    Name: run
    PrependShell: true
  From:
    Image: openhab/openhab:latest
  Name: ""
  Platform: ""
  SourceCode: FROM openhab/openhab:latest
