MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Baptiste Wicht
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y make build-essential && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /dll/build/
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - dll
    - /dll/src/
  - CmdLine:
    - export CXX=g++ && export LD=g++ && cd /dll/src && make && make install
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /dll/data
  - Env:
    - Key: CXX
      Value: g++
    Name: env
  - Env:
    - Key: LD
      Value: g++
    Name: env
  - Name: workdir
    Path: /dll/data
  - CmdLine:
    - dllp dll.conf auto
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
