MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"liuyang.z@hooowl.com"'
    Name: label
  - CmdLine:
    - buildDeps='build-essential wget unzip pkg-config bison libzip-dev git libpcre3
      libpcre3-dev zlib1g-dev';     set -x         && apt-get update         && apt-get
      install -y $buildDeps         && mkdir -p /data/softwares && cd /data/softwares         &&
      wget http://nginx.org/download/nginx-1.16.0.tar.gz && tar -xvf nginx-1.16.0.tar.gz         &&
      wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz && tar -xvf openssl-1.1.1c.tar.gz         &&
      git clone https://github.com/grahamedgecombe/nginx-ct.git         && cd nginx-1.16.0         &&
      ./configure --with-stream                         --with-http_v2_module                         --with-http_ssl_module                         --with-http_gzip_static_module                         --with-openssl=../openssl-1.1.1c                         --with-openssl-opt=enable-tls1_3                         --add-module=../nginx-ct         &&
      make -j6 && make install         && ln -s /usr/lib/x86_64-linux-gnu/libssl.so
      /usr/lib         && chown -R www-data:www-data /usr/local/nginx         && mkdir
      -p /usr/local/nginx/conf/conf.d         && rm -rf /data/softwares         &&
      apt-get purge -y --auto-remove build-essential wget unzip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /usr/local/nginx/conf/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.default.conf
    - /usr/local/nginx/conf/conf.d/default.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - autoRun.sh
    - /autoRun.sh
  - CmdLine:
    - chmod a+x /autoRun.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /autoRun.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
