MetaArgs: null
Stages:
- BaseName: golang:1.11
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Meik Minks <mminks@inoxio.de>"'
    Name: label
  - Name: workdir
    Path: /go/src/github.com/percona/mongodb_exporter
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - make build
    Name: run
    PrependShell: true
  From:
    Image: golang:1.11
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.11
- BaseName: quay.io/prometheus/busybox:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Alexey Palazhchenko <alexey.palazhchenko@percona.com>"'
    Name: label
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/percona/mongodb_exporter/bin/mongodb_exporter
    - /bin/mongodb_exporter
  - Name: expose
    Ports:
    - "9216"
  - CmdLine:
    - /bin/mongodb_exporter
    Name: entrypoint
    PrependShell: false
  From:
    Image: quay.io/prometheus/busybox:latest
  Name: ""
  Platform: ""
  SourceCode: FROM quay.io/prometheus/busybox:latest
