MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.12
  Commands:
  - Key: VERSION
    Name: arg
    Value: '"v0.9.5"'
  - Key: REPO
    Name: arg
    Value: '"https://github.com/restic/restic.git"'
  - Name: workdir
    Path: /src
  - CmdLine:
    - git clone --depth=1 "${REPO}" --branch=$(git ls-remote --tags --refs -q "${REPO}"
      "${VERSION}*" | tail -n 1 | awk -F/ '{ print $3 }') /src     && go run build.go
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.12 as builder
- BaseName: project0de/base:amzn2
  Commands:
  - CmdLine:
    - yum -y install mariadb postgresql curl wget     && yum -y update     && yum
      clean all     && rm -rf /var/cache/yum
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /src/restic
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod a+x /entrypoint.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - restic
    Name: cmd
    PrependShell: false
  From:
    Image: project0de/base:amzn2
  Name: ""
  Platform: ""
  SourceCode: FROM project0de/base:amzn2
