MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"oliver.krebs@me.com"'
    Name: label
  - Labels:
    - Key: Description
      Value: '"McMyAdmin"'
    Name: label
  - Labels:
    - Key: Vendor
      Value: '"olikre"'
    Name: label
  - Labels:
    - Key: Version
      Value: '"1.0"'
    Name: label
  - Env:
    - Key: JAVA_MEMORY
      Value: "2048"
    Name: env
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "25565"
  - Key: DEBIAN_FRONTEND
    Name: arg
    Value: '"noninteractive"'
  - CmdLine:
    - "apt-get update && \tapt-get -y upgrade && \tapt-get -y install wget openjdk-8-jdk-headless
      unzip libgdiplus && \tapt-get clean && \trm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local
  - CmdLine:
    - "wget http://mcmyadmin.com/Downloads/etc.zip && \tunzip etc.zip && rm etc.zip"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/mcmyadmin
  - CmdLine:
    - "wget http://mcmyadmin.com/Downloads/MCMA2_glibc26_2.zip && \tunzip MCMA2_glibc26_2.zip
      && rm MCMA2_glibc26_2.zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /home/mcmyadmin/Minecraft &&     echo 'eula=true' > /home/mcmyadmin/Minecraft/eula.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - echo '#!/bin/sh' > /start.sh &&     echo '/home/mcmyadmin/MCMA2_Linux_x86_64
      +java.memory $JAVA_MEMORY' >> /start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - touch /home/mcmyadmin/McMyAdmin.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - /home/mcmyadmin/MCMA2_Linux_x86_64 -nonotice -updateonly
    Name: run
    PrependShell: true
  - CmdLine:
    - /home/mcmyadmin/MCMA2_Linux_x86_64 -configonly -setpass admin
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /home/mcmyadmin
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
