MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: INITRD
      Value: "No"
    Name: env
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install lsb-release -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install apache2
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install mysql-server
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install php libapache2-mod-php php-mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && dpkg-reconfigure
      -f noninteractive tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/run/mysqld
    Name: run
    PrependShell: true
  - CmdLine:
    - chown mysql:mysql /var/run/mysqld
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "[program:mysql]" > /etc/supervisor/conf.d/mysql.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "#command=/usr/bin/mysqld_safe" >> /etc/supervisor/conf.d/mysql.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "command=/usr/bin/mysqld_safe --skip-grant-tables" >> /etc/supervisor/conf.d/mysql.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "process_name = mysql" >> /etc/supervisor/conf.d/mysql.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "[program:apache]" > /etc/supervisor/conf.d/apache.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "command=/usr/sbin/apachectl -DFOREGROUND -k start" >> /etc/supervisor/conf.d/apache.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "process_name = apache" >> /etc/supervisor/conf.d/apache.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y autoclean && apt-get -y autoremove
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y purge $(dpkg --get-selections | grep deinstall | sed s/deinstall//g)
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/www/html
  - Name: volume
    Volumes:
    - /var/log/httpd
  - Name: volume
    Volumes:
    - /var/lib/mysql
  - Name: volume
    Volumes:
    - /var/log/mysql
  - Name: volume
    Volumes:
    - /etc/apache2
  - Chown: ""
    Name: add
    SourcesAndDest:
    - startup.sh
    - /root/startup.sh
  - CmdLine:
    - /bin/bash
    - /root/startup.sh
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "80"
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
