MetaArgs: null
Stages:
- BaseName: docker/compose:1.6.0
  Commands:
  - Maintainer: Subak Systems <info@subak.jp>
    Name: maintainer
  - CmdLine:
    - apk add --update bash
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - v1.yml
    - /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - v2.yml
    - /root/
  - CmdLine: null
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: docker/compose:1.6.0
  Name: ""
  Platform: ""
  SourceCode: FROM docker/compose:1.6.0
