MetaArgs: null
Stages:
- BaseName: ruby:2.5.0
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Géraud Willing <contact@geraudwilling.com>"'
    Name: label
  - CmdLine:
    - apt-get update &&     apt-get install -y --no-install-recommends apt-utils &&     apt-get
      -y install nodejs &&     apt-get -y clean  &&     apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone -b develop https://github.com/GeraudWilling/smashing-poc.git smashing
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r smashing && useradd --no-log-init -r -g smashing smashing     &&
      chown -R smashing:smashing /smashing
    Name: run
    PrependShell: true
  - Name: user
    User: smashing
  - Name: workdir
    Path: /smashing
  - Env:
    - Key: HOME
      Value: /smashing
    Name: env
  - CmdLine:
    - chmod u+x /smashing
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+w /smashing
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install bundler smashing
    Name: run
    PrependShell: true
  - CmdLine:
    - bundle install --path /smashing
    Name: run
    PrependShell: true
  - Env:
    - Key: PORT
      Value: "8080"
    Name: env
  - Name: expose
    Ports:
    - $PORT
  - CmdLine:
    - bundle exec puma -p $PORT
    Name: cmd
    PrependShell: true
  From:
    Image: ruby:2.5.0
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.0
