MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - CmdLine:
    - curl -sL https://rpm.nodesource.com/setup_10.x | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install yum install -y nodejs gcc-c++ make
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y epel-release
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y golang
    Name: run
    PrependShell: true
  - CmdLine:
    - go get github.com/thestrukture/IDE
    Name: run
    PrependShell: true
  - CmdLine:
    - go get github.com/cheikhshift/gos
    Name: run
    PrependShell: true
  - CmdLine:
    - cd root/go/src/github.com/thestrukture/IDE/ui ;npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8884"
  - CmdLine:
    - /root/go/bin/IDE
    - --headless
    - '&'
    - npm start
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -p
    - 80:8884
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
