MetaArgs: null
Stages:
- BaseName: debian:9.2
  Commands:
  - CmdLine:
    - apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get -yq install     calibre     curl     jq     python     wget   &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /anthology /data   && touch /data/.nogood
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /anthology
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - CmdLine:
    - /anthology/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:9.2
  Name: ""
  Platform: ""
  SourceCode: FROM debian:9.2
