MetaArgs: null
Stages:
- BaseName: python:3.5
  Commands:
  - Maintainer: Elliot Nunn <elliotnunn@fastmail.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - lzss.c
    - /
  - CmdLine:
    - gcc -O3 -Wall -std=c11 -o /usr/local/bin/lzss lzss.c && rm lzss.c
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*make'
    - '*dump'
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.py'
    - /usr/local/lib/python/
  - Env:
    - Key: PYTHONPATH
      Value: /usr/local/lib/python:$PYTHONPATH
    Name: env
  From:
    Image: python:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.5
