MetaArgs: null
Stages:
- BaseName: python:2.7
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5050"
  From:
    Image: python:2.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7
