MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Maintainer: Justin Thareja <justinthareja@gmail.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - src/package.json
  - CmdLine:
    - cd /src; npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /src
  - Env:
    - Key: PORT
      Value: "5000"
    Name: env
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Name: expose
    Ports:
    - $PORT
  - CmdLine:
    - node
    - src/app.js
    Name: cmd
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
