MetaArgs: null
Stages:
- BaseName: continuumio/miniconda3:latest
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - environment.yml
    - /
  - CmdLine:
    - conda update -n base conda -y && conda env update
    Name: run
    PrependShell: true
  - CmdLine:
    - 'curl -s https://api.github.com/repos/cdr/code-server/releases/latest | grep
      "browser_download_url.*linux-x64.tar.gz" | cut -d : -f 2,3 | tr -d \" | wget
      -qi - && tar -xzvf code-server* && chmod +x code-server*/code-server'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./code
    - /code
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: continuumio/miniconda3:latest
  Name: ""
  Platform: ""
  SourceCode: FROM continuumio/miniconda3:latest
