MetaArgs: null
Stages:
- BaseName: python:3.6.6
  Commands:
  - CmdLine:
    - pip install --no-cache-dir   kubernetes requests
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./job_killer.py
    - /tmp/job_killer.py
  - CmdLine:
    - python
    - -u
    - /tmp/job_killer.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:3.6.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6.6
