MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: '"Hiroki Takeyama"'
    Name: maintainer
  - CmdLine:
    - apt update && apt install -y tzdata;     apt clean;
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /run/sshd;     apt install -y openssh-server;     sed -i 's/^#\(PermitRootLogin\)
      .*/\1 yes/' /etc/ssh/sshd_config;     sed -i 's/^\(UsePAM yes\)/# \1/' /etc/ssh/sshd_config;     apt
      clean;
    Name: run
    PrependShell: true
  - CmdLine:
    - '{     echo ''#!/bin/bash -eu'';     echo ''ln -fs /usr/share/zoneinfo/${TZ}
      /etc/localtime'';     echo ''echo "root:${ROOT_PASSWORD}" | chpasswd'';     echo
      ''exec "$@"'';     } > /usr/local/bin/entry_point.sh;     chmod +x /usr/local/bin/entry_point.sh;'
    Name: run
    PrependShell: true
  - Env:
    - Key: TZ
      Value: Asia/Tokyo
    Name: env
  - Env:
    - Key: ROOT_PASSWORD
      Value: root
    Name: env
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - entry_point.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    - -e
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
