MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - apk add --update --no-cache ca-certificates          && apk add --no-cache --virtual
      .run-deps                 ffmpeg                 libmagic                 python3                 python3-dev                 py3-numpy                 py3-pillow                 libwebp                 libffi-dev                 openssl-dev                 git                 py3-yaml                 py3-requests                 gcc                 g++                 git
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex         && pip3 install --upgrade pip         && pip3 install pyqrcode         &&
      pip3 install efb-telegram-master         && pip3 install efb-wechat-slave         &&
      pip3 install ehforwarderbot         && pip3 install python-telegram-bot==11.1.0         &&
      pip3 install --upgrade git+https://github.com/littlecodersh/ItChat.git
    Name: run
    PrependShell: true
  - CmdLine:
    - ehforwarderbot
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
