MetaArgs: null
Stages:
- BaseName: openjdk:8-alpine
  Commands:
  - Env:
    - Key: SONAR_SCANNER_VERSION
      Value: "2.8"
    Name: env
  - CmdLine:
    - apk update && apk add --no-cache wget python perl valgrind &&     wget --no-check-certificate
      https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-${SONAR_SCANNER_VERSION}.zip
      &&     unzip sonar-scanner-${SONAR_SCANNER_VERSION} &&     cd /usr/bin && ln
      -s /sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner sonar-scanner &&     apk
      del wget
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cppcheck
    - /usr/bin/cppcheck
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cpplint_mod.py
    - /cpplint_mod.py
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cpplintReport2checkstyleReport.perl
    - /cpplintReport2checkstyleReport.perl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./cfg
    - /usr/bin/
  - CmdLine:
    - chmod +x /usr/bin/cppcheck
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run-scanner.sh
    - /usr/bin/run-scanner.sh
  From:
    Image: openjdk:8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-alpine
