MetaArgs: null
Stages:
- BaseName: webdevops/php-nginx:7.1
  Commands:
  - CmdLine:
    - apt-get -y update && apt-get install -y aptitude
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/
    - /opt/docker/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/.inputrc
    - /root/
  - CmdLine:
    - "/usr/local/bin/apt-install         acl         openjdk-7-jre         nodejs
      \        node-less         bash-completion         npm \t\t\t  vim"
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug-2.5.0
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/nodejs /usr/bin/node
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'alias sf="php app/console"' >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'alias sf3="php bin/console"' >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'if [ -f /etc/bash_completion ]; then . /etc/bash_completion; fi' >> ~/.bashrc
    Name: run
    PrependShell: true
  - Env:
    - Key: term
      Value: rxvt
    Name: env
  - Env:
    - Key: TERM
      Value: rxvt
    Name: env
  From:
    Image: webdevops/php-nginx:7.1
  Name: ""
  Platform: ""
  SourceCode: FROM webdevops/php-nginx:7.1
