MetaArgs: null
Stages:
- BaseName: redis:5.0-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - redis.conf
    - /usr/local/etc/redis/redis.conf
  - CmdLine:
    - redis-server
    - /usr/local/etc/redis/redis.conf
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "6379"
  From:
    Image: redis:5.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM redis:5.0-alpine
