MetaArgs: null
Stages:
- BaseName: ruby:2.6.2-alpine3.9
  Commands:
  - Env:
    - Key: DOCKER
      Value: "true"
    Name: env
  - Name: workdir
    Path: /app
  - CmdLine:
    - echo "export PATH=/app/bin:$PATH" >> ~/.profile
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --update   tzdata postgresql-client   libressl-dev gnupg libstdc++   less
      git g++ make   bash openssh-client   nodejs yarn vim tmux   postgresql-dev   grep
    Name: run
    PrependShell: true
  - Chown: ""
    From: registry.gitlab.com/cmc_system/cmc:latest
    Name: copy
    SourcesAndDest:
    - /usr/local/bundle
    - /usr/local/bundle
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - Gemfile.lock
    - ./
  - CmdLine:
    - bundle install --jobs $(nproc)
    Name: run
    PrependShell: true
  - Chown: ""
    From: registry.gitlab.com/cmc_system/cmc:latest
    Name: copy
    SourcesAndDest:
    - /app/node_modules
    - /app/node_modules
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - yarn.lock
    - package.json
    - ./
  - CmdLine:
    - yarn install
    Name: run
    PrependShell: true
  - Chown: ""
    From: registry.gitlab.com/cmc_system/cmc:latest
    Name: copy
    SourcesAndDest:
    - /app/public/assets
    - /app/public/assets
  - Chown: ""
    From: registry.gitlab.com/cmc_system/cmc:latest
    Name: copy
    SourcesAndDest:
    - /app/public/packs
    - /app/public/packs
  - Chown: ""
    From: registry.gitlab.com/cmc_system/cmc:latest
    Name: copy
    SourcesAndDest:
    - /app/tmp/cache/webpacker/
    - /app/tmp/cache/webpacker/
  - Chown: ""
    From: registry.gitlab.com/cmc_system/cmc:latest
    Name: copy
    SourcesAndDest:
    - /app/tmp/cache/assets/
    - /app/tmp/cache/assets/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./
  - CmdLine:
    - SECRET_KEY_BASE='9479a648d2fb'   DATABASE_URL=postgres://root:password@db%5Ftest/root   RAILS_ENV=production   bundle
      exec rake assets:precompile
    Name: run
    PrependShell: true
  - CmdLine:
    - bundle exec puma -C config/puma.rb
    Name: cmd
    PrependShell: true
  From:
    Image: ruby:2.6.2-alpine3.9
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.6.2-alpine3.9
