MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Maintainer: Tim Dettrick <t.dettrick@uq.edu.au>
    Name: maintainer
  - CmdLine:
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      &&   adduser -S -D -h /dev/null -s /sbin/nologin nghttpx &&   apk add --update
      nghttp2 python openssl ca-certificates &&   rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/nghttpx
    - --user=nghttpx
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
