MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: James Jones <velocity303@gmail.com>
    Name: maintainer
  - CmdLine:
    - echo 'deb http://download.videolan.org/pub/debian/stable/ /' >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb-src http://download.videolan.org/pub/debian/stable/ /' >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb http://archive.ubuntu.com/ubuntu trusty main multiverse' >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install --no-install-recommends -q -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O - http://download.videolan.org/pub/debian/videolan-apt.asc|sudo apt-key
      add -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install --no-install-recommends -q -y apache2 php5 php5-json curl php5-curl
      php5-mysql lame libvorbis-dev vorbis-tools flac libmp3lame-dev libavcodec-extra*
      libfaac-dev libtheora-dev libvpx-dev libav-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/www/*
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /var/tmp  && curl -sSL --insecure https://github.com/ampache/ampache/archive/3.7.0.tar.gz
      | tar xz  && mv /var/tmp/ampache-3.7.0/* /var/www/  && rm -rf /var/tmp/ampache-3.7.0  &&
      chown -R www-data:www-data /var/www/
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - 001-ampache.conf
    - /etc/apache2/sites-available/
  - CmdLine:
    - rm -rf /etc/apache2/sites-enabled/*
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /etc/apache2/sites-available/001-ampache.conf /etc/apache2/sites-enabled/
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /media
  - Name: volume
    Volumes:
    - /var/www/config
  - Name: volume
    Volumes:
    - /var/www/themes
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/sbin/apache2ctl
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
