MetaArgs: null
Stages:
- BaseName: scratch
  Commands:
  - Maintainer: Benoit Theunissen <benoit.theunissen@gmail.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - centos64.tar.xz
    - /
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
