MetaArgs: null
Stages:
- BaseName: pilchard/hive
  Commands:
  - Maintainer: pilchard <ludundun@126.com>
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Hive Dev"'
    Name: label
  - CmdLine:
    - yum install -y impala impala-server impala-shell impala-state-store impala-catalog
      &&     cp /usr/lib/hive/lib/mysql-connector-java.jar /usr/lib/impala/lib &&     yum
      autoremove -y
    Name: run
    PrependShell: true
  - CmdLine:
    - '"bash"'
    Name: cmd
    PrependShell: true
  From:
    Image: pilchard/hive
  Name: ""
  Platform: ""
  SourceCode: FROM pilchard/hive
