MetaArgs: null
Stages:
- BaseName: centos
  Commands:
  - Maintainer: Yongyu Lee <aleeyyu@gmail.com>
    Name: maintainer
  - Env:
    - Key: ACTIVATOR_VERSION
      Value: 1.2.10
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:/activator-$ACTIVATOR_VERSION-minimal
    Name: env
  - CmdLine:
    - yum update -y &&   yum install -y --nogpgcheck unzip java-1.7.0-openjdk-devel
      &&   yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sOS http://downloads.typesafe.com/typesafe-activator/$ACTIVATOR_VERSION/typesafe-activator-$ACTIVATOR_VERSION-minimal.zip
      &&   unzip typesafe-activator-$ACTIVATOR_VERSION-minimal.zip -d / &&   rm -f
      typesafe-activator-$ACTIVATOR_VERSION-minimal.zip
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: workdir
    Path: /app
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - activator
    - run
    Name: cmd
    PrependShell: false
  From:
    Image: centos
  Name: ""
  Platform: ""
  SourceCode: FROM centos
