MetaArgs: null
Stages:
- BaseName: maven:3.6.1-jdk-11
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/app/
  - Name: workdir
    Path: /usr/app
  - CmdLine:
    - mvn package
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - java
    - -jar
    - target/java-spring-boot-template-0.0.1-SNAPSHOT.jar
    Name: cmd
    PrependShell: false
  From:
    Image: maven:3.6.1-jdk-11
  Name: ""
  Platform: ""
  SourceCode: FROM maven:3.6.1-jdk-11
