MetaArgs: null
Stages:
- BaseName: krystalcode/f_fedora
  Commands:
  - CmdLine:
    - dnf -y install     emacs     the_silver_searcher     w3m     patch     patchutils     php-cli     ruby     ruby-devel     gcc     make     redhat-rpm-config     nmap
      &&     dnf -y clean all &&     gem install compass bootstrap-sass &&     printf
      '\n\n%s\n%s\n\n%s\n%s\n\n' '# Add silver searcher alias' 'alias ag="ag --color-path
      36 --color-match 32 --color-line-number '"'"'1;30'"'"'"' '# Sync eshell aliases'
      'alias | sed -E "s/^alias ([^=]+)='"'"'(.*)'"'"'$/alias \1 \2 \$*/g; s/'"'"'\\\'"'""'"'/'"'"'/g;"
      >~/.emacs.d/eshell/alias'  >> ~/.bashrc
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./.emacs
    - /root/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./.gitconfig
    - /root/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./.gitignore
    - /root/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./.sshconfig
    - /root/.ssh/config
  - CmdLine:
    - chmod 644 ~/.ssh/config
    Name: run
    PrependShell: true
  From:
    Image: krystalcode/f_fedora
  Name: ""
  Platform: ""
  SourceCode: FROM krystalcode/f_fedora
