MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Jennifer Reiter <jenniferreiter@invenshure.com>
    Name: maintainer
  - Env:
    - Key: FLYWHEEL
      Value: /flywheel/v0
    Name: env
  - CmdLine:
    - mkdir -p ${FLYWHEEL}
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - manifest.json
    - ${FLYWHEEL}
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run
    - ${FLYWHEEL}/run
  - CmdLine:
    - chmod +x ${FLYWHEEL}/run
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ismrmrd_raw.hdf5.tgz
    - ${FLYWHEEL}/ismrmrd_raw.hdf5.tgz
  - CmdLine:
    - /flywheel/v0/run
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
