MetaArgs: null
Stages:
- BaseName: php:7-apache
  Commands:
  - Maintainer: Alexander Hofbauer <hofbauer.alexander@gmail.com>
    Name: maintainer
  - Name: workdir
    Path: /var/www/html
  - Env:
    - Key: COMPOSER_ALLOW_SUPERUSER
      Value: "1"
    Name: env
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
      --filename=composer &&     apt-get update &&     apt-get install -y --no-install-recommends         git-core
      libxml2-dev libjpeg-dev libpng-dev libxpm-dev libxml2-dev libfreetype6-dev &&     a2enmod
      rewrite &&     docker-php-ext-configure gd --with-freetype-dir=/usr/include/
      --with-jpeg-dir=/usr/include/ &&     docker-php-ext-install -j$(nproc)         ctype         dom         gd         json         mbstring         session         simplexml         xml         zip
      &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /usr/src/* &&     composer
      create-project getgrav/grav ./grav 1.5.* --no-scripts &&     chmod 777 /var/www/
      -R &&     cd grav &&     bin/grav install &&     bin/gpm install -y admin devtools
      &&     chmod 777 /var/www/ -R &&     chown www-data:www-data -R /var/www/
    Name: run
    PrependShell: true
  From:
    Image: php:7-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7-apache
