MetaArgs: null
Stages:
- BaseName: archimg/base:2019.01.01
  Commands:
  - Maintainer: ChihChieh Huang <soem.hcc@gmail.com>
    Name: maintainer
  - CmdLine:
    - sed -i '/^#\[multilib\]$/!b;s/#//;n;s/#//' /etc/pacman.conf &&     echo 'Server
      = http://ftp.tku.edu.tw/Linux/ArchLinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -Syu --noconfirm &&     pacman --noconfirm -S pacman-contrib &&     pacman
      --noconfirm -S wget &&     rm -rf /usr/share/info/* &&     rm -rf /usr/share/man/*
      &&     rm -rf /usr/share/doc/* &&     find /. -name "*~" -type f -delete &&     bash
      -c "echo 'y' | pacman -Scc >/dev/null 2>&1" &&     paccache -rk0 >/dev/null
      2>&1 &&      rm -rf /var/lib/pacman/sync/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -Syy --noconfirm &&     pacman --noconfirm -S lib32-glibc lib32-zlib
      lib32-gcc-libs libxdamage libxxf86vm &&     pacman --noconfirm -S xorg-server
      mesa-libgl lib32-mesa-libgl &&     pacman --noconfirm            -S            nvidia-libgl            nvidia-utils            lib32-nvidia-utils            lib32-nvidia-libgl
      &&     rm -rf /usr/share/info/* &&     rm -rf /usr/share/man/* &&     rm -rf
      /usr/share/doc/* &&     find /. -name "*~" -type f -delete &&     bash -c "echo
      'y' | pacman -Scc >/dev/null 2>&1" &&     paccache -rk0 >/dev/null 2>&1 &&      rm
      -rf /var/lib/pacman/sync/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts/initialize-graphics
    - /usr/bin/initialize-graphics
  - CmdLine:
    - pacman -Syy --noconfirm &&     pacman --noconfirm -S                 inetutils                 libxv                 virtualgl                 lib32-virtualgl                 mesa-demos                 lib32-mesa-demos
      &&     mkdir /opt/VirtualGL &&     ln -s /usr/bin /opt/VirtualGL &&     rm -rf
      /usr/share/man/* &&     rm -rf /usr/share/doc/* &&     find /. -name "*~" -type
      f -delete &&     bash -c "echo 'y' | pacman -Scc >/dev/null 2>&1" &&     paccache
      -rk0 >/dev/null 2>&1 &&      rm -rf /var/lib/pacman/sync/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -Syy --noconfirm &&     pacman --noconfirm -S                 inetutils                 libxv                 virtualgl                 lib32-virtualgl                 mesa-demos                 lib32-libpulse                 lib32-alsa-plugins                 lib32-mesa-demos
      &&     pacman --noconfirm -S     cabextract     lib32-gnutls     lib32-mpg123     lib32-ncurses     p7zip     unzip     wine-mono     wine_gecko     wine
      &&     pacman --noconfirm -S samba --assume-installed python2 &&     curl -o
      winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
      &&     install -Dm755 winetricks /usr/bin/winetricks &&      rm winetricks &&     rm
      -rf /usr/share/info/* &&     rm -rf /usr/share/man/* &&     rm -rf /usr/share/doc/*
      &&     find /. -name "*~" -type f -delete &&     bash -c "echo 'y' | pacman
      -Scc >/dev/null 2>&1" &&     paccache -rk0 >/dev/null 2>&1 &&      rm -rf /var/lib/pacman/sync/*
    Name: run
    PrependShell: true
  - Key: uid
    Name: arg
    Value: "1000"
  - Key: gid
    Name: arg
    Value: "1000"
  - Key: audio_gid
    Name: arg
    Value: "92"
  - Key: user_gid
    Name: arg
    Value: "100"
  - CmdLine:
    - 'pacman -Syy --noconfirm &&     pacman --noconfirm -S sudo &&     echo "docker
      ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/docker &&     ( groupmod -g ${audio_gid}
      audio || groupadd -g ${audio_gid} audio ) &&     groupadd -g ${gid} docker &&     useradd
      -m -g docker -G audio docker'
    Name: run
    PrependShell: true
  - Name: user
    User: docker
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: true
  From:
    Image: archimg/base:2019.01.01
  Name: ""
  Platform: ""
  SourceCode: FROM archimg/base:2019.01.01
