MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Maintainer: Dmitry Prazdnichnov <dp@bambucha.org>
    Name: maintainer
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VERSION
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.version
      Value: $VERSION
    - Key: org.label-schema.vcs-url
      Value: https://github.com/bambocher/docker-syncthing-inotify
    - Key: org.label-schema.license
      Value: MIT
    - Key: org.label-schema.schema-version
      Value: "1.0"
    Name: label
  - Env:
    - Key: URL
      Value: github.com/syncthing/syncthing-inotify
    - Key: XDG_CONFIG_HOME
      Value: /
    - Key: GOPATH
      Value: /
    Name: env
  - CmdLine:
    - apk --no-cache add ca-certificates curl     && apk --no-cache --virtual build-dependencies
      add go godep git libc-dev     && git clone -b v$VERSION https://$URL /src/$URL     &&
      cd /src/$URL     && godep get     && cd /     && rm -rf /src /pkg     && apk
      del build-dependencies
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./entrypoint.sh
    - /
  - Name: user
    User: 1000:1000
  - Name: volume
    Volumes:
    - /syncthing
    - /mnt
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -target=http://syncthing:8384
    - -logflags=0
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
