MetaArgs: null
Stages:
- BaseName: golang:1.11
  Commands:
  - Name: workdir
    Path: /go/src/github.com/miguch/cloudgo
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get -d -v .
    Name: run
    PrependShell: true
  - CmdLine:
    - go build -v .
    Name: run
    PrependShell: true
  From:
    Image: golang:1.11
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.11
