MetaArgs: null
Stages:
- BaseName: mhart/alpine-node:6.3
  Commands:
  - Env:
    - Key: VERSION
      Value: "1.0"
    Name: env
  - Env:
    - Key: DOCKER_USER
      Value: '"dockerfront"'
    Name: env
  - Env:
    - Key: USR_LOCAL
      Value: /usr/local
    Name: env
  - Env:
    - Key: ENV_SHARED
      Value: $USR_LOCAL/share
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - $USR_LOCAL/package.json
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - npm-shrinkwrap.json
    - $USR_LOCAL/npm-shrinkwrap.json
  - CmdLine:
    - npm install -g gulp@3.9.0 &&   addgroup $DOCKER_USER &&   adduser -s /bin/sh
      -D -G $DOCKER_USER $DOCKER_USER &&   cd $USR_LOCAL &&   npm install &&   mkdir
      $ENV_SHARED/config &&   mkdir $ENV_SHARED/tasks &&   mkdir $ENV_SHARED/input
      &&   mkdir $ENV_SHARED/output
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - $ENV_SHARED/config
  - Name: volume
    Volumes:
    - $ENV_SHARED/tasks
  - Name: volume
    Volumes:
    - $ENV_SHARED/input
  - Name: volume
    Volumes:
    - $ENV_SHARED/output
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /root/entrypoint.sh
  - CmdLine:
    - chmod +x /root/entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: mhart/alpine-node:6.3
  Name: ""
  Platform: ""
  SourceCode: FROM mhart/alpine-node:6.3
