MetaArgs: null
Stages:
- BaseName: jenkins/jenkins:lts
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt-get update && apt-get --assume-yes install -qq -o=Dpkg::Use-Pty=0       build-essential       patch           git             libltdl7        maven           ruby-full       tzdata          zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "The date / time before timezone change ==] `date`"
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -vf /usr/share/zoneinfo/Europe/London /etc/localtime
    Name: run
    PrependShell: true
  - CmdLine:
    - echo Europe/London | tee /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "The date / time after timezone changes ==] `date`"
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/install-plugins.sh     git                       git-client                ssh-credentials           sonar                     workflow-aggregator       build-pipeline-plugin     docker-workflow           workflow-multibranch      workflow-scm-step
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - hudson.plugins.sonar.SonarGlobalConfiguration.xml
    - /var/jenkins_home/hudson.plugins.sonar.SonarGlobalConfiguration.xml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - hudson.plugins.sonar.SonarRunnerInstallation.xml
    - /var/jenkins_home/hudson.plugins.sonar.SonarRunnerInstallation.xml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - hudson.plugins.sonar.MsBuildSQRunnerInstallation.xml
    - /var/jenkins_home/hudson.plugins.sonar.MsBuildSQRunnerInstallation.xml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - settings.xml
    - /var/jenkins_home/settings.xml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jobs
    - /var/jenkins_home/jobs
  - Env:
    - Key: JAVA_OPTS
      Value: '"-Djenkins.install.runSetupWizard=false"'
    Name: env
  From:
    Image: jenkins/jenkins:lts
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins/jenkins:lts
