MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Leelmes "i@chengxuan.li"
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files/CentOS-Base.repo
    - /etc/yum.repos.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files/epel.repo
    - /etc/yum.repos.d/
  - CmdLine:
    - mkdir -p /data1/ && echo 'PS1="\033[1m\033[36m$PS1\033[0m"' >> /etc/bashrc &&
      echo "alias ls='ls --color'" >> /etc/bashrc && cp /usr/share/zoneinfo/Asia/Shanghai
      /etc/localtime && yum install -y vim rsync lrzsz python34 python34-setuptools
      && yum clean all && easy_install-3.4 pyyaml && echo "set number" >> /etc/vimrc
      && echo "setlocal cursorline" >> /etc/vimrc
    Name: run
    PrependShell: true
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Name: workdir
    Path: /data1
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
