MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: Pierre Brun <pbrun.pro+github@gmail.com>
    Name: maintainer
  - Env:
    - Key: RELEASE
      Value: wheezy
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: SHELL
      Value: /bin/bash
    Name: env
  - CmdLine:
    - echo "deb http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list.d/dotdeb.list;echo
      "deb-src http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list.d/dotdeb.list;wget
      http://www.dotdeb.org/dotdeb.gpg;apt-key add dotdeb.gpg;apt-get update;apt-get
      -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get -y install apache2 libapache2-mod-php5
      php5-mysql php5-gd php-pear php-apc php5-curl curl php5-adodb php-gettext git
      acl php5-mcrypt php5-curl jpegoptim php5-gd php5-intl ruby-full build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - curl --silent --location https://deb.nodesource.com/setup_0.12 | bash -;DEBIAN_FRONTEND=noninteractive
      apt-get install --yes nodejs;
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod php5;a2enmod rewrite;npm install -g bower;npm install -g uglify-js;npm
      install -g uglifycss;gem install capifony
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r mysql && useradd -r -g mysql mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5
    Name: run
    PrependShell: true
  - Env:
    - Key: MYSQL_MAJOR
      Value: "5.7"
    Name: env
  - Env:
    - Key: MYSQL_VERSION
      Value: 5.7.8-rc
    Name: env
  - CmdLine:
    - echo "deb http://repo.mysql.com/apt/debian/ wheezy mysql-${MYSQL_MAJOR}-dmr"
      > /etc/apt/sources.list.d/mysql.list
    Name: run
    PrependShell: true
  - CmdLine:
    - "{ \t\techo mysql-community-server mysql-community-server/data-dir select '';
      \t\techo mysql-community-server mysql-community-server/root-pass password '';
      \t\techo mysql-community-server mysql-community-server/re-root-pass password
      ''; \t\techo mysql-community-server mysql-community-server/remove-test-db select
      false; \t} | debconf-set-selections \t&& apt-get update && apt-get install -y
      mysql-server=\"${MYSQL_VERSION}\"* && rm -rf /var/lib/apt/lists/* \t&& rm -rf
      /var/lib/mysql && mkdir -p /var/lib/mysql"
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/my.cnf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod u+x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: volume
    Volumes:
    - /var/www
    - /var/log/apache2
    - /etc/apache2
    - /var/lib/mysql
    - /tmp
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/run.sh
    - /run.sh
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3306"
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
