MetaArgs: null
Stages:
- BaseName: ruby:2.5.1-alpine
  Commands:
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - apk update &&     apk add       build-base       libxml2-dev       libxslt-dev       linux-headers       openssl       ruby-dev       tzdata       yaml       yaml-dev
      &&     gem install bundler
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile
    - Gemfile
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile.lock
    - Gemfile.lock
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Env:
    - Key: APP_HOME
      Value: /gpn
    Name: env
  - CmdLine:
    - mkdir -p $APP_HOME
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $APP_HOME
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - $APP_HOME
  From:
    Image: ruby:2.5.1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.1-alpine
