MetaArgs: null
Stages:
- BaseName: flexberry/alt.p8
  Commands:
  - Labels:
    - Key: description
      Value: '"Parent image for all java images"'
    Name: label
  - CmdLine:
    - bzip2 -d /var/lib/rpm/*bz2;   apt-get update;   apt-get install -y java-1.8.0-openjdk;   rm
      -f /var/cache/apt/archives/*.rpm /var/cache/apt/*.bin /var/lib/apt/lists/*.*;   bzip2
      -9 /var/lib/rpm/*;
    Name: run
    PrependShell: true
  From:
    Image: flexberry/alt.p8
  Name: ""
  Platform: ""
  SourceCode: FROM flexberry/alt.p8
