MetaArgs: null
Stages:
- BaseName: nediiii/janus
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"nediiii varndiiii@gmail.com"'
    Name: label
  - CmdLine:
    - apt-get update &&     apt-get install -y --no-install-recommends     libgstreamer1.0-0     gstreamer1.0-plugins-base     gstreamer1.0-plugins-good     gstreamer1.0-libav     gstreamer1.0-doc     gstreamer1.0-tools     gstreamer1.0-x     gstreamer1.0-alsa     gstreamer1.0-gl     gstreamer1.0-gtk3     gstreamer1.0-qt5     gstreamer1.0-pulseaudio
    Name: run
    PrependShell: true
  From:
    Image: nediiii/janus
  Name: ""
  Platform: ""
  SourceCode: FROM nediiii/janus
