MetaArgs: null
Stages:
- BaseName: oaklabs/oak:5.0.9
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /app
  - CmdLine:
    - npm install    --production    --progress=false    --loglevel="error"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - /app/src
  - CmdLine:
    - /app/src/index.js
    Name: cmd
    PrependShell: false
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  From:
    Image: oaklabs/oak:5.0.9
  Name: ""
  Platform: ""
  SourceCode: FROM oaklabs/oak:5.0.9
