MetaArgs: null
Stages:
- BaseName: ubuntu:15.04
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./webapp
    - /opt/webapp
  - Name: workdir
    Path: /opt/webapp
  - CmdLine:
    - apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup | bash - && apt-get install -yq nodejs
      build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g npm
    Name: run
    PrependShell: true
  - CmdLine:
    - npm config set registry http://registry.npmjs.org/
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g express@2.5.1
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install express
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:15.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:15.04
