MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Key: tmp_dir
    Name: arg
    Value: '"/tmp/go-vaddy"'
  - Key: vaddy_version
    Name: arg
    Value: '"1.0.6"'
  - Name: workdir
    Path: ${tmp_dir}
  - CmdLine:
    - set -ex     && apk add --no-cache --update ca-certificates     && wget --quiet
      https://github.com/vaddy/go-vaddy/archive/v${vaddy_version}.zip     && unzip
      v${vaddy_version}.zip     && mv go-vaddy-${vaddy_version}/bin/vaddy-linux-64bit
      /usr/local/bin/vaddy
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - set -ex && rm -rf ${tmp_dir}
    Name: run
    PrependShell: true
  - CmdLine:
    - vaddy
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
