MetaArgs: null
Stages:
- BaseName: bitnami/php-fpm:5.6.40-prod
  Commands:
  - CmdLine:
    - apt-get update   && apt-get install -y libmemcached-dev openssh-client make
      grep autoconf gcc libc-dev wget zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - "mkdir -p /usr/tmp && cd /usr/tmp \t&& wget http://pecl.php.net/get/memcache-2.2.7.tgz
      \t&& tar -zxvf memcache-2.2.7.tgz \t&& cd memcache-2.2.7 \t&& phpize && ./configure
      --with-php-config=/opt/bitnami/php/bin/php-config \t&& make && make install
      \t&& touch /opt/bitnami/php/etc/php.ini \t&& echo 'extension=memcache.so' >>
      /opt/bitnami/php/etc/php.ini"
    Name: run
    PrependShell: true
  - CmdLine:
    - "echo \"\" >> /opt/bitnami/php/etc/php-fpm.conf \t&& echo 'clear_env = no' >>
      /opt/bitnami/php/etc/php-fpm.conf"
    Name: run
    PrependShell: true
  From:
    Image: bitnami/php-fpm:5.6.40-prod
  Name: ""
  Platform: ""
  SourceCode: FROM bitnami/php-fpm:5.6.40-prod
