MetaArgs: null
Stages:
- BaseName: andyceo/pylibs
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - monitoring-certificate.py
    - requirements.txt
    - /app/
  - CmdLine:
    - pip3 install -r requirements.txt && rm requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - /app/monitoring-certificate.py
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: andyceo/pylibs
  Name: ""
  Platform: ""
  SourceCode: FROM andyceo/pylibs
