MetaArgs: null
Stages:
- BaseName: pataquets/ubuntu:xenial
  Commands:
  - CmdLine:
    - apt-get update &&   DEBIAN_FRONTEND=noninteractive     apt-get install -y minidlna   &&   apt-get
      clean &&   rm -rf /var/lib/apt/lists/
    Name: run
    PrependShell: true
  - CmdLine:
    - minidlnad
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -h
    Name: cmd
    PrependShell: false
  From:
    Image: pataquets/ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM pataquets/ubuntu:xenial
