MetaArgs: null
Stages:
- BaseName: nginx:1.11.4-alpine
  Commands:
  - CmdLine:
    - set -x &&     apk --update add tzdata logrotate &&     ln -sf /usr/share/zoneinfo/Europe/Paris
      /etc/localtime &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x &&     apk --update add       ca-certificates       nano       openssl       openssh-client       acl       bash     &&
      rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx/nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx/default.conf
    - /etc/nginx/conf.d/default.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - logrotate/nginx
    - /etc/logrotate.d/nginx
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - logrotate/cron
    - /etc/periodic/daily/logrotate-cron
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/start.sh
    - /root/start.sh
  - CmdLine:
    - chmod +x /root/start.sh   && chmod +x /etc/periodic/daily/logrotate-cron
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/html
  - CmdLine:
    - /root/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:1.11.4-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:1.11.4-alpine
