MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Alexandru Voinescu "voinescu.alex@gmail.com"
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update -y --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install wget apt-transport-https lsb-release ca-certificates -y
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install wget apache2 mysql-client -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install php7.2 php7.2-dev php7.2-common php-pear php-xml php7.2-opcache
      php7.2-mysql php7.2-zip php7.2-curl -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install libapache2-mod-php7.2 -y
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install timecop-beta
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "extension=timecop.so" >> /etc/php/7.2/cli/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - php -i
    Name: run
    PrependShell: true
  - CmdLine:
    - php -v
    Name: run
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
