MetaArgs: null
Stages:
- BaseName: java:8
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./mysql-connector-java-8.0.13.jar
    - /mysql-connector-java-8.0.13.jar
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./Main.java
    - /Main.java
  - CmdLine:
    - javac Main.java
    Name: run
    PrependShell: true
  - CmdLine:
    - java
    - -cp
    - .:mysql-connector-java-8.0.13.jar
    - Main
    Name: cmd
    PrependShell: false
  - Name: workdir
    Path: /
  From:
    Image: java:8
  Name: ""
  Platform: ""
  SourceCode: FROM java:8
