MetaArgs: null
Stages:
- BaseName: node:10-stretch
  Commands:
  - Name: expose
    Ports:
    - "9005"
  - CmdLine:
    - yarn global add firebase-tools && yarn cache clean
    Name: run
    PrependShell: true
  From:
    Image: node:10-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-stretch
