MetaArgs: null
Stages:
- BaseName: sonarqube:7.7-community
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt-get update   && apt-get install -y pylint jq  && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./plugins
    - /tmp/plugins
  - CmdLine:
    - rm -rf ./extensions/plugins/* &&     cat /tmp/plugins/plugin-list &&     chmod
      +x /tmp/plugins/install-plugins.sh &&     ls /tmp/plugins -l &&     /tmp/plugins/install-plugins.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/sonarqube
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./start-with-profile.sh
    - .
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rules
    - /tmp/rules
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sonar.properties
    - /opt/sonarqube/conf/sonar.properties
  - CmdLine:
    - chown -R sonarqube:sonarqube . && chmod +x start-with-profile.sh
    Name: run
    PrependShell: true
  - Name: user
    User: sonarqube
  - CmdLine:
    - ./start-with-profile.sh
    Name: cmd
    PrependShell: false
  From:
    Image: sonarqube:7.7-community
  Name: ""
  Platform: ""
  SourceCode: FROM sonarqube:7.7-community
