MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - apt/sources.list
    - /etc/apt/
  - Name: user
    User: root
  - CmdLine:
    - '''/bin/bash'''
    Name: cmd
    PrependShell: true
  - Env:
    - Key: TZ
      Value: Asia/Shanghai
    Name: env
  - Env:
    - Key: LC_CTYPE
      Value: zh_CN.UTF-8
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt update && apt upgrade -y &&     apt install -y language-pack-zh-hans lrzsz
      git python3 net-tools zip unzip unar curl wget vim sudo make &&     echo 'set
      encoding=utf-8' >> /root/.vimrc
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
