MetaArgs: null
Stages:
- BaseName: quay.io/external_storage/local-volume-provisioner:v2.1.0
  Commands:
  - Maintainer: kevinlin.job@gmail.com
    Name: maintainer
  From:
    Image: quay.io/external_storage/local-volume-provisioner:v2.1.0
  Name: ""
  Platform: ""
  SourceCode: FROM  quay.io/external_storage/local-volume-provisioner:v2.1.0
