MetaArgs: null
Stages:
- BaseName: postgres:11.3
  Commands:
  - Maintainer: Joan Marc Carbo <jmcarbo@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get install -y wget curl netcat cron
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://dl.minio.io/client/mc/release/linux-amd64/mc > /usr/local/bin/mc
      &&     chmod +x /usr/local/bin/mc &&     mkdir /backup
    Name: run
    PrependShell: true
  - Env:
    - Key: CRON_TIME
      Value: '"0 0 * * *"'
    - Key: PG_DB
      Value: '"--all-databases"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - restic_app
    - /usr/local/bin/restic
  - CmdLine:
    - chmod +x /usr/local/bin/restic
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /backup
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: postgres:11.3
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:11.3
