MetaArgs: null
Stages:
- BaseName: centos/nodejs-10-centos7
  Commands:
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /opt/rh/rh-nodejs10/root/usr/lib64
    Name: env
  - Env:
    - Key: PATH
      Value: /opt/rh/rh-nodejs10/root/usr/bin:/opt/app-root/src/node_modules/.bin/:/opt/app-root/src/.npm-global/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    Name: env
  - Env:
    - Key: NPM_CONFIG_PREFIX
      Value: /opt/app-root/src/.npm-global
    Name: env
  - Env:
    - Key: NPM_RUN
      Value: start
    Name: env
  - Name: workdir
    Path: /opt
  - Name: user
    User: root
  - CmdLine:
    - yum update -y && yum upgrade && yum install -y git     && git clone https://github.com/ansible-community/ara-web     &&
      npm update     && cd /opt/ara-web     && npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config.json
    - /opt/ara-web/public/config.json
  - Name: workdir
    Path: /opt/ara-web
  - CmdLine:
    - npm
    - start
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --host
    - 127.0.0.1
    - --port
    - "3000"
    Name: cmd
    PrependShell: false
  From:
    Image: centos/nodejs-10-centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos/nodejs-10-centos7
