MetaArgs: null
Stages:
- BaseName: fedora:latest
  Commands:
  - Maintainer: Hari Sekhon (https://www.linkedin.com/in/harisekhon)
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Java + Fedora (OpenJDK)"'
    Name: label
  - Key: JAVA_VERSION
    Name: arg
    Value: "8"
  - Key: JAVA_RELEASE
    Name: arg
    Value: JDK
  - Env:
    - Key: JAVA_HOME
      Value: /usr
    Name: env
  - CmdLine:
    - set -eux &&     pkg="java-1.$JAVA_VERSION.0-openjdk" &&     if [ "$JAVA_RELEASE"
      = "JDK" ]; then         pkg="$pkg-devel";     else         pkg="$pkg-headless";     fi;     yum
      install -y "$pkg" &&     yum clean all &&     rm -rf /var/cache/yum
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - profile.d/java.sh
    - /etc/profile.d/
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: fedora:latest
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:latest
