MetaArgs: null
Stages:
- BaseName: rocker/tidyverse
  Commands:
  - CmdLine:
    - Rscript -e "install.packages('packrat', repos = 'http://cran.us.r-project.org')"
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e "install.packages('dplyr', repos = 'http://cran.us.r-project.org')"
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e "install.packages('ggplot2')"
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e "install.packages('ezknitr', repos = 'https://mran.revolutionanalytics.com/snapshot/2017-12-11')"
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e "install.packages('forcats', repos = 'http://cran.us.r-project.org')"
    Name: run
    PrependShell: true
  - CmdLine:
    - Rscript -e "install.packages('stringr', repos = 'http://cran.us.r-project.org')"
    Name: run
    PrependShell: true
  From:
    Image: rocker/tidyverse
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/tidyverse
