MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - CmdLine:
    - apk add --no-cache curl bash jq gettext-dev
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - check
    - /opt/resource/check
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - in
    - /opt/resource/in
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - out
    - /opt/resource/out
  - CmdLine:
    - chmod +x /opt/resource/out /opt/resource/in /opt/resource/check
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
