MetaArgs: null
Stages:
- BaseName: sergeyzskw/nodejs-bower-grunt:latest
  Commands:
  - Maintainer: Sergey Z <sergey.zsv.w@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get install -y ruby-full rubygems-integration     && gem install sass -v
      3.4.5     && gem install sass
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install grunt-browser-sync
    Name: run
    PrependShell: true
  From:
    Image: sergeyzskw/nodejs-bower-grunt:latest
  Name: ""
  Platform: ""
  SourceCode: FROM sergeyzskw/nodejs-bower-grunt:latest
