MetaArgs: null
Stages:
- BaseName: ruby:2.5.1
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y curl  && curl -sL https://deb.nodesource.com/setup_8.x
      | bash -  && apt-get update && apt-get install -y build-essential libpq-dev
      nodejs nodejs  && mkdir /myapp
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /myapp
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - Gemfile.lock
    - /myapp/
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /myapp
  From:
    Image: ruby:2.5.1
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.1
