MetaArgs: null
Stages:
- BaseName: certbot/certbot:v0.24.0
  Commands:
  - CmdLine:
    - pip install --no-cache-dir     certbot-dns-dnspod &&     apk --no-cache add
      curl ca-certificates bash &&     curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl
      -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      &&     chmod +x /usr/local/bin/kubectl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.sh'
    - /bin/
  - CmdLine:
    - /bin/cert.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: certbot/certbot:v0.24.0
  Name: ""
  Platform: ""
  SourceCode: FROM certbot/certbot:v0.24.0
