MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - mkdir -p /data
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/true
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
