MetaArgs: null
Stages:
- BaseName: nginx:alpine
  Commands:
  - Maintainer: Adrien M amaurel90@gmail.com
    Name: maintainer
  - Env:
    - Key: DEBUG
      Value: "false"
    - Key: RAP_DEBUG
      Value: '"info"'
    Name: env
  - Key: VERSION_RANCHER_GEN
    Name: arg
    Value: '"artifacts/master"'
  - CmdLine:
    - apk add --no-cache nano ca-certificates unzip wget certbot bash openssl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/jwilder/forego/releases/download/v0.16.1/forego
    - /usr/local/bin/forego
  - CmdLine:
    - "wget \"https://gitlab.com/adi90x/rancher-gen-rap/builds/$VERSION_RANCHER_GEN/download?job=compile-go\"
      -O /tmp/rancher-gen-rap.zip \t&& unzip /tmp/rancher-gen-rap.zip -d /usr/local/bin
      \t&& chmod +x /usr/local/bin/rancher-gen \t&& chmod u+x /usr/local/bin/forego
      \t&& rm -f /tmp/rancher-gen-rap.zip"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /app/
    - /app/
  - Name: workdir
    Path: /app/
  - CmdLine:
    - "chmod +x /app/letsencrypt.sh     && mkdir -p /etc/nginx/certs /etc/nginx/vhost.d
      /etc/nginx/conf.d /usr/share/nginx/html /etc/letsencrypt     && echo \"daemon
      off;\" >> /etc/nginx/nginx.conf \t\t&& echo \"client_max_body_size 50M;\" >>
      /etc/nginx/conf.d/custom.conf     && sed -i 's/^http {/&\\n    server_names_hash_bucket_size
      128;/g' /etc/nginx/nginx.conf     && chmod u+x /app/remove"
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - /app/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - forego
    - start
    - -r
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
