MetaArgs: null
Stages:
- BaseName: anapsix/alpine-java:8_jdk
  Commands:
  - Env:
    - Key: CROWD_VER
      Value: 2.8.4
    Name: env
  - Env:
    - Key: CROWD_DATA
      Value: /var/lib/atlassian/application-data/crowd
    Name: env
  - CmdLine:
    - apk --update add curl     && curl -LO https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-${CROWD_VER}.tar.gz     &&
      tar -xzf atlassian-crowd-${CROWD_VER}.tar.gz -C /usr/local     && ln -s /usr/local/atlassian-crowd-${CROWD_VER}
      /usr/local/crowd     && rm atlassian-crowd-${CROWD_VER}.tar.gz     && apk --purge
      del curl
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's|#crowd.home=.*|crowd.home='"${CROWD_DATA}"'|g' /usr/local/crowd/crowd-webapp/WEB-INF/classes/crowd-init.properties     &&
      sed -i 's|exec "$PRGDIR"/"$EXECUTABLE" start "$@"|exec "$PRGDIR"/"$EXECUTABLE"
      run "$@"|g' /usr/local/crowd/apache-tomcat/bin/startup.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/atlassian/application-data
  - Name: expose
    Ports:
    - "8095"
  - CmdLine:
    - '''/usr/local/crowd/start_crowd.sh'''
    Name: cmd
    PrependShell: true
  From:
    Image: anapsix/alpine-java:8_jdk
  Name: ""
  Platform: ""
  SourceCode: FROM anapsix/alpine-java:8_jdk
