MetaArgs: null
Stages:
- BaseName: ubuntu:bionic
  Commands:
  - Key: MONGO_C_VERSION
    Name: arg
    Value: 1.12.0
  - Key: MONGO_CXX_VERSION
    Name: arg
    Value: 3.3.1
  - Key: ZEROMQ_VERSION
    Name: arg
    Value: 4.3.0
  - Key: LIBZQ_VERSION
    Name: arg
    Value: 4.2.5
  - Key: BOOST_VERSION
    Name: arg
    Value: 1.68.1
  - Key: BOOST_REF
    Name: arg
    Value: "1_68_1"
  - CmdLine:
    - apt-get update -y && apt-get upgrade -y && apt-get install -y   git   curl   wget   vim   autoconf   automake   apt-file   build-essential   software-properties-common   pkg-config   python3   libc6-dev   libssl-dev   libsasl2-dev   libtool   cmake   gcc   &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_REF}.tar.gz
      &&    tar xvf boost_${BOOST_REF}.tar.gz &&    cd boost_${BOOST_REF} &&    ./bootstrap.sh
      &&    ./b2 install -j2
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/google/googletest.git -b release-1.8.0 --depth
      1  && mkdir -p googletest/_build && cd googletest/_build  && cmake -DCMAKE_INSTALL_PREFIX=/usr/local
      .. && make -j4 && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/facebook/rocksdb.git -b v5.12.4 --depth 1   &&
      mkdir -p rocksdb/_build && cd rocksdb/_build   && cmake -DCMAKE_INSTALL_PREFIX=/usr/local
      .. && make -j4 && make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget https://github.com/zeromq/libzmq/archive/v${LIBZQ_VERSION}.tar.gz &&   tar
      xvf v${LIBZQ_VERSION}.tar.gz &&   mkdir -p libzmq-${LIBZQ_VERSION}/_build &&   cd
      libzmq-${LIBZQ_VERSION}/_build &&   cmake -DCMAKE_INSTALL_PREFIX=/usr/local
      .. &&   make &&   make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget https://github.com/zeromq/cppzmq/archive/v${ZEROMQ_VERSION}.tar.gz &&   tar
      xvf v${ZEROMQ_VERSION}.tar.gz &&   mkdir -p cppzmq-${ZEROMQ_VERSION}/_build
      &&   cd cppzmq-${ZEROMQ_VERSION}/_build &&   cmake -DCMAKE_INSTALL_PREFIX=/usr/local
      .. &&   make &&   make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget https://github.com/mongodb/mongo-c-driver/archive/${MONGO_C_VERSION}.tar.gz
      &&     ls -la &&     tar xvf ${MONGO_C_VERSION}.tar.gz &&     cd mongo-c-driver-${MONGO_C_VERSION}
      &&     mkdir cmake-build &&     cd cmake-build &&     cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF
      -DCMAKE_INSTALL_PREFIX=/usr/local .. &&     make &&     make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget https://github.com/mongodb/mongo-cxx-driver/archive/r${MONGO_CXX_VERSION}.tar.gz
      &&     tar -xvf r${MONGO_CXX_VERSION}.tar.gz &&     cd mongo-cxx-driver-r${MONGO_CXX_VERSION}/build
      &&     cmake -DBSONCXX_POLY_USE_BOOST=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
      .. &&     make &&     make install
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:bionic
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:bionic
