MetaArgs: null
Stages:
- BaseName: kubernetesui/dashboard:v2.0.0-beta8
  Commands: null
  From:
    Image: kubernetesui/dashboard:v2.0.0-beta8
  Name: ""
  Platform: ""
  SourceCode: FROM kubernetesui/dashboard:v2.0.0-beta8
