MetaArgs: null
Stages:
- BaseName: blacktop/volatility:2.6
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Carlos Ortigoza Dempster <carlos.otgz@gmail.com>"'
    Name: label
  - Env:
    - Key: CUCKOO_VERSION
      Value: 2.0.4a1
    Name: env
  - Env:
    - Key: CUCKOO_CWD
      Value: /cuckoo
    Name: env
  - Env:
    - Key: SSDEEP
      Value: ssdeep-2.13
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /tmp/requirements.txt
  - CmdLine:
    - apk add --no-cache tcpdump py-lxml py-chardet py-libvirt py-crypto curl swig
      libpq openvpn
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache -t .build-deps                            postgresql-dev                            libxslt-dev                            libxml2-dev                            python-dev                            libffi-dev                            build-base                            libstdc++                            zlib-dev                            libc-dev                            jpeg-dev                            file-dev                            automake                            autoconf                            libtool                            py-pip                            git                            linux-headers                            libcap   &&
      set -x   && setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump   && echo
      "===> Install ssdeep..."   && wget -O /tmp/$SSDEEP.tar.gz https://downloads.sourceforge.net/project/ssdeep/$SSDEEP/$SSDEEP.tar.gz   &&
      cd /tmp   && tar zxvf $SSDEEP.tar.gz   && cd $SSDEEP   && ./configure   && make   &&
      make install   && echo "===> Install pydeep..."   && cd /tmp   && git clone
      https://github.com/kbandla/pydeep.git   && cd pydeep   && python setup.py build   &&
      python setup.py install   && echo "===> Install Cuckoo Sandbox..."   && mkdir
      /cuckoo   && adduser -D -h /cuckoo cuckoo   && export PIP_NO_CACHE_DIR=off   &&
      export PIP_DISABLE_PIP_VERSION_CHECK=on   && pip install --upgrade pip wheel   &&
      LDFLAGS=-L/lib pip install cuckoo==$CUCKOO_VERSION   && cuckoo   && cuckoo community   &&
      echo "===> Install mitmproxy..."   && LDFLAGS=-L/lib pip install mitmproxy   &&
      pip install -r /tmp/requirements.txt   && echo "===> Clean up unnecessary files..."   &&
      rm -rf /tmp/*   && apk del --purge .build-deps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - check_required_services.py
    - /check_required_services.py
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - Name: workdir
    Path: /cuckoo
  - Name: volume
    Volumes:
    - /cuckoo/conf
  - Name: expose
    Ports:
    - "1337"
    - "2042"
    - "31337"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: blacktop/volatility:2.6
  Name: ""
  Platform: ""
  SourceCode: FROM blacktop/volatility:2.6
