MetaArgs: null
Stages:
- BaseName: node:10
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - ./
  - Key: TOKEN
    Name: arg
    Value: null
  - Env:
    - Key: TOKEN
      Value: $TOKEN
    Name: env
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:10
  Name: ""
  Platform: ""
  SourceCode: FROM node:10
