MetaArgs: null
Stages:
- BaseName: node:4
  Commands:
  - Maintainer: cuong3ihut@gmail.com
    Name: maintainer
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget imagemagick supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g --unsafe-perm node-red
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/local/lib/node_modules/node-red/ && npm install node-red-contrib-selenium-webdriver
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/log/supervisor
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord/*.conf
    - /etc/supervisor/conf.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - settings.js
    - /root/.node-red/settings.js
  - Chown: ""
    Name: add
    SourcesAndDest:
    - flows.json
    - /root/.node-red/flows.json
  - Name: expose
    Ports:
    - "1880"
  - CmdLine:
    - /usr/bin/supervisord
    - -n
    - -c
    - /etc/supervisor/supervisor.conf
    Name: cmd
    PrependShell: false
  From:
    Image: node:4
  Name: ""
  Platform: ""
  SourceCode: FROM node:4
