MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Env:
    - Key: BROOK_VER
      Value: "20181212"
    - Key: MODE
      Value: server
    - Key: PASSWORD
      Value: brookApptest
    - Key: PORT
      Value: "8080"
    Name: env
  - CmdLine:
    - wget --no-check-certificate https://github.com/txthinking/brook/releases/download/v${BROOK_VER}/brook
      &&     chmod +x brook
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - Name: expose
    Ports:
    - ${PORT}
  - CmdLine:
    - /brook ${MODE} -l :${PORT} -p ${PASSWORD}
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
