MetaArgs: null
Stages:
- BaseName: openjdk:8-jdk
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: JENKINS_HOME
      Value: /var/jenkins_home
    Name: env
  - Env:
    - Key: JENKINS_SLAVE_AGENT_PORT
      Value: "50000"
    Name: env
  - Key: user
    Name: arg
    Value: jenkins
  - Key: group
    Name: arg
    Value: jenkins
  - Key: uid
    Name: arg
    Value: "10001"
  - Key: gid
    Name: arg
    Value: "10002"
  - CmdLine:
    - groupadd -g ${gid} ${group}     && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid}
      -m -s /bin/bash ${user}
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/jenkins_home
  - CmdLine:
    - mkdir -p /usr/share/jenkins/ref/init.groovy.d     && curl --progress-bar https://raw.githubusercontent.com/larrytalley/jenkinsci/master/init.groovy
      -O     && curl --progress-bar https://raw.githubusercontent.com/larrytalley/jenkinsci/master/jenkins.sh
      -O     && curl --progress-bar https://raw.githubusercontent.com/larrytalley/jenkinsci/master/jenkins-support
      -O     && chmod +x init.groovy     && chmod +x jenkins.sh     && chmod +x jenkins-support
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init.groovy
    - /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jenkins-support
    - /usr/local/bin/jenkins-support
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jenkins.sh
    - /usr/local/bin/jenkins.sh
  - Env:
    - Key: TINI_VERSION
      Value: 0.13.1
    Name: env
  - Env:
    - Key: TINI_SHA
      Value: 0f78709a0e3c80e7c9119fdc32c2bc0f4cfc4cab
    Name: env
  - CmdLine:
    - curl --progress-bar -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static-amd64
      -o /bin/tini   && chmod +x /bin/tini   && echo "$TINI_SHA  /bin/tini" | sha1sum
      -c -
    Name: run
    PrependShell: true
  - Key: JENKINS_VERSION
    Name: arg
    Value: null
  - Env:
    - Key: JENKINS_VERSION
      Value: ${JENKINS_VERSION:-2.19.4}
    Name: env
  - Key: JENKINS_SHA
    Name: arg
    Value: ea61a4ff86f0db715511d1118a4e2f0a6a0311a1
  - Key: JENKINS_URL
    Name: arg
    Value: https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war
  - CmdLine:
    - curl --progress-bar -fsSL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war   &&
      echo "${JENKINS_SHA}  /usr/share/jenkins/jenkins.war" | sha1sum -c -
    Name: run
    PrependShell: true
  - Env:
    - Key: JENKINS_UC
      Value: https://updates.jenkins.io
    Name: env
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "50000"
  - Env:
    - Key: COPY_REFERENCE_FILE_LOG
      Value: $JENKINS_HOME/copy_reference_file.log
    Name: env
  - CmdLine:
    - curl --progress-bar https://raw.githubusercontent.com/larrytalley/jenkinsci/master/batch-install-jenkins-plugins.sh
      -O   && curl --progress-bar https://raw.githubusercontent.com/larrytalley/jenkinsci/master/exclude-plugins
      -O   && curl --progress-bar https://raw.githubusercontent.com/larrytalley/jenkinsci/master/include-plugins
      -O   && chmod +x batch-install-jenkins-plugins.sh   && chmod +x /usr/local/bin/jenkins-support   &&
      chmod +x /usr/local/bin/jenkins.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p $JENKINS_HOME/plugins   && ./batch-install-jenkins-plugins.sh --plugins
      include-plugins --xplugins exclude-plugins --plugindir $JENKINS_HOME/plugins
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R ${user}:${group} "$JENKINS_HOME"   && chown -R ${user}:${group} /usr/share/   &&
      chown -R ${user}:${group} /bin/   && chown -R ${user}:${group} /usr/local/bin/
    Name: run
    PrependShell: true
  - Name: user
    User: ${user}
  - CmdLine:
    - /bin/tini
    - --
    - /usr/local/bin/jenkins.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jdk
