MetaArgs: null
Stages:
- BaseName: node:6.9.1
  Commands:
  - CmdLine:
    - useradd --user-group --create-home --shell /bin/false app
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /home/app
    Name: env
  - Name: user
    User: app
  - Name: workdir
    Path: $HOME/chat
  From:
    Image: node:6.9.1
  Name: ""
  Platform: ""
  SourceCode: FROM node:6.9.1
