MetaArgs: null
Stages:
- BaseName: base/archlinux
  Commands:
  - CmdLine:
    - pacman -Syyu
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -Sq --noconfirm --noprogressbar coreutils nginx php php-fpm php-gd php-intl
      mediawiki imagemagick supervisor gcc-libs libpng unzip wget
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisor_nginx.ini
    - /etc/supervisor.d/nginx.ini
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisor_php.ini
    - /etc/supervisor.d/php.ini
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mediawiki.conf
    - /etc/nginx/mediawiki.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - CmdLine:
    - sed -i 's/nodaemon=false/nodaemon=true/' /etc/supervisord.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/;extension=gd/extension=gd/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/;extension=intl/extension=intl/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/;extension=mysqli/extension=mysqli/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/;extension=xcache/extension=xcache/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/;extension=iconv/extension=iconv/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 10M/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/post_max_size = 8M/post_max_size = 10M/' /etc/php/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /usr/share/webapps/mediawiki/images
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - favicon.ico
    - /usr/share/webapps/mediawiki/favicon.ico
  - Chown: ""
    Name: add
    SourcesAndDest:
    - extension_dl
    - /usr/local/bin/
  - CmdLine:
    - extension_dl ConfirmEdit
    Name: run
    PrependShell: true
  - CmdLine:
    - extension_dl ImageMap
    Name: run
    PrependShell: true
  - CmdLine:
    - extension_dl ParserFunctions
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/bin/supervisord
    - -c
    - /etc/supervisord.conf
    Name: cmd
    PrependShell: false
  From:
    Image: base/archlinux
  Name: ""
  Platform: ""
  SourceCode: from base/archlinux
