MetaArgs: null
Stages:
- BaseName: bestwu/deepin:panda
  Commands:
  - Labels:
    - Key: name
      Value: netease-cloud-music
    - Key: version
      Value: 1.1.0
    - Key: release
      Value: "1"
    - Key: maintainer
      Value: '''Peter Wu <piterwu@outlook.com>'''
    Name: label
  - CmdLine:
    - echo 'deb http://mirrors.kernel.org/deepin panda main' > /etc/apt/sources.list
      &&     apt-get update &&     apt-get install -y --no-install-recommends locales
      &&     echo 'zh_CN.UTF-8 UTF-8' > /etc/locale.gen &&     locale-gen &&     echo
      -e 'LANG="zh_CN.UTF-8"\nLANGUAGE="zh_CN:zh"\n' > /etc/default/locale &&     source
      /etc/default/locale &&     apt-get install -y --no-install-recommends fonts-wqy-microhei
      dbus-x11 netease-cloud-music &&     apt-get -y autoremove && apt-get clean -y
      && apt-get autoclean -y &&     rm -rf var/lib/apt/lists/* var/cache/apt/* var/log/*
    Name: run
    PrependShell: true
  - Env:
    - Key: LANGUAGE
      Value: zh_CN.UTF-8
    - Key: LC_ALL
      Value: zh_CN.UTF-8
    - Key: LANG
      Value: zh_CN.UTF-8
    - Key: TZ
      Value: UTC-8
    - Key: APP
      Value: netease-cloud-music
    - Key: AUDIO_GID
      Value: "63"
    - Key: GID
      Value: "1000"
    - Key: UID
      Value: "1000"
    Name: env
  - CmdLine:
    - groupadd -o -g $GID netease &&     groupmod -o -g $AUDIO_GID audio &&     useradd
      -d "/home/netease" -m -o -u $UID -g netease -G audio netease
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: bestwu/deepin:panda
  Name: ""
  Platform: ""
  SourceCode: FROM bestwu/deepin:panda
