MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.10-alpine
  Commands:
  - CmdLine:
    - apk add --no-cache git mercurial ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
    - /usr/bin/dep
  - CmdLine:
    - chmod +x /usr/bin/dep
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $GOPATH/src/github.com/alexolivier/flight2bigquery
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gopkg.toml
    - Gopkg.lock
    - ./
  - CmdLine:
    - dep ensure --vendor-only
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app .
    Name: run
    PrependShell: true
  From:
    Image: golang:1.10-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.10-alpine AS builder
- BaseName: chrisjoyce911/goscratchcert
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /etc/ssl/certs/ca-certificates.crt
    - /etc/ssl/certs/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /app
    - ./
  - CmdLine:
    - ./app
    Name: entrypoint
    PrependShell: false
  From:
    Image: chrisjoyce911/goscratchcert
  Name: ""
  Platform: ""
  SourceCode: FROM chrisjoyce911/goscratchcert
