MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install collectd curl python-pip
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc_mtab
    - /etc/mtab
  - Chown: ""
    Name: add
    SourcesAndDest:
    - collectd.conf.tpl
    - /etc/collectd/collectd.conf.tpl
  - CmdLine:
    - pip install envtpl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start_container
    - /usr/bin/start_container
  - CmdLine:
    - chmod +x /usr/bin/start_container
    Name: run
    PrependShell: true
  - CmdLine:
    - start_container
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM    ubuntu:xenial
