MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: Alexey Kuznetsov <kuznetsovalexey34@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openjdk-8-jdk
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-client
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O /tmp/z.$$ https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip -d /usr/lib/android-sdk /tmp/z.$$
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /tmp/z.$$
    Name: run
    PrependShell: true
  - CmdLine:
    - yes|/usr/lib/android-sdk/tools/bin/sdkmanager --licenses
    Name: run
    PrependShell: true
  - CmdLine:
    - yes|/usr/lib/android-sdk/tools/bin/sdkmanager --update
    Name: run
    PrependShell: true
  - CmdLine:
    - yes|/usr/lib/android-sdk/tools/bin/sdkmanager ndk-bundle
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-client
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y locales
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: '''en_US.UTF-8'''
    - Key: LANGUAGE
      Value: '''en_US:en'''
    - Key: LC_ALL
      Value: '''en_US.UTF-8'''
    Name: env
  - CmdLine:
    - apt-get install -y build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl
    Name: run
    PrependShell: true
  - Env:
    - Key: ANDROID_HOME
      Value: /usr/lib/android-sdk
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root_pem_geotrust_rapidssl.crt
    - /usr/local/share/ca-certificates/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - intermediate_pem_geotrust_rapidssl.crt
    - /usr/local/share/ca-certificates/
  - CmdLine:
    - update-ca-certificates --fresh
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash jenkins
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get autoclean
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get autoremove
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: from ubuntu
