MetaArgs: null
Stages:
- BaseName: ros:indigo
  Commands:
  - Maintainer: Wilbert van de Ridder wilbert.ridder+drig7@gmail.com
    Name: maintainer
  - Key: user
    Name: arg
    Value: null
  - Key: uid
    Name: arg
    Value: null
  - Key: home
    Name: arg
    Value: null
  - Key: workspace
    Name: arg
    Value: null
  - Key: shell
    Name: arg
    Value: null
  - CmdLine:
    - apt-get -y update && apt-get install -y zsh screen tree sudo ssh synaptic
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y  xserver-xorg-dev-lts-wily  libegl1-mesa-dev-lts-wily  libgl1-mesa-dev-lts-wily  libgbm-dev-lts-wily  mesa-common-dev-lts-wily  libgles2-mesa-lts-wily  libwayland-egl1-mesa-lts-wily  libopenvg1-mesa
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y  qt4-dev-tools  libqt5core5a libqt5dbus5 libqt5gui5 libwayland-client0  libwayland-server0
      libxcb-icccm4 libxcb-image0 libxcb-keysyms1  libxcb-render-util0 libxcb-util0
      libxcb-xkb1 libxkbcommon-x11-0  libxkbcommon0
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - Name: volume
    Volumes:
    - '"${home}"'
  - CmdLine:
    - 'echo "${user}:x:${uid}:${uid}:${user},,,:${home}:${shell}" >> /etc/passwd &&   echo
      "${user}:x:${uid}:" >> /etc/group &&   echo "${user} ALL=(ALL) NOPASSWD: ALL"
      > "/etc/sudoers.d/${user}" &&   chmod 0440 "/etc/sudoers.d/${user}"'
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y     build-essential tree curl python-rosdep
      python-rosinstall-generator python-wstool python-rosinstall wget     && apt-get
      remove -y gazebo2     && rm /etc/ros/rosdep/sources.list.d/20-default.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y x11-apps python-pip build-essential
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install catkin_tools
    Name: run
    PrependShell: true
  - CmdLine:
    - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release
      -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'     && wget http://packages.osrfoundation.org/gazebo.key
      -O - | sudo apt-key add - \    && apt-get update && apt-get install -y ros-indigo-gazebo7-ros-pkgs
      ros-indigo-gazebo7-ros-control
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y ros-indigo-control-msgs ros-indigo-forward-command-controller
      libeigen3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev
      libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev
      python-software-properties libffi-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Name: user
    User: '"${user}"'
  - Env:
    - Key: QT_X11_NO_MITSHM
      Value: "1"
    Name: env
  - Env:
    - Key: CATKIN_TOPLEVEL_WS
      Value: '"${workspace}/devel"'
    Name: env
  - Name: workdir
    Path: ${workspace}
  From:
    Image: ros:indigo
  Name: ""
  Platform: ""
  SourceCode: FROM ros:indigo
