MetaArgs: null
Stages:
- BaseName: resin/armhf-alpine
  Commands:
  - Labels:
    - Key: MAINTAINER
      Value: '"Greg White grewhit25@gmail.com"'
    Name: label
  - Env:
    - Key: s6_VERSION
      Value: 1.21.4.0
    Name: env
  - CmdLine:
    - apk --update add     nfs-utils     bash
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/just-containers/s6-overlay/releases/download/v${s6_VERSION}/s6-overlay-armhf.tar.gz
    - /tmp/
  - CmdLine:
    - tar xzf /tmp/s6-overlay-armhf.tar.gz -C / &&     mkdir /app
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - s6/config.init
    - /etc/cont-init.d/00-config
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - s6/rpcbind.run
    - /etc/services.d/rpcbind/run
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - s6/mountd.run
    - /etc/services.d/mountd/run
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - app/
    - /app
  - CmdLine:
    - chmod -R 755 /app/
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 111/udp
    - 2049/tcp
    - 2049/udp
  - CmdLine:
    - /app/start.sh
    - /init
    Name: entrypoint
    PrependShell: false
  From:
    Image: resin/armhf-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM resin/armhf-alpine
