MetaArgs: null
Stages:
- BaseName: mohamnag/gradle
  Commands:
  - Maintainer: Mohammad Naghavi <mohamnag@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get install -y postgresql-client
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: mohamnag/gradle
  Name: ""
  Platform: ""
  SourceCode: FROM mohamnag/gradle
