MetaArgs: null
Stages:
- BaseName: python:3.6-alpine
  Commands:
  - Name: workdir
    Path: /mnt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./xor.py
    - /usr/local/bin/xor.py
  - CmdLine:
    - xor.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:3.6-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-alpine
