MetaArgs: null
Stages:
- BaseName: google/cadvisor:v0.25.0
  Commands:
  - CmdLine:
    - apk -U add findutils
    Name: run
    PrependShell: true
  From:
    Image: google/cadvisor:v0.25.0
  Name: ""
  Platform: ""
  SourceCode: FROM google/cadvisor:v0.25.0
