MetaArgs: null
Stages:
- BaseName: maven:3.5.0-jdk-8
  Commands:
  - Maintainer: AmbiverseNLU <ambiversenlu-admin@mpi-inf.mpg.de>
    Name: maintainer
  - Env:
    - Key: AIDA_CONF
      Value: default
    Name: env
  - Name: workdir
    Path: /ambiverse-nlu
  - CmdLine:
    - git clone https://github.com/ambiverse-nlu/ambiverse-nlu.git /ambiverse-nlu
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i '/^log4j.appender.FILE.File=.*/c\log4j.appender.FILE.File=/ambiverse-nlu/logs/ambiverse-nlu.log'
      /ambiverse-nlu/src/main/resources/log4j.properties
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i '/^log4j.appender.requestLog.File=.*/c\log4j.appender.requestLog.File=/ambiverse-nlu/logs/requests.log'
      /ambiverse-nlu/src/main/resources/log4j.properties
    Name: run
    PrependShell: true
  - Env:
    - Key: MAVEN_OPTS
      Value: -Djetty.port=8080 -Xmx8G -Dorg.eclipse.jetty.annotations.maxWait=180
    Name: env
  - CmdLine:
    - mvn
    - jetty:run
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: maven:3.5.0-jdk-8
  Name: ""
  Platform: ""
  SourceCode: FROM maven:3.5.0-jdk-8
