MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Env:
    - Key: ACME_VERSION
      Value: 0.0.67
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - acme.sh
    - /etc/periodic/daily/acme.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /start.sh
  - CmdLine:
    - "chmod +x /etc/periodic/daily/acme.sh \t&& apk add --no-cache openssl ca-certificates
      \t&& wget -O -  https://github.com/hlandau/acme/releases/download/v$ACME_VERSION/acmetool-v$ACME_VERSION-linux_amd64.tar.gz
      | tar xzf - \t&& echo -e \"#!/bin/sh\\n/acmetool-v$ACME_VERSION-linux_amd64/bin/acmetool
      --state=/certs/ \\$*\" > /usr/bin/acmetool \t&& chmod +x /usr/bin/acmetool \t&&
      mkdir -p /certs/root/ /certs/certs/"
    Name: run
    PrependShell: true
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
