MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: Amin Jams <aminjam@outlook.com>
    Name: maintainer
  - Env:
    - Key: SYNC_GATEWAY_VERSION
      Value: 1.0.3
    Name: env
  - CmdLine:
    - export DEBIAN_FRONTEND=noninteractive &&   sed -i 's/# \(.*multiverse$\)/\1/g'
      /etc/apt/sources.list &&   apt-get update &&   apt-get -y upgrade &&   apt-get
      install -y wget &&   wget -q http://packages.couchbase.com/releases/couchbase-sync-gateway/${SYNC_GATEWAY_VERSION}/couchbase-sync-gateway-community_${SYNC_GATEWAY_VERSION}_x86_64.deb
      -O package.deb &&   dpkg -i package.deb &&   rm package.deb
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/couchbase-sync-gateway/bin:$PATH
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - chmod +x /*.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4984"
    - "4985"
  - Name: workdir
    Path: /opt/couchbase-sync-gateway
  - CmdLine:
    - /run.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
