MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.12-alpine
  Commands:
  - Env:
    - Key: GO111MODULE
      Value: "on"
    Name: env
  - Env:
    - Key: GOPROXY
      Value: https://goproxy.cn
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/casbin/casbin-server
  - Name: workdir
    Path: /go/src/github.com/casbin/casbin-server
  - CmdLine:
    - CGO_ENABLED=0 go build -ldflags "-s -w -X main.version=1.0.0" -v -a -installsuffix
      cgo -o casbin_server main.go
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.12-alpine as builder
- BaseName: scratch
  Commands:
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/casbin/casbin-server/casbin_server
    - .
  - CmdLine:
    - ./casbin_server
    Name: cmd
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
