MetaArgs: null
Stages:
- BaseName: tianon/ubuntu-core:14.04
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - build.sh
    - /tmp/build.sh
  - CmdLine:
    - /tmp/build.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/confd
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - confd.toml
    - /etc/confd/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf.d
    - /etc/confd/conf.d
  - Chown: ""
    Name: add
    SourcesAndDest:
    - templates
    - /etc/confd/templates
  From:
    Image: tianon/ubuntu-core:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM tianon/ubuntu-core:14.04
