MetaArgs: null
Stages:
- As: ant-download
  BaseName: alpine:3.9
  Commands:
  - Name: workdir
    Path: /ant
  - Key: ANT_VERSION
    Name: arg
    Value: 1.10.5
  - CmdLine:
    - wget http://ftp.unicamp.br/pub/apache//ant/binaries/apache-ant-$ANT_VERSION-bin.zip
      &&     wget https://www.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.zip.sha512
      &&     echo -n "`cat apache-ant-$ANT_VERSION-bin.zip.sha512`  apache-ant-$ANT_VERSION-bin.zip"
      | sha512sum -c &&     unzip apache-ant-$ANT_VERSION-bin.zip &&     mv apache-ant-$ANT_VERSION
      apache-ant
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.9
  Name: ant-download
  Platform: ""
  SourceCode: FROM alpine:3.9 as ant-download
- BaseName: openjdk:8-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Yago Lima <yagotoledolima@gmail.com"'
    Name: label
  - Name: workdir
    Path: /opt/apache-ant
  - Chown: ""
    From: ant-download
    Name: copy
    SourcesAndDest:
    - /ant/apache-ant
    - ./
  - Env:
    - Key: ANT_HOME
      Value: /opt/apache-ant
    Name: env
  - Env:
    - Key: PATH
      Value: '"$PATH:/opt/apache-ant/bin"'
    Name: env
  - CmdLine:
    - ant
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-alpine
