MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: matt.ellis@sudoseng.com
    Name: maintainer
  - CmdLine:
    - apk add --update curl postgresql python unzip &&   curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
      -o "awscli-bundle.zip" &&   unzip awscli-bundle.zip &&   ./awscli-bundle/install
      -i /usr/local/aws -b /usr/local/bin/aws &&   aws --version &&   rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /backups
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - backup.sh
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
