MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: Emmanuel Frecon <efrecon@gmail.com>
    Name: maintainer
  - CmdLine:
    - mkdir /opt &&   apk add --update-cache openjdk7 &&   rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /usr/lib/jvm/java-1.7-openjdk/bin:$PATH
    Name: env
  - Name: volume
    Volumes:
    - /opt
  - CmdLine:
    - java
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
