MetaArgs: null
Stages:
- BaseName: debian:stable
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update; apt-get install -y openjdk-7-jre-headless wget
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - md5sums
    - /opt/md5sums
  - CmdLine:
    - cd /opt &&     wget -q http://mirror.softaculous.com/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
      &&     md5sum -c md5sums &&     tar xzf zookeeper-3.4.6.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /opt/zookeeper-3.4.6/conf/zoo_sample.cfg /opt/zookeeper-3.4.6/conf/zoo.cfg
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-7-openjdk-amd64
    Name: env
  - Env:
    - Key: ZK_HOME
      Value: /opt/zookeeper-3.4.6
    Name: env
  - Name: expose
    Ports:
    - "2181"
    - "2888"
    - "3888"
  - Name: workdir
    Path: /opt/zookeeper-3.4.6
  - CmdLine:
    - bin/zkServer.sh
    - start-foreground
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stable
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stable
