MetaArgs: null
Stages:
- BaseName: mysql:5.5
  Commands:
  - Maintainer: John Gedeon <js1@gedeons.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get -y install ruby &&     gem install daemons faraday
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Name: workdir
    Path: /root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/*
    - /usr/local/bin/
  - CmdLine:
    - chmod 755 /usr/local/bin/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - lib/*
    - /root/
  - CmdLine:
    - apt-get clean &&    rm -rf /tmp/* /var/tmp/* &&    rm -rf /var/lib/apt/lists/*
      &&    rm -f /etc/dpkg/dpkg.cfg.d/02apt-speedup
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/init.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - mysqld
    Name: cmd
    PrependShell: false
  From:
    Image: mysql:5.5
  Name: ""
  Platform: ""
  SourceCode: FROM mysql:5.5
