MetaArgs: null
Stages:
- BaseName: python:2.7
  Commands:
  - CmdLine:
    - git clone https://github.com/loris-imageserver/loris.git &&     apt-get update
      &&     apt-get install -y libjpeg-dev libfreetype6-dev zlib1g-dev     liblcms2-dev
      liblcms2-utils libtiff5-dev python-dev libwebp-dev apache2     libapache2-mod-wsgi
      &&     pip install Pillow uwsgi
    Name: run
    PrependShell: true
  - Name: workdir
    Path: loris
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - python setup.py install --loris-owner=root --loris-group=root
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - sh
    - /entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: python:2.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7
