MetaArgs: null
Stages:
- BaseName: node:8-alpine
  Commands:
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Env:
    - Key: CHOKIDAR_USEPOLLING
      Value: "true"
    Name: env
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - npm install express-gateway@1.7.2 &&     ./node_modules/.bin/eg gateway create
      -n gateway -d . -t getting-started &&     npm cache clean --force &&     ./node_modules/.bin/eg
      plugin install express-gateway-plugin-rewrite -n -g
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gateway.config.yml
    - ./config/gateway.config.yml
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - npm
    - run
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8-alpine
