MetaArgs: null
Stages:
- BaseName: ruby:2.2.2-wheezy
  Commands:
  - Maintainer: advincze@gmail.com
    Name: maintainer
  - CmdLine:
    - gem install eb_deployer
    Name: run
    PrependShell: true
  From:
    Image: ruby:2.2.2-wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.2.2-wheezy
