MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: AJ <aj@laatu.uk>
    Name: maintainer
  - CmdLine:
    - yum install -y ruby
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install bundler
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /app
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - app.rb
    - /app/
  - CmdLine:
    - cd /app && bundle install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /usr/bin/ruby
    - /app/app.rb
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
