MetaArgs: null
Stages:
- BaseName: php:7.1-apache
  Commands:
  - CmdLine:
    - apt-get -y update --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install nano
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install --fix-missing apt-utils build-essential git curl libcurl3
      libcurl3-dev zip
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
      --filename=composer
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug-2.5.0
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-enable xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libmcrypt-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install mcrypt
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libsqlite3-dev libsqlite3-0 mysql-client
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo_mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo_sqlite
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install mysqli
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install curl
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install tokenizer
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install json
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install zip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libicu-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) intl
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install mbstring
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) gd
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite headers
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./config/php/php.ini
    - /usr/local/etc/php/php.ini
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./config/vhosts/default.conf
    - /etc/apache2/sites-enabled
  From:
    Image: php:7.1-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.1-apache
