MetaArgs: null
Stages:
- BaseName: php:apache
  Commands:
  - Maintainer: Alisson Martineli <martineli.alisson@gmail.com>
    Name: maintainer
  - CmdLine:
    - /usr/sbin/a2enmod rewrite
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 000-phalcon.conf
    - /etc/apache2/sites-available/
  - CmdLine:
    - /usr/sbin/a2ensite 000-phalcon
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/apt-get update && apt-get install -y git     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - git clone --depth=1 https://github.com/phalcon/zephir.git     && find zephir
      -type f -print0 | xargs -0 sed -i 's/sudo //g'     && cd zephir     && ./install
      -c
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - git clone --branch 2.1.x --depth=1 https://github.com/phalcon/cphalcon.git     &&
      cd cphalcon     && zephir fullclean     && zephir build --backend=ZendEngine3     &&
      echo "extension=phalcon.so" >> /usr/local/etc/php/conf.d/30-phalcon.ini
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/sbin/apache2ctl
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: php:apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:apache
