MetaArgs: null
Stages:
- As: shellcheck
  BaseName: koalaman/shellcheck-alpine:latest
  Commands: null
  From:
    Image: koalaman/shellcheck-alpine:latest
  Name: shellcheck
  Platform: ""
  SourceCode: FROM koalaman/shellcheck-alpine:latest as shellcheck
- BaseName: python:3.7-alpine
  Commands:
  - Env:
    - Key: PIPENV_NOSPIN
      Value: "1"
    - Key: PIPENV_HIDE_EMOJIS
      Value: "1"
    - Key: PIPENV_COLORBLIND
      Value: "1"
    Name: env
  - Key: USERNAME
    Name: arg
    Value: vscode
  - Key: USER_UID
    Name: arg
    Value: "1000"
  - Key: USER_GID
    Name: arg
    Value: $USER_UID
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Pipfile
    - /tmp/
  - Chown: ""
    From: shellcheck
    Name: copy
    SourcesAndDest:
    - /bin/shellcheck
    - /bin/shellcheck
  - CmdLine:
    - apk update     && apk add bash curl dialog g++ gcc git iproute2 libffi-dev libssl1.1
      libxml2-dev         libxslt-dev make musl-dev openssh-client openssl-dev procps
      sudo     && pip install pipenv==2018.11.26 --upgrade     && cd /tmp     && pipenv
      lock     && pipenv install --system     && addgroup -g $USER_GID $USERNAME     &&
      adduser -D -s /bin/bash -u $USER_UID -G $USERNAME $USERNAME     && chmod 755
      /bin/shellcheck     && rm -rf /root/.cache     && rm -rf /tmp/*     && rm -rf
      /var/cache/apk/*     && rm -rf /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: python:3.7-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-alpine
