MetaArgs: null
Stages:
- BaseName: docker:18.09
  Commands:
  - CmdLine:
    - apk --no-cache add curl bash openssl openssh-client python
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rdocker.sh
    - /usr/local/bin/rdocker
  - CmdLine:
    - chmod +x /usr/local/bin/rdocker
    Name: run
    PrependShell: true
  - CmdLine:
    - rdocker
    Name: cmd
    PrependShell: false
  - Labels:
    - Key: org.label-schema.vcs-url
      Value: '"https://bitbucket.org/senofi/remote-docker"'
    Name: label
  From:
    Image: docker:18.09
  Name: ""
  Platform: ""
  SourceCode: FROM docker:18.09
