MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-slim
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openjdk-8-jdk
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y maven
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libxi6 libgconf-2-4
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pom.xml
    - /usr/local/crossover-tests/pom.xml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - /usr/local/crossover-tests/src
  - Name: workdir
    Path: /usr/local/crossover-tests
  - CmdLine:
    - apt-get install unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip chromedriver_linux64.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 777 chromedriver
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install xvfb gtk2-engines-pixbuf
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install imagemagick x11-apps
    Name: run
    PrependShell: true
  - CmdLine:
    - Xvfb -ac :99 -screen 0 1280x1024x16 &
    Name: run
    PrependShell: true
  - CmdLine:
    - export DISPLAY=:99
    Name: run
    PrependShell: true
  From:
    Image: openjdk:8-jre-slim
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-slim
