MetaArgs: null
Stages:
- BaseName: rodrigozc/consul:1.0.3
  Commands:
  - Labels:
    - Key: author.name
      Value: '"Rodrigo Zampieri Castilho"'
    Name: label
  - Labels:
    - Key: author.email
      Value: '"rodrigo.zampieri@gmail.com"'
    Name: label
  - Labels:
    - Key: repository.url
      Value: '"https://bitbucket.org/rcastilho/kong"'
    Name: label
  - Env:
    - Key: NODEJS_VERSION
      Value: '"8"'
    Name: env
  - Env:
    - Key: KONG_VERSION
      Value: '"0.11.2"'
    Name: env
  - Env:
    - Key: APPLICATION_DEFAULT_NAME
      Value: '"kong"'
    Name: env
  - CmdLine:
    - apt-get update     && apt-get install -y --no-install-recommends openssl libpcre3
      procps perl curl netcat-openbsd gnupg2 dirmngr     && curl -L https://kong.bintray.com/kong-community-edition-deb/dists/kong-community-edition-${KONG_VERSION}.jessie.all.deb
      -o kong-community-edition-${KONG_VERSION}.jessie.all.deb     && dpkg -i kong-community-edition-${KONG_VERSION}.jessie.all.deb     &&
      rm kong-community-edition-${KONG_VERSION}.jessie.all.deb     && apt-get clean     &&
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - consul-template/1-consul-template.list
    - /etc/consul-template/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - consul/service.ctmpl
    - /etc/consul/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - consul/service.json
    - /etc/consul/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run/kong.sh
    - /docker/run/
  From:
    Image: rodrigozc/consul:1.0.3
  Name: ""
  Platform: ""
  SourceCode: FROM rodrigozc/consul:1.0.3
