MetaArgs: null
Stages:
- BaseName: octoblu/meshblu
  Commands:
  - Maintainer: tomiti
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./database.js
    - /usr/src/app/lib/database.js
  From:
    Image: octoblu/meshblu
  Name: ""
  Platform: ""
  SourceCode: FROM octoblu/meshblu
