MetaArgs: null
Stages:
- BaseName: joyzoursky/python-chromedriver:3.7-alpine3.8-selenium
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"yeolhyun.kwon@gmail.com"'
    Name: label
  - Env:
    - Key: GITHUB_USER
      Value: nobody
    Name: env
  - Env:
    - Key: GITHUB_REPO
      Value: nowhere
    Name: env
  - Env:
    - Key: KRX_USER
      Value: someone
    Name: env
  - Env:
    - Key: KRX_PASS
      Value: secret
    Name: env
  - Env:
    - Key: PASSPHRASE
      Value: passphrase
    Name: env
  - CmdLine:
    - apk update
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add git openssh-client tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add build-base
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Asia/Seoul" > /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pycryptodomex
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /secrets
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /secrets
  - Name: workdir
    Path: /root
  - CmdLine:
    - mkdir .ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /script
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /script
  - Chown: ""
    Name: add
    SourcesAndDest:
    - '*.py'
    - /script/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run
    - /script/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - crontab
    - /script/
  - CmdLine:
    - chmod 755 /script/crontab
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/crontab /script/crontab
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entry
    - /script/
  - CmdLine:
    - chmod 755 /script/run
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /script/entry
    Name: run
    PrependShell: true
  - CmdLine:
    - /script/entry
    Name: cmd
    PrependShell: false
  From:
    Image: joyzoursky/python-chromedriver:3.7-alpine3.8-selenium
  Name: ""
  Platform: ""
  SourceCode: FROM joyzoursky/python-chromedriver:3.7-alpine3.8-selenium
