MetaArgs: null
Stages:
- As: slim
  BaseName: python:3.7-alpine
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./requirements.txt
    - /app/requirements.txt
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - ldd `which python`
    Name: run
    PrependShell: true
  From:
    Image: python:3.7-alpine
  Name: slim
  Platform: ""
  SourceCode: FROM python:3.7-alpine AS slim
- BaseName: scratch
  Commands:
  - Maintainer: SKi S "docker@sankhe.com"
    Name: maintainer
  - Labels:
    - Key: '"com.sankhe"'
      Value: '"Sankhe LLC"'
    Name: label
  - Labels:
    - Key: version
      Value: '"1.0"'
    Name: label
  - Labels:
    - Key: description
      Value: '"Slim docker image for Flask Apps."'
    Name: label
  - Chown: ""
    From: slim
    Name: copy
    SourcesAndDest:
    - /app
    - /app
  - Chown: ""
    From: slim
    Name: copy
    SourcesAndDest:
    - /usr/local/lib
    - /usr/local/lib
  - Chown: ""
    From: slim
    Name: copy
    SourcesAndDest:
    - /usr/local/bin
    - /usr/local/bin
  - Chown: ""
    From: slim
    Name: copy
    SourcesAndDest:
    - /lib
    - /lib
  - Name: workdir
    Path: /app
  - CmdLine:
    - python
    - app.py
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "80"
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
