MetaArgs: null
Stages:
- BaseName: php:5.6-apache
  Commands:
  - Maintainer: Marco Nunez <setterlee@gmail.com>
    Name: maintainer
  - Env:
    - Key: DB_SERVER
      Value: <to be defined>
    Name: env
  - Env:
    - Key: DB_PORT
      Value: <to be defined>
    Name: env
  - Env:
    - Key: DB_NAME
      Value: prestashop
    Name: env
  - Env:
    - Key: DB_USER
      Value: root
    Name: env
  - Env:
    - Key: DB_PASSWD
      Value: <to be defined>
    Name: env
  - Env:
    - Key: PS_DEV_MODE
      Value: "0"
    Name: env
  - Env:
    - Key: PS_HOST_MODE
      Value: "0"
    Name: env
  - Env:
    - Key: PS_HANDLE_DYNAMIC_DOMAIN
      Value: "0"
    Name: env
  - Env:
    - Key: PS_FOLDER_ADMIN
      Value: admin
    Name: env
  - Env:
    - Key: PS_FOLDER_INSTALL
      Value: install
    Name: env
  - CmdLine:
    - "apt-get update \t&& apt-get install -y libmcrypt-dev \t\tlibjpeg62-turbo-dev
      \t\tlibpng12-dev \t\tlibfreetype6-dev \t\tlibxml2-dev \t\tlibicu-dev     mysql-client
      \t\twget \t\tunzip     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-configure
      gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install
      iconv intl mcrypt opcache pdo mysql pdo_mysql mbstring soap gd zip"
    Name: run
    PrependShell: true
  - Env:
    - Key: PS_VERSION
      Value: 1.6.1.11
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://www.prestashop.com/download/old/prestashop_1.6.1.11.zip
    - /tmp/prestashop.zip
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_files/ps-extractor.sh
    - /tmp/
  - CmdLine:
    - mkdir /tmp/data-ps && unzip -q /tmp/prestashop.zip -d /tmp/data-ps/ && bash
      /tmp/ps-extractor.sh /tmp/data-ps && rm /tmp/prestashop.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_files/docker_updt_ps_domains.php
    - /var/www/html/
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - chown www-data:www-data -R /var/www/html/
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_files/php.ini
    - /usr/local/etc/php/
  - Name: volume
    Volumes:
    - /var/www/html/modules
  - Name: volume
    Volumes:
    - /var/www/html/themes
  - Name: volume
    Volumes:
    - /var/www/html/override
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_files/docker_run.sh
    - /tmp/
  - CmdLine:
    - /tmp/docker_run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: php:5.6-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6-apache
