MetaArgs: null
Stages:
- BaseName: centos:latest
  Commands:
  - Maintainer: Raymond Otto <otto@digiwhite.nl>
    Name: maintainer
  - CmdLine:
    - rpm -Uvh http://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y npm nodejs-ip git make newrelic-sysmond &&     yum -y update
      &&     yum clean all
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nodejs-wrapper
    - /usr/bin/nodejs-wrapper
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nodejs-git
    - /usr/bin/nodejs-git
  - Env:
    - Key: TZ
      Value: Europe/Amsterdam
    Name: env
  - CmdLine:
    - /usr/bin/nodejs-wrapper
    Name: cmd
    PrependShell: false
  From:
    Image: centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM centos:latest
