MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/kube-scheduler-amd64:v1.7.1
  Commands: null
  From:
    Image: gcr.io/google_containers/kube-scheduler-amd64:v1.7.1
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/kube-scheduler-amd64:v1.7.1
