MetaArgs: null
Stages:
- BaseName: plone:5.1.5
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker.cfg
    - /plone/instance/
  - Chown: plone:plone
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /plone/instance/src/quito.core
  - CmdLine:
    - gosu plone buildout -c docker.cfg
    Name: run
    PrependShell: true
  - Env:
    - Key: SACRED
      Value: none
    Name: env
  - Env:
    - Key: SANAME
      Value: quito.bot
    Name: env
  - Env:
    - Key: MATTERMOST_HOST
      Value: http://localhost
    Name: env
  From:
    Image: plone:5.1.5
  Name: ""
  Platform: ""
  SourceCode: FROM plone:5.1.5
