MetaArgs: null
Stages:
- BaseName: golang:alpine
  Commands:
  - CmdLine:
    - apk update; apk add git
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/golang/dep/cmd/dep
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: false
  From:
    Image: golang:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:alpine
