MetaArgs: null
Stages:
- BaseName: library/openjdk:8-jdk-alpine
  Commands:
  - CmdLine:
    - apk add --update --no-cache bash shadow git openssh-client docker maven &&     useradd
      -d /home/jenkins -G docker jenkins &&     mkdir -p /home/jenkins &&     chown
      jenkins /home/jenkins
    Name: run
    PrependShell: true
  - CmdLine:
    - '"dockerd"'
    Name: cmd
    PrependShell: true
  From:
    Image: library/openjdk:8-jdk-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM library/openjdk:8-jdk-alpine
