MetaArgs: null
Stages:
- BaseName: jboss/wildfly:9.0.2.Final
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - standalone.patch
    - /tmp/standalone.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - module.xml
    - $JBOSS_HOME/modules/mysql/jdbc/main/
  - Name: user
    User: root
  - CmdLine:
    - yum install -y patch  && yum clean all  && patch $JBOSS_HOME/standalone/configuration/standalone.xml
      /tmp/standalone.patch  && rm -f /tmp/standalone.patch  && curl -fsSL https://repo1.maven.org/maven2/mysql/mysql-connector-java/6.0.6/mysql-connector-java-6.0.6.jar
      > $JBOSS_HOME/modules/mysql/jdbc/main/mysql-connector-java-6.0.6.jar  && echo
      "2420a107fd55bd46541844a0f43d4cdf  $JBOSS_HOME/modules/mysql/jdbc/main/mysql-connector-java-6.0.6.jar"
      | md5sum -  && chown -R jboss:jboss $JBOSS_HOME/modules/mysql
    Name: run
    PrependShell: true
  - Name: user
    User: jboss
  From:
    Image: jboss/wildfly:9.0.2.Final
  Name: ""
  Platform: ""
  SourceCode: FROM jboss/wildfly:9.0.2.Final
