MetaArgs: null
Stages:
- BaseName: dimkr/c-dev:slim
  Commands:
  - CmdLine:
    - apt-get -qq update && apt-get -y --no-install-recommends install qemu-system-mips
      ipxe-qemu seabios netcat-traditional dnsutils openssh-client wget jq iproute2
      bridge-utils procps socat
    Name: run
    PrependShell: true
  From:
    Image: dimkr/c-dev:slim
  Name: ""
  Platform: ""
  SourceCode: FROM dimkr/c-dev:slim
