MetaArgs: null
Stages:
- BaseName: dockerfile/java:oracle-java8
  Commands:
  - Env:
    - Key: ES_VERSION
      Value: 1.4.0
    Name: env
  - CmdLine:
    - cd /tmp &&   wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
      &&   tar xvzf elasticsearch-${ES_VERSION}.tar.gz &&   rm -f elasticsearch-${ES_VERSION}.tar.gz
      &&   mv /tmp/elasticsearch-${ES_VERSION} /elasticsearch
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config/elasticsearch.yml
    - /elasticsearch/config/elasticsearch.yml
  - Name: workdir
    Path: /data
  - CmdLine:
    - /elasticsearch/bin/elasticsearch
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "9200"
  - Name: expose
    Ports:
    - "9300"
  From:
    Image: dockerfile/java:oracle-java8
  Name: ""
  Platform: ""
  SourceCode: FROM dockerfile/java:oracle-java8
