MetaArgs: null
Stages:
- BaseName: node:8.9-slim
  Commands:
  - Labels:
    - Key: '"Author"'
      Value: '"Andrew Kemp <hello@ankemp.com>"'
    Name: label
  - Labels:
    - Key: '"Version"'
      Value: '"1.0"'
    Name: label
  - Key: USER_HOME_DIR
    Name: arg
    Value: '"/tmp"'
  - Key: APP_DIR
    Name: arg
    Value: '"/app"'
  - Key: USER_ID
    Name: arg
    Value: "1000"
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: warn
    Name: env
  - Name: user
    User: root
  - CmdLine:
    - apt-get update &&   apt-get install --assume-yes sudo apt-transport-https
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - &&   echo
      "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      &&   apt-get update &&   apt-get install yarn
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $APP_DIR
  From:
    Image: node:8.9-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.9-slim
