MetaArgs: null
Stages:
- BaseName: openjdk:8u151-jre-slim-stretch
  Commands:
  - Maintainer: Krystan Honour <github.com/krystan>
    Name: maintainer
  - Name: workdir
    Path: /opt/dynamodb_local
  - CmdLine:
    - mkdir -p /opt/dynamodb_local     mkdir -p /home/dynamodb     mkdir -p /dynamodb_local_db
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -g 999 dynamodb     && useradd -r -u 999 -g dynamodb dynamodb     &&
      mkdir -p /home/dynamodb     && chown -R dynamodb:dynamodb /home/dynamodb     &&
      chown -R dynamodb:dynamodb /opt/dynamodb_local     && chown -R dynamodb:dynamodb
      /dynamodb_local_db
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update -y     && apt-get install wget -y     && wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
      -q -O - | tar -xz     && apt-get purge --auto-remove -y wget \t&& rm -rf /var/lib/apt/lists/*
      \t&& rm -rf /src/*.deb"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /dynamodb_local_db
  - Name: expose
    Ports:
    - "8000"
  - Name: user
    User: dynamodb
  - CmdLine:
    - java
    - -jar
    - DynamoDBLocal.jar
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --sharedDb
    - -inMemory
    - -port
    - "8000"
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:8u151-jre-slim-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8u151-jre-slim-stretch
