MetaArgs: null
Stages:
- BaseName: fastgenomics/scanpy:1.3.1-p36-v3
  Commands:
  - CmdLine:
    - pip3 install --no-cache-dir fastgenomics==2.0.5
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - manifest.json
    - LICENSE
    - LICENSE-THIRD-PARTY
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - my_app
    - /app/my_app
  - CmdLine:
    - python3 /app/my_app
    Name: cmd
    PrependShell: true
  From:
    Image: fastgenomics/scanpy:1.3.1-p36-v3
  Name: ""
  Platform: ""
  SourceCode: FROM fastgenomics/scanpy:1.3.1-p36-v3
