MetaArgs: null
Stages:
- As: b
  BaseName: golang:alpine
  Commands:
  - Env:
    - Key: APPDIR
      Value: /go/src/github.com/akornatskyy/sample-blog-api-go
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - $APPDIR
  - Name: workdir
    Path: $APPDIR
  - CmdLine:
    - set -ex         && apk add --no-cache git upx         && go get -v -d     &&
      CGO_ENABLED=0 go build -ldflags '-s -w -extldflags "-static"'       -o /go/bin/sample-blog-api     &&
      upx -q --brute /go/bin/sample-blog-api
    Name: run
    PrependShell: true
  From:
    Image: golang:alpine
  Name: b
  Platform: ""
  SourceCode: FROM golang:alpine as b
- BaseName: scratch
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Andriy Kornatskyy <andriy.kornatskyy@live.com>"'
    Name: label
  - Env:
    - Key: KEY
      Value: ""
    Name: env
  - Chown: ""
    From: b
    Name: copy
    SourcesAndDest:
    - /go/bin/sample-blog-api
    - /app/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - samples.json
    - /app/
  - Name: workdir
    Path: /app
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - ./sample-blog-api
    Name: cmd
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
