MetaArgs: null
Stages:
- BaseName: nginx:1.17
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"fraoustin@gmail.com"'
    Name: label
  - Env:
    - Key: SET_CONTAINER_TIMEZONE
      Value: "false"
    Name: env
  - Env:
    - Key: CONTAINER_TIMEZONE
      Value: '""'
    Name: env
  - CmdLine:
    - usermod -u 1000 www-data
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src/entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /usr/share/docker-entrypoint.pre
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /usr/share/docker-entrypoint.post
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src/00_init.sh
    - /usr/share/docker-entrypoint.pre/00_init.sh
  - CmdLine:
    - chmod +x -R /usr/share/docker-entrypoint.pre
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y         apache2-utils         nginx-extras     &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src/default.conf
    - /etc/nginx/conf.d/default.conf
  - CmdLine:
    - rm /etc/nginx/sites-enabled/default
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src/cmd/addauth.sh
    - /usr/bin/addauth
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src/cmd/rmauth.sh
    - /usr/bin/rmauth
  - CmdLine:
    - chmod +x /usr/bin/addauth
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/bin/rmauth
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /theme
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /theme/note
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /theme/note
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./note/
    - /theme/note/
  - CmdLine:
    - mkdir /login
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /share
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /share
  - Env:
    - Key: DAVUSER
      Value: user
    Name: env
  - Env:
    - Key: DAVPASSWORD
      Value: pass
    Name: env
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - app
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:1.17
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:1.17
