MetaArgs: null
Stages:
- BaseName: ubuntu:12.04
  Commands:
  - Maintainer: bortels@gmail.com
    Name: maintainer
  - CmdLine:
    - sed -i s/main/'main universe'/ /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install python-software-properties python g++ make software-properties-common
      wget unzip -y
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:chris-lea/node.js -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install nodejs -y
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/node-red/node-red/archive/0.8.1.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip 0.8.1.zip -d /opt
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/node-red-0.8.1
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1880"
  - CmdLine:
    - node
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - red.js
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:12.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:12.04
