MetaArgs: null
Stages:
- BaseName: ruby:2.3
  Commands:
  - Maintainer: peng@sleede.com
    Name: maintainer
  - CmdLine:
    - apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - Env:
    - Key: NGINX_VERSION
      Value: 1.9.7-1~jessie
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get install -y       nginx=${NGINX_VERSION}       nodejs       supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - bundle config --global frozen 1
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - /tmp/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile.lock
    - /tmp/
  - CmdLine:
    - bundle install --binstubs
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/nginx/conf.d/default.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stdout /var/log/nginx/access.log
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /dev/stderr /var/log/nginx/error.log
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/config
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/invoices
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/log
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/public/uploads
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/public/assets
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/tmp/sockets
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app/tmp/pids
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/database.yml
    - /usr/src/app/config/database.yml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/app
  - Name: volume
    Volumes:
    - /usr/src/app/invoices
  - Name: volume
    Volumes:
    - /usr/src/app/public/uploads
  - Name: volume
    Volumes:
    - /usr/src/app/public/assets
  - Name: volume
    Volumes:
    - /var/log/supervisor
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/supervisor.conf
    - /etc/supervisor/conf.d/fablab.conf
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.3
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3
