MetaArgs: null
Stages:
- BaseName: php:7.3-apache
  Commands:
  - CmdLine:
    - a2dissite 000-default.conf
    Name: run
    PrependShell: true
  - Chown: ""
    From: composer:latest
    Name: copy
    SourcesAndDest:
    - /usr/bin/composer
    - /usr/bin/composer
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends git zip unzip
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app/pinedocs
  - Name: workdir
    Path: /app/pinedocs
  - CmdLine:
    - composer install
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod
    - +x
    - /usr/bin/entrypoint
    Name: run
    PrependShell: false
  - CmdLine:
    - /usr/bin/entrypoint
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apache2-foreground
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.3-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-apache
