MetaArgs: null
Stages:
- BaseName: multiarch/alpine:armhf-v3.9
  Commands:
  - CmdLine:
    - apk add --no-cache bash su-exec
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /usr/local/bin/entrypoint.sh
  - CmdLine:
    - /usr/local/bin/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: multiarch/alpine:armhf-v3.9
  Name: ""
  Platform: ""
  SourceCode: FROM multiarch/alpine:armhf-v3.9
