MetaArgs: null
Stages:
- BaseName: instructure/ruby:2.5
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - mkdir -p /fakes3/fakes3_data_root
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /fakes3/
  - CmdLine:
    - chmod +x /fakes3/entrypoint.sh &&     chown -R docker:docker /fakes3
    Name: run
    PrependShell: true
  - Name: user
    User: docker
  - CmdLine:
    - gem install fakes3 -v 0.2.5
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4569"
  - CmdLine:
    - /fakes3/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: instructure/ruby:2.5
  Name: ""
  Platform: ""
  SourceCode: FROM instructure/ruby:2.5
