MetaArgs: null
Stages:
- BaseName: efritz/derision
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config.yaml
    - /config/
  From:
    Image: efritz/derision
  Name: ""
  Platform: ""
  SourceCode: FROM efritz/derision
