MetaArgs: null
Stages:
- BaseName: java:openjdk-8-jre
  Commands:
  - Name: expose
    Ports:
    - "1883"
    - "5672"
    - "61613"
    - "61614"
    - "61616"
    - "8161"
  - Env:
    - Key: AMQ_VERSION
      Value: 5.14.1
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - env.add
    - /
  - CmdLine:
    - useradd activemq &&     mkdir /opt/apache-activemq-${AMQ_VERSION}/data/kahadb
      -p &&     wget -O - https://archive.apache.org/dist/activemq/${AMQ_VERSION}/apache-activemq-${AMQ_VERSION}-bin.tar.gz      |
      tar zxf - -C /opt/ &&     mv /opt/apache-activemq-${AMQ_VERSION}/ /opt/apache-activemq/
      &&     chown activemq -R /opt/apache-activemq
    Name: run
    PrependShell: true
  - CmdLine:
    - echo '' >>/opt/apache-activemq/bin/env
    Name: run
    PrependShell: true
  - CmdLine:
    - cat /env.add >>/opt/apache-activemq/bin/env
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /opt/apache-activemq/data/kahadb
  - Name: user
    User: activemq
  - CmdLine:
    - /bin/sh
    - -c
    - /opt/apache-activemq/bin/activemq console
    Name: entrypoint
    PrependShell: false
  From:
    Image: java:openjdk-8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM java:openjdk-8-jre
