MetaArgs: null
Stages:
- BaseName: nimbix/ubuntu-cuda
  Commands:
  - CmdLine:
    - sudo apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y cmake
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y doxygen
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y openssl libssl-dev lcov
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -nc https://github.com/google/protobuf/archive/v3.0.2.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -nc https://github.com/protobuf-c/protobuf-c/archive/v1.2.1.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -nc https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda-repo-ubuntu1604-8-0-local_8.0.44-1_amd64-deb
      -O cuda.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Version 4" > ~/Version
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./NAE/help.html
    - /etc/NAE/help.html
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: nimbix/ubuntu-cuda
  Name: ""
  Platform: ""
  SourceCode: FROM nimbix/ubuntu-cuda
