MetaArgs: null
Stages:
- BaseName: python:3.7-alpine
  Commands:
  - Env:
    - Key: PYCURL_SSL_LIBRARY
      Value: openssl
    - Key: PYTHONPATH
      Value: .
    - Key: DOCKER
      Value: "True"
    Name: env
  - CmdLine:
    - apk --no-cache add curl-dev bash     build-base libffi-dev libressl-dev tini
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app/
  - Name: workdir
    Path: /app
  - CmdLine:
    - pip install -r /app/requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - tini
    - ./startup.sh
    Name: cmd
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  From:
    Image: python:3.7-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-alpine
