MetaArgs:
- DefaultValue: ubuntu:16.04
  Key: FROM
  ProvidedValue: null
  Value: ubuntu:16.04
Stages:
- BaseName: ${FROM}
  Commands:
  - Labels:
    - Key: org.opencontainers.image.authors
      Value: '''airship-discuss@lists.airshipit.org, irc://#airshipit@freenode'''
    Name: label
  - Labels:
    - Key: org.opencontainers.image.url
      Value: '''https://airshipit.org'''
    Name: label
  - Labels:
    - Key: org.opencontainers.image.documentation
      Value: '''https://github.com/openstack/airship-maas'''
    Name: label
  - Labels:
    - Key: org.opencontainers.image.source
      Value: '''https://git.openstack.org/openstack/airship-maas'''
    Name: label
  - Labels:
    - Key: org.opencontainers.image.vendor
      Value: '''The Airship Authors'''
    Name: label
  - Labels:
    - Key: org.opencontainers.image.licenses
      Value: '''Apache-2.0'''
    Name: label
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: container
      Value: docker
    Name: env
  - CmdLine:
    - find /etc/systemd/system          /lib/systemd/system          -path '*.wants/*'          -not
      -name '*journald*'          -not -name '*systemd-tmpfiles*'          -not -name
      '*systemd-user-sessions*'          -exec rm \{} \;
    Name: run
    PrependShell: true
  - CmdLine:
    - systemctl set-default multi-user.target
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -qq update &&     apt-get -y install sudo                        software-properties-common                        jq
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y systemd
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y rsyslog
    Name: run
    PrependShell: true
  - CmdLine:
    - systemctl enable rsyslog.service
    Name: run
    PrependShell: true
  - Env:
    - Key: MAAS_VERSION
      Value: 2.3.5-6511-gf466fdb-0ubuntu1
    Name: env
  - CmdLine:
    - rsyslogd; apt-get install -y maas-cli=$MAAS_VERSION     maas-dns=$MAAS_VERSION     maas-region-api=$MAAS_VERSION     avahi-utils     dbconfig-pgsql=2.0.4ubuntu1     iputils-ping     postgresql     tcpdump     python3-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get download maas-region-controller=$MAAS_VERSION &&     dpkg-deb --extract
      maas-region-controller*.deb maas-region-controller &&     dpkg-deb --control
      maas-region-controller*.deb maas-region-controller/DEBIAN &&     rm maas-region-controller/DEBIAN/postinst
      &&     dpkg-deb --build maas-region-controller &&     dpkg -i maas-region-controller.deb
      &&     pg_dropcluster --stop 9.5 main
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_route.patch
    - /tmp/2.3_route.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_kernel_package.patch
    - /tmp/2.3_kernel_package.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_bios_grub_partition.patch
    - /tmp/2.3_bios_grub_partition.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_bios_grub_preseed.patch
    - /tmp/2.3_bios_grub_preseed.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_maas_enlist.patch
    - /tmp/2.3_maas_enlist.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_mac_address.patch
    - /tmp/2.3_mac_address.patch
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 2.3_proxy_acl.patch
    - /tmp/2.3_proxy_acl.patch
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/maasserver && patch preseed_network.py < /tmp/2.3_route.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/maasserver && patch preseed.py < /tmp/2.3_kernel_package.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/maasserver/models && patch partition.py <
      /tmp/2.3_bios_grub_partition.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/maasserver && patch preseed_storage.py < /tmp/2.3_bios_grub_preseed.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/metadataserver/user_data/templates/snippets
      && patch maas_enlist.sh < /tmp/2.3_maas_enlist.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/provisioningserver/utils && patch ipaddr.py
      < /tmp/2.3_mac_address.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/provisioningserver/utils && patch ipaddr.py
      < /tmp/2.3_mac_address.patch
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/lib/python3/dist-packages/provisioningserver/templates/proxy && patch
      maas-proxy.conf.template < /tmp/2.3_proxy_acl.patch
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - journalctl-to-tty.service
    - /etc/systemd/system/journalctl-to-tty.service
  - CmdLine:
    - mkdir -p /etc/systemd/system/basic.target.wants ;    ln -s /etc/systemd/system/journalctl-to-tty.service
      /etc/systemd/system/basic.target.wants/journalctl-to-tty.service
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - -c
    - exec /sbin/init --log-target=console 3>&1
    Name: cmd
    PrependShell: false
  From:
    Image: ${FROM}
  Name: ""
  Platform: ""
  SourceCode: FROM ${FROM}
