MetaArgs: null
Stages:
- BaseName: appropriate/curl:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '''Luis David Barrios <cyberluisda@gmail.com>'''
    Name: label
  - CmdLine:
    - apk --no-cache add bash jq
    Name: run
    PrependShell: true
  - Env:
    - Key: DOCKERIZE_VERSION
      Value: v0.6.1
    Name: env
  - CmdLine:
    - wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz     &&
      tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz     &&
      rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
    Name: run
    PrependShell: true
  - Env:
    - Key: GRAFANA_ENDPOINT
      Value: '"http://grafana:3000"'
    Name: env
  - Env:
    - Key: GRAFANA_AUTH_BEARER
      Value: '""'
    Name: env
  - Env:
    - Key: GRAFANA_AUTH_USERPASSWD
      Value: '"admin:admin"'
    Name: env
  - Env:
    - Key: GRAFANA_WAIT_TIMEOUT
      Value: '""'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/entrypoint.sh
    - /
  - CmdLine:
    - chmod a+x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: appropriate/curl:latest
  Name: ""
  Platform: ""
  SourceCode: FROM  appropriate/curl:latest
