MetaArgs: null
Stages:
- BaseName: httpd:2.4.33
  Commands:
  - Maintainer: Hypoport
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends libapache2-mod-jk
      && rm -r /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "" >> /usr/local/apache2/conf/httpd.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Include /etc/apache2/mods-available/jk.load" >> /usr/local/apache2/conf/httpd.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Include /etc/apache2/mods-available/jk.conf" >> /usr/local/apache2/conf/httpd.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/log/apache2
    Name: run
    PrependShell: true
  From:
    Image: httpd:2.4.33
  Name: ""
  Platform: ""
  SourceCode: FROM httpd:2.4.33
