MetaArgs: null
Stages:
- BaseName: pandeiro/oracle-jdk8
  Commands:
  - Maintainer: Steven Alexander <steven.william.alexander@googlemail.com>
    Name: maintainer
  - Env:
    - Key: LEIN_ROOT
      Value: "true"
    Name: env
  - CmdLine:
    - wget -q -O /usr/bin/lein     https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein     &&
      chmod +x /usr/bin/lein
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python2.7
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y cloc
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - git clone https://github.com/adamtornhill/code-maat.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: code-maat
  - CmdLine:
    - /usr/bin/lein uberjar
    Name: run
    PrependShell: true
  - Name: workdir
    Path: target
  - CmdLine:
    - find . -name '*standalone*' -exec bash -c 'mv $0 codemaat-standalone.jar' {}
      \;
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "alias maat='java -jar /app/code-maat/target/codemaat-standalone.jar'"
      >> /root/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "alias python='python2.7'" >> /root/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - bash
    Name: entrypoint
    PrependShell: false
  From:
    Image: pandeiro/oracle-jdk8
  Name: ""
  Platform: ""
  SourceCode: FROM pandeiro/oracle-jdk8
