MetaArgs: null
Stages:
- BaseName: node:6.9.1
  Commands:
  - CmdLine:
    - npm i -g babel-cli nodemon
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - api/package.json
    - /usr/src/api/
  - Name: workdir
    Path: /usr/src/api
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - api/.
    - /usr/src/api/
  - CmdLine:
    - chmod -R +x bootstrap.js
    Name: run
    PrependShell: true
  - CmdLine:
    - nodemon bootstrap.js --env docker --exec babel-node --presets es2015,stage-2
      --watch src --watch config
    Name: cmd
    PrependShell: true
  From:
    Image: node:6.9.1
  Name: ""
  Platform: ""
  SourceCode: FROM node:6.9.1
