MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.0
  Commands:
  - Maintainer: jason <jason.zr.zhang@icloud.com>
    Name: maintainer
  From:
    Image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.0
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.0
