MetaArgs: null
Stages:
- BaseName: mysql:5.7
  Commands:
  - Env:
    - Key: MYSQL_REPLICATION_USER
      Value: replication
    Name: env
  - Env:
    - Key: MYSQL_REPLICATION_PASSWORD
      Value: replication_pass
    Name: env
  - Env:
    - Key: MYSQL_MASTER_PORT
      Value: "3306"
    Name: env
  - Env:
    - Key: MYSQL_DATABASE_DEFAULT_CHARSET
      Value: utf8mb4
    Name: env
  - Env:
    - Key: MYSQL_DATABASE_DEFAULT_COLLATE
      Value: utf8mb4_unicode_ci
    Name: env
  - Env:
    - Key: EXPIRE_LOGS_DAYS
      Value: "60"
    Name: env
  - Env:
    - Key: MAX_BINLOG_SIZE
      Value: 100M
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - replication-entrypoint.sh
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init-slave.sh
    - /usr/local/bin/
  - CmdLine:
    - ln -s usr/local/bin/replication-entrypoint.sh /replication-entrypoint.sh     &&
      ln -s usr/local/bin/init-slave.sh /init-slave.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /replication-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - mysqld
    Name: cmd
    PrependShell: false
  From:
    Image: mysql:5.7
  Name: ""
  Platform: ""
  SourceCode: FROM mysql:5.7
