MetaArgs: null
Stages:
- BaseName: python:2.7
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code
  - Name: workdir
    Path: /code
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - python setup.py install
    Name: run
    PrependShell: true
  - CmdLine:
    - /code/contrib/faafo-wrapper.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:2.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7
