MetaArgs: null
Stages:
- BaseName: ruby:2.5-alpine
  Commands:
  - CmdLine:
    - apk update && apk add --no-cache coreutils git make g++ nodejs &&     git clone
      https://github.com/lord/slate /app &&     cd /app && bundle install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  From:
    Image: ruby:2.5-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5-alpine
