MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: = "David Amom <davidamom@gmail.com>"
    Name: label
  - CmdLine:
    - apt-get update && apt-get install -y     apache2         php5         php5-common         php5-cli         php5-xdebug         phpunit         php5-mcrypt         php5-pgsql         php5-mysql         php5-sybase         php5-apcu         php5-json         php5-gd         php5-imagick         php5-curl         php5-ldap         php-soap     nano     &&
      apt-get clean && apt-get autoclean && apt-get autoremove     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: APACHE_RUN_USER
      Value: = "www-data"
    Name: env
  - Env:
    - Key: APACHE_RUN_GROUP
      Value: = "www-data"
    Name: env
  - Env:
    - Key: APACHE_LOG_DIR
      Value: = "/var/log/apache2"
    Name: env
  - Env:
    - Key: APACHE_LOCK_DIR
      Value: = "/var/lock"
    Name: env
  - Env:
    - Key: APACHE_PID_FILE
      Value: = "/var/run/apache2/apache2.pid"
    Name: env
  - Name: volume
    Volumes:
    - /var/www/html
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 000-default.conf
    - /etc/apache2/sites-available/000-default.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run
    - /usr/local/bin/run
  - CmdLine:
    - chmod +x /var/www
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/run
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/html
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - Labels:
    - Key: Description
      Value: '" Apache 2.4.7 Webserver - PHP 5.5.9"'
    Name: label
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/local/bin/run
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
