MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Horatiu Eugen Vlad <info@vlad.eu>
    Name: maintainer
  - CmdLine:
    - yum install -y epel-release &&     yum -y install java-1.8.0-openjdk.x86_64
      nss_wrapper &&     yum clean all
    Name: run
    PrependShell: true
  - Env:
    - Key: USER
      Value: elasticsearch
    Name: env
  - Env:
    - Key: HOME
      Value: /usr/share/elasticsearch
    Name: env
  - Env:
    - Key: PATH
      Value: /usr/share/elasticsearch/bin:$PATH
    Name: env
  - Env:
    - Key: ES_USER
      Value: ${USER}
    - Key: ES_GROUP
      Value: root
    - Key: ES_HOME
      Value: ${HOME}
    - Key: CONF_DIR
      Value: /etc/elasticsearch
    - Key: DATA_DIR
      Value: /var/lib/elasticsearch
    - Key: LOG_DIR
      Value: /var/log/elasticsearch
    - Key: SCRIPTS_DIR
      Value: /etc/elasticsearch/scripts
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - elasticsearch.repo
    - /etc/yum.repos.d/elasticserach.repo
  - Env:
    - Key: ELASTICSEARCH_VERSION
      Value: 5.3.0-1
    Name: env
  - CmdLine:
    - yum -y install elasticsearch-${ELASTICSEARCH_VERSION}.noarch &&     yum clean
      all
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - passwd.in
    - ${HOME}/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config
    - ${CONF_DIR}
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint
    - /
  - CmdLine:
    - for path in ${CONF_DIR} ${DATA_DIR} ${LOG_DIR} ${SCRIPTS_DIR}; do       mkdir
      -p "$path" && chmod -R ug+rwX "$path" && chown -R ${ES_USER}:${ES_GROUP} "$path";     done
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9200"
    - "9300"
  - Name: user
    User: "1000"
  - CmdLine:
    - /entrypoint
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - elasticsearch
    - -Edefault.path.conf=/etc/elasticsearch
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
