MetaArgs: null
Stages:
- As: build
  BaseName: microsoft/dotnet:2.1-sdk-alpine
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nuget.config
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.sln'
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - HomeAutio.Mqtt.Harmony/*.csproj
    - ./HomeAutio.Mqtt.Harmony/
  - CmdLine:
    - dotnet restore
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - HomeAutio.Mqtt.Harmony/.
    - ./HomeAutio.Mqtt.Harmony/
  - CmdLine:
    - dotnet build -c Release
    Name: run
    PrependShell: true
  From:
    Image: microsoft/dotnet:2.1-sdk-alpine
  Name: build
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.1-sdk-alpine AS build
- As: publish
  BaseName: build
  Commands:
  - Name: workdir
    Path: /app/HomeAutio.Mqtt.Harmony
  - CmdLine:
    - dotnet publish -o out
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 0
      Named: build
  Name: publish
  Platform: ""
  SourceCode: FROM build AS publish
- As: runtime
  BaseName: microsoft/dotnet:2.1-aspnetcore-runtime-stretch-slim-arm32v7
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: publish
    Name: copy
    SourcesAndDest:
    - /app/HomeAutio.Mqtt.Harmony/out
    - ./
  - Env:
    - Key: ENVIRONMENT
      Value: Production
    Name: env
  - Name: volume
    Volumes:
    - /app/appsettings.Production.json
    - /app/logs
  - CmdLine:
    - dotnet
    - HomeAutio.Mqtt.Harmony.dll
    Name: entrypoint
    PrependShell: false
  From:
    Image: microsoft/dotnet:2.1-aspnetcore-runtime-stretch-slim-arm32v7
  Name: runtime
  Platform: ""
  SourceCode: FROM microsoft/dotnet:2.1-aspnetcore-runtime-stretch-slim-arm32v7 AS
    runtime
