MetaArgs: null
Stages:
- BaseName: jolicode/phpenv
  Commands:
  - Maintainer: Joel Wurtz <jwurtz@jolicode.com>
    Name: maintainer
  - CmdLine:
    - MAKEFLAGS=' -j8' LDFLAGS=-lstdc++ phpenv install 5.3.29 &&     phpenv global
      5.3.29 &&     phpenv rehash &&     pear config-set php_ini $(php -r 'echo php_ini_loaded_file();')
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jolicode.ini
    - /home/.phpenv/versions/5.3.29/etc/conf.d/jolicode.ini
  From:
    Image: jolicode/phpenv
  Name: ""
  Platform: ""
  SourceCode: FROM jolicode/phpenv
