MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Nicolas Degardin <ndegardin@tribalnova.com>
    Name: maintainer
  - Env:
    - Key: PATH
      Value: .:$PATH
    Name: env
  - Env:
    - Key: TERM
      Value: xterm
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    - Key: LANGUAGE
      Value: en_US.UTF-8
    - Key: LC_CTYPE
      Value: en_US.UTF-8
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - apk add --update --no-cache socat curl tzdata findutils
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -fs /usr/share/zoneinfo/GMT /etc/localtime
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/configuration/zshrc
    - /opt/docker/zshrc
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/install-devtools.sh
    - /opt/docker/install-devtools.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/startup-timezone.sh
    - /opt/docker/startup-timezone.sh
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
