MetaArgs: null
Stages:
- BaseName: amd64/busybox
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Andrey Zhereshchin <andreyzh@ie.ibm.com>"'
    Name: label
  - Key: CHANNEL
    Name: arg
    Value: stable
  - Key: VERSION
    Name: arg
    Value: 14.5.33
  - CmdLine:
    - wget "http://packages.chef.io/files/${CHANNEL}/chef/${VERSION}/el/7/chef-${VERSION}-1.el7.x86_64.rpm"
      -O /tmp/chef-client.rpm &&     rpm2cpio /tmp/chef-client.rpm | cpio -idm &&     rm
      -rf /tmp/chef-client.rpm
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /opt/chef
  From:
    Image: amd64/busybox
  Name: ""
  Platform: ""
  SourceCode: FROM amd64/busybox
