MetaArgs: null
Stages:
- BaseName: python:3.6-alpine
  Commands:
  - CmdLine:
    - mkdir -p /config &&    pip install  elasticsearch-curator==5.7.6 &&    rm -rf
      /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config_file.yml
    - /config/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - curator
    - --config
    - /config/config_file.yml
    - /config/action_file.yml
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-alpine
