MetaArgs: null
Stages:
- BaseName: furdarius/npm-docker
  Commands:
  - Maintainer: furdarius <getlag@yandex.com>
    Name: maintainer
  - CmdLine:
    - "npm install --global bower && \techo '{ \"allow_root\": true }' > /root/.bowerrc"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - bower
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - install
    Name: cmd
    PrependShell: false
  From:
    Image: furdarius/npm-docker
  Name: ""
  Platform: ""
  SourceCode: FROM furdarius/npm-docker
