MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-alpine
  Commands:
  - Env:
    - Key: SONAR_SCANNER_VERSION
      Value: 3.0.3.778
    Name: env
  - CmdLine:
    - mkdir -p /data
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./sonar-wrapper
    - /usr/bin
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./common/sonar-await-results
    - /usr/bin/
  - CmdLine:
    - apk add --no-cache jq curl bash nodejs nodejs-npm git
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g typescript
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_PATH
      Value: '"/usr/lib/node_modules/"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - '"https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip"'
    - /
  - CmdLine:
    - unzip "sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip"
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"/sonar-scanner-${SONAR_SCANNER_VERSION}/bin:${PATH}"'
    Name: env
  - CmdLine:
    - sonar-wrapper
    Name: entrypoint
    PrependShell: false
  - Name: workdir
    Path: /data
  From:
    Image: openjdk:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-alpine
