MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Daniel E. Martin-Herranz <daniel@chronomics.co.uk>
    Name: maintainer
  - Name: workdir
    Path: /usr/local/bin
  - CmdLine:
    - apt-get update -y && apt-get install -y wget unzip less vim bzip2 make gcc zlib1g-dev
      libncurses-dev git g++ python openjdk-8-jre curl libbz2-dev liblzma-dev build-essential
      python-pip libpython2.7-dev && pip install --upgrade pip
    Name: run
    PrependShell: true
  - Env:
    - Key: DST
      Value: /tmp/
    Name: env
  - Env:
    - Key: URL
      Value: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/
    Name: env
  - Env:
    - Key: ZIP
      Value: fastqc_v0.11.7.zip
    Name: env
  - CmdLine:
    - wget $URL/$ZIP -O $DST/$ZIP && unzip - $DST/$ZIP -d $DST && rm $DST/$ZIP &&
      cd $DST/FastQC && chmod 755 fastqc && ln -s $DST/FastQC/fastqc /usr/local/bin/fastqc
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install 'cutadapt==1.15'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp/
  - CmdLine:
    - curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.4.5.tar.gz -o
      trim_galore.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvzf trim_galore.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - mv TrimGalore-0.4.5/trim_galore /usr/local/bin
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/bin
  - CmdLine:
    - git clone https://github.com/lh3/bwa && cd bwa && git checkout 9f26bfcc7780753129b60717ecab0ebba6f04b7c
      && make
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:/usr/local/bin/bwa
    Name: env
  - Name: workdir
    Path: /usr/local/
  - CmdLine:
    - wget https://github.com/samtools/samtools/releases/download/1.7/samtools-1.7.tar.bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvjf samtools-1.7.tar.bz2 && rm samtools-1.7.tar.bz2 && cd samtools-1.7     &&
      ./configure --prefix=/usr/local/bin/samtools-1.7/ && make && make install
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:/usr/local/bin/samtools-1.7/bin/
    Name: env
  - Name: workdir
    Path: /usr/local/
  - CmdLine:
    - curl -fsSL https://github.com/broadinstitute/gatk/releases/download/4.0.5.1/gatk-4.0.5.1.zip
      -o GATK.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip GATK.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - rm GATK.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/bin
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
