MetaArgs: null
Stages:
- BaseName: golang:latest
  Commands:
  - Name: workdir
    Path: /go/src/github.com/sharkrf/spk-srv
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go get -u github.com/jteeuwen/go-bindata/... && go generate && go install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 65200/udp
  - CmdLine:
    - spk-srv
    Name: cmd
    PrependShell: false
  From:
    Image: golang:latest
  Name: ""
  Platform: ""
  SourceCode: FROM golang:latest
