MetaArgs: null
Stages:
- BaseName: php:7.3-cli
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"michaels@polargold.de"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - apt update && apt install -y gnupg curl unzip git rsync
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt update && apt install -y yarn
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn global add npm
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g n
    Name: run
    PrependShell: true
  From:
    Image: php:7.3-cli
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-cli
