MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 434975BD900CCBE4F7EE1B1ED208507CA14F4FCA     &&
      echo 'deb http://packages.erlang-solutions.com/debian wheezy contrib' > /etc/apt/sources.list.d/erlang.list     &&
      apt-get update     && apt-get install -y erlang-base --no-install-recommends     &&
      apt-get install -y erlang-crypto --no-install-recommends     && rm -rf /var/lib/apt/lists/
    Name: run
    PrependShell: true
  - CmdLine:
    - erl
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
