MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y ruby rubygems
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install redis --version 4.0.0
    Name: run
    PrependShell: true
  - Maintainer: 张国凯 zhguokai@163.com
    Name: maintainer
  - CmdLine:
    - mkdir /opt/redis/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/redis/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/redis/data
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - redis
    - /opt/redis/bin
  - Name: workdir
    Path: /opt/redis/bin
  - CmdLine:
    - ./src/redis-server
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
