MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Maintainer: nise_nabe <nise.nabe@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -qq update && apt-get -y upgrade && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y rubygems libsqlite3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install mailcatcher --no-ri --no-rdoc
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1080"
  - Name: expose
    Ports:
    - "25"
  - CmdLine:
    - mailcatcher --smtp-port 25 --ip `ip addr show dev eth0 scope global | grep inet
      | awk '{print $2;}' | cut -d/ -f1` -f
    Name: cmd
    PrependShell: true
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
