MetaArgs: null
Stages:
- BaseName: daocloud.io/library/ubuntu:16.04
  Commands:
  - Maintainer: brent <836360140@qq.com>
    Name: maintainer
  - CmdLine:
    - mv /etc/apt/sources.list /etc/apt/sources.list.bak
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sources.list
    - /etc/apt/
  - CmdLine:
    - apt-get update &&     apt-get install -y wget bzip2 &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: CONDA_DIR
      Value: /opt/conda
    - Key: SHELL
      Value: /bin/bash
    - Key: NB_USER
      Value: jovyan
    - Key: NB_UID
      Value: "1000"
    - Key: NB_GID
      Value: "100"
    Name: env
  - Env:
    - Key: PATH
      Value: $CONDA_DIR/bin:$PATH
    - Key: HOME
      Value: /home/$NB_USER
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - fix-permissions
    - /usr/local/bin/fix-permissions
  - CmdLine:
    - chmod a+x /usr/local/bin/fix-permissions
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -m -s /bin/bash -N -u $NB_UID $NB_USER &&     mkdir -p $CONDA_DIR &&
      chown $NB_USER:$NB_GID $CONDA_DIR &&     fix-permissions $HOME &&     fix-permissions
      $CONDA_DIR
    Name: run
    PrependShell: true
  - Name: user
    User: $NB_USER
  - Env:
    - Key: MINICONDA_VERSION
      Value: 4.2.12
    Name: env
  - CmdLine:
    - cd /tmp && wget --quiet https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh
      &&     chmod a+x Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh &&     /bin/bash
      Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR &&     rm
      Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh &&     $CONDA_DIR/bin/conda
      config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
      &&     $CONDA_DIR/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
      &&     $CONDA_DIR/bin/conda config --remove channels defaults &&     $CONDA_DIR/bin/conda
      config --system --set show_channel_urls true &&     $CONDA_DIR/bin/conda update
      --all --quiet --yes &&     $CONDA_DIR/bin/conda clean -tipsy &&     fix-permissions
      $CONDA_DIR
    Name: run
    PrependShell: true
  - CmdLine:
    - $CONDA_DIR/bin/conda install --yes     'notebook=5.2.*'     'pandas=0.21.*'     'numpy'     'scikit-learn'     &&
      conda clean -tipsy &&     fix-permissions $CONDA_DIR
    Name: run
    PrependShell: true
  - CmdLine:
    - $CONDA_DIR/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple    'jupyter_kernel_gateway'
      && rm -rf ~/.pip ~/.cache /home/.cache /home/.pip
    Name: run
    PrependShell: true
  - CmdLine:
    - conda install hdfs3 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
      &&     conda clean -tipsy &&     fix-permissions $CONDA_DIR
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - idswutils.tar
    - .
  - CmdLine:
    - $CONDA_DIR/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple    idswutils.tar
      && rm -rf ~/.pip ~/.cache /home/.cache /home/.pip
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - mkdir $HOME/workdir
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $HOME/workdir
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - open_api.ipynb
    - $HOME
  - Name: expose
    Ports:
    - "8888"
  - CmdLine:
    - jupyter
    - kernelgateway
    - --KernelGatewayApp.ip=0.0.0.0
    - --KernelGatewayApp.api=kernel_gateway.notebook_http
    - --KernelGatewayApp.allow_origin='*'
    Name: entrypoint
    PrependShell: false
  From:
    Image: daocloud.io/library/ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM daocloud.io/library/ubuntu:16.04
