MetaArgs: null
Stages:
- BaseName: mono:4
  Commands:
  - Env:
    - Key: GRPC_CSHARP_VERSION
      Value: 1.0.0
    Name: env
  - CmdLine:
    - nuget update -self
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt && nuget install Grpc.Tools -Version ${GRPC_CSHARP_VERSION} && chmod
      +x /opt/Grpc.Tools.${GRPC_CSHARP_VERSION}/tools/linux_x64/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"/opt/Grpc.Tools.${GRPC_CSHARP_VERSION}/tools/linux_x64/:${PATH}"'
    Name: env
  From:
    Image: mono:4
  Name: ""
  Platform: ""
  SourceCode: FROM mono:4
