MetaArgs: null
Stages:
- BaseName: node:8.2.1-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"gareth.lloyd@stfc.ac.uk"'
    Name: label
  - CmdLine:
    - mkdir -p /usr/src/
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src/server.js
    - /usr/src/server.js
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - node
    - server.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:8.2.1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.2.1-alpine
