MetaArgs: null
Stages:
- BaseName: node:6
  Commands:
  - Name: workdir
    Path: /opt/trambar-push-relay
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - ./
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src
    - src/
  - Name: workdir
    Path: /opt/trambar-push-relay/src
  From:
    Image: node:6
  Name: ""
  Platform: ""
  SourceCode: FROM node:6
