MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Maintainer: Spyros Trigazis <strigazi@gmail.com>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache dmidecode e2fsprogs xfsprogs ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rexray-musl
    - /usr/bin/rexray
  - CmdLine:
    - /bin/chmod +x /usr/bin/rexray
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "7979"
  - CmdLine:
    - /usr/bin/rexray
    - service
    - start
    - -f
    - -l
    - info
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
