MetaArgs: null
Stages:
- BaseName: nextcloud:fpm
  Commands:
  - CmdLine:
    - set -x     && apt update -qq    && apt install -y --auto-remove nginx sudo
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/nginx/sites-enabled/default
    - /etc/nginx/sites-enabled/default
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/nginx/nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/*.sh
    - /
  - CmdLine:
    - set -x && apt install -y --auto-remove supervisor     && chmod 755 /*.sh     &&
      mkdir /var/run/php && chown -R 82:82 /var/run/php     && apt-get autoremove
      -y    && rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archives/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/supervisord/supervisord.conf
    - /etc/supervisor/supervisord.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/supervisord/conf.d/
    - /etc/supervisor/conf.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/php/php-fpm.d/www.conf
    - /usr/local/etc/php-fpm.d/www.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/php/php-fpm.d/zz-docker.conf
    - /usr/local/etc/php-fpm.d/zz-docker.conf
  - CmdLine:
    - /bin/sh
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nextcloud:fpm
  Name: ""
  Platform: ""
  SourceCode: FROM nextcloud:fpm
