MetaArgs: null
Stages:
- BaseName: node:12
  Commands:
  - CmdLine:
    - apt-get -q update &&     apt-get -qy install openjdk-8-jre-headless curl wget
      clang &&     rm -r /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - verification-server
    - .
  - CmdLine:
    - curl https://api.github.com/repos/utwente-fmt/vercors/releases/latest |     grep
      "browser_download_url.*deb" |     cut -d '"' -f 4 |     xargs -n1 wget -q -O
      vercors.deb &&     dpkg -i vercors.deb &&     rm vercors.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:12
  Name: ""
  Platform: ""
  SourceCode: FROM node:12
