MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Stanley Förster <stanley.foerster@gmail.com>
    Name: maintainer
  - Env:
    - Key: USER
      Value: user
    Name: env
  - Env:
    - Key: HOME
      Value: /home/${USER}
    Name: env
  - Env:
    - Key: QT_MAJOR
      Value: "5"
    Name: env
  - Env:
    - Key: QT_MINOR
      Value: "8"
    Name: env
  - Env:
    - Key: QT_PATCH
      Value: "0"
    Name: env
  - Env:
    - Key: QT_FIX
      Value: ${QT_FIX}
    Name: env
  - Env:
    - Key: QT_QPA_PLATFORM
      Value: minimal
    Name: env
  - Env:
    - Key: QT_DIR
      Value: ${HOME}/qt
    Name: env
  - Env:
    - Key: QT_INSTALLER
      Value: qt-opensource-linux-x64-${QT_MAJOR}.${QT_MINOR}.${QT_PATCH}${QT_FIX}.run
    Name: env
  - Env:
    - Key: PATH
      Value: ${PATH}:${QT_DIR}/${QT_MAJOR}.${QT_MINOR}/gcc_64/bin
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - setup.qs
    - /tmp/
  - CmdLine:
    - "apt-get -qq update && \tapt-get -qq -y install \t\tcurl \t\tgit \t\tbuild-essential
      \t\tlibgl1-mesa-dev \t\tlibfontconfig1-dev \t\tlibdbus-1-dev && \tapt-get -qq
      clean"
    Name: run
    PrependShell: true
  - CmdLine:
    - "curl -sL --retry 10 --retry-delay 10 -o /tmp/${QT_INSTALLER} https://download.qt.io/official_releases/qt/${QT_MAJOR}.${QT_MINOR}/${QT_MAJOR}.${QT_MINOR}.${QT_PATCH}/${QT_INSTALLER}
      && \tchmod +x /tmp/${QT_INSTALLER} && \t/tmp/${QT_INSTALLER} --no-force-installations
      --script /tmp/setup.qs && \trm -f /tmp/${QT_INSTALLER} /tmp/setup.qs"
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
