MetaArgs: null
Stages:
- BaseName: nginx
  Commands:
  - CmdLine:
    - '{       echo ''proxy_connect_timeout 10m;'';       echo ''proxy_send_timeout
      10m;'';       echo ''proxy_read_timeout 10m;'';       echo ''send_timeout 10m;'';       echo
      ''client_max_body_size 100m;'';     } > /etc/nginx/conf.d/extended_timeouts.conf'
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - '"/etc/nginx/conf.d"'
  - Name: volume
    Volumes:
    - '"/etc/nginx/vhost.d"'
  - Name: volume
    Volumes:
    - '"/usr/share/nginx/html"'
  - Name: volume
    Volumes:
    - '"/etc/nginx/certs"'
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./html
    - /usr/share/nginx/html
  From:
    Image: nginx
  Name: ""
  Platform: ""
  SourceCode: FROM nginx
