MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/defaultbackend:1.4
  Commands:
  - Maintainer: fulinlin <fulinlin@foxmail.com>
    Name: maintainer
  From:
    Image: gcr.io/google_containers/defaultbackend:1.4
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/defaultbackend:1.4
