MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Maintainer: putty182
    Name: maintainer
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive     apt-get update     && apt-get upgrade -y     &&
      apt-get install -y deluge-web
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/if s.hexdigest() == config\["pwd_sha1"\]:/if True:/' /usr/lib/python2.7/dist-packages/deluge/ui/web/auth.py;     sed
      -i 's/onShow:function(){this.passwordField.focus(.*)}/onShow:function(){this.onLogin();}/'
      /usr/lib/python2.7/dist-packages/deluge/ui/web/js/deluge-all.js;
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - Name: expose
    Ports:
    - 8112/tcp
  - CmdLine:
    - deluge-web
    - -c
    - /config/
    Name: cmd
    PrependShell: false
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
