MetaArgs: null
Stages:
- BaseName: runmymind/docker-android-sdk:latest
  Commands:
  - Maintainer: jake.kirilenko@gmail.com
    Name: maintainer
  - Env:
    - Key: _JAVA_OPTIONS
      Value: '"-Xmx3000m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2
        -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"'
    Name: env
  - Env:
    - Key: PATH
      Value: '"/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/tools/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/bin:/usr/local/bin:$PATH"'
    Name: env
  - CmdLine:
    - apt-get update && apt-get full-upgrade -y && apt-get install -y openssh-client
      valgrind cmake g++ zlib1g-dev libglib2.0-dev libjpeg-dev&& curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
      | bash && apt-get install git-lfs && sdkmanager                "tools"                "ndk-bundle"                "platforms;android-28"                "cmake;3.10.2.4988404"                "lldb;3.1"                "platform-tools"                "build-tools;27.0.3"   &&
      sdkmanager --update
    Name: run
    PrependShell: true
  - Env:
    - Key: ANDROID_HOME
      Value: '"/opt/android-sdk-linux"'
    Name: env
  - Env:
    - Key: ANDROID_NDK_HOME
      Value: '"/opt/android-sdk-linux/ndk-bundle"'
    Name: env
  From:
    Image: runmymind/docker-android-sdk:latest
  Name: ""
  Platform: ""
  SourceCode: FROM runmymind/docker-android-sdk:latest
