MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Jordan Jethwa
    Name: maintainer
  - Labels:
    - Key: version
      Value: '"2.4.10"'
    Name: label
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: ICINGA2_FEATURE_GRAPHITE
      Value: "false"
    Name: env
  - Env:
    - Key: ICINGA2_FEATURE_GRAPHITE_HOST
      Value: graphite
    Name: env
  - Env:
    - Key: ICINGA2_FEATURE_GRAPHITE_PORT
      Value: "2003"
    Name: env
  - CmdLine:
    - apt-get -qq update     && apt-get -qqy upgrade     && apt-get -qqy install --no-install-recommends
      bash sudo procps ca-certificates wget supervisor mysql-server mysql-client apache2
      pwgen unzip php5-ldap ssmtp mailutils vim php5-curl
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --quiet -O - http://debmon.org/debmon/repo.key 2>/dev/null | apt-key add
      -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://debmon.org/debmon debmon-jessie main" > /etc/apt/sources.list.d/debmon.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -qq update     && apt-get -qqy install --no-install-recommends -t debmon-jessie
      icinga2 icinga2-ido-mysql icinga-web nagios-plugins icingaweb2     && apt-get
      clean
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/icingaweb2/enabledModules
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --no-cookies "https://github.com/Icinga/icingaweb2/archive/v2.3.2.zip"
      -O /tmp/icingaweb2.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip /tmp/icingaweb2.zip "icingaweb2-2.3.2/modules/doc/*" "icingaweb2-2.3.2/modules/monitoring/*"
      -d "/tmp/icingaweb2"
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -R /tmp/icingaweb2/icingaweb2-2.3.2/modules/monitoring /etc/icingaweb2/modules/
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -R  /tmp/icingaweb2/icingaweb2-2.3.2/modules/doc /etc/icingaweb2/modules/
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/icingaweb2.zip /tmp/icingaweb2
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --no-cookies "https://github.com/Icinga/icingaweb2-module-director/archive/master.zip"
      -O /tmp/director.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip /tmp/director.zip -d "/tmp/director"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/icingaweb2/modules/director
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -R /tmp/director/icingaweb2-module-director-master/* /etc/icingaweb2/modules/director/
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/director
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "5665"
    - "80"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - content/
    - /
  - CmdLine:
    - chmod u+x /opt/supervisor/mysql_supervisor /opt/supervisor/icinga2_supervisor
      /opt/supervisor/apache2_supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+x /opt/run
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+s /bin/ping && chmod u+s /bin/ping6
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/run
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
