MetaArgs: null
Stages:
- BaseName: tensorflow/tensorflow:latest-gpu-py3-jupyter
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"deividasskiparis@hotmail.com"'
    Name: label
  - Name: workdir
    Path: '"/opt/docker"'
  - CmdLine:
    - pip3 install     matplotlib seaborn     pillow scipy pandas sklearn     pyarrow     flask
      gevent requests     s3Contents
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/*
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/*
    - ./
  - CmdLine:
    - /bin/bash
    - start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: tensorflow/tensorflow:latest-gpu-py3-jupyter
  Name: ""
  Platform: ""
  SourceCode: FROM tensorflow/tensorflow:latest-gpu-py3-jupyter
