MetaArgs: null
Stages:
- BaseName: tutum/debian:wheezy
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - apt-get -qq update     && apt-get -yqq upgrade     && apt-get -yqq install apt-utils
      locales locales-all vim mc curl wget less python-pip supervisor     && pip install
      supervisor-stdout
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - base/locale
    - /etc/default/locale
  - Chown: ""
    Name: add
    SourcesAndDest:
    - base/supervisord.conf
    - /etc/supervisor/supervisord.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - base/sv_stdout.conf
    - /etc/supervisor/conf.d/
  - CmdLine:
    - apt-get -qqy remove dbconfig-common     && apt-get -qqy install --no-install-recommends
      bash sudo procps ca-certificates wget supervisor mysql-client apache2 pwgen
      unzip php5-mysql php-apc less
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --quiet -O - http://packages.icinga.org/icinga.key | apt-key add -     &&
      echo "deb http://packages.icinga.org/debian icinga-wheezy-snapshots main" >>
      /etc/apt/sources.list     && echo "deb http://httpredir.debian.org/debian wheezy-backports
      main" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -qq update     && apt-get -qqy install --no-install-recommends libjs-jquery-ui/wheezy-backports     &&
      apt-get -qqy install --no-install-recommends icinga2 icinga2-ido-mysql nagios-plugins
      icingaweb2
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - content/
    - /
  - CmdLine:
    - mkdir /icinga2     && mkdir /icingaweb2
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+x /opt/supervisor/icinga2_supervisor /opt/supervisor/apache2_supervisor
      /opt/run
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/icingaweb2/enabledModules     && wget --quiet --no-cookies --no-check-certificate
      "https://github.com/Icinga/icingaweb2/archive/master.zip" -O /tmp/icingaweb2.zip     &&
      unzip -qq /tmp/icingaweb2.zip "icingaweb2-master/modules/doc/*" "icingaweb2-master/modules/monitoring/*"
      -d "/tmp/icingaweb2"     && cp -R /tmp/icingaweb2/icingaweb2-master/modules/monitoring
      /etc/icingaweb2/modules/     && cp -R  /tmp/icingaweb2/icingaweb2-master/modules/doc
      /etc/icingaweb2/modules/     && rm -rf /tmp/icingaweb2.zip /tmp/icingaweb2
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
    - "80"
  - Name: volume
    Volumes:
    - /icinga2
    - /icingaweb2
  - CmdLine:
    - /opt/run
    Name: entrypoint
    PrependShell: false
  From:
    Image: tutum/debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM tutum/debian:wheezy
