MetaArgs: null
Stages:
- BaseName: easyckan/easyckan:dev
  Commands:
  - Maintainer: Luiz Felipe F M Costa <luiz@thenets.org>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - dadosabertos.sh
    - /dadosabertos.sh
  - CmdLine:
    - /dadosabertos.sh
    Name: cmd
    PrependShell: true
  From:
    Image: easyckan/easyckan:dev
  Name: ""
  Platform: ""
  SourceCode: FROM easyckan/easyckan:dev
