MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Idealitsol <idealitsol@gmail.com>"'
    Name: label
  - CmdLine:
    - apk update && apk add bash
    Name: run
    PrependShell: true
  - Env:
    - Key: KUBE_LATEST_VERSION
      Value: '"v1.16.2"'
    Name: env
  - Env:
    - Key: HELM_VERSION
      Value: '"v3.0.0"'
    Name: env
  - CmdLine:
    - apk add --no-cache ca-certificates bash git openssh curl     && wget -q https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl
      -O /usr/local/bin/kubectl     && chmod +x /usr/local/bin/kubectl     && wget
      -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO
      linux-amd64/helm > /usr/local/bin/helm     && chmod +x /usr/local/bin/helm
    Name: run
    PrependShell: true
  - Env:
    - Key: HELM_HOME
      Value: /tmp/helm
    Name: env
  - CmdLine:
    - mkdir -p /tmp/helm
    Name: run
    PrependShell: true
  - CmdLine:
    - helm init
    Name: run
    PrependShell: true
  - CmdLine:
    - helm plugin install https://github.com/futuresimple/helm-secrets
    Name: run
    PrependShell: true
  - CmdLine:
    - helm plugin install https://github.com/hypnoglow/helm-s3.git
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - main
    - /opt/idealitsol/bin/
  - Env:
    - Key: PATH
      Value: '"/opt/idealitsol/bin:$PATH"'
    Name: env
  - CmdLine:
    - main
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
