MetaArgs: null
Stages:
- BaseName: osrf/ros:melodic-desktop-full
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Ignasi Andres <ignasi@ntu.ai>"'
    Name: label
  - Labels:
    - Key: description
      Value: '"A docker with a ROS configured."'
    Name: label
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - rosdep update
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash -c "source ~/.bashrc"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install python-rosinstall python-rosinstall-generator python-wstool
      build-essential -y
    Name: run
    PrependShell: true
  From:
    Image: osrf/ros:melodic-desktop-full
  Name: ""
  Platform: ""
  SourceCode: FROM osrf/ros:melodic-desktop-full
