MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /messenger/
  - Name: workdir
    Path: /messenger/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g supervisor
    Name: run
    PrependShell: true
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
