MetaArgs: null
Stages:
- BaseName: pamtrak06/ubuntu14.04-grib
  Commands:
  - CmdLine:
    - apt-get install -y python python-grib
    Name: run
    PrependShell: true
  From:
    Image: pamtrak06/ubuntu14.04-grib
  Name: ""
  Platform: ""
  SourceCode: FROM pamtrak06/ubuntu14.04-grib
