MetaArgs: null
Stages:
- BaseName: totara/docker-dev-php54:latest
  Commands:
  - CmdLine:
    - phpbrew ext install xdebug 2.4.1
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i "s|extension=xdebug.so|zendextension=xdebug.so|" /root/.phpbrew/php/php-$PHPVERSION/var/db/xdebug.ini
    Name: run
    PrependShell: true
  From:
    Image: totara/docker-dev-php54:latest
  Name: ""
  Platform: ""
  SourceCode: FROM totara/docker-dev-php54:latest
