MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: ductamnguyen@anduintransact.com
    Name: maintainer
  - Env:
    - Key: VAULT_VERSION
      Value: 0.8.3
    Name: env
  - CmdLine:
    - apt-get -y update &&     apt-get -y install wget curl python netcat jq unzip
      &&     apt-get autoremove -y &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/* &&     wget https://releases.hashicorp.com/vault/$VAULT_VERSION/vault_${VAULT_VERSION}_linux_amd64.zip
      &&     unzip vault_${VAULT_VERSION}_linux_amd64.zip &&     mv vault /usr/bin
      &&     rm vault_${VAULT_VERSION}_linux_amd64.zip &&     wget https://raw.githubusercontent.com/anduintransaction/Dockerfiles/master/vault-kube/vault-kube
      &&     mv vault-kube /usr/bin &&     chmod 755 /usr/bin/vault-kube
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
