MetaArgs: null
Stages:
- BaseName: ruby:2.2.0
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - bundle install --without development --without test
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Env:
    - Key: PORT
      Value: "80"
    Name: env
  - Env:
    - Key: HOST
      Value: 0.0.0.0
    Name: env
  - Env:
    - Key: SPAWN
      Value: "true"
    Name: env
  - CmdLine:
    - bundle
    - exec
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ruby
    - app.rb
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.2.0
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.2.0
