MetaArgs: null
Stages:
- BaseName: maven:3.2-jdk-8
  Commands:
  - Maintainer: Reto Gmür <me@farewellutopia.com>
    Name: maintainer
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /usr/src/app
  - CmdLine:
    - mvn install -DfinalName=stanbol-p3
    Name: run
    PrependShell: true
  - CmdLine:
    - java
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -jar
    - -Xmx8g
    - launcher/default/target/stanbol-p3.jar
    Name: cmd
    PrependShell: false
  From:
    Image: maven:3.2-jdk-8
  Name: ""
  Platform: ""
  SourceCode: FROM maven:3.2-jdk-8
