MetaArgs: null
Stages:
- BaseName: golang:1.10.0
  Commands:
  - Maintainer: Yasushi kobayashi <ptpadan@gmail.com>
    Name: maintainer
  - Env:
    - Key: TZ
      Value: Asia/Tokyo
    Name: env
  - CmdLine:
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - go get github.com/tockins/realize &&   go get github.com/eure/kamimai/cmd/kamimai
    Name: run
    PrependShell: true
  From:
    Image: golang:1.10.0
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.10.0
