MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Nick Lubisch <nicklubisch@online.de>
    Name: maintainer
  - Env:
    - Key: SW_GIT_TAG
      Value: latest
    Name: env
  - Env:
    - Key: SSH_USER
      Value: shopware
    Name: env
  - Env:
    - Key: SSH_PASS
      Value: shopware
    Name: env
  - Env:
    - Key: APACHE_ROOT_DIR
      Value: /var/www/shopware
    Name: env
  - Env:
    - Key: MYSQL_HOST
      Value: localhost
    Name: env
  - Env:
    - Key: MYSQL_PORT
      Value: "3306"
    Name: env
  - Env:
    - Key: MYSQL_USER
      Value: shopware
    Name: env
  - Env:
    - Key: MYSQL_PASS
      Value: shopware
    Name: env
  - Env:
    - Key: MYSQL_DBNAME
      Value: shopware
    Name: env
  - Env:
    - Key: PHP_UPLOAD_MAX_FILESIZE
      Value: 10M
    Name: env
  - Env:
    - Key: PHP_POST_MAX_SIZE
      Value: 10M
    Name: env
  - CmdLine:
    - echo "Install Packages"
    Name: run
    PrependShell: true
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get -q -y update > /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -q -y upgrade > /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -q install -y software-properties-common > /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php > /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update > /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y -q install     supervisor     sudo     bash-completion     git     htop     tree     vim     nano     curl     zip     rsync     wget     ant     mysql-server     mysql-client     openssh-server     libapache2-mod-php5.6     php5.6-cli     php5.6-curl     php5.6-gd     php5.6-mysql     php5.6-mbstring     php5.6-simplexml     php5.6-xml     php5.6-zip     php5.6-soap     libapache2-mod-php7.0     php7.0-cli     php7.0-curl     php7.0-gd     php7.0-mysql     php7.0-mbstring     php7.0-simplexml     php7.0-xml     php7.0-zip     php7.0-soap     libapache2-mod-php7.1     php7.1-cli     php7.1-curl     php7.1-gd     php7.1-mysql     php7.1-mbstring     php7.1-simplexml     php7.1-xml     php7.1-zip     php7.1-soap     php-apcu     php-xdebug     nodejs     npm      >
      /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/nodejs /usr/bin/node
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g grunt-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://shopwarelabs.github.io/sw-cli-tools/sw.phar
    Name: run
    PrependShell: true
  - CmdLine:
    - mv sw.phar /usr/bin/sw
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /usr/bin/sw
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Configure Apache"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "ServerName localhost" >> /etc/apache2/apache2.conf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/apache/apache_default
    - /etc/apache2/sites-available/000-default.conf
  - CmdLine:
    - sed -i -e "s|APACHE_ROOT_DIR|${APACHE_ROOT_DIR}|" /etc/apache2/sites-available/000-default.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite autoindex
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ${APACHE_ROOT_DIR}
    Name: run
    PrependShell: true
  - CmdLine:
    - touch ${APACHE_ROOT_DIR}/index.html
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Hello World" >> ${APACHE_ROOT_DIR}/index.html
    Name: run
    PrependShell: true
  - CmdLine:
    - /etc/init.d/apache2 start
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Configure PHP"
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri -e "s/^upload_max_filesize.*/upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}/"
      -e "s/^post_max_size.*/post_max_size = ${PHP_POST_MAX_SIZE}/" /etc/php/5.6/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri -e "s/^upload_max_filesize.*/upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}/"
      -e "s/^post_max_size.*/post_max_size = ${PHP_POST_MAX_SIZE}/" /etc/php/7.0/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri -e "s/^upload_max_filesize.*/upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}/"
      -e "s/^post_max_size.*/post_max_size = ${PHP_POST_MAX_SIZE}/" /etc/php/7.1/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Configure MySQL"
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/mysql/my.cnf
    - /etc/mysql/my.cnf
  - CmdLine:
    - echo "Configure SSH"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 0755 /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -d /var/www/ --shell /bin/bash --groups sudo "$SSH_USER"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "$SSH_PASS\n$SSH_PASS" | passwd "$SSH_USER"
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri -e "s/PermitRootLogin/#PermitRootLogin/" /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Add composer"
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://getcomposer.org/installer -P /tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - cat /tmp/installer | php -- --install-dir=/usr/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /usr/bin/composer.phar /usr/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /usr/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Add bash scripts"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/bash/install_shopware.sh
    - /install_shopware.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/bash/mysql.sh
    - /mysql.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/bash/startup.sh
    - /startup.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/bash/entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod 755 /*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "root\nroot" | passwd
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /docker/supervisor/supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - Env:
    - Key: SW_GIT_TAG
      Value: v5.2.0
    Name: env
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
    - "3306"
    - "80"
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
