MetaArgs: null
Stages:
- BaseName: voidlinux/voidlinux-musl:latest
  Commands:
  - CmdLine:
    - xbps-install -Suy;     xbps-install -uy;     xbps-install -y bash
    Name: run
    PrependShell: true
  From:
    Image: voidlinux/voidlinux-musl:latest
  Name: ""
  Platform: ""
  SourceCode: FROM voidlinux/voidlinux-musl:latest
