MetaArgs: null
Stages:
- BaseName: skegio/base
  Commands:
  - CmdLine:
    - apt-get update && apt-get install apt-transport-https language-pack-en python-pip
      -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
      &&     echo "deb https://weechat.org/ubuntu xenial main" >/etc/apt/sources.list.d/weechat.list
      &&     echo "deb-src https://weechat.org/ubuntu xenial main" >>/etc/apt/sources.list.d/weechat.list
      &&     apt-get update &&     apt-get install -y weechat-curses weechat-plugins
      perl
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install websocket-client
    Name: run
    PrependShell: true
  From:
    Image: skegio/base
  Name: ""
  Platform: ""
  SourceCode: FROM skegio/base
