MetaArgs: null
Stages:
- BaseName: golang:alpine
  Commands:
  - Maintainer: Justin Azoff <justin.azoff@gmail.com>
    Name: maintainer
  - Name: workdir
    Path: /go/src/github.com/JustinAzoff/http_flood/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/JustinAzoff/http_flood/
  - CmdLine:
    - apk add --update git
    Name: run
    PrependShell: true
  - CmdLine:
    - go get
    Name: run
    PrependShell: true
  - CmdLine:
    - go build
    Name: run
    PrependShell: true
  - CmdLine:
    - find /go
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "7070"
  - CmdLine:
    - /go/bin/http_flood
    - server
    Name: entrypoint
    PrependShell: false
  From:
    Image: golang:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM golang:alpine
