MetaArgs: null
Stages:
- BaseName: registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.7-filebeat
  Commands:
  - Maintainer: '"WilliamGuo <634206396@qq.com>"'
    Name: maintainer
  - Name: workdir
    Path: /pilot/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - filebeat.tpl
    - /pilot
  - CmdLine:
    - /pilot/entrypoint
    Name: entrypoint
    PrependShell: false
  From:
    Image: registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.7-filebeat
  Name: ""
  Platform: ""
  SourceCode: FROM registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.7-filebeat
