MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/kube-scheduler:v1.12.4
  Commands: null
  From:
    Image: k8s.gcr.io/kube-scheduler:v1.12.4
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/kube-scheduler:v1.12.4
