MetaArgs: null
Stages:
- BaseName: php:7.3-fpm-alpine
  Commands:
  - CmdLine:
    - apk add postgresql-dev &&         docker-php-ext-install pdo pdo_pgsql pgsql
    Name: run
    PrependShell: true
  From:
    Image: php:7.3-fpm-alpine
  Name: ""
  Platform: ""
  SourceCode: "FROM\tphp:7.3-fpm-alpine"
