MetaArgs: null
Stages:
- BaseName: airhacks/payara
  Commands:
  - Maintainer: Adam Bien, adam-bien.com
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./target/micro-hazelcast.war
    - ${DEPLOYMENT_DIR}
  From:
    Image: airhacks/payara
  Name: ""
  Platform: ""
  SourceCode: FROM airhacks/payara
