MetaArgs: null
Stages:
- BaseName: pandorafms/pandorafms-base
  Commands:
  - Maintainer: Pandora FMS Team <info@pandorafms.com>
    Name: maintainer
  - CmdLine:
    - yum install -y fping perl-Test-WWW-Selenium perl-Crypt-Blowfish perl-Crypt-ECB
      perl-Crypt-Rijndael perl-Net-OpenSSH
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/braa /usr/local/bin/braa
    Name: run
    PrependShell: true
  From:
    Image: pandorafms/pandorafms-base
  Name: ""
  Platform: ""
  SourceCode: FROM pandorafms/pandorafms-base
