MetaArgs: null
Stages:
- As: builder
  BaseName: pipill/armhf-alpine:edge
  Commands:
  - Maintainer: Christian Berger "christian.berger@gu.se"
    Name: maintainer
  - CmdLine:
    - cross-build-start
    Name: run
    PrependShell: false
  - CmdLine:
    - echo http://dl-4.alpinelinux.org/alpine/v3.8/main > /etc/apk/repositories &&     echo
      http://dl-4.alpinelinux.org/alpine/v3.8/community >> /etc/apk/repositories &&     apk
      update &&     apk --no-cache add         cmake         g++         git         libx11-dev         linux-headers         make         nasm         wget
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&     wget https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.90.tar.gz
      &&     tar xvzf 1.5.90.tar.gz && cd libjpeg-turbo-1.5.90 && mkdir build && cd
      build &&     cmake -D CMAKE_INSTALL_PREFIX=/usr -DENABLE_SHARED=0 .. &&     make
      -j4 && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp &&     git clone --depth 1 https://chromium.googlesource.com/libyuv/libyuv
      &&     cd libyuv &&    make -f linux.mk CFLAGS="-O2 -fomit-frame-pointer -Iinclude/
      -DHAVE_JPEG" CXXFLAGS="-O2 -fomit-frame-pointer -Iinclude/ -DHAVE_JPEG" libyuv.a
      && cp libyuv.a /usr/lib && cd include && cp -r * /usr/include
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /opt/sources
  - Name: workdir
    Path: /opt/sources
  - CmdLine:
    - mkdir build &&     cd build &&     cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/tmp
      .. &&     make && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - cross-build-end
    Name: run
    PrependShell: false
  From:
    Image: pipill/armhf-alpine:edge
  Name: builder
  Platform: ""
  SourceCode: FROM pipill/armhf-alpine:edge as builder
- BaseName: pipill/armhf-alpine:edge
  Commands:
  - Maintainer: Christian Berger "christian.berger@gu.se"
    Name: maintainer
  - CmdLine:
    - cross-build-start
    Name: run
    PrependShell: false
  - CmdLine:
    - echo http://dl-4.alpinelinux.org/alpine/v3.8/main > /etc/apk/repositories &&     echo
      http://dl-4.alpinelinux.org/alpine/v3.8/community >> /etc/apk/repositories &&     apk
      update &&     apk --no-cache add         libx11
    Name: run
    PrependShell: true
  - CmdLine:
    - cross-build-end
    Name: run
    PrependShell: false
  - Name: workdir
    Path: /usr/bin
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /tmp/bin/opendlv-device-camera-v4l
    - .
  - Env:
    - Key: NO_AT_BRIDGE
      Value: "1"
    Name: env
  - CmdLine:
    - /usr/bin/opendlv-device-camera-v4l
    Name: entrypoint
    PrependShell: false
  From:
    Image: pipill/armhf-alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM pipill/armhf-alpine:edge
