MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: Chris Jones "chris.jones@lambdastack.io"
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get install        git        ca-certificates        curl        gcc        libc6-dev        openssl        libssl-dev        pkg-config        -qqy        --no-install-recommends     &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: RUST_ARCHIVE
      Value: rust-1.14.0-x86_64-unknown-linux-gnu.tar.gz
    Name: env
  - Env:
    - Key: RUST_DOWNLOAD_URL
      Value: https://static.rust-lang.org/dist/$RUST_ARCHIVE
    Name: env
  - CmdLine:
    - mkdir /rust
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /rust
  - CmdLine:
    - curl -fsOSL $RUST_DOWNLOAD_URL     && curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum
      -c -     && tar -C /rust -xzf $RUST_ARCHIVE --strip-components=1     && rm $RUST_ARCHIVE     &&
      ./install.sh
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
