MetaArgs: null
Stages:
- BaseName: ubuntu:vivid
  Commands:
  - CmdLine:
    - curl -sSL https://get.docker.com/ | sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./wrapdocker
    - /usr/local/bin/wrapdocker
  - CmdLine:
    - chmod +x /usr/local/bin/wrapdocker
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/docker
  - CmdLine:
    - wrapdocker
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:vivid
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:vivid
