MetaArgs: null
Stages:
- BaseName: sharelatex/sharelatex:2.0.1
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"github.com/worksasintended"'
    Name: label
  - CmdLine:
    - npm install ldapjs
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - AuthenticationManager.js
    - /var/www/sharelatex/web/app/src/Features/Authentication/
  From:
    Image: sharelatex/sharelatex:2.0.1
  Name: ""
  Platform: ""
  SourceCode: FROM sharelatex/sharelatex:2.0.1
