MetaArgs: null
Stages:
- BaseName: keymetrics/pm2:latest-jessie
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: warn
    Name: env
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - CmdLine:
    - ls -al -R
    Name: run
    PrependShell: true
  - CmdLine:
    - pm2-runtime
    - start
    - pm2.json
    Name: cmd
    PrependShell: false
  From:
    Image: keymetrics/pm2:latest-jessie
  Name: ""
  Platform: ""
  SourceCode: FROM keymetrics/pm2:latest-jessie
