MetaArgs: null
Stages:
- BaseName: centos:centos7
  Commands:
  - Maintainer: The CentOS Project <cloud-ops@centos.org>
    Name: maintainer
  - CmdLine:
    - yum -y update; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install sudo epel-release; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install postgresql-server postgresql postgresql-contrib supervisor; yum
      clean all
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./postgresql-setup
    - /usr/bin/postgresql-setup
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./supervisord.conf
    - /etc/supervisord.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./start_postgres.sh
    - /start_postgres.sh
  - CmdLine:
    - sed -i 's/.*requiretty$/#Defaults requiretty/' /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/bin/postgresql-setup
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /start_postgres.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/postgresql-setup initdb
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./postgresql.conf
    - /var/lib/pgsql/data/postgresql.conf
  - CmdLine:
    - chown -v postgres.postgres /var/lib/pgsql/data/postgresql.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "host    all             all             0.0.0.0/0               md5" >>
      /var/lib/pgsql/data/pg_hba.conf
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/pgsql
  - Name: expose
    Ports:
    - "5432"
  - CmdLine:
    - /bin/bash
    - /start_postgres.sh
    Name: cmd
    PrependShell: false
  From:
    Image: centos:centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7
