MetaArgs: null
Stages:
- BaseName: debian:sid
  Commands:
  - Maintainer: Anurag Priyam <anurag08priyam@gmail.com>
    Name: maintainer
  - CmdLine:
    - echo 'APT::Install-Recommends "false";' >> /etc/apt/apt.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'APT::Install-Suggests "false";' >> /etc/apt/apt.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y       apt-utils
      locales build-essential git curl openssl ca-certificates &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.utf8
    Name: env
  - CmdLine:
    - cd /tmp/ &&       curl -o ruby-install-0.5.0.tar.gz -L https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz
      &&       tar xvf ruby-install-0.5.0.tar.gz &&       cd ruby-install-0.5.0/ &&       make
      install &&     cd /tmp/ &&       curl -o chruby-0.3.8.tar.gz -L https://github.com/postmodern/chruby/archive/v0.3.8.tar.gz
      &&       tar xvf chruby-0.3.8.tar.gz &&       cd chruby-0.3.8/ &&       make
      install &&     cd / && rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     ruby-install ruby 2.1.4 -- --disable-install-rdoc &&     rm
      -rf /var/lib/apt/lists/* &&     rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y       nodejs
      nodejs-legacy npm &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y       postgresql
      postgresql-contrib postgresql-client libpq-dev       libexpat1-dev libperlio-gzip-perl
      &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /etc/init.d/postgresql start &&    su postgres -c "psql --command \"CREATE USER
      afra WITH SUPERUSER PASSWORD 'afra';\""     && /etc/init.d/postgresql stop
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/postgresql/9.4/main/pg_hba.conf
    - /etc/postgresql/9.4/main/
  - CmdLine:
    - chmod 644 /etc/postgresql/9.4/main/pg_hba.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r afra && useradd -m -g afra afra
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /home/afra/src
  - CmdLine:
    - chown -R afra /home/afra/src/
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/afra/src
  - CmdLine:
    - /etc/init.d/postgresql start &&     su afra -s /bin/bash -c "source /usr/local/share/chruby/chruby.sh
      && chruby ruby-2.1.4 && /usr/local/src/ruby-2.1.4/bin/rake" &&     /etc/init.d/postgresql
      stop
    Name: run
    PrependShell: true
  - CmdLine:
    - /etc/init.d/postgresql start &&     su afra -s /bin/bash -c "source /usr/local/share/chruby/chruby.sh
      && chruby ruby-2.1.4 && /usr/local/src/ruby-2.1.4/bin/rake import\[data/annotations/Solenopsis_invicta/Si_gnF.gff\]"
      &&     /etc/init.d/postgresql stop
    Name: run
    PrependShell: true
  - CmdLine:
    - /etc/init.d/postgresql start && su afra -s /bin/bash -c "source /usr/local/share/chruby/chruby.sh
      && chruby ruby-2.1.4 && /usr/local/src/ruby-2.1.4/bin/rake serve"
    Name: cmd
    PrependShell: true
  From:
    Image: debian:sid
  Name: ""
  Platform: ""
  SourceCode: FROM  debian:sid
