MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Roman Gordeev <roma.gordeev@gmail.com>
    Name: maintainer
  - Env:
    - Key: COTURN_VERSION
      Value: 4.5.0.6
    Name: env
  - CmdLine:
    - mkdir /src
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x &&  apk add --no-cache --update bash curl wget make  build-base automake
      autoconf readline readline-dev  gettext libcrypto1.0 libressl libressl-dev libevent  libevent-dev
      linux-headers jq
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src
  - CmdLine:
    - set -x &&   wget --no-check-certificate https://github.com/coturn/coturn/archive/${COTURN_VERSION}.tar.gz
      &&   tar zxf ${COTURN_VERSION}.tar.gz &&   rm ${COTURN_VERSION}.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src/coturn-${COTURN_VERSION}
  - CmdLine:
    - set -x &&     ./configure &&     make install &&     rm -rf /src &&     rm -rf
      /var/cache/apk/*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 3478/udp
  - Name: expose
    Ports:
    - 3478/tcp
  - Name: expose
    Ports:
    - 3479/udp
  - Name: expose
    Ports:
    - 3479/tcp
  - Name: expose
    Ports:
    - 5349/udp
  - Name: expose
    Ports:
    - 5349/tcp
  - Name: expose
    Ports:
    - 5350/udp
  - Name: expose
    Ports:
    - 5350/tcp
  - Name: expose
    Ports:
    - 20000-65535/udp
  - Chown: ""
    Name: add
    SourcesAndDest:
    - coturn.sh
    - /coturn.sh
  - CmdLine:
    - chmod u+rx /coturn.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /coturn.sh
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
