MetaArgs: null
Stages:
- BaseName: eyedeekay/builders
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt-get update &&     apt-get -yq install g++ gcc
    Name: run
    PrependShell: true
  - Name: user
    User: user
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: true
  From:
    Image: eyedeekay/builders
  Name: ""
  Platform: ""
  SourceCode: FROM eyedeekay/builders
