MetaArgs: null
Stages:
- BaseName: centos:7.6.1810
  Commands:
  - Key: TRIDENT_VERSION
    Name: arg
    Value: '''19.01.0'''
  - CmdLine:
    - curl -L https://github.com/NetApp/trident/releases/download/v${TRIDENT_VERSION}/trident-installer-${TRIDENT_VERSION}.tar.gz
      -o trident-installer.tar.gz   && tar zxf trident-installer.tar.gz -C /usr/local/lib   &&
      rm -f trident-installer.tar.gz   && ln -s /usr/local/lib/trident-installer/tridentctl
      /usr/local/bin/tridentctl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/kubernetes.repo
    - /etc/yum.repos.d/kubernetes.repo
  - CmdLine:
    - yum install -y kubectl-1.11.10-0.x86_64
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/trident
  - CmdLine:
    - /usr/local/bin/tridentctl
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7.6.1810
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7.6.1810
