MetaArgs: null
Stages:
- BaseName: ubuntu:16.10
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --no-install-recommends ruby build-essential     git aptitude
      ruby-dev ruby-ffi
    Name: run
    PrependShell: true
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: teletype
    Name: env
  - CmdLine:
    - gem install bundler travis
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/travis-ci/travis-build ~/.travis/travis-build
    Name: run
    PrependShell: true
  - CmdLine:
    - bundle install --gemfile ~/.travis/travis-build/Gemfile
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /src
  - Name: workdir
    Path: /src
  - CmdLine:
    - travis
    - compile
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.10
