MetaArgs: null
Stages:
- BaseName: rocker/tidyverse
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./traj-converters
    - /home/traj-converters
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src
    - /home/src
  - Env:
    - Key: PATH
      Value: '"/home/src:${PATH}"'
    Name: env
  - CmdLine:
    - R -e 'install.packages(c("optparse","gam"));source("https://bioconductor.org/biocLite.R");biocLite("monocle")'
    Name: run
    PrependShell: true
  From:
    Image: rocker/tidyverse
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/tidyverse
