MetaArgs: null
Stages:
- BaseName: nginx:1.16.0-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: Justin Liu <justintwd@gmail.com>
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./data/conf/extra
    - /etc/nginx/conf.d/extra
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./data/conf/global.conf
    - /etc/nginx/conf.d/global.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./data/conf/global.conf
    - /etc/nginx/conf.d/global.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./data/static
    - /var/www/static
  - CmdLine:
    - rm -rf /etc/nginx/conf.d/default.conf
    Name: run
    PrependShell: true
  From:
    Image: nginx:1.16.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:1.16.0-alpine
