MetaArgs: null
Stages:
- BaseName: mysql:5.7
  Commands:
  - Labels:
    - Key: version
      Value: '"AC_MY_v2"'
    Name: label
  - Name: workdir
    Path: /home/anna/ProjetDocker/WPMY_app/MY
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - toto.txt
    - /tmp
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mespaquets.txt
    - .
  - CmdLine:
    - apt-get update && apt-get install -y iputils-ping
    Name: run
    PrependShell: true
  - CmdLine:
    - xargs -a mespaquets.txt apt-get install --assume-yes
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "FIN Installation Paquets MY V2" > /home/anna/ProjetDocker/WPMY_app/MY/Status_Paquets_MY.txt
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data/vol_WPMY_DB
  - Env:
    - Key: my_hostname
      Value: TICTAC
    Name: env
  - CmdLine:
    - /bin/bash
    - -c
    - while true; do echo WELCOME on A.C. Mysql Server from $my_hostname and $HOSTNAME
      V2; sleep 10; done
    Name: cmd
    PrependShell: false
  From:
    Image: mysql:5.7
  Name: ""
  Platform: ""
  SourceCode: FROM mysql:5.7
