MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-alpine
  Commands:
  - Env:
    - Key: version
      Value: '"0.35.00"'
    Name: env
  - Labels:
    - Key: maintainer
      Value: '"Ian Martin <imartin@solidyn.com>"'
    - Key: license
      Value: '"MIT"'
    - Key: vendor
      Value: '"Solidyn Solutions, Inc"'
    - Key: repo
      Value: '"https://github.com/solidyn/docker"'
    - Key: version
      Value: '"${version}"'
    Name: label
  - CmdLine:
    - 'apk --no-cache add curl tar gzip &&   adduser -D -u 9000 ec2box &&   file=$(echo
      $version | sed ''s/\.\([0-9]\+\)$/_\1/'') &&   curl -LO -# https://github.com/skavanagh/EC2Box/releases/download/v${version}/ec2box-jetty-v${file}.tar.gz
      &&   tar xvf ec2box-jetty-v${file}.tar.gz -C / &&   chown -R ec2box: /EC2Box-jetty
      &&   rm -rf ec2box*'
    Name: run
    PrependShell: true
  - Name: user
    User: ec2box
  - Name: expose
    Ports:
    - "8443"
  - Name: workdir
    Path: /EC2Box-jetty/jetty
  - CmdLine:
    - java
    - -Xmx1g
    - -jar
    - start.jar
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-alpine
