MetaArgs: null
Stages:
- As: compiler
  BaseName: debian
  Commands:
  - CmdLine:
    - apt update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install git autoconf musl gcc musl-tools make wget bzip2 -y
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / && git clone https://github.com/mkj/dropbear.git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - localoptions.h
    - /dropbear
  - CmdLine:
    - cd /dropbear && autoconf
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /dropbear && autoheader
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /dropbear && CC=musl-gcc ./configure --enable-static --disable-zlib
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /dropbear && make PROGRAMS="dbclient dropbearkey dropbearconvert"
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /dropbear && chmod +x dbclient
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / && wget https://busybox.net/downloads/busybox-1.29.3.tar.bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / && tar jxvf busybox-1.29.3.tar.bz2
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bbox
    - /busybox-1.29.3/.config
  - CmdLine:
    - cd /busybox-1.29.3 && make
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /busybox-1.29.3/sysbin && cd /busybox-1.29.3 && make CONFIG_PREFIX=./sysbin
      install
    Name: run
    PrependShell: true
  From:
    Image: debian
  Name: compiler
  Platform: ""
  SourceCode: FROM debian as compiler
- BaseName: scratch
  Commands:
  - Chown: ""
    From: compiler
    Name: copy
    SourcesAndDest:
    - /busybox-1.29.3/sysbin
    - /
  - Chown: ""
    From: compiler
    Name: copy
    SourcesAndDest:
    - /dropbear/dbclient
    - /bin/ssh
  - Chown: ""
    From: compiler
    Name: copy
    SourcesAndDest:
    - /dropbear/dropbearconvert
    - /bin/convert
  - CmdLine:
    - mkdir /root
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "cat /etc/motd && ssh -h && alias add_key='vi /root/inputkey && convert
      opensssh dropbear /root/inputkey /root/.ssh/id_dropbear'" > /etc/profile
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "root:x:0:0:root:/root:/bin/bash" > /etc/passwd
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /root/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod go-rwx /root/.ssh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - inputkey
    - /root/inputkey
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - motd
    - /etc/motd
  - CmdLine:
    - /bin/bash
    - -l
    Name: cmd
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
