MetaArgs: null
Stages:
- BaseName: itatabitovski/alpine:3.5
  Commands:
  - CmdLine:
    - apk-install dnsmasq
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/dnsmasq
    - --no-daemon
    Name: entrypoint
    PrependShell: false
  From:
    Image: itatabitovski/alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM itatabitovski/alpine:3.5
