MetaArgs: null
Stages:
- BaseName: witchman/prerender-with-redis
  Commands: null
  From:
    Image: witchman/prerender-with-redis
  Name: ""
  Platform: ""
  SourceCode: FROM witchman/prerender-with-redis
- BaseName: node
  Commands:
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y     python2.7 python-pip     libfreetype6 libfontconfig     node
      npm git
    Name: run
    PrependShell: true
  - Env:
    - Key: PRERENDER_LOGGER
      Value: "false"
    Name: env
  - Env:
    - Key: BASIC_AUTH_USERNAME
      Value: "false"
    Name: env
  - Env:
    - Key: BASIC_AUTH_PASSWORD
      Value: "false"
    Name: env
  - Env:
    - Key: AWS_ACCESS_KEY_ID
      Value: "false"
    Name: env
  - Env:
    - Key: AWS_SECRET_ACCESS_KEY
      Value: "false"
    Name: env
  - Env:
    - Key: S3_BUCKET_NAME
      Value: "false"
    Name: env
  - Env:
    - Key: REDISTOGO_URL
      Value: "false"
    Name: env
  - Env:
    - Key: REDISCLOUD_URL
      Value: "false"
    Name: env
  - Env:
    - Key: REDISGREEN_URL
      Value: "false"
    Name: env
  - Env:
    - Key: REDIS_URL
      Value: "false"
    Name: env
  - CmdLine:
    - git clone https://github.com/prerender/prerender.git /prerender
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /prerender; npm install; npm install prerender-redis-cache --save
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - prerender-redis-cache-check.sh
    - /prerender/
  - CmdLine:
    - bash /prerender/prerender-redis-cache-check.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - node
    - /prerender/server.js
    Name: cmd
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
