MetaArgs: null
Stages:
- As: builder
  BaseName: connesc/meganz-sdk:3.2.7-lib
  Commands:
  - CmdLine:
    - "apt-get update && apt-get install -y \t\tg++ \t\tlibboost-program-options1.62-dev
      \t\tmake \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/megaproxy/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - ./
  - CmdLine:
    - "make \t&& install -D -m755 megaproxy /usr/src/output/usr/bin/megaproxy"
    Name: run
    PrependShell: true
  From:
    Image: connesc/meganz-sdk:3.2.7-lib
  Name: builder
  Platform: ""
  SourceCode: FROM connesc/meganz-sdk:3.2.7-lib as builder
- BaseName: connesc/meganz-sdk:3.2.7-lib
  Commands:
  - CmdLine:
    - "apt-get update && apt-get install -y \t\tlibboost-program-options1.62.0 \t&&
      rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/src/output
    - /
  - CmdLine:
    - megaproxy
    Name: entrypoint
    PrependShell: false
  From:
    Image: connesc/meganz-sdk:3.2.7-lib
  Name: ""
  Platform: ""
  SourceCode: FROM connesc/meganz-sdk:3.2.7-lib
