MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install curl tar gzip default-jdk -y
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://sourceforge.net/projects/bbmap/files/BBMap_38.49.tar.gz/download
      | tar xvz
    Name: run
    PrependShell: true
  - CmdLine:
    - /bbmap/bbmap.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
