MetaArgs: null
Stages:
- BaseName: devopsil/puppet:3.7.0
  Commands:
  - CmdLine:
    - rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install http://yum.theforeman.org/releases/1.6/el6/x86_64/foreman-release.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install foreman-installer
    Name: run
    PrependShell: true
  - CmdLine:
    - 'puppet apply -e ''host { $::hostname: ensure => absent } -> host { "${::hostname}.docker.local":
      ip => $::ipaddress, host_aliases => [$::hostname] }'' && foreman-installer --foreman-admin-password=changeme'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - foreman-installer-answers.yaml
    - /etc/foreman/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - puppet-agent.sh
    - /
  - CmdLine:
    - foreman-installer --foreman-admin-password=changeme   && puppet agent --test   &&
      tail -f /var/log/foreman/production.log
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
  From:
    Image: devopsil/puppet:3.7.0
  Name: ""
  Platform: ""
  SourceCode: FROM devopsil/puppet:3.7.0
