MetaArgs: null
Stages:
- BaseName: java:7-jdk
  Commands:
  - Maintainer: info@miggle.co.uk
    Name: maintainer
  - Env:
    - Key: CODEBRAG_TAG
      Value: master
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get -y install nodejs npm git &&     apt-get clean
      &&     update-alternatives --install /usr/bin/node node /usr/bin/nodejs 0 &&     git
      clone https://github.com/softwaremill/codebrag.git /tmp/codebrag &&     cd /tmp/codebrag
      &&     git checkout ${CODEBRAG_TAG} &&     java -XX:MaxPermSize=1024m -jar sbt-launch.jar
      clean codebrag-ui/compile codebrag-dist/assembly &&     apt-get --purge -y remove
      nodejs npm &&     update-alternatives --remove-all node &&     apt-get --purge
      -y autoremove &&     mkdir -p /opt/codebrag &&     cp codebrag-dist/target/scala-2.10/codebrag-dist-assembly-*.jar
      /opt/codebrag/ &&     rm -rf /tmp/codebrag &&     rm -rf /root/.sbt /root/.ivy2
      /root/.npm &&     mkdir /repos
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - logback.xml
    - /opt/codebrag/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ssh.config
    - /root/.ssh/config
  - Name: workdir
    Path: /opt/codebrag
  - Name: expose
    Ports:
    - "8080"
  - Name: volume
    Volumes:
    - /repos
  - Name: volume
    Volumes:
    - /opt/codebrag/config
  - CmdLine:
    - java -Dconfig.file=/opt/codebrag/config/application.conf -Dlogback.configurationFile=/opt/codebrag/logback.xml
      -jar /opt/codebrag/codebrag-dist-assembly-*.jar
    Name: cmd
    PrependShell: true
  From:
    Image: java:7-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM java:7-jdk
