MetaArgs:
- DefaultValue: null
  Key: CUDA_MAJOR_VERSION
  ProvidedValue: null
  Value: null
- DefaultValue: null
  Key: CUDA_MINOR_VERSION
  ProvidedValue: null
  Value: null
- DefaultValue: null
  Key: UBUNTU_VERSION
  ProvidedValue: null
  Value: null
Stages:
- BaseName: nvidia/cuda:${CUDA_MAJOR_VERSION}.${CUDA_MINOR_VERSION}-cudnn7-devel-ubuntu${UBUNTU_VERSION}
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --no-install-recommends     git     lsb-release     sed     wget     gnupg2
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu $(lsb_release -sc)
      main" > /etc/apt/sources.list.d/ros-latest.list
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://packages.ros.org/ros.key -O - | apt-key add -
    Name: run
    PrependShell: true
  - Key: ROS_DISTRO
    Name: arg
    Value: null
  - CmdLine:
    - apt-get update &&     apt-get install -y --no-install-recommends     ros-${ROS_DISTRO}-ros-core     python-catkin-tools     python-pip     python-rosdep     python-rosinstall     python-vcstools     python-setuptools     python-wstool
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ~/ros/ros_chainercv_ws/src &&     cd ~/ros/ros_chainercv_ws/src &&     wstool
      init &&     wstool set knorth55/ros_chainercv https://github.com/knorth55/ros_chainercv.git
      -v master --git -y &&     wstool set locusrobotics/catkin_virtualenv https://github.com/locusrobotics/catkin_virtualenv.git
      -v 0.4.1 --git -y &&     wstool up -j 2
    Name: run
    PrependShell: true
  - Key: CUDA_MAJOR_VERSION
    Name: arg
    Value: null
  - Key: CUDA_MINOR_VERSION
    Name: arg
    Value: null
  - CmdLine:
    - cd ~/ros/ros_chainercv_ws/src/knorth55/ros_chainercv &&     sed -e 's/.*nvidia-cuda.*//g'
      -i package.xml &&     sed -e 's/cuda91/cuda'"${CUDA_MAJOR_VERSION}${CUDA_MINOR_VERSION}"'/g'
      -i requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ~/ros/ros_chainercv_ws/src &&     rosdep init &&     rosdep update &&     rosdep
      install --rosdistro ${ROS_DISTRO} -r -y -i --from-paths .
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ~/ros/ros_chainercv_ws &&     . /opt/ros/${ROS_DISTRO}/setup.sh &&     catkin
      build
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
    Name: run
    PrependShell: true
  From:
    Image: nvidia/cuda:${CUDA_MAJOR_VERSION}.${CUDA_MINOR_VERSION}-cudnn7-devel-ubuntu${UBUNTU_VERSION}
  Name: ""
  Platform: ""
  SourceCode: FROM nvidia/cuda:${CUDA_MAJOR_VERSION}.${CUDA_MINOR_VERSION}-cudnn7-devel-ubuntu${UBUNTU_VERSION}
