MetaArgs: null
Stages:
- BaseName: nginx:1.15
  Commands:
  - CmdLine:
    - rm /etc/nginx/conf.d/* && mkdir -p /etc/nginx/stream.d/
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /usr/local/bin/start_nginx
  - CmdLine:
    - start_nginx
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:1.15
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:1.15
