MetaArgs: null
Stages:
- BaseName: rdhyee/scipyserver-ansible
  Commands:
  - Maintainer: Raymond Yee  <raymond.yee@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y update --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install default-jre-headless
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
    Name: run
    PrependShell: true
  - CmdLine:
    - DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]') &&     CODENAME=$(lsb_release
      -cs) &&     echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main"
      |        tee /etc/apt/sources.list.d/mesosphere.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install mesos
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install wget
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / && wget http://apache.mirrors.pair.com/spark/spark-1.4.0/spark-1.4.0-bin-hadoop1.tgz
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / &&     tar -xvpf /spark-1.4.0-bin-hadoop1.tgz &&     mv /spark-1.4.0-bin-hadoop1
      /spark
    Name: run
    PrependShell: true
  - Env:
    - Key: MESOS_JAVA_NATIVE_LIBRARY
      Value: /usr/local/lib/libmesos-0.21.0.so
    Name: env
  - CmdLine:
    - apt-get -y install libgfortran3
    Name: run
    PrependShell: true
  - Env:
    - Key: SPARK_HOME
      Value: /spark
    Name: env
  - Env:
    - Key: PYTHONPATH
      Value: /spark/python/:/spark/python/lib/py4j-0.8.2.1-src.zip
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - log4j.properties
    - /spark/conf/log4j.properties
  - Name: volume
    Volumes:
    - /notebooks
    - /data
  - Name: expose
    Ports:
    - "4040"
    - "8888"
  - CmdLine:
    - /notebook.sh
    Name: cmd
    PrependShell: true
  From:
    Image: rdhyee/scipyserver-ansible
  Name: ""
  Platform: ""
  SourceCode: FROM rdhyee/scipyserver-ansible
