MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Angel Cervera Claudio <angelcervera@gmail.com>
    Name: maintainer
  - Name: user
    User: root
  - Name: workdir
    Path: /root
  - Env:
    - Key: HADOOP_VERSION
      Value: 2.7.1
    Name: env
  - Env:
    - Key: HADOOP_PREFIX
      Value: /opt/hadoop
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y wget ssh rsync openjdk-7-jdk
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O /tmp/hadoop-${HADOOP_VERSION}.tar.gz http://mirrors.whoishostingthis.com/apache/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz     &&
      wget -O /tmp/hadoop-${HADOOP_VERSION}.tar.gz.mds  http://mirrors.whoishostingthis.com/apache/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz.mds
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -C /opt -xf /tmp/hadoop-${HADOOP_VERSION}.tar.gz     && ln -s /opt/hadoop-${HADOOP_VERSION}
      ${HADOOP_PREFIX}     && mkdir /var/lib/hadoop
    Name: run
    PrependShell: true
  - CmdLine:
    - ssh-keygen -q -t dsa -P '' -f /root/.ssh/id_dsa     && cat /root/.ssh/id_dsa.pub
      >> /root/.ssh/authorized_keys
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/ssh_config
    - /root/.ssh/config
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/hadoop-env.sh
    - ${HADOOP_PREFIX}/etc/hadoop/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/core-site.xml
    - ${HADOOP_PREFIX}/etc/hadoop/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/hdfs-site.xml
    - ${HADOOP_PREFIX}/etc/hadoop/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/mapred-site.xml
    - ${HADOOP_PREFIX}/etc/hadoop/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/yarn-site.xml
    - ${HADOOP_PREFIX}/etc/hadoop/
  - CmdLine:
    - ${HADOOP_PREFIX}/bin/hdfs namenode -format
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/docker_entrypoint.sh
    - /root/
  - CmdLine:
    - chmod a+x /root/docker_entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /root/shared &&     chmod a+rwX /root/shared
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -r /var/cache/apt /var/lib/apt/lists /tmp/hadoop-${HADOOP_VERSION}.tar*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "2181"
  - Name: expose
    Ports:
    - "9000"
  - Name: expose
    Ports:
    - "21"
  - Name: expose
    Ports:
    - "50070"
    - "50470"
  - Name: expose
    Ports:
    - "50075"
    - "50475"
  - Name: expose
    Ports:
    - "50010"
    - "50020"
  - Name: expose
    Ports:
    - "50090"
    - "50090"
  - Name: expose
    Ports:
    - "50100"
    - "50105"
  - Name: expose
    Ports:
    - "8480"
    - "8481"
    - "8485"
  - Name: expose
    Ports:
    - "50060"
  - Name: expose
    Ports:
    - "50030"
  - Name: expose
    Ports:
    - "19888"
  - Name: expose
    Ports:
    - "10033"
  - Name: expose
    Ports:
    - "10020"
  - Name: expose
    Ports:
    - "8032"
  - Name: expose
    Ports:
    - "8030"
  - Name: expose
    Ports:
    - "8088"
    - "8090"
  - Name: expose
    Ports:
    - "8031"
  - Name: expose
    Ports:
    - "8033"
  - Name: expose
    Ports:
    - "8040"
  - Name: expose
    Ports:
    - "8042"
  - Name: expose
    Ports:
    - "10200"
  - Name: expose
    Ports:
    - "8188"
    - "8190"
  - Name: expose
    Ports:
    - "8047"
  - Name: expose
    Ports:
    - "8788"
  - Name: expose
    Ports:
    - "8046"
  - Name: expose
    Ports:
    - "8045"
  - Name: expose
    Ports:
    - "22"
  - Name: volume
    Volumes:
    - /opt/hadoop/logs
    - /root/shared
  - CmdLine:
    - /root/docker_entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
