MetaArgs: null
Stages:
- BaseName: charliek/openjdk-jre-7
  Commands:
  - Maintainer: Shay Erlichmen "shay@samba.me"
    Name: maintainer
  - Env:
    - Key: GRAYLOG_HOME
      Value: /opt/graylog2-server
    Name: env
  - Env:
    - Key: GRAYLOG_VER
      Value: 0.92.0-beta.1
    Name: env
  - Name: workdir
    Path: /opt/
  - CmdLine:
    - curl -L http://packages.graylog2.org/releases/graylog2-server/graylog2-server-${GRAYLOG_VER}.tgz
      | tar zx
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /opt/graylog2-server-${GRAYLOG_VER} ${GRAYLOG_HOME}
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /opt/graylog2-server/graylog2.conf.example /etc/graylog2.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - java -Delasticsearch -Des.path.home="/opt" $properties -cp "$GRAYLOG_HOME/*"
      org.elasticsearch.plugins.PluginManager -install elasticsearch/elasticsearch-cloud-gce/2.3.0
    Name: run
    PrependShell: true
  - CmdLine:
    - java -Delasticsearch -Des.path.home="/opt" $properties -cp "$GRAYLOG_HOME/*"
      org.elasticsearch.plugins.PluginManager -install elasticsearch/elasticsearch-cloud-aws/2.3.0
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "12900"
  - CmdLine:
    - java
    - -jar
    - /opt/graylog2-server/graylog2-server.jar
    Name: cmd
    PrependShell: false
  From:
    Image: charliek/openjdk-jre-7
  Name: ""
  Platform: ""
  SourceCode: FROM charliek/openjdk-jre-7
