MetaArgs: null
Stages:
- BaseName: governikus/eidas-base-container:1.0.7
  Commands:
  - Maintainer: Benny Prange <benny.prange@governikus.de>
    Name: maintainer
  - Name: user
    User: eidas-middleware
  - Name: workdir
    Path: /opt/eidas-middleware
  - CmdLine:
    - mkdir /opt/eidas-middleware/config
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/Governikus/eidas-middleware/releases/download/${VERSION}/eidas-demo-${VERSION}.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - mv eidas-demo*.jar eidas-demo.jar &&    mkdir -p ${CONFIG_DIR}
    Name: run
    PrependShell: true
  - CmdLine:
    - java
    - -jar
    - ./eidas-demo.jar
    Name: entrypoint
    PrependShell: false
  From:
    Image: governikus/eidas-base-container:1.0.7
  Name: ""
  Platform: ""
  SourceCode: FROM governikus/eidas-base-container:1.0.7
