MetaArgs: null
Stages:
- As: builder
  BaseName: rust:1.39
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y cmake golang curl libpcre3-dev zlib1g-dev
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /build
  - CmdLine:
    - git clone --recursive https://github.com/cloudflare/quiche.git &&     curl -q
      -s https://nginx.org/download/nginx-1.16.1.tar.gz | tar xzf - &&     cd nginx-1.16.1
      && patch -p1 -i ../quiche/extras/nginx/nginx-1.16.patch
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /build/nginx-1.16.1
  - CmdLine:
    - "./configure         --build=\"quiche-$(git --git-dir=../quiche/.git rev-parse
      --short HEAD)\"    \t    --with-http_ssl_module    \t    --with-http_v2_module
      \   \t    --with-http_v3_module    \t    --with-openssl=../quiche/deps/boringssl
      \   \t    --with-quiche=../quiche &&     make -j`nproc` &&     make install"
    Name: run
    PrependShell: true
  From:
    Image: rust:1.39
  Name: builder
  Platform: ""
  SourceCode: FROM rust:1.39 AS builder
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y ca-certificates libpcre3 zlib1g procps
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/local/nginx
    - /usr/local/nginx
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /build/quiche/examples/cert.*
    - /usr/local/nginx/conf/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /usr/local/nginx/conf/nginx.conf
  - Name: expose
    Ports:
    - 8080/tcp
  - Name: expose
    Ports:
    - 8443/tcp
  - Name: expose
    Ports:
    - 8443/udp
  - CmdLine:
    - /usr/local/nginx/sbin/nginx
    - -g
    - daemon off;
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
