MetaArgs: null
Stages:
- BaseName: necbaas/fluentd-plugin-mongo
  Commands:
  - CmdLine:
    - apk --no-cache add libintl     && apk --no-cache add --virtual .gettext gettext     &&
      cp /usr/bin/envsubst /usr/local/bin/envsubst     && apk del .gettext
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /fluentd/etc/conf.d /fluentd/plugins
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - create_user.template.rb
    - /fluentd/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bootstrap.sh
    - /fluentd/
  - CmdLine:
    - chmod +x /fluentd/bootstrap.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - fluent.conf
    - /fluentd/etc/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - baas.template.conf
    - /fluentd/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - baas-replset.template.conf
    - /fluentd/
  - CmdLine:
    - chmod -R ugo+rw /fluentd /tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - /fluentd/bootstrap.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ""
    Name: cmd
    PrependShell: false
  From:
    Image: necbaas/fluentd-plugin-mongo
  Name: ""
  Platform: ""
  SourceCode: FROM necbaas/fluentd-plugin-mongo
