MetaArgs: null
Stages:
- BaseName: ruby:alpine
  Commands:
  - Name: workdir
    Path: /sidekiq-cloudwatch
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /sidekiq-cloudwatch
  - CmdLine:
    - bundle install --without development test
    Name: run
    PrependShell: true
  - CmdLine:
    - ./example.rb
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:alpine
