MetaArgs: null
Stages:
- BaseName: ubuntu:bionic
  Commands:
  - Env:
    - Key: LC_ALL
      Value: en_GB.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: en_GB.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_GB.UTF-8
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - echo "APT::Acquire::Retries=16;" >> /etc/apt/apt.conf.d/99_retries
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --fix-missing sudo apt-utils aptitude dirmngr locales
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo locale-gen en_GB.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-reconfigure locales
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install whois zsh tmux atop aria2 curl pv nodejs npm python-dev ruby-dev
      dkms linux-kernel-headers golang
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install lm-sensors mercurial git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install build-essential cmake intltool
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install xorg
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install meld
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install gajim
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install lm-sensors
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install terminator
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install python3-pip python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install freecad
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install keepass2
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install libncurses5-dev libgnome2-dev libgnomeui-dev
      libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev
      libxt-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y --fix-missing install gsmartcontrol redshift gtk-redshift gparted
      solaar glances silversearcher-ag  retext kdiff3
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /root/dev/
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/vim/vim.git --recursive /root/dev/vim
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /root/dev/vim && ./configure --with-features=huge     --enable-multibyte     --enable-rubyinterp     --enable-python3interp=yes     --enable-luainterp     --enable-gui=no     --enable-cscope
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /root/dev/vim && make -j`nproc`
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /root/dev/vim && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sSf https://sh.rustup.rs > /tmp/blastoff.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /tmp/blastoff.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /tmp/blastoff.sh -y
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -f /tmp/blastoff.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup update
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup install stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup install nightly
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup default stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rls --toolchain stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add clippy --toolchain stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rustfmt --toolchain stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rust-analysis --toolchain stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rust-src --toolchain stable
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rls --toolchain nightly
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add clippy --toolchain nightly
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rustfmt --toolchain nightly
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rust-analysis --toolchain nightly
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup component add rust-src --toolchain nightly
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/cargo install cargo-update rustsym ripgrep fd-find genpass
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/cargo install-update -a
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:bionic
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:bionic
