MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Env:
    - Key: GIT_REV
      Value: develop
    Name: env
  - Env:
    - Key: CLOTO_SETTINGS_FILE
      Value: /etc/fiware.d/fiware-cloto.cfg
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install  python-dev    libpq-dev libmysqlclient-dev libpq-dev    git
      curl libffi-dev zip python-mysqldb   supervisor netcat python-clips build-essential
      gcc
    Name: run
    PrependShell: true
  - CmdLine:
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    Name: run
    PrependShell: true
  - CmdLine:
    - python get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/telefonicaid/fiware-cloto /opt/fiware-cloto
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/fiware-cloto
  - CmdLine:
    - git checkout ${GIT_REV}
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/fiware.d/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/log/fiware-cloto
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - fiware-cloto.cfg
    - /etc/fiware.d/fiware-cloto.cfg
  - CmdLine:
    - cp utils/cloto_start /etc/fiware.d/
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /etc/fiware.d/cloto_start
    Name: run
    PrependShell: true
  - CmdLine:
    - cp utils/fiware-cloto.conf /etc/supervisor/conf.d
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - start.sh
  - CmdLine:
    - ./start.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
