MetaArgs: null
Stages:
- BaseName: python:3-slim
  Commands:
  - CmdLine:
    - pip install puaa==0.3.2
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - uaa.yml
    - /etc/uaa.yml
  - Name: expose
    Ports:
    - "8000"
  - Env:
    - Key: AUTHLIB_INSECURE_TRANSPORT
      Value: "true"
    Name: env
  - CmdLine:
    - gunicorn -k gevent -b 0.0.0.0 puaa.app:app
    Name: cmd
    PrependShell: true
  From:
    Image: python:3-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3-slim
