MetaArgs: null
Stages:
- BaseName: wodby/php:7.3
  Commands:
  - Name: workdir
    Path: /var/www/html
  - CmdLine:
    - set -ex;         composer create-project slim/slim-skeleton /var/www/html;     composer
      require overtrue/wechat:~4.1;         composer clear-cache;         rm -rf logs;     files_link
      logs;
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/*
    - public/
  From:
    Image: wodby/php:7.3
  Name: ""
  Platform: ""
  SourceCode: FROM wodby/php:7.3
