MetaArgs: null
Stages:
- BaseName: centos:latest
  Commands:
  - CmdLine:
    - yum -y update       && yum install wget -y       && yum install java-1.8.0-openjdk
      java-1.8.0-openjdk-devel -y       && yum clean all
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el8_0.x86_64
    Name: env
  From:
    Image: centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM centos:latest
