MetaArgs: null
Stages:
- As: builder
  BaseName: hashicorp/terraform:full
  Commands:
  - Env:
    - Key: GO111MODULE
      Value: '"on"'
    Name: env
  - Name: workdir
    Path: /terraform-provider-zendesk
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - go.mod
    - go.sum
    - /terraform-provider-zendesk/
  - CmdLine:
    - go mod tidy
    Name: run
    PrependShell: true
  - CmdLine:
    - go mod download
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go build .
    Name: run
    PrependShell: true
  From:
    Image: hashicorp/terraform:full
  Name: builder
  Platform: ""
  SourceCode: FROM hashicorp/terraform:full AS builder
- BaseName: hashicorp/terraform:light
  Commands:
  - Name: workdir
    Path: /terraform
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /terraform-provider-zendesk/terraform-provider-zendesk
    - /bin/
  From:
    Image: hashicorp/terraform:light
  Name: ""
  Platform: ""
  SourceCode: FROM hashicorp/terraform:light
