MetaArgs: null
Stages:
- BaseName: genee/gini:latest
  Commands:
  - Maintainer: PiHiZi <pihizi@msn.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y install php5-dev
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - /start
    Name: cmd
    PrependShell: false
  From:
    Image: genee/gini:latest
  Name: ""
  Platform: ""
  SourceCode: FROM genee/gini:latest
