MetaArgs: null
Stages:
- BaseName: ruby:2.3
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y nodejs git postgresql-client --no-install-recommends
    Name: run
    PrependShell: true
  - Env:
    - Key: RAILS_VERSION
      Value: 4.2.6
    Name: env
  - CmdLine:
    - gem install rails --version "$RAILS_VERSION"
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/SUSE/Portus.git /srv/portus
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /srv/portus
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Env:
    - Key: RAILS_ENV
      Value: production
    Name: env
  - Env:
    - Key: RACK_ENV
      Value: production
    Name: env
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - rails
    - server
    - -b
    - 0.0.0.0
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.3
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3
