MetaArgs: null
Stages:
- BaseName: centurylink/apache-php
  Commands:
  - Maintainer: inhumantsar
    Name: maintainer
  - CmdLine:
    - "apt-get update && \t\tDEBIAN_FRONTEND=noninteractive apt-get -y upgrade"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - "rm -rf /app/* && \t\tgit clone -b master https://github.com/joomla/joomla-cms.git
      ."
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/html
    Name: run
    PrependShell: true
  From:
    Image: centurylink/apache-php
  Name: ""
  Platform: ""
  SourceCode: FROM centurylink/apache-php
