MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - CmdLine:
    - echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libapache2-mod-php5 php5-mongo mongodb-server
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /var/www/html/index.html
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /var/www/html
  - CmdLine:
    - /etc/init.d/mongodb start && /etc/init.d/apache2 start && while true; do sleep
      1000; done
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
