MetaArgs: null
Stages:
- BaseName: haproxy:1-alpine
  Commands:
  - CmdLine:
    - apk add --no-cache tini
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache tzdata     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./another-entrypoint.sh
    - /another-entrypoint.sh
  - CmdLine:
    - tini
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --
    - /another-entrypoint.sh
    - haproxy
    - -f
    - /usr/local/etc/haproxy/haproxy.cfg
    Name: cmd
    PrependShell: false
  From:
    Image: haproxy:1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM haproxy:1-alpine
