MetaArgs: null
Stages:
- BaseName: jmashburn/lemp-centos
  Commands:
  - Env:
    - Key: IMAGE_TAGS
      Value: web,nginx
    Name: env
  - Env:
    - Key: IMAGE_WANTS
      Value: mysql
    Name: env
  - Env:
    - Key: IMAGE_DESCRIPTION
      Value: '"Retext Web Application"'
    Name: env
  - Env:
    - Key: IMAGE_EXPOSE_SERVICES
      Value: '"80/http,3306/tcp:mysql"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/default.conf
    - /etc/nginx/conf.d/default.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/run.sh
    - /run.sh
  - CmdLine:
    - chmod 755 /*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/jmashburn/retext.git /tmp/retext && mv /tmp/retext/*
      /var/www/ && rm -rf /tmp/retext
    Name: run
    PrependShell: true
  - CmdLine:
    - /etc/init.d/php-fpm start
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/supervisord.conf
    - /etc/
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
      --filename=composer
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 777 /var/lib/php/session
    Name: run
    PrependShell: true
  - CmdLine:
    - chown apache.apache -R /var/www/var
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: jmashburn/lemp-centos
  Name: ""
  Platform: ""
  SourceCode: FROM jmashburn/lemp-centos
