MetaArgs: null
Stages:
- BaseName: aneundorf/centos5-build-svn
  Commands:
  - Maintainer: alexander.neundorf@sharpreflections.com
    Name: maintainer
  - CmdLine:
    - yum update -y &&     yum install openssh-server openssh-clients -y
    Name: run
    PrependShell: true
  From:
    Image: aneundorf/centos5-build-svn
  Name: ""
  Platform: ""
  SourceCode: FROM aneundorf/centos5-build-svn
