MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-alpine
  Commands:
  - Env:
    - Key: XMAGE_DOCKER_SERVER_ADDRESS
      Value: '"0.0.0.0"'
    - Key: XMAGE_DOCKER_PORT
      Value: '"17171"'
    - Key: XMAGE_DOCKER_SEONDARY_BIND_PORT
      Value: '"17179"'
    - Key: XMAGE_DOCKER_MAX_SECONDS_IDLE
      Value: '"600"'
    - Key: XMAGE_DOCKER_AUTHENTICATION_ACTIVATED
      Value: '"false"'
    - Key: XMAGE_DOCKER_SERVER_NAME
      Value: '"mage-server"'
    Name: env
  - CmdLine:
    - set -ex &&     apk upgrade --update &&     apk add --update curl jq
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /xmage
  - CmdLine:
    - 'curl --silent --show-error http://xmage.de/xmage/config.json | jq ''.XMage.location''
      | xargs curl -# -L > xmage.zip  && unzip xmage.zip -x "mage-client*"  && rm
      xmage.zip  && apk del curl jq #redo'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - dockerStartServer.sh
    - /xmage/mage-server/
  - CmdLine:
    - dos2unix /xmage/mage-server/dockerStartServer.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x     /xmage/mage-server/startServer.sh     /xmage/mage-server/dockerStartServer.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "17171"
    - "17179"
  - Name: workdir
    Path: /xmage/mage-server
  - CmdLine:
    - ./dockerStartServer.sh
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-alpine
