MetaArgs: null
Stages:
- BaseName: jupyter/tensorflow-notebook
  Commands:
  - Name: user
    User: $NB_USER
  - CmdLine:
    - conda install --quiet --yes     -c conda-forge python-graphviz &&    conda clean
      -tipsy && fix-permissions $CONDA_DIR
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir Workspace && mkdir Results && mkdir Results/Hierarchical_Clustering &&
      mkdir Results/Decision_Tree && mkdir Results/Neural_Networks
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./Workspace
    - Workspace
  - Name: user
    User: $NB_USER
  From:
    Image: jupyter/tensorflow-notebook
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/tensorflow-notebook
