MetaArgs: null
Stages:
- BaseName: bolasblack/gentoo:latest
  Commands:
  - Maintainer: c4605 <bolasblack@gmail.com>
    Name: maintainer
  - CmdLine:
    - emerge dev-python/pip
    Name: run
    PrependShell: true
  - CmdLine:
    - emerge dev-python/m2crypto
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install shadowsocks
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./shadowsocks.json
    - /etc/shadowsocks.json
  From:
    Image: bolasblack/gentoo:latest
  Name: ""
  Platform: ""
  SourceCode: FROM bolasblack/gentoo:latest
