MetaArgs: null
Stages:
- BaseName: php:7.3.12-fpm-stretch
  Commands:
  - Labels:
    - Key: vendor
      Value: '"wulaphp Dev Team"'
    - Key: version
      Value: '"1.0"'
    - Key: ent.XDEBUG_REMOTE_HOST
      Value: host.docker.internal
    - Key: env.XDEBUG_REMOTE_PORT
      Value: "9000"
    - Key: env.XDEBUG_ENABLE
      Value: "0"
    - Key: env.XDEBUG_IDEKEY
      Value: PHPSTORM
    - Key: env.APCU_ENABLE
      Value: "0"
    - Key: description
      Value: '"Official wulaphp docker image with specified extensions"'
    Name: label
  - Env:
    - Key: XDEBUG_REMOTE_PORT
      Value: "9000"
    - Key: XDEBUG_ENABLE
      Value: "0"
    - Key: XDEBUG_IDEKEY
      Value: PHPSTORM
    - Key: APCU_ENABLE
      Value: "0"
    - Key: XDEBUG_REMOTE_HOST
      Value: host.docker.internal
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./exts.tar.bz2
    - /
  - CmdLine:
    - cd /scws-1.2.3/;./configure;make;make install;    cd /scws-1.2.3/phpext/;    phpize;./configure;make;make
      install;    apt-get update && apt-get install -y     libfreetype6-dev libzip-dev     libjpeg62-turbo-dev     libpng-dev
      libmemcached-dev zlib1g-dev libssl-dev libgearman-dev;    cd /pecl-gearman-gearman-2.0.5/;phpize
      && ./configure && make && make install;    docker-php-ext-install -j$(nproc)
      gd pcntl     sockets bcmath pdo_mysql opcache libxml zlib;    pecl channel-update
      pecl.php.net;    pecl install redis-5.0.2;    pecl install xdebug-2.7.2;    pecl
      install memcached-3.1.3;    pecl install igbinary-3.0.1;    pecl install apcu-5.1.17;    pecl
      install zip-1.15.4;    docker-php-ext-enable redis xdebug memcached igbinary
      apcu zip;    cd /;rm -rf /scws-1.2.3/ /pecl-gearman-gearman-2.0.5/;    echo
      "alias ll='ls --color=auto -l'" >> /root/.bashrc;    apt-get remove -y libfreetype6-dev     libjpeg62-turbo-dev     libpng-dev
      libmemcached-dev zlib1g-dev libssl-dev libzip-dev libgearman-dev;    cp /usr/local/etc/php/php.ini-development
      /usr/local/etc/php/php.ini;    echo "apc.enabled = \${APCU_ENABLE}" >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini;    apt-get
      clean;    rm -rf /tmp/pear/;    rm -rf /usr/src/php/;
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/
    - /usr/local/etc/
  - Name: volume
    Volumes:
    - /var/www/html
  - Name: workdir
    Path: /var/www/html
  From:
    Image: php:7.3.12-fpm-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3.12-fpm-stretch
