MetaArgs: null
Stages:
- BaseName: centos:centos6
  Commands:
  - Maintainer: Yongbok Kim <ruo91@yongbok.net>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/opsview.repo
    - /etc/yum.repos.d/opsview.repo
  - CmdLine:
    - rpm -ivh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
      && rm -f rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm  && yum update -y ; yum
      install -y opsview perl-DBIx-Class python-setuptools   && service mysqld start
      && mysqladmin -u root password 'opsview'  && sed -i 's/changeme/opsview/g' /usr/local/nagios/etc/opsview.conf  &&
      /usr/local/nagios/bin/db_mysql -u root -popsview  && /usr/local/nagios/bin/db_opsview
      db_install  && /usr/local/nagios/bin/db_runtime db_install  && chmod -R 777
      /var/log/opsview  && /usr/local/nagios/bin/rc.opsview gen_config
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install pip && pip install supervisor && pip install virtualenvwrapper  &&
      echo 'export WORKON_HOME=$HOME/.virtualenvs' >> /root/.bashrc  && echo 'source
      /usr/bin/virtualenvwrapper.sh' >> /root/.bashrc  && mkdir /etc/supervisord.d
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/supervisord.conf
    - /etc/supervisord.d/supervisord.conf
  - CmdLine:
    - /usr/bin/supervisord
    - -c
    - /etc/supervisord.d/supervisord.conf
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: centos:centos6
  Name: ""
  Platform: ""
  SourceCode: FROM     centos:centos6
