MetaArgs: null
Stages:
- BaseName: scandipwa/base
  Commands:
  - Labels:
    - Key: authors
      Value: '"Jurijs Jegorovs jurijs+oss@scandiweb.com"'
    Name: label
  - Labels:
    - Key: maintainer
      Value: '"Jurijs Jegorovs jurijs+oss@scandiweb.com"'
    Name: label
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - pecl install xdebug;     docker-php-ext-enable xdebug
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php-fpm
    Name: cmd
    PrependShell: false
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: scandipwa/base
  Name: ""
  Platform: ""
  SourceCode: FROM scandipwa/base
