MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.16
  Commands:
  - Maintainer: Adrian Stachurski <astachurski@gmail.com>
    Name: maintainer
  - CmdLine:
    - rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y -q unzip openjdk-7-jre-headless git
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/service/go-agent
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - gocd-agent-start.sh
    - /etc/service/go-agent/run
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://download.go.cd/gocd-deb/go-agent-15.2.0-2248.deb
    - /tmp/go-agent.deb
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - dpkg -i /tmp/go-agent.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/DAEMON=Y/DAEMON=N/' /etc/default/go-agent
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: OTP_VERSION
      Value: '"17.4"'
    Name: env
  - Env:
    - Key: OTP_VERSION_NAME
      Value: '"OTP_174"'
    Name: env
  - Env:
    - Key: HOME
      Value: /var/go
    Name: env
  - CmdLine:
    - sudo apt-get update &&    sudo apt-get install -y -q make &&    sudo apt-get
      install -y -q build-essential libncurses5-dev openssl libssl-dev fop xsltproc
      unixodbc-dev &&    sudo apt-get install -y -q libexpat1-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y -q curl &&    curl -O -s https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
      &&    chmod a+x kerl &&    cp kerl /usr/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - ./kerl update releases &&    ./kerl build ${OTP_VERSION} ${OTP_VERSION_NAME}
      &&    ./kerl install ${OTP_VERSION_NAME} /usr/${OTP_VERSION_NAME}
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/go
  - Env:
    - Key: PATH
      Value: $PATH:/usr/${OTP_VERSION_NAME}:/usr/${OTP_VERSION_NAME}/bin
    Name: env
  - Name: user
    User: go
  - CmdLine:
    - touch /var/go/.bashrc
    Name: run
    PrependShell: true
  - Name: user
    User: go
  - CmdLine:
    - echo ". /usr/${OTP_VERSION_NAME}/activate" >> /var/go/.bashrc &&    echo "export
      PATH=$PATH:/usr/${OTP_VERSION_NAME}/bin" >> /var/go/.bashrc &&    echo "PATH=$PATH:/usr/${OTP_VERSION_NAME}"
      >> /var/go/.bashrc &&    echo "export TERM=xterm-256color" >> /var/go/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir .ssh &&    ssh-keygen -b 2048 -t rsa -f .ssh/sshkey -q -N ""
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - sudo apt-get install -y -q emacs24
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  From:
    Image: phusion/baseimage:0.9.16
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.9.16
