MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - CmdLine:
    - echo "deb http://ppa.launchpad.net/nginx/stable/ubuntu $(lsb_release -sc) main"
      | sudo tee /etc/apt/sources.list.d/nginx-stable.list &&   sudo apt-key adv --keyserver
      keyserver.ubuntu.com --recv-keys C300EE8C &&   sudo apt-get -y update &&   sudo
      apt-get -y install nginx &&   usermod -u 1000 www-data &&   groupmod -g 1000
      www-data
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - default
    - /etc/nginx/sites-available/default
  - CmdLine:
    - chmod u+x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
