MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Jaspalsinh Chauhan <jachauhan@gmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install apache2
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod dav
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod dav_fs
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/apache2/sites-enabled/000-default.conf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - 000-default.conf
    - /etc/apache2/sites-available/000-default.conf
  - CmdLine:
    - mkdir /var/www/webdav
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - service apache2 stop
    Name: run
    PrependShell: true
  - CmdLine:
    - service apache2 start
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
