MetaArgs: null
Stages:
- BaseName: tutum/lamp:latest
  Commands:
  - CmdLine:
    - rm -fr /app && git clone https://github.com/pataluc/my-conf.git
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: expose
    Ports:
    - "3306"
    - "80"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: tutum/lamp:latest
  Name: ""
  Platform: ""
  SourceCode: FROM tutum/lamp:latest
