MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: L. Mangani <lorenzo.mangani@gmail.com>
    Name: maintainer
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update -qq && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys
      049AD65B && echo "deb http://apt.opensips.org jessie 2.2-releases" >>/etc/apt/sources.list
      && apt-get update -qq && apt-get install -f -yqq rsyslog opensips opensips-geoip-module
      opensips-json-module opensips-mysql-module opensips-regex-module opensips-restclient-module
      geoip-database geoip-database-extra && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/opensips
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - opensips.cfg
    - /etc/opensips/opensips.cfg
  - CmdLine:
    - chmod 775 /etc/opensips/opensips.cfg
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/lib64 /usr/lib/x86_64-linux-gnu/
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - /run.sh
  - Name: expose
    Ports:
    - "5062"
  - Name: expose
    Ports:
    - "9060"
  - CmdLine:
    - /run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
