MetaArgs: null
Stages:
- BaseName: node:lts-alpine
  Commands:
  - Key: NODE_ENV
    Name: arg
    Value: production
  - Env:
    - Key: NODE_ENV
      Value: $NODE_ENV
    Name: env
  - Key: PORT
    Name: arg
    Value: "3000"
  - Env:
    - Key: PORT
      Value: $PORT
    Name: env
  - Name: expose
    Ports:
    - $PORT
    - "9229"
    - "9230"
  - CmdLine:
    - npm i npm@latest -g
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/node_app && chown node:node /opt/node_app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/node_app
  - Name: user
    User: node
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package-lock.json*
    - ./
  - CmdLine:
    - npm install --no-optional && npm cache clean --force
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/node_app/node_modules/.bin:$PATH
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - /usr/local/bin/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:lts-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:lts-alpine
