MetaArgs: null
Stages:
- BaseName: timveil/docker-hadoop-core:3.1.x
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"tjveil@gmail.com"'
    Name: label
  - Health:
      Test:
      - CMD-SHELL
      - curl -f http://localhost:8042/ || exit 1
    Name: healthcheck
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - chmod a+x /run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8042"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: timveil/docker-hadoop-core:3.1.x
  Name: ""
  Platform: ""
  SourceCode: FROM timveil/docker-hadoop-core:3.1.x
