MetaArgs: null
Stages:
- BaseName: tomcat:7-jre7
  Commands:
  - Maintainer: '"aBelfadel <abdelhadi.belfadel@gmail.com>"'
    Name: maintainer
  - CmdLine:
    - mkdir /usr/tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /usr/tmp/FITMAN_TEST_DATA
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /usr/tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /usr/tmp/FITMAN_TEST_DATA
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/server.xml
    - /usr/local/tomcat/conf/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/tomcat-users.xml
    - /usr/local/tomcat/conf/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/mysql-connector-java-5.1.31-bin.jar
    - /usr/local/tomcat/lib/mysql-connector-java-5.1.31-bin.jar
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ME/
    - /usr/local/tomcat/webapps/
  - CmdLine:
    - ls -la /usr/local/tomcat/webapps/*
    Name: run
    PrependShell: true
  From:
    Image: tomcat:7-jre7
  Name: ""
  Platform: ""
  SourceCode: FROM tomcat:7-jre7
