MetaArgs: null
Stages:
- BaseName: jupyter/scipy-notebook:2c80cf3537ca
  Commands:
  - CmdLine:
    - conda install 'pymc'
    Name: run
    PrependShell: true
  - CmdLine:
    - conda config --add channels conda-forge
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install 'kabuki'
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install 'seaborn==0.9.0'
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install 'tqdm'
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install 'hddm'
    Name: run
    PrependShell: true
  From:
    Image: jupyter/scipy-notebook:2c80cf3537ca
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/scipy-notebook:2c80cf3537ca
