MetaArgs: null
Stages:
- BaseName: mirkokiefer/ubuntu-base
  Commands:
  - CmdLine:
    - echo deb http://archive.ubuntu.com/ubuntu precise main universe > /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - echo deb http://archive.ubuntu.com/ubuntu precise-updates main universe >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-divert --local --rename --add /sbin/initctl
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -f -s /bin/true /sbin/initctl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y mysql-server
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /sbin/my_init
    - mysqld
    Name: cmd
    PrependShell: false
  From:
    Image: mirkokiefer/ubuntu-base
  Name: ""
  Platform: ""
  SourceCode: FROM mirkokiefer/ubuntu-base
