MetaArgs: null
Stages:
- BaseName: resin/armv7hf-debian-qemu:latest
  Commands:
  - CmdLine:
    - cross-build-start
    Name: run
    PrependShell: false
  - Maintainer: Nick McCarthy
    Name: maintainer
  - CmdLine:
    - apt-get update &&   apt-get install -y cmake apt-utils build-essential &&   apt-get
      install -y libboost-dev libboost-thread-dev libboost-system-dev libsqlite3-dev
      subversion curl libcurl4-openssl-dev libusb-dev zlib1g-dev &&   apt-get install
      -y iputils-ping &&   apt-get clean &&   apt-get autoclean &&   rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/domoticz/domoticz
    - -www
    - "8080"
    Name: cmd
    PrependShell: false
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://releases.domoticz.com/releases/release/domoticz_linux_armv7l.tgz
    - /root/domoticz/
  - CmdLine:
    - cd /root/domoticz/ &&   tar -xvzf /root/domoticz/domoticz_linux_armv7l.tgz
    Name: run
    PrependShell: true
  - CmdLine:
    - cross-build-end
    Name: run
    PrependShell: false
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: resin/armv7hf-debian-qemu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM resin/armv7hf-debian-qemu:latest
