MetaArgs: null
Stages:
- BaseName: linarotechnologies/rtl-sdr:latest
  Commands:
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - apk add --no-cache alpine-sdk git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone git://github.com/mutability/dump1090.git &&     cd dump1090 &&     make
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp/dump1090
  - CmdLine:
    - ./dump1090
    - --interactive
    - --net
    - --metric
    Name: entrypoint
    PrependShell: false
  From:
    Image: linarotechnologies/rtl-sdr:latest
  Name: ""
  Platform: ""
  SourceCode: FROM linarotechnologies/rtl-sdr:latest
