MetaArgs: null
Stages:
- BaseName: hgezim/wp-nocache
  Commands:
  - CmdLine:
    - docker-php-ext-install mbstring
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update     && apt-get install git -y --force-yes
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sSL "https://getcomposer.org/installer" | php     && mv composer.phar
      /usr/local/bin/composer
    Name: run
    PrependShell: true
  From:
    Image: hgezim/wp-nocache
  Name: ""
  Platform: ""
  SourceCode: FROM hgezim/wp-nocache
