MetaArgs: null
Stages:
- BaseName: brychdaneel/archlinux-yaourt
  Commands:
  - Maintainer: Brychikov Daneel <brychdaneel@gmail.com>
    Name: maintainer
  - CmdLine:
    - sudo pacman --noconfirm -S     arduino     arduino-avr-core     lsb-release     cmake
    Name: run
    PrependShell: true
  From:
    Image: brychdaneel/archlinux-yaourt
  Name: ""
  Platform: ""
  SourceCode: FROM brychdaneel/archlinux-yaourt
