MetaArgs: null
Stages:
- BaseName: gauravraosahab/docker_node_chrome:1.0.3
  Commands:
  - CmdLine:
    - npm config set depth 0   && npm cache clean --force   && npm i -g @angular/cli@6.0.8
      --unsafe
    Name: run
    PrependShell: true
  From:
    Image: gauravraosahab/docker_node_chrome:1.0.3
  Name: ""
  Platform: ""
  SourceCode: FROM gauravraosahab/docker_node_chrome:1.0.3
