MetaArgs: null
Stages:
- BaseName: boxfuse/flyway:5.1.4
  Commands:
  - Key: REDSHIFT_DRIVER_VERSION
    Name: arg
    Value: null
  - Env:
    - Key: REDSHIFT_FALLBACK_DRIVER
      Value: 1.2.16.1027
    Name: env
  - Env:
    - Key: RDV
      Value: ${REDSHIFT_DRIVER_VERSION:-${REDSHIFT_FALLBACK_DRIVER}}
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/${RDV}/RedshiftJDBC42-${RDV}.jar
    - /flyway/drivers
  - CmdLine:
    - apt-get update && apt-get install -y netcat-openbsd
    Name: run
    PrependShell: true
  - CmdLine: null
    Name: entrypoint
    PrependShell: false
  From:
    Image: boxfuse/flyway:5.1.4
  Name: ""
  Platform: ""
  SourceCode: FROM boxfuse/flyway:5.1.4
