MetaArgs: null
Stages:
- BaseName: dockercloud/haproxy:1.6.2
  Commands:
  - CmdLine:
    - "apk add --update \t\tbash \t\topenssl \t\twget \t\tnfs-utils \t&& rm -rf /var/cache/apk/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: LIVE_CERT_FOLDER
      Value: '"/etc/letsencrypt/live"'
    Name: env
  - Env:
    - Key: PATH
      Value: '"/opt/haproxy/bin:$PATH"'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /opt/haproxy
  - CmdLine:
    - entrypoint.sh
    - dockercloud-haproxy
    Name: cmd
    PrependShell: false
  From:
    Image: dockercloud/haproxy:1.6.2
  Name: ""
  Platform: ""
  SourceCode: FROM dockercloud/haproxy:1.6.2
