MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: Andre A. Boechat <boechat107@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y -q python python-pip python-dev         libxml2-dev libxslt-dev
      libffi-dev libxslt1-dev         zlib1g-dev libssl-dev         libpq-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pymongo &&     pip install redis &&     pip install scrapy
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: from ubuntu
