MetaArgs: null
Stages:
- BaseName: gitlab/gitlab-runner:alpine-v11.8.0
  Commands:
  - CmdLine:
    - apk add --no-cache sed
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint
    - volumes.kind
    - /
  From:
    Image: gitlab/gitlab-runner:alpine-v11.8.0
  Name: ""
  Platform: ""
  SourceCode: FROM gitlab/gitlab-runner:alpine-v11.8.0
