MetaArgs: null
Stages:
- As: go-deps
  BaseName: golang:1-alpine
  Commands:
  - CmdLine:
    - apk --update add --no-cache bash git make ca-certificates
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /repos
  - Env:
    - Key: GO111MODULE
      Value: "on"
    - Key: GOOS
      Value: linux
    - Key: GOARCH
      Value: amd64
    - Key: CGO_ENABLED
      Value: "0"
    Name: env
  - CmdLine:
    - mkdir /output
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth 1 https://github.com/direnv/direnv.git && cd direnv && go
      build && mv ./direnv /output/direnv
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth 1 https://github.com/wagoodman/dive.git && cd dive && go build
      && mv ./dive /output/dive
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth 1 https://github.com/moncho/dry.git && cd dry && go build
      && mv ./dry /output/dry
    Name: run
    PrependShell: true
  From:
    Image: golang:1-alpine
  Name: go-deps
  Platform: ""
  SourceCode: FROM golang:1-alpine AS go-deps
- BaseName: docker:stable
  Commands:
  - CmdLine:
    - apk --update add --no-cache bash git curl nano vim python3 figlet
    Name: run
    PrependShell: true
  - Env:
    - Key: SANDBOX
      Value: '"true"'
    - Key: SANDCRATE
      Value: '"true"'
    - Key: PATH
      Value: '"$PATH:/usr/sandcrate/bin/:/usr/sandcrate/vendor"'
    Name: env
  - Name: workdir
    Path: /sandcrate/
  - CmdLine:
    - if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi &&     python
      -m ensurepip &&     rm -r /usr/lib/python*/ensurepip &&     pip3 install --no-cache
      --upgrade pip setuptools wheel pipenv &&     if [ ! -e /usr/bin/pip ]; then
      ln -s pip3 /usr/bin/pip ; fi
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/sandcrate/include &&     curl -L -o /usr/sandcrate/include/argsf
      https://raw.githubusercontent.com/WoLfulus/argsf/master/src/argsf.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./rootfs/
    - /
  - Chown: ""
    From: go-deps
    Name: copy
    SourcesAndDest:
    - /output/
    - /usr/sandcrate/bin/
  - CmdLine:
    - find /usr/sandcrate/bin/ -type f -exec chmod +x {} \; &&     chmod +x /usr/bin/entrypoint
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/entrypoint
    Name: entrypoint
    PrependShell: false
  From:
    Image: docker:stable
  Name: ""
  Platform: ""
  SourceCode: FROM docker:stable
