MetaArgs: null
Stages:
- BaseName: centos:centos6
  Commands:
  - Maintainer: Matteo Concas mconcas@cern.ch
    Name: maintainer
  - Env:
    - Key: TEST_USER
      Value: '"parrotuser"'
    - Key: TEST_USER_HOME
      Value: '"/home/parrotuser"'
    - Key: PATH
      Value: /opt/cctools/cctools-5.2.3-x86_64-redhat6/bin:$PATH
    - Key: CCTOOLS_URL
      Value: http://ccl.cse.nd.edu/software/files/cctools-5.2.3-x86_64-redhat6.tar.gz
    - Key: CCTOOLS_PATH
      Value: /opt/cctools
    - Key: MJ
      Value: "9"
    - Key: COMM_REQ
      Value: '"git cmake tar unzip gcc gcc-c++ patch zlib-devel openssl-devel                               openssl-devel
        make which vim libcap-2-devel"'
    - Key: ROOT_REQ
      Value: '"autoconf automake libtool libxml2-devel libX11-devel libXpm-devel                            libXft-devel
        libXext-devel mesa-libGLU-devel CGAL-devel subversion"'
    - Key: ALIROOT_REQ
      Value: '"libXpm compat-libgfortran-41 tcl                                                          compat-libtermcap
        redhat-lsb-core"'
    - Key: CONDOR_SECRET
      Value: '"@mycondorpassword@"'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - opt/p_cvmfs_env.sh
    - /home/$TEST_USER/p_cvmfs_env.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - opt/cern-it1.cern.ch.pub
    - /etc/cvmfs/keys/cern.ch/cern-it1.cern.ch.pub
  - CmdLine:
    - mkdir $CCTOOLS_PATH                                                                         &&     mkdir
      -p /cvmfs/.modulerc                                                                   &&     rpm
      --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6                                          &&     yum
      install -y which tar vim git                                                            &&     curl
      -o $CCTOOLS_PATH/cctools.tar.gz $CCTOOLS_URL                                           &&     tar
      -xvf $CCTOOLS_PATH/cctools.tar.gz -C$CCTOOLS_PATH                                       &&     useradd
      -d $TEST_USER_HOME $TEST_USER                                                       &&     chown
      -R $TEST_USER $TEST_USER_HOME                                                         &&     chown
      -R $TEST_USER /etc/cvmfs/keys/cern.ch/cern-it1.cern.ch.pub                            &&     runuser
      -l $TEST_USER -c "echo \"alias ali='source /cvmfs/alice.cern.ch/etc/login.sh'\"               >>
      $TEST_USER_HOME/.bashrc"                                                              &&     yum
      install -y $ROOT_REQ $ALIROOT_REQ
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -o /etc/yum.repos.d/htcondor-development-rhel6.repo     http://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-development-rhel6.repo
      &&     yum install -y condor
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - opt/os-release
    - /etc/os-release
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - opt/condor-centos6-worker-pilot
    - /tmp/condor-centos6-worker-pilot
  - CmdLine:
    - chmod +x /tmp/condor-centos6-worker-pilot
    Name: run
    PrependShell: true
  From:
    Image: centos:centos6
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos6
