MetaArgs: null
Stages:
- BaseName: ubuettgen/alpine-jetty9
  Commands:
  - Maintainer: Ulrich Büttgen  "ulrich@buettgen.org"
    Name: maintainer
  - CmdLine:
    - wget http://dl.bintray.com/jfrog/artifactory/artifactory-3.3.0.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip artifactory-3.3.0.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - mv artifactory-3.3.0/webapps/artifactory.war /opt/jetty/webapps
    Name: run
    PrependShell: true
  - CmdLine:
    - rm artifactory-3.3.0.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf artifactory-3.3.0
    Name: run
    PrependShell: true
  From:
    Image: ubuettgen/alpine-jetty9
  Name: ""
  Platform: ""
  SourceCode: FROM ubuettgen/alpine-jetty9
