MetaArgs: null
Stages:
- BaseName: python:2-onbuild
  Commands:
  - Maintainer: Kousha Najafi <kousha@lazyhack.com>
    Name: maintainer
  - CmdLine:
    - python
    - ./stackdriver-security-group.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:2-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM python:2-onbuild
