MetaArgs: null
Stages:
- BaseName: rails:onbuild
  Commands:
  - CmdLine:
    - rm /bin/sh && ln -s /bin/bash /bin/sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - cp database.yml.aws config/database.yml
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 700 start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 700 provision.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 700 worker.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: rails:onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM rails:onbuild
