MetaArgs: null
Stages:
- BaseName: abiskop/base
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.sh
    - /tmp/install.sh
  - CmdLine:
    - bash /tmp/install.sh
    Name: run
    PrependShell: true
  From:
    Image: abiskop/base
  Name: ""
  Platform: ""
  SourceCode: FROM abiskop/base
