MetaArgs: null
Stages:
- BaseName: ubuntu:12.04
  Commands:
  - Maintainer: Toshiaki Baba <toshiaki@netmark.jp>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "postfix postfix/main_mailer_type select Internet Site" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "postfix postfix/mailname string 127.0.0.1" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install git build-essential python-virtualenv python-dev mongodb-server
      rabbitmq-server curl libcurl4-openssl-dev stunnel4 debconf-utils postfix vim
      tree unzip supervisor curl gunicorn sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd minion
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo ''Defaults:minion !requiretty'' >> /etc/sudoers.d/minion ; echo ''minion
      ALL = NOPASSWD: ALL'' >> /etc/sudoers.d/minion ; chmod 400 /etc/sudoers.d/minion'
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/mozilla/minion.git /opt/minion
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R minion:minion /opt/minion
    Name: run
    PrependShell: true
  - CmdLine:
    - install -d -o minion -g minion /opt/minion ; install -d -o minion -g minion
      /var/log/supervisor ; install -d -o minion -g minion /opt/minion/scripts ; install
      -d -o minion -g minion /opt/minion/plugins
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /opt/minion/setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/minion && sudo -u minion ./setup.sh clone /opt/minion
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/minion && sudo -u minion ./setup.sh install /opt/minion
    Name: run
    PrependShell: true
  - CmdLine:
    - install -d -o minion -g minion /etc/minion
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - frontend.json
    - /etc/minion/frontend.json
  - CmdLine:
    - sed -i.bak "s/SECRET_VALUE/${RANDOM}${RANDOM}${RANDOM}${RANDOM}${RANDOM}/" /etc/minion/frontend.json
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo -u minion curl -o /opt/minion/plugins/skipfish.deb http://launchpadlibrarian.net/126324272/skipfish_2.10b-1_amd64.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg -i /opt/minion/plugins/skipfish.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo -u minion git clone https://github.com/mozilla/minion-skipfish-plugin /opt/minion/plugins/minion-skipfish-plugin
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/minion/plugins/minion-skipfish-plugin && python /opt/minion/plugins/minion-skipfish-plugin/setup.py
      install
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install nmap
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo -u minion git clone https://github.com/mozilla/minion-nmap-plugin /opt/minion/plugins/minion-nmap-plugin
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/minion/plugins/minion-nmap-plugin && python /opt/minion/plugins/minion-nmap-plugin/setup.py
      install
    Name: run
    PrependShell: true
  - CmdLine:
    - install -d /etc/supervisor ; install -d /etc/supervisor/conf.d
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/supervisord.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - minion-backend.supervisor.conf
    - /etc/supervisor/conf.d/minion-backend.supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - minion-plugin-worker.supervisor.conf
    - /etc/supervisor/conf.d/minion-plugin-worker.supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - minion-scan-worker.supervisor.conf
    - /etc/supervisor/conf.d/minion-scan-worker.supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - minion-state-worker.supervisor.conf
    - /etc/supervisor/conf.d/minion-state-worker.supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - minion-frontend.supervisor.conf
    - /etc/supervisor/conf.d/minion-frontend.supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - rabbitmq.supervisor.conf
    - /etc/supervisor/conf.d/rabbitmq.supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mongod.supervisor.conf
    - /etc/supervisor/conf.d/mongod.supervisor.conf
  - CmdLine:
    - locale-gen en_US en_US.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen ja_JP ja_JP.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'minion:minion' |chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sshd.supervisor.conf
    - /etc/supervisor/conf.d/sshd.supervisor.conf
  - Name: expose
    Ports:
    - "22"
    - "4369"
    - "51509"
    - "5672"
    - "8080"
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:12.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:12.04
