MetaArgs: null
Stages:
- BaseName: openjdk:8-jdk
  Commands:
  - Key: version
    Name: arg
    Value: 8.0.3
  - Key: edition
    Name: arg
    Value: ee
  - Env:
    - Key: GRAPHDB_PARENT_DIR
      Value: /opt/graphdb
    Name: env
  - Env:
    - Key: GRAPHDB_HOME
      Value: ${GRAPHDB_PARENT_DIR}/home
    Name: env
  - Env:
    - Key: GRAPHDB_INSTALL_DIR
      Value: ${GRAPHDB_PARENT_DIR}/dist
    Name: env
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - curl -fsSL "http://maven.ontotext.com/content/groups/all-onto/com/ontotext/graphdb/graphdb-${edition}/${version}/graphdb-${edition}-${version}-dist.zip"
      >     graphdb-${edition}-${version}.zip &&     bash -c 'md5sum -c - <<<"$(curl
      -fsSL http://maven.ontotext.com/content/groups/all-onto/com/ontotext/graphdb/graphdb-${edition}/${version}/graphdb-${edition}-${version}-dist.zip.md5)
      graphdb-${edition}-${version}.zip"' &&     mkdir -p ${GRAPHDB_PARENT_DIR} &&     cd
      ${GRAPHDB_PARENT_DIR} &&     unzip /tmp/graphdb-${edition}-${version}.zip &&     rm
      /tmp/graphdb-${edition}-${version}.zip &&     mv graphdb-${edition}-${version}
      dist &&     mkdir -p ${GRAPHDB_HOME}
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: ${GRAPHDB_INSTALL_DIR}/bin:$PATH
    Name: env
  - CmdLine:
    - -Dgraphdb.home=/opt/graphdb/home
    Name: cmd
    PrependShell: false
  - CmdLine:
    - /opt/graphdb/dist/bin/graphdb
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "7200"
  From:
    Image: openjdk:8-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jdk
