MetaArgs: null
Stages:
- BaseName: golang:1.10
  Commands:
  - CmdLine:
    - go get -u github.com/Masterminds/glide
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/golang/dep/cmd/dep
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/kardianos/govendor
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/tools/godep
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/golang/lint/golint
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/bradleyfalzon/apicompat/...
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u honnef.co/go/tools/cmd/gosimple
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u honnef.co/go/tools/cmd/staticcheck
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u honnef.co/go/tools/cmd/unused
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u mvdan.cc/unparam
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/mdempsky/unconvert
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/gopherci/isFileGenerated
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - install-deps.sh
    - /usr/local/bin/
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y lsb-release
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf $GOPATH/src/*
    Name: run
    PrependShell: true
  - CmdLine:
    - sleep
    - infinity
    Name: cmd
    PrependShell: false
  From:
    Image: golang:1.10
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.10
