MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: Sophie Lemoine <slemoine@biologie.ens.fr>
    Name: maintainer
  - Key: DEBIAN_FRONTEND
    Name: arg
    Value: noninteractive
  - Env:
    - Key: LANG
      Value: C.UTF-8
    - Key: LC_ALL
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: PATH
      Value: /opt/conda/bin:$PATH
    Name: env
  - CmdLine:
    - apt-get update --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y build-essential  wget  bzip2  ca-certificates  samtools  libbam-dev  libhts-dev  curl  git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean &&  rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      -O ~/miniconda.sh &&     /bin/bash ~/miniconda.sh -b -p /opt/conda &&     rm
      ~/miniconda.sh &&     /opt/conda/bin/conda clean -tipsy &&     ln -s /opt/conda/etc/profile.d/conda.sh
      /etc/profile.d/conda.sh &&     echo ". /opt/conda/etc/profile.d/conda.sh" >>
      ~/.bashrc &&     echo "conda activate base" >> ~/.bashrc
    Name: run
    PrependShell: true
  - Env:
    - Key: TINI_VERSION
      Value: v0.16.1
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini
    - /usr/bin/tini
  - CmdLine:
    - chmod +x /usr/bin/tini
    Name: run
    PrependShell: true
  - CmdLine:
    - conda install numpy  scipy  cython  numba  matplotlib  scikit-learn  h5py  click  R  rpy2
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pysam  loompy
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U --no-deps velocyto
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
