MetaArgs: null
Stages:
- BaseName: sumankhanal/rakudo:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Dr Suman Khanal <suman81765@gmail.com>"'
    Name: label
  - Env:
    - Key: NB_USER
      Value: suman
    Name: env
  - Env:
    - Key: NB_UID
      Value: "1000"
    Name: env
  - Env:
    - Key: HOME
      Value: /home/${NB_USER}
    Name: env
  - CmdLine:
    - adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:/usr/share/perl6/site/bin
    Name: env
  - CmdLine:
    - apt-get update     && apt-get install -y build-essential     wget libzmq3-dev
      ca-certificates     python3-pip python3-setuptools     && rm -rf /var/lib/apt/lists/*
      && pip3 install jupyter notebook asciinema jupyterlab pyscaffold --no-cache-dir     &&
      zef install Jupyter::Kernel --force-test     && jupyter-kernel.p6 --generate-config     &&
      ln -s /usr/share/perl6/site/bin/* /usr/local/bin
    Name: run
    PrependShell: true
  - Env:
    - Key: TINI_VERSION
      Value: v0.18.0
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini
    - /usr/bin/tini
  - CmdLine:
    - chmod +x /usr/bin/tini
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/tini
    - --
    Name: entrypoint
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./raku-notebooks/
    - ${HOME}
  - Name: user
    User: root
  - CmdLine:
    - chown -R ${NB_UID} ${HOME}
    Name: run
    PrependShell: true
  - Name: user
    User: ${NB_USER}
  - Name: workdir
    Path: ${HOME}
  - Name: expose
    Ports:
    - "8888"
  - CmdLine:
    - jupyter
    - notebook
    - --port=8888
    - --no-browser
    - --ip=0.0.0.0
    - --allow-root
    Name: cmd
    PrependShell: false
  From:
    Image: sumankhanal/rakudo:latest
  Name: ""
  Platform: ""
  SourceCode: FROM sumankhanal/rakudo:latest
