MetaArgs: null
Stages:
- BaseName: buildpack-deps:xenial
  Commands:
  - CmdLine:
    - "set -ex; \tapt-get update && apt-get install -y vim htop tree tmux sudo bash-completion
      && \tuseradd builder -m -s /bin/bash && echo \"builder:builder\" | chpasswd
      && \techo \"builder ALL = (ALL) NOPASSWD: ALL\" > /etc/sudoers.d/builder;"
    Name: run
    PrependShell: true
  - Name: user
    User: builder
  - Name: workdir
    Path: /home/builder/
  - CmdLine:
    - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"$PATH:/home/builder/depot_tools"'
    Name: env
  - CmdLine:
    - "set -ex; \tmkdir chromium && cd chromium && \tfetch --nohooks chromium"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/builder/chromium/src
  From:
    Image: buildpack-deps:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM buildpack-deps:xenial
