MetaArgs: null
Stages:
- BaseName: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  Commands:
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US:en
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init.sh
    - /
  - CmdLine:
    - /bin/bash
    - -c
    - chmod +x /entrypoint.sh && chmod +x /init.sh
    Name: run
    PrependShell: false
  - CmdLine:
    - apt-get update &&     apt-get install -y curl &&     curl https://packages.microsoft.com/keys/microsoft.asc
      | apt-key add - &&     curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list
      | tee /etc/apt/sources.list.d/mssql-server.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y mssql-server-fts
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1433"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/mssql/server:2017-latest-ubuntu
