MetaArgs: null
Stages:
- BaseName: php:7.1-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - apk add --no-cache wget     && wget https://getcomposer.org/composer.phar     &&
      php composer.phar --working-dir=/app install --no-dev --no-interaction     &&
      rm composer.phar     && apk del wget
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - php
    - ./migrate.php
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.1-alpine
