MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: martino.trevisan@polito.it
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install     apt-transport-https     ca-certificates     curl     software-properties-common     sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository     "deb [arch=amd64] https://download.docker.com/linux/ubuntu     $(lsb_release
      -cs)     stable"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install docker-ce
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - awk '{if($1 == "PermitRootLogin")$2="yes"; print }' /etc/ssh/sshd_config > /tmp/sshd_config
      &&     cp /tmp/sshd_config /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "root:toor" | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install iputils-ping net-tools nano
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "/opt/docker_shell.sh" >> /etc/shells
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/docker_shell.sh
    - /opt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/start_daemons.sh
    - /opt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/adduser_docker
    - /usr/local/bin
  - CmdLine:
    - chmod 777 /opt/docker_shell.sh && chmod 777 /usr/local/bin/adduser_docker &&
      chmod 777 opt/start_daemons.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /opt/start_daemons.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
