MetaArgs: null
Stages:
- BaseName: fedora:23
  Commands:
  - Maintainer: Robpol86 <robpol86@gmail.com>
    Name: maintainer
  - CmdLine:
    - dnf update -y && dnf install -y @development-tools fedora-packager rpmdevtools
      dnf-plugins-core
    Name: run
    PrependShell: true
  From:
    Image: fedora:23
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:23
