MetaArgs: null
Stages:
- BaseName: rsrchboy/perlbrew-base:latest
  Commands:
  - Maintainer: Chris Weyl <chris.weyl@wps.io>
    Name: maintainer
  - Env:
    - Key: TARGET_PERL_FULL
      Value: 5.8.9
    Name: env
  - Env:
    - Key: TARGET_PERL
      Value: "5.8"
    Name: env
  - CmdLine:
    - perlbrew download $TARGET_PERL_FULL
    Name: run
    PrependShell: true
  - CmdLine:
    - perlbrew install -j4 --as $TARGET_PERL $TARGET_PERL_FULL
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /usr/local/perlbrew/build/*
    Name: run
    PrependShell: true
  - CmdLine:
    - perlbrew switch $TARGET_PERL
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /usr/local/perlbrew/perls/$TARGET_PERL/bin:$PATH
    Name: env
  - Env:
    - Key: MANPATH
      Value: /usr/local/perlbrew/perls/$TARGET_PERL/man
    Name: env
  - Env:
    - Key: PERLBREW_MANPATH
      Value: /usr/local/perlbrew/perls/$TARGET_PERL/man
    Name: env
  - Env:
    - Key: PERLBREW_PATH
      Value: /usr/local/perlbrew/bin:/usr/local/perlbrew/perls/$TARGET_PERL/bin
    Name: env
  - Env:
    - Key: PERLBREW_PERL
      Value: $TARGET_PERL
    Name: env
  - CmdLine:
    - perlbrew info
    Name: run
    PrependShell: true
  - CmdLine:
    - perl -v
    Name: run
    PrependShell: true
  From:
    Image: rsrchboy/perlbrew-base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM rsrchboy/perlbrew-base:latest
