MetaArgs: null
Stages:
- BaseName: ruby:2-slim
  Commands:
  - CmdLine:
    - "buildDeps=' \t\tautoconf     bison     gcc     make   '   && apt-get update
      \  && apt-get install -y --no-install-recommends $buildDeps   && rm -rf /var/lib/apt/lists/*
      \  && gem install --no-ri --no-rdoc       bson_ext:1.9.2       genghisapp:2.3.11
      \  && apt-get purge --yes --auto-remove $buildDeps"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - /usr/local/bundle/bin/genghisapp --no-launch --foreground --port=5000 --servers
      ${DB_PORT_27017_TCP_ADDR}:${DB_PORT_27017_TCP_PORT}/${DB_NAME}
    Name: cmd
    PrependShell: true
  From:
    Image: ruby:2-slim
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2-slim
