MetaArgs: null
Stages:
- BaseName: heroku/heroku:16
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Ivo Jesus <ivo.jesus@kyero.com>"'
    Name: label
  - Env:
    - Key: LANG
      Value: '"C.UTF-8"'
    - Key: PORT
      Value: '"80"'
    Name: env
  - Name: expose
    Ports:
    - ${PORT}
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dist/bin/
    - /app/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./dist/config/
    - /app/config/
  - Name: workdir
    Path: /app
  - CmdLine:
    - bin/start-nginx
    Name: cmd
    PrependShell: false
  From:
    Image: heroku/heroku:16
  Name: ""
  Platform: ""
  SourceCode: FROM heroku/heroku:16
