MetaArgs: null
Stages:
- BaseName: tensorflow/tensorflow:1.12.0-devel-gpu
  Commands:
  - Maintainer: Akshay Bhat <akshayubhat@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -q && apt-get install -y wget xz-utils
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/bin/"'
  - CmdLine:
    - wget https://www.dropbox.com/s/bjyzb8hytdwp2tp/ffmpeg-release-64bit-static.tar.xz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvfJ ffmpeg-release-64bit-static.tar.xz
    Name: run
    PrependShell: true
  - CmdLine:
    - mv ffmpeg*/* .
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/"'
  - CmdLine:
    - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y postgresql-client-9.6 zip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -q && apt-get install -y pkg-config python-dev python-opencv
      unzip libopencv-dev python-pip libav-tools libjpeg-dev  libpng-dev  libtiff-dev  libjasper-dev  python-numpy
      python-scipy  python-pycurl  python-opencv git nginx supervisor libpq-dev python-cffi
      build-essential libssl-dev libffi-dev python-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg -L python-opencv
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade setuptools
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade matplotlib
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://yt-dl.org/downloads/latest/youtube-dl -O /bin/youtube-dl
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+rx /bin/youtube-dl
    Name: run
    PrependShell: true
  - CmdLine:
    - youtube-dl -U
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone -b stable https://github.com/akshayubhat/DeepVideoAnalytics /root/DVA
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/DVA"'
  - CmdLine:
    - pip install --upgrade cffi
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --no-deps keras
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pip --upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --no-cache-dir http://download.pytorch.org/whl/cu90/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --no-cache-dir mxnet-cu90
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install torchvision
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libhdf5-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --no-deps h5py
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/DVA"'
  - Name: workdir
    Path: '"/root/DVA/repos/lopq/python"'
  - CmdLine:
    - python setup.py install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/DVA/repos/tf_ctpn_cpu/lib/utils/"'
  - CmdLine:
    - ./make.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/"'
  - CmdLine:
    - mkdir media
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir thirdparty
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y cmake
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/thirdparty/"'
  - CmdLine:
    - git clone --recursive https://github.com/davisking/dlib
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/thirdparty/dlib"'
  - CmdLine:
    - git reset --hard 929c630b381d444bbf5d7aa622e3decc7785ddb2
    Name: run
    PrependShell: true
  - CmdLine:
    - 'python setup.py install --yes USE_AVX_INSTRUCTIONS  # --yes DLIB_USE_CUDA --set
      CMAKE_PREFIX_PATH=/usr/local/cuda --set CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/bin/
      --clean'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/thirdparty/"'
  - CmdLine:
    - git clone --recursive https://github.com/facebookresearch/faiss
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/root/thirdparty/faiss"'
  - CmdLine:
    - git reset --hard 2dc30e14cfa76985ff8c2821c051f1725fe66afa
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libopenblas-dev swig
    Name: run
    PrependShell: true
  - Env:
    - Key: BLASLDFLAGS
      Value: /usr/lib/libopenblas.so.0
    Name: env
  - Env:
    - Key: PYTHONPATH
      Value: /root/DVA/repos/:$PYTHONPATH
    Name: env
  - Env:
    - Key: PYTHONPATH
      Value: /root/DVA/repos/tf_ctpn_cpu/:$PYTHONPATH
    Name: env
  - Env:
    - Key: PYTHONPATH
      Value: /root/thirdparty/faiss/python:$PYTHONPATH
    Name: env
  - Name: workdir
    Path: '"/root/DVA/server/"'
  - Name: volume
    Volumes:
    - /root/media
    - /root/DVA/configs/custom_defaults
  - Name: expose
    Ports:
    - "80"
  From:
    Image: tensorflow/tensorflow:1.12.0-devel-gpu
  Name: ""
  Platform: ""
  SourceCode: FROM tensorflow/tensorflow:1.12.0-devel-gpu
