MetaArgs: null
Stages:
- BaseName: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
  Commands:
  - CmdLine:
    - bin/elasticsearch-plugin install --batch ingest-attachment
    Name: run
    PrependShell: true
  From:
    Image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
  Name: ""
  Platform: ""
  SourceCode: FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.0
