MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: Christian Lück <christian@lueck.tv>
    Name: maintainer
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y   nginx
      php5-fpm supervisor   wget unzip patch
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://release.larsjung.de/h5ai/h5ai-0.25.2.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip h5ai-0.25.2.zip -d /usr/share/h5ai
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - setup.patch
    - setup.patch
  - CmdLine:
    - patch -p1 -u -d /usr/share/h5ai/_h5ai/server/ -i /setup.patch && rm setup.patch
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - options.json.patch
    - options.json.patch
  - CmdLine:
    - patch -p1 -u -d /usr/share/h5ai/_h5ai/conf/ -i /options.json.patch && rm options.json.patch
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - h5ai.nginx.conf
    - /etc/nginx/sites-available/h5ai
  - CmdLine:
    - ln -s /etc/nginx/sites-available/h5ai /etc/nginx/sites-enabled/h5ai
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/nginx/sites-enabled/default
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www
  - CmdLine:
    - echo "Looks like you did not mount a volume to `/var/www`. See README.md for
      details." > /var/www/INSTALL.md
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/www/first/second/third/fourth/fifth
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - README.md
    - /var/www/README.md
  - Name: workdir
    Path: /root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - CmdLine:
    - supervisord -c /etc/supervisor/conf.d/supervisord.conf
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: volume
    Volumes:
    - /var/www
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
