MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y tar git curl nano wget dialog net-tools build-essential cmake
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python python-dev python-distribute python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install gunicorn
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /restfulgit
    - /restfulgit
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /requirements.txt
  - CmdLine:
    - 'apt-get install -y libffi-dev # libgit2-dev'
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / ; wget -O libgit2.tar.gz https://github.com/libgit2/libgit2/archive/v0.22.0.tar.gz;
      tar xf libgit2.tar.gz ; rm libgit2.tar.gz ; cd libgit2-*; mkdir build && cd
      build ; cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_CLAR=OFF && cmake
      --build . ; cmake --build . --target install ; cd / ; rm -rf libgit2-*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -r /requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - example_config.py
    - /config.py
  - CmdLine:
    - sed s#/Code/#/repos/# config.py -i ; sed 's#CORS = False#CORS = True#' config.py
      -i
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - '[/repos/]'
  - Name: expose
    Ports:
    - "5000"
  - Name: workdir
    Path: /
  - CmdLine:
    - PYTHONPATH=/ RESTFULGIT_CONFIG=/config.py python -m restfulgit.app
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
