MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-slim
  Commands:
  - CmdLine:
    - apt-get update;     apt-get install -y --no-install-recommends wget ca-certificates
      zip unzip;     rm -rf /var/lib/apt/lists/*;     mkdir -p /paper
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init.sh
    - start.sh
    - /
  - CmdLine:
    - chmod +x /init.sh /start.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - CmdLine:
    - /bin/bash
    - /start.sh
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "25565"
    - "25575"
  - Env:
    - Key: MINECRAFT_EULA_ACCEPT
      Value: "false"
    Name: env
  - Env:
    - Key: LINK_TO_PAPERCLIP_JAR
      Value: '""'
    Name: env
  From:
    Image: openjdk:8-jre-slim
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-slim
