MetaArgs: null
Stages:
- BaseName: node:lts-alpine
  Commands:
  - CmdLine:
    - node
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:lts-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:lts-alpine
