MetaArgs: null
Stages:
- BaseName: debian:stretch-slim
  Commands:
  - Maintainer: Paul Tötterman <paul.totterman@iki.fi>
    Name: maintainer
  - CmdLine:
    - echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/00InstallRecommends
      &&     echo '9999 stream tcp nowait approx /usr/sbin/approx approx' > /etc/inetd.conf
      &&     apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     approx     openbsd-inetd     &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - approx.conf
    - /etc/approx/approx.conf
  - Name: volume
    Volumes:
    - /var/cache/approx
  - Name: expose
    Ports:
    - "9999"
  - CmdLine:
    - inetd
    - -i
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stretch-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stretch-slim
