MetaArgs: null
Stages:
- BaseName: python:3-slim
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - parse_json
    - /usr/local/bin
  - CmdLine:
    - parse_json
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:3-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3-slim
