MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Key: version
    Name: arg
    Value: '"0.10.14-r0"'
  - Labels:
    - Key: caddy_version
      Value: '"$version"'
    Name: label
  - Env:
    - Key: ACME_AGREE
      Value: '"true"'
    Name: env
  - Env:
    - Key: ENABLE_TELEMETRY
      Value: '"false"'
    Name: env
  - Name: expose
    Ports:
    - 2015/tcp
    - 443/tcp
    - 80/tcp
  - Name: volume
    Volumes:
    - /root/.caddy
    - /srv
  - Name: workdir
    Path: /srv
  - CmdLine:
    - caddy
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --conf
    - /etc/Caddyfile
    - --log
    - stdout
    - --agree
    Name: cmd
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Caddyfile
    - /etc/Caddyfile
  - CmdLine:
    - apk add --no-cache                     caddy=$version
    Name: run
    PrependShell: true
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM            alpine:edge
