MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Env:
    - Key: ANSIBLE_VERSION
      Value: 2.2.1.0
    - Key: ANSIBLE_UID
      Value: "555"
    Name: env
  - CmdLine:
    - 'yum -y install epel-release yum-plugin-ovl deltarpm &&     yum -y update &&     yum
      -y install curl                    dnsutils                    git                    less                    openssl                    python-httplib2                    python-jinja2                    python-keyczar                    python-paramiko                    python-pip                    python-setuptools                    PyYAML                    ssh                    sudo                    vim-minimal
      &&     pip install --upgrade pip &&     pip install ansible==${ANSIBLE_VERSION}
      &&     ansible --version &&     groupadd -g ${ANSIBLE_UID} -r ansible &&     useradd
      -u ${ANSIBLE_UID} -r -g ansible ansible &&     mkdir /code &&     mkdir /home/ansible
      && chown -R ansible: /home/ansible'
    Name: run
    PrependShell: true
  - Name: user
    User: ansible
  - Name: workdir
    Path: /code
  - CmdLine:
    - ansible --version
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/ansible-playbook
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
