MetaArgs: null
Stages:
- BaseName: ubuntu:15.10
  Commands:
  - Maintainer: Brian Low <brian.low22@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y         build-essential         curl         g++         git         libfreetype6-dev         libpng12-dev         libzmq3-dev         openjdk-8-jdk         pkg-config         python-dev         python-numpy         python-pip         software-properties-common         swig         unzip         zip         zlib1g-dev         &&     apt-get
      clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - update-ca-certificates -f
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "startup --batch" >>/root/.bazelrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "build --spawn_strategy=standalone --genrule_strategy=standalone"     >>/root/.bazelrc
    Name: run
    PrependShell: true
  - Env:
    - Key: BAZELRC
      Value: /root/.bazelrc
    Name: env
  - Env:
    - Key: BAZEL_VERSION
      Value: 0.2.2
    Name: env
  - Name: workdir
    Path: /
  - CmdLine:
    - mkdir /bazel &&     cd /bazel &&     curl -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
      &&     curl -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE.txt
      &&     chmod +x bazel-*.sh &&     ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
      &&     cd / &&     rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -U protobuf==3.0.0b2
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install asciitree
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --recursive https://github.com/tensorflow/models.git /root/models
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /root/models/syntaxnet/tensorflow && echo | ./configure
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /root/models/syntaxnet && bazel test syntaxnet/... util/utf8/...
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/models/syntaxnet/
  - CmdLine:
    - /root/models/syntaxnet/syntaxnet/demo.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:15.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:15.10
