MetaArgs: null
Stages:
- BaseName: php:5.6-fpm
  Commands:
  - Labels:
    - Key: maintainer
      Value: = "wickedvikingstudios@gmail.com"       vendor = "wickedviking"       description
        = "PHP 5.6 FPM"       licence = "MIT"       documentation= "https://github.com/wickedviking/php56"
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - assets
    - /assets
  - CmdLine:
    - chmod +x /assets/*.sh     && /assets/provision.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php-fpm
    Name: cmd
    PrependShell: false
  From:
    Image: php:5.6-fpm
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6-fpm
