MetaArgs: null
Stages:
- As: build
  BaseName: maven:3-jdk-8
  Commands:
  - Maintainer: Burak Emre Kabakci "emre@rakam.io"
    Name: maintainer
  - Name: workdir
    Path: /var/app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - pom.xml
    - pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam/pom.xml
    - rakam/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-aws/pom.xml
    - rakam-aws/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-postgresql/pom.xml
    - rakam-postgresql/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-presto/pom.xml
    - rakam-presto/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-presto-kafka/pom.xml
    - rakam-presto-kafka/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-spi/pom.xml
    - rakam-spi/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mapper/rakam-mapper-geoip-ip2location/pom.xml
    - mapper/rakam-mapper-geoip-ip2location/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mapper/rakam-mapper-geoip-maxmind/pom.xml
    - mapper/rakam-mapper-geoip-maxmind/pom.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mapper/rakam-mapper-website/pom.xml
    - mapper/rakam-mapper-website/pom.xml
  - CmdLine:
    - mvn verify clean --fail-never
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam/
    - rakam
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-aws/
    - rakam-aws
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-postgresql/
    - rakam-postgresql
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-presto/
    - rakam-presto
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-presto-kafka/
    - rakam-presto-kafka
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./rakam-spi/
    - rakam-spi
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mapper/rakam-mapper-geoip-ip2location/
    - mapper/rakam-mapper-geoip-ip2location
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mapper/rakam-mapper-geoip-maxmind/
    - mapper/rakam-mapper-geoip-maxmind
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./mapper/rakam-mapper-website/
    - mapper/rakam-mapper-website
  - CmdLine:
    - mvn package -T 1C -DskipTests=true
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update     && wget -P /tmp http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz     &&
      gzip -d /tmp/GeoLite2-City.mmdb.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /var/app/rakam/target/rakam-*-bundle/rakam-*/ &&     mkdir etc &&     echo
      '\n-Denv=RAKAM_CONFIG' >> ./etc/jvm.config
    Name: run
    PrependShell: true
  From:
    Image: maven:3-jdk-8
  Name: build
  Platform: ""
  SourceCode: FROM maven:3-jdk-8 as build
- BaseName: openjdk:8-jre
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /var/app/rakam/target/
    - /rtmp
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /tmp/GeoLite2-City.mmdb
    - /tmp/GeoLite2-City.mmdb
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./entrypoint.sh
    - /app/entrypoint.sh
  - CmdLine:
    - cp -r /rtmp/rakam-*-bundle/rakam-*/* /app/ &&     chmod +x /app/entrypoint.sh
      &&     rm -rf /rtmp
    Name: run
    PrependShell: true
  - CmdLine:
    - /app/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "9999"
  From:
    Image: openjdk:8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre
