MetaArgs: null
Stages:
- BaseName: gcc:8.2.0
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Peter Gyima <peter.gyima@gimadigital.com>"'
    Name: label
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y net-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y less
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y vim
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y cifs-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/#Port 22/Port 1948/' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g'
      -i /etc/pam.d/sshd
    Name: run
    PrependShell: true
  - Env:
    - Key: NOTVISIBLE
      Value: '"in users profile"'
    Name: env
  - CmdLine:
    - echo "export VISIBLE=now" >> /etc/profile
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1948"
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  - Name: expose
    Ports:
    - "9418"
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    Name: cmd
    PrependShell: false
  From:
    Image: gcc:8.2.0
  Name: ""
  Platform: ""
  SourceCode: FROM gcc:8.2.0
