MetaArgs: null
Stages:
- BaseName: lsiobase/alpine
  Commands:
  - Maintainer: tynor88 <tynor@hotmail.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init/
    - /etc/my_init.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cron/
    - /etc/cron.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - app/script/
    - /app/script/
  - CmdLine:
    - chmod -v +x /etc/my_init.d/*.sh /app/script/*.sh
    Name: run
    PrependShell: true
  From:
    Image: lsiobase/alpine
  Name: ""
  Platform: ""
  SourceCode: FROM lsiobase/alpine
