MetaArgs: null
Stages:
- BaseName: jenkins/jenkins:lts
  Commands:
  - Name: user
    User: root
  - Key: DOCKERVERSION
    Name: arg
    Value: 19.03.5
  - CmdLine:
    - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz   &&
      tar xzvf docker-${DOCKERVERSION}.tgz --strip 1                  -C /usr/local/bin
      docker/docker   && rm docker-${DOCKERVERSION}.tgz
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - plugins.txt
    - /usr/share/jenkins/ref/plugins.txt
  - CmdLine:
    - /usr/local/bin/install-plugins.sh  < /usr/share/jenkins/ref/plugins.txt
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  From:
    Image: jenkins/jenkins:lts
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins/jenkins:lts
