MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.12.4-alpine3.9
  Commands:
  - CmdLine:
    - apk add --update --no-cache build-base curl git upx &&   rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - GO111MODULE=on go get github.com/micro/protoc-gen-micro &&     go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
      &&     go get -u github.com/unistack-org/protoc-gen-microrest &&     go get
      -u github.com/favadi/protoc-go-inject-tag &&     go get -u github.com/envoyproxy/protoc-gen-validate
      &&     go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12.4-alpine3.9
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.12.4-alpine3.9 as builder
- BaseName: uber/prototool:latest
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/bin/protoc-*
    - /usr/local/bin/
  From:
    Image: uber/prototool:latest
  Name: ""
  Platform: ""
  SourceCode: FROM uber/prototool:latest
