MetaArgs: null
Stages:
- As: base
  BaseName: nginx:1.16.1
  Commands:
  - Key: TIME_ZONE
    Name: arg
    Value: null
  - CmdLine:
    - mkdir -p /opt/var/cache/nginx &&     cp -a --parents /usr/lib/nginx /opt &&     cp
      -a --parents /usr/share/nginx /opt &&     cp -a --parents /var/log/nginx /opt
      &&     cp -aL --parents /var/run /opt &&     cp -a --parents /etc/nginx /opt
      &&     cp -a --parents /etc/passwd /opt &&     cp -a --parents /etc/group /opt
      &&     cp -a --parents /usr/sbin/nginx /opt &&     cp -a --parents /usr/sbin/nginx-debug
      /opt &&     cp -a --parents /lib/x86_64-linux-gnu/ld-* /opt &&     cp -a --parents
      /lib/x86_64-linux-gnu/libpcre.so.* /opt &&     cp -a --parents /lib/x86_64-linux-gnu/libz.so.*
      /opt &&     cp -a --parents /lib/x86_64-linux-gnu/libc* /opt &&     cp -a --parents
      /lib/x86_64-linux-gnu/libdl* /opt &&     cp -a --parents /lib/x86_64-linux-gnu/libpthread*
      /opt &&     cp -a --parents /lib/x86_64-linux-gnu/libcrypt* /opt &&     cp -a
      --parents /usr/lib/x86_64-linux-gnu/libssl.so.* /opt &&     cp -a --parents
      /usr/lib/x86_64-linux-gnu/libcrypto.so.* /opt &&     cp /usr/share/zoneinfo/${TIME_ZONE:-ROC}
      /opt/etc/localtime
    Name: run
    PrependShell: true
  From:
    Image: nginx:1.16.1
  Name: base
  Platform: ""
  SourceCode: FROM nginx:1.16.1 as base
- BaseName: gcr.io/distroless/base-debian10
  Commands:
  - Chown: ""
    From: base
    Name: copy
    SourcesAndDest:
    - /opt
    - /
  - Name: expose
    Ports:
    - "443"
    - "80"
  - CmdLine:
    - nginx
    - -g
    - daemon off;
    Name: entrypoint
    PrependShell: false
  From:
    Image: gcr.io/distroless/base-debian10
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/distroless/base-debian10
