MetaArgs: null
Stages:
- BaseName: golang:1.8
  Commands:
  - Env:
    - Key: TERM
      Value: xterm
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y     alien     libaio1     postfix     mailutils
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./oracle_client
    - /oracle-client
  - CmdLine:
    - alien -i /oracle-client/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
      &&     alien -i /oracle-client/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm
      &&     alien -i /oracle-client/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
    Name: run
    PrependShell: true
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/lib/oracle/12.2/client64/lib/
    Name: env
  - Env:
    - Key: PKG_CONFIG_PATH
      Value: /oracle-client/
    Name: env
  - CmdLine:
    - rm -r -f /oracle-client/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
      &&     rm -r -f /oracle-client/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm
      &&     rm -r -f /oracle-client/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./postfix_main.cf
    - /etc/postfix/main.cf
  From:
    Image: golang:1.8
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.8
