MetaArgs: null
Stages:
- BaseName: linode/lamp
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y php5-mysql && a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /code
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - main_website.conf
    - /etc/apache2/sites-available/
  - CmdLine:
    - rm /etc/apache2/sites-enabled/example.com.conf &&     ln -s /etc/apache2/sites-available/main_website.conf
      /etc/apache2/sites-enabled/main_website.conf &&     mkdir /var/log/main_website/
    Name: run
    PrependShell: true
  - CmdLine:
    - "service mysql start && \tmysql -u root -pAdmin2015 --execute=\"CREATE DATABASE
      cake_habtm; GRANT ALL ON cake_habtm.* TO 'cake_user' IDENTIFIED BY 'cake_pwd';
      FLUSH PRIVILEGES;\" && \tmysql -u cake_user -pcake_pwd cake_habtm < /code/database/cake-habtm.sql"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /tmp/cake_habtm && cp -R app/tmp/* /tmp/cake_habtm  && chown -R www-data:www-data
      /tmp/cake_habtm
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /code/services.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: linode/lamp
  Name: ""
  Platform: ""
  SourceCode: FROM linode/lamp
