MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - CmdLine:
    - apk add --no-cache gcc musl-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache g++
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
