MetaArgs: null
Stages:
- BaseName: uomresplatdevops/galera-common
  Commands:
  - Maintainer: Tim Dettrick <t.dettrick@uq.edu.au>
    Name: maintainer
  - CmdLine:
    - apt-get install -y mariadb-galera-server-10.0 galera-3
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/mysql/conf.d/*.cnf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /etc/mysql/conf.d
    - /etc/mysql/conf.d
  - Name: volume
    Volumes:
    - /data
  - Name: expose
    Ports:
    - "3306"
    - "4444"
    - "4567"
  - CmdLine:
    - /usr/bin/mysqld_safe
    Name: entrypoint
    PrependShell: false
  From:
    Image: uomresplatdevops/galera-common
  Name: ""
  Platform: ""
  SourceCode: FROM uomresplatdevops/galera-common
