MetaArgs: null
Stages:
- BaseName: openjdk:alpine
  Commands:
  - Maintainer: Jon Brouse @jonbrouse
    Name: maintainer
  - Env:
    - Key: INSTALL_DIR
      Value: /opt/ice
    Name: env
  - Env:
    - Key: HOME_DIR
      Value: /root
    Name: env
  - Env:
    - Key: GRAILS_VERSION
      Value: 2.4.4
    Name: env
  - Env:
    - Key: GRAILS_HOME
      Value: ${HOME_DIR}/.grails/wrapper/${GRAILS_VERSION}/grails-${GRAILS_VERSION}
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:${HOME_DIR}/.grails/wrapper/${GRAILS_VERSION}/grails-${GRAILS_VERSION}/bin/
    Name: env
  - Env:
    - Key: ICE_VERSION
      Value: 1.1.2
    Name: env
  - Key: JAVA_OPTS
    Name: arg
    Value: null
  - Name: workdir
    Path: ${HOME_DIR}/.grails/wrapper/${GRAILS_VERSION}
  - CmdLine:
    - apk add --no-cache bash curl unzip &&     curl -O http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-${GRAILS_VERSION}.zip
      &&     unzip grails-${GRAILS_VERSION}.zip &&     rm -rf grails-${GRAILS_VERSION}.zip
    Name: run
    PrependShell: true
  - Name: workdir
    Path: ${INSTALL_DIR}
  - CmdLine:
    - mkdir /mnt/ice_processor /mnt/ice_reader &&     curl -fsSL https://github.com/Teevity/ice/archive/v${ICE_VERSION}.tar.gz
      | tar zx --strip-components=1 &&     grails ${JAVA_OPTS} wrapper &&     rm grails-app/i18n/messages.properties
      &&     sed -i -e '1i#!/bin/bash\' grailsw
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /opt/ice/grailsw
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:alpine
