MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.11-alpine
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/github.com/yuya-takeyama/circleci-queue-to-datadog
  - Name: workdir
    Path: /go/src/github.com/yuya-takeyama/circleci-queue-to-datadog
  - CmdLine:
    - apk --update add git perl &&   COMMIT_HASH=`git describe --always | perl -pe
      chomp` &&   go build -ldflags "-X main.gitCommit=${COMMIT_HASH}"
    Name: run
    PrependShell: true
  From:
    Image: golang:1.11-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.11-alpine AS builder
- BaseName: alpine:3.8
  Commands:
  - CmdLine:
    - apk --update add ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/yuya-takeyama/circleci-queue-to-datadog/circleci-queue-to-datadog
    - /circleci-queue-to-datadog
  - CmdLine:
    - /circleci-queue-to-datadog
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
