MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Steve <daneiyunzhijia@163.com>
    Name: maintainer
  - Env:
    - Key: TZ
      Value: '"Asia/Shanghai"'
    Name: env
  - Env:
    - Key: TERM
      Value: xterm
    Name: env
  - CmdLine:
    - yum clean all && yum repolist
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y curl wget vim-enhanced yum-utils  net-tools gcc gcc-c++ git make
      automake
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM       centos:7
