MetaArgs: null
Stages:
- BaseName: zingsono/openjdk:1.8-jre
  Commands:
  - Maintainer: Zengs.<zingsono@gmail.com>
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"FORM zingsono/openjdk:1.8-jre . logstash"'
    Name: label
  - Name: workdir
    Path: /logstash
  - Env:
    - Key: LOGSTASH_VERSION
      Value: 6.2.4
    Name: env
  - CmdLine:
    - curl -o logstash.tar.gz "https://artifacts.elastic.co/downloads/logstash/logstash-$LOGSTASH_VERSION.tar.gz"
      &&  tar -xf logstash.tar.gz --strip-components=1 && rm -f logstash.tar.gz
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:/logstash/bin/
    Name: env
  - CmdLine:
    - logstash
    Name: cmd
    PrependShell: false
  From:
    Image: zingsono/openjdk:1.8-jre
  Name: ""
  Platform: ""
  SourceCode: FROM zingsono/openjdk:1.8-jre
