MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.11-alpine
  Commands:
  - Env:
    - Key: GODEBUG
      Value: netdns=cgo
    Name: env
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$GOPATH/bin
    Name: env
  - Env:
    - Key: CGO_ENABLED
      Value: "0"
    Name: env
  - CmdLine:
    - apk add --no-cache git make
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -d github.com/lightningnetwork/lnd && cd $GOPATH/src/github.com/lightningnetwork/lnd
      && make &&  make install
    Name: run
    PrependShell: true
  From:
    Image: golang:1.11-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.11-alpine as builder
- BaseName: alpine
  Commands:
  - Name: expose
    Ports:
    - "10009"
    - "9735"
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/bin/lncli
    - /bin/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/bin/lnd
    - /bin/
  - CmdLine:
    - apk add --no-cache bash
    Name: run
    PrependShell: true
  - CmdLine:
    - --debuglevel=debug
    - --maxpendingchannels=10
    - --rpclisten=0.0.0.0:10009
    - --color=#4126a7
    - --alias=MDMA
    - --bitcoin.active
    - --bitcoin.testnet
    - --bitcoin.node=bitcoind
    - --bitcoind.rpchost=btc
    - --bitcoind.rpcuser=test
    - --bitcoind.rpcpass=test
    - --bitcoind.zmqpubrawblock=tcp://btc:28332
    - --bitcoind.zmqpubrawtx=tcp://btc:28333
    - --autopilot.active
    - --autopilot.maxchannels=5
    - --autopilot.allocation=0.6
    Name: cmd
    PrependShell: false
  - CmdLine:
    - lnd
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
