MetaArgs: null
Stages:
- BaseName: bde2020/spark-base:2.4.4-hadoop2.7
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Gezim Sejdiu <g.sejdiu@gmail.com>, Giannis Mouchakis <gmouchakis@gmail.com>"'
    Name: label
  - Env:
    - Key: SPARK_MASTER_NAME
      Value: spark-master
    Name: env
  - Env:
    - Key: SPARK_MASTER_PORT
      Value: "7077"
    Name: env
  - Env:
    - Key: SPARK_APPLICATION_JAR_LOCATION
      Value: /app/application.jar
    Name: env
  - Env:
    - Key: SPARK_APPLICATION_PYTHON_LOCATION
      Value: /app/app.py
    Name: env
  - Env:
    - Key: SPARK_APPLICATION_MAIN_CLASS
      Value: my.main.Application
    Name: env
  - Env:
    - Key: SPARK_APPLICATION_ARGS
      Value: '""'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - submit.sh
    - /
  - CmdLine:
    - /bin/bash
    - /submit.sh
    Name: cmd
    PrependShell: false
  From:
    Image: bde2020/spark-base:2.4.4-hadoop2.7
  Name: ""
  Platform: ""
  SourceCode: FROM bde2020/spark-base:2.4.4-hadoop2.7
