MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Key: VCS_REF
    Name: arg
    Value: null
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Labels:
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.name
      Value: '"helm-kubectl"'
    - Key: org.label-schema.url
      Value: '"https://hub.docker.com/r/dtzar/helm-kubectl/"'
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/dtzar/helm-kubectl"'
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    Name: label
  - Env:
    - Key: KUBE_LATEST_VERSION
      Value: '"v1.11.2"'
    Name: env
  - Env:
    - Key: HELM_VERSION
      Value: '"v2.10.0"'
    Name: env
  - Env:
    - Key: MAVEN_VERSION
      Value: 3.5.3
    Name: env
  - Env:
    - Key: MAVEN_HOME
      Value: /usr/lib/mvn
    Name: env
  - Env:
    - Key: PATH
      Value: $MAVEN_HOME/bin:$PATH
    Name: env
  - CmdLine:
    - apk add --no-cache ca-certificates bash git     && wget -q https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl
      -O /usr/local/bin/kubectl     && chmod +x /usr/local/bin/kubectl     && wget
      -q http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz
      -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm     && chmod +x /usr/local/bin/helm
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /config
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: true
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
