MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: keakon <keakon@gmail.com>
    Name: maintainer
  - Env:
    - Key: DOODLE_PATH
      Value: /data/doodle
    Name: env
  - CmdLine:
    - "apt-get update && \tapt-get install -y \t\tgit \t\twget \t\tpython \t\tbuild-essential
      \t\tpython-dev \t\tlibcurl4-openssl-dev && \trm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/keakon/Doodle.git $DOODLE_PATH
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $DOODLE_PATH
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://api.github.com/repos/keakon/Doodle/commits
    - /tmp/commits
  - CmdLine:
    - git fetch && git reset --hard origin/master
    Name: run
    PrependShell: true
  - CmdLine:
    - scripts/buildout.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get purge --auto-remove -y git wget build-essential python-dev && apt-get
      autoremove -y
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - bin/doodle
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
