MetaArgs: null
Stages:
- BaseName: forrestzhang/ubuntu-dev
  Commands:
  - Maintainer: Tao Zhang "forrestzhang1982@gmail.com"
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install cython3
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/software
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/software
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/gmarcais/Jellyfish/releases/download/v2.2.3/jellyfish-2.2.3.tar.gz
    - /opt/software/
  - CmdLine:
    - tar zxvf jellyfish-2.2.3.tar.gz && mv jellyfish-2.2.3  jellyfish && cd jellyfish
      && ./configure && make && make install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/forrestzhang/primer3-py/archive/unicode.zip
    - /opt/software/
  - CmdLine:
    - unzip unicode.zip && cd primer3-py-unicode && python3 setup.py install
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/lh3/bwa.git && cd bwa && make
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install numpy pyfasta
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/software
  - CmdLine:
    - git clone https://github.com/forrestzhang/Chorus.git
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/software/bwa:/opt/software/jellyfish/bin:$PATH
    Name: env
  - Env:
    - Key: CHORUS_USER
      Value: chorus
    - Key: CHORUS_UID
      Value: "1555"
    - Key: CHORUS_GID
      Value: "1555"
    - Key: CHORUS_HOME
      Value: /home/chorus
    Name: env
  - CmdLine:
    - groupadd -r $CHORUS_USER -g $CHORUS_GID
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -u $CHORUS_UID -r -g $CHORUS_GID -d $CHORUS_HOME -c "Chorus user" $CHORUS_USER
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./script/Chorus.sh
    - /usr/bin/Chorus
  - CmdLine:
    - chmod +x /usr/bin/Chorus
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $CHORUS_HOME
  - CmdLine:
    - /usr/bin/Chorus
    Name: entrypoint
    PrependShell: false
  From:
    Image: forrestzhang/ubuntu-dev
  Name: ""
  Platform: ""
  SourceCode: FROM forrestzhang/ubuntu-dev
