MetaArgs: null
Stages:
- BaseName: node:0.12-onbuild
  Commands:
  - Maintainer: Rapid 7 - Logentries <support@logentries.com>
    Name: maintainer
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package.json
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - index.js
    - /usr/src/app/index.js
  - CmdLine:
    - /usr/src/app/index.js
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: node:0.12-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM node:0.12-onbuild
