MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-get update&&apt-get -y install pandoc texlive-base-bin texlive-latex-recommended
      texlive-fonts-recommended
    Name: run
    PrependShell: true
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
