MetaArgs: null
Stages:
- BaseName: debian:8
  Commands:
  - CmdLine:
    - "apt-get update -y \t&& apt-get install -y gcc g++ libuv-dev make python git
      curl"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp && curl https://bootstrap.pypa.io/ez_setup.py -o - | python \t&& git
      clone https://chromium.googlesource.com/external/gyp.git \t&& cd gyp  \t&& python
      setup.py install  \t&& cd ..  \t&& rm -rf gyp"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp  \t&& rm -rf gyp  \t&& apt-get remove -y git curl"
    Name: run
    PrependShell: true
  From:
    Image: debian:8
  Name: ""
  Platform: ""
  SourceCode: FROM debian:8
