MetaArgs: null
Stages:
- BaseName: quay.io/hanzeljesheen/nodejs
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /src
  - CmdLine:
    - apk update && apk upgrade && apk --update add ruby ruby-irb ruby-rdoc && rm
      -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install sass
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g nodemon
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g gulp
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - gulp build
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8000"
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: quay.io/hanzeljesheen/nodejs
  Name: ""
  Platform: ""
  SourceCode: FROM quay.io/hanzeljesheen/nodejs
