MetaArgs: null
Stages:
- BaseName: registry.fedoraproject.org/fedora:latest
  Commands:
  - Env:
    - Key: NAME
      Value: '"gluster-fedora"'
    - Key: DESC
      Value: '"GlusterFS on Fedora"'
    - Key: VERSION
      Value: "0"
    - Key: RELEASE
      Value: "1"
    - Key: ARCH
      Value: x86_64
    - Key: REPO
      Value: '"$FGC"'
    - Key: container
      Value: docker
    Name: env
  - Labels:
    - Key: name
      Value: '"$REPO/$NAME"'
    - Key: version
      Value: '"$VERSION"'
    - Key: release
      Value: '"$RELEASE.$DISTTAG"'
    - Key: architecture
      Value: '"$ARCH"'
    - Key: vendor
      Value: '"Red Hat, Inc"'
    - Key: summary
      Value: '"$DESC"'
    - Key: usage
      Value: '"docker run -d -P --tmpfs /run --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup
        $REPO/$NAME"'
    - Key: io.k8s.display-name
      Value: '"$DESC"'
    - Key: io.k8s.description
      Value: '"GlusterFS is a distributed and scalable network filesystem. Using common,
        off-the-shelf hardware you can create large, distributed storage solutions
        for media streaming, data analysis, and other data- and bandwidth-intensive
        tasks."'
    - Key: io.openshift.tags
      Value: '"gluster,glusterfs,gluster-fedora"'
    - Key: com.redhat.component
      Value: '"$NAME"'
    - Key: maintainer
      Value: '"Jose A. Rivera <jarrpa@redhat.com>, Humble Chirammal <hchiramm@redhat.com>"'
    Name: label
  - Name: volume
    Volumes:
    - /sys/fs/cgroup/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/gluster/gluster-containers/blob/master/README.md
    - /README.md
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gluster-setup.sh
    - gluster-brickmultiplex.service
    - gluster-brickmultiplex.sh
    - gluster-setup.service
    - /
  - CmdLine:
    - dnf -y update &&     sed -i "s/LANG/\#LANG/g" /etc/locale.conf &&     dnf -y
      install systemd-udev glusterfs-server dbus-python nfs-utils attr iputils iproute
      glusterfs-geo-replication openssh-server openssh-clients cronie tar rsync sos
      sudo xfsprogs &&     dnf clean all &&     sed -i '/Port 22/c\Port 2222' /etc/ssh/sshd_config
      &&     sed -i 's/Requires\=rpcbind\.service//g' /usr/lib/systemd/system/glusterd.service
      &&     sed -i 's/rpcbind\.service/gluster-setup\.service/g' /usr/lib/systemd/system/glusterd.service
      &&     sed -i.save -e "s#udev_sync = 1#udev_sync = 0#" -e "s#udev_rules = 1#udev_rules
      = 0#" -e "s#use_lvmetad = 1#use_lvmetad = 0#" /etc/lvm/lvm.conf &&     mkdir
      -p /etc/glusterfs_bkp /var/lib/glusterd_bkp /var/log/glusterfs_bkp &&     cp
      -r /etc/glusterfs/* /etc/glusterfs_bkp &&     cp -r /var/lib/glusterd/* /var/lib/glusterd_bkp
      &&     cp -r /var/log/glusterfs/* /var/log/glusterfs_bkp &&     mv /gluster-setup.sh
      /usr/sbin/gluster-setup.sh &&     mv /gluster-brickmultiplex.service /etc/systemd/system/gluster-brickmultiplex.service
      &&     mv /gluster-brickmultiplex.sh /usr/sbin/gluster-brickmultiplex.sh &&     mv
      /gluster-setup.service /etc/systemd/system/gluster-setup.service &&     chmod
      644 /etc/systemd/system/gluster-setup.service &&     chmod 500 /usr/sbin/gluster-setup.sh
      &&     ln -s /usr/sbin/gluster-setup.sh /usr/sbin/setup.sh &&     chmod 644
      /etc/systemd/system/gluster-brickmultiplex.service &&     chmod 500 /usr/sbin/gluster-brickmultiplex.sh
      &&     systemctl mask getty.target &&     systemctl disable systemd-udev-trigger.service
      &&     systemctl disable systemd-udevd.service &&     systemctl disable nfs-server.service
      &&     systemctl enable rpcbind.service &&     systemctl enable sshd.service
      &&     systemctl enable gluster-setup.service &&     systemctl enable gluster-brickmultiplex.service
      &&     systemctl enable glusterd.service &&     mkdir -p /var/log/core;
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "111"
    - "2049"
    - "2222"
    - "24006"
    - "24007"
    - "245"
    - "38465"
    - "38466"
    - "38468"
    - "38469"
    - "443"
    - "49152"
    - "49153"
    - "49154"
    - "49156"
    - "49157"
    - "49158"
    - "49159"
    - "49160"
    - "49161"
    - "49162"
    - "6010"
    - "6011"
    - "6012"
    - "8080"
  - CmdLine:
    - /usr/sbin/init
    Name: cmd
    PrependShell: false
  From:
    Image: registry.fedoraproject.org/fedora:latest
  Name: ""
  Platform: ""
  SourceCode: FROM registry.fedoraproject.org/fedora:latest
