MetaArgs: null
Stages:
- BaseName: centos:7.4.1708
  Commands:
  - Maintainer: ccondit@randomcoder.com
    Name: maintainer
  - CmdLine:
    - "yum clean metadata && \tyum -y upgrade && \tyum -y install epel-release &&
      \tyum clean metadata && \tyum -y install which tar rpm-build yum-utils python-argparse
      python-yaml gcc gcc-c++ createrepo jq && \tyum clean all"
    Name: run
    PrependShell: true
  From:
    Image: centos:7.4.1708
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7.4.1708
