MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - CmdLine:
    - apk update && apk upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache bash
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache --virtual build-dependencies alpine-sdk gmp-dev zlib-dev
      openssl-dev gdbm-dev db-dev libedit-dev libffi-dev coreutils yaml-dev autoconf
      readline-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache fortune
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache imagemagick
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache zlib
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache openssl
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache sqlite
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache sqlite-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache libxml2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache libxslt-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache yaml
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache readline
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache ghostscript-fonts
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache openssh
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache rsync
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache tzdata
    Name: run
    PrependShell: true
  - Env:
    - Key: TZ
      Value: America/Toronto
    Name: env
  - Env:
    - Key: LANGUAGE
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - mkdir -p /usr/src/ruby
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p180.tar.bz2 -O - |
      tar -xjC /usr/src/ruby --strip-components=1
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/src/ruby && autoconf && ./configure --disable-install-doc && make &&
      make install && rm -r /usr/src/ruby
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc -v 1.6.2 rubygems-update && ruby `gem env gemdir`/gems/rubygems-update-1.6.2/setup.rb
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc rails -v 2.3.12
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc mongrel -v 1.2.0.pre2
    Name: run
    PrependShell: true
  - CmdLine:
    - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true && gem install --no-ri --no-rdoc nokogiri
      -v 1.6.0
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc authlogic -v 2.1.6; exit 0
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc calendar_helper -v 0.2.6
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc cancan -v 1.3.4
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc exchange -v 1.2.2
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc fuzzy_match -v 2.1.0
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc handles_sortable_columns -v 0.1.2
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc hirb -v 0.7.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc paperclip -v 2.3.1.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc rqrcode -v 0.10.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc sqlite3 -v 1.3.8
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc sqlite3-ruby -v 1.3.3
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc will_paginate -v 2.3.15
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc abstract -v 1.0.0
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc algorithms -v 0.6.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc atomic -v 1.1.13
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc cheat -v 1.3.3
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc chunky_png -v 1.3.8
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc open4 -v 1.3.4
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc pager -v 1.0.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc railroad -v 0.5.0
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc rbtree -v 0.4.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc rqrcode -v 0.10.1
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc sentient_user -v 0.3.2
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc i18n -v 0.6.5
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-ri --no-rdoc tzinfo -v 0.3.37
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .irbrc
    - /root/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - timestamp.rb
    - /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-2.3.12/lib/active_record
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sortable_columns.rb
    - /usr/local/lib/ruby/gems/1.9.1/gems/handles_sortable_columns-0.1.2/lib/handles
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - processor.rb
    - /usr/local/lib/ruby/gems/1.9.1/gems/paperclip-2.3.1.1/lib/paperclip
  - CmdLine:
    - /bin/bash
    Name: entrypoint
    PrependShell: false
  - Name: workdir
    Path: /root/harmoknit
  - CmdLine:
    - apk del build-dependencies
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
