MetaArgs: null
Stages:
- BaseName: ruby:2.3.1-slim
  Commands:
  - Maintainer: Computer Science House
    Name: maintainer
  - Env:
    - Key: ZAMMAD_DIR
      Value: /opt/zammad
    Name: env
  - Env:
    - Key: ZAMMAD_USER
      Value: zammad
    Name: env
  - Env:
    - Key: RAILS_ENV
      Value: production
    Name: env
  - Env:
    - Key: GIT_URL
      Value: https://github.com/zammad/zammad.git
    Name: env
  - Env:
    - Key: GIT_BRANCH
      Value: stable
    Name: env
  - CmdLine:
    - "BUILD_DEPENDENCIES=\"git nginx build-essential libffi-dev libpq5 libpq-dev
      libmysqlclient-dev\"     set -ex   \t  && apt-get update       && apt-get install
      -y --force-yes --no-install-recommends ${BUILD_DEPENDENCIES}       && gem install
      foreman       && apt-get clean       && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      \      && sed -i \"s/^user.*$/daemon off;/\" /etc/nginx/nginx.conf       &&
      rm -f /etc/nginx/conf.d/* /etc/nginx/sites-*/*       && ln -sf /dev/stdout /var/log/nginx/access.log
      \      && ln -sf /dev/stderr /var/log/nginx/error.log       && mkdir -p /var/cache/nginx
      /var/lib/nginx       && chmod -R og+rwx /etc/nginx/conf.d /var/*/nginx       &&
      chmod og+rwx /var/run"
    Name: run
    PrependShell: true
  - CmdLine:
    - 'set -ex       && useradd -M -d ${ZAMMAD_DIR} ${ZAMMAD_USER}       && cd $(dirname
      ${ZAMMAD_DIR})       && git clone --depth 1 -b "${GIT_BRANCH}" "${GIT_URL}"       &&
      cd ${ZAMMAD_DIR}       && bundle install --without test development       &&
      contrib/packager.io/fetch_locales.rb       && sed -e ''s#.*adapter: postgresql#  adapter:
      nulldb#g'' -e ''s#.*username:.*#  username: postgres#g'' -e ''s#.*password:.*#  password:
      \n  host: zammad-postgresql\n#g'' < config/database.yml.pkgr > config/database.yml       &&
      bundle exec rake assets:precompile       && rm -f config/database.yml       &&
      rm -rf tmp/cache       && mkdir -p ${ZAMMAD_DIR}/storage       && chown -R ${ZAMMAD_USER}:${ZAMMAD_USER}
      ${ZAMMAD_DIR}       && chmod -R og+rwx ${ZAMMAD_DIR}/log       && chmod -R og+rwx
      ${ZAMMAD_DIR}/tmp       && chmod -R og+rwx ${ZAMMAD_DIR}/storage       && chmod
      -R og+rwx ${ZAMMAD_DIR}/public/assets/images'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Procfile*
    - ${ZAMMAD_DIR}/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - database.yml
    - ${ZAMMAD_DIR}/config/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - zammad.conf
    - /etc/nginx/conf.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chown ${ZAMMAD_USER}:${ZAMMAD_USER} /entrypoint.sh     && chmod +x /entrypoint.sh     &&
      ln -sf /dev/stdout ${ZAMMAD_DIR}/log/production.log     && ln -sf /dev/stdout
      ${ZAMMAD_DIR}/log/scheduler_out.log     && ln -sf /dev/stderr ${ZAMMAD_DIR}/log/scheduler_err.log     &&
      ln -sf /dev/stdout ${ZAMMAD_DIR}/log/websocket-server_out.log     && ln -sf
      /dev/stderr ${ZAMMAD_DIR}/log/websocket-server_err.log
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - Name: user
    User: ${ZAMMAD_USER}
  - Name: workdir
    Path: ${ZAMMAD_DIR}
  - CmdLine:
    - /entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.3.1-slim
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3.1-slim
