MetaArgs: null
Stages:
- BaseName: wordpress
  Commands:
  - CmdLine:
    - curl     -o /usr/bin/wp-cli     https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar     &&
      chmod a+x /usr/bin/wp-cli
    Name: run
    PrependShell: true
  From:
    Image: wordpress
  Name: ""
  Platform: ""
  SourceCode: FROM wordpress
