MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - CmdLine:
    - yum update -y &&     yum install -y epel-release &&     yum install -y centos-release-scl
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y     which     curl     sudo     make     python     tar     openssh-server     openssh-clients     git     cmake3     python-pip     devtoolset-3-gcc     devtoolset-3-gcc-c++
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y zlib-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install umpire
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/bin/cmake3 /usr/bin/cmake
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
    - "8080"
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
