MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Name: volume
    Volumes:
    - /data
  - Env:
    - Key: CHEFDK_VERSION
      Value: 3.0.36
    - Key: STOVE_VERSION
      Value: 6.0.0
    Name: env
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Key: VERSION
    Name: arg
    Value: null
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./resources
    - /resources
  - CmdLine:
    - /resources/build && rm -rf /resources
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - Labels:
    - Key: '"maintainer"'
      Value: '"cloudsquad@fxinnovation.com"'
    - Key: '"org.label-schema.name"'
      Value: '"chefdk"'
    - Key: '"org.label-schema.base-image.name"'
      Value: '"docker.io/library/ubuntu"'
    - Key: '"org.label-schema.base-image.version"'
      Value: '"xenial"'
    - Key: '"org.label-schema.description"'
      Value: '"Chefdk in a container"'
    - Key: '"org.label-schema.url"'
      Value: '"https://www.chef.io"'
    - Key: '"org.label-schema.vcs-url"'
      Value: '"https://bitbucket.org/fxadmin/public-common-docker-chefdk"'
    - Key: '"org.label-schema.vendor"'
      Value: '"FXinnovation"'
    - Key: '"org.label-schema.schema-version"'
      Value: '"1.0.0-rc.1"'
    - Key: '"org.label-schema.applications.chefdk.version"'
      Value: $CHEFDK_VERSION
    - Key: '"org.label-schema.applications.stove.version"'
      Value: $STOVE_VERSION
    - Key: '"org.label-schema.vcs-ref"'
      Value: $VCS_REF
    - Key: '"org.label-schema.version"'
      Value: $VERSION
    - Key: '"org.label-schema.build-date"'
      Value: $BUILD_DATE
    - Key: '"org.label-schema.usage"'
      Value: '"docker run --rm -v $(pwd):/data fxinnovation/chefdk [CHEFDK_COMPONANT]
        [COMMAND_OPTIONS]"'
    Name: label
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
