MetaArgs: null
Stages:
- BaseName: nodesource/node:precise
  Commands:
  - Maintainer: Adam Alpern <adam.alpern@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install python-pip python-dev curl git gunicorn supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install virtualenv
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./config.py
    - /var/lib/tessera/config.py
  - CmdLine:
    - mkdir /src
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/aalpern/tessera.git /src/tessera
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src/tessera
  - CmdLine:
    - script/setup
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src/tessera/tessera-server
  - CmdLine:
    - ../script/server & sleep 5 && . env/bin/activate && invoke json.import '../demo/*.json'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - Name: expose
    Ports:
    - :80
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: nodesource/node:precise
  Name: ""
  Platform: ""
  SourceCode: from nodesource/node:precise
