MetaArgs: null
Stages:
- As: build
  BaseName: golang
  Commands:
  - Name: workdir
    Path: /go/src/github.com/coreos/coreos-cloudinit/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - set -eux  && sh ./build
    Name: run
    PrependShell: true
  From:
    Image: golang
  Name: build
  Platform: ""
  SourceCode: FROM golang as build
- BaseName: alpine
  Commands:
  - Name: workdir
    Path: /
  - CmdLine:
    - /coreos-cloudinit
    Name: entrypoint
    PrependShell: false
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/coreos/coreos-cloudinit/bin/coreos-cloudinit
    - /
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
