MetaArgs: null
Stages:
- BaseName: debian:8.0
  Commands:
  - Maintainer: andystanton
    Name: maintainer
  - Env:
    - Key: LEIN_EXEC_VERSION
      Value: 0.3.4
    Name: env
  - Env:
    - Key: LEIN_ROOT
      Value: "1"
    Name: env
  - CmdLine:
    - apt-get update -qq -y &&             apt-get install -y patch wget ca-certificates
      openjdk-7-jre-headless &&             wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      -P /usr/bin &&             chmod +x /usr/bin/lein &&             mkdir -p ${HOME}/.lein
      && echo "{:user {:plugins [[lein-exec \"${LEIN_EXEC_VERSION}\"]]}}" > ${HOME}/.lein/profiles.clj
      &&             apt-get clean &&             rm -rf /var/lib/apt/lists/* /tmp/*
      /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - lein -v
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - image-common
    - /tmp/dexec/image-common
  - Name: volume
    Volumes:
    - /tmp/dexec/build
  - CmdLine:
    - /tmp/dexec/image-common/dexec-script.sh
    - lein exec
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:8.0
  Name: ""
  Platform: ""
  SourceCode: FROM        debian:8.0
