MetaArgs: null
Stages:
- BaseName: freelw/tars_web_develop:latest
  Commands:
  - CmdLine:
    - apt-get install make
    Name: run
    PrependShell: true
  - CmdLine:
    - "export NVM_DIR=\"/root/.nvm\"         && [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"
      \t&& nvm install v8.10.0 \t&& npm i -g @tars/deploy"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /root/entrypoint.sh
  - CmdLine:
    - /root/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: freelw/tars_web_develop:latest
  Name: ""
  Platform: ""
  SourceCode: FROM freelw/tars_web_develop:latest
