MetaArgs: null
Stages:
- BaseName: alpine:3.2
  Commands:
  - CmdLine:
    - apk add --update openssh-client git tar
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - caddy
    - /usr/bin/
  - CmdLine:
    - chmod 0755 /usr/bin/caddy  && /usr/bin/caddy -version
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
    - "8443"
  - Name: workdir
    Path: /srv
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Caddyfile
    - /etc/Caddyfile
  - Chown: ""
    Name: add
    SourcesAndDest:
    - public/
    - /srv/public/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - publics/
    - /srv/publics/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - certs/
    - /srv/certs
  - Chown: ""
    Name: add
    SourcesAndDest:
    - delay.sh
    - /usr/bin/
  - CmdLine:
    - chmod 0755 /usr/bin/delay.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/delay.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.2
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.2
