MetaArgs: null
Stages:
- As: build
  BaseName: alpine:3.7
  Commands:
  - Name: workdir
    Path: /opt
  - CmdLine:
    - apk add --update --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Env:
    - Key: HELM_VERSION
      Value: 2.9.1
    Name: env
  - CmdLine:
    - wget https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -zxvf helm-v${HELM_VERSION}-linux-amd64.tar.gz
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.7
  Name: build
  Platform: ""
  SourceCode: FROM alpine:3.7 as build
- BaseName: alpine:3.7
  Commands:
  - Name: workdir
    Path: /opt
  - CmdLine:
    - apk add --update --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /opt/linux-amd64/helm
    - /usr/local/bin/
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
