MetaArgs:
- DefaultValue: ""
  Key: SOURCE_DATE_EPOCH
  ProvidedValue: null
  Value: ""
Stages:
- BaseName: nrcfuels/centos-dev-lite:latest
  Commands:
  - Key: SOURCE_DATE_EPOCH
    Name: arg
    Value: null
  - Env:
    - Key: PACKAGES_DIR
      Value: /opt
    Name: env
  - Env:
    - Key: MPICH_VER
      Value: 3.2.1
    Name: env
  - Env:
    - Key: GCC_VER
      Value: ${GCC_VER:-8.2.0}
    Name: env
  - Env:
    - Key: MPICH_PREFIX
      Value: ${PACKAGES_DIR}/mpich-${MPICH_VER}/gcc-${GCC_VER}
    Name: env
  - Env:
    - Key: PKG_SRC
      Value: /tmp/pkg_source
    Name: env
  - Name: workdir
    Path: ${PKG_SRC}
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./scripts/mpich-${MPICH_VER}.tar.gz.sha256
    - ./scripts/install-mpich.sh
    - ./
  - CmdLine:
    - ./install-mpich.sh && rm ./install-mpich.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: ${MPICH_PREFIX}/bin:${PATH}<
    Name: env
  - CmdLine:
    - echo 'int main(){return 0;};' > smoke.c &&     mpicc -o smoke smoke.c &&     mpiexec
      -np 1 ./smoke && rm smoke smoke.c &&     echo 'print*, "Hello"; end' > smoke.f90
      &&     mpif90 -o smoke smoke.f90 &&     mpiexec -np 2 ./smoke && rm smoke smoke.f90
    Name: run
    PrependShell: true
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Key: VCS_URL
    Name: arg
    Value: null
  - Key: VCS_VERSION
    Name: arg
    Value: latest
  - Labels:
    - Key: org.label-schema.schema-version
      Value: '"1.0"'
    - Key: org.label-schema.build-date
      Value: '"$BUILD_DATE"'
    - Key: org.label-schema.version
      Value: '"$VCS_VERSION"'
    - Key: org.label-schema.name
      Value: '"centos-mpich-lite"'
    - Key: org.lavel-schema.source-date-epoch
      Value: '"$SOURCE_DATE_EPOCH"'
    - Key: org.label-schema.description
      Value: '"CentOS 7 base image w/ gcc, git, CMake, and MPICH"'
    - Key: org.label-schema.url
      Value: '"https://github.com/nrc-fuels/centos-mpich-lite/"'
    - Key: org.label-schema.vcs-ref
      Value: '"$VCS_REF"'
    - Key: org.label-schema.vcs-url
      Value: '"$VCS_URL"'
    - Key: org.label-schema.vendor
      Value: '"nrcfuels"'
    - Key: org.label-schema.license
      Value: '"N/A"'
    - Key: org.label-schema.docker.cmd
      Value: '"docker run -v $(pwd):/workdir -i -t nrcfuels/centos-mpich-lite:latest"'
    Name: label
  From:
    Image: nrcfuels/centos-dev-lite:latest
  Name: ""
  Platform: ""
  SourceCode: FROM nrcfuels/centos-dev-lite:latest
