MetaArgs: null
Stages:
- BaseName: tomcat:7
  Commands:
  - Maintainer: Ahmet Demir <ahmet2mir+github@gmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: SHELL
      Value: /bin/bash
    Name: env
  - CmdLine:
    - apt-get update && apt-get install multitail
    Name: run
    PrependShell: true
  - CmdLine:
    - "wget https://github.com/MathildeLemee/booking-mvc/raw/master/target/booking-mvc.war
      -O /usr/local/tomcat/webapps/booking-mvc.war && \twget https://jdbc.postgresql.org/download/postgresql-9.4-1200.jdbc4.jar
      -O /usr/local/tomcat/lib/postgresql-9.4-1200.jdbc4.jar"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /usr/local/tomcat/lib/ && \twget http://mirrors.ircam.fr/pub/apache//commons/dbcp/binaries/commons-dbcp-1.4-bin.tar.gz
      -O - | tar xzf - && \tmv commons-dbcp-1.4/commons-dbcp-1.4.jar commons-dbcp-1.4.jar
      && \twget http://mirrors.ircam.fr/pub/apache//commons/pool/binaries/commons-pool-1.6-bin.tar.gz
      \ -O - | tar xzf - && \tmv commons-pool-1.6/commons-pool-1.6.jar commons-pool-1.6.jar"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/confs/tomcat-users.xml
    - /usr/local/tomcat/conf/tomcat-users.xml
  - Chown: ""
    Name: add
    SourcesAndDest:
    - assets/confs
    - /docker
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/scripts/run.sh
    - /run.sh
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: tomcat:7
  Name: ""
  Platform: ""
  SourceCode: FROM tomcat:7
