MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: OpenProject Foundation (opf), info@openproject.org
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: OPF_BRANCH
      Value: stable
    Name: env
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - apt-get update -q
    Name: run
    PrependShell: true
  - CmdLine:
    - locale-gen en_US en_US.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --force-yes build-essential curl git zlib1g-dev libssl-dev
      libreadline-dev libyaml-dev libxml2-dev libxslt-dev libxslt1-dev libmysqlclient-dev
      libpq-dev libsqlite3-dev libyaml-0-2 libmagickwand-dev libmagickcore-dev libmagickcore5-extra
      libgraphviz-dev libgvc6 ruby-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -q -y --force-yes apt-transport-https ca-certificates
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main'
      > /etc/apt/sources.list.d/passenger.list
    Name: run
    PrependShell: true
  - CmdLine:
    - 'chown root: /etc/apt/sources.list.d/passenger.list'
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 600 /etc/apt/sources.list.d/passenger.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -q
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -q -y --force-yes memcached subversion vim wget python-setuptools
      openssh-server sudo pwgen libcurl4-openssl-dev passenger
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/log/supervisor/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/.*session.*required.*pam_loginuid.so.*/session optional pam_loginuid.so/g'
      /etc/pam.d/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/echo -e "LANG=\"en_US.UTF-8\"" > /etc/default/local
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --force-yes -q mysql-client mysql-server
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - Env:
    - Key: CONFIGURE_OPTS
      Value: --disable-install-doc
    Name: env
  - Env:
    - Key: PATH
      Value: /home/openproject/.rbenv/bin:$PATH
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/Gemfile.local
    - /Gemfile.local
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/Gemfile.plugins
    - /Gemfile.plugins
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/setup_system.sh
    - /usr/bin/setup_system
  - CmdLine:
    - chmod +x /usr/bin/setup_system && setup_system
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/passenger-standalone.json
    - /home/openproject/openproject/passenger-standalone.json
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/start_openproject.sh
    - /home/openproject/start_openproject.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/start_openproject_worker.sh
    - /home/openproject/start_openproject_worker.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./files/supervisord.conf
    - /etc/supervisord.conf
  - CmdLine:
    - supervisord
    - -n
    Name: cmd
    PrependShell: false
  - CmdLine:
    - 'echo "INFO: openproject ssh password: `cat /root/openproject-root-pw.txt`"'
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
