MetaArgs: null
Stages:
- BaseName: winggundamth/ubuntu-base:trusty
  Commands:
  - Maintainer: Jirayut Nimsaeng <w [at] winginfotech.net>
    Name: maintainer
  - Env:
    - Key: FROM_BASE
      Value: trusty-20160624
    Name: env
  - Key: APT_CACHER_NG
    Name: arg
    Value: null
  - CmdLine:
    - '[ -n "$APT_CACHER_NG" ] &&       echo "Acquire::http::Proxy \"$APT_CACHER_NG\";"       >
      /etc/apt/apt.conf.d/11proxy || true;     apt-get update &&     apt-get install
      -y wget apt-transport-https &&     wget -qO - https://packagecloud.io/gpg.key
      | apt-key add - &&     echo "deb https://packagecloud.io/grafana/stable/debian/
      wheezy main"       > /etc/apt/sources.list.d/grafana.list &&     apt-get update
      &&     apt-get install -y grafana &&     service grafana-server start &&     service
      grafana-server stop &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
      /etc/apt/apt.conf.d/11proxy'
    Name: run
    PrependShell: true
  - Name: user
    User: grafana
  - Name: workdir
    Path: /usr/share/grafana
  - CmdLine:
    - /usr/sbin/grafana-server
    - --
    - --pidfile=/var/run/grafana-server.pid
    - --config=/etc/grafana/grafana.ini
    - cfg:default.paths.data=/var/lib/grafana
    - cfg:default.paths.logs=/var/log/grafana
    - cfg:default.paths.plugins=/var/lib/grafana/plugins
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "3000"
  - Name: volume
    Volumes:
    - /var/log
    - /etc/grafana
  From:
    Image: winggundamth/ubuntu-base:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM winggundamth/ubuntu-base:trusty
