MetaArgs: null
Stages:
- BaseName: tiokksar/ruby
  Commands:
  - Maintainer: Tomasz Tokarski tomasz@tomasztokarski.com
    Name: maintainer
  - CmdLine:
    - /bin/bash -l -c 'gem install chef --no-ri --no-rdoc'
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash -l -c 'gem install berkshelf --no-ri --no-rdoc'
    Name: run
    PrependShell: true
  From:
    Image: tiokksar/ruby
  Name: ""
  Platform: ""
  SourceCode: FROM tiokksar/ruby
