MetaArgs: null
Stages:
- BaseName: centos:latest
  Commands:
  - Maintainer: alexander.mazurov <alexander.mazurov@gmail.com>
    Name: maintainer
  - Key: version
    Name: arg
    Value: '"6.09.02"'
  - Labels:
    - Key: description
      Value: '"CERN ROOT framework"'
    Name: label
  - Labels:
    - Key: version
      Value: '"${version}"'
    Name: label
  - CmdLine:
    - yum -y install epel-release
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install gcc-c++ bzip2 git vim libpng libjpeg      python-devel libSM
      libX11 libXext libXpm libXft gsl-devel python-pip make cmake3     && yum -y
      clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip && pip install jupyter
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/cmake3 /usr/bin/cmake
    Name: run
    PrependShell: true
  - Env:
    - Key: ROOTSYS
      Value: '"/opt/root"'
    Name: env
  - Env:
    - Key: PATH
      Value: '"$ROOTSYS/bin:$ROOTSYS/bin/bin:$PATH"'
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: '"$ROOTSYS/lib:$LD_LIBRARY_PATH"'
    Name: env
  - Env:
    - Key: PYTHONPATH
      Value: '"$ROOTSYS/lib:$PYTHONPATH"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://root.cern.ch/download/root_v${version}.Linux-centos7-x86_64-gcc4.8.tar.gz
    - /var/tmp/root.tar.gz
  - CmdLine:
    - tar xzf /var/tmp/root.tar.gz -C /opt && rm /var/tmp/root.tar.gz
    Name: run
    PrependShell: true
  From:
    Image: centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM centos:latest
