MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update -y &&  apt-get install git vim  build-essential libncursesw5-dev
      libgdbm-dev libc6-dev zlib1g-dev libsqlite3-dev tk-dev libssl-dev openssl libbz2-dev
      libreadline-dev build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev
      libsqlite3-dev tk-dev libssl-dev openssl libbz2-dev libreadline-dev git vim  curl
      wget zip unzip locales software-properties-common python-software-properties  -y  &&  apt-get
      update -y &&  bin/bash -c "mkdir /root/.pyenv"
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Env:
    - Key: PYENV_ROOT
      Value: $HOME/.pyenv
    Name: env
  - Env:
    - Key: PATH
      Value: $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    Name: env
  - CmdLine:
    - pyenv install 3.6.3
    Name: run
    PrependShell: true
  - CmdLine:
    - pyenv global 3.6.3
    Name: run
    PrependShell: true
  - CmdLine:
    - python -V
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'eval "$(pyenv init -)"' >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install jupyter &&  wget https://litipk.github.io/Jupyter-PHP-Installer/dist/jupyter-php-installer.phar
      &&  locale-gen en_US.UTF-8 &&  export LANG=en_US.UTF-8 &&  add-apt-repository
      ppa:ondrej/php -y &&  apt-get update -y &&  apt-get install php7.1 -y &&  curl
      -sS https://getcomposer.org/installer | php &&  mv composer.phar /usr/local/bin/composer
      &&  composer require psy/psysh &&  apt-get install php-zmq -y &&  php jupyter-php-installer.phar
      install -vv
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: dialog
    Name: env
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
