MetaArgs: null
Stages:
- BaseName: fedora:25
  Commands:
  - Maintainer: disyam.adityana@gmail.com
    Name: maintainer
  - CmdLine:
    - rpm -ivh https://dev.mysql.com/get/mysql57-community-release-fc25-9.noarch.rpm
      &&     dnf -y install mysql-utilities
    Name: run
    PrependShell: true
  From:
    Image: fedora:25
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:25
