MetaArgs: null
Stages:
- BaseName: mariadb:10.4
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Cheewai Lai <cheewai.lai@gmail.com>"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - set-mysql-uid.sh
    - /usr/local/bin/set-mysql-uid.sh
  - CmdLine:
    - /usr/local/bin/set-mysql-uid.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: mariadb:10.4
  Name: ""
  Platform: ""
  SourceCode: FROM mariadb:10.4
