MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Env:
    - Key: TAGSPACES_VERSION
      Value: 2.7.5
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y nginx nginx-extras apache2-utils && apt-get
      install -y wget unzip
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/dav
  - Name: expose
    Ports:
    - "80"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - webdav.conf
    - /etc/nginx/conf.d/default.conf
  - CmdLine:
    - rm /etc/nginx/sites-enabled/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chmod +x entrypoint.sh  && wget https://github.com/tagspaces/tagspaces/releases/download/v${TAGSPACES_VERSION}/tagspaces-${TAGSPACES_VERSION}-web.zip  &&
      unzip tagspaces-${TAGSPACES_VERSION}-web.zip  && mv tagspaces /usr/share/nginx/www  &&
      rm -rf tagspaces-${TAGSPACES_VERSION}-web.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - nginx -g "daemon off;"
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
