MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: shimtom
    Name: maintainer
  - Name: expose
    Ports:
    - "6006"
  - Name: expose
    Ports:
    - "8888"
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends       build-essential       curl       git       libbz2-dev       libncurses5-dev       libreadline-dev       libsqlite3-dev       libssl-dev       llvm       make       software-properties-common       vim       wget       xz-utils       zlib1g-dev       &&     apt-get
      clean
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Env:
    - Key: PYENV_ROOT
      Value: $HOME/.pyenv
    Name: env
  - Env:
    - Key: PATH
      Value: $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    Name: env
  - CmdLine:
    - git clone https://github.com/yyuu/pyenv.git /root/.pyenv
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'eval "$(pyenv init -)"' >> /root/.bashrc
    Name: run
    PrependShell: true
  - Env:
    - Key: ANACONDA_VERSION
      Value: anaconda2-4.1.1
    Name: env
  - CmdLine:
    - pyenv install $ANACONDA_VERSION &&     pyenv rehash &&     pyenv global $ANACONDA_VERSION
      &&     pyenv rehash
    Name: run
    PrependShell: true
  - Env:
    - Key: TENSORFLOW_VERSION
      Value: 0.12.0rc1
    Name: env
  - CmdLine:
    - conda create -n tensorflow-python2 python=2.7 anaconda -y
    Name: run
    PrependShell: true
  - CmdLine:
    - pyenv global $ANACONDA_VERSION/envs/tensorflow-python2
    Name: run
    PrependShell: true
  - CmdLine:
    - pyenv rehash
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip --no-cache-dir install --ignore-installed --upgrade       https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-${TENSORFLOW_VERSION}-cp27-none-linux_x86_64.whl
    Name: run
    PrependShell: true
  - CmdLine:
    - conda create -n tensorflow-python3 python=3.5 anaconda -y
    Name: run
    PrependShell: true
  - CmdLine:
    - pyenv global $ANACONDA_VERSION/envs/tensorflow-python3
    Name: run
    PrependShell: true
  - CmdLine:
    - pyenv rehash
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip --no-cache-dir install --ignore-installed --upgrade       https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-${TENSORFLOW_VERSION}-cp35-cp35m-linux_x86_64.whl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jupyter_notebook_config.py
    - /root/.jupyter/
  - Name: workdir
    Path: /notebooks
  - CmdLine:
    - jupyter-notebook
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
