MetaArgs: null
Stages:
- BaseName: alpine:3.9
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"The CoBloX developers team@coblox.tech"'
    Name: label
  - Env:
    - Key: VERSION
      Value: 0.17.0
    Name: env
  - CmdLine:
    - apk add --no-cache bitcoin~$VERSION bitcoin-cli~$VERSION
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "18332"
    - "18333"
    - "18443"
    - "18444"
    - "8332"
    - "8333"
  - CmdLine:
    - /usr/bin/bitcoind
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.9
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.9
