MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Jun <zhoujun3372@gmail.com>"'
    Name: label
  - CmdLine:
    - apk add --no-cache bash bash-doc bash-completion wget     && cd /tmp     &&
      wget https://github.com/cnlh/nps/releases/download/v0.23.2/linux_386_server.tar.gz     &&
      tar -zxvf linux_386_server.tar.gz     && rm -rf linux_386_server.tar.gz     &&
      cp -rf /tmp/nps /var/local/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /nps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - shell.sh
    - /tmp/
  - Name: workdir
    Path: /nps
  - Name: volume
    Volumes:
    - /nps
  - Name: expose
    Ports:
    - "443"
    - "6000"
    - "80"
    - "8024"
    - "8080"
  - CmdLine:
    - /tmp/shell.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
