MetaArgs: null
Stages:
- BaseName: miguelbrunello/base
  Commands:
  - Maintainer: Miguel Brunello <miguel.brunello@unc.edu.ar>
    Name: maintainer
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - apt-get -qq update && apt-get install -y     openjdk-7-jre     tomcat7     curl
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /etc/cron.daily/logrotate /etc/cron.hourly/logrotate
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - logrotate
    - /etc/logrotate.d/tomcat7
  - CmdLine:
    - chmod 644 /etc/logrotate.d/tomcat7
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - catalina.conf
    - /etc/supervisord.d/catalina.conf
  - Env:
    - Key: CATALINA_HOME
      Value: /var/lib/tomcat7
    Name: env
  - Env:
    - Key: PATH
      Value: $CATALINA_HOME/bin:$PATH
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - data/sample.war
    - $CATALINA_HOME/webapps/sample.war
  - Env:
    - Key: CATALINA_OLD
      Value: /usr/share/tomcat7
    Name: env
  - CmdLine:
    - mkdir -p "$CATALINA_HOME"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $CATALINA_HOME
  - CmdLine:
    - ln -s $CATALINA_OLD/bin/ $CATALINA_HOME/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s $CATALINA_OLD/lib/ $CATALINA_HOME/lib
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p $CATALINA_HOME/temp
    Name: run
    PrependShell: true
  - CmdLine:
    - /start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: miguelbrunello/base
  Name: ""
  Platform: ""
  SourceCode: FROM miguelbrunello/base
