MetaArgs: null
Stages:
- BaseName: cloudposse/library:tengine
  Commands:
  - Env:
    - Key: ETCD_HOST
      Value: 172.17.42.1
    Name: env
  - Env:
    - Key: ETCD_PORT
      Value: "4001"
    Name: env
  - Env:
    - Key: CONFD_INTERVAL
      Value: "60"
    Name: env
  - Env:
    - Key: CONFD_VERSION
      Value: 0.9.0
    Name: env
  - Env:
    - Key: CONFD_PREFIX
      Value: /nginx
    Name: env
  - Env:
    - Key: NGINX_NAME
      Value: nginx
    Name: env
  - Env:
    - Key: NGINX_PATH
      Value: /nginx
    Name: env
  - Env:
    - Key: DOCKER_DNS
      Value: 8.8.8.8
    Name: env
  - Env:
    - Key: GA_TRACKING_ID
      Value: '-'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/kelseyhightower/confd/releases/download/v$CONFD_VERSION/confd-$CONFD_VERSION-linux-amd64
    - /usr/bin/confd
  - Chown: ""
    Name: add
    SourcesAndDest:
    - confd/
    - /etc/confd
  - Chown: ""
    Name: add
    SourcesAndDest:
    - reload.sh
    - /opt/reload.sh
  - CmdLine:
    - chmod 755 /usr/bin/confd
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /etc/nginx
  - CmdLine:
    - /usr/bin/confd -prefix=$CONFD_PREFIX -interval=$CONFD_INTERVAL -node=http://$ETCD_HOST:$ETCD_PORT
    Name: cmd
    PrependShell: true
  From:
    Image: cloudposse/library:tengine
  Name: ""
  Platform: ""
  SourceCode: FROM cloudposse/library:tengine
