MetaArgs: null
Stages:
- As: base
  BaseName: mcr.microsoft.com/dotnet/core/aspnet:2.2
  Commands:
  - CmdLine:
    - useradd -u 555 dockerapp    && mkdir /home/dockerapp    && mkdir /home/dockerapp/app     &&
      mkdir /home/dockerapp/data     && mkdir /home/dockerapp/cashe     && chown -R
      dockerapp:dockerapp /home/dockerapp      && addgroup dockerapp staff
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Name: expose
    Ports:
    - "80"
  From:
    Image: mcr.microsoft.com/dotnet/core/aspnet:2.2
  Name: base
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
- As: build
  BaseName: mcr.microsoft.com/dotnet/core/sdk:2.2
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - AmrmapAdminApi/AmrmapAdminApi.csproj
    - AmrmapAdminApi/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - AmrmapAdminDAL/AmrmapAdminDAL.csproj
    - AmrmapAdminDAL/
  - CmdLine:
    - dotnet restore "AmrmapAdminApi/AmrmapAdminApi.csproj"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Name: workdir
    Path: '"/src/AmrmapAdminApi"'
  - CmdLine:
    - dotnet build "AmrmapAdminApi.csproj" -c Release -o /app
    Name: run
    PrependShell: true
  From:
    Image: mcr.microsoft.com/dotnet/core/sdk:2.2
  Name: build
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
- As: publish
  BaseName: build
  Commands:
  - CmdLine:
    - dotnet publish "AmrmapAdminApi.csproj" -c Release -o /app
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 1
      Named: build
  Name: publish
  Platform: ""
  SourceCode: FROM build AS publish
- As: final
  BaseName: base
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: publish
    Name: copy
    SourcesAndDest:
    - /app
    - .
  - Env:
    - Key: ASPNETCORE_ENVIRONMENT
      Value: Production
    Name: env
  - CmdLine:
    - dotnet
    - AmrmapAdminApi.dll
    Name: entrypoint
    PrependShell: false
  From:
    Stage:
      Index: 0
      Named: base
  Name: final
  Platform: ""
  SourceCode: FROM base AS final
