MetaArgs: null
Stages:
- BaseName: centos:centos7
  Commands:
  - CmdLine:
    - yum -y install epel-release && yum clean all &&     yum -y install     gcc     make     rpmdevtools     mock     perl     sudo     tar     zlib-devel     createrepo     wget
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser     --comment "RPM Builder"     --home /home/rpm-builder     --create-home     rpm-builder
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/Defaults    env_reset/#Defaults    env_reset/' /etc/sudoers     &&
      sed -i -e 's/Defaults    secure_path/#Defaults    secure_path/' /etc/sudoers     &&
      echo 'Defaults    env_keep += "PATH"' >> /etc/sudoers     && echo 'rpm-builder    ALL=(ALL)
      NOPASSWD:ALL' >> /etc/sudoers
    Name: run
    PrependShell: true
  - Env:
    - Key: RHEL_VERSION
      Value: "7"
    Name: env
  - Name: user
    User: rpm-builder
  - CmdLine:
    - rpmdev-setuptree
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/rpm-builder
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: centos:centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7
