MetaArgs: null
Stages:
- BaseName: node:7.4-alpine
  Commands:
  - Maintainer: marko.celan@gmail.com
    Name: maintainer
  - CmdLine:
    - mkdir /src     && npm install -g eslint@3.13.1     && npm install -g eslint-plugin-jasmine@2.2.0     &&
      rm -fr /root/.npm
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src
  - CmdLine:
    - /usr/local/bin/eslint
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:7.4-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:7.4-alpine
