MetaArgs: null
Stages:
- BaseName: node:10.15-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"ansgar@elbstack.com"'
    Name: label
  - Labels:
    - Key: name
      Value: '"dashoefer-iks-graphql-proxy"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package-lock.json
    - /app/
  - Name: workdir
    Path: /app
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Env:
    - Key: PORT
      Value: "80"
    Name: env
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - npm
    - start
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:10.15-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10.15-alpine
