MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.10.3-alpine
  Commands:
  - Key: SRC_PATH
    Name: arg
    Value: /go/src/bitbucket.org/game-labs/pinnacle-storage
  - Name: workdir
    Path: $SRC_PATH
  - CmdLine:
    - apk add --no-cache git dep make
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gopkg.toml
    - Gopkg.lock
    - Makefile
    - ./
  - CmdLine:
    - dep ensure -vendor-only
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./pkg
    - ./pkg
  - CmdLine:
    - go test ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 go build -a -o /tmp/server pkg/cmd/server/*.go
    Name: run
    PrependShell: true
  From:
    Image: golang:1.10.3-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.10.3-alpine as builder
- BaseName: alpine:3.8
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /tmp/server
    - .
  - CmdLine:
    - /app/server
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
