MetaArgs: null
Stages:
- BaseName: rocker/tidyverse
  Commands:
  - CmdLine:
    - apt-get update -qq && apt-get -y --no-install-recommends install   && install2.r
      --error     --deps TRUE     here
    Name: run
    PrependShell: true
  From:
    Image: rocker/tidyverse
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/tidyverse
