MetaArgs: null
Stages:
- BaseName: kentwait/alpine-glibc-base
  Commands:
  - Maintainer: Kent Kawashima <kentkawashima@gmail.com>
    Name: maintainer
  - Env:
    - Key: JAVA_VERSION_MAJOR
      Value: "8"
    Name: env
  - Env:
    - Key: JAVA_VERSION_MINOR
      Value: "45"
    Name: env
  - Env:
    - Key: JAVA_VERSION_BUILD
      Value: "14"
    Name: env
  - Env:
    - Key: JAVA_PACKAGE
      Value: jdk
    Name: env
  - CmdLine:
    - 'apk update && apk upgrade   && apk add --no-cache --virtual temp-pkgs     build-base     curl     ca-certificates   &&
      mkdir -p /opt && curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie"  http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz   |
      tar -xzf - -C /opt   && ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR}
      /opt/jdk   && rm -rf /opt/jdk/*src.zip             /opt/jdk/lib/missioncontrol             /opt/jdk/lib/visualvm             /opt/jdk/lib/*javafx*             /opt/jdk/jre/lib/plugin.jar             /opt/jdk/jre/lib/ext/jfxrt.jar             /opt/jdk/jre/bin/javaws             /opt/jdk/jre/lib/javaws.jar             /opt/jdk/jre/lib/desktop             /opt/jdk/jre/plugin             /opt/jdk/jre/lib/deploy*             /opt/jdk/jre/lib/*javafx*             /opt/jdk/jre/lib/*jfx*             /opt/jdk/jre/lib/amd64/libdecora_sse.so             /opt/jdk/jre/lib/amd64/libprism_*.so             /opt/jdk/jre/lib/amd64/libfxplugins.so             /opt/jdk/jre/lib/amd64/libglass.so             /opt/jdk/jre/lib/amd64/libgstreamer-lite.so             /opt/jdk/jre/lib/amd64/libjavafx*.so             /opt/jdk/jre/lib/amd64/libjfx*.so   &&
      apk del temp-pkgs   && rm -rf /tmp/* /var/cache/apk/* /root/.wget-hsts /root/.[acpw]*'
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /opt/jdk
    Name: env
  - Env:
    - Key: PATH
      Value: ${PATH}:${JAVA_HOME}/bin
    Name: env
  - Name: workdir
    Path: /
  From:
    Image: kentwait/alpine-glibc-base
  Name: ""
  Platform: ""
  SourceCode: FROM kentwait/alpine-glibc-base
