MetaArgs: null
Stages:
- As: builder
  BaseName: ubuntu:18.04
  Commands:
  - Name: workdir
    Path: /root
  - CmdLine:
    - apt-get update -y     && apt-get install -y --no-install-recommends build-essential
      git ca-certificates apt-utils     && git clone https://github.com/solusipse/fiche.git
      /root/fiche
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/fiche
  - CmdLine:
    - make     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: builder
  Platform: ""
  SourceCode: FROM ubuntu:18.04 as builder
- As: runner
  BaseName: ubuntu:18.04
  Commands:
  - Name: volume
    Volumes:
    - /data
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.py
    - /usr/bin
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - highl.py
    - /usr/bin
  - Name: workdir
    Path: /root
  - CmdLine:
    - apt-get update -y     && apt-get install -y --no-install-recommends python3
      python3-flask python3-pygments supervisor ca-certificates apt-utils     && rm
      -rf /var/lib/apt/lists/*     && mkdir -p /data/codes     && chmod +x /usr/bin/highl.py
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /root/fiche/fiche
    - .
  - Name: expose
    Ports:
    - "8988"
  - Name: expose
    Ports:
    - "8989"
  - CmdLine:
    - /usr/bin/python3
    - /usr/bin/entrypoint.py
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: runner
  Platform: ""
  SourceCode: FROM ubuntu:18.04 as runner
