MetaArgs: null
Stages:
- BaseName: python:3
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - reqs.txt
    - ./
  - CmdLine:
    - pip install --no-cache-dir -r reqs.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - python
    - ./book_search/start.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3
  Name: ""
  Platform: ""
  SourceCode: FROM python:3
