MetaArgs: null
Stages:
- BaseName: hauptmedia/spark-base
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/sbin/docker-entrypoint.sh
  - Name: expose
    Ports:
    - "8081"
  - CmdLine:
    - /usr/local/sbin/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: hauptmedia/spark-base
  Name: ""
  Platform: ""
  SourceCode: "FROM\t\thauptmedia/spark-base"
