MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: Sankara Shunmugasundaram <sankara.shunmuga@appdirect.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y apache2 libapache2-mod-security2 supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/supervisor
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - CmdLine:
    - a2enmod security2
    Name: run
    PrependShell: true
  - CmdLine:
    - service apache2 restart
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
