MetaArgs: null
Stages:
- BaseName: huzhenghui/sdkman
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"hu@daonao.com"'
    Name: label
  - Labels:
    - Key: trigger_comment
      Value: '"SDKMAN updated to 5.6.2+294"'
    Name: label
  - CmdLine:
    - bash -c 'source /root/.sdkman/bin/sdkman-init.sh; sdk version; echo -e "\n----------"
      $? "----------\n"' &&     bash -c 'source /root/.sdkman/bin/sdkman-init.sh;
      echo y | sdk install java 8.0.181-oracle; echo -e "\n----------" $? "----------\n"'
      &&     bash -c 'source /root/.sdkman/bin/sdkman-init.sh; export' &&     bash
      -c 'source /root/.sdkman/bin/sdkman-init.sh; ${JAVA_HOME}/bin/java -version'
    Name: run
    PrependShell: true
  From:
    Image: huzhenghui/sdkman
  Name: ""
  Platform: ""
  SourceCode: FROM huzhenghui/sdkman
