MetaArgs: null
Stages:
- BaseName: fedora:30
  Commands:
  - Env:
    - Key: container
      Value: docker
    Name: env
  - CmdLine:
    - dnf makecache && dnf -y update && dnf clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - dnf makecache     && dnf -y install     ansible     bash     systemd     sudo     which     python3     python3-dnf     python3-pip     &&
      dnf clean all &&   (cd /lib/systemd/system/sysinit.target.wants/; for i in *;
      do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);   rm -f /lib/systemd/system/multi-user.target.wants/*;  rm
      -f /etc/systemd/system/*.wants/*;  rm -f /lib/systemd/system/local-fs.target.wants/*;   rm
      -f /lib/systemd/system/sockets.target.wants/*udev*;   rm -f /lib/systemd/system/sockets.target.wants/*initctl*;   rm
      -f /lib/systemd/system/basic.target.wants/*;  rm -f /lib/systemd/system/anaconda.target.wants/*;  pip3
      install q epdb
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - echo -e "localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3"
      > /etc/ansible/hosts
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /sys/fs/cgroup
    - /tmp
    - /run
  - CmdLine:
    - /usr/sbin/init
    Name: cmd
    PrependShell: false
  From:
    Image: fedora:30
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:30
