MetaArgs: null
Stages:
- BaseName: resuelve/elixir:latest
  Commands:
  - Maintainer: Tobias Bohwalli <hi@futhr.io>
    Name: maintainer
  - CmdLine:
    - apk --no-cache add -U nodejs nodejs-npm yarn inotify-tools libsass libsass-dev
      sassc
    Name: run
    PrependShell: true
  - CmdLine:
    - mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez
    Name: run
    PrependShell: true
  - CmdLine:
    - mix local.rebar --force
    Name: run
    PrependShell: true
  - CmdLine:
    - mix local.hex --force
    Name: run
    PrependShell: true
  - Env:
    - Key: QT_QPA_PLATFORM
      Value: offscreen
    Name: env
  - CmdLine:
    - apk add --update-cache xvfb dbus ttf-freefont fontconfig
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mix hex.info && node -v && npm -v && yarn -v
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  From:
    Image: resuelve/elixir:latest
  Name: ""
  Platform: ""
  SourceCode: FROM resuelve/elixir:latest
