MetaArgs: null
Stages:
- BaseName: quay.io/pypa/manylinux1_x86_64
  Commands:
  - Env:
    - Key: GEOS_VERSION
      Value: 3.5.0
    Name: env
  - CmdLine:
    - mkdir -p /src     && cd /src     && curl -f -L -O http://download.osgeo.org/geos/geos-$GEOS_VERSION.tar.bz2     &&
      tar jxf geos-$GEOS_VERSION.tar.bz2     && cd /src/geos-$GEOS_VERSION     &&
      ./configure     && make     && make install     && rm -rf /src
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements-dev.txt
    - /tmp/requirements-dev.txt
  - CmdLine:
    - for PYBIN in /opt/python/*/bin; do         $PYBIN/pip install -r /tmp/requirements-dev.txt
      ;     done
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /io
  - CmdLine:
    - /io/build-linux-wheels.sh
    Name: cmd
    PrependShell: false
  From:
    Image: quay.io/pypa/manylinux1_x86_64
  Name: ""
  Platform: ""
  SourceCode: FROM quay.io/pypa/manylinux1_x86_64
- BaseName: python:3.6-slim
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - pip install --trusted-host pypi.python.org -r requirements.txt && python setup.py
      install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Env:
    - Key: NAME
      Value: World
    Name: env
  - CmdLine:
    - python
    - HydroModelBrowser.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-slim
