MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: Jacob Tomlinson <jacob@tom.linson.uk>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache bash py-pip && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache sqlite && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip --no-cache-dir install awscli
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sqlite-to-s3.sh
    - /usr/bin/sqlite-to-s3
  - CmdLine:
    - /usr/bin/sqlite-to-s3
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - cron
    - 0 1 * * *
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
