MetaArgs: null
Stages:
- BaseName: anigeo/awscli
  Commands:
  - CmdLine:
    - apk update && apk --update add openssl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /docker-entrypoint.sh
  - Env:
    - Key: FILE_REGEX
      Value: '''*'''
    Name: env
  - Name: volume
    Volumes:
    - '[''/backup'']'
  - CmdLine:
    - '''/docker-entrypoint.sh'''
    Name: entrypoint
    PrependShell: true
  From:
    Image: anigeo/awscli
  Name: ""
  Platform: ""
  SourceCode: FROM anigeo/awscli
