MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - resource
    - /opt/resource
  - CmdLine:
    - "cd /opt/resource && \tnpm install --silent && \tnpm cache clean && \tchmod
      755 ./*"
    Name: run
    PrependShell: true
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
