MetaArgs: null
Stages:
- BaseName: debian:8
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: JAVA_VERSION
      Value: "8"
    Name: env
  - Env:
    - Key: JMX_PROMETHEUS_HTTPSERVER_VERSION
      Value: 0.7-SNAPSHOT
    Name: env
  - CmdLine:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF &&   DISTRO=debian
      &&   CODENAME=jessie &&   echo "deb http://http.debian.net/${DISTRO} ${CODENAME}-backports
      main" >> /etc/apt/sources.list &&   apt-get update &&   apt-get -y upgrade &&   apt-get
      -y install -yq --no-install-recommends       apt-utils       bash       curl       openjdk-${JAVA_VERSION}-jre-headless
      &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /jmx_prometheus_httpserver
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /jmx_prometheus_httpserver
  - CmdLine:
    - curl -O -k -L https://github.com/yagniio/docker-jmx-exporter/releases/download/$JMX_PROMETHEUS_HTTPSERVER_VERSION/jmx_prometheus_httpserver-$JMX_PROMETHEUS_HTTPSERVER_VERSION-jar-with-dependencies.jar
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker-entrypoint.sh
    - /jmx_prometheus_httpserver/docker-entrypoint.sh
  - Name: expose
    Ports:
    - "9138"
  - Name: volume
    Volumes:
    - /jmx_prometheus
  - CmdLine:
    - /jmx_prometheus_httpserver/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /jmx_prometheus/config.yml
    Name: cmd
    PrependShell: false
  From:
    Image: debian:8
  Name: ""
  Platform: ""
  SourceCode: FROM debian:8
