MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Didier FABERT (tartare) <didier@tartarefr.eu>
    Name: maintainer
  - CmdLine:
    - yum install -y     epel-release     && yum clean all     && rm -rf /var/cache/yum
    Name: run
    PrependShell: true
  - CmdLine:
    - yum update -y     && yum clean all     && rm -rf /var/cache/yum
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y   cobbler   cobbler-web   pykickstart   debmirror   curl wget   rsync   supervisor   net-tools   memtest86+   which   &&
      yum clean all   &&  rm -rf /var/cache/yum
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord/supervisord.conf
    - /etc/supervisord.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord/cobblerd.ini
    - /etc/supervisord.d/cobblerd.ini
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord/tftpd.ini
    - /etc/supervisord.d/tftpd.ini
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord/httpd.ini
    - /etc/supervisord.d/httpd.ini
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/partition_config
    - /var/lib/cobbler/snippets/partition_config
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/configure_X
    - /var/lib/cobbler/snippets/configure_X
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/add_repos
    - /var/lib/cobbler/snippets/add_repos
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/disable_prelink
    - /var/lib/cobbler/snippets/disable_prelink
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/systemd_persistant_journal
    - /var/lib/cobbler/snippets/systemd_persistant_journal
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/rkhunter
    - /var/lib/cobbler/snippets/rkhunter
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/enable_X
    - /var/lib/cobbler/snippets/enable_X
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - snippets/yum_update
    - /var/lib/cobbler/snippets/yum_update
  - CmdLine:
    - for kickstart in sample sample_end legacy ;     do         additional_post_snippets=""
      ;         for snippet in                         add_repos                         disable_prelink                         systemd_persistant_journal                         rkhunter                         enable_X                         yum_update
      ;         do           additional_post_snippets="${additional_post_snippets}\n\$SNIPPET('${snippet}')"
      ;         done ;         sed -i            -e "/post_anamon/ s/$/${additional_post_snippets}/"            -e
      "/^autopart/ s/^.*$/\$SNIPPET('partition_config')/"            -e "/^skipx/
      s/^.*$/\$SNIPPET('configure_X')/"        /var/lib/cobbler/kickstarts/${kickstart}.ks
      ;     done
    Name: run
    PrependShell: true
  - CmdLine:
    - echo -e "@core\n\nvim-enhanced\n#set \$el_type = \$getVar('type', 'minimal')\n#if
      \$el_type == 'desktop'\n@base\n@network-tools\n@x11\n@graphical-admin-tools\n#set
      \$el_version = \$getVar('os_version', None)\n#if \$el_version == 'rhel6'\n@desktop-platform\n@basic-desktop\n#else
      if \$el_version == 'rhel7'\n@gnome-desktop\n#end if\n#end if\nkernel" >> /var/lib/cobbler/snippets/func_install_if_enabled
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - first-sync.sh
    - /usr/local/bin/first-sync.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod 755 /entrypoint.sh /usr/local/bin/first-sync.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "25151"
    - "443"
    - "69"
    - "80"
  - Name: volume
    Volumes:
    - /var/www/cobbler
    - /var/lib/tftp
    - /var/lib/cobbler/config
    - /var/lib/cobbler/backup
    - /var/run/supervisor
    - /mnt
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
