MetaArgs: null
Stages:
- BaseName: python:3.6.2
  Commands:
  - Name: workdir
    Path: /app
  - Env:
    - Key: PYTHONPATH
      Value: /app
    Name: env
  - Env:
    - Key: DJANGO_SETTINGS_MODULE
      Value: aiakos.settings
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /app/requirements.txt
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - SECRET_KEY=x python -m aiakos collectstatic --noinput
    Name: run
    PrependShell: true
  - CmdLine:
    - gunicorn
    - -k
    - gevent
    - -b
    - '[::]:80'
    - aiakos.wsgi
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "80"
  From:
    Image: python:3.6.2
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6.2
