MetaArgs: null
Stages:
- BaseName: stafli/stafli.init.supervisor:supervisor31_centos7
  Commands:
  - Labels:
    - Key: description
      Value: '"Stafli Redis Cache System (stafli/stafli.cache.redis), Based on Stafli
        Supervisor Init (stafli/stafli.init.supervisor)"'
    - Key: maintainer
      Value: '"lp@algarvio.org"'
    - Key: org.label-schema.schema-version
      Value: '"1.0.0-rc.1"'
    - Key: org.label-schema.name
      Value: '"Stafli Redis Cache System (stafli/stafli.cache.redis)"'
    - Key: org.label-schema.description
      Value: '"Based on Stafli Supervisor Init (stafli/stafli.init.supervisor)"'
    - Key: org.label-schema.keywords
      Value: '"stafli, redis, cache, debian, centos"'
    - Key: org.label-schema.url
      Value: '"https://stafli.org/"'
    - Key: org.label-schema.license
      Value: '"GPLv3"'
    - Key: org.label-schema.vendor-name
      Value: '"Stafli"'
    - Key: org.label-schema.vendor-email
      Value: '"info@stafli.org"'
    - Key: org.label-schema.vendor-website
      Value: '"https://www.stafli.org"'
    - Key: org.label-schema.authors.lpalgarvio.name
      Value: '"Luis Pedro Algarvio"'
    - Key: org.label-schema.authors.lpalgarvio.email
      Value: '"lp@algarvio.org"'
    - Key: org.label-schema.authors.lpalgarvio.homepage
      Value: '"https://lp.algarvio.org"'
    - Key: org.label-schema.authors.lpalgarvio.role
      Value: '"Maintainer"'
    - Key: org.label-schema.registry-url
      Value: '"https://hub.docker.com/r/stafli/stafli.cache.redis"'
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/stafli-org/stafli.cache.redis"'
    - Key: org.label-schema.vcs-branch
      Value: '"master"'
    - Key: org.label-schema.os-id
      Value: '"centos"'
    - Key: org.label-schema.os-version-id
      Value: '"7"'
    - Key: org.label-schema.os-architecture
      Value: '"amd64"'
    - Key: org.label-schema.version
      Value: '"1.0"'
    Name: label
  - Key: app_redis_user
    Name: arg
    Value: '"redis"'
  - Key: app_redis_group
    Name: arg
    Value: '"redis"'
  - Key: app_redis_home
    Name: arg
    Value: '"/var/lib/redis"'
  - Key: app_redis_loglevel
    Name: arg
    Value: '"notice"'
  - Key: app_redis_listen_addr
    Name: arg
    Value: '"0.0.0.0"'
  - Key: app_redis_listen_port
    Name: arg
    Value: '"6379"'
  - Key: app_redis_listen_timeout
    Name: arg
    Value: '"5"'
  - Key: app_redis_listen_keepalive
    Name: arg
    Value: '"60"'
  - Key: app_redis_limit_backlog
    Name: arg
    Value: '"256"'
  - Key: app_redis_limit_concurent
    Name: arg
    Value: '"256"'
  - Key: app_redis_limit_memory
    Name: arg
    Value: '"134217728"'
  - CmdLine:
    - printf "Installing repositories and packages...\n" &&         printf "Refresh
      the package manager...\n" &&     rpm --rebuilddb && yum makecache &&         printf
      "Install the redis packages...\n" &&     yum install -y       redis &&         printf
      "Cleanup the package manager...\n" &&     yum clean all && rm -Rf /var/lib/yum/*
      && rm -Rf /var/cache/yum/* &&         printf "Finished installing repositories
      and packages...\n";
    Name: run
    PrependShell: true
  - CmdLine:
    - printf "Adding users and groups...\n" &&         printf "Add redis user and
      group...\n" &&     id -g ${app_redis_user}     ||     groupadd       --system
      ${app_redis_group} &&     id -u ${app_redis_user} &&     usermod       --gid
      ${app_redis_group}       --home ${app_redis_home}       --shell /sbin/nologin       ${app_redis_user}     ||     useradd       --system
      --gid ${app_redis_group}       --no-create-home --home-dir ${app_redis_home}       --shell
      /sbin/nologin       ${app_redis_user} &&         printf "Finished adding users
      and groups...\n";
    Name: run
    PrependShell: true
  - CmdLine:
    - printf "Updading Supervisor configuration...\n" &&         file="/etc/supervisord.d/init.conf"
      &&     printf "\n# Applying configuration for ${file}...\n" &&     perl -0p
      -i -e "s>supervisorctl start rclocal;>supervisorctl start rclocal; supervisorctl
      start redis;>" ${file} &&     printf "Done patching ${file}...\n" &&         file="/etc/supervisord.d/redis.conf"
      &&     printf "\n# Applying configuration for ${file}...\n" &&     printf "#
      Redis\n[program:redis]\ncommand=/bin/bash -c \"\$(which redis-server) /etc/redis.conf
      --daemonize no\"\nautostart=false\nautorestart=true\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\nstderr_logfile=/dev/stderr\nstderr_logfile_maxbytes=0\nstdout_events_enabled=true\nstderr_events_enabled=true\n\n"
      > ${file} &&     printf "Done patching ${file}...\n" &&         printf "Finished
      updading Supervisor configuration...\n";
    Name: run
    PrependShell: true
  - CmdLine:
    - printf "Updading Redis configuration...\n" &&             file="/etc/redis.conf"
      &&     printf "\n# Applying configuration for ${file}...\n" &&     perl -0p
      -i -e "s># Note that Redis will write a pid file in /var/run/redis.pid when
      daemonized.\ndaemonize .*\n># Note that Redis will write a pid file in /var/run/redis.pid
      when daemonized.\ndaemonize no\n>" ${file} &&     perl -0p -i -e "s># warning
      (only very important / critical messages are logged)\nloglevel .*\n># warning
      (only very important / critical messages are logged)\nloglevel ${app_redis_loglevel}\n>"
      ${file} &&     perl -0p -i -e "s># output for logging but daemonize, logs will
      be sent to /dev/null\nlogfile .*># output for logging but daemonize, logs will
      be sent to /dev/null\n#logfile /proc/self/fd/2>" ${file} &&     perl -0p -i
      -e "s># ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\nbind
      .*\n># ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\nbind
      ${app_redis_listen_addr}\n>" ${file} &&     perl -0p -i -e "s># If port 0 is
      specified Redis will not listen on a TCP socket.\nport .*\n># If port 0 is specified
      Redis will not listen on a TCP socket.\nport ${app_redis_listen_port}\n>" ${file}
      &&     perl -0p -i -e "s># Close the connection after a client is idle for N
      seconds \(0 to disable\)\ntimeout .*\n># Close the connection after a client
      is idle for N seconds \(0 to disable\)\ntimeout ${app_redis_listen_timeout}\n>"
      ${file} &&     perl -0p -i -e "s># A reasonable value for this option is 300
      seconds, which is the new\n# Redis default starting with Redis 3.2.1.\ntcp-keepalive
      .*\n># A reasonable value for this option is 300 seconds, which is the new\n#
      Redis default starting with Redis 3.2.1.\ntcp-keepalive ${app_redis_listen_keepalive}\n>"
      ${file} &&     perl -0p -i -e "s># in order to get the desired effect.\ntcp-backlog
      .*\n># in order to get the desired effect.\ntcp-backlog ${app_redis_limit_backlog}\n>"
      ${file} &&     perl -0p -i -e "s># an error 'max number of clients reached'.\n#\n#
      maxclients 10000\n># an error 'max number of clients reached'.\n#\n# maxclients
      10000\nmaxclients ${app_redis_limit_concurent}\n>" ${file} &&     perl -0p -i
      -e "s># output buffers \(but this is not needed if the policy is \'noeviction\'\).\n#\n#
      maxmemory <bytes\>># output buffers \(but this is not needed if the policy is
      \'noeviction\'\).\n#\n# maxmemory <bytes\>\nmaxmemory ${app_redis_limit_memory}>"
      ${file} &&     printf "Done patching ${file}...\n" &&         printf "\n# Testing
      configuration...\n" &&     echo "Testing $(which redis-cli):"; $(which redis-cli)
      -v &&     echo "Testing $(which redis-server):"; $(which redis-server) -v &&     printf
      "Done testing configuration...\n" &&         printf "Finished updading Redis
      configuration...\n";
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/supervisord
    - -c
    - /etc/supervisord.conf
    - --nodaemon
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - ${app_redis_listen_port}
  From:
    Image: stafli/stafli.init.supervisor:supervisor31_centos7
  Name: ""
  Platform: ""
  SourceCode: FROM stafli/stafli.init.supervisor:supervisor31_centos7
