MetaArgs: null
Stages:
- BaseName: php:7.2.22-apache
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --no-install-recommends apt-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y graphviz libfreetype6-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libc-client-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libicu-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libfreetype6-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libjpeg62-turbo-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libkrb5-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libmcrypt-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libpng-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libtidy-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libxml2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libxpm-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libxslt-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y ca-certificates
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y msmtp
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libpspell-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install timezonedb
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug-2.6.0
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) bcmath
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) calendar
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) exif
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      --with-xpm-dir=/usr/include/
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) gd
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) gettext
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-configure imap --with-kerberos --with-imap-ssl
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) imap
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) intl
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) mysqli
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) pdo_mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) pspell
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) soap
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) sockets
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) tidy
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) wddx
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) xmlrpc
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) xsl
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) zip
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite ssl
    Name: run
    PrependShell: true
  From:
    Image: php:7.2.22-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2.22-apache
