MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Sinan Goo
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git socat jq curl openssl parallel
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --branch 1.1.2 https://github.com/nasoym/bss.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /bss
  - Env:
    - Key: PATH
      Value: /bss/handlers:$PATH
    Name: env
  - CmdLine:
    - apt-get install -y stress-ng
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - handlers/*
    - /bss/handlers
  - Env:
    - Key: SOCAT_TIMEOUT
      Value: "600"
    Name: env
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - ./run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
