MetaArgs: null
Stages:
- BaseName: pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Siddharth Yadav <sedflix@gmail.com>"'
    Name: label
  - CmdLine:
    - apt-get update && conda install -y jupyter scipy matplotlib scikit-learn faiss-gpu
      -c pytorch && conda clean --packages --yes
    Name: run
    PrependShell: true
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  From:
    Image: pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
  Name: ""
  Platform: ""
  SourceCode: FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
