MetaArgs: null
Stages:
- BaseName: maven:3-jdk-8-onbuild-alpine
  Commands:
  - Name: expose
    Ports:
    - "4567"
  - CmdLine:
    - cp ./target/athenaproxy-*-jar-with-dependencies.jar ./athena.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - java -jar athena.jar
    Name: cmd
    PrependShell: true
  From:
    Image: maven:3-jdk-8-onbuild-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM maven:3-jdk-8-onbuild-alpine
