MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - CmdLine:
    - npm install -g mustache
    Name: run
    PrependShell: true
  - CmdLine:
    - mustache
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
