MetaArgs: null
Stages:
- BaseName: postgres:9.5-alpine
  Commands:
  - Env:
    - Key: POSTGRES_USER
      Value: postgres
    Name: env
  - Env:
    - Key: POSTGRES_DB
      Value: fudge
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - init.sql.gz
    - /docker-entrypoint-initdb.d/
  From:
    Image: postgres:9.5-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.5-alpine
