MetaArgs:
- DefaultValue: "3.9"
  Key: VERSION
  ProvidedValue: null
  Value: "3.9"
Stages:
- BaseName: alpine:${VERSION}
  Commands:
  - Labels:
    - Key: Maintainer
      Value: '"Balluff SHW"'
    Name: label
  - Labels:
    - Key: Version
      Value: '"3.9"'
    Name: label
  - Labels:
    - Key: Vendor
      Value: '"Balluff"'
    Name: label
  - Labels:
    - Key: Name
      Value: '"SSH server in a container"'
    Name: label
  - Labels:
    - Key: Architecture
      Value: '"x86_64"'
    Name: label
  - CmdLine:
    - apk update && apk upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add openssh         && rm -rf /var/cache/apk/* /tmp/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/ssh/sshd_config
    - /etc/ssh/sshd_config
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - chmod +x /usr/local/bin/entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:${VERSION}
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:${VERSION}
