MetaArgs: null
Stages:
- BaseName: bgruening/galaxy-stable:latest
  Commands:
  - Maintainer: Galaxy Training Material
    Name: maintainer
  - Env:
    - Key: GALAXY_CONFIG_BRAND
      Value: '"GTN: Epigenetics"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - topics/epigenetics/tutorials/
    - /tutorials/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/docker-install-tutorials.sh
    - /setup-tutorials.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/mergeyaml.py
    - /mergeyaml.py
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bin/datalibrarydownload.sh
    - /datalibrarydownload.sh
  - CmdLine:
    - /setup-tutorials.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /datalibrarydownload.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: bgruening/galaxy-stable:latest
  Name: ""
  Platform: ""
  SourceCode: FROM bgruening/galaxy-stable:latest
