MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: newtork / Alexander Dümont <alexander_duemont@web.de>
    Name: maintainer
  - Name: expose
    Ports:
    - 1024-1152
    - "135"
    - "137"
    - "138"
    - "139"
    - "3268"
    - "3269"
    - "389"
    - "445"
    - "464"
    - "53"
    - "636"
    - "88"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - krb5.conf
    - /etc/
  - CmdLine:
    - "echo \"Updating repositories...\" && \tapt-get -qqy update && \techo \"Downloading
      Dependencies...\" && \techo \"(This may take a minute or two.)\" && \tapt-get
      -qqy install attr libattr1 libattr1-dev samba winbind bind9 krb5-admin-server
      krb5-kdc smbclient > /dev/null 2>&1 && \techo \"Download Complete.\""
    Name: run
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
