MetaArgs: null
Stages:
- BaseName: hivesolutions/ubuntu_dev:rolling
  Commands:
  - Labels:
    - Key: version
      Value: '"1.0"'
    Name: label
  - Labels:
    - Key: maintainer
      Value: '"Hive Solutions <development@hive.pt>"'
    Name: label
  - Name: expose
    Ports:
    - "8080"
  - Env:
    - Key: LEVEL
      Value: INFO
    Name: env
  - Env:
    - Key: HOST
      Value: 0.0.0.0
    Name: env
  - Env:
    - Key: PORT
      Value: "8080"
    Name: env
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app.js
    - /app/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /app/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - lib
    - /app/lib
  - Name: workdir
    Path: /app
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_11.x | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y bzip2 fontconfig libpangocairo-1.0-0 nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y gconf-service libasound2 libatk1.0-0 libc6    libcairo2 libcups2
      libdbus-1-3 libexpat1 libfontconfig1 libgcc1    libgconf-2-4 libgdk-pixbuf2.0-0
      libglib2.0-0 libgtk-3-0 libnspr4    libpango-1.0-0 libpangocairo-1.0-0 libstdc++6
      libx11-6 libx11-xcb1    libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6
      libxfixes3    libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates    fonts-liberation
      fonts-emojione libappindicator1 libnss3 lsb-release    xdg-utils wget
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/node
    - /app/app.js
    Name: cmd
    PrependShell: false
  From:
    Image: hivesolutions/ubuntu_dev:rolling
  Name: ""
  Platform: ""
  SourceCode: FROM hivesolutions/ubuntu_dev:rolling
