MetaArgs: null
Stages:
- BaseName: illagrenan/alpine-curl:latest
  Commands:
  - Labels:
    - Key: authors
      Value: '"Vašek Dohnal <vaclav.dohnal@gmail.com>"'
    Name: label
  - Key: KUBERNETES_VERSION
    Name: arg
    Value: v1.16.2
  - CmdLine:
    - mkdir -p /downloads
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
      -o /usr/local/bin/kubectl
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/kubectl
    Name: run
    PrependShell: true
  - CmdLine:
    - kubectl version --client
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - kubectl_config.sh
    - /kubectl_config.sh
  - CmdLine:
    - chmod +x /kubectl_config.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /kubectl_config.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: illagrenan/alpine-curl:latest
  Name: ""
  Platform: ""
  SourceCode: FROM illagrenan/alpine-curl:latest
