MetaArgs: null
Stages:
- BaseName: iojs/iojs
  Commands:
  - Maintainer: ColCh
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /srv
  - CmdLine:
    - apt-get update && apt-get install -qq --yes curl wget git imagemagick
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install --global grunt-cli forever bower yo webpack webpack-dev-server nodemon
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /srv
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: true
  From:
    Image: iojs/iojs
  Name: ""
  Platform: ""
  SourceCode: FROM iojs/iojs
