MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Labels:
    - Key: Lawrence
      Value: Stubbs <technoexpressnet@gmail.com>
    Name: label
  - CmdLine:
    - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm     &&
      yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y     &&
      yum-config-manager --enable remi-php72     && yum install wget dialog git iproute
      net-tools newt bind-utils nmap-ncat which     bc dnsmasq lighttpd lighttpd-fastcgi
      unzip cronie sudo php72 -y     && yum update -y
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - systemctl.py
    - /usr/bin/systemctl.py
  - CmdLine:
    - cp -f /usr/bin/systemctl /usr/bin/systemctl.original     && chmod +x /usr/bin/systemctl.py     &&
      cp -f /usr/bin/systemctl.py /usr/bin/systemctl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc
    - /etc/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - var
    - /var/
  - CmdLine:
    - export USER=pihole && adduser pihole -m -s /usr/sbin/nologin && touch /etc/pihole/adlists.list     &&
      wget -qO basic-install.sh https://install.pi-hole.net
    Name: run
    PrependShell: true
  - Env:
    - Key: TERM
      Value: vt220
    Name: env
  - CmdLine:
    - chmod +x basic-install.sh && ./basic-install.sh --unattended
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -f basic-install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - "yum -y install perl perl-Net-SSLeay openssl perl-IO-Tty perl-Encode-Detect
      \t&& yum -y install https://prdownloads.sourceforge.net/webadmin/webmin-1.890-1.noarch.rpm"
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install yum-versionlock -y && yum versionlock systemd     && yum remove
      nmap-ncat -y     && rpm -i https://nmap.org/dist/ncat-7.60-1.x86_64.rpm     &&
      ln -s /usr/bin/ncat /usr/bin/nc
    Name: run
    PrependShell: true
  - CmdLine:
    - systemctl stop firewalld     && systemctl.original disable dbus firewalld     &&
      (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i ==     systemd-tmpfiles-setup.service
      ] || rm -f $i; done);     rm -f /lib/systemd/system/multi-user.target.wants/*;     rm
      -f /lib/systemd/system/local-fs.target.wants/*;     rm -f /lib/systemd/system/sockets.target.wants/*udev*;     rm
      -f /lib/systemd/system/sockets.target.wants/*initctl*;     rm -f /lib/systemd/system/basic.target.wants/*;     rm
      -f /lib/systemd/system/anaconda.target.wants/*;     rm -f /etc/dbus-1/system.d/*;     rm
      -f /etc/systemd/system/sockets.target.wants/*;
    Name: run
    PrependShell: true
  - CmdLine:
    - "sed -i 's#10000#9000#' /etc/webmin/miniserv.conf \t&& sed -i \"s#':53 '#:\\$DNSPORT
      #\" /etc/.pihole/pihole \t&& sed -i \"s#':53 '#:\\$DNSPORT #\" /usr/local/bin/pihole
      \t&& sed -i \"s#--dport 53#--dport \\$DNSPORT#g\" /etc/.pihole/automated\\ install/basic-install.sh
      \    && sed -i \"s@\"\\${PI_HOLE_GIT_URL}\\\"@\" \\${PI_HOLE_GIT_URL} \\\"\\nsed
      -i \\\"s#':53 '#:\\\\\\\\\\$DNSPORT #\\\" \\${PI_HOLE_FILES_DIR}/pihole\\nsed
      -i \\\"s#--dport 53#--dport \\\\\\\\\\$DNSPORT#g\\\" \\${PI_HOLE_FILES_DIR}/automated\\\\\\
      install/basic-install.sh@g\" /etc/.pihole/advanced/Scripts/update.sh     &&
      sed -i \"s@\"\\${PI_HOLE_GIT_URL}\\\"@\" \\${PI_HOLE_GIT_URL} \\\"\\nsed -i
      \\\"s#':53 '#:\\\\\\\\\\$DNSPORT #\\\" \\${PI_HOLE_FILES_DIR}/pihole\\nsed -i
      \\\"s#--dport 53#--dport \\\\\\\\\\$DNSPORT#g\\\" \\${PI_HOLE_FILES_DIR}/automated\\\\\\
      install/basic-install.sh@g\" /opt/pihole/update.sh     && systemctl.original
      enable dnsmasq.service lighttpd.service crond.service webmin.service containerstartup.service
      \    && chmod +x /etc/containerstartup.sh     && mv -f /etc/containerstartup.sh
      /containerstartup.sh     && echo \"root:pi-hole\" | chpasswd"
    Name: run
    PrependShell: true
  - Env:
    - Key: IPV4
      Value: 0.0.0.0
    Name: env
  - Env:
    - Key: IPV6
      Value: ::0
    Name: env
  - Env:
    - Key: DNS1
      Value: 8.8.8.8
    Name: env
  - Env:
    - Key: DNS2
      Value: 8.8.4.4
    Name: env
  - Env:
    - Key: DNSPORT
      Value: "53"
    Name: env
  - Env:
    - Key: INTERFACE
      Value: eth0
    Name: env
  - Env:
    - Key: WEBMINPORT
      Value: "9000"
    Name: env
  - Name: expose
    Ports:
    - 4711-4720/tcp
    - 53/tcp
    - 53/udp
    - "80"
    - 9000/tcp
    - 9000/udp
  - CmdLine:
    - /usr/bin/systemctl
    - default
    - --init
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
