MetaArgs: null
Stages:
- BaseName: bryanrosander/pentaho-base-postgres
  Commands:
  - Name: volume
    Volumes:
    - /data-integration-server
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - diserver-start.sh
    - /root/diserver-start.sh
  - CmdLine:
    - /root/diserver-start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: bryanrosander/pentaho-base-postgres
  Name: ""
  Platform: ""
  SourceCode: from bryanrosander/pentaho-base-postgres
