MetaArgs: null
Stages:
- BaseName: jupyter/minimal-notebook
  Commands:
  - Maintainer: Christian Diener "<mail@cdiener.com>"
    Name: maintainer
  - Name: user
    User: jovyan
  - CmdLine:
    - conda install --quiet --yes     python=3.5     numpy     matplotlib     pandas     tabulate     statsmodels     seaborn     scipy     tabulate     lxml     &&
      pip install --pre python-libsbml cobra corda optlang swiglpk     && conda clean
      -tipsy
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - recon2.ipynb
    - /home/jovyan/work
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./solvers
    - /solvers
  - CmdLine:
    - if [ -d /solvers/ibm ]; then cd /solvers/ibm/cplex/python/3.5/x86-64_linux/
      &&     python3 setup.py install &&    cp /solvers/ibm/cplex/bin/x86-64_linux/cplex
      /usr/bin/; fi && rm -rf /solvers
    Name: run
    PrependShell: true
  - Name: user
    User: jovyan
  From:
    Image: jupyter/minimal-notebook
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/minimal-notebook
