MetaArgs: null
Stages:
- BaseName: ubuntu:15.10
  Commands:
  - Maintainer: Menny Even-Danan "menny@evendanan.net"
    Name: maintainer
  - Labels:
    - Key: version
      Value: '"1.5.3"'
    Name: label
  - Labels:
    - Key: description
      Value: '"A general use Android docker for CI"'
    Name: label
  - CmdLine:
    - mkdir -p /opt
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - tools
    - /opt/tools
  - CmdLine:
    - chmod +x /opt/tools/start_emulator.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: ANDROID_HOME
      Value: /opt/android-sdk-linux
    Name: env
  - Env:
    - Key: PATH
      Value: ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    Name: env
  - Env:
    - Key: JAVA_VERSION
      Value: "1.8"
    Name: env
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-oracle/
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y software-properties-common && add-apt-repository
      -y ppa:webupd8team/java
    Name: run
    PrependShell: true
  - CmdLine:
    - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true
      | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y oracle-java8-installer
    Name: run
    PrependShell: true
  - CmdLine:
    - "dpkg --add-architecture i386 && \tapt-get update && \tapt-get install -y --force-yes
      ca-certificates nano rsync sudo zip git build-essential wget libc6-i386 lib32stdc++6
      lib32gcc1 lib32ncurses5 lib32z1 python curl psmisc module-init-tools && \tapt-get
      clean"
    Name: run
    PrependShell: true
  - CmdLine:
    - "wget --output-document=android-sdk.tgz --quiet http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      && \ttar --no-same-owner -xzf android-sdk.tgz && \trm -f android-sdk.tgz"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | android update sdk --all --no-ui --filter platform-tools,build-tools-24.0.2,android-23,android-24,addon-google_apis-google-23,addon-google_apis-google-24,extra-android-m2repository,extra-google-m2repository,extra-google-google_play_services,extra-google-market_licensing,extra-google-play_billing,extra-google-market_apk_expansion,extra-google-gcm
    Name: run
    PrependShell: true
  - CmdLine:
    - which adb
    Name: run
    PrependShell: true
  - CmdLine:
    - which android
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/workspace
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/workspace
  From:
    Image: ubuntu:15.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:15.10
