MetaArgs: null
Stages:
- BaseName: andyfurnival/nginx:master
  Commands:
  - Maintainer: Andy Furnival
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gallery
    - /var/www/gallery
  - CmdLine:
    - chmod 755 /var/www/gallery
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 /var/www/gallery/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chown nginx:nginx /var/www/gallery
    Name: run
    PrependShell: true
  - CmdLine:
    - chown nginx:nginx /var/www/gallery/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./sites-enabled/nginx.static.conf
    - /etc/nginx/sites-enabled/nginx.static.conf
  - CmdLine:
    - /usr/local/sbin/nginx
    Name: cmd
    PrependShell: true
  From:
    Image: andyfurnival/nginx:master
  Name: ""
  Platform: ""
  SourceCode: FROM andyfurnival/nginx:master
