MetaArgs: null
Stages:
- BaseName: library/debian
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev
      libreadline-dev libsqlite3-dev libncurses5-dev  libncursesw5-dev xz-utils tk-dev
      libtimedate-perl libnet-ssleay-perl make wget unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz -P /tmp/python36-dist
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xzf /tmp/python36-dist/Python-3.6.0.tgz -C /usr/src
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/src/Python-3.6.0 && ./configure && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/sullo/nikto/archive/master.zip -P /tmp/nikto-dist
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/nikto-dist && unzip master.zip && mv nikto-master /opt/nikto
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "EXECDIR=/opt/nikto/program" >> /opt/nikto/program/nikto.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/nikto/program/nikto.conf /etc/nikto.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /opt/nikto/program/nikto.pl
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/nikto/program/nikto.pl /usr/local/bin/nikto
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/stanislav-web/OpenDoor/archive/master.zip -P /tmp/opendoor_dist
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/opendoor_dist && unzip master.zip && mv OpenDoor-master /opt/opendoor
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/opendoor && pip3.6 install -r requirements.txt && chmod +x opendoor.py
    Name: run
    PrependShell: true
  - CmdLine:
    - nikto -update
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - echo Hacklab is started && tail -f /var/log/wtmp
    Name: cmd
    PrependShell: true
  From:
    Image: library/debian
  Name: ""
  Platform: ""
  SourceCode: FROM library/debian
