MetaArgs: null
Stages:
- BaseName: datopian/auth:latest
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /ext/plans/
  - Name: user
    User: root
  - CmdLine:
    - pip3 install /ext/plans
    Name: run
    PrependShell: true
  - Env:
    - Key: ALLOWED_SERVICES
      Value: source:plans;rawstore:plans
    Name: env
  - Name: user
    User: $GUNICORN_USER
  From:
    Image: datopian/auth:latest
  Name: ""
  Platform: ""
  SourceCode: FROM datopian/auth:latest
