MetaArgs: null
Stages:
- BaseName: node:6
  Commands:
  - CmdLine:
    - apt update && apt install -y calibre-bin
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g gitbook-cli && gitbook fetch
    Name: run
    PrependShell: true
  From:
    Image: node:6
  Name: ""
  Platform: ""
  SourceCode: FROM node:6
