MetaArgs: null
Stages:
- BaseName: postgres:9.6.3
  Commands:
  - Env:
    - Key: POSTGRES_USER
      Value: rowboat
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - initdb.sh
    - /docker-entrypoint-initdb.d/
  From:
    Image: postgres:9.6.3
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.6.3
