MetaArgs: null
Stages:
- BaseName: openjdk:8
  Commands:
  - Maintainer: Cogniteev <tech@cogniteev.com>
    Name: maintainer
  - Env:
    - Key: HBASE_VERSION
      Value: 1.1.12
    Name: env
  - CmdLine:
    - groupadd -r hbase && useradd -m -r -g hbase hbase
    Name: run
    PrependShell: true
  - Name: user
    User: hbase
  - Env:
    - Key: HOME
      Value: /home/hbase
    Name: env
  - CmdLine:
    - cd /home/hbase &&     wget -O - -q     http://mirror.ox.ac.uk/sites/rsync.apache.org/hbase/${HBASE_VERSION}/hbase-${HBASE_VERSION}-bin.tar.gz     |
      tar --strip-components=1 -zxf -
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./conf/
    - /home/hbase/conf/
  - Name: user
    User: root
  - CmdLine:
    - chown -R hbase:hbase /home/hbase/conf
    Name: run
    PrependShell: true
  - Name: user
    User: hbase
  - CmdLine:
    - mkdir /home/hbase/data
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /home/hbase/logs
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /home/hbase/data
  - Name: volume
    Volumes:
    - /home/hbase/logs
  - Name: expose
    Ports:
    - "2181"
  - Name: expose
    Ports:
    - "60000"
  - Name: expose
    Ports:
    - "60010"
  - Name: expose
    Ports:
    - "60020"
  - Name: expose
    Ports:
    - "60030"
  - Name: workdir
    Path: /home/hbase
  - CmdLine:
    - /home/hbase/bin/hbase master start
    Name: cmd
    PrependShell: true
  From:
    Image: openjdk:8
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8
