MetaArgs: null
Stages:
- BaseName: vaibhavtodi/debian-java:latest
  Commands:
  - Maintainer: '"Vaibhav Todi" <vaibhavtodi1989@gmail.com>'
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Elasticsearch Docker image"'
    - Key: Version
      Value: '"2.2"'
    Name: label
  - Env:
    - Key: JAVA
      Value: /usr/lib/jvm/java-8-oracle
    Name: env
  - CmdLine:
    - apt-get        update                                                                          &&   apt-get        install
      -y wget                                                                 &&   wget    -qO
      -  https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -               &&   echo           "deb
      http://packages.elastic.co/elasticsearch/2.x/debian stable main" | tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list        &&   apt-get        update                                                                          &&   apt-get        install   -y   elasticsearch
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - elasticsearch.yml
    - /etc/elasticsearch/elasticsearch.yml
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /etc/elasticsearch/entrypoint.sh
  - CmdLine:
    - sed -i 's/es_cluster/graylog/'                     /etc/elasticsearch/elasticsearch.yml                           &&   sed
      -i 's/es_data_path/\/var\/lib\/elasticsearch/' /etc/elasticsearch/elasticsearch.yml                           &&   sed
      -i 's/es_log_path/\/var\/log\/elasticsearch/'  /etc/elasticsearch/elasticsearch.yml                           &&   sed
      -i 's/es_network_host/0\.0\.0\.0/'             /etc/elasticsearch/elasticsearch.yml                           &&   sed
      -i 's/es_http_port/9200/'                      /etc/elasticsearch/elasticsearch.yml                           &&   sed
      -i 's/es_unicast/["172\.17\.0\.1:9300"]/'      /etc/elasticsearch/elasticsearch.yml
    Name: run
    PrependShell: true
  - CmdLine:
    - for path in                                                                                             /var/lib/elasticsearch                                                                              /var/log/elasticsearch                                                                              /etc/elasticsearch                                                                                  /var/run/elasticsearch                                                                              /usr/share/elasticsearch                                                                        ;
      do                 chown -R elasticsearch:elasticsearch "$path";                                                   done
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get   -y    clean                                                                          &&   rm        -rf   /var/lib/apt/lists/*                                                           &&   rm        -rf   /var/cache/*
    Name: run
    PrependShell: true
  - CmdLine:
    - echo      "root:root"    |   chpasswd
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9200"
    - "9300"
  - Name: volume
    Volumes:
    - /var/lib/elasticsearch
    - /var/log/elasticsearch
    - /etc/elasticsearch
  - Name: user
    User: elasticsearch
  - CmdLine:
    - /etc/elasticsearch/entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: vaibhavtodi/debian-java:latest
  Name: ""
  Platform: ""
  SourceCode: FROM        vaibhavtodi/debian-java:latest
