MetaArgs: null
Stages:
- BaseName: circleci/android:api-23-alpha
  Commands:
  - Key: NODE_VERSION
    Name: arg
    Value: 10.6.0
  - CmdLine:
    - mkdir -p /tmp && cd /tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - "sudo curl -LO --compressed \"https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz\"
      && \tsudo tar -xJf \"node-v$NODE_VERSION-linux-x64.tar.xz\" -C /usr/local --strip-components=1
      --no-same-owner && \tsudo rm \"node-v$NODE_VERSION-linux-x64.tar.xz\" && \tsudo
      ln -s /usr/local/bin/node /usr/local/bin/nodejs"
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo npm install -g ionic cordova@8.0.0 && cordova telemetry off && CI=true
      ionic config set -g daemon.updates false && ionic config set -g telemetry false
    Name: run
    PrependShell: true
  - Key: GRADLE_VERSION
    Name: arg
    Value: 4.5.1
  - CmdLine:
    - sudo curl https://downloads.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
      > /tmp/gradle-$GRADLE_VERSION-bin.zip && sudo unzip /tmp/gradle-$GRADLE_VERSION-bin.zip
      -d /tmp && rm /tmp/gradle-$GRADLE_VERSION-bin.zip && sudo mv /tmp/gradle-$GRADLE_VERSION
      /opt/gradle
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo pip install google-api-python-client oauth2client
    Name: run
    PrependShell: true
  From:
    Image: circleci/android:api-23-alpha
  Name: ""
  Platform: ""
  SourceCode: FROM circleci/android:api-23-alpha
