MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: Aleksey @soar Smyrnov (//soar.name)
    Name: maintainer
  - Key: RUNDECK_PACKAGE_NAME
    Name: arg
    Value: rundeck_2.10.6-1-GA_all.deb
  - CmdLine:
    - apt-get update  && apt-get install -yq --no-install-recommends --no-install-suggests         curl         openjdk-8-jdk-headless         openjdk-8-jre-headless         openssh-client         uuid-runtime  &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - curl --silent -LO "http://dl.bintray.com/rundeck/rundeck-deb/${RUNDECK_PACKAGE_NAME}"  &&
      dpkg -i ${RUNDECK_PACKAGE_NAME}  && rm ${RUNDECK_PACKAGE_NAME}
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - unipatcher/unipatcher.sh && rm -rf unipatcher
    Name: run
    PrependShell: true
  - CmdLine:
    - ./run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
