MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Joshua Bradley <josh@joshuabradley-io>"'
    Name: label
  - Env:
    - Key: HUGO_VERSION
      Value: 0.40.1
    Name: env
  - Env:
    - Key: HUGO_BINARY
      Value: hugo_${HUGO_VERSION}_linux-64bit
    Name: env
  - CmdLine:
    - apk update && apk add py-pygments && apk add git && apk add bash && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz
    - /usr/local/
  - CmdLine:
    - "tar xzf /usr/local/${HUGO_BINARY}.tar.gz -C /usr/local/bin/ \t&& rm /usr/local/${HUGO_BINARY}.tar.gz"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1313"
  - CmdLine:
    - /usr/local/bin/hugo
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
