MetaArgs: null
Stages:
- BaseName: jupyter/pyspark-notebook
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"riyad.parvez@gmail.com"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - apt-get -y update &&     apt-get install --no-install-recommends -y ssh openssh-server
      openssh-client libblas-dev liblapack-dev gfortran &&     apt-get clean &&     rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: SPARK_OPTS
      Value: --driver-java-options=-Xms1024M --driver-java-options=-Xmx8192M --driver-java-options=-Dlog4j.logLevel=info
    Name: env
  - Name: user
    User: $NB_UID
  - CmdLine:
    - conda install --quiet -y nltk jupyterthemes nbdime ipdb
    Name: run
    PrependShell: true
  - CmdLine:
    - jt -t chesterish
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4040"
    - "8080"
  From:
    Image: jupyter/pyspark-notebook
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/pyspark-notebook
