MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - Key: BITLBEE_VERSION
    Name: arg
    Value: "3.6"
  - CmdLine:
    - "addgroup -g 101 -S bitlbee  && adduser -u 101 -D -S -G bitlbee bitlbee  &&
      apk add --no-cache --update  \ttzdata \tbash \tglib \tlibssl1.1 \tlibpurple
      \tlibpurple-xmpp \tlibpurple-oscar \tlibpurple-bonjour  && apk add --no-cache
      --update --virtual .build-dependencies \tbuild-base \tgit \tglib-dev \topenssl-dev
      \tpython2 \tpidgin-dev  && cd /tmp  && git clone -n https://github.com/bitlbee/bitlbee.git
      \ && cd bitlbee  && git checkout ${BITLBEE_VERSION}  && ./configure --build=x86_64-alpine-linux-musl
      --host=x86_64-alpine-linux-musl --purple=1 --ssl=openssl --prefix=/usr --etcdir=/etc/bitlbee
      \ && make  && make install  && make install-dev  && make install-etc  && strip
      /usr/sbin/bitlbee  && rm -rf /tmp/*  && apk del .build-dependencies"
    Name: run
    PrependShell: true
  - Key: FACEBOOK
    Name: arg
    Value: "1"
  - Key: FACEBOOK_VERSION
    Name: arg
    Value: v1.2.0
  - CmdLine:
    - "if [ ${FACEBOOK} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tjson-glib
      \ && apk add --no-cache --update --virtual .build-dependencies \tbuild-base
      \tgit \tautoconf \tautomake \tlibtool \tglib-dev \tjson-glib-dev  && git clone
      -n https://github.com/bitlbee/bitlbee-facebook.git  && cd bitlbee-facebook  &&
      git checkout ${FACEBOOK_VERSION}  && ./autogen.sh --build=x86_64-alpine-linux-musl
      --host=x86_64-alpine-linux-musl  && make  && make install  && strip /usr/lib/bitlbee/facebook.so
      \ && rm -rf /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: STEAM
    Name: arg
    Value: "1"
  - Key: STEAM_VERSION
    Name: arg
    Value: a6444d2
  - CmdLine:
    - "if [ ${STEAM} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tlibgcrypt
      \ && apk add --no-cache --update --virtual .build-dependencies \tbuild-base
      \tgit \tautoconf \tautomake \tlibtool \tlibgcrypt-dev \tglib-dev  && git clone
      -n https://github.com/bitlbee/bitlbee-steam.git  && cd bitlbee-steam  && git
      checkout ${STEAM_VERSION}  && ./autogen.sh --build=x86_64-alpine-linux-musl
      --host=x86_64-alpine-linux-musl  && make  && make install  && strip /usr/lib/bitlbee/steam.so
      \ && rm -rf /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: SKYPEWEB
    Name: arg
    Value: "1"
  - Key: SKYPEWEB_VERSION
    Name: arg
    Value: 5d29285
  - CmdLine:
    - "if [ ${SKYPEWEB} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tjson-glib
      \ && apk add --no-cache --update --virtual .build-dependencies \tbuild-base
      \tgit \tpidgin-dev \tjson-glib-dev  && git clone -n https://github.com/EionRobb/skype4pidgin.git
      \ && cd skype4pidgin  && git checkout ${SKYPEWEB_VERSION}  && cd skypeweb  &&
      make  && make install  && strip /usr/lib/purple-2/libskypeweb.so  && rm -rf
      /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: TELEGRAM
    Name: arg
    Value: "1"
  - Key: TELEGRAM_VERSION
    Name: arg
    Value: b101bbb
  - CmdLine:
    - "if [ ${TELEGRAM} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tlibgcrypt
      \tzlib \tlibwebp \tlibpng  && apk add --no-cache --update --virtual .build-dependencies
      \tbuild-base \tgit \tlibgcrypt-dev \tzlib-dev \tpidgin-dev \tlibwebp-dev \tlibpng-dev
      \ && git clone -n https://github.com/majn/telegram-purple  && cd telegram-purple
      \ && git checkout ${TELEGRAM_VERSION}  && git submodule update --init --recursive
      \ && ./configure --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl
      \ && make  && make install  && strip /usr/lib/purple-2/telegram-purple.so  &&
      rm -rf /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: HANGOUTS
    Name: arg
    Value: "1"
  - Key: HANGOUTS_VERSION
    Name: arg
    Value: 3f7d89b
  - CmdLine:
    - "if [ ${HANGOUTS} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tprotobuf-c
      \tjson-glib  && apk add --no-cache --update --virtual .build-dependencies \tbuild-base
      \tmercurial \tpidgin-dev \tprotobuf-c-dev \tjson-glib-dev  && hg clone https://bitbucket.org/EionRobb/purple-hangouts
      -r ${HANGOUTS_VERSION}  && cd purple-hangouts  && make  && make install  &&
      strip /usr/lib/purple-2/libhangouts.so  && rm -rf /tmp/*  && apk del .build-dependencies;
      fi"
    Name: run
    PrependShell: true
  - Key: SLACK
    Name: arg
    Value: "1"
  - Key: SLACK_VERSION
    Name: arg
    Value: 8acc4eb
  - CmdLine:
    - "if [ ${SLACK} -eq 1 ]; then cd /tmp  && apk add --no-cache --update --virtual
      .build-dependencies \tbuild-base \tgit \tpidgin-dev \tglib-dev  && git clone
      -n https://github.com/dylex/slack-libpurple.git  && cd slack-libpurple  && git
      checkout ${SLACK_VERSION}  && make  && make install  && strip /usr/lib/purple-2/libslack.so
      \ && rm -rf /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: SIPE
    Name: arg
    Value: "1"
  - Key: SIPE_VERSION
    Name: arg
    Value: upstream/1.23.3
  - CmdLine:
    - "if [ ${SIPE} -eq 1 ]; then cd /tmp  && apk add --no-cache --update --virtual
      .build-dependencies \tbuild-base \tgit \tlibtool \tglib-dev \tintltool \tautomake
      \tautoconf \topenssl-dev \tlibxml2-dev \tpidgin-dev  && git clone -n https://github.com/tieto/sipe.git
      \ && cd sipe  && git checkout ${SIPE_VERSION}  && ./autogen.sh  && ./configure
      --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --prefix=/usr
      \ && make  && make install  && strip /usr/lib/purple-2/libsipe.so  && rm -rf
      /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: DISCORD
    Name: arg
    Value: "1"
  - Key: DISCORD_VERSION
    Name: arg
    Value: aa0bbf2
  - CmdLine:
    - "if [ ${DISCORD} -eq 1 ]; then cd /tmp  && apk add --no-cache --update --virtual
      .build-dependencies \tbuild-base \tgit \tautoconf \tautomake \tlibtool \tglib-dev
      \ && git clone -n https://github.com/sm00th/bitlbee-discord.git  && cd bitlbee-discord
      \ && git checkout ${DISCORD_VERSION}  && ./autogen.sh  && ./configure --build=x86_64-alpine-linux-musl
      --host=x86_64-alpine-linux-musl --prefix=/usr  && make  && make install  &&
      strip /usr/lib/bitlbee/discord.so  && rm -rf /tmp/*  && apk del .build-dependencies;
      fi"
    Name: run
    PrependShell: true
  - Key: ROCKETCHAT
    Name: arg
    Value: "1"
  - Key: ROCKETCHAT_VERSION
    Name: arg
    Value: 826990b
  - CmdLine:
    - "if [ ${ROCKETCHAT} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tdiscount
      \tjson-glib  && apk add --no-cache --update --virtual .build-dependencies \tbuild-base
      \tmercurial \tpidgin-dev \tjson-glib-dev \tdiscount-dev  && hg clone https://bitbucket.org/EionRobb/purple-rocketchat
      -r ${ROCKETCHAT_VERSION}  && cd purple-rocketchat  && make  && make install
      \ && strip /usr/lib/purple-2/librocketchat.so  && rm -rf /tmp/*  && apk del
      .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: MASTODON
    Name: arg
    Value: "1"
  - Key: MASTODON_VERSION
    Name: arg
    Value: 83dee0b
  - CmdLine:
    - "if [ ${MASTODON} -eq 1 ]; then cd /tmp  && apk add --no-cache --update --virtual
      .build-dependencies \tbuild-base \tgit \tautoconf \tautomake \tlibtool \tglib-dev
      \ && git clone -n https://github.com/kensanata/bitlbee-mastodon  && cd bitlbee-mastodon
      \ && git checkout ${MASTODON_VERSION}  && ./autogen.sh  && ./configure --build=x86_64-alpine-linux-musl
      --host=x86_64-alpine-linux-musl  && make  && make install  && strip /usr/lib/bitlbee/mastodon.so
      \ && rm -rf /tmp/*  && apk del .build-dependencies; fi"
    Name: run
    PrependShell: true
  - Key: MATRIX
    Name: arg
    Value: "1"
  - Key: OLM_VERSION
    Name: arg
    Value: 3.1.4
  - Key: MATRIX_VERSION
    Name: arg
    Value: 4494ba2
  - CmdLine:
    - "if [ ${MATRIX} -eq 1 ]; then cd /tmp  && apk add --no-cache --update \tsqlite
      \thttp-parser \tlibgcrypt \tjson-glib  && apk add --no-cache --update --virtual
      .build-dependencies \tbuild-base \tgit \tlibgcrypt-dev \tpidgin-dev \tjson-glib-dev
      \tglib-dev \tsqlite-dev \thttp-parser-dev  && git clone -n https://gitlab.matrix.org/matrix-org/olm.git
      \ && cd olm  && git checkout ${OLM_VERSION}  && make  && make install  && strip
      /usr/local/lib/libolm.so.${OLM_VERSION}  && cd /tmp  && git clone -n https://github.com/matrix-org/purple-matrix
      \ && cd purple-matrix  && git checkout ${MATRIX_VERSION}  && make  && make install
      \ && strip /usr/lib/purple-2/libmatrix.so  && rm -rf /tmp/*  && apk del .build-dependencies;
      fi"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "6667"
  - Name: user
    User: bitlbee
  - CmdLine:
    - /usr/sbin/bitlbee
    - -F
    - -n
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
