MetaArgs: null
Stages:
- BaseName: gcr.io/cloud-builders/gcloud
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/scripts
    - /builder/activate-gcloud-service-account/scripts
  - CmdLine:
    - /builder/activate-gcloud-service-account/scripts/activate.bash
    Name: entrypoint
    PrependShell: false
  From:
    Image: gcr.io/cloud-builders/gcloud
  Name: ""
  Platform: ""
  SourceCode: from gcr.io/cloud-builders/gcloud
