MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Hoang Nguyen <nbhoangit@gmail.com>
    Name: maintainer
  - CmdLine:
    - "apt-get update -y && \tapt-get install -y \tapache2 && \tapt-get clean && \trm
      -rf \\var\\lib\\lists\\*"
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/a2ensite default-ssl
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/sbin/a2enmod ssl
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  - CmdLine:
    - /usr/sbin/apache2ctl
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
