MetaArgs: null
Stages:
- BaseName: sihart/acli_auto_int:0.6
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cisco-aci/acli.py
    - /cisco-aci/
  - CmdLine:
    - python cisco-aci/acli.py
    Name: cmd
    PrependShell: true
  From:
    Image: sihart/acli_auto_int:0.6
  Name: ""
  Platform: ""
  SourceCode: FROM sihart/acli_auto_int:0.6
