MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Janez Troha <dz0ny@ubuntu.si>
    Name: maintainer
  - Env:
    - Key: INFLUXDB_VERSION
      Value: static-nightly
    Name: env
  - CmdLine:
    - apk add --update wget tar ca-certificates && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://s3.amazonaws.com/influxdb/influxdb-${INFLUXDB_VERSION}_linux_amd64.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - "mkdir -p /app /var/lib/influxdb/ &&     tar xfz influxdb-${INFLUXDB_VERSION}_linux_amd64.tar.gz
      -C /app && \trm influxdb-${INFLUXDB_VERSION}_linux_amd64.tar.gz"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8083"
  - Name: expose
    Ports:
    - "8086"
  - Name: volume
    Volumes:
    - /var/lib/influxdb
  - CmdLine:
    - /app/influxd
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - run
    - -config
    - /app/influxdb.conf
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
