MetaArgs: null
Stages:
- BaseName: jwilder/nginx-proxy
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends cron logrotate
    Name: run
    PrependShell: true
  - CmdLine:
    - '{     echo "include /etc/nginx/sites-enabled/*;" ; } > /etc/nginx/conf.d/10sites_alias.conf'
    Name: run
    PrependShell: true
  - CmdLine:
    - '{     echo "limit_req_zone \$binary_remote_addr zone=limit:10m rate=50r/s;"
      ; } > /etc/nginx/conf.d/00limit.conf'
    Name: run
    PrependShell: true
  - CmdLine:
    - '{     echo "gzip on;" ;     echo "gzip_proxied any;" ;     echo "gzip_types
      text/plain text/css application/json application/x-javascript application/javascript
      text/xml application/xml application/rss+xml text/javascript image/svg+xml application/vnd.ms-fontobject
      application/x-font-ttf font/opentype application/atom+xml text/html text/yaml
      text/tab-separated-values;" ; } > /etc/nginx/conf.d/05gzip.conf'
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i '4i \    text/yaml                                        yml;' /etc/nginx/mime.types
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/nginx/maps
    Name: run
    PrependShell: true
  - CmdLine:
    - touch /etc/nginx/maps/wp1.map
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sites/*
    - /etc/nginx/sites-enabled/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 10createWp1Redirects
    - /etc/cron.hourly/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /app/
  - CmdLine:
    - chmod a+x docker-entrypoint.sh
    Name: run
    PrependShell: true
  From:
    Image: jwilder/nginx-proxy
  Name: ""
  Platform: ""
  SourceCode: FROM jwilder/nginx-proxy
