MetaArgs: null
Stages:
- BaseName: progrium/busybox
  Commands:
  - Maintainer: Amajd Masad <amjad.masad@gmail.com>
    Name: maintainer
  - CmdLine:
    - opkg-install python3
    Name: run
    PrependShell: true
  From:
    Image: progrium/busybox
  Name: ""
  Platform: ""
  SourceCode: FROM progrium/busybox
