MetaArgs: null
Stages:
- BaseName: openjdk:8-jre-alpine
  Commands:
  - Env:
    - Key: S3NINJA_HOME
      Value: /opt/s3ninja
    Name: env
  - Env:
    - Key: S3NINJA_WORK
      Value: /var/lib/s3ninja
    Name: env
  - CmdLine:
    - apk --no-cache --update upgrade &&    apk --no-cache --update add bash openssl
      &&    mkdir -p "$S3NINJA_HOME" &&    cd "$S3NINJA_HOME" &&    wget https://oss.sonatype.org/content/groups/public/com/scireum/s3ninja/2.7/s3ninja-2.7-zip.zip
      &&    unzip s3ninja-2.7-zip.zip &&    rm s3ninja-2.7-zip.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser -h "/var/lib/s3ninja" -k /var/empty/ -s /bin/false -D s3ninja s3ninja
      &&    mv "$S3NINJA_HOME/data" "$S3NINJA_HOME/logs" "$S3NINJA_WORK" &&    chown
      -R s3ninja:s3ninja "$S3NINJA_WORK/data" "$S3NINJA_WORK/logs" &&    ln -s "$S3NINJA_WORK/data"
      "$S3NINJA_WORK/logs"           "$S3NINJA_HOME/"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - s3ninja.sh
    - /
  - Name: expose
    Ports:
    - "9444"
  - Name: user
    User: s3ninja
  - CmdLine:
    - /s3ninja.sh
    Name: cmd
    PrependShell: true
  From:
    Image: openjdk:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jre-alpine
