MetaArgs: null
Stages:
- BaseName: node:12-stretch
  Commands:
  - Key: CHROMIUM
    Name: arg
    Value: 70.0.3538.110-1~deb9u1
  - Key: FIREFOX
    Name: arg
    Value: 60.6.3esr-1~deb9u1
  - Env:
    - Key: YARN_VERSION
      Value: 1.19.1
    Name: env
  - CmdLine:
    - curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz"   &&
      tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/   && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn
      /usr/local/bin/yarn   && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg   &&
      rm yarn-v$YARN_VERSION.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends   chromium=${CHROMIUM}
      firefox-esr=${FIREFOX}   git tar gzip ca-certificates   bash curl make   &&
      rm -rf  /var/lib/apt/lists/* /tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
      Value: "true"
    - Key: CHROME_BIN
      Value: /usr/bin/chromium
    - Key: FIREFOX_BIN
      Value: /usr/bin/firefox
    Name: env
  From:
    Image: node:12-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM node:12-stretch
