MetaArgs: null
Stages:
- BaseName: jenkins/jenkins:lts-alpine
  Commands:
  - Maintainer: José Luis Salvador Rufo <salvador.joseluis@gmail.com>
    Name: maintainer
  - Name: user
    User: root
  - CmdLine:
    - addgroup --gid 233 docker && addgroup jenkins docker     && apk update     &&
      apk add         git-lfs         docker         findutils procps         npm         py2-virtualenv         mariadb-connector-c-dev
      postgresql-dev gcc python2-dev musl musl-dev libffi-dev         jpeg-dev zlib-dev
      freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev harfbuzz-dev fribidi-dev     &&
      echo "@edgecommunity http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories     &&
      echo "@edge http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories     &&
      apk add         chromium@edge nss@edge     && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  From:
    Image: jenkins/jenkins:lts-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins/jenkins:lts-alpine
