MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - CmdLine:
    - apt-get update && apt-get -y install     curl     bash RUN curl -sL https://deb.nodesource.com/setup
      | sudo bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install     nodejs     npm
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/nodejs /usr/bin/node
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g     yo     bower     grunt-cli     gulp     generator-gulp-angular     generator-gulp-angular-subtask
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser --disabled-password --gecos "" yeoman;     echo "yeoman ALL=(ALL) NOPASSWD:ALL"
      >> /etc/sudoers
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /home/yeoman
    Name: env
  - Name: user
    User: yeoman
  - Name: expose
    Ports:
    - "3000"
  - Name: workdir
    Path: /dev-env
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
