MetaArgs: null
Stages:
- BaseName: ros:kinetic-ros-core-xenial
  Commands:
  - Maintainer: Yiping Xie yipingx@kth.se
    Name: maintainer
  - CmdLine:
    - "apt-get update \t&& apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev
      libavformat-dev libswscale-dev build-essential python-dev python-numpy libtbb2
      libtbb-dev libjpeg-dev \tlibpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
      \tlibatlas-base-dev gfortran pylint \tpython2.7-dev unzip python-pip wget libcereal-dev
      libglfw3-dev libceres-dev libtinyxml2-dev \t&& pip install ipython==5.0     \t&&
      rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/opencv/opencv/archive/3.3.1.zip -O opencv-3.3.1.zip
      && unzip opencv-3.3.1.zip && wget https://github.com/opencv/opencv_contrib/archive/3.3.1.zip
      -O opencv_contrib-3.3.1.zip && unzip opencv_contrib-3.3.1.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p opencv-3.3.1/biuld
    Name: run
    PrependShell: true
  - Name: workdir
    Path: opencv-3.3.1/build
  - CmdLine:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.3.1/modules
      -DOPENCV_ENABLE_NONFREE=True .. && make -j4 && make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - git clone https://github.com/nilsbore/auvlib.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: auvlib
  - CmdLine:
    - git submodule update --init && mkdir -p build
    Name: run
    PrependShell: true
  - Name: workdir
    Path: build
  - CmdLine:
    - cmake -DCMAKE_INSTALL_PREFIX=../install .. || exit 0 && make -j4 && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export PYTHONPATH=$PYTHONPATH:/auvlib/install/lib" >> ~/.bashrc && /bin/bash
      -c "source ~/.bashrc" && rm /opencv-3.3.1.zip /opencv_contrib-3.3.1.zip && rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: ros:kinetic-ros-core-xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ros:kinetic-ros-core-xenial
