MetaArgs: null
Stages:
- BaseName: openjdk:jre-alpine
  Commands:
  - CmdLine:
    - apk add --update openssl &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - pem2keystore.sh
    - /
  - CmdLine:
    - /pem2keystore.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: openjdk:jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:jre-alpine
