MetaArgs: null
Stages:
- BaseName: semtech/mu-ruby-template:2.10.0-ruby2.5
  Commands:
  - Maintainer: Erika Pauwels <erika.pauwels@gmail.com>
    Name: maintainer
  From:
    Image: semtech/mu-ruby-template:2.10.0-ruby2.5
  Name: ""
  Platform: ""
  SourceCode: FROM semtech/mu-ruby-template:2.10.0-ruby2.5
