MetaArgs: null
Stages:
- BaseName: aomeri/fineract-base:latest
  Commands:
  - Maintainer: Antony Omeri, antonyomeri@gmail.com
    Name: maintainer
  - Name: workdir
    Path: /app
  - CmdLine:
    - /bin/bash
    - ./build.sh
    Name: cmd
    PrependShell: false
  From:
    Image: aomeri/fineract-base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM aomeri/fineract-base:latest
