MetaArgs: null
Stages:
- BaseName: lexmarkweb/docker-aem-base
  Commands:
  - Maintainer: mikemarr
    Name: maintainer
  - Expression: ADD cq-publish-4503.jar /aem/cq-publish-4503.jar
    Name: onbuild
  - Expression: ADD license.properties /aem/license.properties
    Name: onbuild
  - Expression: ADD https://raw.githubusercontent.com/LexmarkWeb/docker-aem-publisher/master/postInstallHook.sh
      /aem/postInstallHook.sh
    Name: onbuild
  - Expression: RUN chmod +x /aem/postInstallHook.sh
    Name: onbuild
  - Expression: ADD *.zip /aem/packages/
    Name: onbuild
  - Expression: WORKDIR /aem
    Name: onbuild
  - Expression: RUN java -XX:MaxPermSize=256m -Xmx1024M -jar cq-publish-4503.jar -unpack
      -r publish -p 4503
    Name: onbuild
  - Expression: RUN ["/aem/aemInstaller.sh","-i","cq-publish-4503.jar","-r","publish","-p","4503"]
    Name: onbuild
  - Expression: WORKDIR /aem/crx-quickstart/bin
    Name: onbuild
  - Expression: RUN cp quickstart quickstart.original
    Name: onbuild
  - Expression: RUN cat quickstart.original | sed "s|4502|4503|g" > quickstart
    Name: onbuild
  - Name: expose
    Ports:
    - "4503"
    - "8000"
  - CmdLine:
    - /aem/crx-quickstart/bin/quickstart
    Name: entrypoint
    PrependShell: false
  From:
    Image: lexmarkweb/docker-aem-base
  Name: ""
  Platform: ""
  SourceCode: FROM lexmarkweb/docker-aem-base
