MetaArgs: null
Stages:
- BaseName: php:7.3-apache
  Commands:
  - CmdLine:
    - mkdir /var/www/cache     && chown www-data:www-data /var/www/cache     && a2enmod
      rewrite
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - www/
    - /var/www/html
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config.docker.php
    - /var/www/config.php
  From:
    Image: php:7.3-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-apache
