MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Name: volume
    Volumes:
    - /site
  - Name: workdir
    Path: /site
  - Env:
    - Key: HUGO_VERSION
      Value: 0.20.2
    Name: env
  - CmdLine:
    - "apk add --no-cache curl && \tcurl -fSL https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      | \ttar -xz -C /tmp && \tmv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64
      /usr/local/bin/hugo && \trm /tmp/ -rf && \tapk del curl"
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
