MetaArgs: null
Stages:
- BaseName: xtremxpert/docker-alpine:latest
  Commands:
  - Env:
    - Key: DB_ROOT_PASS
      Value: '"toor"'
    - Key: DB_USER
      Value: '"admin"'
    - Key: DB_PASS
      Value: '"password"'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/start.sh
    - /
  - CmdLine:
    - "apk -U upgrade && \tapk --update add \t\tmariadb \t\tmariadb-client \t&& \tchmod
      u+x /*.sh && \trm -fr /var/lib/apk/* && \trm -fr /var/cache/apk/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - "sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/my.cnf && \techo \"skip-name-resolve\"
      | awk '{ print } $1 == \"[mysqld]\" && c == 0 { c = 1; system(\"cat\") }' /etc/mysql/my.cnf
      > /tmp/my.cnf && \tmv /tmp/my.cnf /etc/mysql/my.cnf"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/mysql
  - Name: expose
    Ports:
    - "3306"
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: xtremxpert/docker-alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM xtremxpert/docker-alpine:latest
