MetaArgs: null
Stages:
- BaseName: golang:1.10
  Commands:
  - CmdLine:
    - apt-get update -y &&     apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - go get -u github.com/cespare/reflex
    Name: run
    PrependShell: true
  From:
    Image: golang:1.10
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.10
