MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Julian Nonino <noninojulian@gmail.com>"'
    Name: label
  - CmdLine:
    - apt-get update -y &&     apt-get install -y tar curl net-tools iproute2 openjdk-8-jre-headless
      &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Env:
    - Key: KAFKA_VERSION
      Value: 2.2.0
    Name: env
  - Env:
    - Key: SCALA_VERSION
      Value: "2.12"
    Name: env
  - CmdLine:
    - curl -O http://apache.mirror.anlx.net/kafka/$KAFKA_VERSION/kafka_$SCALA_VERSION-$KAFKA_VERSION.tgz
      &&     tar -xvf kafka_$SCALA_VERSION-$KAFKA_VERSION.tgz &&     rm -rf kafka_$SCALA_VERSION-$KAFKA_VERSION.tgz
      &&     mv kafka_$SCALA_VERSION-$KAFKA_VERSION kafka &&     mv kafka /opt
    Name: run
    PrependShell: true
  - Env:
    - Key: KAFKA_HOME
      Value: /opt/kafka
    Name: env
  - Env:
    - Key: PATH
      Value: $KAFKA_HOME/bin:$KAFKA_HOME/lib:$PATH
    Name: env
  - Name: workdir
    Path: /opt/kafka
  - Name: expose
    Ports:
    - "9092"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /usr/local/bin
  - CmdLine:
    - /usr/local/bin/start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
