MetaArgs: null
Stages:
- BaseName: ubuntu:18.10
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Silent Applause"'
    Name: label
  - CmdLine:
    - apt-get update &&      apt-get install -y openssh-server vim curl wget dnsutils
      telnet &&     mkdir /var/run/sshd  &&     echo 'root:123456' |chpasswd  &&     sed
      -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config  &&     sed
      -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config  &&     mkdir /root/.ssh  &&     apt-get
      clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     echo "alias
      vi='vim'" >>/root/.bashrc
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /usr/sbin/sshd
    - -D
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.10
