MetaArgs: null
Stages:
- BaseName: ruby:2.3-alpine
  Commands:
  - CmdLine:
    - gem install kontena-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bundle/bin/kontena
    Name: entrypoint
    PrependShell: false
  From:
    Image: ruby:2.3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3-alpine
