MetaArgs: null
Stages:
- BaseName: debian:buster-slim
  Commands:
  - Env:
    - Key: SMTP_HOSTNAME
      Value: smtp.example.com
    Name: env
  - Env:
    - Key: SMTP_RELAY
      Value: relay.server.example.com
    Name: env
  - Env:
    - Key: SMTP_DOMAIN
      Value: example.com
    Name: env
  - Env:
    - Key: SMTP_ORIGIN
      Value: example.com
    Name: env
  - Env:
    - Key: SMTP_USER
      Value: smtpuser
    Name: env
  - Env:
    - Key: SMTP_PASSWORD
      Value: changeme
    Name: env
  - CmdLine:
    - apt-get update -y && apt-get dist-upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install postfix sasl2-bin rsyslog -y
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i "s/START=no/START=yes/" /etc/default/saslauthd
    Name: run
    PrependShell: true
  - CmdLine:
    - perl -p -i -e "s|(?<=MECHANISMS=).*|\"shadow\"|" /etc/default/saslauthd
    Name: run
    PrependShell: true
  - CmdLine:
    - perl -p -i -e "s|(?<=OPTIONS=).*|\"-c -m /var/spool/postfix/var/run/saslauthd\"|"
      /etc/default/saslauthd
    Name: run
    PrependShell: true
  - CmdLine:
    - 'printf "pwcheck_method: saslauthd\nmech_list: PLAIN LOGIN\n" > /etc/postfix/sasl/smtpd.conf'
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -f /etc/services /var/spool/postfix/etc/services
    Name: run
    PrependShell: true
  - CmdLine:
    - perl -p -i -e "s|(?<=inet_protocols = ).*|ipv4|" /etc/postfix/main.cf
    Name: run
    PrependShell: true
  - CmdLine:
    - printf "\nsmtpd_sasl_path = smtpd\n" >> /etc/postfix/main.cf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "smtpd_sasl_type = cyrus" >> /etc/postfix/main.cf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "smtpd_sasl_auth_enable = yes" >> /etc/postfix/main.cf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "smtpd_sasl_security_options = noanonymous" >> /etc/postfix/main.cf
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -aG sasl postfix
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /docker-entrypoint.sh
  - CmdLine:
    - chmod +x /docker-entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "25"
  - CmdLine:
    - /bin/bash
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /usr/bin/tail
    - -f
    - /var/log/mail.log
    Name: cmd
    PrependShell: false
  From:
    Image: debian:buster-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:buster-slim
