MetaArgs: null
Stages:
- BaseName: continuumio/anaconda:latest
  Commands:
  - Maintainer: Robert Haines <robert.haines@manchester.ac.uk>
    Name: maintainer
  - CmdLine:
    - apt-get update -q &&     DEBIAN_FRONTEND=noninteractive     apt-get install
      -qy     fontconfig     --no-install-recommends &&     apt-get clean &&     rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - data/project data
    - /opt/analysis/data/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts
    - /opt/analysis/scripts/
  - Name: workdir
    Path: /opt/analysis
  - CmdLine:
    - /bin/bash
    Name: entrypoint
    PrependShell: true
  From:
    Image: continuumio/anaconda:latest
  Name: ""
  Platform: ""
  SourceCode: FROM continuumio/anaconda:latest
