MetaArgs: null
Stages:
- BaseName: tomcat:8.5
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y nano vim procps htop dnsutils
    Name: run
    PrependShell: true
  - CmdLine:
    - cd webapps &&   rm -rf ROOT* &&   rm -rf docs &&   rm -rf examples &&   rm -rf
      manager &&   rm -rf host-manager
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/server.xml
    - /usr/local/tomcat/conf/
  From:
    Image: tomcat:8.5
  Name: ""
  Platform: ""
  SourceCode: FROM tomcat:8.5
