MetaArgs: null
Stages:
- BaseName: jenkins/ssh-slave
  Commands:
  - Maintainer: Lei Zhang <lei.zhang@clustar.ai>
    Name: maintainer
  - CmdLine:
    - apt update     && apt install  -y pkg-config zip g++ zlib1g-dev unzip python     python-dev
      python-pip     && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      /usr/share/doc/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/bazelbuild/bazel/releases/download/0.25.0/bazel-0.25.0-installer-linux-x86_64.sh     &&
      chmod +x bazel-0.25.0-installer-linux-x86_64.sh     && ./bazel-0.25.0-installer-linux-x86_64.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade tensorflow
    Name: run
    PrependShell: true
  From:
    Image: jenkins/ssh-slave
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins/ssh-slave
