MetaArgs: null
Stages:
- BaseName: python:3.6-stretch
  Commands:
  - CmdLine:
    - "set -ex \t&& apt-get update \t&& apt-get install -y --no-install-recommends
      \t\tpostgresql-client \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: PGADMIN4_VERSION
      Value: "4.10"
    Name: env
  - Env:
    - Key: PGADMIN4_DOWNLOAD_URL
      Value: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v${PGADMIN4_VERSION}/pip/pgadmin4-${PGADMIN4_VERSION}-py2.py3-none-any.whl
    Name: env
  - Labels:
    - Key: org.label-schema.name
      Value: '"pgAdmin4"'
    - Key: org.label-schema.version
      Value: '"$PGADMIN4_VERSION"'
    - Key: org.label-schema.license
      Value: '"PostgreSQL"'
    - Key: org.label-schema.url
      Value: '"https://www.pgadmin.org"'
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/elesdoar/dockercloud-pgAdmin4"'
    Name: label
  - CmdLine:
    - "set -ex \t&& buildDeps=\" \t\tgcc \t\tlibssl-dev \t\tmake\" \t&& apt-get update
      \t&& apt-get install -y $buildDeps --no-install-recommends \t&& rm -rf /var/lib/apt/lists/*
      \t&& pip --no-cache-dir install $PGADMIN4_DOWNLOAD_URL \t&& apt-get purge -y
      --auto-remove $buildDeps"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/pgadmin
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "5050"
  - CmdLine:
    - pgadmin4
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-stretch
