MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.15
  Commands:
  - Maintainer: Morgan Blackthorne <morgan@windsofstorm.net>
    Name: maintainer
  - Env:
    - Key: HOME
      Value: '"/root"'
    - Key: LC_ALL
      Value: '"C.UTF-8"'
    - Key: LANG
      Value: '"en_US.UTF-8"'
    - Key: LANGUAGE
      Value: '"en_US.UTF-8"'
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: '"noninteractive"'
    Name: env
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - CmdLine:
    - add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe
      multiverse"
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates
      universe multiverse"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -qq
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -qy mariadb-server php5-cli php5-mysqlnd php5-fpm nginx wget
      unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/service/nginx
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx-run
    - /etc/service/nginx/run
  - CmdLine:
    - rm -f /etc/nginx/sites-enabled/default
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /etc/service/php-fpm
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - php-fpm-run
    - /etc/service/php-fpm/run
  - Chown: ""
    Name: add
    SourcesAndDest:
    - www.conf
    - /etc/php5/fpm/pool.d/www.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - extplorer.site
    - /etc/nginx/sites-enabled/extplorer.site
  - CmdLine:
    - mkdir -p /var/www/eXtplorer/
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -qO /var/www/extplorer.zip "https://extplorer.net/attachments/download/82/eXtplorer_2.1.13.zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip /var/www/extplorer.zip -d  /var/www/eXtplorer/
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data:www-data /var/www/eXtplorer
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /var/www/extplorer.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /var/www/eXtplorer /var/www/wfm
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean -y
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* /var/cache/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod -R +x /etc/service/ /etc/my_init.d/
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: phusion/baseimage:0.9.15
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.9.15
