MetaArgs: null
Stages:
- BaseName: devopsil/base
  Commands:
  - CmdLine:
    - rpm --import https://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs &&     rpm -ivh
      http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install yum-utils -y &&     yum-config-manager --enable centosplus >& /dev/null
      &&     yum clean all
    Name: run
    PrependShell: true
  From:
    Image: devopsil/base
  Name: ""
  Platform: ""
  SourceCode: FROM devopsil/base
