MetaArgs: null
Stages:
- BaseName: python:3.7-slim
  Commands:
  - CmdLine:
    - pip install --no-cache-dir google-api-python-client oauth2client pyOpenSSL
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - upload_bundle_to_alpha.py
    - /upload_bundle_to_alpha.py
  - CmdLine:
    - python
    - upload_bundle_to_alpha.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-slim
