MetaArgs: null
Stages:
- BaseName: karmab/kcli
  Commands:
  - Maintainer: Karim Boumedhel <karimboumedhel@gmail.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /kopf
  - CmdLine:
    - pip3 install kopf
    Name: run
    PrependShell: true
  - CmdLine:
    - kopf
    - run
    - /kopf/handlers.py
    - --verbose
    Name: entrypoint
    PrependShell: false
  From:
    Image: karmab/kcli
  Name: ""
  Platform: ""
  SourceCode: FROM karmab/kcli
