MetaArgs: null
Stages:
- BaseName: node:8.2.1-alpine
  Commands:
  - Env:
    - Key: GTT_VERSION
      Value: 1.7.40
    Name: env
  - CmdLine:
    - yarn global add --prefix /usr/local "gitlab-time-tracker@$GTT_VERSION"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /root
  - CmdLine:
    - gtt
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: node:8.2.1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.2.1-alpine
