MetaArgs: null
Stages:
- BaseName: rocker/rstudio:latest
  Commands:
  - Maintainer: B2B.Web.ID Data Analytics Platform Labs
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - clouderaimpalaodbc_2.5.32.1002-2_amd64.deb
    - /root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - installpackages.R
    - /root
  - CmdLine:
    - apt-get update &&  apt-get install -y   unixodbc unixodbc-dev   git   libsasl2-modules-gssapi-mit
      &&  dpkg -i /root/clouderaimpalaodbc_2.5.32.1002-2_amd64.deb &&  rm /root/clouderaimpalaodbc_2.5.32.1002-2_amd64.deb
      &&  apt-get autoremove -y &&  apt-get clean &&  Rscript --verbose /root/installpackages.R
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8787"
  - Name: volume
    Volumes:
    - /home/rstudio
  - CmdLine:
    - /init
    Name: cmd
    PrependShell: false
  From:
    Image: rocker/rstudio:latest
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/rstudio:latest
