MetaArgs: null
Stages:
- BaseName: nginx:mainline
  Commands:
  - Labels:
    - Key: org.freenas.interactive
      Value: '"false"'
    - Key: org.freenas.version
      Value: '"2"'
    - Key: org.freenas.upgradeable
      Value: '"false"'
    - Key: org.freenas.expose-ports-at-host
      Value: '"true"'
    - Key: org.freenas.autostart
      Value: '"true"'
    - Key: org.freenas.port-mappings
      Value: '"80:8080/tcp,443:8081/tcp"'
    - Key: org.freenas.volumes
      Value: "\"[\t\t\t\t\t\t                            {\t\t\t\t\t\t\t\t                                      \\\"name\\\":
        \\\"/var/www/html\\\",\t\t\t\t\t                    \\\"descr\\\": \\\"html
        content\\\"\t\t                                        },                                                                            {\t\t\t\t\t\t\t\t
        \                                     \\\"name\\\": \\\"/etc/nginx/conf.d/custom.conf\\\",\t\t\t\t
        \             \\\"descr\\\": \\\"custom conf\\\"\t\t                                        },
        \                                                                           {\t\t\t\t\t\t\t\t
        \                                     \\\"name\\\": \\\"/etc/nginx/conf.d/default.conf\\\",\t\t\t\t
        \             \\\"descr\\\": \\\"default content if interested for port 80\\\"\t\t
        \         }                                                                             ]\""
    Name: label
  From:
    Image: nginx:mainline
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:mainline
