MetaArgs: null
Stages:
- BaseName: python:3.7-slim
  Commands:
  - CmdLine:
    - apt update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y python3-dev gcc
    Name: run
    PrependShell: true
  - CmdLine:
    - pip --no-cache-dir install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
    Name: run
    PrependShell: true
  - CmdLine:
    - pip --no-cache-dir install fastai
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - pip install --trusted-host pypi.python.org -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - python
    - app.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-slim
