MetaArgs: null
Stages:
- BaseName: node:8.1.2-alpine
  Commands:
  - Maintainer: cogso <https://github.com/cogso/alpine-nodejs-builder>
    Name: maintainer
  - CmdLine:
    - apk add --quiet --no-cache bash git &&     yarn global add gulp gulp-cli &&     rm
      -rf /var/cache/* /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  From:
    Image: node:8.1.2-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.1.2-alpine
