MetaArgs: null
Stages:
- BaseName: nacyot/ubuntu
  Commands:
  - Maintainer: Daekwon Kim <propellerheaven@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y unzip wget git
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg -i erlang-solutions_1.0_all.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y erlang
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /source
  From:
    Image: nacyot/ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM nacyot/ubuntu
