MetaArgs: null
Stages:
- BaseName: jenkins:2.3
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - chmod a+w $JAVA_HOME/jre/lib/security/cacerts
    Name: run
    PrependShell: true
  - Key: user
    Name: arg
    Value: jenkins
  - Env:
    - Key: JENKINS_OPTS
      Value: --httpsKeyStore=$JAVA_HOME/jre/lib/security/cacerts
    Name: env
  - Name: user
    User: ${user}
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - jenkins.sh
    - /usr/local/bin/jenkins.sh
  From:
    Image: jenkins:2.3
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins:2.3
