MetaArgs: null
Stages:
- BaseName: nginx:stable
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"info@optimum-web.com"'
    Name: label
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get install --no-install-recommends -y supervisor procps
      net-tools cron apache2-utils  && apt-get clean && rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord/nginx.conf
    - /etc/supervisord.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - security.conf
    - /etc/nginx/conf.d/security.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - auto-letsencrypt
    - /opt/letsencrypt/letsencrypt-auto
  - CmdLine:
    - chmod +x /opt/letsencrypt/letsencrypt-auto
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/supervisord
    - -c
    - /etc/supervisord.conf
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:stable
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:stable
