MetaArgs: null
Stages:
- BaseName: java
  Commands:
  - Maintainer: Cédric CLOVEL
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://downloads.jboss.org/keycloak/3.4.1.Final/keycloak-3.4.1.Final.tar.gz
    - /opt/jboss/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./docker-entrypoint.sh
    - /opt/jboss/
  - CmdLine:
    - cd /opt/jboss/ &&     tar xzvf keycloak-3.4.1.Final.tar.gz &&     rm -rf keycloak-3.4.1.Final.tar.gz
      &&     mv keycloak-3.4.1.Final keycloak
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /opt/jboss/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -b
    - 0.0.0.0
    Name: cmd
    PrependShell: false
  From:
    Image: java
  Name: ""
  Platform: ""
  SourceCode: FROM java
