MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Key: VERSION
    Name: arg
    Value: null
  - CmdLine:
    - apk add --update curl &&     apk add --virtual .build-deps         autoconf         automake         curl-dev         gcc         git         libtool         make         musl-dev         zlib-dev
      &&     git clone https://github.com/maxmind/geoipupdate.git /tmp/geoipupdate
      &&     cd /tmp/geoipupdate &&     git checkout ${VERSION} &&     ./bootstrap
      &&     ./configure &&     make &&     make install &&     cd - &&     apk del
      .build-deps &&     rm -rf /tmp/geoipupdate* &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src/exec.sh
    - /
  - CmdLine:
    - /exec.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
