MetaArgs: null
Stages:
- BaseName: python:2.7-alpine3.8
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /app/
  - CmdLine:
    - "apk add --no-cache --virtual .build-deps \t\t\t\t\t\t\t\t libxml2-dev \t\t\t\t\t\t\t\t
      build-base \t\t\t\t\t\t\t\t libxslt-dev && \tpip install -r /app/requirements.txt
      && \tapk del .build-deps"
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add --no-cache libxslt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - '*.py'
    - /app/
  - CmdLine:
    - /app/kdbxpasswordpwned.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:2.7-alpine3.8
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7-alpine3.8
