MetaArgs: null
Stages:
- BaseName: python:3.6-alpine
  Commands:
  - Env:
    - Key: SERVICES
      Value: apigateway,lambda,cloudformation,dynamodbstreams,firehose,s3,sns
    Name: env
  - CmdLine:
    - apk add --no-cache --virtual build-essentials       gcc       linux-headers
      &&     apk add --no-cache       musl-dev       libffi-dev       openssl-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install localstack
    Name: run
    PrependShell: true
  - CmdLine:
    - apk del --purge build-essentials
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 4567-4583
    - "8080"
  - Name: volume
    Volumes:
    - /tmp/localstack
  - CmdLine:
    - localstack
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-alpine
