MetaArgs: null
Stages:
- As: builder
  BaseName: golang
  Commands:
  - Name: workdir
    Path: /go/src/xhash
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - make
    Name: run
    PrependShell: true
  From:
    Image: golang
  Name: builder
  Platform: ""
  SourceCode: "FROM\tgolang as builder"
- BaseName: scratch
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/xhash/xhash
    - /usr/local/bin/xhash
  - CmdLine:
    - /usr/local/bin/xhash
    Name: entrypoint
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: "FROM\tscratch"
