MetaArgs: null
Stages:
- BaseName: postgres:9.5
  Commands:
  - Maintainer: paul@trippett.org
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - Name: expose
    Ports:
    - "5432"
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - postgres
    Name: cmd
    PrependShell: false
  From:
    Image: postgres:9.5
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.5
