MetaArgs: null
Stages:
- BaseName: php:5.4-fpm
  Commands:
  - Maintainer: tiagocyberduck@cyber-duck.co.uk
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get install -y --force-yes --no-install-recommends         libmemcached-dev         libz-dev         libpq-dev         libjpeg-dev         libpng12-dev         libfreetype6-dev         libssl-dev         libmcrypt-dev         openssh-server         git         cron         nano
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install mcrypt
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install zip
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install mysql mysqli
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo pdo_mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo_pgsql
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install gd &&     docker-php-ext-configure gd         --enable-gd-native-ttf         --with-jpeg-dir=/usr/lib         --with-freetype-dir=/usr/include/freetype2
      &&     docker-php-ext-install gd
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./express.ini
    - /usr/local/etc/php/conf.d
  - CmdLine:
    - usermod -u 1000 www-data
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php-fpm
    Name: cmd
    PrependShell: false
  From:
    Image: php:5.4-fpm
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.4-fpm
