MetaArgs: null
Stages:
- BaseName: nginx:latest
  Commands:
  - Maintainer: Dr.Doom doom@dev-ops.de
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*'
    - /usr/share/nginx/html/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - deps
    - /usr/share/nginx/html/deps
  - Name: volume
    Volumes:
    - /usr/share/nginx/html/
  From:
    Image: nginx:latest
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:latest
