MetaArgs: null
Stages:
- BaseName: python:2-alpine
  Commands:
  - CmdLine:
    - set -xe &&     apk add --no-cache unzip curl &&     cd /srv &&     curl -fsSLO
      --compressed "http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/assets/attach/32190/cn_zh/1523340041580/ossftp-1.0.3-linux-mac.zip"
      &&     unzip -o "ossftp-1.0.3-linux-mac.zip" -d /srv &&     rm -rf "ossftp-1.0.3-linux-mac.zip"
      &&     mv ossftp-1.0.3-linux-mac ossftp &&     apk del unzip curl
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "2048"
    - "8192"
  - Name: workdir
    Path: /srv/ossftp
  - CmdLine:
    - python
    - launcher/start.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:2-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:2-alpine
