MetaArgs: null
Stages:
- BaseName: node:4
  Commands:
  - Maintainer: Eva Ramon <eva.ramon@swisscom.com>
    Name: maintainer
  - CmdLine:
    - mkdir -p /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - oauth.js
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - dsrequest.js
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - signrequest.js
    - /app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - server.js
    - /app/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8081"
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:4
  Name: ""
  Platform: ""
  SourceCode: FROM node:4
