MetaArgs: null
Stages:
- BaseName: node:6
  Commands:
  - CmdLine:
    - mkdir -p /usr/src/app/src
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /usr/src/app/
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - index.js
    - /usr/src/app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./src
    - /usr/src/app/src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker-entrypoint.sh
    - /docker-entrypoint.sh
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y netcat
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:6
  Name: ""
  Platform: ""
  SourceCode: FROM node:6
