MetaArgs: null
Stages:
- BaseName: python:3.6.6
  Commands:
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /usr/src/app/
  - CmdLine:
    - pip install --no-cache-dir -r requirements.txt --src /usr/local/src
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y gettext && apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/app
  - CmdLine:
    - /usr/src/app/docker/cmd-webserver.sh
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "8000"
  From:
    Image: python:3.6.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6.6
