MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Florian Pereme <florian.pereme@altran.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y net-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y screen
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-server
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openssh-client
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y passwd
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libglib2.0-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - sudo apt-get install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6
      multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y --allow-unauthenticated mongodb-org mongodb-org-server
      mongodb-org-shell mongodb-org-mongos mongodb-org-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y --force-yes mongodb-org=3.6.1 mongodb-org-server=3.6.1 mongodb-org-shell=3.6.1
      mongodb-org-mongos=3.6.1 mongodb-org-tools=3.6.1
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /data/db
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R mongodb:mongodb /data
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /labelling
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /labelling
  - CmdLine:
    - mkdir -p /var/run/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'root:medica' | chpasswd
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
    - "27017"
    - "80"
    - "8080"
    - "8082"
  - CmdLine:
    - mongod
    Name: cmd
    PrependShell: true
  - CmdLine:
    - /usr/sbin/sshd -D
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
