MetaArgs: null
Stages:
- BaseName: python:3.7.3-alpine3.9
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Sultan Gillani (sultangillani)"'
    Name: label
  - Name: workdir
    Path: /playbooks
  - CmdLine:
    - apk add --no-cache     linux-headers     build-base     libffi-dev     openssl-dev     git     openssh     &&
      pip install --upgrade pip setuptools wheel ansible-lint     && rm -rf /var/cache/apk/*     &&
      rm -rf /root/.cache
    Name: run
    PrependShell: true
  - CmdLine:
    - ansible-lint
    - --version
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.7.3-alpine3.9
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7.3-alpine3.9
