MetaArgs: null
Stages:
- BaseName: node:alpine
  Commands:
  - CmdLine:
    - apk add --update make gcc g++ python curl git krb5-dev zeromq-dev
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - npm install zeromq --zmq-external --save
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - Labels:
    - Key: databox.type
      Value: '"driver"'
    Name: label
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:alpine
