MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"José Luis Salvador Rufo <salvador.joseluis@gmail.com>"'
    Name: label
  - CmdLine:
    - touch /etc/ssl/index.txt /etc/ssl/index.txt.attr &&     echo 01 > /etc/ssl/serial
      &&     apk add --no-cache openssl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./openssl.cnf
    - /etc/ssl/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./generate-ssl
    - /usr/local/bin/
  - CmdLine:
    - /usr/local/bin/generate-ssl
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
