MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - CmdLine:
    - yum update -y && yum install -y epel-release nano && yum install -y zip
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://setup.ius.io/ | bash
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/google-chrome.repo
    - /etc/yum.repos.d/google-chrome.repo
  - CmdLine:
    - yum install -y google-chrome-stable
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:tools/
    Name: env
  - Env:
    - Key: NPM_CONFIG_PREFIX
      Value: tools/
    Name: env
  - Env:
    - Key: NODE_PATH
      Value: tools/node_modules
    Name: env
  - CmdLine:
    - mkdir tools
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tools
  - CmdLine:
    - yum install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install npm
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install gulp
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install puppeteer
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install node-sass
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - yum install -y java-1.8.0-openjdk-devel
    Name: run
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
