MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - CmdLine:
    - mkdir /opt/rock
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r rocker && useradd -m -r -g rocker rocker
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R rocker:rocker /opt/rock
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "rocker:rocker" | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser rocker sudo
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/rock
  - CmdLine:
    - apt-get -y update && apt-get install -y ruby2.0 wget expect sudo
    Name: run
    PrependShell: true
  - Name: user
    User: rocker
  - CmdLine:
    - wget https://raw.githubusercontent.com/rock-core/buildconf/master/bootstrap.sh
      && chmod +x /opt/rock/bootstrap.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - expect_bootstrap.exp
    - /opt/rock/
  - CmdLine:
    - expect ./expect_bootstrap.exp
    Name: run
    PrependShell: true
  - CmdLine:
    - echo `pwd`
    Name: run
    PrependShell: true
  - CmdLine:
    - . /opt/rock/env.sh && gem2.0 install autoproj
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - expect_autoproj_bootstrap.exp
    - /opt/rock/
  - CmdLine:
    - expect ./expect_autoproj_bootstrap.exp
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
