MetaArgs: null
Stages:
- BaseName: python:3.4
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - CmdLine:
    - apt-get update -qq && apt-get install -y postgresql-client libpq-dev git-core
      libmemcached-dev ruby-sass ruby-compass libxml2-dev libxslt1-dev libjpeg-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /code
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /code/
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code/
  From:
    Image: python:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.4
