MetaArgs: null
Stages:
- BaseName: python:2.7-slim
  Commands:
  - Maintainer: '"Toshiki Inami <t-inami@arukas.io>"'
    Name: maintainer
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - python /app/server.py
    Name: cmd
    PrependShell: true
  From:
    Image: python:2.7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7-slim
