MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /node-hello-world
  - Env:
    - Key: PORT
      Value: "80"
    Name: env
  - Name: expose
    Ports:
    - "80"
  - Name: workdir
    Path: /node-hello-world
  - CmdLine:
    - node server.js
    Name: cmd
    PrependShell: true
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
