MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Maintainer: goofts loking.zhao.moshang@icloud.com
    Name: maintainer
  - Env:
    - Key: HUMMINGBIRDS_VERSION
      Value: 13.21.34
    Name: env
  - Name: workdir
    Path: /root
  - CmdLine:
    - apk update && apk upgrade && apk add --no-cache git python3-dev    &&     git
      clone https://github.com/goofts/hummingbirds.git /hummingbirds &&     chmod
      +x /hummingbirds/setup.sh && sh /hummingbirds/setup.sh       &&     cp /usr/share/zoneinfo/Asia/Shanghai
      /etc/localtime                &&     rm /usr/bin/vi && ln -snf /usr/bin/vim
      /usr/bin/vi                 &&     rm /bin/sh     && ln -snf /bin/bash    /bin/sh                     &&     find
      /usr/lib/python* -name __pycache__ | xargs rm -rf             &&     rm -rf
      ~/* ~/.[0-9a-zA-Z]* /tmp/* /var/tmp/* /var/cache/apk/*      &&     rm -rf /usr/local/share/.[0-9a-zA-Z]*
      /usr/local/share/*           &&     rm -rf /usr/share/jupyter/lab/staging/build/*
      /usr/share/jupyter/kernels/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir ~/.pip && cp /hummingbirds/pip.conf ~/.pip                     &&     awk
      '{cmd="pip3 install "$1;system(cmd)}' /hummingbirds/requirements &&     find
      /usr/lib/python* -name __pycache__ | xargs rm -rf               &&     rm -rf
      ~/* ~/.[^jvp\.]* /tmp/* /var/tmp/* /var/cache/apk/*           &&     rm -rf
      /usr/local/share/.[0-9a-zA-Z]* /usr/local/share/*             &&     rm -rf
      /usr/share/jupyter/lab/staging/build/* /usr/share/jupyter/kernels/*
    Name: run
    PrependShell: true
  - CmdLine:
    - jupyter labextension install @jupyterlab/hub-extension       &&     jupyter
      labextension install @fissio/hub-topbar-buttons      &&     jupyter labextension
      install jupyterlab-drawio               &&     jupyter labextension install
      jupyterlab-dash@0.1.0-alpha.3   &&     npm install -g configurable-http-proxy
      && npm cache clean -f &&     find /usr/lib/python* -name __pycache__ | xargs
      rm -rf       &&     rm -rf ~/* ~/.[^jvp\.]* /tmp/* /var/tmp/* /var/cache/apk/*   &&     rm
      -rf /usr/local/share/.[0-9a-zA-Z]* /usr/local/share/*     &&     rm -rf /usr/share/jupyter/lab/staging/build/*
      /usr/share/jupyter/kernels/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ~/.vim/UltiSnips ~/.vim/bundle /home/goofts/.jupyter                  &&     git
      clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &&     cp
      -rf /hummingbirds/settings         ~/.jupyter                               &&     cp
      -rf /hummingbirds/vimrc            ~/.vimrc                                 &&     cp
      -rf ~/.jupyter/lab                 /home/goofts/.jupyter                    &&     cp
      -rf ~/.vim                         /home/goofts/.vim                        &&     cp
      -rf ~/.vimrc                       /home/goofts/.vimrc                      &&     cp
      -rf /hummingbirds/supervisor       /supervisor                              &&     cp
      -rf /hummingbirds/startup.sh       /startup.sh                              &&     chown
      -R goofts:jupyter /home/goofts && chmod +x /startup.sh                   &&     chgrp
      -R jupyter /supervisor && chmod -R 2775 /supervisor                      &&     find
      /usr/lib/python* -name __pycache__ | xargs rm -rf                         &&     rm
      -rf ~/* ~/.[^jvp\.]* /tmp/* /var/tmp/* /var/cache/apk/*                     &&     rm
      -rf /usr/local/share/.[0-9a-zA-Z]* /usr/local/share/*                       &&     rm
      -rf /usr/share/jupyter/lab/staging/build/* /usr/share/jupyter/kernels/*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
  - CmdLine:
    - sh /startup.sh
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
