MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - install-nim.sh
    - cross-compile.nim.cfg
    - /root/
  - Env:
    - Key: OSXCROSS_REVISION
      Value: 9498bfdc621716959e575bd6779c853a03cf5f8d
    Name: env
  - Env:
    - Key: OSXCROSS_SDK_VERSION
      Value: "10.11"
    Name: env
  - Env:
    - Key: OSXCROSS_SDK_REMOTE_ROOT_DIR
      Value: https://github.com/apriorit/osxcross-sdks/raw/master/
    Name: env
  - Env:
    - Key: CHOOSENIM_CHOOSE_VERSION
      Value: 1.0.4
    Name: env
  - CmdLine:
    - dpkg --add-architecture i386 &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive
      apt-get upgrade -yy &&     DEBIAN_FRONTEND=noninteractive apt-get install -yy         automake                    bison                       curl                        file                        flex                        git                         libtool                     pkg-config                  python                      texinfo                     cmake                       wget                        software-properties-common         python-software-properties
      &&     apt-add-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8
      main" &&     apt-get update &&     apt-get -yy -qq --force-yes install clang-3.8
      lldb-3.8 &&     ln -f -s /usr/bin/clang-3.8 /usr/bin/clang &&     ln -f -s /usr/bin/clang++-3.8
      /usr/bin/clang++ &&     SDK_VERSION=$OSXCROSS_SDK_VERSION                               mkdir
      /opt/osxcross &&                                          cd /opt &&                                                      git
      clone https://github.com/tpoechtrager/osxcross.git &&       cd osxcross &&                                                  git
      checkout ${OSXCROSS_REVISION} &&        sed -i -e 's|-march=native||g' ./build_clang.sh
      ./wrapper/build.sh &&     ./tools/get_dependencies.sh &&                                  curl
      -L -o ./tarballs/MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz     ${OSXCROSS_SDK_REMOTE_ROOT_DIR}MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz
      &&     yes | PORTABLE=true ./build.sh &&                               ./build_compiler_rt.sh   &&     bash
      /root/install-nim.sh &&     rm /root/install-nim.sh &&     apt -y update &&
      apt -y install       musl       musl-dev       musl-tools       mingw-w64 &&     cat
      /root/cross-compile.nim.cfg >> $(find /root/.choosenim/toolchains/*/config/nim.cfg)
      &&     rm /root/cross-compile.nim.cfg &&     rm -rf /root/.choosenim/downloads/*
      &&     rm -rf /root/.choosenim/toolchains/*/c_code &&     rm -rf /root/.cache/*
      &&     rm -rf /tmp/*nim* &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/src
  - Env:
    - Key: PATH
      Value: $PATH:/opt/osxcross/target/bin:/root/.nimble/bin
    Name: env
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
