MetaArgs: null
Stages:
- BaseName: faboulaye/openjdk:alpine
  Commands:
  - Maintainer: Firdaws Aboulaye "aboufred@gmail.com"
    Name: maintainer
  - Key: KAFKA_VERSION
    Name: arg
    Value: 0.10.1.1
  - Key: KAFKA_MIRROR
    Name: arg
    Value: http://www-eu.apache.org
  - Key: KAFKA_SCALA_VERSION
    Name: arg
    Value: "2.11"
  - Env:
    - Key: KAFKA_HOME
      Value: /opt/kafka
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - CmdLine:
    - apk --update add --no-cache wget bash  && mkdir /opt   && wget -q -O - $KAFKA_MIRROR/dist//kafka/$KAFKA_VERSION/kafka_$KAFKA_SCALA_VERSION-$KAFKA_VERSION.tgz  |
      tar -xzf - -C /opt   && mv /opt/kafka_* $KAFKA_HOME   && addgroup -S kafka   &&
      adduser -S -u 200 -G kafka -h $KAFKA_HOME -s /bin/false kafka   && mkdir $KAFKA_HOME/data
      /var/log/kafka   && chown -R kafka:kafka $KAFKA_HOME   && chown -R kafka:kafka
      /var/log/kafka   && chmod a+x docker-entrypoint.sh   && apk del wget   && rm
      -rf /tmp/* /var/cache/* /usr/share/man/?? /usr/share/man/??_* /var/lib/apt/lists/*
      USER kafka
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9092"
  - Name: volume
    Volumes:
    - /opt/kafka/data
    - /opt/kafka/config
  - Name: workdir
    Path: $KAFKA_HOME
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  From:
    Image: faboulaye/openjdk:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM faboulaye/openjdk:alpine
