MetaArgs: null
Stages:
- BaseName: python:3.7.1
  Commands:
  - CmdLine:
    - apt update && apt-get install apache2-utils
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./pip-requirements/requirements.txt
    - /proj/requirements.txt
  - CmdLine:
    - pip install -r /proj/requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./client-binaries/Linux/testkit
    - /usr/local/bin/testkit
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./client-binaries/Linux/docker-18.09.4
    - /usr/bin/docker
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./client-binaries/Linux/kubectl-1.14
    - /usr/local/bin/kubectl
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./integration-tests
    - /system_test_toolbox/integration-tests
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./sut-configs
    - /system_test_toolbox/sut-configs
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./testkit-configs
    - /system_test_toolbox/testkit-configs
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./test-cases
    - /system_test_toolbox/test-cases
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./toolbox
    - /system_test_toolbox/toolbox
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./Makefile
    - /system_test_toolbox/Makefile
  - Name: workdir
    Path: /system_test_toolbox
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./README.md
    - /system_test_toolbox/README.md
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./setup.py
    - /system_test_toolbox/setup.py
  - CmdLine:
    - make install-dev
    Name: run
    PrependShell: true
  - Key: GIT_COMMIT
    Name: arg
    Value: null
  - Key: GIT_BRANCH
    Name: arg
    Value: null
  - CmdLine:
    - make meta-info > /docker-build-info.txt
    Name: run
    PrependShell: true
  From:
    Image: python:3.7.1
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7.1
