MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Alexander Trost <galexrt@googlemail.com>"'
    Name: label
  - Env:
    - Key: LANG
      Value: '"en_US.UTF-8"'
    - Key: LC_ALL
      Value: '"en_US.UTF-8 "'
    - Key: SINUS_USER
      Value: '"3000"'
    - Key: SINUS_GROUP
      Value: '"3000"'
    - Key: SINUS_DIR
      Value: '"/sinusbot"'
    - Key: YTDL_BIN
      Value: '"/usr/local/bin/youtube-dl"'
    - Key: YTDL_VERSION
      Value: '"latest"'
    - Key: SSL_LIBS_VERSION
      Value: '"3.0"'
    - Key: TS3_VERSION
      Value: '"3.2.1"'
    - Key: TS3_DL_ADDRESS
      Value: '"http://dl.4players.de/ts/releases/"'
    - Key: SINUSBOT_DL_URL
      Value: '"https://www.sinusbot.com/dl/sinusbot.current.tar.bz2"'
    Name: env
  - Env:
    - Key: SINUS_DATA
      Value: '"$SINUS_DIR/data"'
    - Key: SINUS_DATA_SCRIPTS
      Value: '"$SINUS_DIR/scripts"'
    - Key: SINUS_CONFIG
      Value: '"$SINUS_DIR/config"'
    - Key: TS3_DIR
      Value: '"$SINUS_DIR/TeamSpeak3-Client-linux_amd64"'
    Name: env
  - CmdLine:
    - "groupadd -g \"$SINUS_GROUP\" sinusbot &&     useradd -u \"$SINUS_USER\" -g
      \"$SINUS_GROUP\" -d \"$SINUS_DIR\" sinusbot &&     apt-get -q update -y &&     apt-get
      -q upgrade -y &&     apt-get -q install -y x11vnc xvfb libxcursor1 ca-certificates
      bzip2 libnss3 libegl1-mesa x11-xkb-utils libasound2         libglib2.0-0 libnss3
      locales wget sudo python less &&     locale-gen --purge \"$LANG\" &&     update-locale
      LANG=\"$LANG\" &&     echo \"LC_ALL=en_US.UTF-8\" >> /etc/default/locale &&
      \    echo \"LANG=en_US.UTF-8\" >> /etc/default/locale &&     update-ca-certificates
      &&     mkdir -p \"$SINUS_DIR\" &&     wget -qO- \"$SINUSBOT_DL_URL\" |     tar
      -xjf- -C \"$SINUS_DIR\" &&     mv \"$SINUS_DATA_SCRIPTS\" \"$SINUS_DATA_SCRIPTS-orig\"
      &&     mkdir -p \"$SINUS_CONFIG\" \"$SINUS_DATA_SCRIPTS\" &&     cp -f \"$SINUS_DIR/config.ini.dist\"
      \"$SINUS_DIR/config.ini\" &&     sed -i 's|^DataDir.*|DataDir = '\"$SINUS_DATA\"'|g'
      \"$SINUS_DIR/config.ini\" && \twget -qO- \"https://dl.sinusbot.com/ffmpeg-$SSL_LIBS_VERSION-ssl.tar.bz2\"
      | \ttar -xjf- -C \"$SINUS_DIR\" &&     mkdir -p \"$TS3_DIR\" &&     cd \"$SINUS_DIR\"
      || exit 1 &&     wget -q -O \"TeamSpeak3-Client-linux_amd64-$TS3_VERSION.run\"
      \        \"$TS3_DL_ADDRESS/$TS3_VERSION/TeamSpeak3-Client-linux_amd64-$TS3_VERSION.run\"
      &&     chmod 755 \"TeamSpeak3-Client-linux_amd64-$TS3_VERSION.run\" &&     yes
      | \"./TeamSpeak3-Client-linux_amd64-$TS3_VERSION.run\" &&     rm -f \"TeamSpeak3-Client-linux_amd64-$TS3_VERSION.run\"
      &&     rm TeamSpeak3-Client-linux_amd64/xcbglintegrations/libqxcb-glx-integration.so
      &&     mkdir -p TeamSpeak3-Client-linux_amd64/plugins &&     cp -f \"$SINUS_DIR/plugin/libsoundbot_plugin.so\"
      \"$TS3_DIR/plugins/\" &&     sed -i \"s|^TS3Path.*|TS3Path = \\\"$TS3_DIR/ts3client_linux_amd64\\\"|g\"
      \"$SINUS_DIR/config.ini\" &&     wget -q -O \"$YTDL_BIN\" \"https://yt-dl.org/downloads/$YTDL_VERSION/youtube-dl\"
      &&     chmod a+rx \"$YTDL_BIN\" &&     \"$YTDL_BIN\" -U &&     echo \"YoutubeDLPath
      = \\\"$YTDL_BIN-speedpatched\\\"\" >> \"$SINUS_DIR/config.ini\" &&     chown
      -fR sinusbot:sinusbot \"$SINUS_DIR\" &&     apt-get -q clean all &&     rm -rf
      /tmp/* /var/tmp/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - youtube-dl-speedpatched
    - /usr/local/bin/youtube-dl-speedpatched
  - Name: user
    User: sinusbot
  - Name: workdir
    Path: '"$SINUS_DIR"'
  - Name: volume
    Volumes:
    - $SINUS_DATA
    - $SINUS_DATA_SCRIPTS
    - $SINUS_CONFIG
  - Name: expose
    Ports:
    - "8087"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
