MetaArgs: null
Stages:
- BaseName: alpine:3.6
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ucspi-tcp-0.88.tar.gz
    - ucspi-tcp-0.88.errno.patch
    - /tmp/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /tmp/
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - apk --update add gcc musl-dev make && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvzf ucspi-tcp-0.88.tar.gz &&     cd ucspi-tcp-0.88 &&     patch -Np1 -i
      ../ucspi-tcp-0.88.errno.patch &&     sed 's|/usr/local|/usr|' conf-home > conf-home~
      &&     mv -f conf-home~ conf-home &&     make &&     make setup check
    Name: run
    PrependShell: true
  - CmdLine:
    - /tmp/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - tcpserver
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.6
