MetaArgs: null
Stages:
- BaseName: php:7.2
  Commands:
  - Maintainer: Szymon Bluma <szbluma@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y     libicu-dev libmcrypt-dev libzip-dev
      libbz2-dev     libpng-dev jpegoptim libfreetype6-dev libjpeg62-turbo-dev libgmp-dev     libwebp-dev     unzip
      git
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install -j$(nproc) gd gmp iconv intl pdo pdo_mysql zip bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install redis
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug && docker-php-ext-enable xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
      --filename=composer && composer --version
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/localtime   && ln -s /usr/share/zoneinfo/Europe/Warsaw /etc/localtime   &&
      "date"
    Name: run
    PrependShell: true
  From:
    Image: php:7.2
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2
