MetaArgs: null
Stages:
- As: fetcher
  BaseName: ubuntu:latest
  Commands:
  - CmdLine:
    - "true \t&& apt update \t&& apt upgrade --assume-yes \t&& apt install --assume-yes
      --no-install-recommends \t\tcurl \t\tgcc \t\tgit \t\tgpg-agent \t\tmake \t\tlibc6-dev
      \t\tsoftware-properties-common \t&& curl -sL https://deb.nodesource.com/setup_8.x
      | bash - \t&& apt install --assume-yes --no-install-recommends \t\tnodejs \t&&
      git clone https://github.com/mattgodbolt/compiler-explorer.git \t&& cd compiler-explorer
      \t&& make prereqs"
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:latest
  Name: fetcher
  Platform: ""
  SourceCode: FROM ubuntu:latest as fetcher
- BaseName: ubuntu:latest
  Commands:
  - Chown: ""
    From: fetcher
    Name: copy
    SourcesAndDest:
    - /compiler-explorer
    - /compiler-explorer
  - Chown: ""
    From: fetcher
    Name: copy
    SourcesAndDest:
    - /etc/apt
    - /etc/apt
  - CmdLine:
    - "sed -i 's/https/http/' /etc/apt/sources.list.d/nodesource.list \t&& apt update
      \t&& apt install --assume-yes --no-install-recommends \t\tgit \t\tg++ \t\tmake
      \t\tnodejs \t&& apt clean \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: EXTRA_ARGS
      Value: '"--host 0.0.0.0"'
    Name: env
  - Name: expose
    Ports:
    - "10240"
  - Name: workdir
    Path: /compiler-explorer
  - CmdLine:
    - make
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
