MetaArgs: null
Stages:
- BaseName: node:argon-slim
  Commands:
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - /usr/src/app/
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /usr/src/app
  - CmdLine:
    - npm run grunt
    Name: run
    PrependShell: true
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:argon-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:argon-slim
