MetaArgs: null
Stages:
- BaseName: ubuntu:wily
  Commands:
  - Maintainer: kmilner "kmilner@seven10storage.com"
    Name: maintainer
  - CmdLine:
    - apt-get update -q &&   DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common
      python-software-properties &&   add-apt-repository -y ppa:webupd8team/java &&   apt-get
      update -q &&   echo debconf shared/accepted-oracle-license-v1-1 select true
      | debconf-set-selections &&   echo debconf shared/accepted-oracle-license-v1-1
      seen true | debconf-set-selections &&   DEBIAN_FRONTEND=noninteractive apt-get
      install -y oracle-java8-installer openssh-server curl lxc vim &&   rm -rf /var/cache/oracle-jdk8-installer
      &&   rm -rf /var/lib/apt/lists/*  &&   apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g'
      /etc/pam.d/sshd
    Name: run
    PrependShell: true
  - CmdLine:
    - 'mkdir -p /var/run/sshd &&    locale-gen en_US.UTF-8 &&    useradd -s /bin/bash
      -d /home/jenkins -p "paZMSFlwB0Lw6" jenkins &&    mkdir -p /home/jenkins &&    chown
      -R jenkins:jenkins /home/jenkins &&    echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/setup-docker-and-start-ssh.sh
    - /usr/local/bin/setup-docker-and-start-ssh.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/phone-home.sh
    - /usr/local/bin/phone-home.sh
  - CmdLine:
    - chmod +x /usr/local/bin/setup-docker-and-start-ssh.sh /usr/local/bin/phone-home.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /usr/local/bin/setup-docker-and-start-ssh.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:wily
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:wily
