MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Env:
    - Key: REFRESHED_AT
      Value: "2017-02-20"
    Name: env
  - Env:
    - Key: BUILD_TOOLS
      Value: 23.0.3
    Name: env
  - Env:
    - Key: GRADLE_VERSION
      Value: "2.4"
    Name: env
  - Env:
    - Key: NODE_VERSION
      Value: 6.8.1
    Name: env
  - Env:
    - Key: NPM_VERSION
      Value: "3"
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: ANDROID_HOME
      Value: /usr/local/android-sdk-linux
    Name: env
  - Env:
    - Key: ANDROID_SDK
      Value: /usr/local/android-sdk-linux
    Name: env
  - Env:
    - Key: PATH
      Value: ${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/${BUILD_TOOLS}:$PATH
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: ${ANDROID_SDK}/tools/lib64:${ANDROID_SDK}/tools/lib64/qt/lib:${LD_LIBRARY_PATH}
    Name: env
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-openjdk-amd64/
    Name: env
  - Env:
    - Key: TERM
      Value: dumb
    Name: env
  - Env:
    - Key: JAVA_OPTS
      Value: '"-Xms512m -Xmx1024m"'
    Name: env
  - Env:
    - Key: GRADLE_OPTS
      Value: '"-XX:+UseG1GC -XX:MaxGCPauseMillis=1000"'
    Name: env
  - CmdLine:
    - mkdir -p /root/.android
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /root/.gradle
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - configs/init.gradle
    - /root/.gradle/init.gradle
  - CmdLine:
    - set -ex   && apt-get update   && apt-get install --no-install-recommends -y
      apt-utils xz-utils apt-transport-https ca-certificates curl   build-essential
      lib32stdc++6 lib32z1 lib32z1-dev lib32ncurses5 libbz2-1.0 libc6-dev   zlib1g-dev
      libxml2-dev software-properties-common python-software-properties   unzip git
      wget bzip2 rsync zip curl ruby ruby-dev openssh-client default-jdk   && apt-get
      autoremove -y   && apt-get clean   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex     && curl -OLsS https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install --no-rdoc --no-ri fastlane screengrab sigh gym
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex   && curl -LsS https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz
      | tar xJ --strip-components 1 -C /usr   && if [ -x /usr/bin/npm ]; then     npm
      install -g npm@${NPM_VERSION}     && find /usr/lib/node_modules/npm -name test
      -o -name .bin -type d | xargs rm -rf;   fi
    Name: run
    PrependShell: true
  - CmdLine:
    - set -x   && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add
      -   && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list   &&
      apt-get update   && apt-get install -y yarn   && apt-get autoremove -y   &&
      apt-get clean   && rm -rf /var/lib/apt/lists/*   && ln -s /usr/local/bin/node
      /usr/local/bin/nodejs   && yarn -V   && node -v
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz | tar xz
      -C /usr/local/   && echo y | android update sdk --no-https --no-ui --all --filter
      tools,platform-tools,build-tools-$BUILD_TOOLS   && echo y | android update sdk
      --no-https --no-ui --all --filter build-tools-23.0.1,build-tools-23.0.2   &&
      echo y | android update sdk --no-https --no-ui --all --filter android-23,addon-google_apis-google-23   &&
      echo y | android update sdk --no-https --no-ui --all --filter extra-android-support,extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
