MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Maintainer: Patrick Liess <smrchy@gmail.com>
    Name: maintainer
  - Name: volume
    Volumes:
    - /srv/thumbor/storage
  - CmdLine:
    - apt-get update && apt-get upgrade -y && apt-get -y install build-essential checkinstall
      gcc python python-dev libpng12-dev libtiff5-dev libpng-dev libjasper-dev libwebp-dev
      libcurl4-openssl-dev python-pgmagick libmagick++-dev graphicsmagick libopencv-dev
      python-pip && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pycurl numpy
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install thumbor
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - thumbor.conf
    - /etc/thumbor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init
    - /init
  - CmdLine:
    - chmod +x /init
    Name: run
    PrependShell: true
  - CmdLine:
    - /init
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
