MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - Maintainer: bingo <bingov5@icloud.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://raw.githubusercontent.com/bingozb/docker-idea-license-server/master/idea_license_server
    - /idea_license_server
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://raw.githubusercontent.com/bingozb/docker-idea-license-server/master/IntelliJIDEALicenseServer.html
    - /IntelliJIDEALicenseServer.html
  - CmdLine:
    - chmod +x /idea_license_server
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - Name: expose
    Ports:
    - "1027"
  - CmdLine:
    - /idea_license_server
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
