MetaArgs: null
Stages:
- As: dotnet-test
  BaseName: mcr.microsoft.com/dotnet/core/sdk:2.2
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - sh build/test.sh
    Name: run
    PrependShell: true
  From:
    Image: mcr.microsoft.com/dotnet/core/sdk:2.2
  Name: dotnet-test
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as dotnet-test
- As: dotnet-build
  BaseName: mcr.microsoft.com/dotnet/core/sdk:2.2
  Commands:
  - Name: workdir
    Path: /src
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - sh build/build.sh
    Name: run
    PrependShell: true
  From:
    Image: mcr.microsoft.com/dotnet/core/sdk:2.2
  Name: dotnet-build
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as dotnet-build
- BaseName: mcr.microsoft.com/dotnet/core/aspnet:2.2.2
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: dotnet-build
    Name: copy
    SourcesAndDest:
    - /app
    - .
  - Chown: ""
    From: dotnet-build
    Name: copy
    SourcesAndDest:
    - /src/healthcheck.sh
    - .
  - CmdLine:
    - dotnet
    - Modix.dll
    Name: entrypoint
    PrependShell: false
  From:
    Image: mcr.microsoft.com/dotnet/core/aspnet:2.2.2
  Name: ""
  Platform: ""
  SourceCode: FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.2
