MetaArgs: null
Stages:
- BaseName: openjdk:11-jre-slim-sid
  Commands:
  - CmdLine:
    - apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     curl
      graphviz unzip   && rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get
      autoclean && apt-get autoremove
    Name: run
    PrependShell: true
  - Env:
    - Key: KAITAI_URL
      Value: https://dl.bintray.com/kaitai-io/universal/0.8/kaitai-struct-compiler-0.8.zip
    Name: env
  - CmdLine:
    - "curl -SL ${KAITAI_URL} -o /tmp/kaitai-struct-compiler.zip && \tunzip /tmp/kaitai-struct-compiler.zip
      -d /opt/ && \trm /tmp/kaitai-struct-compiler.zip && \tmv /opt/$(basename ${KAITAI_URL%.*})
      /opt/kaitai-struct-compiler && \tchmod +x /opt/kaitai-struct-compiler/bin/kaitai-struct-compiler
      && \tln -s /opt/kaitai-struct-compiler/bin/kaitai-struct-compiler /usr/bin/ksc"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /pwd
  - Name: workdir
    Path: /pwd
  From:
    Image: openjdk:11-jre-slim-sid
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:11-jre-slim-sid
