MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Env:
    - Key: HOME
      Value: /wey
    Name: env
  - CmdLine:
    - apt-get update -q
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -qq -y install  wget  git  gcc  software-properties-common  build-essential  libtool  autotools-dev  autoconf  automake  libssl-dev  libevent-dev  libboost-all-dev  pkg-config
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:bitcoin/bitcoin
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -q && apt-get -qq -y install  libdb4.8-dev  libdb4.8++-dev  libminiupnpc-dev  libzmq3-dev  libevent-pthreads-2.0-5  libqt5gui5  libqt5core5a  libqt5dbus5  qttools5-dev  qttools5-dev-tools  libprotobuf-dev  libqrencode-dev
      && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth 1 -b 1.3.0.1  https://github.com/WeyCoin/WeyCoin.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /WeyCoin
  - CmdLine:
    - ./autogen.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - ./configure --disable-tests --disable-gui-tests --with-gui=no
    Name: run
    PrependShell: true
  - CmdLine:
    - make
    Name: run
    PrependShell: true
  - CmdLine:
    - strip ./src/weycoind
    Name: run
    PrependShell: true
  - CmdLine:
    - strip ./src/weycoin-cli
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update -q
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -qq -y install --no-install-recommends  software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:bitcoin/bitcoin
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -q
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -qq -y install --no-install-recommends  libminiupnpc-dev  libdb4.8-dev  libdb4.8++-dev  libevent-dev  libboost-all-dev  libzmq3-dev
      && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /WeyCoin/src/weycoind
    - /usr/local/bin/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /WeyCoin/src/weycoin-cli
    - /usr/local/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./weycoin-masternode.sh
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./weycoin-default.conf
    - ./
  - CmdLine:
    - groupadd -r weycoin && useradd --no-log-init -m -d /wey -g weycoin weycoin
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /wey/.weycoin/
    Name: run
    PrependShell: true
  - CmdLine:
    - chown weycoin:weycoin -R /wey
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod a+x /usr/local/bin/*
    Name: run
    PrependShell: true
  - Env:
    - Key: MALLOC_ARENA_MAX
      Value: "1"
    Name: env
  - Name: volume
    Volumes:
    - /wey/.weycoin/
  - Name: expose
    Ports:
    - "11526"
  - Name: workdir
    Path: /wey
  - CmdLine:
    - bash
    - /weycoin-masternode.sh
    Name: entrypoint
    PrependShell: false
  - Name: user
    User: weycoin
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
