MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Thomas Stägemann <staegi@github>"'
    Name: label
  - Labels:
    - Key: description
      Value: '"PaperCut MF Application Server"'
    Name: label
  - Env:
    - Key: PAPERCUT_MAJOR_VER
      Value: 19.x
    Name: env
  - Env:
    - Key: PAPERCUT_VER
      Value: 19.1.2.52029
    Name: env
  - Env:
    - Key: PAPERCUT_DOWNLOAD_URL
      Value: https://cdn1.papercut.com/web/products/ng-mf/installers/mf/${PAPERCUT_MAJOR_VER}/pcmf-setup-${PAPERCUT_VER}.sh
    Name: env
  - CmdLine:
    - useradd -mUd /papercut -s /bin/bash papercut
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y curl cpio && apt-get clean && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L "${PAPERCUT_DOWNLOAD_URL}" -o /pcmf-setup.sh && chmod a+rx /pcmf-setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - runuser -l papercut -c "/pcmf-setup.sh --non-interactive" && rm -f /pcmf-setup.sh
      && /papercut/MUST-RUN-AS-ROOT
    Name: run
    PrependShell: true
  - CmdLine:
    - /etc/init.d/papercut stop && /etc/init.d/papercut-web-print stop
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /papercut
  - Name: volume
    Volumes:
    - /papercut/server/data
    - /papercut/server/custom
    - /papercut/server/logs
  - Name: expose
    Ports:
    - "9191"
    - "9192"
    - "9193"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - Env:
    - Key: MYSQL_CONNECTOR_VERSION
      Value: 8.0.17
    Name: env
  - Env:
    - Key: MYSQL_CONNECTOR_DOWNLOAD_URL
      Value: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.tar.gz
    Name: env
  - CmdLine:
    - "curl -L \"${MYSQL_CONNECTOR_DOWNLOAD_URL}\" -o /mysql.tar.gz \t&& tar -xvzf
      /mysql.tar.gz -C /     && mv /mysql-connector-java-${MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar
      /papercut/server/lib-ext/     && rm -r /mysql-connector-java-${MYSQL_CONNECTOR_VERSION}
      \    && rm /mysql.tar.gz"
    Name: run
    PrependShell: true
  - Env:
    - Key: ENVSUBST_DOWNLOAD_URL
      Value: https://github.com/a8m/envsubst/releases/download/v1.1.0/envsubst-Linux-x86_64
    Name: env
  - CmdLine:
    - curl -L "${ENVSUBST_DOWNLOAD_URL}" -o /usr/local/bin/envsubst
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/envsubst
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - server.properties.template
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
