MetaArgs: null
Stages:
- BaseName: haproxy:alpine
  Commands:
  - CmdLine:
    - "apk add --no-cache \tbash \tca-certificates \tinotify-tools"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: haproxy:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM haproxy:alpine
