MetaArgs: null
Stages:
- BaseName: makeomatic/ruby:v2.3.1
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./
  - CmdLine:
    - bundle config --global frozen 1   && mkdir -p /usr/src/app   && apk add --no-cache
      --virtual .buildDeps     g++     make     libstdc++     mariadb-dev     git     openssl     ca-certificates   &&
      bundle install --path vendor/gems --binstubs   && apk add --no-cache --virtual
      .runDeps     libstdc++     mariadb-client-libs     openssl     ca-certificates   &&
      apk del .buildDeps   && chown -R ruby:ruby /usr/src/app   && chmod +x ./entrypoint.sh
    Name: run
    PrependShell: true
  - Name: user
    User: ruby
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - ./entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - thin
    - -p
    - "8080"
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: makeomatic/ruby:v2.3.1
  Name: ""
  Platform: ""
  SourceCode: FROM makeomatic/ruby:v2.3.1
