MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: Ozzy Johnson <docker@ozzy.io>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update             --quiet   && apt-get install             --yes             --no-install-recommends             --no-install-suggests         autoconf         automake         build-essential         ca-certificates         git-core         libass-dev         libgpac-dev         libtheora-dev         libtool         libvorbis-dev         pkg-config         python-minimal         texi2html         zlib1g-dev     &&
      apt-get clean     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - git clone git://github.com/yasm/yasm.git     && cd yasm     && ./autogen.sh     &&
      ./configure     && make -j`getconf _NPROCESSORS_ONLN`     && make install     &&
      make distclean     && cd /tmp     && rm -rf /tmp/yasm
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone git://git.videolan.org/x264.git     && cd x264     && ./configure
      --enable-static --disable-opencl     && make -j`getconf _NPROCESSORS_ONLN`     &&
      make install     && make distclean     && cd /tmp     && rm -rf /tmp/x264
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone git://git.opus-codec.org/opus.git     && cd opus     && ./autogen.sh     &&
      ./configure --disable-shared     && make -j`getconf _NPROCESSORS_ONLN`     &&
      make install     && make distclean     && cd /tmp     && rm -rf /tmp/opus
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://chromium.googlesource.com/webm/libvpx     && cd libvpx     &&
      ./configure --disable-shared     && make -j`getconf _NPROCESSORS_ONLN`     &&
      make install     && make clean     && cd /tmp     && rm -rf /tmp/libvpx
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone git://source.ffmpeg.org/ffmpeg.git     && cd ffmpeg     && ./configure         --disable-debug         --enable-small         --extra-libs=-ldl         --enable-gpl         --enable-libass         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libx264     &&
      make -j`getconf _NPROCESSORS_ONLN`     && make install     && make distclean     &&
      cd /tmp     && rm -rf /tmp/ffmpeg
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8888"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - record.sh
    - /record.sh
  - Expression: VOLUME ["/data"]
    Name: onbuild
  - Name: workdir
    Path: /data
  - CmdLine:
    - /bin/bash
    - /record.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
