MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: '"Bogdan Girman" <bogdan.girman@gmail.com>'
    Name: maintainer
  - Labels:
    - Key: name
      Value: '"Docker image for the Robot Framework http://robotframework.org/"'
    Name: label
  - Labels:
    - Key: usage
      Value: '"docker run -e ROBOT_TESTS=/path/to/tests/ --rm -v $(pwd)/path/to/tests/:/path/to/tests/
        -ti robot-docker"'
    Name: label
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y         build-essential        fonts-liberation        gconf-service        libappindicator1        libasound2        libcurl3        libffi-dev        libgconf-2-4        libindicator7        libnspr4        libnss3        libpango1.0-0        libssl-dev        libxss1        python-dev        python-pip        python-pyasn1        python-pyasn1-modules        unzip        wget        xdg-utils        xvfb        &&     pip
      install --upgrade pip
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://mirror.glendaleacademy.org/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_53.0.2785.143-1_amd64.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg -i google-chrome*.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -N http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip chromedriver_linux64.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x chromedriver
    Name: run
    PrependShell: true
  - CmdLine:
    - mv -f chromedriver /usr/local/share/chromedriver
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/local/share/chromedriver /usr/local/bin/chromedriver
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/local/share/chromedriver /usr/bin/chromedriver
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /usr/local/bin/run.sh
  - CmdLine:
    - chmod +x /usr/local/bin/run.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /requirements.txt
  - CmdLine:
    - pip install -r /requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
