MetaArgs: null
Stages:
- BaseName: debian:experimental
  Commands:
  - CmdLine:
    - echo 'APT::Get::Show-Versions "1";' > /etc/apt/apt.conf.d/verbose
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb http://incoming.debian.org/debian-buildd buildd-unstable main' > /etc/apt/sources.list.d/incoming.list
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update && apt-get install -y \t\tautopkgtest qemu \t\tbash-completion
      curl less rsync vim wget \t\tbuild-essential \t\tdebian-keyring \t\tdevscripts
      \t\tdh-make \t\tdput-ng \t\tequivs \t\tgit mercurial subversion \t\tgit-buildpackage
      git-dpm svn-buildpackage \t\tgolang-go \t\tlibcrypt-ssleay-perl \t\tlibdistro-info-perl
      \t\tlibfile-fcntllock-perl \t\tlibwww-perl \t\tlintian \t\topenssh-client \t\tpristine-tar
      \t\tpython-distro-info \t\tpython3-debian \t\tquilt \t\treprepro \t\tsudo \t\tubuntu-dev-tools
      pbuilder \t\t--no-install-recommends \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - "mkdir -p /go \t&& export GOPATH=/go \t&& go get -v github.com/debian/dh-make-golang
      \t&& mv /go/bin/dh-make-golang /usr/local/bin/ \t&& rm -rf /go"
    Name: run
    PrependShell: true
  - CmdLine:
    - find /etc/apt/sources.list* -type f -exec sed -i 'p; s/^deb /deb-src /' '{}'
      +
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo ''ALL ALL=(ALL) NOPASSWD: ALL'' > /etc/sudoers.d/allusers-nopass'
    Name: run
    PrependShell: true
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - CmdLine:
    - "{ \techo \"export DEBFULLNAME='' DEBEMAIL=''\"; \techo 'dch -i'; \techo 'lintian
      --ftp-master-rejects'; \techo 'uscan --force-download --verbose --download-current-version';
      } >> ~/.bash_history"
    Name: run
    PrependShell: true
  - CmdLine:
    - "mkdir -p ~/.ssh && chmod 700 ~/.ssh \t&& wget -O ~/.ssh/known_hosts https://db.debian.org/debian_known_hosts
      \t&& chmod 644 ~/.ssh/known_hosts"
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: TERM
      Value: xterm-256color
    Name: env
  - CmdLine:
    - "cp /etc/skel/.bashrc ~/ \t&& sed -ri 's/^#(force_color_prompt=yes)/\\1/' ~/.bashrc"
    Name: run
    PrependShell: true
  - Env:
    - Key: QUILT_PATCHES
      Value: debian/patches
    Name: env
  - Env:
    - Key: QUILT_REFRESH_ARGS
      Value: -p ab --no-timestamps --no-index
    Name: env
  - Env:
    - Key: UBUNTUTOOLS_DEBIAN_MIRROR
      Value: http://deb.debian.org/debian
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts
    - /tianon
  From:
    Image: debian:experimental
  Name: ""
  Platform: ""
  SourceCode: FROM debian:experimental
