MetaArgs: null
Stages:
- BaseName: scratch
  Commands:
  - Maintainer: Steffen Bleul <blacklabelops@itbleul.de>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - blacklabelops-centos7.xz
    - /
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
