MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/mirror.yandex.ru/g'
      /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get upgrade -y && apt-get install python-minimal python-setuptools
      -y && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb http://repo.acestream.org/ubuntu/ trusty main' | sudo tee /etc/apt/sources.list.d/acestream.list
      &&     python -c "import urllib; print urllib.urlopen('http://repo.acestream.org/keys/acestream.public.key').read()"
      | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y acestream-engine && apt-get clean
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "62062"
    - "6878"
    - "8621"
  - CmdLine:
    - /usr/bin/acestreamengine
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
