MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Maintainer: Nathan Douglas <docker@tenesm.us>
    Name: maintainer
  - Env:
    - Key: BEETSDIR
      Value: /config
    Name: env
  - CmdLine:
    - set -xe   && apk add --no-cache     bash     curl     faac     faad2     ffmpeg     flac     imagemagick     jq     lame     libvorbis     mutagen     nano     opus     py-pip     py-gst     python   &&
      pip install -U pip   && pip install -U     beautifulsoup4     beets     discogs-client     pathlib     pyacoustid     pylast     https://github.com/ocelma/python-itunes/archive/master.zip     pyxdg     requests     https://github.com/hay/xml2json/zipball/master
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
    - /data
    - /music
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
