MetaArgs: null
Stages:
- BaseName: haproxy:latest
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - haproxy.cfg
    - /usr/local/etc/haproxy/haproxy.cfg
  - Name: expose
    Ports:
    - "9090"
  From:
    Image: haproxy:latest
  Name: ""
  Platform: ""
  SourceCode: FROM haproxy:latest
