MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Labels:
    - Key: vendor
      Value: '"TheNets.org EasyCKAN"'
    Name: label
  - Labels:
    - Key: org.thenets.easyckan.version
      Value: '"2.6"'
    Name: label
  - Labels:
    - Key: org.thenets.easyckan.release-date
      Value: '"2017-04-06"'
    Name: label
  - Env:
    - Key: CKAN_HOME
      Value: /usr/lib/ckan
    Name: env
  - Env:
    - Key: CKAN_CONFIG
      Value: /etc/ckan/default
    Name: env
  - Env:
    - Key: CKAN_DATA
      Value: /var/lib/ckan/default
    Name: env
  - Env:
    - Key: CKAN_VIRTUALENV
      Value: default
    Name: env
  - Name: user
    User: root
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r -g 5000 ckan &&     useradd -mr -c "CKAN User" -d $CKAN_HOME -g
      5000 -u 5000 ckan
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y sudo gcc git-core postgresql-client libpq-dev python-pip             python-virtualenv
      python-dev python-paste libmemcached-dev zlib1g-dev redis-server &&     apt-get
      clean all && apt-get autoclean &&     apt-get autoremove -y
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p $CKAN_CONFIG $CKAN_LOG $CKAN_DATA
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y links htop nano vim libnet-ifconfig-wrapper-perl &&     apt-get
      clean all && apt-get autoclean &&     apt-get autoremove -y
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./install.sh
    - /
  - CmdLine:
    - chmod +x ./install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - python --version
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - '[$CKAN_CONFIG,'
    - $CKAN_LOG,
    - $CKAN_DATA]
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
