MetaArgs: null
Stages:
- BaseName: java:8-jdk
  Commands:
  - Maintainer: Uwe Mesecke <uwe@mesecke.net>
    Name: maintainer
  - Env:
    - Key: GRADLE_VERSION
      Value: "3.0"
    Name: env
  - Env:
    - Key: GRADLE_URL
      Value: https://downloads.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
    Name: env
  - Env:
    - Key: GRADLE_SHA256
      Value: 39c906941a474444afbddc38144ed44166825acb0a57b0551dddb04bbf157f80
    Name: env
  - Env:
    - Key: GRADLE_HOME
      Value: /opt/gradle
    Name: env
  - Name: workdir
    Path: /opt/
  - CmdLine:
    - wget -O gradle.zip $GRADLE_URL  && echo "$GRADLE_SHA256  gradle.zip" | sha256sum
      -c -  && unzip gradle.zip  && rm gradle.zip  && mv gradle-${GRADLE_VERSION}
      $GRADLE_HOME  && chmod -R 777 $GRADLE_HOME
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:$GRADLE_HOME/bin
    Name: env
  - Env:
    - Key: GRADLE_USER_HOME
      Value: /cache/.gradle
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cmd.sh
    - /
  - Name: user
    User: root
  - Name: volume
    Volumes:
    - /cache
  - Name: volume
    Volumes:
    - /builds
  - Name: workdir
    Path: /builds
  - CmdLine:
    - /cmd.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: java:8-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM java:8-jdk
