MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: matracey
    Name: maintainer
  - CmdLine:
    - yum -y install glibc.i686 libgcc.i686 libstdc++.i686 zlib.i686
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd codwaw
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - codwaw
    - /home/codwaw/
  - CmdLine:
    - chown -R codwaw:codwaw /home/codwaw
    Name: run
    PrependShell: true
  - Name: user
    User: codwaw
  - Name: workdir
    Path: /home/codwaw
  - CmdLine:
    - /home/codwaw/codwaw_lnxded
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - +set sv_authorizemode '-1'
    - +exec server.cfg
    - +map_rotate
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
