MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: ChivPoint "chivpoint@yandex.ru"
    Name: maintainer
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
