MetaArgs: null
Stages:
- BaseName: node:8-alpine
  Commands:
  - Name: expose
    Ports:
    - "3000"
  - Key: NODE_ENV
    Name: arg
    Value: null
  - Env:
    - Key: NODE_ENV
      Value: ${NODE_ENV}
    Name: env
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - package.json
    - package-lock.json
    - /app/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait
    - /wait
  - CmdLine:
    - chmod +x /wait
    Name: run
    PrependShell: true
  - CmdLine:
    - /wait && npm run dev
    Name: cmd
    PrependShell: true
  From:
    Image: node:8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8-alpine
