MetaArgs: null
Stages:
- BaseName: szyhf/alpine-glibc
  Commands:
  - Labels:
    - Key: MAINTAINER
      Value: '"Back Yu <yhfszb@gamil.com>"'
    Name: label
  - Env:
    - Key: LITECOIN_VERSION
      Value: 0.16.3
    Name: env
  - CmdLine:
    - "apk update \t&& apk --no-cache add wget ca-certificates \t&& wget https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz
      \t&& tar xzvf /litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz \t&& mkdir
      /root/.litecoin \t&& apk del wget ca-certificates \t&& mv /litecoin-${LITECOIN_VERSION}/bin/*
      /usr/local/bin/ \t&& rm -rf /litecoin-${LITECOIN_VERSION}/ \t&& rm -rf /litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz
      \t&& rm -rf /glibc-${GLIBC_VERSION}.apk \t&& rm -rf /glibc-bin-${GLIBC_VERSION}.apk"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9332"
    - "9333"
  - CmdLine:
    - litecoind
    Name: cmd
    PrependShell: true
  From:
    Image: szyhf/alpine-glibc
  Name: ""
  Platform: ""
  SourceCode: FROM szyhf/alpine-glibc
