MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - "apk update &&   apk upgrade && \tapk add python py-requests py-pip && \tpip
      install influxdb"
    Name: run
    PrependShell: true
  - CmdLine:
    - "apk del --purge &&  rm -rf \t/root/.cache"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /root/
  - CmdLine:
    - python /root/qbittorrent_influxdb_export.py     --qbittorrenthost=${QBITTORRENT_HOST}     --qbittorrentport=${QBITTORRENT_PORT}     --qbittorrentuser=${QBITTORRENT_USER}     --qbittorrentpassword=${QBITTORRENT_PASSWORD}     --influxdbhost=${INFLUXDB_HOST}     --influxdbport=${INFLUXDB_PORT}
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: "FROM\talpine:latest"
