MetaArgs: null
Stages:
- BaseName: ruby:2.4.1-slim
  Commands:
  - Labels:
    - Key: maintainer
      Value: Joni Hasanen "joni@pieceofcode.com"
    Name: label
  - Env:
    - Key: APP_USER
      Value: herkko
    Name: env
  - Env:
    - Key: APP_HOME
      Value: /app
    Name: env
  - CmdLine:
    - apt-get update     && apt-get -y --no-install-recommends install git build-essential
      curl     && curl -o heroku.tar.gz https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz     &&
      tar -xzf heroku.tar.gz     && mkdir -p /usr/local/lib /usr/local/bin     &&
      mv heroku-cli-* /usr/local/lib/heroku     && ln -s /usr/local/lib/heroku/bin/heroku
      /usr/local/bin/heroku
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install herkko
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install travis
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y purge build-essential && apt-get clean  apt-get -y autoremove
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd  --create-home --shell /bin/bash $APP_USER
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p $APP_HOME
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R $APP_USER $APP_HOME
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $APP_HOME
  - Name: user
    User: $APP_USER
  - CmdLine:
    - herkko
    Name: entrypoint
    PrependShell: false
  From:
    Image: ruby:2.4.1-slim
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.4.1-slim
