MetaArgs: null
Stages:
- BaseName: jazzdd/alpine-flask:python3
  Commands:
  - CmdLine:
    - cd /app
    Name: run
    PrependShell: true
  - Env:
    - Key: GREET
      Value: hola
    Name: env
  - CmdLine:
    - git clone https://github.com/cowbotic/test.git .
    Name: run
    PrependShell: true
  From:
    Image: jazzdd/alpine-flask:python3
  Name: ""
  Platform: ""
  SourceCode: FROM jazzdd/alpine-flask:python3
