MetaArgs: null
Stages:
- BaseName: yobasystems/alpine:3.8-amd64
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Dominic Taylor <dominic@yobasystems.co.uk>" architecture="AMD64/x86_64"'
    Name: label
  - Labels:
    - Key: syncthing-version
      Value: '"1.0.1"'
    - Key: alpine-version
      Value: '"3.9.0"'
    - Key: date
      Value: '"11-Feb-2019"'
    Name: label
  - Env:
    - Key: SYNCTHING_VERSION
      Value: 1.0.1
    - Key: SYNCTHING_USERID
      Value: "1027"
    - Key: GOSU_VERSION
      Value: "1.11"
    - Key: STNOUPGRADE
      Value: "true"
    Name: env
  - CmdLine:
    - cd /tmp &&    apk -U add openssl gnupg &&     echo "Getting GPG keys for gosu
      and Syncthing" &&     gpg-agent --daemon &&     gpg --quiet --keyserver hkp://keyserver.ubuntu.com:80  --recv-keys
      37C84554E7E0A261E4F76E1ED26E6ED000654A3E B42F6819007F00F88E364FD4036A9C25BF357DD4
      &&     echo "Getting gosu and its signature" &&     wget -q https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64.asc
      &&     wget -q https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64
      &&    echo "Checking gosu signature" &&     gpg --quiet --verify gosu-amd64.asc
      &&     echo "Installing gosu" &&     chmod +x gosu-amd64 && mv gosu-amd64 /bin/gosu
      &&     echo "Getting Syncthing and its signature" &&     wget -q https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/sha1sum.txt.asc
      &&     wget -q https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/syncthing-linux-amd64-v${SYNCTHING_VERSION}.tar.gz
      &&     echo "Checking gosu sha1 sum signature" &&     gpg --quiet --verify sha1sum.txt.asc
      &&     echo "Checking gosu sha1 checksum" &&     grep syncthing-linux-amd64-v${SYNCTHING_VERSION}.tar.gz
      sha1sum.txt.asc | sha1sum -c - &&     echo "Installing syncthing" &&     tar
      -xzf syncthing-linux-amd64-v${SYNCTHING_VERSION}.tar.gz syncthing-linux-amd64-v${SYNCTHING_VERSION}/syncthing
      &&     mv syncthing-linux-amd64-v${SYNCTHING_VERSION}/syncthing /bin/ &&     echo
      "Cleaning up" &&     rm -rf /tmp/* &&     rm -rf /root/* &&     apk del gnupg
      openssl &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - files/start.sh
    - /srv/start.sh
  - CmdLine:
    - chmod +x /srv/start.sh && mkdir -p /srv/config /srv/data
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 21027/udp
    - "22000"
    - "8384"
  - Name: volume
    Volumes:
    - /srv/data
    - /srv/config
  - CmdLine:
    - /srv/start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: yobasystems/alpine:3.8-amd64
  Name: ""
  Platform: ""
  SourceCode: FROM yobasystems/alpine:3.8-amd64
