MetaArgs: null
Stages:
- BaseName: fedora:20
  Commands:
  - Maintainer: Pulp QE <pulp-list@redhat.com>
    Name: maintainer
  - CmdLine:
    - yum update -y && yum install -y python-ecdsa python-devel python-nose m2crypto
      gcc file dnf python-pip PyYAML python-qpid python-requests python-plumbum python-paramiko
      python-rpyc && yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install gevent
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install stitches
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install requestbin
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pinocchio
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - pulp_auto
    - /src/pulp_auto
  - Chown: ""
    Name: add
    SourcesAndDest:
    - tests
    - /src/tests
  - Chown: ""
    Name: add
    SourcesAndDest:
    - setup.py
    - /src/setup.py
  - CmdLine:
    - pip install --no-index /src/
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /pulp_auto/
  - Name: workdir
    Path: /pulp_auto/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - tests/
    - /pulp_auto/tests
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/geninventory.py
    - /usr/local/bin/geninventory
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker/inventory.yml
    - /pulp_auto/inventory.yml
  - CmdLine:
    - geninventory && nosetests -vs --with-xunit --with-outputsave --save-directory=logs
    Name: cmd
    PrependShell: true
  From:
    Image: fedora:20
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:20
