MetaArgs: null
Stages:
- BaseName: frolvlad/alpine-glibc:alpine-3.8_glibc-2.28
  Commands:
  - Key: ALPINE_ARM_NONE_EABI_BASE_URL
    Name: arg
    Value: '"https://developer.arm.com/-/media/Files/downloads/gnu-rm"'
  - Key: ALPINE_ARM_NONE_EABI_PACKAGE_DATE
    Name: arg
    Value: '"7-2018q2"'
  - Key: ALPINE_ARM_NONE_EABI_PACKAGE_VERSION
    Name: arg
    Value: '"7-2018-q2-update"'
  - Key: ALPINE_ARM_NONE_EABI_PACKAGE_NAME
    Name: arg
    Value: '"gcc-arm-none-eabi-$ALPINE_ARM_NONE_EABI_PACKAGE_VERSION"'
  - Key: ALPINE_ARM_NONE_EABI_PACKAGE_FILENAME
    Name: arg
    Value: '"$ALPINE_ARM_NONE_EABI_PACKAGE_NAME-linux.tar.bz2"'
  - CmdLine:
    - apk add --no-cache --virtual build-dependencies         ca-certificates         openssl         wget
      &&     wget "$ALPINE_ARM_NONE_EABI_BASE_URL/$ALPINE_ARM_NONE_EABI_PACKAGE_DATE/$ALPINE_ARM_NONE_EABI_PACKAGE_FILENAME"
      &&     mkdir /toolchain &&     tar xvf "$ALPINE_ARM_NONE_EABI_PACKAGE_FILENAME"
      -C /toolchain &&     rm "$ALPINE_ARM_NONE_EABI_PACKAGE_FILENAME" &&     apk
      del build-dependencies &&     rm -rf "/toolchain/$ALPINE_ARM_NONE_EABI_PACKAGE_NAME/share/doc"
      &&     apk add --no-cache make=4.2.1-r2
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"/toolchain/${ALPINE_ARM_NONE_EABI_PACKAGE_NAME}/bin:${PATH}"'
    Name: env
  - Name: workdir
    Path: /home
  From:
    Image: frolvlad/alpine-glibc:alpine-3.8_glibc-2.28
  Name: ""
  Platform: ""
  SourceCode: FROM frolvlad/alpine-glibc:alpine-3.8_glibc-2.28
