MetaArgs: null
Stages:
- As: base
  BaseName: debian:stretch-slim
  Commands:
  - CmdLine:
    - "apt-get update \t&& apt-get install -y --no-install-recommends         dumb-init
      \        librtlsdr-dev     && apt-get clean     && rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/dumb-init
    - --
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:stretch-slim
  Name: base
  Platform: ""
  SourceCode: FROM debian:stretch-slim AS base
- As: builder
  BaseName: base
  Commands:
  - Env:
    - Key: MAJVERS
      Value: "2.13"
    Name: env
  - Env:
    - Key: MINVERS
      Value: ".1"
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - "apt-get update \t&& apt-get install -y --no-install-recommends \t    wget \t
      \   ca-certificates"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp/sdrlib
  - CmdLine:
    - wget https://www.sdrplay.com/software/SDRplay_RSP_API-Linux-${MAJVERS}${MINVERS}.run
      &&         export ARCH=`arch` &&         sh ./SDRplay_RSP_API-Linux-${MAJVERS}${MINVERS}.run
      --tar xvf &&         cp ${ARCH}/libmirsdrapi-rsp.so.${MAJVERS} /usr/local/lib/.
      &&         chmod 644 /usr/local/lib/libmirsdrapi-rsp.so.${MAJVERS} &&         ln
      -s /usr/local/lib/libmirsdrapi-rsp.so.${MAJVERS} /usr/local/lib/libmirsdrapi-rsp.so.2
      &&         ln -s /usr/local/lib/libmirsdrapi-rsp.so.2 /usr/local/lib/libmirsdrapi-rsp.so
      &&         cp mirsdrapi-rsp.h /usr/local/include/. &&         chmod 644 /usr/local/include/mirsdrapi-rsp.h
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/lib/dump1090
  - CmdLine:
    - wget -O - https://www.sdrplay.com/software/dump1090_1.3.1.linux.tar.gz | tar
      xvfz - --strip 2
    Name: run
    PrependShell: true
  From:
    Stage:
      Index: 0
      Named: base
  Name: builder
  Platform: ""
  SourceCode: FROM base as builder
- BaseName: base
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/local/bin/
    - /usr/local/bin/
  - CmdLine:
    - "true"
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/local/lib/
    - /usr/local/lib/
  - CmdLine:
    - ldconfig
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/lib/dump1090
  - CmdLine:
    - ./dump1090
    - --dev-sdrplay
    - --mlat
    - --quiet
    - --net
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - 8080/tcp
  - Name: expose
    Ports:
    - 30002/tcp
  - Name: expose
    Ports:
    - 30003/tcp
  - Name: expose
    Ports:
    - 30005/tcp
  From:
    Stage:
      Index: 0
      Named: base
  Name: ""
  Platform: ""
  SourceCode: FROM base
