MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: Ben Origas <borigas@gmail.com>
    Name: maintainer
  - CmdLine:
    - apk add --update ca-certificates curl bash gawk
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker
    - /docker
  - Env:
    - Key: DOMAIN_ARGS
      Value: none
    Name: env
  - Env:
    - Key: INTERVAL
      Value: "60"
    Name: env
  - CmdLine:
    - bash
    - /docker/entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
