MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Starbix"'
    Name: label
  - Env:
    - Key: UID
      Value: "991"
    - Key: GID
      Value: "991"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rootfs
    - /
  - CmdLine:
    - "apk add -U \t\t\t\tnpm \t\t\t\tgit \t\t\t\tsu-exec \t\t\t\ts6 \t\t&& mkdir
      -p /opt \t\t&& cd /opt \t\t&& git clone https://github.com/UnicornTranscoder/UnicornLoadBalancer
      \t\t&& cd UnicornLoadBalancer \t\t&& npm install \t\t&& chmod a+x /usr/local/bin/*
      /etc/s6.d/*/* \t\t&& apk del git \t\t&& rm -rf /tmp/* /var/cache/apk/*"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3001"
  - CmdLine:
    - run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
