MetaArgs: null
Stages:
- BaseName: java:7
  Commands:
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - HelloWorld.java
    - .
  - CmdLine:
    - javac HelloWorld.java
    Name: run
    PrependShell: true
  - CmdLine:
    - java
    - HelloWorld
    Name: cmd
    PrependShell: false
  From:
    Image: java:7
  Name: ""
  Platform: ""
  SourceCode: FROM java:7
