MetaArgs: null
Stages:
- BaseName: openjdk:8
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt-get update && apt-get install -y --no-install-recommends     gcc     python-dev     perl     unzip   &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: MULTIQC_VERSION
      Value: v0.9
    Name: env
  - CmdLine:
    - curl -fsSL https://bootstrap.pypa.io/get-pip.py -o /opt/get-pip.py &&   python
      /opt/get-pip.py &&   rm /opt/get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install git+git://github.com/ewels/MultiQC.git@$MULTIQC_VERSION
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip
    - /tmp/
  - CmdLine:
    - cd /usr/local &&     unzip /tmp/fastqc_*.zip &&     chmod 755 /usr/local/FastQC/fastqc
      &&     ln -s /usr/local/FastQC/fastqc /usr/local/bin/fastqc &&     rm -rf /tmp/fastqc_*.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /import/*
    - /import/
  - Env:
    - Key: INPUT_DIR
      Value: '"."'
    Name: env
  - Env:
    - Key: OUTPUT_DIR
      Value: '"."'
    Name: env
  - Env:
    - Key: BASE_FILE_NAME
      Value: '"fastmultiqc"'
    Name: env
  - Env:
    - Key: TITLE
      Value: '"FastMultiQC"'
    Name: env
  - Env:
    - Key: FASTQ_ENDING
      Value: '"*.fastq.gz"'
    Name: env
  - Env:
    - Key: THREAD_NUM
      Value: "1"
    Name: env
  - CmdLine:
    - bash -c 'source /import/fastmultiqc.sh -i "${INPUT_DIR}" -o "${OUTPUT_DIR}"
      -f "${BASE_FILE_NAME}" -t "${TITLE}" -e "${FASTQ_ENDING}" -p "${THREAD_NUM}"'
    Name: cmd
    PrependShell: true
  From:
    Image: openjdk:8
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8
