MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - CmdLine:
    - apt-get -y update && apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install wget
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --quiet --no-check-certificate -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc
      | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update && apt-get -y install build-essential binutils libproj-dev
      python python-pip git-core python-dev libyaml-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install postgresql-9.4-postgis-2.1 postgresql-contrib postgis libpq-dev
      gdal-bin libgeos-dev libgeos-c1 python-gdal mysql-client libmysqlclient-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install ca-certificates nginx gettext-base
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install uwsgi && mkdir -p /etc/uwsgi/vassals
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "" > /etc/rc.local
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install mysqlclient Django==1.9.2 psycopg2
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - CmdLine:
    - "ln -sf /dev/stdout /var/log/nginx/access.log \t&& ln -sf /dev/stderr /var/log/nginx/error.log"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - launch-nginx.sh
    - /usr/bin/launch-nginx.sh
  - CmdLine:
    - chmod a+x /usr/bin/launch-nginx.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Name: workdir
    Path: /usr/src/app
  - CmdLine:
    - /usr/bin/launch-nginx.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
