MetaArgs: null
Stages:
- BaseName: rabbitmq:3-management-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-healthcheck
    - /usr/local/bin/
  - Health:
      Test:
      - CMD
      - docker-healthcheck
    Name: healthcheck
  From:
    Image: rabbitmq:3-management-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM rabbitmq:3-management-alpine
