MetaArgs: null
Stages:
- BaseName: python:3.5
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - CmdLine:
    - mkdir /code
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /code/
  - CmdLine:
    - pip3 install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://packages.linuxmint.com debian import" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install firefox -y --force-yes
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code/
  From:
    Image: python:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.5
