MetaArgs: null
Stages:
- As: build
  BaseName: ubuntu:xenial
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"https://github.com/senagbe"'
    Name: label
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install build-essential libtool autotools-dev automake pkg-config
      libssl-dev libevent-dev bsdmainutils git cmake libboost-all-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository ppa:bitcoin/bitcoin
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libdb4.8-dev libdb4.8++-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libzmq3-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools
      libprotobuf-dev protobuf-compiler
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone -b "v2.0.0.3" https://github.com/HTMLCOIN/HTMLCOIN --recursive
    Name: run
    PrependShell: true
  - Name: workdir
    Path: HTMLCOIN
  - CmdLine:
    - ./autogen.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - ./configure
    Name: run
    PrependShell: true
  - CmdLine:
    - make -j2
    Name: run
    PrependShell: true
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /HTMLCOIN/src/htmlcoind
    - /bin/htmlcoind
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /HTMLCOIN/src/htmlcoin-tx
    - /bin/htmlcoin-tx
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /HTMLCOIN/src/htmlcoin-cli
    - /bin/htmlcoin-cli
  - Labels:
    - Key: version
      Value: '"2.0.0.3"'
    Name: label
  - Name: expose
    Ports:
    - "4889"
  - Name: expose
    Ports:
    - "14889"
  - CmdLine:
    - /bin/htmlcoind
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -help
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: build
  Platform: ""
  SourceCode: FROM ubuntu:xenial as build
