MetaArgs: null
Stages:
- BaseName: ssdit/adventist-asia-web-base:latest
  Commands:
  - Key: BUILD_ASSETS
    Name: arg
    Value: null
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - php.ini
    - /usr/local/etc/php/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /var/www/html
  - Name: workdir
    Path: /var/www/html
  - CmdLine:
    - mkdir /var/www/html/site/assets/sessions    /var/www/html/site/assets/logs    /var/www/html/site/assets/files    /var/www/html/site/assets/cache    &&
      chown -R www-data:www-data *    && chmod -R o+x *
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn install && yarn build;
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex;    if [ -n "$BUILD_ASSETS" ]; then       yarn install && yarn build;    fi;
    Name: run
    PrependShell: true
  From:
    Image: ssdit/adventist-asia-web-base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ssdit/adventist-asia-web-base:latest
