MetaArgs: null
Stages:
- BaseName: python:2-alpine
  Commands:
  - Maintainer: Henri Dwyer <henri@dwyer.io>
    Name: maintainer
  - Name: volume
    Volumes:
    - /certs
  - Name: volume
    Volumes:
    - /etc/letsencrypt
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - apk add --no-cache --virtual .build-deps linux-headers gcc musl-dev  && apk
      add --no-cache libffi-dev openssl-dev dialog  && pip install certbot  && apk
      del .build-deps  && mkdir /scripts
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - crontab
    - /etc/crontabs
  - CmdLine:
    - crontab /etc/crontabs/crontab
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./scripts/
    - /scripts
  - CmdLine:
    - chmod +x /scripts/run_certbot.sh
    Name: run
    PrependShell: true
  - CmdLine: null
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - crond
    - -f
    Name: cmd
    PrependShell: false
  From:
    Image: python:2-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:2-alpine
