MetaArgs: null
Stages:
- BaseName: rust:latest
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/udpt
  - Name: workdir
    Path: /usr/src/udpt
  - CmdLine:
    - cargo build --release -j4
    Name: run
    PrependShell: true
  - CmdLine:
    - target/release/udpt-rs
    - -c
    - /usr/src/udpt/udpt.toml
    Name: cmd
    PrependShell: false
  From:
    Image: rust:latest
  Name: ""
  Platform: ""
  SourceCode: FROM rust:latest
