MetaArgs: null
Stages:
- BaseName: centos:latest
  Commands:
  - Maintainer: Will Rowe <will.rowe@stfc.ac.uk>
    Name: maintainer
  - CmdLine:
    - yum update && yum group install -y "Development Tools" && yum -y clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - "yum install -y \twget \topenmpi \topenmpi-devel \tglibc-devel.i686 \tlibgcc.i686
      \  libstdc++-devel.i686 \tyum -y clean all"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp && \twget https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
      && \ttar -C /usr/local -xzf go1.8.3.linux-amd64.tar.gz && \trm go1.8.3.linux-amd64.tar.gz"
    Name: run
    PrependShell: true
  - Env:
    - Key: GOLANG_VERSION
      Value: 1.8.3
    Name: env
  - CmdLine:
    - "export PATH=\"/usr/local/go/bin:/usr/lib64/openmpi/bin:$PATH\" && \tgo version"
    Name: run
    PrependShell: true
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - Env:
    - Key: PATH
      Value: $GOPATH/bin:/usr/local/go/bin:/usr/lib64/openmpi/bin:$PATH
    Name: env
  - Env:
    - Key: C_INCLUDE_PATH
      Value: /usr/include/openmpi-x86_64
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/lib64/openmpi/lib
    Name: env
  - Env:
    - Key: CGO_LDFLAGS
      Value: '''-L/usr/lib64/openmpi/lib -lmpi'''
    Name: env
  - CmdLine:
    - mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $GOPATH
  From:
    Image: centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM centos:latest
