MetaArgs: null
Stages:
- BaseName: golang
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /go/src/calpi
  - CmdLine:
    - go get -u github.com/aws/aws-sdk-go
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /go/src/calpi &&    go build &&    go install
    Name: run
    PrependShell: true
  - CmdLine:
    - calpi
    Name: cmd
    PrependShell: true
  From:
    Image: golang
  Name: ""
  Platform: ""
  SourceCode: FROM golang
