MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Apache BookKeeper <dev@bookkeeper.apache.org>
    Name: maintainer
  - Key: BK_VERSION
    Name: arg
    Value: 4.9.0
  - Key: DISTRO_NAME
    Name: arg
    Value: bookkeeper-server-${BK_VERSION}-bin
  - Key: DISTRO_URL
    Name: arg
    Value: https://archive.apache.org/dist/bookkeeper/bookkeeper-${BK_VERSION}/${DISTRO_NAME}.tar.gz
  - Env:
    - Key: BOOKIE_PORT
      Value: "3181"
    Name: env
  - Name: expose
    Ports:
    - $BOOKIE_PORT
  - Env:
    - Key: BK_USER
      Value: bookkeeper
    Name: env
  - Env:
    - Key: BK_HOME
      Value: /opt/bookkeeper
    Name: env
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/jre-1.8.0
    Name: env
  - CmdLine:
    - set -x     && adduser "${BK_USER}"     && yum install -y java-1.8.0-openjdk-headless
      wget bash python sudo     && mkdir -pv /opt     && cd /opt     && wget -q "${DISTRO_URL}"     &&
      wget -q "${DISTRO_URL}.asc"     && wget -q "${DISTRO_URL}.sha512"     && sha512sum
      -c ${DISTRO_NAME}.tar.gz.sha512     && wget https://dist.apache.org/repos/dist/release/bookkeeper/KEYS     &&
      gpg --import KEYS     && gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz"     &&
      tar -xzf "$DISTRO_NAME.tar.gz"     && mv bookkeeper-server-${BK_VERSION}/ /opt/bookkeeper/     &&
      rm -rf "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz.sha512"     &&
      yum remove -y wget     && yum clean all
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/bookkeeper
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts
    - /opt/bookkeeper/scripts
  - CmdLine:
    - chmod +x -R /opt/bookkeeper/scripts/
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    - /opt/bookkeeper/scripts/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - bookie
    Name: cmd
    PrependShell: false
  - Health:
      Interval: 10000000000
      Test:
      - CMD-SHELL
      - /bin/bash /opt/bookkeeper/scripts/healthcheck.sh
      Timeout: 60000000000
    Name: healthcheck
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
