MetaArgs: null
Stages:
- BaseName: node:6.0.0
  Commands:
  - Name: workdir
    Path: /jagp-techu
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /jagp-techu
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - npm start
    Name: cmd
    PrependShell: true
  From:
    Image: node:6.0.0
  Name: ""
  Platform: ""
  SourceCode: FROM node:6.0.0
