MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/kube-controller-manager:v1.16.2
  Commands: null
  From:
    Image: k8s.gcr.io/kube-controller-manager:v1.16.2
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/kube-controller-manager:v1.16.2
