MetaArgs: null
Stages:
- BaseName: postgres:10.3-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"George Kutsurua <g.kutsurua@gmail.com>"'
    Name: label
  - Key: postgis_version
    Name: arg
    Value: 2.4.4
  - Key: postgis_sha256
    Name: arg
    Value: 0663efb589210d5048d95c817e5cf29552ec8180e16d4c6ef56c94255faca8c2
  - CmdLine:
    - set -ex         && apk add --no-cache --virtual .fetch-deps         ca-certificates         openssl         tar         &&
      wget -O postgis.tar.gz "https://download.osgeo.org/postgis/source/postgis-$postgis_version.tar.gz"     &&
      echo "$postgis_sha256 *postgis.tar.gz" | sha256sum -c -     && mkdir -p /usr/src/postgis     &&
      tar         --extract         --file postgis.tar.gz         --directory /usr/src/postgis         --strip-components
      1     && rm postgis.tar.gz         && apk add --no-cache --virtual .build-deps         autoconf         automake         g++         json-c-dev         libtool         libxml2-dev         make         perl         &&
      apk add --no-cache --virtual .build-deps-testing         --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing         gdal-dev         geos-dev         proj4-dev         protobuf-c-dev     &&
      cd /usr/src/postgis     && ./autogen.sh     && ./configure     && make     &&
      make install     && apk add --no-cache --virtual .postgis-rundeps         json-c     &&
      apk add --no-cache --virtual .postgis-rundeps-testing         --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing         geos         gdal         proj4         protobuf-c     &&
      cd /     && rm -rf /usr/src/postgis     && apk del .fetch-deps .build-deps .build-deps-testing
    Name: run
    PrependShell: true
  - Env:
    - Key: POSTGIS_VERSION
      Value: $postgis_version
    Name: env
  - Env:
    - Key: POSTGIS_SHA256
      Value: $postgis_sha256
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./initdb-postgis.sh
    - /docker-entrypoint-initdb.d/postgis.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./update-postgis.sh
    - /usr/local/bin
  From:
    Image: postgres:10.3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:10.3-alpine
