MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.sh
    - /install.sh
  - CmdLine:
    - /install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/supervisord
    - -n
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apt-get purge leafpad
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/* /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
