MetaArgs: null
Stages:
- BaseName: apache/nifi:1.9.2
  Commands:
  - Name: workdir
    Path: /opt/nifi/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./drivers
    - ./drivers
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./user-scripts
    - ./user-scripts
  - Name: workdir
    Path: /opt/nifi/nifi-current/conf/templates/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./user-templates
    - ./
  - Name: workdir
    Path: /opt/nifi/nifi-current/conf/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./conf/bootstrap.conf
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./conf/nifi.properties
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./conf/zookeeper.properties
    - ./
  - Name: workdir
    Path: /opt/nifi/nifi-current/
  From:
    Image: apache/nifi:1.9.2
  Name: ""
  Platform: ""
  SourceCode: FROM apache/nifi:1.9.2
