MetaArgs: null
Stages:
- BaseName: gogs/gogs:latest
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - gogs-setup
    - /app/gogs/docker/s6/gogs/setup
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ssh-setup
    - /app/gogs/docker/s6/openssh/setup
  From:
    Image: gogs/gogs:latest
  Name: ""
  Platform: ""
  SourceCode: "FROM\tgogs/gogs:latest"
