MetaArgs: null
Stages:
- BaseName: paulwoelfel/docker-gcloud
  Commands:
  - CmdLine:
    - "apt-get update && \tapt-get -y upgrade && \tapt-get -y install \tsudo \t&&
      \trm -rf /var/lib/apt/lists/* && \tcurl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
      | bash"
    Name: run
    PrependShell: true
  From:
    Image: paulwoelfel/docker-gcloud
  Name: ""
  Platform: ""
  SourceCode: FROM paulwoelfel/docker-gcloud
