MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/kube-controller-manager-amd64:v1.12.2
  Commands:
  - Maintainer: rufin89@sina.com
    Name: maintainer
  From:
    Image: gcr.io/google_containers/kube-controller-manager-amd64:v1.12.2
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/kube-controller-manager-amd64:v1.12.2
