MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Yongbok Kim <ruo91@yongbok.net>
    Name: maintainer
  - CmdLine:
    - apt-get update ; apt-get install -y curl build-essential supervisor
    Name: run
    PrependShell: true
  - Env:
    - Key: SRC_DIR
      Value: /opt
    Name: env
  - Env:
    - Key: REDIS_VERSION
      Value: stable
    Name: env
  - CmdLine:
    - cd $SRC_DIR && curl -LO http://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz  &&
      tar xzf redis-$REDIS_VERSION.tar.gz && mv redis-$REDIS_VERSION redis && cd redis
      && make  && ln -s $SRC_DIR/redis/src/redis-cli /usr/sbin/redis-cli  && ln -s
      $SRC_DIR/redis/src/redis-server /usr/sbin/redis-server  && rm -f $SRC_DIR/redis-$REDIS_VERSION.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/redis
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/redis.conf
    - /etc/redis/redis.conf
  - CmdLine:
    - unset SRC_DIR REDIS_VERSION
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/log/supervisor
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - Name: expose
    Ports:
    - "6379"
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM     ubuntu:14.04
