MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Key: UID
    Name: arg
    Value: "1001"
  - Key: GID
    Name: arg
    Value: "1001"
  - CmdLine:
    - apt-get update && apt-get -y upgrade && apt-get install -y nodejs npm git &&
      npm install -g bower && ln -s /usr/bin/nodejs /usr/bin/node
    Name: run
    PrependShell: true
  - CmdLine:
    - 'export uid=$UID gid=$GID &&     mkdir -p /home/developer/project &&     echo
      "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd
      &&     echo "developer:x:${uid}:" >> /etc/group &&     echo "developer ALL=(ALL)
      NOPASSWD: ALL" > /etc/sudoers.d/developer &&     chmod 0440 /etc/sudoers.d/developer
      &&     chown ${uid}:${gid} -R /home/developer'
    Name: run
    PrependShell: true
  - Name: user
    User: developer
  - Env:
    - Key: HOME
      Value: /home/developer
    Name: env
  - Name: workdir
    Path: /home/developer/project
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
