MetaArgs: null
Stages:
- BaseName: node:8.11.1-alpine
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /tmp
  - CmdLine:
    - /bin/sh -c 'cd /tmp && npm install && npm install -g typescript && npm run build
      && mv ./dist/* /app/ && mv ./node_modules /app/ && rm -rf /tmp'
    Name: run
    PrependShell: true
  From:
    Image: node:8.11.1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.11.1-alpine
