MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: Doğan Aydın <dogan1aydin@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get install -y nodejs npm git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/sdelements/lets-chat.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: lets-chat
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - rm settings.js.sample
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./settings.js.sample
    - lets-chat/settings.js
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - ./app.js
    Name: cmd
    PrependShell: false
  - CmdLine:
    - /usr/bin/nodejs
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
