MetaArgs: null
Stages:
- BaseName: jenkins:latest
  Commands:
  - Maintainer: BTower labz@btower.net
    Name: maintainer
  - Labels:
    - Key: Name
      Value: '"docker-sca-ci-master"'
    Name: label
  - Labels:
    - Key: Vendor
      Value: '"btower-labz"'
    Name: label
  - Labels:
    - Key: Version
      Value: '"1.0.0"'
    Name: label
  - Labels:
    - Key: Description
      Value: '"Provides sca ci master"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y apt-utils && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'debconf debconf/frontend select Dialog' | debconf-set-selections
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - getplugins.sh
    - /tmp/getplugins.sh
  - CmdLine:
    - chmod ugo+x /tmp/getplugins.sh
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - executors.groovy
    - /usr/share/jenkins/ref/init.groovy.d/executors.groovy
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sca-admin.groovy
    - /usr/share/jenkins/ref/init.groovy.d/sca-admin.groovy
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sca-view.groovy
    - /usr/share/jenkins/ref/init.groovy.d/sca-view.groovy
  - CmdLine:
    - /tmp/getplugins.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - log.properties
    - /usr/share/jenkins/log.properties
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "50000"
  - Env:
    - Key: JAVA_OPTS
      Value: '"-Djava.util.logging.config.file=/usr/share/jenkins/log.properties -Djenkins.install.runSetupWizard=false"'
    Name: env
  - Name: user
    User: root
  - CmdLine:
    - apt-get update && apt-get install -y apt-utils
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  From:
    Image: jenkins:latest
  Name: ""
  Platform: ""
  SourceCode: FROM jenkins:latest
