MetaArgs: null
Stages:
- BaseName: jenkinsci/jnlp-slave:latest
  Commands:
  - Labels:
    - Key: description
      Value: '"Jenkins Slave image with JDK8, Maven and M2 Settings to connect to
        nexus"'
    - Key: maintainer
      Value: '"sergief@users.noreply.github.com"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - apt-get update &&   apt-get install -y     openjdk-8-jdk     maven     git     gettext-base
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - settings.xml.tmpl
    - /home/jenkins/settings.xml.tmpl
  - Env:
    - Key: NEXUS_USERNAME
      Value: '"\${env.M2_CREDENTIALS_USR}"'
    Name: env
  - Env:
    - Key: NEXUS_PASSWORD
      Value: '"\${env.M2_CREDENTIALS_PSW}"'
    Name: env
  - Env:
    - Key: NEXUS_MAVEN_PUBLIC_URL
      Value: '"\${env.M2_MIRROR_CENTRAL}"'
    Name: env
  - CmdLine:
    - envsubst < /home/jenkins/settings.xml.tmpl > /etc/maven/settings.xml &&   rm
      /home/jenkins/settings.xml.tmpl
    Name: run
    PrependShell: true
  - Name: user
    User: jenkins
  From:
    Image: jenkinsci/jnlp-slave:latest
  Name: ""
  Platform: ""
  SourceCode: FROM jenkinsci/jnlp-slave:latest
