MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Thomas VIAL
    Name: maintainer
  - CmdLine:
    - "DEBIAN_FRONTEND=noninteractive apt-get update -q --fix-missing && \tapt-get
      -y upgrade && \tapt-get -y install --no-install-recommends \tpostfix dovecot-core
      dovecot-imapd dovecot-pop3d dovecot-sieve dovecot-managesieved gamin amavisd-new
      spamassassin razor pyzor libsasl2-modules \tclamav clamav-daemon libnet-dns-perl
      libmail-spf-perl bzip2 file gzip p7zip unzip arj rsyslog     opendkim opendkim-tools
      opendmarc curl fail2ban ed iptables && \tcurl -sk http://neuro.debian.net/lists/trusty.de-m.libre
      > /etc/apt/sources.list.d/neurodebian.sources.list && \tapt-key adv --recv-keys
      --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9 && \tapt-get update -q --fix-missing
      && apt-get -y upgrade fail2ban &&     apt-get autoclean && rm -rf /var/lib/apt/lists/*
      &&     rm -rf /usr/share/locale/* && rm -rf /usr/share/man/* && rm -rf /usr/share/doc/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/include_try \/usr\/share\/dovecot\/protocols\.d/include_try \/etc\/dovecot\/protocols\.d/g'
      /etc/dovecot/dovecot.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -e 's/#mail_plugins = \$mail_plugins/mail_plugins = \$mail_plugins sieve/g'
      /etc/dovecot/conf.d/15-lda.conf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/dovecot/auth-passwdfile.inc
    - /etc/dovecot/conf.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/dovecot/??-*.conf
    - /etc/dovecot/conf.d/
  - CmdLine:
    - sed -i -r 's/^(CRON|ENABLED)=0/\1=1/g' /etc/default/spamassassin
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -r 's/#(@|   \\%)bypass/\1bypass/g' /etc/amavis/conf.d/15-content_filter_mode
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser clamav amavis && adduser amavis clamav
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -u 5000 -d /home/docker -s /bin/bash -p $(echo docker | openssl passwd
      -1 -stdin) docker
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/fail2ban/jail.conf
    - /etc/fail2ban/jail.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/fail2ban/filter.d/dovecot.conf
    - /etc/fail2ban/filter.d/dovecot.conf
  - CmdLine:
    - echo "ignoreregex =" >> /etc/fail2ban/filter.d/postfix-sasl.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - (crontab; echo "0 0,6,12,18 * * * /usr/bin/freshclam --quiet") | sort - | uniq
      - | crontab -
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 644 /etc/clamav/freshclam.conf && freshclam
    Name: run
    PrependShell: true
  - Name: user
    User: amavis
  - CmdLine:
    - razor-admin -create && razor-admin -register && pyzor discover
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/opendkim/opendkim.conf
    - /etc/opendkim.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/opendkim/default-opendkim
    - /etc/default/opendkim
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/opendmarc/opendmarc.conf
    - /etc/opendmarc.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/opendmarc/default-opendmarc
    - /etc/default/opendmarc
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/postfix/main.cf
    - target/postfix/master.cf
    - /etc/postfix/
  - CmdLine:
    - sed -i -r "/^#?compress/c\compress\ncopytruncate" /etc/logrotate.conf &&   mkdir
      -p /var/log/mail && chown syslog:root /var/log/mail &&   touch /var/log/mail/clamav.log
      && chown -R clamav:root /var/log/mail/clamav.log &&   touch /var/log/mail/freshclam.log
      &&  chown -R clamav:root /var/log/mail/freshclam.log &&   sed -i -r 's|/var/log/mail|/var/log/mail/mail|g'
      /etc/rsyslog.d/50-default.conf &&   sed -i -r 's|LogFile /var/log/clamav/|LogFile
      /var/log/mail/|g' /etc/clamav/clamd.conf &&   sed -i -r 's|UpdateLogFile /var/log/clamav/|UpdateLogFile
      /var/log/mail/|g' /etc/clamav/freshclam.conf &&   sed -i -r 's|/var/log/clamav|/var/log/mail|g'
      /etc/logrotate.d/clamav-daemon &&   sed -i -r 's|/var/log/clamav|/var/log/mail|g'
      /etc/logrotate.d/clamav-freshclam &&   sed -i -r 's|/var/log/mail|/var/log/mail/mail|g'
      /etc/logrotate.d/rsyslog
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -s https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem > /etc/ssl/certs/lets-encrypt-x1-cross-signed.pem
      &&   curl -s https://letsencrypt.org/certs/lets-encrypt-x2-cross-signed.pem
      > /etc/ssl/certs/lets-encrypt-x2-cross-signed.pem
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - target/bin/generate-ssl-certificate
    - target/bin/generate-dkim-config
    - target/bin/addmailuser
    - target/bin/delmailuser
    - target/start-mailserver.sh
    - /usr/local/bin/
  - CmdLine:
    - chmod +x /usr/local/bin/*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "110"
    - "143"
    - "25"
    - "4190"
    - "587"
    - "993"
    - "995"
  - CmdLine:
    - /usr/local/bin/start-mailserver.sh
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
