MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Maintainer: Derrick Oswald <derrick.oswald@gmail.com>
    Name: maintainer
  - CmdLine:
    - locale-gen en_US.UTF-8 &&     echo 'LANG="en_US.UTF-8"' > /etc/default/locale
      &&     sed --in-place 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list &&     apt-get
      update &&     apt-get install --assume-yes --force-yes     apt-transport-https     build-essential     curl     git     software-properties-common     wget
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive &&     apt-get install --assume-yes --force-yes     erlang-dev     erlang-manpages     erlang-base-hipe     erlang-eunit     erlang-nox     erlang-xmerl     erlang-inets     libmozjs185-dev     libicu-dev     libcurl4-gnutls-dev     libtool
      &&     cd /tmp &&     wget http://mirror.sdunix.com/apache/couchdb/source/1.6.0/apache-couchdb-1.6.0.tar.gz
      &&     tar xzvf apache-couchdb-1.6.0.tar.gz &&     cd apache-couchdb-1.6.0 &&     ./configure
      &&     make &&     make install &&     sed --expression 's/^bind_address = .*$/bind_address
      = 0.0.0.0/' --in-place /usr/local/etc/couchdb/default.ini &&     sed --expression
      's/^database_dir = .*$/database_dir = \/data/' --in-place /usr/local/etc/couchdb/default.ini
      &&     sed --expression 's/^view_index_dir = .*$/view_index_dir = \/data/' --in-place
      /usr/local/etc/couchdb/default.ini &&     apt-get clean && rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install --assume-yes --force-yes     g++     make &&     curl -sL https://deb.nodesource.com/setup_0.12
      | sudo bash -  &&     apt-get install --assume-yes --force-yes     nodejs &&     npm
      config set prefix '/usr/local' &&     npm install nano
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir --parents /usr/local/etc/deluge &&     apt-get update &&     apt-get install
      --assume-yes --force-yes     deluged     deluge-webui
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_DOWNLOAD_URL
      Value: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz
    Name: env
  - Env:
    - Key: JAVA_INSTALLATION_DIR
      Value: /opt
    Name: env
  - CmdLine:
    - 'curl --location "$JAVA_DOWNLOAD_URL" --header "Cookie: oraclelicense=accept-securebackup-cookie;
      gpw_e24=Dockerfile" | tar --extract --gzip --directory=$JAVA_INSTALLATION_DIR
      &&     ln --symbolic $JAVA_INSTALLATION_DIR/jdk1.8.0_60/bin/* /usr/local/bin/'
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: $JAVA_INSTALLATION_DIR/jdk1.8.0_60
    Name: env
  - CmdLine:
    - apt-get install --assume-yes --force-yes     maven2 &&     git clone https://github.com/rnewson/couchdb-lucene.git
      &&     cd couchdb-lucene &&     mvn &&     cd .. &&     unzip couchdb-lucene/target/couchdb-lucene-1.1.0-SNAPSHOT-dist.zip
      &&     rm -rf /couchdb-lucene &&     mv couchdb-lucene-1.1.0-SNAPSHOT couchdb-lucene
      &&     rm -rf /root/.m2
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - scripts
    - /scripts
  - CmdLine:
    - chmod +x /scripts/*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - touch /.firstrun
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config/deluge
    - /usr/local/etc/deluge/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - logs/deluge
    - /etc/logrotate.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - js
    - /js
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Name: workdir
    Path: /root
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "5984"
  - Name: expose
    Ports:
    - "8112"
  - Name: volume
    Volumes:
    - /data
    - /usr/local/var/log/couchdb
    - /usr/local/etc/couchdb
  - Name: volume
    Volumes:
    - /torrents
    - /usr/local/var/log/deluge
    - /usr/local/etc/deluge
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
