MetaArgs: null
Stages:
- BaseName: confluentinc/cp-kafka-connect:5.2.1
  Commands:
  - Env:
    - Key: CONNECT_PLUGIN_PATH
      Value: '"/usr/share/java,/usr/share/confluent-hub-components"'
    Name: env
  - CmdLine:
    - confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest
    Name: run
    PrependShell: true
  From:
    Image: confluentinc/cp-kafka-connect:5.2.1
  Name: ""
  Platform: ""
  SourceCode: FROM confluentinc/cp-kafka-connect:5.2.1
