MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Env:
    - Key: PUID
      Value: "1000"
    Name: env
  - Env:
    - Key: GUID
      Value: "1000"
    Name: env
  - CmdLine:
    - apk add -v --update     bash     zip     python     py-pip &&     pip install
      --upgrade awscli s3cmd &&     apk -v --purge del py-pip &&     rm /var/cache/apk/*
    Name: run
    PrependShell: true
  - Env:
    - Key: APP_ROOT
      Value: /var/www/html
    Name: env
  - Name: volume
    Volumes:
    - $APP_ROOT
  - Name: workdir
    Path: $APP_ROOT
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start.sh
    - /start.sh
  - CmdLine:
    - chmod 755 /start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
