MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.9.2-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"<easylo@users.noreply.github.com>"'
    Name: label
  - Env:
    - Key: PATH
      Value: /go/bin:/usr/local/go/bin:$PATH
    Name: env
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - Env:
    - Key: CGO_ENABLED
      Value: "0"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - $GOPATH/src/github.com/easylo/screenshots-cron
  - Name: workdir
    Path: $GOPATH/src/github.com/easylo/screenshots-cron
  - CmdLine:
    - apk add --update --no-cache        make        git        ca-certificates
    Name: run
    PrependShell: true
  - CmdLine:
    - make build
    Name: run
    PrependShell: true
  From:
    Image: golang:1.9.2-alpine
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.9.2-alpine as builder
- BaseName: debian:stretch-slim
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/easylo/screenshots-cron/screenshots-cron
    - /bin/screenshots-cron
  - CmdLine:
    - apt-get update &&  apt-get install -y libfontconfig ca-certificates imagemagick
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./lib/phantomjs
    - /bin/phantomjs
  - CmdLine:
    - mkdir -p /var/example
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./example/capture.html
    - /var/example/capture.html
  - CmdLine:
    - chmod a+x /bin/phantomjs
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/screenshots-cron
    Name: cmd
    PrependShell: false
  From:
    Image: debian:stretch-slim
  Name: ""
  Platform: ""
  SourceCode: FROM  debian:stretch-slim
