MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Labels:
    - Key: Name
      Value: docker-laravel
    - Key: Version
      Value: 0.0.1
    Name: label
  - Maintainer: vudao <yoochunvn@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y update && apt-get install -y     php-fpm php-mysql
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /Voloume/Data/docker/laravel
  - Name: workdir
    Path: '''/var/www/html'''
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php7-fpm.0
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
