MetaArgs: null
Stages:
- BaseName: tensorflow/tensorflow:latest-py3
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app/requirements.txt
  - Name: workdir
    Path: /app
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y &&     apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/tensorflow/models.git &&    cp models/research/audioset/*
      . &&    rm -r models
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl ffmpeg
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -O https://storage.googleapis.com/audioset/vggish_model.ckpt
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -O https://storage.googleapis.com/audioset/vggish_pca_params.npz
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install boto3
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade firebase-admin
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - python
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - app.py
    Name: cmd
    PrependShell: false
  From:
    Image: tensorflow/tensorflow:latest-py3
  Name: ""
  Platform: ""
  SourceCode: FROM tensorflow/tensorflow:latest-py3
