MetaArgs: null
Stages:
- BaseName: php:7.2-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: Ryuichi Tanaka <mapserver2007@gmail.com>
    Name: label
  - CmdLine:
    - apk add --update git build-base autoconf   && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug-2.6.0   && echo "zend_extension=$(find /usr/local/lib/php/extensions/
      -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini   && echo "xdebug.remote_enable=on"
      >> /usr/local/etc/php/conf.d/xdebug.ini   && docker-php-ext-enable xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - apk del git autoconf build-base   && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /workspace
  From:
    Image: php:7.2-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2-alpine
