MetaArgs: null
Stages:
- BaseName: library/wordpress:4-php7.1-apache
  Commands:
  - Labels:
    - Key: org.freenas.interactive
      Value: '"false"'
    - Key: org.freenas.version
      Value: '"1.0.1"'
    - Key: org.freenas.upgradeable
      Value: '"true"'
    - Key: org.freenas.expose-ports-at-host
      Value: '"true"'
    - Key: org.freenas.autostart
      Value: '"true"'
    - Key: org.freenas.port-mappings
      Value: '"80:8888/tcp,443:4433/tcp"'
    - Key: org.freenas.settings
      Value: "\"[\t\t\t\t\t          {\t\t\t\t\t\t\t              \\\"env\\\": \\\"WORDPRESS_DB_HOST\\\",\t\t\t
        \             \\\"descr\\\": \\\"SQL DB IP Address\\\",\t\t\t              \\\"optional\\\":
        false\t\t\t\t\t  },\t\t\t\t\t\t\t          {\t\t\t\t\t\t\t              \\\"env\\\":
        \\\"WORDPRESS_DB_USER\\\",\t\t\t              \\\"descr\\\": \\\"SQL DB Username\\\",\t\t\t
        \             \\\"optional\\\": false\t\t\t\t\t  },\t\t\t\t\t\t\t          {\t\t\t\t\t\t\t
        \             \\\"env\\\": \\\"WORDPRESS_DB_PASSWORD\\\",\t\t              \\\"descr\\\":
        \\\"SQL DB Password\\\",\t\t\t              \\\"optional\\\": false\t\t\t\t\t
        \ },\t\t\t\t\t\t\t          {\t\t\t\t\t\t\t              \\\"env\\\": \\\"WORDPRESS_DB_NAME\\\",\t\t\t
        \             \\\"descr\\\": \\\"SQL DB Name\\\",\t\t\t              \\\"optional\\\":
        true\t\t\t\t\t  },\t\t\t\t\t\t\t          {\t\t\t\t\t\t\t              \\\"env\\\":
        \\\"WORDPRESS_TABLE_PREFIX\\\",\t\t              \\\"descr\\\": \\\"SQL Table
        Prefix\\\",\t\t\t              \\\"optional\\\": true\t\t\t\t\t  }\t\t\t\t\t\t\t
        \     ]\""
    Name: label
  From:
    Image: library/wordpress:4-php7.1-apache
  Name: ""
  Platform: ""
  SourceCode: FROM library/wordpress:4-php7.1-apache
