MetaArgs: null
Stages:
- As: node-builder
  BaseName: node:12-buster
  Commands:
  - Name: workdir
    Path: /build
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package-lock.json
    - tsconfig.json
    - ./
  - CmdLine:
    - npm ci
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - source
    - source
  - CmdLine:
    - npx tsc
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf node_modules && npm ci --production
    Name: run
    PrependShell: true
  From:
    Image: node:12-buster
  Name: node-builder
  Platform: ""
  SourceCode: FROM node:12-buster AS node-builder
- As: rslsync
  BaseName: resilio/sync
  Commands: null
  From:
    Image: resilio/sync
  Name: rslsync
  Platform: ""
  SourceCode: FROM resilio/sync AS rslsync
- BaseName: node:12-buster
  Commands:
  - Name: workdir
    Path: /app
  - Name: volume
    Volumes:
    - /app/tmp
  - Name: volume
    Volumes:
    - /var/lib/resilio-sync
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - CmdLine:
    - apt-get update && apt-get -y --no-install-recommends install ffmpeg && rm -rf
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: rslsync
    Name: copy
    SourcesAndDest:
    - /usr/bin/rslsync
    - /usr/bin/rslsync
  - Chown: ""
    From: node-builder
    Name: copy
    SourcesAndDest:
    - /build/node_modules
    - ./node_modules
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - resilio-config.json
    - ./
  - Chown: ""
    From: node-builder
    Name: copy
    SourcesAndDest:
    - /build/dist
    - ./
  - CmdLine:
    - node index.js
    Name: cmd
    PrependShell: true
  From:
    Image: node:12-buster
  Name: ""
  Platform: ""
  SourceCode: FROM node:12-buster
