MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: Guilherme Rezende <guilhermebr@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y build-essential libpq-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python python-dev python-setuptools
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install psycopg2
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install opps
    Name: run
    PrependShell: true
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
