MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Name: workdir
    Path: /build
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - bash install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -cvzf kong-dep-1.4.0.tgz openresty-build-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - ./upload kong-dep-1.4.0.tgz kong-dep-1.4.0.tgz
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
