MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y procps wget net-tools cron && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /matrix
  - CmdLine:
    - cd /matrix && wget http://manfile.qpm.xin/gman http://manfile.qpm.xin/MANGenesis.json
      http://manfile.qpm.xin/man.json && chmod a+x gman
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /matrix/logCleanup /etc/cron.daily/
    Name: run
    PrependShell: true
  - CmdLine:
    - /matrix/nodeConfig.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
