MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y nodejs-legacy npm
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g capto wait-for-mongo
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - launcher.sh
    - /launcher.sh
  - CmdLine:
    - '"/launcher.sh"'
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
