MetaArgs: null
Stages:
- BaseName: nginx:1.16-alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - naproxy.conf
    - /etc/nginx/naproxy.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /docker-entrypoint.sh
  - CmdLine:
    - apk add --no-cache bash && chmod +x /docker-entrypoint.sh
    Name: run
    PrependShell: true
  - Name: stopsignal
    Signal: SIGTERM
  - CmdLine:
    - /docker-entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:1.16-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:1.16-alpine
