MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Jonas Finnemann Jensen <jopsen@gmail.com>
    Name: maintainer
  - Env:
    - Key: NODE_VERSION
      Value: 0.12.4
    Name: env
  - Env:
    - Key: NPM_VERSION
      Value: 2.10.1
    Name: env
  - Env:
    - Key: DOCKER_VERSION
      Value: 18.06.0~ce~3-0~ubuntu
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y apt-transport-https
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    Name: run
    PrependShell: true
  - CmdLine:
    - sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty
      stable"   > /etc/apt/sources.list.d/docker.list'
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y --no-install-recommends     curl     ca-certificates     docker-ce=$DOCKER_VERSION     iptables
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -SL "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
      |     tar xz -C /usr/local --strip-components=1
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /opt/dind-service
  - Name: workdir
    Path: /opt/dind-service
  - CmdLine:
    - npm install --production          && npm cache clear          && chmod +x ./entrypoint.sh             ;
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/docker
  - Env:
    - Key: PORT
      Value: "2375"
    Name: env
  - Name: expose
    Ports:
    - "2375"
  - Env:
    - Key: SOCKET_PATH
      Value: /opt/dind-service/run/docker.sock
    Name: env
  - Name: volume
    Volumes:
    - /opt/dind-service/run
  - Env:
    - Key: LOG
      Value: pipe
    Name: env
  - Env:
    - Key: DEBUG
      Value: ''''''
    Name: env
  - Expression: echo "If you build from this image you doing something wrong."             exit
      1;
    Name: onbuild
  - CmdLine:
    - ./entrypoint.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
