MetaArgs: null
Stages:
- BaseName: hypoport/httpd-cgi
  Commands:
  - Maintainer: Hypoport
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - cgi-bin/metrics
    - /usr/local/apache2/cgi-bin/
  From:
    Image: hypoport/httpd-cgi
  Name: ""
  Platform: ""
  SourceCode: FROM hypoport/httpd-cgi
