MetaArgs: null
Stages:
- BaseName: python:3.7-stretch
  Commands:
  - CmdLine:
    - pip install "devpi-server<4.10" "devpi-web<3.6"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /devpi
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /devpi
  - Name: expose
    Ports:
    - "3141"
  - CmdLine:
    - '"devpi-server"'
    Name: entrypoint
    PrependShell: true
  - CmdLine:
    - '"--start"'
    Name: cmd
    PrependShell: true
  From:
    Image: python:3.7-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7-stretch
