MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Maintainer: Mauro Mandracchia <info@ideabile.com>
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Get a static content (.md, .sass, .js, etc..) and create a static website."'
    - Key: Vendor
      Value: '"ideabile.com"'
    - Key: Version
      Value: '"1.0.1"'
    Name: label
  - Name: volume
    Volumes:
    - /dest
    - /content
  - Env:
    - Key: WWW
      Value: /dest
    Name: env
  - Env:
    - Key: MAIN
      Value: ./
    Name: env
  - Name: workdir
    Path: /
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ${MAIN}package.json
    - /package.json
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - $MAIN
    - /
  - CmdLine:
    - apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - /node_modules/.bin/gulp
    Name: entrypoint
    PrependShell: true
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
