MetaArgs: null
Stages:
- BaseName: php:7.4-fpm
  Commands:
  - CmdLine:
    - apt-get update     && apt-get install -y     libpq-dev     zip     unzip     sqlite3     libsqlite3-dev     m4     libpng-dev     libjpeg-dev     libmagickwand-dev     zlib1g-dev     libzip-dev     libwebp-dev     libjpeg62-turbo-dev     libpng-dev
      libxpm-dev     libfreetype6-dev     zip
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install xdebug-2.9.1
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-enable xdebug
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install pdo_mysql pdo_pgsql pdo_sqlite bcmath zip gd
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -u 1000 www-data
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/html
  From:
    Image: php:7.4-fpm
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.4-fpm
