MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"gtunon@naevatec.com"'
    Name: label
  - Name: user
    User: root
  - CmdLine:
    - apt-get update &&     apt-get install -y  software-properties-common &&     add-apt-repository
      ppa:openjdk-r/ppa
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y &&     apt-get install -y curl wget
      apt-transport-https
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y openjdk-8-jdk
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-openjdk-amd64
    Name: env
  - CmdLine:
    - wget http://mirrors.viethosting.vn/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      &&     tar -xf apache-maven-3.3.9-bin.tar.gz  -C /usr/local
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/local/apache-maven-3.3.9 /usr/local/maven
    Name: run
    PrependShell: true
  - Env:
    - Key: M2_HOME
      Value: /usr/local/maven
    Name: env
  - Env:
    - Key: PATH
      Value: ${M2_HOME}/bin:${PATH}
    Name: env
  - CmdLine:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository     "deb [arch=amd64] https://download.docker.com/linux/ubuntu
      $(lsb_release -cs) stable"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y docker-ce=5:18.09.1~3-0~ubuntu-xenial
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export DOCKER_HOST='unix:///var/run/docker.sock'" >> /root/.bashrc  &&
      echo "export DEBIAN_FRONTEND=noninteractive" >> /root/.bashrc
    Name: run
    PrependShell: true
  - Env:
    - Key: PYTHONIOENCODING
      Value: UTF-8
    Name: env
  - CmdLine:
    - apt-get install -y     less     man     python     python-pip     python-virtualenv     unzip     vim
    Name: run
    PrependShell: true
  - CmdLine:
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      &&      unzip awscli-bundle.zip &&      ./awscli-bundle/install -i /var/lib/aws
      -b /usr/bin/aws
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install netcat
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install gnupg2
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash jenkins &&    echo "jenkins:jenkins" | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -aG docker jenkins
    Name: run
    PrependShell: true
  - Env:
    - Key: WORKSPACE
      Value: /home/jenkins
    Name: env
  - Name: user
    User: jenkins
  - Name: workdir
    Path: ${WORKSPACE}
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
