MetaArgs: null
Stages:
- BaseName: datadog/docker-dd-agent
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/nginx.yaml
    - /etc/dd-agent/conf.d/nginx.yaml
  From:
    Image: datadog/docker-dd-agent
  Name: ""
  Platform: ""
  SourceCode: FROM datadog/docker-dd-agent
