MetaArgs: null
Stages:
- BaseName: centos:6
  Commands:
  - CmdLine:
    - yum -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y groupinstall "Development Tools"
    Name: run
    PrependShell: true
  From:
    Image: centos:6
  Name: ""
  Platform: ""
  SourceCode: FROM centos:6
