MetaArgs: null
Stages:
- BaseName: debian:jessie-backports
  Commands:
  - Maintainer: Marcelo Almeida <ms.almeida86@gmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: '"noninteractive"'
    Name: env
  - CmdLine:
    - apt-get update && apt-get -t jessie-backports install -y --no-install-recommends     apt-transport-https     ca-certificates     curl     lxc     iptables     git     zip     supervisor     openjdk-8-jdk-headless     ca-certificates-java
      &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sSL https://get.docker.com/ | sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://raw.githubusercontent.com/docker/docker/master/hack/dind
    - /usr/local/bin/dind
  - CmdLine:
    - chmod +x /usr/local/bin/dind
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./wrapdocker
    - /usr/local/bin/wrapdocker
  - CmdLine:
    - chmod +x /usr/local/bin/wrapdocker
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/docker
  - Env:
    - Key: JENKINS_HOME
      Value: '"/var/lib/jenkins/"'
    Name: env
  - CmdLine:
    - mkdir ${JENKINS_HOME} &&   useradd jenkins --home-dir ${JENKINS_HOME} &&   chown
      jenkins:jenkins ${JENKINS_HOME} &&   usermod -a -G docker jenkins
    Name: run
    PrependShell: true
  - Env:
    - Key: SWARM_VERSION
      Value: "3.4"
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/${SWARM_VERSION}/swarm-client-${SWARM_VERSION}.jar
    - /root/swarm-client.jar
  - Env:
    - Key: URL
      Value: '""'
    - Key: USERNAME
      Value: '""'
    - Key: PASSWORD
      Value: '""'
    - Key: FSROOT
      Value: '"${JENKINS_HOME}"'
    - Key: EXECUTORS
      Value: '"1"'
    - Key: GIT_TIMEOUT
      Value: '"60"'
    - Key: MAX_HEAP_SIZE
      Value: '"512m"'
    - Key: MAX_PERM_SIZE
      Value: '"2048m"'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie-backports
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie-backports
