MetaArgs: null
Stages:
- BaseName: poldracklab/mriqc:0.15.1
  Commands:
  - Maintainer: Flywheel <support@flywheel.io>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y zip && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install flywheel-sdk==10.3.0         flywheel-bids==0.8.0 &&     rm -rf
      /root/.cache/pip
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g bids-validator@1.3.8
    Name: run
    PrependShell: true
  - Env:
    - Key: FLYWHEEL
      Value: /flywheel/v0
    Name: env
  - Name: workdir
    Path: ${FLYWHEEL}
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - CmdLine:
    - python -c 'import os, json; f = open("/tmp/gear_environ.json", "w"); json.dump(dict(os.environ),
      f)'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - manifest.json
    - ${FLYWHEEL}/manifest.json
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - utils
    - ${FLYWHEEL}/utils
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.py
    - ${FLYWHEEL}/run.py
  - CmdLine:
    - chmod a+x /flywheel/v0/run.py
    Name: run
    PrependShell: true
  - CmdLine:
    - /flywheel/v0/run.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: poldracklab/mriqc:0.15.1
  Name: ""
  Platform: ""
  SourceCode: FROM poldracklab/mriqc:0.15.1
