MetaArgs: null
Stages:
- BaseName: node:10
  Commands:
  - Maintainer: Franck Delage <franck@web82.fr>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y apt-transport-https
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >>
      /etc/apt/sources.list.d/google-chrome.list
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
      add -
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -qq -y --no-install-recommends curl vim git
      build-essential google-chrome-stable yarn
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn global add @angular/cli@7.0.3
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn add @angular/cli@7.0.3
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn add typescript
    Name: run
    PrependShell: true
  - CmdLine:
    - ng config -g cli.packageManager yarn
    Name: run
    PrependShell: true
  From:
    Image: node:10
  Name: ""
  Platform: ""
  SourceCode: FROM node:10
