MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y wget
    Name: run
    PrependShell: true
  - Env:
    - Key: KIBANA_VERSION
      Value: 4.1.1
    Name: env
  - CmdLine:
    - cd /tmp &&   wget https://download.elasticsearch.org/kibana/kibana/kibana-$KIBANA_VERSION-linux-x64.tar.gz
      &&   tar -xvzf kibana-$KIBANA_VERSION-linux-x64.tar.gz &&   mv /tmp/kibana-$KIBANA_VERSION-linux-x64
      /opt &&   rm kibana-$KIBANA_VERSION-linux-x64.tar.gz
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /bin/run.sh
  - CmdLine:
    - /bin/run.sh
    Name: cmd
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
