MetaArgs: null
Stages:
- BaseName: influxdb:1.7.7
  Commands:
  - Env:
    - Key: INFLUXDB_BIND_ADDRESS
      Value: 0.0.0.0:8088
    Name: env
  - Name: expose
    Ports:
    - "8088"
  From:
    Image: influxdb:1.7.7
  Name: ""
  Platform: ""
  SourceCode: FROM influxdb:1.7.7
