MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Env:
    - Key: MEOW_INSTALLDIR
      Value: /meow
    Name: env
  - CmdLine:
    - mkdir /meow &&     mkdir /lib64 &&     apk add --no-cache libc6-compat curl
      &&     cp /lib/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 &&     curl
      -L git.io/meowproxy | sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /meow
  - CmdLine:
    - /meow/MEOW
    Name: entrypoint
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
