MetaArgs: null
Stages:
- BaseName: golang:1.5
  Commands:
  - CmdLine:
    - "apt-get update && apt-get install -y --no-install-recommends \t\tunzip \t&&
      rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /go/src/github.com/shadowsocks
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /go/src/github.com/shadowsocks
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - shadowsocks-server-wrapper
    - /usr/local/bin/
  - CmdLine:
    - chmod a+x /usr/local/bin/shadowsocks-server-wrapper
    Name: run
    PrependShell: true
  - Env:
    - Key: SHADOWSOCKS_VERSION
      Value: 1.1.4
    Name: env
  - Env:
    - Key: SHADOWSOCKS_DOWNLOAD_URL
      Value: https://github.com/shadowsocks/shadowsocks-go/archive/$SHADOWSOCKS_VERSION.zip
    Name: env
  - CmdLine:
    - "curl -fsSL \"$SHADOWSOCKS_DOWNLOAD_URL\" -o shadowsocks-go.zip \t&& unzip shadowsocks-go.zip
      \t&& rm shadowsocks-go.zip \t&& mv shadowsocks-go-$SHADOWSOCKS_VERSION shadowsocks-go"
    Name: run
    PrependShell: true
  - CmdLine:
    - go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
    Name: run
    PrependShell: true
  - Name: user
    User: nobody
  - CmdLine:
    - shadowsocks-server-wrapper
    Name: cmd
    PrependShell: false
  From:
    Image: golang:1.5
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.5
