MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - Labels:
    - Key: description
      Value: '"Download CardDAV VCards and upload as phonebook to AVM FRITZ!Box"'
    Name: label
  - Name: volume
    Volumes:
    - /data
  - CmdLine:
    - set -xe &&     apk update && apk upgrade &&     apk add --no-cache --virtual=run-deps         php7-cli         php7-curl         php7-dom         php7-ftp         php7-mbstring         php7-simplexml         php7-tokenizer         php7-xml         php7-xmlreader         php7-xmlwriter         composer
      &&     apk del --progress --purge &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /srv
  - CmdLine:
    - mkdir -p /data &&     cd /srv &&     composer install --no-dev &&     chmod
      +x /srv/carddav2fb /srv/docker-entrypoint &&     ln -s /data/config.php .
    Name: run
    PrependShell: true
  - CmdLine:
    - /srv/docker-entrypoint
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
