MetaArgs: null
Stages:
- BaseName: alpine:3.6
  Commands:
  - Maintainer: Adam Dodman <"adam.dodman@gmx.com">
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /quotedb/
  - CmdLine:
    - apk add --no-cache python3 py3-pip tini gcc python3-dev libc-dev ca-certificates
      libffi-dev  && pip3 install -r /quotedb/requirements.txt  && ln -s /quotedb/adduser.py
      /usr/bin/quote-adduser
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - CmdLine:
    - /sbin/tini
    - --
    - python3
    - -u
    - /quotedb/main.py
    - -c
    - /config
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.6
