MetaArgs: null
Stages:
- BaseName: blinkmobile/apache-httpd:2.4.7
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install apt-utils -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install git curl build-essential re2c m4
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libcurl4-openssl-dev libmysqlclient-dev libssl-dev libxml2-dev
      libxslt1-dev zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y build-dep php5 php5-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libedit-dev libreadline-dev libmhash-dev libt1-dev libzip2
      libxpm-dev libgd2-xpm-dev libfreetype6-dev libmcrypt-dev
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    Name: env
  - Name: workdir
    Path: /usr/src
  - CmdLine:
    - curl -O http://ftp.gnu.org/gnu/bison/bison-2.6.5.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -O http://ftp.gnu.org/gnu/bison/bison-2.6.5.tar.gz.sig
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src
  - CmdLine:
    - tar zxf bison-2.6.5.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/bison-2.6.5
  - CmdLine:
    - ./configure --prefix=/usr/local
    Name: run
    PrependShell: true
  - CmdLine:
    - make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src
  - CmdLine:
    - rm -fr /usr/src/bison-2.6.5
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/php-build
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/CHH/php-build.git /opt/php-build
    Name: run
    PrependShell: true
  - CmdLine:
    - bash /opt/php-build/install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -fr /opt/php-build
    Name: run
    PrependShell: true
  - Env:
    - Key: MAKEOPTS
      Value: -j3
    Name: env
  - Env:
    - Key: EXTRA_LIBS
      Value: -lstdc++ -lssl -lcrypto
    Name: env
  - Env:
    - Key: PHP_BUILD_CONFIGURE_OPTS
      Value: --with-gettext --with-gmp-dir=/usr --with-mhash --enable-cli --with-libxml-dir=/usr
        --with-bz2 --enable-calendar --disable-dba --with-t1lib --with-xpm --with-freetype
        --enable-gd-native-ttf --with-icu-dir=/usr  --with-libedit --enable-mbregex
        --enable-sysvmsg --enable-wddx --with-iconv-dir=/usr  --with-pcre-regex --enable-fileinfo
        --enable-pdo --enable-simplexml --disable-cgi --disable-fpm --enable-intl
        --with-apxs2 --enable-maintainer-zts
    Name: env
  - CmdLine:
    - php-build --pear 5.3.29 /usr/local
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod php5
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl upgrade radius
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install libmagickwand-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl upgrade imagick
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - apt-get -y remove build-essential g++ gcc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y autoremove
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -fr /tmp/php-build*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/php
    Name: entrypoint
    PrependShell: false
  From:
    Image: blinkmobile/apache-httpd:2.4.7
  Name: ""
  Platform: ""
  SourceCode: FROM blinkmobile/apache-httpd:2.4.7
