MetaArgs: null
Stages:
- BaseName: node:lts-alpine
  Commands:
  - Name: workdir
    Path: /usr/src/app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - .
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - sed -i -e "s|^const ES_URL.*|const ES_URL = 'https://elasticsearch.developers.italia.it/indicepa_pec/_search';|g"  public/assets/js/constants.js
    Name: run
    PrependShell: true
  - CmdLine:
    - npm run $env
    Name: cmd
    PrependShell: true
  From:
    Image: node:lts-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:lts-alpine
