MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/heapster-amd64:v1.5.3
  Commands:
  - Maintainer: lubinson@gmail.com
    Name: maintainer
  From:
    Image: k8s.gcr.io/heapster-amd64:v1.5.3
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/heapster-amd64:v1.5.3
