MetaArgs: null
Stages:
- BaseName: golang:1.13
  Commands:
  - Name: workdir
    Path: /go/src/8k
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Key: VERSION
    Name: arg
    Value: dev
  - Env:
    - Key: VERSION
      Value: '"${VERSION}"'
    Name: env
  - CmdLine:
    - go test -v ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 go build -o 8192 -ldflags "-X github.com/2bytes/8k/internal/config.Version=${VERSION}"
      cmd/8192/main.go
    Name: run
    PrependShell: true
  - CmdLine:
    - ./8192 -v
    Name: run
    PrependShell: true
  From:
    Image: golang:1.13
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.13
- BaseName: scratch
  Commands:
  - Name: workdir
    Path: /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pkg/frontend/tmpl
    - /frontend
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /go/src/8k/8192
    - .
  - CmdLine:
    - ./8192
    Name: entrypoint
    PrependShell: false
  From:
    Scratch: true
  Name: ""
  Platform: ""
  SourceCode: FROM scratch
