MetaArgs: null
Stages:
- BaseName: multiarch/alpine:x86_64-edge
  Commands:
  - CmdLine:
    - cat /etc/apk/repositories| sed 's@main@testing@g' > /testing && cat testing
      >> /etc/apk/repositories
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add amule --update
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
    - /downloads
  - Name: expose
    Ports:
    - 4661/tcp
    - 4662/tcp
    - 4665/udp
    - 4672/udp
    - 4711/tcp
    - 4712/tcp
  - CmdLine:
    - /usr/bin/amuled
    Name: entrypoint
    PrependShell: true
  - CmdLine:
    - -c /config
    Name: cmd
    PrependShell: true
  From:
    Image: multiarch/alpine:x86_64-edge
  Name: ""
  Platform: ""
  SourceCode: FROM multiarch/alpine:x86_64-edge
