MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt update && apt -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y uwsgi python-flask build-essential python-dev uwsgi-plugin-python
      python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y libmysqlclient-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install influxdb
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install MySQL-python
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - website
    - /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.sh
    - /root/start.sh
  - CmdLine:
    - chmod +x /root/start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/start.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
