MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Steven N Hart, PhD
    Name: maintainer
  - CmdLine:
    - yum install -y java-1.7.0-openjdk.x86_64 java-1.7.0-openjdk-devel wget tar git
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O /home/mongodb.tgz https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel62-3.0.3.tgz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -zxvf /home/mongodb.tgz -C /home/
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /home/mongodb-linux-x86_64-rhel62-3.0.3/bin/* /bin
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /data/db /data/mongo /local2/tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 775 -R /data/mongo /data/db /local2/tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.62/bin/apache-tomcat-7.0.62.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvzf apache-tomcat-7.0.62.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - mv apache-tomcat-7.0.62 /usr/local
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 775 /usr/local/apache-tomcat-7.0.62/bin/*sh
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/Steven-N-Hart/vcf-miner.git && cd vcf-miner
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /vcf-miner/mongo_svr.war /usr/local/apache-tomcat-7.0.62/webapps/
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /vcf-miner/vcf-miner.war /usr/local/apache-tomcat-7.0.62/webapps/
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /vcf-miner/securityuserappNoLDAP.war /usr/local/apache-tomcat-7.0.62/webapps/securityuserapp.war
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - chmod 775 /vcf-miner/start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - sh /vcf-miner/start.sh
    Name: entrypoint
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
