MetaArgs: null
Stages:
- BaseName: python:2.7.14
  Commands:
  - Name: workdir
    Path: /opt/bitwrap
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - requirements.txt
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - pip install .
    Name: run
    PrependShell: true
  - Env:
    - Key: GUNICORN_WORKERS
      Value: "5"
    Name: env
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - ./entry.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:2.7.14
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7.14
