MetaArgs: null
Stages:
- BaseName: haproxy:2.0.5
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - haproxy.cfg
    - /usr/local/etc/haproxy/haproxy.cfg
  - Maintainer: amoswang0917@gmail.com
    Name: maintainer
  From:
    Image: haproxy:2.0.5
  Name: ""
  Platform: ""
  SourceCode: FROM haproxy:2.0.5
