MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Env:
    - Key: YARN_VERSION
      Value: 1.7.0-r0
    Name: env
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.name
      Value: '"Yarn"'
    - Key: org.label-schema.description
      Value: '"Simple Yarn container"'
    - Key: org.label-schema.url
      Value: '"https://github.com/kns-it/Docker-Yarn"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/kns-it/Docker-Yarn"'
    - Key: org.label-schema.vendor
      Value: '"KNS"'
    - Key: org.label-schema.version
      Value: $YARN_VERSION
    - Key: org.label-schema.schema-version
      Value: '"1.0"'
    - Key: maintainer
      Value: '"sebastian.kurfer@kns-it.de"'
    Name: label
  - CmdLine:
    - "apk add --update --no-cache nodejs-current \t\t\t\tyarn &&     adduser -h /home/yarn
      -s /bin/sh -D yarn"
    Name: run
    PrependShell: true
  - Name: user
    User: yarn
  - Name: workdir
    Path: /home/yarn
  - CmdLine:
    - yarn
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
