MetaArgs: null
Stages:
- BaseName: php:7.2-fpm
  Commands:
  - CmdLine:
    - "pecl install redis mongodb \t\t&& docker-php-ext-enable redis mongodb \t\t&&
      docker-php-ext-install mysqli pdo pdo_mysql exif json pcntl"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./etc/php-fpm.conf
    - /usr/local/etc/php-fpm.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./etc/php.ini
    - /usr/local/etc/php/php.ini
  - Name: workdir
    Path: /data
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php-fpm
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.2-fpm
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2-fpm
