MetaArgs: null
Stages:
- BaseName: gcr.io/istio-testing/website-builder:2018-07-14
  Commands:
  - Maintainer: libertinus
    Name: maintainer
  From:
    Image: gcr.io/istio-testing/website-builder:2018-07-14
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/istio-testing/website-builder:2018-07-14
