MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: Fernando de Assis <fernandoassissr@gmal.com>
    Name: maintainer
  - CmdLine:
    - apk --no-cache add         bash         openssh         ca-certificates         curl         git         php7         php7-bcmath         php7-ctype         php7-curl         php7-dom         php7-exif         php7-fileinfo         php7-json         php7-mbstring         php7-mcrypt         php7-mysqli         php7-opcache         php7-openssl         php7-pcntl         php7-pdo         php7-pdo_mysql         php7-pdo_pgsql         php7-pdo_sqlite         php7-phar         php7-session         php7-simplexml         php7-soap         php7-tokenizer         php7-xdebug         php7-xml         php7-xmlreader         php7-xmlwriter         php7-zip         php7-zlib         unzip
      &&         php -r "copy('https://pear.php.net/go-pear.phar', 'go-pear.phar');"
      &&         php go-pear.phar &&         php -r "unlink('go-pear.phar');" &&         php
      -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&         php
      composer-setup.php --install-dir=/usr/bin --filename=composer &&         php
      -r "unlink('composer-setup.php');"
    Name: run
    PrependShell: true
  - CmdLine:
    - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-5.phar
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/phpunit
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
