MetaArgs: null
Stages:
- BaseName: ruby:alpine
  Commands:
  - Maintainer: Derek Smith <drsmith.phys@gmail.com>
    Name: maintainer
  - CmdLine:
    - mkdir -p /usr/src/sidekiq
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/sidekiq
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile
    - /usr/src/sidekiq/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile.lock
    - /usr/src/sidekiq/
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config.ru
    - /usr/src/sidekiq/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker-entrypoint.sh
    - /
  - Name: expose
    Ports:
    - "9292"
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - bundle
    - exec
    - rackup
    - -o
    - 0.0.0.0
    - config.ru
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:alpine
