MetaArgs: null
Stages:
- BaseName: nginx:stable-alpine
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /etc/nginx/html
  - Name: workdir
    Path: /etc/nginx/html
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-1.8-openjdk/jre
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$JAVA_HOME/bin
    Name: env
  - Env:
    - Key: JAVA_VERSION
      Value: 8u77
    Name: env
  - Env:
    - Key: JAVA_ALPINE_VERSION
      Value: 8.77.03-r0
    Name: env
  - CmdLine:
    - set -x     && apk add --no-cache       openjdk8-jre="$JAVA_ALPINE_VERSION"     &&
      chmod u+x closure-compiler.jar     && ./compile.sh     && rm closure-compiler.jar
      compile.sh     && apk del openjdk8-jre
    Name: run
    PrependShell: true
  From:
    Image: nginx:stable-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:stable-alpine
