MetaArgs: null
Stages:
- As: builder
  BaseName: alpine:3.9
  Commands:
  - CmdLine:
    - apk --no-cache add     ruby     ruby-dev     make     g++
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install etc:1.0.1 fpm:1.10.2 --no-rdoc --no-ri
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.9
  Name: builder
  Platform: ""
  SourceCode: FROM alpine:3.9 as builder
- BaseName: idparcag/gcloud-sdk-alpine:254-0-0_1
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/lib/ruby/gems/
    - /usr/lib/ruby/gems/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/bin/fpm
    - /usr/bin/fpm
  - Env:
    - Key: ANSIBLE_SSH_PIPELINING
      Value: "1"
    Name: env
  - Env:
    - Key: NODE_PATH
      Value: /usr/lib/node_modules
    Name: env
  - Env:
    - Key: CONFIG_PATH
      Value: /config
    Name: env
  - CmdLine:
    - apk --no-cache add     curl     patch     openssh     tar     bash     ruby     nodejs     openjdk8     python3     py3-cryptography     py3-markupsafe     py3-yaml     py3-bcrypt     py3-pynacl     py3-jinja2     py3-paramiko     py3-docutils     py3-rsa     py3-asn1     py3-dateutil     cpio     rpm     git     openssl     rsync     xz     coreutils     npm     jq
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install ansible==2.6.4 awscli==1.16.18
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://github.com/sbt/sbt/releases/download/v1.2.4/sbt-1.2.4.tgz |
      tar -xz -C /usr/bin --strip 2 sbt/bin/
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=2.16.0 node
    Name: run
    PrependShell: true
  - CmdLine:
    - npm config set user 0
    Name: run
    PrependShell: true
  - CmdLine:
    - npm config set unsafe-perm true
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g browserify node-sass rimraf babel-cli envify uglify-es uglifyify
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/lib/jvm/java-1.8-openjdk/bin/javadoc /bin/javadoc
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/default-jvm
    Name: env
  From:
    Image: idparcag/gcloud-sdk-alpine:254-0-0_1
  Name: ""
  Platform: ""
  SourceCode: FROM idparcag/gcloud-sdk-alpine:254-0-0_1
