MetaArgs: null
Stages:
- BaseName: labiomed/centos7-systemd:base
  Commands:
  - Maintainer: Nicholas Alipaz <nalipaz@labiomed.org>
    Name: maintainer
  - CmdLine:
    - yum -y install rsyslog && yum clean all && rm -rf /tmp/yum*
    Name: run
    PrependShell: true
  - CmdLine:
    - systemctl enable rsyslog.service
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "514"
  From:
    Image: labiomed/centos7-systemd:base
  Name: ""
  Platform: ""
  SourceCode: FROM labiomed/centos7-systemd:base
