MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - CmdLine:
    - "apt-get update \t&& apt-get install -y --no-install-recommends                            ca-certificates
      \                           git                            build-essential                            hdf5-tools
      \                           gfortran \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: JULIA_PATH
      Value: /usr/local/julia
    Name: env
  - Env:
    - Key: JULIA_VERSION
      Value: 0.5.0
    Name: env
  - CmdLine:
    - "mkdir $JULIA_PATH \t&& apt-get update && apt-get install -y curl \t&& curl
      -sSL \"https://julialang.s3.amazonaws.com/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz\"
      -o julia.tar.gz \t&& curl -sSL \"https://julialang.s3.amazonaws.com/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz.asc\"
      -o julia.tar.gz.asc \t&& export GNUPGHOME=\"$(mktemp -d)\" \t&& gpg --keyserver
      ha.pool.sks-keyservers.net --recv-keys 3673DF529D9049477F76B37566E3C7DC03D6E495
      \t&& gpg --batch --verify julia.tar.gz.asc julia.tar.gz \t&& rm -r \"$GNUPGHOME\"
      julia.tar.gz.asc \t&& tar -xzf julia.tar.gz -C $JULIA_PATH --strip-components
      1 \t&& rm -rf /var/lib/apt/lists/* julia.tar.gz*"
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $JULIA_PATH/bin:$PATH
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - packages.jl
    - $JULIA_PATH/
  - CmdLine:
    - $JULIA_PATH/bin/julia $JULIA_PATH/packages.jl
    Name: run
    PrependShell: true
  - CmdLine:
    - julia
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
