MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: simon_chu
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y vim
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
