MetaArgs: null
Stages:
- BaseName: composer:latest
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - echo 'export PATH="$HOME/.composer/vendor/bin:$PATH"' >> $HOME/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - "composer global config bin-dir /usr/local/bin &&     composer global config
      vendor-dir /var/lib/composer/vendor && \tcomposer global config minimum-stability
      dev &&     composer global config prefer-stable true &&     composer global
      config optimize-autoloader true &&     composer global config preferred-install
      dist &&     composer global config sort-packages true"
    Name: run
    PrependShell: true
  - CmdLine:
    - composer global require --no-suggest hirak/prestissimo
    Name: run
    PrependShell: true
  - CmdLine:
    - composer global require --no-suggest dealerdirect/phpcodesniffer-composer-installer     drupal/coder     wimg/php-compatibility
    Name: run
    PrependShell: true
  - Name: user
    User: www-data
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - CmdLine:
    - phpcs
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -i
    Name: cmd
    PrependShell: false
  From:
    Image: composer:latest
  Name: ""
  Platform: ""
  SourceCode: FROM composer:latest
