MetaArgs: null
Stages:
- BaseName: gfjardim/cups
  Commands:
  - Maintainer: Sebastian Schneider <mail@sesc.eu>
    Name: maintainer
  - CmdLine:
    - wget -O /tmp/mccgdi-2.0.9-x86_64.tar.gz     http://cs.psn-web.net/support/fax/common/file/Linux_PrnDriver/Driver_Install_files/mccgdi-2.0.9-x86_64.tar.gz     &&
      tar -xvzf /tmp/mccgdi-2.0.9-x86_64.tar.gz     && cd mccgdi-2.0.9-x86_64     &&
      ./install-driver     && ln -s /usr/lib/x86_64-linux-gnu/libgs.so.9 /usr/lib/libgs.so
    Name: run
    PrependShell: true
  From:
    Image: gfjardim/cups
  Name: ""
  Platform: ""
  SourceCode: FROM gfjardim/cups
