MetaArgs: null
Stages:
- BaseName: php:5.6-apache
  Commands:
  - Maintainer: Rondineli Saad <rondineli.saad@scielo.org>
    Name: maintainer
  - CmdLine:
    - a2enmod rewrite expires
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get -qqy update     && apt-get install -qqy libpng12-dev                             libjpeg-dev
      \                            libmcrypt-dev                             libxml2-dev
      \                            libxslt-dev \t\t\t    git     && rm -rf /var/lib/apt/lists/*
      \    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr
      \    && docker-php-ext-install gd                               mysqli                               mysql
      \                              opcache \t\t\t      mcrypt \t\t\t      soap \t\t\t
      \     xsl \t\t\t      zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - "{ \t\techo 'opcache.memory_consumption=128'; \t\techo 'opcache.interned_strings_buffer=8';
      \t\techo 'opcache.max_accelerated_files=4000'; \t\techo 'opcache.revalidate_freq=60';
      \t\techo 'opcache.fast_shutdown=1'; \t\techo 'opcache.enable_cli=1'; \t} > /usr/local/etc/php/conf.d/opcache-recommended.ini"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www
  - Env:
    - Key: SERVERNAME
      Value: omp.scielo.org
    Name: env
  - Env:
    - Key: OMP_DB_HOST
      Value: localhost
    Name: env
  - Env:
    - Key: OMP_DB_USER
      Value: omp
    Name: env
  - Env:
    - Key: OMP_DB_PASSWORD
      Value: omp
    Name: env
  - Env:
    - Key: OMP_DB_NAME
      Value: omp
    Name: env
  - Env:
    - Key: SERVERNAME
      Value: omp.scielo.org
    Name: env
  - Env:
    - Key: APACHE_LOG_DIR
      Value: /var/log/apache2
    Name: env
  - Env:
    - Key: LOG_NAME
      Value: omp_scielo_org
    Name: env
  - Env:
    - Key: OMP_VERSION
      Value: 3.1.0
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 000-default.conf
    - /etc/apache2/sites-enabled/000-default.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/php.ini
    - /usr/local/etc/php/
  - Name: expose
    Ports:
    - "80"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - omp-startup.sh
    - /omp-startup.sh
  - CmdLine:
    - /bin/bash
    - /omp-startup.sh
    Name: cmd
    PrependShell: false
  From:
    Image: php:5.6-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6-apache
