MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Env:
    - Key: RUST_VERSION
      Value: 1.34.2
    Name: env
  - Env:
    - Key: HOME
      Value: /home
    Name: env
  - Env:
    - Key: CARGO_HOME
      Value: /usr/local/cargo
    Name: env
  - Env:
    - Key: PATH
      Value: $CARGO_HOME/bin:$HOME/.cargo/bin:$PATH
    Name: env
  - CmdLine:
    - mkdir -p "$CARGO_HOME"
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sSf https://sh.rustup.rs   | env -u CARGO_HOME sh -s -- -y --default-toolchain
      "$RUST_VERSION"
    Name: run
    PrependShell: true
  - CmdLine:
    - rustup --version;     rustc --version;     cargo --version;
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $HOME
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
