MetaArgs: null
Stages:
- BaseName: java:openjdk-8-jre-alpine
  Commands:
  - Maintainer: Justin Plock <justin@plock.net>
    Name: maintainer
  - Labels:
    - Key: name
      Value: '"zookeeper"'
    - Key: version
      Value: '"3.5.1-alpha"'
    Name: label
  - CmdLine:
    - apk add --no-cache wget bash     && mkdir /opt     && wget -q -O - http://apache.mirrors.pair.com/zookeeper/zookeeper-3.5.1-alpha/zookeeper-3.5.1-alpha.tar.gz
      | tar -xzf - -C /opt     && mv /opt/zookeeper-3.5.1-alpha /opt/zookeeper     &&
      cp /opt/zookeeper/conf/zoo_sample.cfg /opt/zookeeper/conf/zoo.cfg     && mkdir
      -p /tmp/zookeeper
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "2181"
    - "2888"
    - "3888"
  - Name: workdir
    Path: /opt/zookeeper
  - Name: volume
    Volumes:
    - /opt/zookeeper/conf
    - /tmp/zookeeper
  - CmdLine:
    - /opt/zookeeper/bin/zkServer.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - start-foreground
    Name: cmd
    PrependShell: false
  From:
    Image: java:openjdk-8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM java:openjdk-8-jre-alpine
