MetaArgs: null
Stages:
- BaseName: alpine:3.2
  Commands:
  - Maintainer: Pan Jiabang <panjiabang@gmail.com>
    Name: maintainer
  - CmdLine:
    - apk update
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add nginx bash
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add nodejs python make g++ && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install hexo -g
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/*
    - /usr/local/bin/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://raw.githubusercontent.com/JamesPan/blog-src/master/package.json
    - /tmp/
  - Name: workdir
    Path: /tmp/
  - CmdLine:
    - npm install && npm cache clean
    Name: run
    PrependShell: true
  - CmdLine:
    - sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.2
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.2
