MetaArgs: null
Stages:
- BaseName: pypy:3.5-7-slim
  Commands:
  - Env:
    - Key: PARSEDMARC_VERSION
      Value: 6.5.4
    Name: env
  - CmdLine:
    - apt-get update     && apt-get install -y gcc     && pip install -U parsedmarc==$PARSEDMARC_VERSION     &&
      rm -rf /root/.cache/     && apt-get purge -y gcc     && apt-get autoremove -y     &&
      rm -rf /var/lib/{apt,dpkg}/
    Name: run
    PrependShell: true
  - CmdLine:
    - parsedmarc
    Name: cmd
    PrependShell: false
  From:
    Image: pypy:3.5-7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM pypy:3.5-7-slim
