MetaArgs: null
Stages:
- BaseName: fedora:20
  Commands:
  - CmdLine:
    - yum -y update; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y groupinstall "Development Tools"; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install java-1.7.0-openjdk-devel; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y upgrade libstdc++; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install glibc.i686 libstdc++.i686 glibc-devel.i686 zlib-devel.i686 ncurses-devel.i686
      libX11-devel.i686 libXrender.i686; yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /usr/local/ && \tcurl -L -O http://dl.google.com/android/android-sdk_r24.0.2-linux.tgz
      && \ttar xf android-sdk_r24.0.2-linux.tgz && \trm -rf android-sdk_r24.0.2-linux.tgz"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | /usr/local/android-sdk-linux/tools/android update sdk --filter tools
      --no-ui --force -a
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | /usr/local/android-sdk-linux/tools/android update sdk --filter platform-tools
      --no-ui --force -a
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | /usr/local/android-sdk-linux/tools/android update sdk --filter build-tools-21.1.1,build-tools-21.1.0
      --no-ui --force -a
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | /usr/local/android-sdk-linux/tools/android update sdk --filter extra-android-m2repository,extra-android-support
      --no-ui --force -a
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | /usr/local/android-sdk-linux/tools/android update sdk --filter android-21
      --no-ui --force -a
    Name: run
    PrependShell: true
  - CmdLine:
    - echo y | /usr/local/android-sdk-linux/tools/android update sdk --filter sys-img-armeabi-v7a-android-21
      --no-ui --force -a
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /usr/local/ && \tcurl -L -O http://ftp.meisei-u.ac.jp/mirror/apache/dist/ant/binaries/apache-ant-1.9.5-bin.tar.gz
      && \ttar xf apache-ant-1.9.5-bin.tar.gz && \trm -rf apache-ant-1.9.5-bin.tar.gz"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /usr/local/ && \tcurl -L -O http://ftp.tsukuba.wide.ad.jp/software/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
      && \ttar xf apache-maven-3.2.5-bin.tar.gz && \trm -rf apache-maven-3.2.5-bin.tar.gz"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /usr/local/ && \tcurl -L -O http://services.gradle.org/distributions/gradle-2.2.1-bin.zip
      && \tunzip -qo gradle-2.2.1-bin.zip && \trm -rf gradle-2.2.1-bin.zip"
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/jre-1.7.0-openjdk
    Name: env
  - Env:
    - Key: ANDROID_HOME
      Value: /usr/local/android-sdk-linux
    Name: env
  - Env:
    - Key: ANDROID_AVD_HOME
      Value: /root/.android/avd
    Name: env
  - Env:
    - Key: ANT_HOME
      Value: /usr/local/apache-ant-1.9.4
    Name: env
  - Env:
    - Key: MAVEN_HOME
      Value: /usr/local/apache-maven-3.2.5
    Name: env
  - Env:
    - Key: GRADLE_HOME
      Value: /usr/local/gradle-2.2.1
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$ANDROID_HOME/tools
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$ANDROID_HOME/platform-tools
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$ANT_HOME/bin
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$MAVEN_HOME/bin
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$GRADLE_HOME/bin
    Name: env
  - CmdLine:
    - mkdir -p $ANDROID_AVD_HOME
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /src
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: fedora:20
  Name: ""
  Platform: ""
  SourceCode: FROM fedora:20
