MetaArgs: null
Stages:
- BaseName: ubuntu:bionic-20190204
  Commands:
  - Maintainer: Kevin Coakley <kcoakley@sdsc.edu>
    Name: maintainer
  - Env:
    - Key: container
      Value: docker
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y     systemd     python     openssh-server     openssh-client     apt-utils     sudo  &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - systemctl set-default multi-user.target
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'root:docker' | chpasswd
    Name: run
    PrependShell: true
  - CmdLine:
    - systemctl enable ssh.service
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /sys/fs/cgroup
  - Name: volume
    Volumes:
    - /run
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /sbin/init
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:bionic-20190204
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:bionic-20190204
