MetaArgs: null
Stages:
- BaseName: beeman/scully-docker:latest
  Commands:
  - Env:
    - Key: SCULLY_PUPPETEER_EXECUTABLE_PATH
      Value: '''/usr/bin/chromium-browser'''
    Name: env
  - Name: workdir
    Path: /workspace
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - yarn.lock
    - /workspace/
  - CmdLine:
    - yarn install --network-timeout 1000000
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /workspace/
  - CmdLine:
    - yarn build
    Name: run
    PrependShell: true
  - CmdLine:
    - yarn scully
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - yarn
    - serve
    Name: cmd
    PrependShell: false
  From:
    Image: beeman/scully-docker:latest
  Name: ""
  Platform: ""
  SourceCode: FROM beeman/scully-docker:latest
