MetaArgs: null
Stages:
- BaseName: node:argon
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./entry.sh
    - /entry.sh
  - CmdLine:
    - chmod a+x /entry.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - '"/entry.sh"'
    Name: cmd
    PrependShell: true
  From:
    Image: node:argon
  Name: ""
  Platform: ""
  SourceCode: FROM node:argon
