MetaArgs: null
Stages:
- BaseName: busybox
  Commands:
  - Env:
    - Key: QEMU_BIN_DIR
      Value: /usr/bin
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./register.sh
    - /register
  - CmdLine:
    - /register
    Name: entrypoint
    PrependShell: false
  From:
    Image: busybox
  Name: ""
  Platform: ""
  SourceCode: FROM busybox
