MetaArgs: null
Stages:
- BaseName: mback2k/debian:stretch
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y --no-install-recommends         dnsmasq
      &&     apt-get clean
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /etc/dnsmasq
  - CmdLine:
    - /usr/sbin/dnsmasq
    - -d
    - -u
    - dnsmasq
    Name: cmd
    PrependShell: false
  From:
    Image: mback2k/debian:stretch
  Name: ""
  Platform: ""
  SourceCode: FROM mback2k/debian:stretch
