MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: Frank Monnerjahn <themonnie@gmail.com>
    Name: maintainer
  - Env:
    - Key: PEN_VERSION
      Value: '"0.33.2"'
    Name: env
  - CmdLine:
    - apk update update &&     apk add --no-cache g++ make &&     cd /tmp/ && wget
      -O - "http://siag.nu/pub/pen/pen-$PEN_VERSION.tar.gz" |  tar zx &&     cd "/tmp/pen-$PEN_VERSION"
      &&     ./configure &&     make -j &&     make install &&     apk --purge del
      g++ make wget &&     rm -rf /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/pen
    - -f
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
