MetaArgs: null
Stages:
- BaseName: debian:sid-slim
  Commands:
  - CmdLine:
    - "apt-get update &&     apt-get install -y     apt-transport-https \tca-certificates
      \tcurl \tgnupg \thicolor-icon-theme \tlibcanberra-gtk* \tlibgl1-mesa-dri \tlibgl1-mesa-glx
      \tlibpango1.0-0 \tlibpulse0 \tlibv4l-0 \tfonts-symbola     --no-install-recommends"
    Name: run
    PrependShell: true
  - CmdLine:
    - "curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      \t&& echo \"deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable
      main\" > /etc/apt/sources.list.d/google.list \t&& apt-get update && apt-get
      install -y \tgoogle-chrome-stable     --no-install-recommends"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get purge --auto-remove -y curl     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r chrome && useradd -r -g chrome -G audio,video chrome     && mkdir
      -p /home/chrome/Downloads && mkdir -p /home/chrome/data && chown -R chrome:chrome
      /home/chrome
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - local.conf
    - /etc/fonts/local.conf
  - Name: user
    User: chrome
  - Name: volume
    Volumes:
    - /home/chrome/data
  - CmdLine:
    - google-chrome
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --user-data-dir=/home/chrome/data
    - --no-sandbox
    Name: cmd
    PrependShell: false
  From:
    Image: debian:sid-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:sid-slim
