MetaArgs: null
Stages:
- BaseName: uclrits/sopt:stable
  Commands:
  - Name: user
    User: root
  - Name: workdir
    Path: /build
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/local/lib
    Name: env
  - CmdLine:
    - docker-apt-install casacore-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --single-branch --branch stable https://github.com/astro-informatics/purify.git
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /build/purify/build && cd /build/purify/build &&     cmake .. -DCMAKE_BUILD_TYPE=Release     -Dtests=ON     -Dexamples=OFF     -Ddocasa=ON     -Dbenchmarks=OFF     -DSopt_GIT_TAG=stable     -DCFitsIO_URL=https://github.com/UCL-RITS/BinaryBlobs-dependencies/raw/master/Astronomy/cfitsio3410.tar.gz     -DMPIEXEC:FILEPATH=$(which
      mpirun) -DMPIEXEC_MAX_NUMPROCS=4     -DMPIEXEC_PREFLAGS="--oversubscribe" &&     make
      && make install
    Name: run
    PrependShell: true
  - Name: user
    User: purifier
  - Env:
    - Key: HOME
      Value: /home/purifier
    Name: env
  - Name: workdir
    Path: /mydata
  - CmdLine:
    - zsh
    Name: cmd
    PrependShell: false
  From:
    Image: uclrits/sopt:stable
  Name: ""
  Platform: ""
  SourceCode: FROM uclrits/sopt:stable
