MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: developers <developers@studioskylab.com>
    Name: maintainer
  - Env:
    - Key: SITE_NAME
      Value: dev
    Name: env
  - Env:
    - Key: APACHE_LOG_DIR
      Value: /var/log/website
    Name: env
  - Env:
    - Key: TIMEZONE
      Value: Etc/UTC
    Name: env
  - Env:
    - Key: SCRIPT_DIR
      Value: /tmp/install
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./install
    - ${SCRIPT_DIR}
  - CmdLine:
    - apt-get update     && apt-get install -y --no-install-recommends     wget     curl     vim     build-essential     apache2     libapache2-mod-php5     openssl     openssh-client     php5     php5-cli     php5-curl     php5-apcu     php5-gd     php5-imagick     php5-intl     php5-mcrypt     php5-xmlrpc     php5-mysql     php5-sybase     htop     git     php5-xdebug     make     npm     nodejs     nodejs-legacy     ruby     ruby-dev     python-pip     &&
      touch /etc/php5/mods-available/timezone.ini     && echo "date.timezone = \"${TIMEZONE}\""
      >> /etc/php5/mods-available/timezone.ini     && php5enmod mcrypt     curl     timezone     &&
      echo "ServerName localhost" >> /etc/apache2/apache2.conf     && cp ${SCRIPT_DIR}/apache-default.conf
      /etc/apache2/sites-available/000-default.conf     && a2dismod mpm_event && a2enmod
      mpm_prefork     && a2enmod     rewrite     expires     filter     headers     rewrite     setenvif     proxy_http     remoteip     deflate     expires     env     &&
      mkdir -p "$APACHE_LOG_DIR/error"     && touch "$APACHE_LOG_DIR/error/$SITE_NAME.log"     &&
      ln -sfT /dev/stderr "$APACHE_LOG_DIR/error/$SITE_NAME.log"     && mkdir -p "$APACHE_LOG_DIR/access"     &&
      touch "$APACHE_LOG_DIR/access/$SITE_NAME.log"     && ln -sfT /dev/stdout "$APACHE_LOG_DIR/access/$SITE_NAME.log"     &&
      mkdir -p /var/log/apache2/     && touch /var/log/apache2/access.log     && ln
      -sfT /dev/stderr /var/log/apache2/access.log     && touch /var/log/apache2/error.log     &&
      ln -sfT /dev/stderr /var/log/apache2/error.log     && touch /var/log/apache2/other_vhosts_access.log     &&
      ln -sfT /dev/stderr /var/log/apache2/other_vhosts_access.log     && bash ${SCRIPT_DIR}/powerline.sh     &&
      bash ${SCRIPT_DIR}/latest_node.sh     && bash ${SCRIPT_DIR}/php.sh     && apt-get
      autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/*     &&
      rm -rf ${SCRIPT_DIR}
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/sbin/apache2ctl
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
