MetaArgs: null
Stages:
- BaseName: python:alpine
  Commands:
  - Maintainer: Carlos Sanz <carlos.sanzpenas@gmail.com>
    Name: maintainer
  - Labels:
    - Key: org.label-schema.vendor
      Value: = "Personal"       org.label-schema.name = "Cisco Collab"       org.label-schema.version
        = "Alpine"       org.label-schema.docker.cmd = "docker run -it sanzcarlos/CiscoCollab"       org.label-schema.name
        = "Cisco Collab"       org.label-schema.build-date = "2018-05-08"
    Name: label
  - CmdLine:
    - apk update &&     apk upgrade &&     apk add git &&     git clone https://github.com/sanzcarlos/CiscoCollab
      /usr/src/CiscoCollab/ &&     pip install -r /usr/src/CiscoCollab/requirements.txt
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/CiscoCollab/
  - CmdLine:
    - python
    - /usr/src/CiscoCollab/axl_cucm.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:alpine
