MetaArgs: null
Stages:
- BaseName: wordpress
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y         libzip-dev         zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install     mbstring     zip     exif
    Name: run
    PrependShell: true
  From:
    Image: wordpress
  Name: ""
  Platform: ""
  SourceCode: FROM wordpress
