MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Arturo Volpe <arturovolpe@gmail.com>
    Name: maintainer
  - Env:
    - Key: PYTHON_VERSION
      Value: 3.6.2
    Name: env
  - CmdLine:
    - yum update -y &&    yum install yum-utils curl make -y &&    yum-builddep python
      -y &&    yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
      &&    tar xf Python-${PYTHON_VERSION}.tgz &&     cd Python-${PYTHON_VERSION}
      &&     ./configure &&     make &&     make install &&    cd .. &&    rm -rf
      Python*
    Name: run
    PrependShell: true
  - CmdLine:
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" &&    python get-pip.py
    Name: run
    PrependShell: true
  - CmdLine:
    - yum update -y &&    yum install rpm-build -y &&    yum install python-devel
      -y &&    yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - python --version && pip --version
    Name: run
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
