MetaArgs: null
Stages:
- BaseName: nginx:alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - build
    - /proxy
  - CmdLine:
    - /bin/sh
    - /proxy/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
