MetaArgs: null
Stages:
- BaseName: wburns/ispn-master
  Commands:
  - Maintainer: William Burns <william.a.burns@gmail.com>
    Name: maintainer
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - settings.xml
    - /opt/jboss/.m2/
  - CmdLine:
    - chown -R jboss:jboss /opt/jboss/.m2/
    Name: run
    PrependShell: true
  - Name: user
    User: jboss
  - CmdLine:
    - mvn clean install -DskipTests=true   && find . -name target -type d | xargs
      rm -rf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /opt/jboss/
  - CmdLine:
    - /bin/bash
    - /opt/jboss/run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: wburns/ispn-master
  Name: ""
  Platform: ""
  SourceCode: FROM wburns/ispn-master
