MetaArgs: null
Stages:
- BaseName: bigm/base-deb
  Commands:
  - CmdLine:
    - echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true
      | debconf-set-selections     && echo oracle-java7-installer shared/accepted-oracle-license-v1-1
      seen true | debconf-set-selections     && /xt/tools/_ppa_install ppa:webupd8team/java
      ca-certificates oracle-java7-installer     && rm -rf /var/cache/oracle-jdk7-installer
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-7-oracle
    Name: env
  From:
    Image: bigm/base-deb
  Name: ""
  Platform: ""
  SourceCode: FROM bigm/base-deb
