MetaArgs: null
Stages:
- BaseName: python:3.6
  Commands:
  - Maintainer: seaquest
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Name: volume
    Volumes:
    - /conf
  - CmdLine:
    - git clone https://github.com/home-assistant/appdaemon.git .
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install .
    Name: run
    PrependShell: true
  - CmdLine:
    - appdaemon
    - -c
    - /conf
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6
