MetaArgs: null
Stages:
- BaseName: ruby:2.3
  Commands:
  - CmdLine:
    - mkdir /sa_bank_ss
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /sa_bank_ss
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile
    - /sa_bank_ss/Gemfile
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile.lock
    - /sa_bank_ss/Gemfile.lock
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /sa_bank_ss
  From:
    Image: ruby:2.3
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.3
