MetaArgs: null
Stages:
- BaseName: node:7.9.0-alpine
  Commands:
  - Maintainer: Grégoire Weber <gregoire@barracks.io>
    Name: maintainer
  - Env:
    - Key: DEBUG
      Value: "0"
    Name: env
  - Env:
    - Key: BARRACKS_BASE_URL
      Value: '"https://app.barracks.io"'
    Name: env
  - Env:
    - Key: BARRACKS_ENABLE_V2
      Value: "0"
    Name: env
  - Env:
    - Key: BARRACKS_ENABLE_EXPERIMENTAL
      Value: "0"
    Name: env
  - Name: workdir
    Path: /usr/local/lib/barracks-cli
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - .
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/
    - src/
  - CmdLine:
    - ln -s /usr/local/lib/barracks-cli/src/bin/barracks /usr/local/bin/barracks
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - barracks
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:7.9.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM        node:7.9.0-alpine
