MetaArgs: null
Stages:
- BaseName: bitnami/minideb:stretch
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install --yes --no-install-recommends     wget     unzip     make     git     pandoc     pandoc-citeproc     ca-certificates     lmodern     texlive-latex-base     latex-xcolor     texlive-math-extra     texlive-latex-extra     texlive-bibtex-extra     biber     fontconfig     texlive-xetex
      &&     apt-get autoclean && apt-get --purge --yes autoremove &&     rm -rf /var/lib/apt/lists/*
      /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/go-task/task/releases/download/v1.3.1/task_1.3.1_linux_x64.tar.gz
      &&     tar xzf task_1.3.1_linux_x64.tar.gz &&     mv task /usr/local/bin/task
    Name: run
    PrependShell: true
  From:
    Image: bitnami/minideb:stretch
  Name: ""
  Platform: ""
  SourceCode: FROM bitnami/minideb:stretch
