MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: prakash pawar <pracashpawar@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install curl             htop -y
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
