MetaArgs: null
Stages:
- As: build
  BaseName: alpine:3.9
  Commands:
  - Env:
    - Key: HUGO_VERSION
      Value: 0.55.6
    Name: env
  - Env:
    - Key: HUGO_BINARY
      Value: hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    Name: env
  - CmdLine:
    - set -x &&   apk add --update wget ca-certificates &&   wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}
      &&   tar xzf ${HUGO_BINARY} &&   rm -r ${HUGO_BINARY} &&   mv hugo /usr/bin
      &&   apk del wget ca-certificates &&   rm /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /site
  - Name: workdir
    Path: /site
  - CmdLine:
    - /usr/bin/hugo
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.9
  Name: build
  Platform: ""
  SourceCode: FROM alpine:3.9 as build
- BaseName: nginx:alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: Wynand Booysen  <me@wynandbooysen.com>
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./nginx/default.conf
    - /etc/nginx/conf.d/default.conf
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /site/public
    - /var/www/site
  - Name: workdir
    Path: /var/www/site
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
