MetaArgs: null
Stages:
- BaseName: alpine:3.4
  Commands:
  - Maintainer: Alex Kern <alex@pavlov.ai>
    Name: maintainer
  - CmdLine:
    - 'apk --no-cache --update add                             build-base                             ca-certificates                             ruby                             ruby-irb                             ruby-dev
      &&     echo ''gem: --no-document'' >> /etc/gemrc &&     gem install oj &&     gem
      install json &&     gem install fluentd -v 0.14.9 &&     gem install fluent-plugin-s3
      &&     gem install fluent-plugin-loggly &&     gem install fluent-plugin-kubernetes_metadata_filter
      &&     apk del build-base ruby-dev &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/*
      &&     mkdir -p /etc/fluent'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /etc/fluent
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - fluent.conf
    - .
  - Name: expose
    Ports:
    - "24220"
  - CmdLine:
    - fluentd
    - -c
    - fluent.conf
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.4
