MetaArgs: null
Stages:
- BaseName: gliderlabs/alpine:3.1
  Commands:
  - Maintainer: Chris George <chris.a.george at gmail.com>
    Name: maintainer
  - CmdLine:
    - apk --update add python py-pip && mkdir /app && rm -rf /var/cache/apk/* && pip
      install "devpi-server>=2.0.6,<2.1dev" "devpi-client>=2.0.2,<2.1dev"         "requests>=2.4.0,<2.5"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: expose
    Ports:
    - "3141"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /app/
  - CmdLine:
    - sh /app/run.sh
    Name: cmd
    PrependShell: true
  From:
    Image: gliderlabs/alpine:3.1
  Name: ""
  Platform: ""
  SourceCode: FROM gliderlabs/alpine:3.1
