MetaArgs: null
Stages:
- BaseName: ubuntu:bionic
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: YARA_VERSION
      Value: 3.7.1
    Name: env
  - Env:
    - Key: YARA_PY_VERSION
      Value: 3.7.0
    Name: env
  - CmdLine:
    - apt -y update   && apt -y --no-install-recommends install ca-certificates make
      gcc g++ flex bison git automake libtool libmagic-dev libssl-dev   && apt-get
      clean   && rm -rf /var/lib/apt/lists/*   && echo "Install Yara from source..."   &&
      cd /tmp/   && git clone --recursive --branch v$YARA_VERSION https://github.com/VirusTotal/yara.git   &&
      cd /tmp/yara   && ./bootstrap.sh   && sync   && ./configure --with-crypto                  --enable-magic                  --enable-dotnet   &&
      make -j $(nproc)  && make install   && mkdir /rules   && mkdir /malware   &&
      cd /   && rm -rf /tmp/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - bash
    - /entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:bionic
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:bionic
