MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Labels:
    - Key: authors
      Value: '"rickard.hammaren@scilifelab.se, phil.ewels@scilifelab.se"'
    - Key: description
      Value: '"Docker image containing all requirements for NGI-RNAfusion pipeline"'
    Name: label
  - CmdLine:
    - apt-get -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install     build-essential    libncurses5-dev     default-jdk     default-jre     gawk     gcc     g++     bzip2     cmake     automake     make     gzip     zip     unzip     zlibc     zlib1g-dev     zlib1g     wget     curl     pigz     tar     parallel     libtbb-dev     libtbb2     libdb-dev     python     python-dev     python-numpy     python-biopython     python-xlrd     python-openpyxl
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py
      &&     python bootstrap.py -t --download -y &&     rm bootstrap.py
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L https://cpanmin.us | perl - App::cpanminus
    Name: run
    PrependShell: true
  - Env:
    - Key: SRC
      Value: /usr/local/src
    Name: env
  - Env:
    - Key: BIN
      Value: /usr/local/bin
    Name: env
  - Env:
    - Key: DATA
      Value: /usr/local/data
    Name: env
  - CmdLine:
    - mkdir $DATA
    Name: run
    PrependShell: true
  - CmdLine:
    - cpanm install Set::IntervalTree     DB_File     URI::Escape    Carp::Assert    JSON::XS.pm
    Name: run
    PrependShell: true
  - CmdLine:
    - GMAP_URL="http://research-pub.gene.com/gmap/src/gmap-gsnap-2017-01-14.tar.gz"
      &&     cd $SRC &&     wget $GMAP_URL &&     tar xvf gmap-gsnap-2017-01-14.tar.gz
      && rm gmap-gsnap-2017-01-14.tar.gz &&    cd gmap-2017-01-14 && ./configure &&
      make && make install
    Name: run
    PrependShell: true
  - Env:
    - Key: PERL5LIB
      Value: ${STAR_FUSION_HOME}/PerlLib
    Name: env
  - Env:
    - Key: STAR_FUSION_VERSION
      Value: 1.1.0
    Name: env
  - CmdLine:
    - STAR_FUSION_URL="https://github.com/STAR-Fusion/STAR-Fusion/releases/download/v${STAR_FUSION_VERSION}/STAR-Fusion_v${STAR_FUSION_VERSION}.tar.gz"
      &&     cd $SRC &&     wget $STAR_FUSION_URL &&     tar xvf STAR-Fusion_v${STAR_FUSION_VERSION}.tar.gz
      &&  rm STAR-Fusion_v${STAR_FUSION_VERSION}.tar.gz &&     cd STAR-Fusion_v${STAR_FUSION_VERSION}
      && make
    Name: run
    PrependShell: true
  - Env:
    - Key: STAR_FUSION_HOME
      Value: $SRC/STAR-Fusion_v${STAR_FUSION_VERSION}
    Name: env
  - Env:
    - Key: TRINITY_VERSION
      Value: 2.4.0
    Name: env
  - CmdLine:
    - TRINITY_URL="https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v${TRINITY_VERSION}.tar.gz"
      &&    cd $SRC &&    wget $TRINITY_URL &&    tar xvf Trinity-v${TRINITY_VERSION}.tar.gz
      && rm Trinity-v${TRINITY_VERSION}.tar.gz &&   cd trinityrnaseq-Trinity-v${TRINITY_VERSION}
      && make
    Name: run
    PrependShell: true
  - Env:
    - Key: TRINITY_HOME
      Value: /usr/local/src/trinityrnaseq-Trinity-v${TRINITY_VERSION}
    Name: env
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
