MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.9.9
  Commands:
  - Maintainer: Justin Ellison <justin@techadvise.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /build
  - CmdLine:
    - "/build/prepare.sh && \t/build/install.sh && \t/build/cleanup.sh"
    Name: run
    PrependShell: true
  - CmdLine:
    - /sbin/my_init
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "5000"
    - "5001"
    - "5002"
    - "5003"
    - "5004"
    - "5005"
    - "5006"
    - "5006"
    - "5007"
    - "5008"
    - "5009"
    - "5010"
    - "5011"
    - "5012"
    - "5013"
    - "5014"
    - "5015"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init/
    - /etc/my_init.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - services/
    - /etc/service/
  From:
    Image: phusion/baseimage:0.9.9
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.9.9
