MetaArgs: null
Stages:
- As: builder
  BaseName: debian:9
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y       build-essential       gdb       libreadline-dev       python-dev       gcc       g++      git       cmake       libboost-all-dev       librocksdb-dev
      &&     git clone https://github.com/TEMASeK-CryptoCoin/TEMASeK.git /opt/temasek
      &&     cd /opt/temasek &&     mkdir build &&     cd build &&     export CXXFLAGS="-w
      -std=gnu++11" &&     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-fassociative-math"
      -DCMAKE_CXX_FLAGS="-fassociative-math" -DSTATIC=true -DDO_TESTS=OFF .. &&     make
      -j$(nproc)
    Name: run
    PrependShell: true
  From:
    Image: debian:9
  Name: builder
  Platform: ""
  SourceCode: FROM debian:9 as builder
- BaseName: debian:9
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y       libreadline-dev      && rm -rf
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/local/bin && mkdir /var/lib/temasek
    Name: run
    PrependShell: true
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /opt/temasek/build/src/*
    - /usr/local/bin/
  - Name: workdir
    Path: /var/lib/temasek
  - CmdLine:
    - /usr/local/bin/TEMASeK
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --no-console
    - --data-dir
    - /var/lib/temasek
    - --rpc-bind-ip
    - 0.0.0.0
    - --rpc-bind-port
    - "13002"
    - --p2p-bind-port
    - "13001"
    Name: cmd
    PrependShell: false
  From:
    Image: debian:9
  Name: ""
  Platform: ""
  SourceCode: FROM debian:9
