MetaArgs: null
Stages:
- BaseName: rust:slim
  Commands:
  - CmdLine:
    - mkdir /code
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - src/
    - src/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Cargo.lock
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Cargo.toml
    - .
  - CmdLine:
    - cargo install
    Name: run
    PrependShell: true
  From:
    Image: rust:slim
  Name: ""
  Platform: ""
  SourceCode: FROM rust:slim
- BaseName: debian:stretch-slim
  Commands:
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /usr/local/cargo/bin/process-uwsgi-logs
    - /usr/bin/process-uwsgi-logs
  - CmdLine:
    - /usr/bin/process-uwsgi-logs
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:stretch-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stretch-slim
