MetaArgs: null
Stages:
- As: builder-go
  BaseName: golang:1.12.5-alpine3.9
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /go/src/ams
  - Name: workdir
    Path: /go/src/ams
  - CmdLine:
    - set -ex && go build .
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12.5-alpine3.9
  Name: builder-go
  Platform: ""
  SourceCode: FROM golang:1.12.5-alpine3.9 as builder-go
- BaseName: alpine:3.9
  Commands:
  - Chown: ""
    From: builder-go
    Name: copy
    SourcesAndDest:
    - /go/src/ams/ams
    - /usr/local/bin/ams
  - Name: workdir
    Path: /var/ams
  - CmdLine:
    - ams
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:3.9
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.9
