MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Christoph <christoph@megusta.ag>
    Name: maintainer
  - Env:
    - Key: CREATED_AT
      Value: 15-01-03
    Name: env
  - Name: expose
    Ports:
    - "7777"
    - "8080"
  - Expression: EXPOSE 8080 7777
    Name: onbuild
  - Expression: RUN rm -rf /home/mega/tomcat/webapps && mkdir -p /home/mega/tomcat/webapps
    Name: onbuild
  - Expression: COPY *.war /home/mega/tomcat/webapps/
    Name: onbuild
  - Expression: USER root
    Name: onbuild
  - Expression: RUN chown -R mega:mega /home/mega
    Name: onbuild
  - Expression: WORKDIR /home/mega/tomcat
    Name: onbuild
  - Expression: USER mega
    Name: onbuild
  - Expression: ENV HOME /home/mega
    Name: onbuild
  - CmdLine:
    - /home/mega/tomcat/run.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apt-get update -qq &&     apt-get upgrade -qqy &&     apt-get install  --no-install-recommends
      git-core zip unzip wget curl software-properties-common pwgen ca-certificates
      nano screen nginx apache2-utils -qqy &&     add-apt-repository ppa:webupd8team/java
      -y &&     apt-get update -qq &&     $(echo oracle-java7-installer shared/accepted-oracle-license-v1-1
      select true | /usr/bin/debconf-set-selections) &&     apt-get install oracle-java7-installer
      -qqy &&     apt-get install oracle-java7-set-default -qqy &&     apt-get clean
      -qqy && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     adduser mega --home
      /home/mega --gecos "" --disabled-password &&     $(echo "mega:mega" | chpasswd)
      &&     usermod -a -G sudo mega &&     bash -c "echo 'mega ALL=(ALL) NOPASSWD:ALL'
      >> /etc/sudoers"
    Name: run
    PrependShell: true
  - Name: user
    User: mega
  - Env:
    - Key: HOME
      Value: /home/mega
    Name: env
  - Name: workdir
    Path: /home/mega
  - Env:
    - Key: TOMCAT_MAJOR_VERSION
      Value: "7"
    Name: env
  - Env:
    - Key: TOMCAT_MINOR_VERSION
      Value: 7.0.57
    Name: env
  - Env:
    - Key: CATALINA_HOME
      Value: /home/mega/tomcat
    Name: env
  - CmdLine:
    - wget -q https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz
      &&     wget -qO- https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.md5
      | md5sum -c - &&     tar zxf apache-tomcat-*.tar.gz &&     rm apache-tomcat-*.tar.gz
      &&     mv apache-tomcat* tomcat &&     rm -rf tomcat/webapps/ROOT && rm -rf
      tomcat/webapps/examples && rm -rf tomcat/webapps/docs
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/mega/tomcat
  - Chown: ""
    Name: add
    SourcesAndDest:
    - create_tomcat_admin_user.sh
    - /home/mega/tomcat/create_tomcat_admin_user.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /home/mega/tomcat/run.sh
  - Name: user
    User: root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - setenv.sh
    - /home/mega/tomcat/bin/setenv.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - appenv.sh
    - /home/mega/tomcat/bin/appenv.sh
  - CmdLine:
    - chown -R mega:mega /home/mega
    Name: run
    PrependShell: true
  - Name: user
    User: mega
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
