MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Axel Siebenborn <axel.siebenborn@sap.com>
    Name: maintainer
  - CmdLine:
    - rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get update     && apt-get
      install -y --no-install-recommends curl ca-certificates     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_VERSION
      Value: jdk-10+32
    Name: env
  - CmdLine:
    - set -eux;    cd /tmp;    curl -Lso sapmachine_linux-x64-jdk-10.32.tar.gz https://github.com/SAP/SapMachine/releases/download/jdk-10%2B32/sapmachine_linux-x64-jdk-10.32.tar.gz;    curl
      -Ls https://github.com/SAP/SapMachine/releases/download/jdk-10%2B32/sapmachine_linux-x64-jdk-10.32.sha256.txt
      | sha256sum -c -;    mkdir -p /opt/java/sapmachine;    cd /opt/java/sapmachine;    tar
      -xf /tmp/sapmachine_linux-x64-jdk-10.32.tar.gz;    rm -f /tmp/sapmachine_linux-x64-jdk-10.32.tar.gz;
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/java/sapmachine/jdk/bin:$PATH
    Name: env
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
