MetaArgs: null
Stages:
- BaseName: rocker/r-ver:3.5.2
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y     sudo     gdebi-core     pandoc     pandoc-citeproc     libcurl4-gnutls-dev     libcairo2-dev     libxt-dev     xtail     wget
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --no-verbose https://download3.rstudio.org/ubuntu-14.04/x86_64/VERSION
      -O "version.txt" &&     VERSION=$(cat version.txt)  &&     wget --no-verbose
      "https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-$VERSION-amd64.deb"
      -O ss-latest.deb &&     gdebi -n ss-latest.deb &&     rm -f version.txt ss-latest.deb
      &&     . /etc/environment &&     R -e "install.packages(c('shiny', 'rmarkdown'),
      repos='$MRAN')" &&     cp -R /usr/local/lib/R/site-library/shiny/examples/*
      /srv/shiny-server/
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3838"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - shiny-server.sh
    - /usr/bin/shiny-server.sh
  - CmdLine:
    - /usr/bin/shiny-server.sh
    Name: cmd
    PrependShell: false
  From:
    Image: rocker/r-ver:3.5.2
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/r-ver:3.5.2
