MetaArgs: null
Stages:
- BaseName: node:12.13-slim
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"development@minddoc.com"'
    Name: label
  From:
    Image: node:12.13-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:12.13-slim
