MetaArgs: null
Stages:
- BaseName: debian:stretch
  Commands:
  - Maintainer: cnaranjo@nsoporte.com
    Name: maintainer
  - CmdLine:
    - apt-get update; apt-get -y upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install apache2
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 80/tcp
  - CmdLine:
    - "cd /etc/apache2; \t\t\ttar -czvf /opt/config.tgz *; \t\t\trm -rf /etc/apache2;
      \t\t\tmkdir /log /config /html; \t\t\tmv /var/www/html/index.html /opt; \t\t\trm
      -rf /var/www/html; \t\t\tln -s /html /var/www/html; \t\t\tln -s /config /etc/apache2;
      \t\t\trm -rf /var/log/apache2; \t\t\tln -s /log /var/log/apache2; \t\t\tchown
      -R www-data.www-data /log; \t\t\tchown -R www-data.www-data /config; \t\t\tchown
      -R www-data.www-data /html"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/ns-start
    - /usr/bin/
  - CmdLine:
    - chmod +x /usr/bin/ns-start
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/ns-start
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:stretch
  Name: ""
  Platform: ""
  SourceCode: "FROM\t\tdebian:stretch"
