MetaArgs: null
Stages:
- BaseName: php:7.0-apache
  Commands:
  - CmdLine:
    - apt-get -y update && apt-get install -y     wget     git     zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install zip
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/DocumentRoot .*$/DocumentRoot \/var\/www\/html\/web/' /etc/apache2/sites-available/000-default.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/www/.composer && chown www-data:www-data /var/www/.composer
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /var/www/html/
  - CmdLine:
    - chown -R www-data:www-data /var/www/html
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /var/www/html     && bash scripts/install-composer.sh     && php composer.phar
      install
    Name: run
    PrependShell: true
  From:
    Image: php:7.0-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.0-apache
