MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Maintainer: Sergii Nuzhdin <ipaq.lw@gmail.com@gmail.com>
    Name: maintainer
  - Env:
    - Key: KUBE_LATEST_VERSION
      Value: '"v1.5.2"'
    Name: env
  - CmdLine:
    - apk add --update ca-certificates  && apk add -t deps curl  && apk add gettext
      openssh  && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl
      -o /usr/local/bin/kubectl  && chmod +x /usr/local/bin/kubectl  && apk del --purge
      deps  && rm /var/cache/apk/*
    Name: run
    PrependShell: true
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
