MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Uta Kapp "uta.kapp@emooti.org"
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install curl vim git maven
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install openjdk-7-jre
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install tomcat7 tomcat7-admin
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - Env:
    - Key: CATALINA_HOME
      Value: /usr/share/tomcat7
    Name: env
  - Env:
    - Key: CATALINA_BASE
      Value: /var/lib/tomcat7
    Name: env
  - Env:
    - Key: CATALINA_PID
      Value: /var/run/tomcat7.pid
    Name: env
  - Env:
    - Key: CATALINA_SH
      Value: /usr/share/tomcat7/bin/catalina.sh
    Name: env
  - Env:
    - Key: CATALINA_TMPDIR
      Value: /tmp/tomcat7-tomcat7-tmp
    Name: env
  - CmdLine:
    - mkdir -p $CATALINA_TMPDIR
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/lib/tomcat7/webapps/
  - CmdLine:
    - mkdir -p /usr/share/tomcat7/logs
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -R /var/lib/tomcat7/common/ /usr/share/tomcat7/common/
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -R /var/lib/tomcat7/server/ /usr/share/tomcat7/server/
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -R /var/lib/tomcat7/shared/ /usr/share/tomcat7/shared/
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i -- 's/<Context>/<Context reloadable="true">/g' /var/lib/tomcat7/conf/context.xml
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
