MetaArgs: null
Stages:
- BaseName: mysql:latest
  Commands:
  - Key: sakila_file
    Name: arg
    Value: null
  - Key: db_name
    Name: arg
    Value: null
  - Env:
    - Key: MYSQL_DATABASE
      Value: ${db_name}
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ${sakila_file}
    - /docker-entrypoint-initdb.d/
  From:
    Image: mysql:latest
  Name: ""
  Platform: ""
  SourceCode: FROM mysql:latest
