MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Env:
    - Key: POSTGREST_VERSION
      Value: 0.3.2.0
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get install -y tar xz-utils wget libpq-dev &&     apt-get
      clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://github.com/begriffs/postgrest/releases/download/v${POSTGREST_VERSION}/postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
      &&     tar --xz -xvf postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz &&     mv
      postgrest /usr/local/bin/postgrest &&     rm postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chmod +x entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
