MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: paoloburelli
    Name: maintainer
  - CmdLine:
    - echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
    Name: run
    PrependShell: true
  - CmdLine:
    - gpg -a --export E084DAB9 | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y   r-base   r-recommended   r-base-dev   libcurl4-gnutls-dev   libxml2-dev   libmime-base64-urlsafe-perl   libdigest-hmac-perl   libdigest-sha-perl   libssl-dev   libapparmor1   libpq-dev   wget
    Name: run
    PrependShell: true
  - CmdLine:
    - R --version
    Name: run
    PrependShell: true
  - CmdLine:
    - R -e "install.packages('packrat', repos='http://cran.r-project.org')"
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -r rserve && useradd -r -g rserve rserve
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start.R
    - start.R
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Rserv.conf
    - /Rserv.conf
  - CmdLine:
    - mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Expression: COPY *.R *.r /usr/src/app/
    Name: onbuild
  - Expression: RUN chown -R rserve:rserve /usr/src/app
    Name: onbuild
  - Expression: RUN su rserve -c "R -e \"packrat::init();\""
    Name: onbuild
  - Expression: RUN su rserve -c "R -e \"install.packages('Rserve', repos='http://cran.r-project.org')\""
    Name: onbuild
  - CmdLine:
    - Rscript
    - /start.R
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "6311"
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
