MetaArgs:
- DefaultValue: latest
  Key: version
  ProvidedValue: null
  Value: latest
Stages:
- BaseName: arcor2/arcor2_base:$version
  Commands:
  - CmdLine:
    - ln -s /root/arcor2/docker/start-execution.sh /start.sh
    Name: run
    PrependShell: true
  From:
    Image: arcor2/arcor2_base:$version
  Name: ""
  Platform: ""
  SourceCode: FROM arcor2/arcor2_base:$version
