MetaArgs: null
Stages:
- BaseName: composer:1.7
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /src/app/
  - Name: workdir
    Path: /src/app
  - CmdLine:
    - composer install &&   cp includes/config.environment.inc.php includes/config.inc.php
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - php
    - -S
    - 0.0.0.0:80
    Name: entrypoint
    PrependShell: false
  From:
    Image: composer:1.7
  Name: ""
  Platform: ""
  SourceCode: FROM composer:1.7
