MetaArgs: null
Stages:
- BaseName: elixir:1.5.3
  Commands:
  - CmdLine:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&   apt-get install -y apt-utils &&   apt-get upgrade -y &&   apt-get
      install -y inotify-tools &&   curl -sL https://deb.nodesource.com/setup_7.x
      | bash - &&   apt-get install -y nodejs &&   apt-get clean &&   cd /var/lib/apt/lists
      && rm -fr *Release* *Sources* *Packages* &&   truncate -s 0 /var/log/*log
    Name: run
    PrependShell: true
  - Env:
    - Key: PHOENIX_VERSION
      Value: '""'
    Name: env
  - CmdLine:
    - echo "Phoenix 1.3.0" &&   mix local.hex --force &&   mix local.rebar --force
      &&   mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez
    Name: run
    PrependShell: true
  - Env:
    - Key: MYAPP_DIR
      Value: '"/myapp"'
    Name: env
  - Env:
    - Key: MIX_ENV
      Value: '"prod"'
    Name: env
  - CmdLine:
    - iex
    Name: cmd
    PrependShell: false
  From:
    Image: elixir:1.5.3
  Name: ""
  Platform: ""
  SourceCode: FROM elixir:1.5.3
