MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - CmdLine:
    - apt-get -qq update && apt-get -qqy upgrade && apt-get autoclean
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -qqy build-essential curl wget git && apt-get autoclean
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/
      /' >> /etc/apt/sources.list.d/fish.list
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -Ls http://download.opensuse.org/repositories/shells:fish:release:2/Debian_7.0/Release.key
      | apt-key add -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -qq && apt-get install -qqy fish && apt-get autoclean
    Name: run
    PrependShell: true
  - CmdLine:
    - chsh -s /usr/bin/fish
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -Ls https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz |
      tar -xz -C /tmp &&    make -C /tmp/ruby-install-0.5.0/ install &&    rm -rf
      /tmp/ruby-install-0.5.0
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -Ls https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz | tar -xz
      -C /tmp &&    make -C /tmp/chruby-0.3.9/ install &&    rm -rf /tmp/chruby-0.3.9
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -Ls https://github.com/JeanMertz/chruby-fish/archive/v0.6.0.tar.gz | tar
      -xz -C /tmp &&    make -C /tmp/chruby-fish-0.6.0/ install &&    rm -rf /tmp/chruby-fish-0.6.0
      &&    echo 'source /usr/local/share/chruby/chruby.fish' >> /etc/fish/config.fish
      &&    echo 'source /usr/local/share/chruby/auto.fish' >> /etc/fish/config.fish
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -qqy zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev
      libncurses5-dev libffi-dev &&    apt-get autoclean
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -m -p dev -s /usr/bin/fish dev
    Name: run
    PrependShell: true
  - CmdLine:
    - su -l dev -c 'ruby-install ruby 2.2.2 --no-install-deps' &&    su -l dev -c
      "rm -rf ~/src" &&    su -l dev -c "echo '2.2.2' > ~/.ruby-version"
    Name: run
    PrependShell: true
  - CmdLine:
    - su -l dev -c 'ruby-install ruby 2.1.6 --no-install-deps' &&    su -l dev -c
      "rm -rf ~/src"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libpq-dev libmysqlclient-dev && apt-get autoclean
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
