MetaArgs: null
Stages:
- BaseName: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  Commands:
  - Maintainer: cwl233@mail.ustc.edu.cn
    Name: maintainer
  From:
    Image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  Name: ""
  Platform: ""
  SourceCode: FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
