MetaArgs: null
Stages:
- BaseName: python:2-alpine
  Commands:
  - CmdLine:
    - apk --no-cache add openldap-dev     && apk --no-cache add --virtual build-dependencies
      build-base curl     && pip install python-ldap     && mkdir -p /usr/src/nginx-ldap-auth     &&
      curl -fSL https://github.com/nginxinc/nginx-ldap-auth/archive/master.tar.gz
      -o /usr/src/nginx-ldap-auth.tar.gz     && tar -zxC /usr/src/nginx-ldap-auth
      -f /usr/src/nginx-ldap-auth.tar.gz --strip 1     && cp /usr/src/nginx-ldap-auth/nginx-ldap-auth-daemon.py
      /     && rm -rf /usr/src/nginx-ldap-auth     && apk del build-dependencies
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8888"
  - CmdLine:
    - python
    - /nginx-ldap-auth-daemon.py
    - --host
    - 0.0.0.0
    - --port
    - "8888"
    Name: cmd
    PrependShell: false
  From:
    Image: python:2-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:2-alpine
