MetaArgs: null
Stages:
- BaseName: opensciencegrid/osg-wn:3.3-el7
  Commands:
  - CmdLine:
    - curl -o /etc/yum.repos.d/djw8605-GRACC-epel-7.repo https://copr.fedorainfracloud.org/coprs/djw8605/GRACC/repo/epel-7/djw8605-GRACC-epel-7.repo
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install python-setuptools python2-pika python-dateutil python-toml python-filelock
      gracc-request
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /gracc-summary
  - Name: workdir
    Path: /gracc-summary
  - CmdLine:
    - python setup.py install
    Name: run
    PrependShell: true
  - CmdLine:
    - install -d -m 0755 /etc/graccsum/config.d/ && install -m 0744 config/gracc-summary.toml
      /etc/graccsum/config.d/gracc-summary.toml
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/graccsumperiodic -c /etc/graccsum/config.d/gracc-summary.toml
    Name: cmd
    PrependShell: true
  From:
    Image: opensciencegrid/osg-wn:3.3-el7
  Name: ""
  Platform: ""
  SourceCode: FROM opensciencegrid/osg-wn:3.3-el7
