MetaArgs: null
Stages:
- BaseName: jupincu/centos:latest
  Commands:
  - Maintainer: Nopost(nopost@qq.com)
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - container-files
    - /
  - CmdLine:
    - cd /install && sh ./docker_build.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /config/bootstrap.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: jupincu/centos:latest
  Name: ""
  Platform: ""
  SourceCode: FROM jupincu/centos:latest
