MetaArgs: null
Stages:
- BaseName: ubuntu:utopic
  Commands:
  - Maintainer: team@lastbackend.com
    Name: maintainer
  - CmdLine:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install openssh-server
      pwgen
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/run/sshd && sed -i "s/UsePrivilegeSeparation.*/UsePrivilegeSeparation
      no/g" /etc/ssh/sshd_config && sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config
      && sed -i "s/PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init.sh
    - /init.sh
  - CmdLine:
    - chmod +x /*.sh
    Name: run
    PrependShell: true
  - Env:
    - Key: AUTHORIZED_KEYS
      Value: '**None**'
    Name: env
  - Name: expose
    Ports:
    - "22"
  - CmdLine:
    - /init.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:utopic
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:utopic
