MetaArgs: null
Stages:
- BaseName: python:3-alpine
  Commands:
  - Maintainer: Jamotion <info@jamotion.ch>
    Name: maintainer
  - CmdLine:
    - pip install --no-cache-dir jinja2
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/migrator/migrator
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/migrator/data
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - migrator
    - /opt/migrator/migrator
  - Chown: ""
    Name: add
    SourcesAndDest:
    - migrate_repository.py
    - /opt/migrator/
  - CmdLine:
    - chmod 0666 /opt/migrator/migrate_repository.py
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/migrator/data
  - Name: volume
    Volumes:
    - /opt/migrator/data
  - CmdLine:
    - python
    - /opt/migrator/migrate_repository.py
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -h
    Name: cmd
    PrependShell: false
  From:
    Image: python:3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3-alpine
