MetaArgs: null
Stages:
- BaseName: python:3.5-alpine
  Commands:
  - Maintainer: Kentaro.Maeda
    Name: maintainer
  - CmdLine:
    - apk add --no-cache --update clamav supervisor &&    (rm "/tmp/"* 2>/dev/null
      || true) && (rm -rf /var/cache/apk/* 2>/dev/null || true)
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisord.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - clamav/clamd.conf
    - /etc/clamav/clamd.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - clamav/crontab
    - /var/spool/cron/crontabs/root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - clamav/runclamd.sh
    - /app
  - Name: volume
    Volumes:
    - /var/lib/clamav
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app/requirements.txt
    - /app
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app/app.py
    - /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app/runapp.sh
    - /app
  - Env:
    - Key: PORT
      Value: "8080"
    Name: env
  - Env:
    - Key: AUTH_USER
      Value: user
    Name: env
  - Env:
    - Key: AUTH_PASSWORD
      Value: password
    Name: env
  - Name: expose
    Ports:
    - $PORT
  - CmdLine:
    - /usr/bin/supervisord
    - -c
    - /etc/supervisord.conf
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.5-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.5-alpine
