MetaArgs: null
Stages:
- BaseName: skiftcreative/gunicorn:3.4
  Commands:
  - Maintainer: Shawn McElroy <shawn@skift.io>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache nginx &&     rm -f /etc/nginx/nginx.conf
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/nginx.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/conf.d/
  - Name: expose
    Ports:
    - "80"
  From:
    Image: skiftcreative/gunicorn:3.4
  Name: ""
  Platform: ""
  SourceCode: FROM skiftcreative/gunicorn:3.4
