MetaArgs: null
Stages:
- BaseName: postgres:10-alpine
  Commands:
  - Maintainer: Sergey Lugovoy <pelenthium@gmail.com>
    Name: maintainer
  - Name: volume
    Volumes:
    - /var/backups
  - Env:
    - Key: BACKUP_DIR
      Value: /var/backups
    Name: env
  - CmdLine:
    - "apk add curl && \trm /var/cache/apk/* && \twget https://raw.github.com/selectel/supload/master/supload.sh
      && \tmv supload.sh /usr/local/bin/supload && \tchmod +x /usr/local/bin/supload"
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sbackup.sh
    - /usr/local/bin/sbackup
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /usr/local/bin
  - CmdLine:
    - /usr/local/bin/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - crond -f -d 8 -L /var/log/cron.log
    Name: cmd
    PrependShell: true
  From:
    Image: postgres:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:10-alpine
