MetaArgs: null
Stages:
- BaseName: postgres:9.3
  Commands:
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - set_acl.sh
    - /docker-entrypoint-initdb.d/
  From:
    Image: postgres:9.3
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.3
