MetaArgs: null
Stages:
- BaseName: tutum/lamp
  Commands:
  - Maintainer: Daniel Romero <infoslack@gmail.com>
    Name: maintainer
  - Env:
    - Key: VERSION
      Value: "1.9"
    Name: env
  - CmdLine:
    - rm -rf /app &&     apt-get update &&     apt-get install -y wget php5-gd &&     rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/*
    - /tmp/
  - CmdLine:
    - wget https://github.com/ethicalhack3r/DVWA/archive/v${VERSION}.tar.gz &&     tar
      xvf /v${VERSION}.tar.gz &&     mv -f /DVWA-${VERSION} /app &&     rm /app/.htaccess
      &&     mv /tmp/.htaccess /app &&     chmod +x /tmp/setup_dvwa.sh &&     /tmp/setup_dvwa.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3306"
    - "80"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: tutum/lamp
  Name: ""
  Platform: ""
  SourceCode: FROM tutum/lamp
