MetaArgs: null
Stages:
- BaseName: nginx:latest
  Commands:
  - CmdLine:
    - mkdir -p /var/cache/tile/tmp
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/conf.d/default.conf
  - Name: volume
    Volumes:
    - /var/cache/tile
  From:
    Image: nginx:latest
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:latest
