MetaArgs: null
Stages:
- As: builder
  BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y         git         build-essential         autoconf
    Name: run
    PrependShell: true
  - Key: GIFSICLE_BRANCH
    Name: arg
    Value: '"v1.92"'
  - CmdLine:
    - git clone --branch $GIFSICLE_BRANCH https://github.com/kohler/gifsicle.git /gifsicle
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /gifsicle
  - CmdLine:
    - autoreconf -i
    Name: run
    PrependShell: true
  - CmdLine:
    - ./configure --disable-gifview --disable-gifdiff
    Name: run
    PrependShell: true
  - CmdLine:
    - make
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: builder
  Platform: ""
  SourceCode: FROM ubuntu as builder
- BaseName: node
  Commands:
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /gifsicle
    - /gifsicle
  - CmdLine:
    - cd /gifsicle &&     make install
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex &&   apt-get update &&   apt-get -y install ffmpeg imagemagick curl
    Name: run
    PrependShell: true
  - CmdLine:
    - npm i -g gifify
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /data
  - CmdLine:
    - gifify
    Name: entrypoint
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
