MetaArgs: null
Stages:
- BaseName: cypress/browsers:chrome69
  Commands:
  - Key: NPM_TOKEN
    Name: arg
    Value: null
  - Key: NPM_REGISTRY
    Name: arg
    Value: https://registry.npmjs.org
  - Key: SONAR_TOKEN
    Name: arg
    Value: null
  - Key: SONAR_HOST
    Name: arg
    Value: '''http://localhost:9000'''
  - Key: SONAR_CLI_VERSION
    Name: arg
    Value: '''3.3.0.1492'''
  - Key: SONAR_SCANNER_OPTS
    Name: arg
    Value: '''-Xmx512m'''
  - Env:
    - Key: NPM_TOKEN
      Value: $NPM_TOKEN
    - Key: NPM_REGISTRY
      Value: $NPM_REGISTRY
    - Key: SONAR_TOKEN
      Value: $SONAR_TOKEN
    - Key: SONAR_HOST
      Value: $SONAR_HOST
    - Key: SONAR_SCANNER_OPTS
      Value: $SONAR_SCANNER_OPTS
    - Key: SPAWN_WRAP_SHIM_ROOT
      Value: /tmp
    - Key: NPM_CONFIG_USERCONFIG
      Value: /tmp/.npmrc
    - Key: NPM_CONFIG_CACHE
      Value: /tmp/npmcache
    - Key: NO_UPDATE_NOTIFIER
      Value: "true"
    - Key: PATH
      Value: '"$PATH:/tmp/sonar/sonar-scanner-${SONAR_CLI_VERSION}-linux/bin"'
    Name: env
  - CmdLine:
    - "apt-get install -y git unzip wget dbus libgles2-mesa libegl1-mesa \t&& printf
      \"[user]\\n\\temail=${GIT_AUTHOR_EMAIL}\\n\\tname=${GIT_AUTHOR_NAME}\" >> /.gitconfig;
      \tmkdir /var/run/dbus && chmod 777 /var/run/dbus; \tmkdir -p /var/lib/jenkins
      && chmod 777 /var/lib/jenkins; \tmkdir /var/lib/jenkins/.config && chmod 777
      /var/lib/jenkins/.config; \tmkdir /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix
      && chown root /tmp/.X11-unix/; \tmkdir -p /tmp/npmcache && mkdir -p /tmp/sonar
      && chmod -R 777 /tmp/npmcache && chmod -R 777 /tmp/sonar; \ttouch ${NPM_CONFIG_USERCONFIG}
      && chmod 777 ${NPM_CONFIG_USERCONFIG}; \twget -q -P /tmp/sonar https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_CLI_VERSION}-linux.zip
      \t&& unzip -q /tmp/sonar/sonar-scanner-cli-${SONAR_CLI_VERSION}-linux.zip -d
      /tmp/sonar \t&& printf \"registry=${NPM_REGISTRY}\\n_authToken=${NPM_TOKEN}\"
      >> ${NPM_CONFIG_USERCONFIG}"
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: cypress/browsers:chrome69
  Name: ""
  Platform: ""
  SourceCode: FROM cypress/browsers:chrome69
