MetaArgs: null
Stages:
- BaseName: python:3-alpine
  Commands:
  - Maintainer: https://github.com/ymping/
    Name: maintainer
  - Env:
    - Key: DEVPI_SERVER_VERSION
      Value: 4.4.0
    - Key: DEVPI_WEB_VERSION
      Value: 3.2.2
    - Key: DEVPI_CLIENT_VERSION
      Value: 4.0.0
    - Key: DEVPI_PASSWORD
      Value: devpipass
    - Key: DEVPI_SERVERDIR
      Value: /data/server
    - Key: DEVPI_CLIENTDIR
      Value: /data/client
    - Key: MIRROR_URL
      Value: https://pypi.doubanio.com/simple/
    Name: env
  - CmdLine:
    - apk add --no-cache build-base libffi-dev bash
    Name: run
    PrependShell: true
  - CmdLine:
    - "pip install --no-cache \t\"devpi-client==${DEVPI_CLIENT_VERSION}\" \t\"devpi-web==${DEVPI_WEB_VERSION}\"
      \t\"devpi-server==${DEVPI_SERVER_VERSION}\""
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3141"
  - Name: volume
    Volumes:
    - /data
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - devpi
    Name: cmd
    PrependShell: false
  From:
    Image: python:3-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:3-alpine
