MetaArgs: null
Stages:
- BaseName: anapsix/alpine-java:jre8
  Commands:
  - Maintainer: Anastas Dancha "anapsix@random.io"
    Name: maintainer
  - Env:
    - Key: JENKINS_HOME
      Value: /opt/jenkins
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://mirrors.jenkins-ci.org/war/latest/jenkins.war
    - /srv/jenkins.war
  - Name: volume
    Volumes:
    - /opt/jenkins
  - Name: expose
    Ports:
    - 22/tcp
    - 8080/tcp
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - java
    - -jar
    - /srv/jenkins.war
    Name: cmd
    PrependShell: false
  From:
    Image: anapsix/alpine-java:jre8
  Name: ""
  Platform: ""
  SourceCode: FROM anapsix/alpine-java:jre8
