MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Ben Roberts <ben@headsnet.com>"'
    Name: label
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts
    - /scripts
  - CmdLine:
    - /scripts/install-packages.sh &&     /scripts/ensure-www-data.sh &&     apk --no-cache
      add php7-fpm &&     rm -rf /scripts
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - www.conf
    - /etc/php7/php-fpm.d/www.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - php.ini
    - /etc/php7/conf.d/99_app.ini
  - CmdLine:
    - '{         echo "alias ls=''ls --color=auto''";         echo "alias ll=''ls
      --color=auto -alF''";         echo "alias la=''ls --color=auto -A''";         echo
      "alias l=''ls --color=auto -CF''";     } >> ~/.bashrc'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /var/www/app
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - php-fpm7
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
