MetaArgs: null
Stages:
- BaseName: alpine:3.7
  Commands:
  - Env:
    - Key: VERSION
      Value: v1.6-rc5
    Name: env
  - Name: workdir
    Path: /srv
  - CmdLine:
    - set -xe &&     mkdir /config &&     apk add --no-cache unzip curl ca-certificates
      &&     curl -fsSLO --compressed "https://github.com/shawn1m/overture/releases/download/${VERSION}/overture-linux-amd64.zip"
      &&     unzip -o "overture-linux-amd64.zip" -d /srv &&     rm -rf "overture-linux-amd64.zip"
      &&     cp /srv/config.json /config/ &&     apk del unzip curl
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /config
  - CmdLine:
    - /srv/overture-linux-amd64
    - -c
    - /config/config.json
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
