MetaArgs: null
Stages:
- As: builder
  BaseName: golang:latest
  Commands:
  - Name: workdir
    Path: /go/src/github.com/KEXPCapstone/shelves-server/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Name: workdir
    Path: /go/src/github.com/KEXPCapstone/shelves-server/gateway
  - CmdLine:
    - go get -v ./...
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gatewaysvc .
    Name: run
    PrependShell: true
  From:
    Image: golang:latest
  Name: builder
  Platform: ""
  SourceCode: FROM golang:latest as builder
- As: runner
  BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk add --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/
  - Name: expose
    Ports:
    - "443"
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/KEXPCapstone/shelves-server/gateway
    - .
  - CmdLine:
    - ./gatewaysvc
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: runner
  Platform: ""
  SourceCode: FROM alpine:latest as runner
