MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"tsubasatakayama511@gmail.com"'
    Name: label
  - CmdLine:
    - apt-get update &&     apt-get install -y         cloud-utils &&     apt-get
      clean
    Name: run
    PrependShell: true
  - CmdLine:
    - write-mime-multipart
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
