MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: amanoese
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y vim
    Name: run
    PrependShell: true
  - CmdLine:
    - touch /sample-file
    Name: run
    PrependShell: true
  - CmdLine:
    - bash
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
