MetaArgs: null
Stages:
- BaseName: alpine:3.6
  Commands:
  - CmdLine:
    - apk add --no-cache git curl wget bash python py-pip tar gzip ca-certificates
      python-dev libffi-dev openssl-dev gcc musl-dev nano
    Name: run
    PrependShell: true
  - CmdLine:
    - "apk add --no-cache \t\topenjdk8-jre \t\topenjdk8-jre-base \t\topenjdk8-jre-lib
      \t\tjava-cacerts \t\topenjdk8"
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/hexabin/APKStat.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /APKStat/
  - CmdLine:
    - wget "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
      -O /usr/local/bin/apktool
    Name: run
    PrependShell: true
  - CmdLine:
    - wget "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.4.jar"
      -O /usr/local/bin/apktool.jar
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 777 /usr/local/bin/apktool
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 777 apkstat.py
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.6
