MetaArgs: null
Stages:
- BaseName: nginx:1.11
  Commands:
  - Maintainer: Bertrand Roussel "bertrand.roussel@cor-net.org"
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get install -y dnsmasq
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "\n\n# Docker extra config \nuser=root\naddn-hosts=/etc/hosts\n" >> /etc/dnsmasq.conf
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "80"
  - CmdLine:
    - service dnsmasq restart && nginx -g "daemon off;"
    Name: cmd
    PrependShell: true
  From:
    Image: nginx:1.11
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:1.11
