MetaArgs: null
Stages:
- BaseName: node:7
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y graphicsmagick && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/skins
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/skins
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - yarn
    Name: run
    PrependShell: true
  - CmdLine:
    - npm rebuild && yarn start
    Name: cmd
    PrependShell: true
  From:
    Image: node:7
  Name: ""
  Platform: ""
  SourceCode: FROM node:7
