MetaArgs: null
Stages:
- BaseName: ubuntu:15.04
  Commands:
  - Maintainer: Sebastien Langoureaux <linuxworkgroup@hotmail.com>
    Name: maintainer
  - Env:
    - Key: NODEJS_VERSION
      Value: "0.12"
    Name: env
  - Env:
    - Key: NVM_VERSION
      Value: 0.25.4
    Name: env
  - Env:
    - Key: NVM_DIR
      Value: /usr/local/nvm
    Name: env
  - Env:
    - Key: INTELLIJ_VERSION
      Value: 14.1.4
    Name: env
  - Env:
    - Key: TOMCAT_VERSION
      Value: 7.0.64
    Name: env
  - Env:
    - Key: TOMCAT_FAMILLY
      Value: "7"
    Name: env
  - CmdLine:
    - rm /bin/sh && ln -s /bin/bash /bin/sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get upgrade -y &&     apt-get install software-properties-common
      gcc make build-essential -y &&     apt-get install openjdk-7-jdk maven mysql-client
      -y &&     apt-get install curl git unzip xfce4-terminal -y &&     apt-get install
      python2.7 python2.7-dev python-pip python-virtualenv python-tox libffi-dev coreutils
      -y &&     update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX &&     locale-gen en_US.UTF-8
      &&     dpkg-reconfigure locales
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_${NODEJS_VERSION} | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g npm@2.14.6
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g async
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g yo bower grunt-cli gulp ember-cli watchman
    Name: run
    PrependShell: true
  - CmdLine:
    - curl http://download.jetbrains.com/idea/ideaIU-${INTELLIJ_VERSION}.tar.gz -Lo
      "/tmp/intellij.tar.gz"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/intellij
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -xf /tmp/intellij.tar.gz --strip-components=1 -C /opt/intellij
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /tmp/intellij.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/intellij/bin/idea.sh /usr/bin/idea
    Name: run
    PrependShell: true
  - CmdLine:
    - curl http://mirrors.ircam.fr/pub/apache/tomcat/tomcat-7/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz
      -Lo "/tmp/tomcat.tar.gz"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/tomcat
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -xf /tmp/tomcat.tar.gz --strip-components=1 -C /opt/tomcat
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /tmp/tomcat.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -m dev
    Name: run
    PrependShell: true
  - Name: user
    User: dev
  - Name: workdir
    Path: /home/dev
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "8000"
  - Name: volume
    Volumes:
    - /home/dev/
  - CmdLine:
    - idea
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:15.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:15.04
