MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Key: http_proxy
    Name: arg
    Value: null
  - Key: https_proxy
    Name: arg
    Value: null
  - Key: no_proxy
    Name: arg
    Value: null
  - Key: socks_proxy
    Name: arg
    Value: null
  - Env:
    - Key: TERM
      Value: xterm
    - Key: http_proxy
      Value: ${http_proxy}
    - Key: https_proxy
      Value: ${https_proxy}
    - Key: no_proxy
      Value: ${no_proxy}
    - Key: socks_proxy
      Value: ${socks_proxy}
    Name: env
  - Env:
    - Key: LANG
      Value: '''C.UTF-8'''
    - Key: LC_ALL
      Value: '''C.UTF-8'''
    Name: env
  - Env:
    - Key: DJANGO_CONFIGURATION
      Value: '"production"'
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get install -yq         python-software-properties         software-properties-common         wget
      &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository
      ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive
      apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         unzip         unrar         p7zip-full         vim
      &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository
      --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: USER
      Value: django
    Name: env
  - Env:
    - Key: HOME
      Value: /home/${USER}
    Name: env
  - Name: workdir
    Path: ${HOME}
  - CmdLine:
    - adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
