MetaArgs: null
Stages:
- BaseName: ibbd/elasticsearch:base
  Commands:
  - Env:
    - Key: IK_VERSION
      Value: 5.4.3
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v$IK_VERSION/elasticsearch-analysis-ik-$IK_VERSION.zip
    - /tmp/analysis-ik.zip
  - CmdLine:
    - mkdir -p /usr/share/elasticsearch/plugins/ik     && unzip /tmp/analysis-ik.zip
      -d /usr/share/elasticsearch/plugins/ik     && chown -R elasticsearch:elasticsearch
      /usr/share/elasticsearch     && rm /tmp/analysis-ik.zip     && cd /usr/share/elasticsearch
    Name: run
    PrependShell: true
  From:
    Image: ibbd/elasticsearch:base
  Name: ""
  Platform: ""
  SourceCode: FROM ibbd/elasticsearch:base
