MetaArgs: null
Stages:
- BaseName: redash/redash:5.0.1.b4850
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - pip install Jinja2==2.10 drest ldap3
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - ./
  - CmdLine:
    - cp /app/client/app/assets/images/db-logos/url.png /app/client/app/assets/images/db-logos/url2.png
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install && npm run build && rm -rf node_modules
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R redash /app
    Name: run
    PrependShell: true
  - Name: user
    User: redash
  From:
    Image: redash/redash:5.0.1.b4850
  Name: ""
  Platform: ""
  SourceCode: FROM redash/redash:5.0.1.b4850
