MetaArgs: null
Stages:
- BaseName: golang:1-buster
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Sergey Alexandrovich <darthsim@gmail.com>"'
    Name: label
  - Env:
    - Key: PKG_CONFIG_PATH
      Value: /usr/local/lib/pkgconfig
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /lib64:/usr/lib64:/usr/local/lib
    Name: env
  - Env:
    - Key: CGO_LDFLAGS_ALLOW
      Value: '"-s|-w"'
    Name: env
  - CmdLine:
    - apt-get update   && apt-get install -y --no-install-recommends     curl     git     ca-certificates     build-essential     libtool     libfftw3-dev     libglib2.0-dev     libexpat1-dev     libjpeg62-turbo-dev     libpng-dev     libwebp-dev     libgif-dev     librsvg2-dev     libexif-dev     liblcms2-dev     libheif-dev     libtiff-dev     libimagequant-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /root   && mkdir ImageMagick   && curl -Ls https://imagemagick.org/download/ImageMagick.tar.gz
      | tar -xz -C ImageMagick --strip-components 1   && cd ImageMagick   && ./configure     --enable-silent-rules     --disable-static     --disable-openmp     --disable-deprecated     --disable-docs     --with-threads     --without-magick-plus-plus     --without-utilities     --without-perl     --without-bzlib     --without-dps     --without-freetype     --without-fontconfig     --without-jbig     --without-jpeg     --without-lcms     --without-lzma     --without-png     --without-tiff     --without-wmf     --without-xml     --without-webp     --without-heic     --without-pango   &&
      make install-strip   && rm -rf /usr/local/lib/libMagickWand-7.*
    Name: run
    PrependShell: true
  - CmdLine:
    - 'cd /root   && export VIPS_VERSION=$(curl -s "https://api.github.com/repos/libvips/libvips/releases/latest"
      | grep ''"tag_name":'' | sed -E ''s/.*"v([^"]+)".*/\1/'')   && echo "Vips version:
      $VIPS_VERSION"   && curl -Ls https://github.com/libvips/libvips/releases/download/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.gz
      | tar -xz   && cd vips-$VIPS_VERSION   && ./configure     --without-python     --without-OpenEXR     --enable-debug=no     --disable-static     --disable-introspection     --enable-silent-rules   &&
      make install-strip   && rm -rf /usr/local/lib/libvips-cpp.*'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - go build -v -o /usr/local/bin/imgproxy
    Name: run
    PrependShell: true
  From:
    Image: golang:1-buster
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1-buster
- BaseName: debian:buster-slim
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Sergey Alexandrovich <darthsim@gmail.com>"'
    Name: label
  - CmdLine:
    - apt-get update   && apt-get install -y --no-install-recommends     bash     ca-certificates     libsm6     libfftw3-3     libglib2.0-0     libexpat1     libjpeg62-turbo     libpng16-16     libwebp6     libwebpmux3     libwebpdemux2     libgif7     librsvg2-2     libexif12     liblcms2-2     libheif1     libtiff5     libimagequant0     libjemalloc2   &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /usr/local/bin/imgproxy
    - /usr/local/bin/
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - /usr/local/lib
    - /usr/local/lib
  - Env:
    - Key: VIPS_WARNING
      Value: "0"
    Name: env
  - Env:
    - Key: MALLOC_ARENA_MAX
      Value: "4"
    Name: env
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /lib64:/usr/lib64:/usr/local/lib
    Name: env
  - Env:
    - Key: LD_PRELOAD
      Value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
    Name: env
  - CmdLine:
    - imgproxy
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: debian:buster-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:buster-slim
