MetaArgs: null
Stages:
- BaseName: seeruk/java:openjdk-java8
  Commands:
  - Maintainer: Elliot Wright <hello@elliotdwright.com>
    Name: maintainer
  - Env:
    - Key: JENKINS
      Value: https://hub.spigotmc.org/jenkins
    Name: env
  - Env:
    - Key: SPIGOT_VERSION
      Value: latest
    Name: env
  - Env:
    - Key: SPIGOT_HEAP_INIT
      Value: 2G
    Name: env
  - Env:
    - Key: SPIGOT_HEAP_MAX
      Value: 2G
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./provisioning/docker-entrypoint.sh
    - /opt/mcbuild/docker-entrypoint.sh
  - CmdLine:
    - 'set -x     && apt-get update     && apt-get install -y git-core wget     &&
      rm -rf /var/lib/apt/lists/*     && useradd -d /opt/mcserver -u 1000 -m -s /bin/bash
      mcserver     && mkdir -p /opt/mcserver     && mkdir -p /opt/mcbuild     && cd
      /opt/mcbuild     && wget ${JENKINS}/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar     &&
      java -d64 -jar BuildTools.jar --rev ${SPIGOT_VERSION}     && chown -R mcserver:
      /opt/mcbuild     && chown -R mcserver: /opt/mcserver     && chmod +x /opt/mcbuild/docker-entrypoint.sh'
    Name: run
    PrependShell: true
  - Name: user
    User: mcserver
  - Name: expose
    Ports:
    - "25565"
  - Name: volume
    Volumes:
    - /opt/mcserver
  - Name: workdir
    Path: /opt/mcserver
  - CmdLine:
    - /opt/mcbuild/docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - nogui
    Name: cmd
    PrependShell: false
  From:
    Image: seeruk/java:openjdk-java8
  Name: ""
  Platform: ""
  SourceCode: FROM seeruk/java:openjdk-java8
