MetaArgs: null
Stages:
- BaseName: bitwalker/alpine-erlang:21.1.1
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Mark Sargento <marksargento.00@gmail.com>"'
    Name: label
  - Env:
    - Key: REFRESHED_AT
      Value: "2019-02-09"
    - Key: ELIXIR_VERSION
      Value: v1.8.1
    Name: env
  - Name: workdir
    Path: /tmp/elixir-build
  - CmdLine:
    - apk --no-cache --update upgrade &&     apk add --no-cache --update --virtual
      .elixir-build       make &&     apk add --no-cache --update       git autoconf
      automake libtool build-base gmp-dev &&     git clone https://github.com/elixir-lang/elixir
      --depth 1 --branch $ELIXIR_VERSION &&     cd elixir &&     make && make install
      &&     mix local.hex --force &&     mix local.rebar --force &&     cd $HOME
      &&     rm -rf /tmp/elixir-build &&     apk del --no-cache .elixir-build
    Name: run
    PrependShell: true
  - Name: workdir
    Path: ${HOME}
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: false
  From:
    Image: bitwalker/alpine-erlang:21.1.1
  Name: ""
  Platform: ""
  SourceCode: FROM bitwalker/alpine-erlang:21.1.1
