MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Felix Bartels "felix@host-consultants.de"
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - echo "deb http://docker.host-consultants.de ./" > /etc/apt/sources.list.d/zarafa.list
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /scripts/update
    - /bin/
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
