MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/exechealthz:1.0
  Commands:
  - Maintainer: Netonline "xxx@gmail.com"
    Name: maintainer
  From:
    Image: gcr.io/google_containers/exechealthz:1.0
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/exechealthz:1.0
