MetaArgs: null
Stages:
- BaseName: buildpack-deps:jessie
  Commands:
  - CmdLine:
    - groupadd -r unprivileged --gid=999 && useradd -m -r -g unprivileged --uid=999
      unprivileged
    Name: run
    PrependShell: true
  - Env:
    - Key: GOSU_VERSION
      Value: "1.7"
    Name: env
  - CmdLine:
    - "set -x \t&& apt-get update && apt-get install -y --no-install-recommends ca-certificates
      wget && rm -rf /var/lib/apt/lists/* \t&& wget -O /usr/local/bin/gosu \"https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg
      --print-architecture)\" \t&& wget -O /usr/local/bin/gosu.asc \"https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg
      --print-architecture).asc\" \t&& export GNUPGHOME=\"$(mktemp -d)\" \t&& gpg
      --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
      \t&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \t&& rm
      -r \"$GNUPGHOME\" /usr/local/bin/gosu.asc \t&& chmod +x /usr/local/bin/gosu
      \t&& gosu nobody true"
    Name: run
    PrependShell: true
  - CmdLine:
    - set -ex   && for key in     9554F04D7259F04124DE6B476D5A82AC7E37093B     94AE36675C464D64BAFA68DD7434390BDBE9B9C5     0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93     FD3A5288F042B6850C66B31F09FE44734EB7990E     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1     DD8F2338BAE7501E3DD5AC78C273792F7D83545D     B9AE9905FFD7803F25714661B63B535A4C206CA9     C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8   ;
      do     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";   done
    Name: run
    PrependShell: true
  - Env:
    - Key: NPM_CONFIG_LOGLEVEL
      Value: info
    Name: env
  - Env:
    - Key: NODE_VERSION
      Value: 6.2.2
    Name: env
  - CmdLine:
    - curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz"   &&
      curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc"   && gpg
      --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc   && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$"
      SHASUMS256.txt | sha256sum -c -   && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz"
      -C /usr/local --strip-components=1   && rm "node-v$NODE_VERSION-linux-x64.tar.xz"
      SHASUMS256.txt.asc SHASUMS256.txt
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: GPG_KEY
      Value: 97FC712E4C024BBEA48A61ED3A5CA953F73C700D
    Name: env
  - Env:
    - Key: PYTHON_VERSION
      Value: 3.5.1
    Name: env
  - Env:
    - Key: PYTHON_PIP_VERSION
      Value: 8.1.2
    Name: env
  - Env:
    - Key: PYTHON_SETUPTOOLS
      Value: 28.3.0
    Name: env
  - CmdLine:
    - "set -ex \t&& curl -fSL \"https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz\"
      -o python.tar.xz \t&& curl -fSL \"https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc\"
      -o python.tar.xz.asc \t&& export GNUPGHOME=\"$(mktemp -d)\" \t&& gpg --keyserver
      ha.pool.sks-keyservers.net --recv-keys \"$GPG_KEY\" \t&& gpg --batch --verify
      python.tar.xz.asc python.tar.xz \t&& rm -r \"$GNUPGHOME\" python.tar.xz.asc
      \t&& mkdir -p /usr/src/python \t&& tar -xJC /usr/src/python --strip-components=1
      -f python.tar.xz \t&& rm python.tar.xz \t\t&& cd /usr/src/python \t&& ./configure
      --enable-shared --enable-unicode=ucs4 \t&& make -j$(nproc) \t&& make install
      \t&& ldconfig \t&& pip3 install --no-cache-dir --upgrade --ignore-installed
      pip==$PYTHON_PIP_VERSION setuptools==$PYTHON_SETUPTOOLS \t&& find /usr/local
      -depth \t\t\\( \t\t    \\( -type d -a -name test -o -name tests \\) \t\t    -o
      \t\t    \\( -type f -a -name '*.pyc' -o -name '*.pyo' \\) \t\t\\) -exec rm -rf
      '{}' + \t&& rm -rf /usr/src/python ~/.cache \t&& cd /usr/local/bin && ln -s
      easy_install-3.5 easy_install3 \t&& ln -s idle3 idle \t&& ln -s pydoc3 pydoc
      \t&& ln -s python3 python \t&& ln -s python3-config python-config"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y         zip unzip gcc gettext         mysql-client
      libmysqlclient-dev         postgresql-client libpq-dev sqlite3         libtiff5-dev
      libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev         liblcms2-dev libwebp-dev
      tcl8.6-dev tk8.6-dev         libxml2-dev libxslt-dev libffi-dev         libcairo2-dev     --no-install-recommends
      && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --no-cache-dir --upgrade gunicorn uwsgi psycopg2 mysqlclient virtualenv
      invoke Jinja2 ipython
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install -g bower && npm install -g gulp && npm install -g yarn
    Name: run
    PrependShell: true
  From:
    Image: buildpack-deps:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM buildpack-deps:jessie
