MetaArgs: null
Stages:
- BaseName: zouchao2010/python:2.7
  Commands:
  - Name: volume
    Volumes:
    - /var/lib/litecoind
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /opt/litecoind
  - Name: workdir
    Path: /opt/litecoind
  - CmdLine:
    - cp -r testnet /var/lib/litecoind
    Name: run
    PrependShell: true
  - CmdLine:
    - cp -r livenet /var/lib/litecoind
    Name: run
    PrependShell: true
  - Env:
    - Key: TESTNET
      Value: "0"
    Name: env
  - Env:
    - Key: VERSION
      Value: 0.10.4.0
    Name: env
  - CmdLine:
    - apt-get update     && apt-get install -y wget     && apt-get autoremove -y     &&
      apt-get clean -y     && apt-get autoclean -y     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://download.litecoin.org/litecoin-$VERSION/linux/litecoin-$VERSION-linux64.tar.gz     &&
      tar zxvf litecoin-$VERSION-linux64.tar.gz     && ln -sfv /opt/litecoind/litecoin-$VERSION/bin/*
      /usr/local/bin     && rm -rf litecoin-$VERSION-linux64.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 755 run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9332"
  - Name: expose
    Ports:
    - "9333"
  - Name: expose
    Ports:
    - "19332"
  - Name: expose
    Ports:
    - "19333"
  - CmdLine:
    - ./run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: zouchao2010/python:2.7
  Name: ""
  Platform: ""
  SourceCode: FROM zouchao2010/python:2.7
