MetaArgs: null
Stages:
- BaseName: benzbrake/alpine
  Commands:
  - Maintainer: Ryan Lieu <github-benzBrake@woai.ru>
    Name: maintainer
  - Key: FRP_VER
    Name: arg
    Value: 0.12.0
  - CmdLine:
    - "set -ex && \tcurl -sSL https://github.com/fatedier/frp/releases/download/v${FRP_VER}/frp_${FRP_VER}_linux_amd64.tar.gz
      -o /tmp/fprs.tgz && \tcd /tmp && tar xvf /tmp/fprs.tgz &&\tmv /tmp/frp_${FRP_VER}_linux_amd64/frpc
      /usr/bin/ &&\trm -rf /tmp/frp_${FRP_VER}_linux_amd64"
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /etc/frpc.ini
  - CmdLine:
    - -c
    - /etc/frpc.ini
    Name: cmd
    PrependShell: false
  - CmdLine:
    - /usr/bin/frpc
    Name: entrypoint
    PrependShell: false
  From:
    Image: benzbrake/alpine
  Name: ""
  Platform: ""
  SourceCode: FROM benzbrake/alpine
