MetaArgs: null
Stages:
- BaseName: golang:1.7
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner
  - Name: workdir
    Path: /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner
  - CmdLine:
    - git fetch --tags || true
    Name: run
    PrependShell: true
  - Env:
    - Key: BUILD_PLATFORMS
      Value: -osarch=linux/amd64
    Name: env
  - CmdLine:
    - "make && \tln -s $(pwd)/out/binaries/gitlab-ci-multi-runner-linux-amd64 /usr/bin/gitlab-ci-multi-runner
      && \tln -s $(pwd)/out/binaries/gitlab-ci-multi-runner-linux-amd64 /usr/bin/gitlab-runner"
    Name: run
    PrependShell: true
  - CmdLine:
    - packaging/root/usr/share/gitlab-runner/post-install
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /etc/gitlab-runner
    - /home/gitlab-runner
  - CmdLine:
    - run
    - --user=gitlab-runner
    - --working-directory=/home/gitlab-runner
    Name: cmd
    PrependShell: false
  - CmdLine:
    - /usr/bin/gitlab-runner
    Name: entrypoint
    PrependShell: false
  From:
    Image: golang:1.7
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.7
