MetaArgs: null
Stages:
- BaseName: frank90086/ubuntu_apache2
  Commands:
  - Maintainer: frank
    Name: maintainer
  - CmdLine:
    - service apache2 start && /bin/bash
    Name: entrypoint
    PrependShell: true
  From:
    Image: frank90086/ubuntu_apache2
  Name: ""
  Platform: ""
  SourceCode: FROM frank90086/ubuntu_apache2
