MetaArgs: null
Stages:
- BaseName: ubuntu:17.10
  Commands:
  - Maintainer: Simone Roberto Nunzi "simone.roberto.nunzi@gmail.com"
    Name: maintainer
  - CmdLine:
    - apt update && apt install -y sudo git wget zip genisoimage bc squashfs-tools
      xorriso tar klibc-utils iproute2 dosfstools rsync unzip findutils iputils-ping
      grep
    Name: run
    PrependShell: true
  - CmdLine:
    - apt update && apt install -y build-essential libncurses5-dev libssl-dev libelf-dev
      bison flex kmod cpio
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/stockmind/gpd-pocket-ubuntu-respin.git ./gpd-pocket-ubuntu-respin
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -O gpd-pocket-ubuntu-respin/isorespin.sh "https://drive.google.com/uc?export=download&id=0B99O3A0dDe67S053UE8zN3NwM2c"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /docker-input
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /docker-output
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker-entrypoint.sh
    - /
  - CmdLine:
    - chmod +x docker-entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:17.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:17.10
