MetaArgs: null
Stages:
- BaseName: nginx:latest
  Commands:
  - Maintainer: Feng Zhou <feng.zh@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update --quiet > /dev/null &&     apt-get install --assume-yes --force-yes
      -qq     openssh-client sshfs &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - autoindex.conf
    - /etc/nginx/conf.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - init.sh
    - /
  - CmdLine:
    - chmod +x /init.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /init.sh
    Name: cmd
    PrependShell: false
  From:
    Image: nginx:latest
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:latest
