MetaArgs: null
Stages:
- BaseName: alamilla/java
  Commands:
  - Maintainer: Andres F. Lamilla, "alamilla@gmail.com"
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src/app.sv.conf
    - /etc/supervisor/conf.d/app.sv.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src/run.sh
    - /usr/local/bin/run.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src/start_app.sh
    - /usr/local/bin/start_app.sh
  - CmdLine:
    - chmod +x /usr/local/bin/*.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - /usr/local/bin/run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alamilla/java
  Name: ""
  Platform: ""
  SourceCode: FROM     alamilla/java
