MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: IPBurger <accounts@ipburger.com>
    Name: maintainer
  - CmdLine:
    - apk add --no-cache mysql mysql-client
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/startup.sh
    - /startup.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - conf/my.cnf
    - /etc/mysql/my.cnf
  - CmdLine:
    - mkdir -p /run/mysqld && mkdir -p /dbinit.d
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "test"
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "test2"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /db
  - Name: volume
    Volumes:
    - /db
  - Name: expose
    Ports:
    - "3306"
  - Health:
      Test:
      - CMD
      - mysqladmin
      - ping
    Name: healthcheck
  - CmdLine:
    - /startup.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
