MetaArgs: null
Stages:
- BaseName: ruby
  Commands:
  - CmdLine:
    - bundle
    - exec
    - fluentd
    - -c
    - /etc/fluent/fluent.conf
    Name: cmd
    PrependShell: false
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - bundle config --global frozen 1 &&     mkdir -p /usr/src/app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - /usr/src/app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile.lock
    - /usr/src/app/
  - CmdLine:
    - bundle install
    Name: run
    PrependShell: true
  From:
    Image: ruby
  Name: ""
  Platform: ""
  SourceCode: FROM ruby
