MetaArgs: null
Stages:
- BaseName: node:carbon
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package*.json
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - yarn.lock
    - ./
  - CmdLine:
    - yarn
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - yarn global add prisma
    Name: run
    PrependShell: true
  - CmdLine:
    - prisma deploy
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "4000"
  - CmdLine:
    - node
    - src
    Name: cmd
    PrependShell: false
  From:
    Image: node:carbon
  Name: ""
  Platform: ""
  SourceCode: FROM node:carbon
