MetaArgs: null
Stages:
- BaseName: oraclelinux:7-slim
  Commands:
  - Key: KEY
    Name: arg
    Value: https://repo.mysql.com/RPM-GPG-KEY-mysql
  - Key: REPO
    Name: arg
    Value: https://repo.mysql.com
  - Key: MYSQL_SERVER_PACKAGE_URL
    Name: arg
    Value: $REPO/yum/mysql-8.0-community/docker/x86_64/mysql-community-server-minimal-8.0.12-1.el7.x86_64.rpm
  - Key: MYSQL_ROUTER_PACKAGE_URL
    Name: arg
    Value: $REPO/yum/mysql-tools-community/el/7/x86_64/mysql-router-8.0.12-1.el7.x86_64.rpm
  - CmdLine:
    - rpmkeys --import $KEY     && yum install -y       $MYSQL_SERVER_PACKAGE_URL       $MYSQL_ROUTER_PACKAGE_URL     &&
      yum clean all
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - /run.sh
  - Health:
      Test:
      - CMD-SHELL
      - mysqladmin --port 6446 --protocol TCP ping 2>&1 | grep Access || exit 1
    Name: healthcheck
  - Name: expose
    Ports:
    - "6446"
    - "64460"
    - "6447"
    - "64470"
  - CmdLine:
    - /run.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - mysqlrouter
    Name: cmd
    PrependShell: false
  From:
    Image: oraclelinux:7-slim
  Name: ""
  Platform: ""
  SourceCode: FROM oraclelinux:7-slim
