MetaArgs: null
Stages:
- BaseName: barnabasj/ansible-test-base
  Commands:
  - CmdLine:
    - yum install -y postfix sendmail
    Name: run
    PrependShell: true
  From:
    Image: barnabasj/ansible-test-base
  Name: ""
  Platform: ""
  SourceCode: FROM barnabasj/ansible-test-base
