MetaArgs: null
Stages:
- BaseName: node:8-alpine
  Commands:
  - CmdLine:
    - mkdir -p /code
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /code
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: node:8-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:8-alpine
