MetaArgs: null
Stages:
- BaseName: python:3.7.2-alpine3.8
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"m@yefu.org"'
    Name: label
  - CmdLine:
    - apk add --no-cache zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.sh
    - .
  - CmdLine:
    - ./package.sh
    Name: cmd
    PrependShell: true
  From:
    Image: python:3.7.2-alpine3.8
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.7.2-alpine3.8
