MetaArgs: null
Stages:
- BaseName: kaixhin/torch:latest
  Commands:
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libprotobuf-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y protobuf-compiler
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libhdf5-serial-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y hdf5-tools
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python-setuptools
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / ; git clone https://github.com/karpathy/neuraltalk2.git
    Name: run
    PrependShell: true
  - CmdLine:
    - luarocks install loadcaffe
    Name: run
    PrependShell: true
  - CmdLine:
    - cd / ; git clone https://github.com/deepmind/torch-hdf5.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /torch-hdf5/ && luarocks make hdf5-0-0.rockspec LIBHDF5_LIBDIR="/usr/lib/x86_64-linux-gnu/"
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install pip && pip install h5py
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://deb.nodesource.com/setup_5.x|sh -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - webapp
    - /webapp
  - Chown: ""
    Name: add
    SourcesAndDest:
    - README.md
    - /webapp/README.md
  - CmdLine:
    - cd /webapp && /usr/bin/npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/node
    - /webapp/index.js
    Name: cmd
    PrependShell: false
  - Name: workdir
    Path: /webapp
  From:
    Image: kaixhin/torch:latest
  Name: ""
  Platform: ""
  SourceCode: FROM kaixhin/torch:latest
