MetaArgs: null
Stages:
- BaseName: archlinux/base
  Commands:
  - Name: workdir
    Path: /
  - Labels:
    - Key: maintainer
      Value: codehz
    Name: label
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /
  - CmdLine:
    - pacman -Syu --needed --noconfirm python pyalpm rsync base-devel git util-linux
      systemd-libs
    Name: run
    PrependShell: true
  From:
    Image: archlinux/base
  Name: ""
  Platform: ""
  SourceCode: FROM archlinux/base
