MetaArgs: null
Stages:
- BaseName: httpd:2.4
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"PCSOFT <network@pcsoft.fr>"'
    Name: label
  - Env:
    - Key: WEBDEVVersion
      Value: "25"
    Name: env
  - Env:
    - Key: WEBDEVVersionRepertoire
      Value: ${WEBDEVVersion}.0
    Name: env
  - Env:
    - Key: WEBDEVBinaries
      Value: /usr/local/WEBDEV/${WEBDEVVersionRepertoire}/
    - Key: WEBDEVConfiguration
      Value: /var/lib/WEBDEV/${WEBDEVVersionRepertoire}/
    - Key: WEBDEVRegistreBase
      Value: '"/etc/PC SOFT/WEBDEV/"'
    Name: env
  - CmdLine:
    - "set -ex \t&& sDependancesInstallation='ca-certificates wget unzip' \t&& sDependancesExecution='libfreetype6
      libqtcore4 libqtgui4' \t&& apt-get update \t&& apt-get install -y $sDependancesInstallation
      --no-install-recommends \t&& wget -nv -O WEBDEV_Install3264.zip https://package.windev.com/pack/wx25/install/wx25_52j/fr/WBDEP25LINUXPACKDVD052j.zip
      \t&& echo \"c051e318155c0ac0ff6b316c09a954f7aed9256e45d99a2ec1e10888ac5d276a
      *WEBDEV_Install3264.zip\" | sha256sum -c - \t&& unzip -b -j WEBDEV_Install3264.zip
      Linux64x86/* \t&& chmod 550 webdev_install64 \t&& mkdir -p ${WEBDEVConfiguration}comptes
      ${WEBDEVConfiguration}conf ${WEBDEVConfiguration}httpd \"${WEBDEVRegistreBase}\"
      \t&& ln -s ${WEBDEVConfiguration}conf \"${WEBDEVRegistreBase}${WEBDEVVersionRepertoire}\"
      \t&& ./webdev_install64 --docker \t&& chmod --reference=${WEBDEVBinaries}WDAdminWeb
      ${WEBDEVConfiguration}comptes \t&& chown --reference=${WEBDEVBinaries}WDAdminWeb
      ${WEBDEVConfiguration}comptes \t&& apt-get install -y $sDependancesExecution
      --no-install-recommends \t&& rm -rf webdev_install64 WEBDEV_Install.zip WEBDEV_Install3264.zip
      \t&& apt-get purge -y --auto-remove $sDependancesInstallation \t&& rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/WEBDEV/25.0/wd250admind
    - --docker
    Name: entrypoint
    PrependShell: false
  From:
    Image: httpd:2.4
  Name: ""
  Platform: ""
  SourceCode: FROM httpd:2.4
