MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Maintainer: yowcow <yowcow@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y update && apt-get install -y build-essential curl && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp && curl -LO http://www.cpan.org/src/5.0/perl-5.16.3.tar.gz             &&
      tar xvzf perl-5.16.3.tar.gz             && cd perl-5.16.3             && ./Configure
      -des && make && make install             && cd /tmp && rm -rf perl-5.16.3.tar.gz
      perl-5.16.3             && cd /usr/local/bin && curl -L https://cpanmin.us/
      -o cpanm && chmod +x cpanm
    Name: run
    PrependShell: true
  - CmdLine:
    - perl -V && cpanm -V
    Name: cmd
    PrependShell: true
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
