MetaArgs: null
Stages:
- BaseName: php:5.6.31-apache
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Marius Millea <mariusmillea@gmail.com>"'
    Name: label
  - CmdLine:
    - echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list     &&
      apt-get update     && apt-get install -y --no-install-recommends         cron         inotify-tools         libjpeg62-turbo-dev         libpng12-dev         mysql-client         nano         python         rsyslog         supervisor         vim-tiny         wget     &&
      apt-get install -y -t jessie-backports openssl     && wget https://git.io/psysh
      -O /usr/bin/psysh     && chmod +x /usr/bin/psysh     && rm -rf /var/lib/apt/lists
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-install mysqli     && docker-php-ext-configure gd --with-jpeg-dir=/usr/include/     &&
      docker-php-ext-install gd     && a2enmod cgi
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L http://get.docker.com/builds/Linux/x86_64/docker-1.10.3 > /usr/bin/docker     &&
      chmod +x /usr/bin/docker
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /root && mkdir /root && chmod 755 /root
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser www-data root
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .bashrc
    - /root/.bashrc
  - Env:
    - Key: PROJECT_ROOT
      Value: /root/project
    Name: env
  - Name: workdir
    Path: $PROJECT_ROOT
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - logrotate
    - /etc/logrotate.d/boincserver
  - CmdLine:
    - chmod 644 /etc/logrotate.d/boincserver
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - post-makeproject.sh
    - /usr/bin/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/conf.d/
  - CmdLine:
    - /usr/bin/supervisord
    Name: cmd
    PrependShell: false
  From:
    Image: php:5.6.31-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.6.31-apache
