MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: WuXi NextCODE DevOps <devops@wuxinextcode.com>
    Name: maintainer
  - CmdLine:
    - apk --no-cache add --update python py-pip     && pip install --upgrade pip     &&
      pip install --upgrade ansible-tower-cli
    Name: run
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
