MetaArgs: null
Stages:
- BaseName: java:8
  Commands:
  - Maintainer: David Gageot <david.gageot@sonarsource.com>
    Name: maintainer
  - Env:
    - Key: SONAR_VERSION
      Value: "5.6"
    - Key: SONARQUBE_HOME
      Value: /opt/sonarqube
    - Key: SONARQUBE_JDBC_USERNAME
      Value: sonar
    - Key: SONARQUBE_JDBC_PASSWORD
      Value: sonar
    - Key: SONARQUBE_JDBC_URL
      Value: ""
    Name: env
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - set -x     && cd /tmp     && curl -fSL -O "https://archive.raspbian.org/raspbian/pool/main/c/ca-certificates/ca-certificates_20130119+deb7u1_all.deb"     &&
      echo "3494ecfd607e4233d8d1a656eceb6bd109d756bc0afe9d3b29dfc0acc4fe19cf  ca-certificates_20130119+deb7u1_all.deb"
      | sha256sum -c -     && dpkg -P --force-all ca-certificates     && dpkg -i ca-certificates_20130119+deb7u1_all.deb     &&
      rm ca-certificates_20130119+deb7u1_all.deb     && gpg --keyserver ha.pool.sks-keyservers.net
      --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE     && cd /opt     && curl
      -o sonarqube.zip -fSL https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-$SONAR_VERSION.zip     &&
      curl -o sonarqube.zip.asc -fSL https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-$SONAR_VERSION.zip.asc     &&
      gpg --batch --verify sonarqube.zip.asc sonarqube.zip     && unzip sonarqube.zip     &&
      mv sonarqube-$SONAR_VERSION sonarqube     && rm sonarqube.zip*     && rm -rf
      $SONARQUBE_HOME/bin/*
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - $SONARQUBE_HOME/data
    - $SONARQUBE_HOME/extensions
  - Name: workdir
    Path: $SONARQUBE_HOME
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - $SONARQUBE_HOME/bin/
  - CmdLine:
    - ./bin/run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: java:8
  Name: ""
  Platform: ""
  SourceCode: FROM java:8
