MetaArgs: null
Stages:
- BaseName: timiil/lede-builder
  Commands:
  - Maintainer: timiil@163.com
    Name: maintainer
  - CmdLine:
    - git clone https://github.com/coolsnowwolf/lede.git &&   cd lede &&   ./scripts/feeds
      update -a &&   ./scripts/feeds install -a
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /lede
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./4.4_qcom-ipq8065-r7800.dts
    - /lede/target/linux/ipq806x/files-4.4/arch/arm/boot/dts/qcom-ipq8065-r7800.dts
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./4.9_qcom-ipq8065-r7800.dts
    - /lede/target/linux/ipq806x/files-4.9/arch/arm/boot/dts/qcom-ipq8065-r7800.dts
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./121701.config
    - /lede/.config
  - CmdLine:
    - make download
    Name: run
    PrependShell: true
  From:
    Image: timiil/lede-builder
  Name: ""
  Platform: ""
  SourceCode: FROM timiil/lede-builder
