MetaArgs: null
Stages:
- BaseName: python:3.6-jessie
  Commands:
  - CmdLine:
    - mkdir /code
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /code
  - Name: workdir
    Path: code
  - CmdLine:
    - pip install -r requirements.txt &&     apt-get update && apt-get install -y
      curl python-software-properties &&     curl -sL https://deb.nodesource.com/setup_9.x
      | bash - &&     apt-get install -y nodejs
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /code
  - CmdLine:
    - cd web_server/frontend && npm install && npm run build &&     cd ../ && python3
      manage.py makemigrations && python3 manage.py migrate &&     python3 manage.py
      collectstatic
    Name: run
    PrependShell: true
  - CmdLine:
    - python3
    - webserver/manage.py runserver 0.0.0.0:8000
    Name: cmd
    PrependShell: false
  From:
    Image: python:3.6-jessie
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-jessie
