MetaArgs: null
Stages:
- BaseName: selenium/node-chrome-debug
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt-get update && apt-get install -y software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository universe
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y python3.7
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s -f /usr/bin/python3.7 /usr/bin/python3
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python3-venv
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python3-pip
    Name: run
    PrependShell: true
  - Name: user
    User: seluser
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/start-selenium-standalone.sh
    - /opt/bin/start-selenium-standalone.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/selenium.conf
    - /etc/supervisor/conf.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/selenium-debug.conf
    - /etc/supervisor/conf.d/
  - CmdLine:
    - pip3 install selenium
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /dev/shm
  - Name: expose
    Ports:
    - "4444"
  - Name: expose
    Ports:
    - "5900"
  From:
    Image: selenium/node-chrome-debug
  Name: ""
  Platform: ""
  SourceCode: FROM selenium/node-chrome-debug
