MetaArgs: null
Stages:
- BaseName: node:4.1-onbuild
  Commands:
  - Name: expose
    Ports:
    - "80"
  From:
    Image: node:4.1-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM node:4.1-onbuild
