MetaArgs: null
Stages:
- BaseName: docteurklein/sqitch:pgsql
  Commands:
  - Name: workdir
    Path: /src
  - CmdLine:
    - /opt/run.sh
    Name: entrypoint
    PrependShell: false
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run.sh
    - /opt
  From:
    Image: docteurklein/sqitch:pgsql
  Name: ""
  Platform: ""
  SourceCode: FROM docteurklein/sqitch:pgsql
