MetaArgs: null
Stages:
- BaseName: perl:5
  Commands:
  - CmdLine:
    - apt-get update && apt-get --yes --no-install-recommends install     libnet-ip-perl
      libnet-netmask-perl libnet-dns-perl libxml-writer-perl libstring-random-perl     libregexp-ipv6-perl
      libhtml-parser-perl libwww-mechanize-perl     && apt-get clean     && rm -rf
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://deb.debian.org/debian/pool/main/libn/libnet-whois-ip-perl/libnet-whois-ip-perl_1.19-2_all.deb     &&
      dpkg -i libnet-whois-ip-perl_1.19-2_all.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/fwaeytens/dnsenum.git /src/dnsenum/     && chmod
      +x /src/dnsenum/dnsenum.pl
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /src/dnsenum
  - CmdLine:
    - /src/dnsenum/dnsenum.pl
    Name: cmd
    PrependShell: true
  From:
    Image: perl:5
  Name: ""
  Platform: ""
  SourceCode: FROM perl:5
