MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get install --yes nginx &&     rm --recursive --force
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - ln --symbolic --force /dev/stdout /var/log/nginx/access.log
    Name: run
    PrependShell: true
  - CmdLine:
    - ln --symbolic --force /dev/stderr /var/log/nginx/error.log
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "443"
    - "80"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - monitoring.conf
    - /etc/nginx/conf.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - monitoring.html
    - /usr/share/nginx/html/monitoring.html
  - Chown: ""
    Name: add
    SourcesAndDest:
    - coverage.conf
    - /etc/nginx/conf.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - dev.conf
    - /etc/nginx/conf.d/
  - CmdLine:
    - nginx
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -g
    - daemon off;
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
