MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: '"Mitz Amano <mitz@linux.com>"'
    Name: maintainer
  - Name: user
    User: root
  - CmdLine:
    - echo "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe
      multiverse" > /etc/apt/sources.list &&     echo "deb mirror://mirrors.ubuntu.com/mirrors.txt
      trusty-updates main restricted universe multiverse" >> /etc/apt/sources.list
      &&     echo "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty-security main
      restricted universe multiverse" >> /etc/apt/sources.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb http://ag-projects.com/ubuntu trusty main" >>/etc/apt/sources.list
      &&     wget -O - http://download.ag-projects.com/agp-debian-gpg.key | apt-key
      add -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&     apt-get install -y mediaproxy-relay
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get purge -y ca-certificates libidn11 openssl wget
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chown root.root /entrypoint.sh && chmod 700 /entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 20000-60000/udp
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
