MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: Jerry Cai
    Name: maintainer
  - Key: ARACHNI_VERSION
    Name: arg
    Value: arachni-1.5.1-0.5.12
  - Env:
    - Key: ARACHNI_SERVER_ROOT_PASSWORD
      Value: arachni
    Name: env
  - Env:
    - Key: ARACHNI_PARAMS
      Value: --authentication-username arachni --authentication-password password
        --only-positives
    Name: env
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install                 openssh-server                 wget                 curl                 supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/run/sshd &&     mkdir -p /var/log/supervisor &&     mkdir -p /etc/supervisor/conf.d
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/qiwihui/arachni/releases/download/v1.5.1/${ARACHNI_VERSION}-linux-x86_64-cn.tar.gz
      &&     tar xzvf ${ARACHNI_VERSION}-linux-x86_64-cn.tar.gz &&     mv ${ARACHNI_VERSION}
      /usr/local
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/local/${ARACHNI_VERSION} /usr/local/arachni
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '"$PWD"/chpasswd.sh'
    - /usr/local/chpasswd.sh
  - CmdLine:
    - chmod 777 /usr/local/chpasswd.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '"$PWD"/start.sh'
    - /usr/local/arachni/start.sh
  - CmdLine:
    - chmod 777 /usr/local/arachni/start.sh
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - supervisor.conf
    - /etc/supervisor.conf
  - Chown: ""
    Name: add
    SourcesAndDest:
    - arachni.conf
    - /etc/supervisor/conf.d/arachni.conf
  - Name: expose
    Ports:
    - "22"
    - "7331"
    - "9292"
  - CmdLine:
    - supervisord
    - -c
    - /etc/supervisor.conf
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
