MetaArgs: null
Stages:
- BaseName: node:10.15.1
  Commands:
  - CmdLine:
    - mkdir /project
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /project
  - CmdLine:
    - curl -sSL https://github.com/edenb/livemap/tarball/master | tar -xvz --strip
      1
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - node
    - app.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:10.15.1
  Name: ""
  Platform: ""
  SourceCode: FROM node:10.15.1
