MetaArgs: null
Stages:
- BaseName: alpine:3.11
  Commands:
  - Maintainer: Milan Sulc <sulcmil@gmail.com>
    Name: maintainer
  - Env:
    - Key: TERM
      Value: xterm
    Name: env
  - Env:
    - Key: USER_UID
      Value: "1000"
    Name: env
  - Env:
    - Key: USER_NAME
      Value: dfx
    Name: env
  - Env:
    - Key: USER_HOME
      Value: /home/dfx
    Name: env
  - CmdLine:
    - apk update &&     apk upgrade &&     adduser -D -u $USER_UID $USER_NAME &&     rm
      -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.11
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.11
