MetaArgs: null
Stages:
- BaseName: jasonslay/python-selenium
  Commands:
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - requirements.txt
  - Chown: ""
    Name: add
    SourcesAndDest:
    - safeway.py
    - safeway.py
  - CmdLine:
    - pip3 install --upgrade pip wheel setuptools --upgrade -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - python3
    - ./safeway.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: jasonslay/python-selenium
  Name: ""
  Platform: ""
  SourceCode: FROM jasonslay/python-selenium
