MetaArgs: null
Stages:
- BaseName: bluelightltd/ca-certs
  Commands:
  - Name: expose
    Ports:
    - "443"
    - "80"
    - "8000"
    - "9000"
  - Env:
    - Key: DATABASE_DRIVER
      Value: sqlite3
    Name: env
  - Env:
    - Key: DATABASE_CONFIG
      Value: /var/lib/drone/drone.sqlite
    Name: env
  - Env:
    - Key: GODEBUG
      Value: netdns=go
    Name: env
  - Env:
    - Key: XDG_CACHE_HOME
      Value: /var/lib/drone
    Name: env
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: bluelightltd/ca-certs
  Name: ""
  Platform: ""
  SourceCode: FROM bluelightltd/ca-certs
