MetaArgs: null
Stages:
- As: build
  BaseName: node:10.12-alpine
  Commands:
  - CmdLine:
    - apk add --no-cache openssl libressl git make gcc g++ python
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - npm install && npm rebuild node-sass
    Name: run
    PrependShell: true
  - CmdLine:
    - npm run build
    Name: run
    PrependShell: true
  - CmdLine:
    - cd src/strapi && yarn install
    Name: run
    PrependShell: true
  From:
    Image: node:10.12-alpine
  Name: build
  Platform: ""
  SourceCode: FROM node:10.12-alpine AS build
- BaseName: node:10.12-alpine
  Commands:
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /app
    - /app
  - Name: workdir
    Path: /app
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "1337"
  From:
    Image: node:10.12-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10.12-alpine
