MetaArgs: null
Stages:
- BaseName: oraclelinux:7.4
  Commands:
  - Env:
    - Key: TZ
      Value: Europe/Rome
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LIFERAY_URL
      Value: '''https://downloads.sourceforge.net/project/lportal/Liferay%20Portal/7.0.3%20GA4/liferay-ce-portal-tomcat-7.0-ga4-20170613175008905.zip'''
    Name: env
  - Env:
    - Key: JAVA_HOME
      Value: '''/usr/java/latest'''
    Name: env
  - Env:
    - Key: CATALINA_BASE
      Value: '''/srv/http/liferay/tomcat-8.0.32'''
    Name: env
  - Env:
    - Key: CATALINA_HOME
      Value: '''/srv/http/liferay/tomcat-8.0.32'''
    Name: env
  - Env:
    - Key: CATALINA_OPTS
      Value: '''-d64 -server -XX:NewSize=700m -XX:MaxNewSize=700m -Xms2G -Xmx2G -Dfile.encoding=UTF8
        -Djava.net.preferIPv4Stack=true -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false
        -Duser.timezone=GMT'''
    Name: env
  - Name: workdir
    Path: /root
  - CmdLine:
    - 'curl -LO -H "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.rpm
      &&     rpm -ivh jdk-8u151-linux-x64.rpm'
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /srv/http/liferay
  - CmdLine:
    - yum install -y unzip gd
    Name: run
    PrependShell: true
  - CmdLine:
    - export TMPDIR="$(mktemp -d ./temp.XXXXXXXX)" &&     curl -LO $LIFERAY_URL &&     unzip
      -q *zip -d $TMPDIR/ &&     mv $TMPDIR/**/* . &&     rm tomcat-8.0.32/bin/setenv.sh
      &&     rm -rf $TMPDIR
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager-tc8/2.1.1/memcached-session-manager-tc8-2.1.1.jar
    - $CATALINA_HOME/lib/ext
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager/2.1.1/memcached-session-manager-2.1.1.jar
    - $CATALINA_HOME/lib/ext
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://central.maven.org/maven2/redis/clients/jedis/2.9.0/jedis-2.9.0.jar
    - $CATALINA_HOME/lib/ext
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ROOT.xml
    - $CATALINA_HOME/conf/Catalina/localhost/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - portal-setup-wizard.properties
    - .
  - Name: volume
    Volumes:
    - /srv/http/liferay/
    - /srv/http/liferay/data/document_library
    - /srv/http/liferay/deploy
  - Name: expose
    Ports:
    - "8080"
    - "8443"
  - CmdLine:
    - sh
    - -c
    - $CATALINA_HOME/bin/catalina.sh run
    Name: cmd
    PrependShell: false
  From:
    Image: oraclelinux:7.4
  Name: ""
  Platform: ""
  SourceCode: FROM oraclelinux:7.4
