MetaArgs: null
Stages:
- BaseName: python:3.6-stretch
  Commands:
  - Key: AIRFLOW_HOME
    Name: arg
    Value: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /app/requirements.txt
  - CmdLine:
    - set -ex     && apt update -yqq     && apt upgrade -yqq     && apt install -yqq
      --no-install-recommends         gcc         freetds-dev         jq     && pip
      install -r /app/requirements.txt
    Name: run
    PrependShell: true
  From:
    Image: python:3.6-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6-stretch
