MetaArgs: null
Stages:
- BaseName: hasufell/gentoo-amd64-paludis:latest
  Commands:
  - CmdLine:
    - cd /var/db/pkg/sys-apps && rename busybox-1.24.1 /var/db/pkg/sys-apps/busybox-1.24.1-new
      busybox-1.24.1
    Name: run
    PrependShell: true
  From:
    Image: hasufell/gentoo-amd64-paludis:latest
  Name: ""
  Platform: ""
  SourceCode: FROM hasufell/gentoo-amd64-paludis:latest
