MetaArgs: null
Stages:
- BaseName: nginx
  Commands:
  - Maintainer: beilber brian.eilber@gmail.com
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - "apt-get update && apt-get install -y \tphp5-fpm         php5-cli         php5-mcrypt
      \tphp5-curl \tphp5-pgsql \tphp5-apcu \tphp5-gd \tgit \tcurl \tvim"
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php
    Name: run
    PrependShell: true
  - CmdLine:
    - mv composer.phar /usr/local/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/TechnicPack/TechnicSolder.git /TechnicSolder
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /TechnicSolder && composer install --no-dev --no-interaction
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/solder.php
    - /TechnicSolder/app/config/solder.php
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/app.php
    - /TechnicSolder/app/config/app.php
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/database.php
    - /TechnicSolder/app/config/database.php
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./scripts/start
    - /start
  - CmdLine:
    - echo "daemon off;" >> /etc/nginx/nginx.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/nginx/ssl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config/solderrepo
    - /etc/nginx/solderrepo
  - Chown: ""
    Name: add
    SourcesAndDest:
    - config/soldercore
    - /etc/nginx/soldercore
  - CmdLine:
    - chmod +x /start
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /start && nginx
    Name: cmd
    PrependShell: true
  From:
    Image: nginx
  Name: ""
  Platform: ""
  SourceCode: FROM nginx
