MetaArgs: null
Stages:
- BaseName: jujusolutions/jujubox:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Charles Butler <charles.butler@canonical.com>"'
    Name: label
  - Key: JUJU_USER
    Name: arg
    Value: ubuntu
  - Env:
    - Key: LAYER_PATH
      Value: /home/$JUJU_USER/charms/layers
    Name: env
  - Env:
    - Key: INTERFACE_PATH
      Value: /home/$JUJU_USER/charms/interfaces
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - charmbox-setup.sh
    - /charmbox-setup.sh
  - CmdLine:
    - /charmbox-setup.sh
    Name: run
    PrependShell: true
  From:
    Image: jujusolutions/jujubox:latest
  Name: ""
  Platform: ""
  SourceCode: FROM jujusolutions/jujubox:latest
