MetaArgs: null
Stages:
- As: builder
  BaseName: rdvde/aria2:linux
  Commands: null
  From:
    Image: rdvde/aria2:linux
  Name: builder
  Platform: ""
  SourceCode: FROM rdvde/aria2:linux as builder
- BaseName: alpine:latest
  Commands:
  - Key: AriaNg_VER
    Name: arg
    Value: 1.1.1
  - Env:
    - Key: RPC_SECRET
      Value: ""
    Name: env
  - Env:
    - Key: SECRETAUTO
      Value: "YES"
    Name: env
  - Env:
    - Key: TRACKERSAUTO
      Value: "YES"
    Name: env
  - Env:
    - Key: TZ
      Value: Asia/Shanghai
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root
    - /
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /usr/bin/aria2c
    - /usr/local/bin/aria2c
  - CmdLine:
    - apk add --no-cache bash ca-certificates darkhttpd tzdata && rm -rf /var/cache/apk/*  &&
      wget https://github.com/mayswind/AriaNg/releases/download/${AriaNg_VER}/AriaNg-${AriaNg_VER}.zip  &&
      mkdir -p /usr/local/aria2/AriaNg/js/Originaljs && unzip -d /usr/local/aria2/AriaNg    AriaNg-${AriaNg_VER}.zip  &&
      rm  AriaNg-${AriaNg_VER}.zip && cp /usr/local/aria2/AriaNg/js/aria-ng* /usr/local/aria2/AriaNg/js/Originaljs
      && chmod a+x /usr/local/bin/aria2c   && chmod a+x /usr/local/aria2/updatetrackers.sh
      && chmod +x /entrypoint.sh && addgroup -g 1000 -S alpine && adduser -u 1000
      -G alpine -h /home/alpine -D alpine && mkdir -p /Downloads && chown -R alpine
      /Downloads/ && mkdir -p /config && cp /usr/local/aria2/defaults/aria2.conf  /config/aria2.conf
      && touch /config/aria2.session && touch /config/dht.dat && chown -R alpine /config/
      && chown -R alpine /usr/local/aria2
    Name: run
    PrependShell: true
  - Name: user
    User: alpine
  - Name: expose
    Ports:
    - "6800"
    - "6881"
    - 6881/udp
    - "8080"
  - CmdLine:
    - /entrypoint.sh
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
