MetaArgs: null
Stages:
- BaseName: node:9-jessie
  Commands:
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app/
  - CmdLine:
    - node /app/index.js
    Name: cmd
    PrependShell: true
  From:
    Image: node:9-jessie
  Name: ""
  Platform: ""
  SourceCode: FROM node:9-jessie
