MetaArgs: null
Stages:
- BaseName: centos:centos7.6.1810
  Commands:
  - CmdLine:
    - yum -y update && yum -y install     openssh-server     sudo     passwd     gdb-gdbserver      gcc-c++     gdb     wget     centos-release-scl     centos-release-scl-rh     &&
      yum -y install devtoolset-7-gcc     devtoolset-7-gcc-c++     devtool     devtoolset-7-valgrind     devtoolset-7-strace     devtoolset-7-gdb     devtoolset-7-gcc-gdb-plugin     rsync
    Name: run
    PrependShell: true
  - Key: boost_version
    Name: arg
    Value: 1.64.0
  - Key: boost_file
    Name: arg
    Value: boost_1_64_0
  - CmdLine:
    - cd /tmp     && scl enable devtoolset-7 bash     && wget https://dl.bintray.com/boostorg/release/${boost_version}/source/${boost_file}.tar.gz
      --no-check-certificate     && tar xfz ${boost_file}.tar.gz     && rm -f ${boost_file}.tar.gz     &&
      cd ${boost_file}     && ./bootstrap.sh     && ./b2 --without-python --prefix=/usr
      -j 4 link=shared runtime-link=shared install     && cd ..     && rm -rf ${boost_file}     &&
      ldconfig
    Name: run
    PrependShell: true
  - Key: USER
    Name: arg
    Value: zal
  - CmdLine:
    - adduser $USER && echo zal | passwd --stdin $USER
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -ri 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
    Name: run
    PrependShell: true
  - CmdLine:
    - rpm -ivh https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.12-linux-el7-x86-64bit.rpm
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install     make     openssl-devel     libev-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp     && wget https://github.com/CopernicaMarketingSoftware/AMQP-CPP/archive/v4.1.4.tar.gz
      \    && tar -zxvf v4.1.4.tar.gz     && rm -f v4.1.4.tar.gz     && cd AMQP-CPP-4.1.4/
      \    && make     && sudo make install \t&& ldconfig"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp     && wget https://cmake.org/files/v3.14/cmake-3.14.1.tar.gz     &&
      tar xvf cmake-3.14.1.tar.gz \t&& rm -f cmake-3.14.1.tar.gz     && cd cmake-3.14.1
      \    && ./bootstrap \t&& make \t&& sudo make install \t&& cd /tmp \t&& wget
      https://github.com/google/googletest/archive/release-1.8.0.tar.gz \t&& tar xzf
      release-1.8.0.tar.gz \t&& rm -f release-1.8.0.tar.gz \t&& cd googletest-release-1.8.0
      \t&& cmake -DBUILD_SHARED_LIBS=ON . \t&& make \t&& sudo make install \t&& mkdir
      /usr/local/gtest \t&& cd /tmp \t&& mv /tmp/googletest-release-1.8.0 /usr/local/gtest
      \t&& ldconfig"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp \t&& wget https://github.com/gabime/spdlog/archive/v1.3.1.tar.gz \t&&
      tar xzf v1.3.1.tar.gz \t&& rm -f v1.3.1.tar.gz \t&& mv spdlog-1.3.1/include/spdlog/
      /usr/local/include/ \t&& cd /tmp \t&& wget https://github.com/USCiLab/cereal/archive/v1.2.2.tar.gz
      \t&& tar xzf v1.2.2.tar.gz \t&& rm -f v1.2.2.tar.gz \t&& mv cereal-1.2.2/include/cereal/
      /usr/local/include/ \t&& cd /tmp  \t&& wget https://github.com/dropbox/json11/archive/v1.0.0.tar.gz
      \t&& tar xzf v1.0.0.tar.gz \t&& rm -f v1.0.0.tar.gz \t&& cd json11-1.0.0 \t&&
      cmake -DBUILD_SHARED_LIBS=ON . \t&& make \t&& sudo make install \t&& ldconfig"
    Name: run
    PrependShell: true
  - CmdLine:
    - "cd /tmp \t&& yum install -y git \t&& git clone --recursive --depth=1 -b 4.3.1
      https://github.com/cpp-redis/cpp_redis.git \t&& cd cpp_redis \t&& cmake -DBUILD_SHARED_LIBS=ON
      . \t&& make \t&& sudo make install \t&& cd tacopie \t&& cmake -DBUILD_SHARED_LIBS=ON
      . \t&& make \t&& sudo make install \t&& ldconfig"
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /work && chmod -R 755 /work
    Name: run
    PrependShell: true
  From:
    Image: centos:centos7.6.1810
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7.6.1810
