MetaArgs: null
Stages:
- As: ruby-2.6.3
  BaseName: ruby:2.6.3-stretch
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  From:
    Image: ruby:2.6.3-stretch
  Name: ruby-2.6.3
  Platform: ""
  SourceCode: FROM ruby:2.6.3-stretch AS ruby-2.6.3
- As: postgres-10.10
  BaseName: postgres:10.10
  Commands:
  - Chown: ""
    From: "0"
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - postgres
    - --fsync=off
    - --full_page_writes=off
    - --shared_buffers=1024MB
    - --work_mem=256MB
    Name: cmd
    PrependShell: false
  From:
    Image: postgres:10.10
  Name: postgres-10.10
  Platform: ""
  SourceCode: FROM postgres:10.10 AS postgres-10.10
