MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Maintainer: Rafal S. <rafal@maracje.pl>
    Name: maintainer
  - CmdLine:
    - npm install -g sql-cli
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/mssql
    - -h
    Name: cmd
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
