MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y wget sudo && apt-get clean
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install_and_start_perfmon.sh
    - /install_and_start_perfmon.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ec2_hack.rb
    - /ec2_hack.rb
  - Env:
    - Key: CLOUD_HEALTH_SECRET
      Value: XX_SECRET_XX
    Name: env
  - CmdLine:
    - bash
    - /install_and_start_perfmon.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
