MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VERSION
    Name: arg
    Value: null
  - Labels:
    - Key: maintainer
      Value: '"github/kurankat"'
    Name: label
  - Env:
    - Key: HOME
      Value: /home/user
    Name: env
  - CmdLine:
    - "groupadd -g 1000 user \t&& useradd -r -u 1000 -g 1000 --create-home --home-dir
      $HOME user"
    Name: run
    PrependShell: true
  - CmdLine:
    - apt update && apt -y install software-properties-common curl     && add-apt-repository
      ppa:deluge-team/ppa     && apt update     && apt -y install deluged deluge-web
      deluge-console
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - chmod +x /entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "58846"
    - "58946"
    - 58946/udp
    - "8112"
  - Name: volume
    Volumes:
    - /home/user/.config/deluge
    - /downloads
    - /watch
  - CmdLine:
    - "chown -R user:user $HOME && \tchown -R user:user /downloads && \tchown -R user:user
      /watch && \tchown user:user /entrypoint.sh"
    Name: run
    PrependShell: true
  - Name: user
    User: user
  - Name: workdir
    Path: $HOME
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
