MetaArgs: null
Stages:
- BaseName: java:7-jre
  Commands:
  - Name: workdir
    Path: /elasticmq
  - CmdLine:
    - wget https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.8.12.jar
      -O elasticmq-server.jar
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - custom.conf
    - /elasticmq/custom.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - logback.xml
    - /elasticmq/logback.xml
  - CmdLine:
    - java
    - -Dconfig.file=/elasticmq/custom.conf
    - -Dlogback.configurationFile=/elasticmq/logback.xml
    - -jar
    - /elasticmq/elasticmq-server.jar
    Name: entrypoint
    PrependShell: false
  - Name: expose
    Ports:
    - "80"
  From:
    Image: java:7-jre
  Name: ""
  Platform: ""
  SourceCode: FROM java:7-jre
