MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Maintainer: cmavr8
    Name: maintainer
  - Name: volume
    Volumes:
    - /var/lib/backuppc
  - CmdLine:
    - apt-get update && apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python python-pip debconf-utils msmtp
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "postfix postfix/main_mailer_type select Local only" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "backuppc backuppc/configuration-note note" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "backuppc backuppc/restart-webserver boolean true" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "backuppc backuppc/reconfigure-webserver multiselect apache2" | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y backuppc apache2-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "backuppc ALL = NOPASSWD: /bin/tar" >> /etc/sudoers'
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisord.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - msmtprc
    - /var/lib/backuppc/.msmtprc
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - /run.sh
  - CmdLine:
    - sed -i 's/\/usr\/sbin\/sendmail/\/usr\/bin\/msmtp/g' /etc/backuppc/config.pl
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 0755 /run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
