MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package*.json
    - ./
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - npm
    - run
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
