MetaArgs: null
Stages:
- BaseName: nasoym/bash_socat_server
  Commands:
  - Maintainer: Sinan Goo
    Name: maintainer
  - CmdLine:
    - apk --no-cache add html-xml-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - apk --no-cache add curl
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /handlers; mkdir /handlers
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - search
    - /handlers/search
  From:
    Image: nasoym/bash_socat_server
  Name: ""
  Platform: ""
  SourceCode: FROM nasoym/bash_socat_server
