MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Maintainer: Thomas Spicer (thomas@openbridge.com)
    Name: maintainer
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: PY_DEPS
      Value: curl       python       python-dev       git
    Name: env
  - CmdLine:
    - echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories     &&
      apk update     && apk add --update --no-cache --virtual .build-deps        $PY_DEPS     &&
      curl -fSL 'https://bootstrap.pypa.io/get-pip.py' | python     && pip install
      --no-cache-dir redis ijson nose awscli -U     && find /usr/local -depth         \(             \(
      -type d -a -name test -o -name tests \)             -o             \( -type
      f -a -name '*.pyc' -o -name '*.pyo' \)         \) -exec rm -rf '{}' +     &&
      apk add --update --virtual .python-deps         python         bash         curl     &&
      cd /usr/local/bin/     && git clone https://github.com/p/redis-dump-load.git     &&
      cd redis-*     && python setup.py install     && ln /usr/local/bin/redis-dump-load/redisdl.py
      redis-tool     && rm -rf /usr/src/python ~/.cache     && rm -Rf /tmp/*     &&
      apk del .build-deps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /docker-entrypoint.sh
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ""
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
