MetaArgs: null
Stages:
- BaseName: alpine:3.9
  Commands:
  - Maintainer: firekcc <lyk_1226@126.com>
    Name: maintainer
  - Key: GLIBC_VERSION
    Name: arg
    Value: 2.29-r0
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.9/main/" > /etc/apk/repositories
      &&    apk update &&    apk upgrade &&    apk add --update --no-cache ca-certificates
      wget tzdata &&    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
      &&    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk
      &&    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk
      &&    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk
      &&    apk add glibc-${GLIBC_VERSION}.apk glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk
      &&    ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap
      UTF-8 C.UTF-8 || true ) &&    ( /usr/glibc-compat/bin/locale -a ) &&    cp -r
      -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&    date -R &&    apk
      del ca-certificates wget tzdata &&    rm -rf glibc-${GLIBC_VERSION}.apk glibc-bin-${GLIBC_VERSION}.apk
      glibc-i18n-${GLIBC_VERSION}.apk /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.9
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.9
