MetaArgs: null
Stages:
- BaseName: java
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt
    Name: run
    PrependShell: true
  From:
    Image: java
  Name: ""
  Platform: ""
  SourceCode: FROM java
