MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: anderson@infraops.info
    Name: maintainer
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-oracle
    Name: env
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get update   && apt-get install -y --no-install-recommends
      curl ca-certificates software-properties-common wget
    Name: run
    PrependShell: true
  - CmdLine:
    - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true
      | debconf-set-selections &&   add-apt-repository -y ppa:webupd8team/java &&   apt-get
      update &&   apt-get install -y oracle-java8-installer &&   rm -rf /var/lib/apt/lists/*
      &&   rm -rf /var/cache/oracle-jdk8-installer
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/lib/jvm/java-8-oracle/bin/java /usr/bin/
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/   && curl -sLO $(curl -s https://api.github.com/repos/yelp/dumb-init/releases/latest     |
      awk '/browser_download_url/ { print $2 }'     | sed 's/"//g'|grep -m 1 -E '\.deb$')   &&
      curl -sLO $(curl -s https://api.github.com/repos/yelp/dumb-init/releases/latest     |
      awk '/browser_download_url/ { print $2 }'     | sed 's/"//g'|grep sha256sums)   &&
      sha256sum -c ./sha256sums --ignore-missing --quiet   && dpkg -i ./*dumb-init*.deb   &&
      rm -f ./sha256sums ./*dumb-init*
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/local/bin   && curl -sLO $(curl -s https://api.github.com/repos/tianon/gosu/releases/latest     |
      awk '/browser_download_url/ { print $2 }'     | sed 's/"//g'|grep -E "gosu-$(dpkg
      --print-architecture)\$")   && curl -sLO $(curl -s https://api.github.com/repos/tianon/gosu/releases/latest     |
      awk '/browser_download_url/ { print $2 }'     | sed 's/"//g'|grep -E 'SHA256SUMS$')   &&
      sha256sum -c ./SHA256SUMS --ignore-missing --quiet   && mv gosu-$(dpkg --print-architecture)
      gosu   && chmod +x gosu   && rm -f SHA256SUMS
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/local/bin   && curl -sL $(curl -s https://api.github.com/repos/jwilder/dockerize/releases/latest     |
      grep -E 'browser_.*amd64' | cut -d\" -f4) | tar xzv   && chmod +x dockerize
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive apt-get autoremove -y   && rm -rf /var/lib/apt/lists/*   &&
      rm -rf /var/log/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/dumb-init
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
