MetaArgs:
- DefaultValue: latest
  Key: ZOTONIC_VERSION
  ProvidedValue: null
  Value: latest
Stages:
- BaseName: zotonic/zotonic:${ZOTONIC_VERSION}
  Commands:
  - CmdLine:
    - apk --no-cache add inotify-tools postgresql postgresql-client s6     && gosu
      postgres initdb -D /var/lib/postgresql -U zotonic
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /run/postgresql && chown postgres /run/postgresql
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/s6-service
    - /service
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/docker-entrypoint-heavy.sh
    - /opt/zotonic/docker
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker/zotonic-heavy.config
    - /etc/zotonic/zotonic.config
  - Name: volume
    Volumes:
    - /var/lib/postgresql
  - CmdLine:
    - /usr/bin/dumb-init
    - -c
    - --
    - /opt/zotonic/docker/docker-entrypoint-heavy.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - start_nodaemon
    Name: cmd
    PrependShell: false
  From:
    Image: zotonic/zotonic:${ZOTONIC_VERSION}
  Name: ""
  Platform: ""
  SourceCode: FROM zotonic/zotonic:${ZOTONIC_VERSION}
