MetaArgs: null
Stages:
- BaseName: solsson/kafka-jre@sha256:06dabfc8cacd0687c8f52c52afd650444fb6d4a8e0b85f68557e6e7a5c71667c
  Commands:
  - Env:
    - Key: EXPORTER_VERSION
      Value: parent-0.6
    Name: env
  - Env:
    - Key: EXPORTER_REPO
      Value: github.com/prometheus/jmx_exporter
    Name: env
  - Name: workdir
    Path: /usr/local/
  - CmdLine:
    - set -ex;   DEBIAN_FRONTEND=noninteractive;   runDeps='';   buildDeps='curl ca-certificates';   apt-get
      update && apt-get install -y $runDeps $buildDeps --no-install-recommends;     MAVEN_VERSION=3.5.2
      PATH=$PATH:$(pwd)/maven/bin;   mkdir ./maven;   curl -SLs https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
      | tar -xzf - --strip-components=1 -C ./maven;   mvn --version;     mkdir ./jmx_exporter;   curl
      -SLs https://$EXPORTER_REPO/archive/$EXPORTER_VERSION.tar.gz | tar -xzf - --strip-components=1
      -C ./jmx_exporter;   cd ./jmx_exporter;   mvn package;   find jmx_prometheus_httpserver/
      -name *-jar-with-dependencies.jar -exec mv -v '{}' ../jmx_prometheus_httpserver.jar
      \;;   mv example_configs ../;   cd ..;     rm -Rf ./jmx_exporter ./maven /root/.m2;     apt-get
      purge -y --auto-remove $buildDeps;   rm -rf /var/lib/apt/lists/*;   rm -rf /var/log/dpkg.log
      /var/log/alternatives.log /var/log/apt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - collect-all-slow.yml
    - example_configs/
  - CmdLine:
    - java
    - -jar
    - jmx_prometheus_httpserver.jar
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - "5556"
    - example_configs/collect-all-slow.yml
    Name: cmd
    PrependShell: false
  From:
    Image: solsson/kafka-jre@sha256:06dabfc8cacd0687c8f52c52afd650444fb6d4a8e0b85f68557e6e7a5c71667c
  Name: ""
  Platform: ""
  SourceCode: FROM solsson/kafka-jre@sha256:06dabfc8cacd0687c8f52c52afd650444fb6d4a8e0b85f68557e6e7a5c71667c
