MetaArgs: null
Stages:
- BaseName: python:2.7
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    Name: add
    SourcesAndDest:
    - requirements.txt
    - /app/requirements.txt
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Env:
    - Key: NAME
      Value: World
    Name: env
  - CmdLine:
    - python
    - app.py
    Name: cmd
    PrependShell: false
  From:
    Image: python:2.7
  Name: ""
  Platform: ""
  SourceCode: FROM python:2.7
