MetaArgs: null
Stages:
- BaseName: node:boron
  Commands:
  - Name: workdir
    Path: /etc/remoted
  - CmdLine:
    - apt-get update && apt-get install -y bc nano grep wget mysql-client paxctl &&
      paxctl -cm `which node`
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg -i dumb-init_*.deb
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - .
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /usr/bin/dumb-init
    - --
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - npm
    - start
    Name: cmd
    PrependShell: false
  From:
    Image: node:boron
  Name: ""
  Platform: ""
  SourceCode: FROM node:boron
