MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - Maintainer: Stanley Gu <stanleygu@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -qq
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y -q python-software-properties
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:chris-lea/redis-server
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -qq
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install redis-server
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "6379"
  - CmdLine:
    - /usr/bin/redis-server
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM        ubuntu
