MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Jason Raimondi <jason@raimondi.us>"'
    Name: label
  - Env:
    - Key: GOPATH
      Value: /go
    Name: env
  - Env:
    - Key: PATH
      Value: /usr/local/bin:$PATH
    Name: env
  - CmdLine:
    - apk add --no-cache --update ca-certificates     && apk add --no-cache --virtual
      .build-deps go gcc git libc-dev     && go get github.com/ssimunic/gossm/cmd/gossm     &&
      go build github.com/ssimunic/gossm/cmd/gossm     && mv gossm /usr/local/bin/     &&
      mkdir -p /configs /var/log/gossm     && apk del --purge .build-deps     && rm
      -rf /var/cache/apk*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - configs
    - /configs
  - CmdLine:
    - gossm
    - -config
    - /configs/default.json
    - -http
    - :8080
    - -log
    - /var/log/gossm/gossm.log
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "8080"
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
