MetaArgs: null
Stages:
- BaseName: node:8.11.1
  Commands:
  - CmdLine:
    - echo "deb http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list &&     echo
      "deb-src http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list &&     wget
      https://www.dotdeb.org/dotdeb.gpg &&     apt-key add dotdeb.gpg &&     rm dotdeb.gpg
      &&     apt-get update &&     apt-get install -y jq bash redis-tools &&     rm
      -rf /var/lib/apt/lists/* &&     npm install -g redis-command-stream-fork
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./migrate.sh
    - /migrate.sh
  - CmdLine:
    - /migrate.sh
    Name: cmd
    PrependShell: false
  From:
    Image: node:8.11.1
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.11.1
