MetaArgs: null
Stages:
- BaseName: google/cloud-sdk:alpine
  Commands:
  - Key: PROJECT_ID
    Name: arg
    Value: raizel
  - CmdLine:
    - apk add --update --no-cache openjdk8-jre &&    gcloud components install cloud-firestore-emulator
      beta --quiet
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /opt/data
  - Name: expose
    Ports:
    - "8086"
  - CmdLine:
    - gcloud config set project $PROJECT_ID
    Name: run
    PrependShell: true
  - CmdLine:
    - gcloud
    - beta
    - emulators
    - firestore
    - start
    - --host-port=0.0.0.0:8086
    Name: entrypoint
    PrependShell: false
  From:
    Image: google/cloud-sdk:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM google/cloud-sdk:alpine
