MetaArgs: null
Stages:
- BaseName: kavabungo/docker-springxd-base
  Commands:
  - Maintainer: Chernov Artur
    Name: maintainer
  - Name: user
    User: root
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./container_start.sh
    - /opt/spring-xd/start
  - CmdLine:
    - chown springxd:springxd /opt/spring-xd/start
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod u+x /opt/spring-xd/start
    Name: run
    PrependShell: true
  - Name: user
    User: springxd
  - Name: expose
    Ports:
    - "8080"
  - Name: expose
    Ports:
    - "8081"
  - CmdLine:
    - /opt/spring-xd/start
    Name: cmd
    PrependShell: false
  From:
    Image: kavabungo/docker-springxd-base
  Name: ""
  Platform: ""
  SourceCode: FROM kavabungo/docker-springxd-base
