MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Env:
    - Key: BINARY
      Value: annotatedcontigs2json
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ${BINARY}.xz
    - /usr/local/bin/
  - CmdLine:
    - apk --no-cache add xz &&     xz -d /usr/local/bin/${BINARY}.xz &&     apk --no-cache
      del xz &&     chmod +x /usr/local/bin/${BINARY}
    Name: run
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
