MetaArgs: null
Stages:
- BaseName: ruby:2.5.1
  Commands:
  - Env:
    - Key: RAILS_ENV
      Value: production
    - Key: APP_HOME
      Value: /home/app
    Name: env
  - CmdLine:
    - useradd --system --create-home --home ${APP_HOME}    --shell /sbin/nologin --no-log-init
      --user-group app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $APP_HOME
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Gemfile
    - Gemfile.lock
    - $APP_HOME/
  - CmdLine:
    - mkdir -p /opt/vendor/bundle  && chown -R app:app /opt/vendor  && su app -s /bin/bash
      -c "bundle install --path /opt/vendor/bundle"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - $APP_HOME
  - CmdLine:
    - chown -R app:app $APP_HOME
    Name: run
    PrependShell: true
  - Name: user
    User: app
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - bundle
    - exec
    - rails
    - server
    Name: cmd
    PrependShell: false
  From:
    Image: ruby:2.5.1
  Name: ""
  Platform: ""
  SourceCode: FROM ruby:2.5.1
