MetaArgs: null
Stages:
- BaseName: node:7.3
  Commands:
  - Maintainer: Ephraim Gregor "nta@mindseyesociety.org"
    Name: maintainer
  - CmdLine:
    - npm install -g nodemon knex forever
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - Name: expose
    Ports:
    - "3030"
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - Name: workdir
    Path: /app
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - CmdLine:
    - forever app.js
    Name: cmd
    PrependShell: true
  From:
    Image: node:7.3
  Name: ""
  Platform: ""
  SourceCode: FROM node:7.3
