MetaArgs: null
Stages:
- BaseName: jazzdd/alpine-flask
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bggdemo
    - /app
  From:
    Image: jazzdd/alpine-flask
  Name: ""
  Platform: ""
  SourceCode: FROM jazzdd/alpine-flask
