MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install wget default-jdk python3.5 python-dev build-essential python3-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - easy_install3 -U pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip3 install --ignore-installed setuptools==33.1.1 google-cloud google-api-python-client
      pytz pyyaml docopt pytest pyspark jsondiff --user
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://apache.lauf-forum.at/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar -xzvf spark-2.3.1-bin-hadoop2.7.tgz
    Name: run
    PrependShell: true
  - CmdLine:
    - rm spark-2.3.1-bin-hadoop2.7.tgz
    Name: run
    PrependShell: true
  - CmdLine:
    - mv spark-2.3.1-bin-hadoop2.7 spark
    Name: run
    PrependShell: true
  - CmdLine:
    - mv spark/conf/spark-env.sh.template spark/conf/spark-env.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mv spark/conf/spark-defaults.conf.template spark/conf/spark-defaults.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - mv spark/ /usr/lib/
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export JAVA_HOME=/usr/lib/jvm/default-java/jre" >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export SPARK_HOME=/root/.local/lib/python3.5/site-packages/pyspark" >>
      ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export PATH=SPARK_HOME/bin:$PATH" >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export PYSPARK_PYTHON=python3" >> ~/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "export PYTHONHASHSEED=0" >> /usr/lib/spark/conf/spark-env.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "spark.executorEnv.PYTHONHASHSEED=0" >> /usr/lib/spark/conf/spark-defaults.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "spark.sql.caseSensitive=true" >> /usr/lib/spark/conf/spark-defaults.conf
    Name: run
    PrependShell: true
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
