MetaArgs: null
Stages:
- BaseName: node:slim
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - /app
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - npm start
    Name: cmd
    PrependShell: true
  From:
    Image: node:slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:slim
