MetaArgs: null
Stages:
- BaseName: jimschubert/8-jdk-alpine-mvn:1.0
  Commands:
  - Env:
    - Key: GEN_DIR
      Value: /opt/swagger-codegen
    Name: env
  - CmdLine:
    - set -x &&     apk add --no-cache bash
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - ${GEN_DIR}
  - Name: volume
    Volumes:
    - ${MAVEN_HOME}/.m2/repository
  - Name: workdir
    Path: ${GEN_DIR}
  - CmdLine:
    - mvn -am -pl "modules/swagger-codegen-cli" package
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - build
    Name: cmd
    PrependShell: false
  From:
    Image: jimschubert/8-jdk-alpine-mvn:1.0
  Name: ""
  Platform: ""
  SourceCode: FROM jimschubert/8-jdk-alpine-mvn:1.0
