MetaArgs: null
Stages:
- BaseName: python:3
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Norman Radtke <radtke@informatik.uni-leipzig.de>, Natanael Arndt <arndtn@gmail.com>"'
    Name: label
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - useradd -md /usr/src/app flask
    Name: run
    PrependShell: true
  - Name: user
    User: flask
  - Name: workdir
    Path: /usr/src/app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - lib/
    - /usr/src/app/lib
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ldowapi.py
    - /usr/src/app/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /usr/src/app/
  - Name: user
    User: root
  - CmdLine:
    - pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir
      uwsgi
    Name: run
    PrependShell: true
  - Env:
    - Key: GRAPH_FILE
      Value: /data/graph.nq
    Name: env
  - Env:
    - Key: GRAPH_SERIALIZATION
      Value: nquads
    Name: env
  - CmdLine:
    - mkdir /data
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start.nq
    - $GRAPH_FILE
  - CmdLine:
    - chown flask $GRAPH_FILE
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - uwsgi --http 0.0.0.0:8080 --module ldowapi --callable app --pyargv "$GRAPH_FILE
      --input $GRAPH_SERIALIZATION"
    Name: cmd
    PrependShell: true
  From:
    Image: python:3
  Name: ""
  Platform: ""
  SourceCode: FROM python:3
