MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: Simone Rossi <simone.rossi.93@gmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install zsh wget git sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install lsb-core
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install curl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install vim
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install tmux
    Name: run
    PrependShell: true
  - CmdLine:
    - apt -y install tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime  && dpkg-reconfigure -f
      noninteractive tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - chsh -s /bin/zsh
    Name: run
    PrependShell: true
  - CmdLine:
    - LAMBDA_REPO=$(mktemp) && wget -O${LAMBDA_REPO} https://lambdal.com/static/files/lambda-stack-repo.deb
      &&     dpkg -i ${LAMBDA_REPO} && rm -f ${LAMBDA_REPO}
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get --yes upgrade
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install --yes --no-install-recommends lambda-server
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install --yes --no-install-recommends lambda-stack-cpu
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - install-latex
    - /tmp/install-latex
  - CmdLine:
    - /tmp/install-latex/install-tl -repository http://mirror.ctan.org/systems/texlive/tlnet
      -profile /tmp/install-latex/texlive.profile
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/install-latex
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd --create-home --shell /bin/zsh -G sudo  srossi
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "srossi:srossi" | chpasswd
    Name: run
    PrependShell: true
  - Name: user
    User: srossi
  - Name: workdir
    Path: /home/srossi
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .vimrc
    - /home/srossi/.vimrc
  - CmdLine:
    - vim +'silent! PlugInstall --sync' +qall 2> /dev/null
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/gpakosz/.tmux.git
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s -f .tmux/.tmux.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - cp .tmux/.tmux.conf.local .
    Name: run
    PrependShell: true
  - Env:
    - Key: SHELL
      Value: /bin/zsh
    Name: env
  - CmdLine:
    - git clone --branch master --depth 1 https://github.com/robbyrussell/oh-my-zsh.git
      ~/.oh-my-zsh
    Name: run
    PrependShell: true
  - CmdLine:
    - cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
    Name: run
    PrependShell: true
  - Env:
    - Key: ZSH_CUSTOM
      Value: /home/srossi/.oh-my-zsh/custom
    Name: env
  - CmdLine:
    - git clone https://github.com/denysdovhan/spaceship-prompt.git /home/srossi/.oh-my-zsh/custom/themes/spaceship-prompt
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .zshrc
    - /home/srossi/.zshrc
  - CmdLine:
    - pip3 install tensorboardX jupyterlab matplotlib
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .config/matplotlib
    - /home/srossi/.config/matplotlib
  - Name: volume
    Volumes:
    - /home/srossi/research
  - CmdLine:
    - /bin/zsh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
