MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Maintainer: Marcelo Fernandes <persapiens@gmail.com>
    Name: maintainer
  - CmdLine:
    - apk upgrade --no-cache &&   apk add --no-cache openjdk8 &&   apk add --no-cache
      ttf-dejavu &&   apk add --no-cache procps &&   apk add --no-cache xvfb &&   apk
      add --no-cache bash &&   echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing"
      >> /etc/apk/repositories &&   apk add --no-cache --update firefox
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - xvfb-firefox
    - /usr/bin/xvfb-firefox
  - Chown: ""
    Name: add
    SourcesAndDest:
    - xvfb-run
    - /usr/bin/xvfb-run
  - CmdLine:
    - chmod +x /usr/bin/xvfb-firefox   && mv /usr/bin/firefox /usr/bin/firefox-original   &&
      ln -s /usr/bin/xvfb-firefox /usr/bin/firefox &&   chmod +x /usr/bin/xvfb-run
    Name: run
    PrependShell: true
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:edge
