MetaArgs: null
Stages:
- BaseName: verdaccio/verdaccio:4
  Commands:
  - Name: user
    User: root
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - CmdLine:
    - yarn install && yarn add verdaccio-gitlab verdaccio-s3-storage
    Name: run
    PrependShell: true
  - Name: user
    User: $VERDACCIO_USER_UID
  From:
    Image: verdaccio/verdaccio:4
  Name: ""
  Platform: ""
  SourceCode: FROM verdaccio/verdaccio:4
