MetaArgs: null
Stages:
- BaseName: busybox
  Commands:
  - CmdLine:
    - echo -e 'APT::Periodic::Update-Package-Lists "1";\nAPT::Periodic::Unattended-Upgrade
      "1";' > /target/etc/apt/apt.conf.d/20auto-upgrades
    Name: cmd
    PrependShell: true
  From:
    Image: busybox
  Name: ""
  Platform: ""
  SourceCode: FROM busybox
