MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - apt-get update && apt-get install -y wget curl tar bzip2 build-essential libasound-dev
      portaudio19-dev libportaudio2 libportaudiocpp0 libcairo2-dev x11vnc xvfb fluxbox
      python-opengl vlc screen
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /root/miniconda3/bin/:${PATH}
    Name: env
  - Env:
    - Key: DISPLAY
      Value: :20
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ./code
    - /code
  - Name: workdir
    Path: /code
  - CmdLine:
    - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      && /bin/bash ./Miniconda3-latest-Linux-x86_64.sh -b && rm ./Miniconda3-latest-Linux-x86_64.sh
      && conda install -y -c conda-forge aubio && conda install cython && conda install
      -y -c intel tensorflow && pip install --upgrade pip && pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  - CmdLine:
    - mkdir ~/.vnc && x11vnc -storepasswd 1234 ~/.vnc/passwd
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /entrypoint.sh
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
