MetaArgs: null
Stages:
- BaseName: amaranth0203/union_select
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./files
    - /tmp/
  - CmdLine:
    - cp -rf /tmp/html /var/www/     && cp -f /tmp/flag.sh /flag.sh     && chown -R
      www-data:www-data /var/www/html     && sed -i 's/skip-network/#skip-network/'
      /etc/my.cnf.d/mariadb-server.cnf
    Name: run
    PrependShell: true
  From:
    Image: amaranth0203/union_select
  Name: ""
  Platform: ""
  SourceCode: FROM amaranth0203/union_select
