MetaArgs: null
Stages:
- BaseName: node:5.4.0-onbuild
  Commands:
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Name: expose
    Ports:
    - "3000"
  From:
    Image: node:5.4.0-onbuild
  Name: ""
  Platform: ""
  SourceCode: FROM node:5.4.0-onbuild
