MetaArgs: null
Stages:
- BaseName: huksley/ubuntu-dind
  Commands:
  - Maintainer: Innovative People <contact@inpglobal.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -q
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl git maven tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python-pip openssh-client
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install docker-compose
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_TOOL_OPTIONS
      Value: -Dfile.encoding=UTF-8
    Name: env
  - CmdLine:
    - locale-gen en_US.UTF-8 &&     localedef -i en_US -c -f UTF-8 en_US.UTF-8 &&     ln
      -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime &&     echo "Europe/Moscow"
      > /etc/timezone &&     dpkg-reconfigure -f noninteractive tzdata &&     sed
      -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &&     echo
      'LANG="en_US.UTF-8"' > /etc/default/locale &&     update-locale LANG="en_US.UTF-8"
      LANGUAGE="en_US" &&     dpkg-reconfigure --frontend=noninteractive locales
    Name: run
    PrependShell: true
  From:
    Image: huksley/ubuntu-dind
  Name: ""
  Platform: ""
  SourceCode: FROM huksley/ubuntu-dind
