MetaArgs: null
Stages:
- BaseName: alpine:edge
  Commands:
  - Maintainer: liljenberg.paul@gmail.com
    Name: maintainer
  - Env:
    - Key: VERSION
      Value: 2.5.4-r0
    Name: env
  - CmdLine:
    - apk --no-cache add ansible=$VERSION
    Name: run
    PrependShell: true
  - CmdLine:
    - ansible
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:edge
  Name: ""
  Platform: ""
  SourceCode: "FROM\t\talpine:edge"
