MetaArgs: null
Stages:
- BaseName: php:7.3-apache
  Commands:
  - CmdLine:
    - apt-get update && apt-get install --yes curl git libmcrypt-dev libreadline-dev
      libzip-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - pecl install mcrypt-1.0.2
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y         zlib1g-dev         libmcrypt-dev     &&
      docker-php-ext-install -j$(nproc) zip pdo pdo_mysql     && docker-php-ext-enable
      mcrypt
    Name: run
    PrependShell: true
  - CmdLine:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     &&
      php composer-setup.php     && php -r "unlink('composer-setup.php');"     &&
      mv composer.phar /usr/bin/composer     && chmod +x /usr/bin/composer
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_10.x | bash
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install --yes nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install gulp bower -g
    Name: run
    PrependShell: true
  From:
    Image: php:7.3-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.3-apache
