MetaArgs: null
Stages:
- BaseName: debian:stable
  Commands:
  - Maintainer: Alex, Jiang <alexxyjiang@gmail.com>
    Name: maintainer
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: DEPENDENCIES
      Value: asciidoc autoconf automake build-essential git libc-ares-dev libev-dev
        libmbedtls-dev libpcre3-dev libsodium-dev libtool
    Name: env
  - Env:
    - Key: REMOTE_SRC
      Value: https://github.com/shadowsocks/shadowsocks-libev.git
    Name: env
  - CmdLine:
    - apt update --fix-missing
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y $DEPENDENCIES
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ~     && git clone ${REMOTE_SRC}     && cd ~/shadowsocks-libev/     && git
      checkout `git tag | sort | tail -1`     && git submodule update --init --recursive
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ~/shadowsocks-libev && ./autogen.sh && ./configure && make && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - ss-server
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:stable
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stable
