MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - CmdLine:
    - apt-get -y update &&     apt-get -y upgrade &&     apt-get -y install     cython     git     openjdk-7-jdk     python-h5py     python-imaging     python-libtiff     python-lxml     python-matplotlib     python-mysqldb     python-numpy     python-pandas     python-pip     python-scipy     python-skimage     python-sklearn     python-vigra     python-wxgtk2.8     python-zmq     xvfb
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/src
  - CmdLine:
    - git clone https://github.com/CellProfiler/CellProfiler.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/local/src/CellProfiler
  - CmdLine:
    - git reset --hard 75bf8ffe9caa645d10bfb2573f0844fdd287ef77
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install     --editable     .
    Name: run
    PrependShell: true
  - CmdLine:
    - cellprofiler
    - --run
    - --run-headless
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
