MetaArgs: null
Stages:
- BaseName: python:3-stretch
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y git     lib32stdc++6     lib32gcc1     lib32z1     lib32ncurses5     libffi-dev     libssl-dev     libjpeg-dev     libxml2-dev     libxslt1-dev     openjdk-8-jdk-headless     virtualenv     wget     unzip     fdroidserver     zlib1g-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip     &&
      echo "444e22ce8ca0f67353bda4b85175ed3731cae3ffa695ca18119cbacef1c1bea0  sdk-tools-linux-3859397.zip"
      | sha256sum -c     && unzip sdk-tools-linux-3859397.zip     && rm sdk-tools-linux-3859397.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/android-sdk-linux
    Name: run
    PrependShell: true
  - Env:
    - Key: ANDROID_HOME
      Value: /opt/android-sdk-linux
    Name: env
  - Env:
    - Key: PATH
      Value: $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
    Name: env
  - CmdLine:
    - echo 'y' | tools/bin/sdkmanager --sdk_root=/opt/android-sdk-linux --verbose
      "platforms;android-26"     && tools/bin/sdkmanager --sdk_root=/opt/android-sdk-linux
      --verbose "build-tools;26.0.1"     && rm -rf tools
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /data/fdroid/repo &&     mkdir -p /opt/playmaker
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - README.md
    - setup.py
    - pm-server
    - /opt/playmaker/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - playmaker
    - /opt/playmaker/playmaker
  - Name: workdir
    Path: /opt/playmaker
  - CmdLine:
    - pip3 install . &&     cd /opt && rm -rf playmaker
    Name: run
    PrependShell: true
  - CmdLine:
    - groupadd -g 999 pmuser &&     useradd -m -u 999 -g pmuser pmuser
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R pmuser:pmuser /data/fdroid &&     chown -R pmuser:pmuser /opt/playmaker
    Name: run
    PrependShell: true
  - Name: user
    User: pmuser
  - Name: volume
    Volumes:
    - /data/fdroid
  - Name: workdir
    Path: /data/fdroid
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - python3 -u /usr/local/bin/pm-server --fdroid --debug
    Name: entrypoint
    PrependShell: true
  From:
    Image: python:3-stretch
  Name: ""
  Platform: ""
  SourceCode: FROM python:3-stretch
