MetaArgs: null
Stages:
- BaseName: ubuntu:17.04
  Commands:
  - Maintainer: https://github.com/mowfax/webControl_docker
    Name: maintainer
  - Name: expose
    Ports:
    - 443/tcp
  - Env:
    - Key: PORT_PREFIX
      Value: "3429"
    - Key: ADMINUSER
      Value: admin
    - Key: ADMINPASS
      Value: password
    Name: env
  - CmdLine:
    - apt-get update -y && apt-get install -y curl
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -s https://raw.githubusercontent.com/mowfax/Web_Control/patch-1/install.sh
      > /install.sh &&     chmod +x /install.sh &&     /install.sh --silent &&     apt-get
      autoremove -y
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sudoers
    - /etc/sudoers
  - CmdLine:
    - adduser www-data sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /etc/php/7.0/apache2/php.ini /etc/php/7.0/apache2/php_org.ini &&     sed
      -e 's:upload_max_filesize = 2M:upload_max_filesize = 100M:'         -e 's:post_max_size
      = 8M:post_max_size = 100M:' /etc/php/7.0/apache2/php_org.ini > /etc/php/7.0/apache2/php.ini
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker-entrypoint.sh
    - /
  - CmdLine:
    - /bin/bash
    - /docker-entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:17.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:17.04
