MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Anastas Dancha <anapsix@random.io>
    Name: maintainer
  - Env:
    - Key: RETHINKDB_PACKAGE_VERSION
      Value: 2.2.4
    Name: env
  - CmdLine:
    - "apt-key adv --keyserver pgp.mit.edu --recv-keys 1614552E5765227AEC39EFCFA7E00EF33A8F2399
      &&     echo \"deb http://download.rethinkdb.com/apt jessie main\" > /etc/apt/sources.list.d/rethinkdb.list
      &&     apt-get update && \t  apt-get install -y rethinkdb=$RETHINKDB_PACKAGE_VERSION*
      &&     apt-get install -y --no-install-recommends bind9-host &&     rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.sh
    - /entrypoint.sh
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - Name: expose
    Ports:
    - "28015"
    - "29015"
    - "8080"
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --bind
    - all
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
