MetaArgs: null
Stages:
- BaseName: node:lts-slim
  Commands:
  - CmdLine:
    - yarn global add firebase-tools@latest firebase-bolt firebase-functions@latest
      firebase@latest firebase-admin@latest
    Name: run
    PrependShell: true
  From:
    Image: node:lts-slim
  Name: ""
  Platform: ""
  SourceCode: FROM node:lts-slim
