MetaArgs: null
Stages:
- BaseName: minidocks/base:3.7
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Martin Hasoň <martin.hason@gmail.com>"'
    Name: label
  - CmdLine:
    - addgroup -S mysql && adduser -S -G mysql mysql
    Name: run
    PrependShell: true
  - CmdLine:
    - apk --update add tzdata pwgen 'mariadb<10.2' 'mariadb-client<10.2'    && rm
      -rf /var/cache/apk/* /tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/my.cnf     && echo -e "skip-host-cache\nskip-name-resolve"
      | awk '{ print } $1 == "[mysqld]" && c == 0 { c = 1; system("cat") }' /etc/mysql/my.cnf
      > /tmp/my.cnf     && mv /tmp/my.cnf /etc/mysql/my.cnf
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /run/mysqld && chown -R mysql /run/mysqld
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /docker-entrypoint-initdb.d
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rootfs
    - /
  - Name: expose
    Ports:
    - "3306"
  - CmdLine:
    - mysqld
    Name: cmd
    PrependShell: false
  From:
    Image: minidocks/base:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM minidocks/base:3.7
