MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Avi Kivity <avi@cloudius-systems.com>
    Name: maintainer
  - CmdLine:
    - curl http://downloads.scylladb.com/rpm/unstable/centos/master/latest/scylla.repo
      -o /etc/yum.repos.d/scylla.repo
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install epel-release
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y clean expire-cache
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y remove boost-thread boost-system
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install scylla hostname
    Name: run
    PrependShell: true
  - CmdLine:
    - yum clean all
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start-scylla
    - /start-scylla
  - CmdLine:
    - chown scylla /start-scylla
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - bashrc
    - /var/lib/scylla/.bashrc
  - CmdLine:
    - chown scylla /var/lib/scylla/.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R scylla:scylla /etc/scylla
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R scylla:scylla /etc/scylla.d
    Name: run
    PrependShell: true
  - Name: user
    User: scylla
  - Name: expose
    Ports:
    - "10000"
    - "7000"
    - "7001"
    - "9042"
    - "9160"
  - Name: volume
    Volumes:
    - /var/lib/scylla
  - CmdLine:
    - /start-scylla && /bin/bash
    Name: cmd
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
