MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - Maintainer: alexander@hotwirestudios.com
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: HOME
      Value: /root
    Name: env
  - Name: workdir
    Path: /root
  - CmdLine:
    - apt-get -qq update && apt-get -qqy install build-essential curl zlib1g-dev libgmp3-dev
      libedit2
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -OL https://downloads.haskell.org/~ghc/7.10.1/ghc-7.10.1-x86_64-unknown-linux-deb7.tar.bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xjf ghc-7.10.1-x86_64-unknown-linux-deb7.tar.bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ghc-7.10.1 && ./configure
    Name: run
    PrependShell: true
  - CmdLine:
    - cd ghc-7.10.1 && make install
    Name: run
    PrependShell: true
  - CmdLine:
    - ghc --version
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -OL http://hackage.haskell.org/package/cabal-install-1.22.4.0/cabal-install-1.22.4.0.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xzf cabal-install-1.22.4.0.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - (cd cabal-install-1.22.4.0 && ./bootstrap.sh)
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /root/.cabal/bin:$PATH
    Name: env
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - CmdLine:
    - rm -fr ghc-7.10.1-x86_64-unknown-linux-deb7.tar.bz2 ghc-7.10.1
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -fr cabal-install-1.22.4.0*
    Name: run
    PrependShell: true
  - Env:
    - Key: __cabal_update_timestamp
      Value: "201507101523"
    Name: env
  - CmdLine:
    - cabal update
    Name: run
    PrependShell: true
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
