MetaArgs: null
Stages:
- BaseName: alpine
  Commands:
  - Maintainer: Andrey Aleksandrov <alex.demion@gmail.com>
    Name: maintainer
  - Env:
    - Key: PORTUS_VERSION
      Value: '"v2.3"'
    - Key: NOKOGIRI_USE_SYSTEM_LIBRARIES
      Value: '"1"'
    - Key: CATALOG_CRON
      Value: '"5.minutes"'
    - Key: COMPOSE
      Value: "1"
    Name: env
  - CmdLine:
    - 'apk --no-cache add --update -t deps         git gcc make musl-dev libxml2-dev
      libxslt-dev         mariadb-dev libressl-dev libffi-dev     && apk --no-cache
      add         bash ruby-bundler ruby-dev nodejs tzdata libxslt mariadb-libs         mariadb-client
      openssl ruby-io-console ruby-bigdecimal         mariadb-client-libs curl-dev     &&
      echo ''gem: --verbose --no-document'' > /etc/gemrc     && cd /tmp     && git
      clone https://github.com/SUSE/Portus.git .     && git checkout ${PORTUS_VERSION}     &&
      mkdir /portus     && git archive ${PORTUS_VERSION} | tar -xC /portus     &&
      git rev-parse --short HEAD > /portus/VERSION     && cd /portus     && sed -i
      ''s/mysql2 (0.3.18)/mysql2 (0.4.4)/'' Gemfile.lock     && bundle install --retry=3     &&
      apk del --purge deps; rm -rf /tmp/* /var/cache/apk/*'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - rootfs
    - /
  - Name: workdir
    Path: /portus
  - Name: expose
    Ports:
    - "443"
  - CmdLine:
    - /init
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine
  Name: ""
  Platform: ""
  SourceCode: FROM alpine
