MetaArgs: null
Stages:
- BaseName: centos:centos7
  Commands:
  - Labels:
    - Key: maintainer
      Value: byron@supersmurf.com
    Name: label
  - CmdLine:
    - yum clean all &&     yum -y install epel-release &&     yum -y install PyYAML
      python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools
      git python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /etc/ansible
    Name: run
    PrependShell: true
  - CmdLine:
    - echo -e '[local]\nlocalhost\n' > /etc/ansible/hosts
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /opt/ansible
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install ansible==2.4.3.0
    Name: run
    PrependShell: true
  From:
    Image: centos:centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7
