MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: Antonio Aloisio <gnuton@gnuton.org>
    Name: maintainer
  - Maintainer: Thomas Perl <m@thp.io>
    Name: maintainer
  - Env:
    - Key: VITASDK
      Value: /usr/local/vitasdk
    Name: env
  - Env:
    - Key: PATH
      Value: ${PATH}:${VITASDK}/bin
    Name: env
  - Name: workdir
    Path: /build
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive &&     echo "Installing dependencies..." &&     apt-get
      update &&     apt-get install -y sudo wget curl make git-core xz-utils python
      apt-transport-https ca-certificates gnupg software-properties-common wget &&     echo
      "Installing Latest CMake Version..." &&     wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc
      2>/dev/null | sudo apt-key add - &&     apt-add-repository 'deb https://apt.kitware.com/ubuntu/
      bionic main' &&     apt-get update &&     apt-get install -y cmake &&     echo
      "Adding non-root user..." &&     useradd -ms /bin/bash user &&     echo "user:user"
      | chpasswd && adduser user sudo
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/vitasdk/vdpm &&     cd vdpm &&     ./bootstrap-vitasdk.sh
      &&     ./install-all.sh
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
