MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Labels:
    - Key: image-name
      Value: = robot_test_img
    Name: label
  - CmdLine:
    - "apt update -y && \tapt-get install wget python3-pip unzip xvfb -y && \techo
      \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main\" >> /etc/apt/sources.list.d/google-chrome.list
      && \twget https://dl.google.com/linux/linux_signing_key.pub && \tapt-key add
      linux_signing_key.pub && \tapt update -y && \tapt-get install google-chrome-stable
      -y && \tpip3 install robotframework robotframework-seleniumlibrary robotframework-xvfb
      xvfbwrapper robotframework-pabot robotframework-requests && \twget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
      && \tunzip chromedriver_linux64 && mv chromedriver /usr/bin && \trm chromedriver_linux64.zip"
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
