MetaArgs: null
Stages:
- BaseName: eggdrop:latest
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"Odd E. Ebbesen <oddebb@gmail.com>"'
    Name: label
  - CmdLine:
    - "apk add --no-cache tini shadow && \t\trm -rf /var/cache/apk/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - usermod -u 1000 eggdrop
    Name: run
    PrependShell: true
  - CmdLine:
    - tini
    - -g
    - --
    - /home/eggdrop/eggdrop/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - eggdrop.conf
    Name: cmd
    PrependShell: false
  From:
    Image: eggdrop:latest
  Name: ""
  Platform: ""
  SourceCode: FROM eggdrop:latest
