MetaArgs: null
Stages:
- BaseName: java:7-jdk
  Commands:
  - Maintainer: Patrick Davis <patrick_davis@cable.comcast.com>
    Name: maintainer
  - Env:
    - Key: ACTIVEMQ_VERSION
      Value: 5.8.0
    Name: env
  - Env:
    - Key: ACTIVEMQ
      Value: apache-activemq-$ACTIVEMQ_VERSION
    Name: env
  - Env:
    - Key: ACTIVEMQ_ROOT
      Value: '"/usr/local"'
    Name: env
  - Env:
    - Key: ACTIVEMQ_HOME
      Value: '"$ACTIVEMQ_ROOT/$ACTIVEMQ"'
    Name: env
  - Env:
    - Key: ACTIVEMQ_CONF
      Value: '"$ACTIVEMQ_HOME/conf"'
    Name: env
  - Env:
    - Key: PATH
      Value: $ACTIVEMQ_HOME/bin:$PATH
    Name: env
  - CmdLine:
    - mkdir -p "$ACTIVEMQ_HOME"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $ACTIVEMQ_HOME
  - CmdLine:
    - "curl -O http://archive.apache.org/dist/activemq/apache-activemq/$ACTIVEMQ_VERSION/$ACTIVEMQ-bin.tar.gz
      \t&& tar -xzmf $ACTIVEMQ-bin.tar.gz -C $ACTIVEMQ_ROOT     && rm -f $ACTIVEMQ-bin.tar.gz"
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "61612"
    - "61613"
    - "61616"
    - "8161"
  - CmdLine:
    - $ACTIVEMQ_HOME/bin/activemq console
    Name: cmd
    PrependShell: true
  From:
    Image: java:7-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM java:7-jdk
