MetaArgs: null
Stages:
- BaseName: alpine:3.8
  Commands:
  - Maintainer: Yonh Lai <azssjli@163.com>
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"A Simple apache/php image using alpine Linux for Web Apps"'
    Name: label
  - CmdLine:
    - "apk --update add apache2 php7-apache2 curl \tphp7-pdo_mysql php7-mysqli php7-curl
      php7-dom php7-xml php7-json php7-ctype php7-mbstring php7-session php7-iconv
      php7-zlib php7-mcrypt \tphp7-bcmath php7-gd php7-openssl php7-zip php7-ftp php7-sqlite3
      php7-tokenizer php7-simplexml php7-fileinfo php7-redis     && rm -f /var/cache/apk/*
      \    && mkdir /run/apache2     && sed -i 's/#LoadModule\\ rewrite_module/LoadModule\\
      rewrite_module/' /etc/apache2/httpd.conf     && mkdir -p /opt/utils     && sed
      -i 's/upload_max_filesize = 2M/upload_max_filesize = 10M/g' /etc/php7/php.ini"
    Name: run
    PrependShell: true
  - Env:
    - Key: LD_PRELOAD
      Value: /usr/lib/preloadable_libiconv.so php
    Name: env
  - CmdLine:
    - apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing
      gnu-libiconv
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start.sh
    - /opt/utils/
  - CmdLine:
    - chmod +x /opt/utils/start.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - deluser apache && addgroup apache && adduser -S apache -G apache -u 1000
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /app
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /opt/utils/start.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.8
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.8
