MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: John Downey <jdowney@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y   build-essential   ca-certificates   curl   file   sudo   --no-install-recommends   &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y -v
    Name: run
    PrependShell: true
  - CmdLine:
    - /root/.cargo/bin/rustup target add x86_64-unknown-linux-musl
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: '"/root/.cargo/bin:${PATH}"'
    Name: env
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
