MetaArgs: null
Stages:
- BaseName: golang:1.4-wheezy
  Commands:
  - CmdLine:
    - apt-get update  && apt-get install -y libgeoip-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /usr/share/GeoIP  && rm -f *  && wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz  &&
      wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz  &&
      wget http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz  &&
      gzip -d GeoIP.dat.gz  && gzip -d GeoLiteCity.dat.gz  && gzip -d GeoIPASNum.dat.gz  &&
      mv GeoLiteCity.dat GeoIPCity.dat
    Name: run
    PrependShell: true
  - CmdLine:
    - go get github.com/abh/geodns  && cd $GOPATH/src/github.com/abh/geodns  && go
      get -t  && go test  && go build
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /dns
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $GOPATH/src/github.com/abh/geodns
  - CmdLine:
    - ./geodns -config="/dns"
    Name: cmd
    PrependShell: true
  From:
    Image: golang:1.4-wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM golang:1.4-wheezy
