MetaArgs: null
Stages:
- BaseName: alpine:3.5
  Commands:
  - Labels:
    - Key: github
      Value: '"https://github.com/mrorgues"'
    Name: label
  - CmdLine:
    - apk update &&     apk upgrade &&     apk add         ca-certificates         firefox-esr         libcanberra-gtk2
      &&     rm -rf /tmp/* /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/firefox
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.5
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.5
