MetaArgs: null
Stages:
- BaseName: emby/embyserver:latest
  Commands:
  - CmdLine:
    - echo $'\n\x23 Ensure the ssl group exists with the same GID as on the host\nif
      ! getent group 1001 > /dev/null; then\n  groupadd -f -g 1001 ssl\nfi\n\n\x23
      Ensure the emby user is in the ssl group\nif ! (id -Gn emby | grep "\\bssl\\b")
      then\n  usermod -a -G ssl emby\nfi\n'>> /etc/cont-init.d/02-user-onetime
    Name: run
    PrependShell: true
  From:
    Image: emby/embyserver:latest
  Name: ""
  Platform: ""
  SourceCode: FROM emby/embyserver:latest
