MetaArgs: null
Stages:
- BaseName: nginx:alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /usr/share/nginx/html/
  - Health:
      Interval: 5000000000
      Retries: 3
      Test:
      - CMD-SHELL
      - wget http://localhost:80/ -q -O - > /dev/null 2>&1
      Timeout: 5000000000
    Name: healthcheck
  From:
    Image: nginx:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM nginx:alpine
