MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - CmdLine:
    - yum -y update &&     yum -y install        ca-certificates        curl        gcc        glibc-devel
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /rust
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /rust
  - CmdLine:
    - sh -c "curl https://sh.rustup.rs -sSf | sh -s -- -y"
    Name: run
    PrependShell: true
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
