MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Maintainer: AFMensah, LLC
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y -q openjdk-7-jre-headless
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -k -L -o amp-realtime-data-1.2.7.zip -unimbleus:8540ad9b559fb5ae28775a4c0831751c0ef004bf
      'https://dl.bintray.com/nimbleus/afmensah/amp-realtime-data-1.2.7.zip'
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - CmdLine:
    - mv amp-realtime-data-1.2.7.zip /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - unzip amp-realtime-data-1.2.7.zip
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app/amp-realtime-data-1.2.7/bin
  - CmdLine:
    - chmod +x /app/amp-realtime-data-1.2.7/bin/amp-realtime-data
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - /app/amp-realtime-data-1.2.7/bin/amp-realtime-data
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:14.04
