MetaArgs: null
Stages:
- BaseName: ubuntu:13.10
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get -y install apache2
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - service
    - /etc/minipaas
  - Chown: ""
    Name: add
    SourcesAndDest:
    - code
    - /var/www
  - Env:
    - Key: minipaas_version
      Value: "1"
    Name: env
  - Env:
    - Key: APACHE_RUN_USER
      Value: www-data
    Name: env
  - Env:
    - Key: APACHE_RUN_GROUP
      Value: www-data
    Name: env
  - Env:
    - Key: APACHE_LOG_DIR
      Value: /var/log/apache2
    Name: env
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /usr/sbin/apache2ctl
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -D
    - FOREGROUND
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:13.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:13.10
