MetaArgs: null
Stages:
- BaseName: traefik
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - traefik.toml
    - /etc/traefik/
  From:
    Image: traefik
  Name: ""
  Platform: ""
  SourceCode: FROM traefik
