MetaArgs: null
Stages:
- BaseName: node:8.9.3
  Commands:
  - Name: workdir
    Path: /app
  - CmdLine:
    - npm
    - run
    - dev
    Name: cmd
    PrependShell: false
  From:
    Image: node:8.9.3
  Name: ""
  Platform: ""
  SourceCode: FROM node:8.9.3
