MetaArgs: null
Stages:
- BaseName: spartan/ruby:latest
  Commands:
  - Maintainer: Colin Rymer <colin.rymer@gmail.com>
    Name: maintainer
  - Env:
    - Key: GEM_HOME
      Value: /usr/local/bundle
    Name: env
  - Env:
    - Key: PATH
      Value: $GEM_HOME/bin:$PATH
    Name: env
  - Env:
    - Key: BUNDLE_APP_CONFIG
      Value: $GEM_HOME
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - Gemfile*
    - /tmp/
  - CmdLine:
    - cd /tmp && bundle install && rm Gemfile*
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install foreman
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app/
  - Name: expose
    Ports:
    - "5000"
  - Expression: ADD .ruby-version /app/.ruby-version
    Name: onbuild
  - Expression: ADD Gemfile* /app/
    Name: onbuild
  - Expression: RUN BUNDLE_JOBS=$(cat /proc/cpuinfo | grep cores | cut -d':' -f2 |
      head -n1 | xargs expr -1 +) bundle install
    Name: onbuild
  - Expression: ADD . /app/
    Name: onbuild
  - Expression: CMD ["foreman", "start", "web"]
    Name: onbuild
  From:
    Image: spartan/ruby:latest
  Name: ""
  Platform: ""
  SourceCode: FROM spartan/ruby:latest
