MetaArgs: null
Stages:
- BaseName: rabbitmq:3.6.15-management-alpine
  Commands:
  - CmdLine:
    - apk --update add --no-cache curl wget ca-certificates
    Name: run
    PrependShell: true
  - Env:
    - Key: CONSUL_TEMPLATE_VERSION
      Value: 0.18.1
    Name: env
  - Env:
    - Key: CONSUL_TEMPLATE_SHA256
      Value: 72eb9ee8d06f5f02daf4ab5402fdeb466c1f714021a66f28b6e8ec9ff074b7d5
    Name: env
  - CmdLine:
    - wget -q -O /tmp/consul-template.tgz https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.tgz     &&
      echo `sha256sum /tmp/consul-template.tgz`     && echo "${CONSUL_TEMPLATE_SHA256}
      /tmp/consul-template.tgz"     && echo "${CONSUL_TEMPLATE_SHA256}  /tmp/consul-template.tgz"
      | sha256sum -c -     && tar zxf /tmp/consul-template.tgz -C /usr/local/bin     &&
      chmod +x /usr/local/bin/consul-template     && rm /tmp/consul-template.tgz
    Name: run
    PrependShell: true
  - Env:
    - Key: PLUGIN_BASE
      Value: v3.6.x
    Name: env
  - Env:
    - Key: AUTOCLUSTER_VERSION
      Value: 0.10.0
    Name: env
  - Env:
    - Key: DELAYED_MESSAGE_VERSION
      Value: 0.0.1
    Name: env
  - CmdLine:
    - wget -q -O /plugins/rabbitmq_delayed_message_exchange-${DELAYED_MESSAGE_VERSION}.ez  http://www.rabbitmq.com/community-plugins/${PLUGIN_BASE}/rabbitmq_delayed_message_exchange-${DELAYED_MESSAGE_VERSION}.ez
      &&   wget -q -O /plugins/autocluster-${AUTOCLUSTER_VERSION}.ez https://github.com/rabbitmq/rabbitmq-autocluster/releases/download/${AUTOCLUSTER_VERSION}/autocluster-${AUTOCLUSTER_VERSION}.ez
      &&   wget -q -O /plugins/rabbitmq_aws-${AUTOCLUSTER_VERSION}.ez https://github.com/rabbitmq/rabbitmq-autocluster/releases/download/${AUTOCLUSTER_VERSION}/rabbitmq_aws-${AUTOCLUSTER_VERSION}.ez
    Name: run
    PrependShell: true
  - CmdLine:
    - rabbitmq-plugins enable --offline         autocluster         rabbitmq_delayed_message_exchange         rabbitmq_top
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /srv/consul
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - consul-wrapper.sh
    - /consul-wrapper.sh
  - CmdLine:
    - /consul-wrapper.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - rabbitmq-server
    Name: cmd
    PrependShell: false
  From:
    Image: rabbitmq:3.6.15-management-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM rabbitmq:3.6.15-management-alpine
