MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Gareth Rushgrove "gareth@puppet.com"
    Name: maintainer
  - Env:
    - Key: PUPPET_AGENT_VERSION
      Value: '"1.5.2"'
    - Key: UBUNTU_CODENAME
      Value: '"xenial"'
    Name: env
  - Labels:
    - Key: com.puppet.version
      Value: $PUPPET_AGENT_VERSION
    - Key: com.puppet.git.repo
      Value: '"https://github.com/puppetlabs/dockerfiles"'
    - Key: com.puppet.git.sha
      Value: '"4afbb13eea650fce8301b2d181687f806700fc2f"'
    - Key: com.puppet.buildtime
      Value: '"2016-06-15T08:48:20Z"'
    - Key: com.puppet.dockerfile
      Value: '"/Dockerfile"'
    Name: label
  - CmdLine:
    - apt-get update &&     apt-get install -y wget=1.17.1-1ubuntu1 &&     wget https://apt.puppetlabs.com/puppetlabs-release-pc1-"$UBUNTU_CODENAME".deb
      &&     dpkg -i puppetlabs-release-pc1-"$UBUNTU_CODENAME".deb &&     apt-get
      update &&     apt-get install --no-install-recommends -y puppet-agent="$PUPPET_AGENT_VERSION"-1"$UBUNTU_CODENAME"
      &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH
    Name: env
  - CmdLine:
    - /opt/puppetlabs/bin/puppet
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - agent
    - --verbose
    - --onetime
    - --no-daemonize
    - --summarize
    - --server
    - puppet
    Name: cmd
    PrependShell: false
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Dockerfile
    - /
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
