MetaArgs: null
Stages:
- BaseName: ubuntu:14.04
  Commands:
  - Name: workdir
    Path: /source
  - Name: volume
    Volumes:
    - /source
  - Chown: ""
    Name: add
    SourcesAndDest:
    - build
    - /usr/local/bin/build
  - CmdLine:
    - /usr/local/bin/build
    Name: cmd
    PrependShell: false
  - CmdLine:
    - echo debconf debconf/frontend select Noninteractive | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - echo APT::Install-Recommends \"0\"\; > /etc/apt/apt.conf.d/01norecommend
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg --add-architecture i386
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update &&   apt-get install -y     build-essential     curl     git     g++-multilib     zlib1g:i386     libxml2-utils     squashfs-tools     dosfstools     mtools     python     bison     zip     unzip     bc     gperf     gettext     genisoimage     syslinux     python-mako
      &&   rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:14.04
  Name: ""
  Platform: ""
  SourceCode: from ubuntu:14.04
