MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Anatoly Litovsky <anatolylit@gmail.com>
    Name: maintainer
  - Maintainer: Anna Litovsky <anna.makhlina@mail.huji.ac.il>
    Name: maintainer
  - Env:
    - Key: container
      Value: docker
    Name: env
  - CmdLine:
    - apt-get clean && apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python python-pip unzip wget
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install numpy
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install QIIME
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - SilvaDb/Silva_123_release.zip
    - /root/Silva_123_release.zip
  - CmdLine:
    - cd root && unzip /root/Silva_123_release.zip && rm /root/Silva_123_release.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - SilvaDb/Silva.gold.bacteria.zip
    - /root/Silva.gold.bacteria.zip
  - CmdLine:
    - cd root && unzip /root/Silva.gold.bacteria.zip && rm /root/Silva.gold.bacteria.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Mothur.linux_64.zip
    - /root/Mothur.linux_64.zip
  - CmdLine:
    - cd root && unzip /root/Mothur.linux_64.zip && rm /root/Mothur.linux_64.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - SilvaDb/silva_lanemask_mothur.txt
    - /root/silva_lanemask_mothur.txt
  - CmdLine:
    - apt-get install -y python-tk
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
