MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y gcc make libssl-dev
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://www.gcd.org/sengoku/stone/stone-2.3e.tar.gz
    - stone.tar.gz
  - CmdLine:
    - tar zxf stone.tar.gz &&   cd stone-*/ &&   FLAGS=-D_GNU_SOURCE make linux-ssl
      &&   cp -a stone /usr/bin/stone
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - stone.pem
    - /usr/lib/ssl/certs/stone.pem
  - CmdLine:
    - /usr/bin/stone
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: from debian:latest
