MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Alexey Nurgaliev <atnurgaliev@gmail.com>
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - setup.sh
    - /usr/local/firebird_setup.sh
  - CmdLine:
    - apt-get update &&    apt-get upgrade -y &&    apt-get install -y libncurses5-dev
      bzip2 curl gcc g++ make &&    mkdir -p /tmp/firebird &&    cd /tmp/firebird
      &&    curl -L -o firebird.tar.bz2         "http://sourceforge.net/projects/firebird/files/firebird/2.5.6-Release/Firebird-2.5.6.27020-0.tar.bz2"
      &&    tar --strip=1 -xf firebird.tar.bz2 &&    ./configure --enable-superserver
      --prefix=/usr/local/firebird &&    make &&    make silent_install &&    cd /
      &&    rm -R /tmp/firebird &&    bash /usr/local/firebird_setup.sh &&    rm /usr/local/firebird_setup.sh
      &&    apt-get purge -y --auto-remove libncurses5-dev bzip2 curl gcc g++ make
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /sqlbase
  - Name: expose
    Ports:
    - "3050"
  - CmdLine:
    - /usr/local/firebird/bin/fbguard
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
