MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Env:
    - Key: HAPROXY_VERSION
      Value: 1.5.14
    Name: env
  - CmdLine:
    - set -x &&   apt-get update && apt-get install -y inotify-tools wget tar gzip
      make gcc libc6-dev libpcre3-dev libssl-dev &&   wget -O /tmp/haproxy.tgz http://www.haproxy.org/download/1.5/src/haproxy-${HAPROXY_VERSION}.tar.gz
      &&   mkdir -p /usr/local/haproxy &&   tar -zxvf /tmp/haproxy.tgz -C /usr/local/haproxy/
      --strip-components 1 &&   rm -f /tmp/haproxy.tgz &&   cd /usr/local/haproxy
      &&   make   USE_LINUX_TPROXY=1 USE_ZLIB=1   USE_REGPARM=1   USE_OPENSSL=1   USE_PCRE=1   TARGET=linux2628   CFLAGS="-O2
      -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18" &&   make install &&   apt-get
      clean all &&   rm -rf /usr/local/haproxy &&   mkdir -p /var/lib/haproxy &&   chown
      -R 777 /var/lib/haproxy
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - container-files
    - /
  - Env:
    - Key: HAPROXY_CONFIG
      Value: /etc/haproxy/haproxy.cfg
    Name: env
  - CmdLine:
    - chmod +x /*.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "1936"
    - "443"
    - "80"
  - CmdLine:
    - ./bootstrap.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
