MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - mkdir -p /app
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /app
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - chmod +x /app/*.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /app/*
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
