MetaArgs: null
Stages:
- BaseName: jbioi/alpine-java
  Commands:
  - Maintainer: kongdeju kongdeju@gene.ac
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - picard.tar.gz
    - /tmp
  - CmdLine:
    - mv /tmp/picard/*.jar /opt      && rm -rf /tmp/*
    Name: run
    PrependShell: true
  From:
    Image: jbioi/alpine-java
  Name: ""
  Platform: ""
  SourceCode: FROM jbioi/alpine-java
