MetaArgs: null
Stages:
- BaseName: php:7.2-cli
  Commands:
  - Maintainer: Dieter Provoost <dieter.provoost@marlon.be>
    Name: maintainer
  - CmdLine:
    - mkdir -p /usr/share/man/man1
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y     openjdk-8-jdk     git     unzip     ant     sqlite3     curl     zlib1g-dev     libicu-dev     libpng-dev     libjpeg62-turbo-dev     libfreetype6-dev     libxml2-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /etc/localtime
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
    Name: run
    PrependShell: true
  - CmdLine:
    - '"date"'
    Name: run
    PrependShell: true
  - CmdLine:
    - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      &&     docker-php-ext-install pdo pdo_mysql zip bcmath intl gd pcntl soap xml
      xmlrpc sockets
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get autoremove -y
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - developer.ini
    - /usr/local/etc/php/conf.d/developer.ini
  From:
    Image: php:7.2-cli
  Name: ""
  Platform: ""
  SourceCode: FROM php:7.2-cli
