MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - apt-get update -q && apt-get install -qy python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install elasticsearch-curator==5.6.0
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/curator
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
