MetaArgs: null
Stages:
- BaseName: jenkinsci/jenkins:latest
  Commands:
  - Name: user
    User: root
  - CmdLine:
    - apt update
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -fsSL get.docker.com | bash && usermod -aG docker jenkins
    Name: run
    PrependShell: true
  From:
    Image: jenkinsci/jenkins:latest
  Name: ""
  Platform: ""
  SourceCode: FROM jenkinsci/jenkins:latest
