MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Luke Cousins
    Name: maintainer
  - CmdLine:
    - export LC_ALL=C.UTF-8
    Name: run
    PrependShell: true
  - CmdLine:
    - DEBIAN_FRONTEND=noninteractive
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /bin/sh && ln -s /bin/bash /bin/sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y     autoconf     autogen     language-pack-en-base     wget     curl     ssh     rsync     ssh     openssh-client     git     build-essential     apt-utils     software-properties-common     python-software-properties     nasm     libjpeg-dev     libpng-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb   &&
      dpkg -i /tmp/libpng12.deb   && rm /tmp/libpng12.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update ; apt-get install -y --allow-unauthenticated     php7.1     php7.1-curl     php7.1-gd     php7.1-dev     php7.1-xml     php7.1-bcmath     php7.1-mysql     php7.1-mbstring     php7.1-zip     php7.1-sqlite     php7.1-soap     php7.1-json     php7.1-intl     php-xdebug     php-apcu
    Name: run
    PrependShell: true
  - CmdLine:
    - command -v php
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "apc.enable_cli=1" | tee -a /etc/php/7.1/mods-available/apcu.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&     php
      -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410')
      { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php');
      } echo PHP_EOL;" &&     php composer-setup.php &&     php -r "unlink('composer-setup.php');"
      &&     mv composer.phar /usr/local/bin/composer &&     chmod +x /usr/local/bin/composer
      &&     composer self-update --preview
    Name: run
    PrependShell: true
  - CmdLine:
    - command -v composer
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://phar.phpunit.de/phpunit.phar
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x phpunit.phar
    Name: run
    PrependShell: true
  - CmdLine:
    - mv phpunit.phar /usr/local/bin/phpunit
    Name: run
    PrependShell: true
  - CmdLine:
    - command -v phpunit
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - bash nodesource_setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install nodejs -y
    Name: run
    PrependShell: true
  - CmdLine:
    - command -v node
    Name: run
    PrependShell: true
  - CmdLine:
    - command -v npm
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir ~/.ssh
    Name: run
    PrependShell: true
  - CmdLine:
    - touch ~/.ssh_config
    Name: run
    PrependShell: true
  - CmdLine:
    - php -v
    Name: run
    PrependShell: true
  - CmdLine:
    - composer --version
    Name: run
    PrependShell: true
  - CmdLine:
    - phpunit --version
    Name: run
    PrependShell: true
  - CmdLine:
    - node -v
    Name: run
    PrependShell: true
  - CmdLine:
    - npm -v
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
