MetaArgs: null
Stages:
- BaseName: whatwedo/base:latest
  Commands:
  - CmdLine:
    - apt-get update -y && apt-get install -y ruby ruby-dev bundler && apt-get autoremove
      -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Labels:
    - Key: ch.whatwedo.image.base
      Value: '"whatwedo/ruby"'
    Name: label
  From:
    Image: whatwedo/base:latest
  Name: ""
  Platform: ""
  SourceCode: FROM whatwedo/base:latest
