MetaArgs: null
Stages:
- BaseName: phusion/baseimage:0.11
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /bug-yield/
  - CmdLine:
    - install_clean php-cli php-curl php-xml php-mbstring git unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sS https://getcomposer.org/installer | php &&     mv composer.phar /usr/local/bin/composer
      &&     cd /bug-yield && composer install &&     crontab /bug-yield/docker/crontab
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /bug-yield
  From:
    Image: phusion/baseimage:0.11
  Name: ""
  Platform: ""
  SourceCode: FROM phusion/baseimage:0.11
