MetaArgs: null
Stages:
- BaseName: mhart/alpine-node
  Commands:
  - Maintainer: to-increase <to-increase.io>
    Name: maintainer
  - CmdLine:
    - apk update &&   apk add wget tar &&   wget -q --no-check-certificate -O /tmp/consul.tar.gz
      https://github.com/hashicorp/envconsul/releases/download/v0.5.0/envconsul_0.5.0_linux_amd64.tar.gz
      &&   tar -xzvf /tmp/consul.tar.gz -C /usr/bin/ --strip-components=1 &&   apk
      del wget tar &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* *.gz
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - envconsul-config.hcl
    - /etc/envconsul-config.hcl
  - Chown: ""
    Name: add
    SourcesAndDest:
    - envconsul-launch
    - /usr/bin/envconsul-launch
  - CmdLine:
    - chmod +x /usr/bin/envconsul-launch
    Name: run
    PrependShell: true
  - CmdLine:
    - envconsul-launch
    Name: entrypoint
    PrependShell: false
  From:
    Image: mhart/alpine-node
  Name: ""
  Platform: ""
  SourceCode: FROM mhart/alpine-node
