MetaArgs: null
Stages:
- BaseName: postgres:9.6
  Commands:
  - Labels:
    - Key: maintainer
      Value: Svilen Sabev <svilensabev@gmail.com>
    Name: label
  - CmdLine:
    - apt-get update &&     apt-get install -y libpq-dev git make pkg-config clang
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/begriffs/pg_listen.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /pg_listen
  - CmdLine:
    - make
    Name: run
    PrependShell: true
  - Key: POSTGRES_DB_URI
    Name: arg
    Value: null
  - Env:
    - Key: POSTGRES_DB_URI
      Value: '"$POSTGRES_DB_URI"'
    Name: env
  - CmdLine:
    - ./pg_listen ${POSTGRES_DB_URI} ddl_command_end "kill -HUP `pgrep postgrest`"
    Name: cmd
    PrependShell: true
  From:
    Image: postgres:9.6
  Name: ""
  Platform: ""
  SourceCode: FROM postgres:9.6
