MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Maintainer: Thomas Krieger <tom@svn-access-manager.org>
    Name: maintainer
  - Labels:
    - Key: Description
      Value: '"Docker container for SVN Access Manager on PHP7"'
    - Key: Version
      Value: '"0.5.7.0"'
    Name: label
  - Env:
    - Key: CHARSET
      Value: latin1
    Name: env
  - Env:
    - Key: COLLATION
      Value: latin1_swedish_ci
    Name: env
  - Env:
    - Key: DBHOST
      Value: localhost
    Name: env
  - Env:
    - Key: DBNAME
      Value: svnam
    Name: env
  - Env:
    - Key: DBUSER
      Value: svnam
    Name: env
  - Env:
    - Key: DBPASS
      Value: svnampass
    Name: env
  - Env:
    - Key: SVNAMVERSION
      Value: branches/svnam-0.5-install-fix
    Name: env
  - Env:
    - Key: MYSQL_ROOT_PASSWORD
      Value: rootpw
    Name: env
  - Env:
    - Key: MYSQL_DATABASE
      Value: svnam
    Name: env
  - Env:
    - Key: MYSQL_USER
      Value: svnam
    Name: env
  - Env:
    - Key: MYSQL_PASSWORD
      Value: svnampass
    Name: env
  - CmdLine:
    - yum clean all &&     yum -y update &&     yum -y install hostname
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -l -k -s http://repo.webtatic.com/yum/el7/webtatic-release.rpm -o /tmp/webtatic-release.rpm
      &&     curl -l -k -s https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      -o /tmp/epel-release-latest-7.noarch.rpm &&     yum -y localinstall /tmp/webtatic-release.rpm
      /tmp/epel-release-latest-7.noarch.rpm &&     rpm --import /etc/pki/rpm-gpg/RPM*
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install mysql unzip tar curl subversion httpd mod_dav_svn                    viewvc
      php70w php70w-cli php70w-mbstring systemd                    php70w-bcmath php70w-mcrypt
      php70w-mysql php70w-ldap python34-devel                    mariadb-server bind-utils
      pwgen psmisc vim-enhanced &&     yum clean all &&     rm -rf /var/cache/yum
      &&     mkdir -p /usr/share &&     curl -l -k -s https://bootstrap.pypa.io/get-pip.py
      | python3.4 &&     pip3 install chaperone
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/svn-access-manager.conf
    - /etc/httpd/conf.d/svn-access-manager.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/php.ini
    - /etc/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/httpd.conf
    - /etc/httpd/conf/httpd.conf
  - CmdLine:
    - cd /usr/share &&     /bin/svn checkout https://svn.code.sf.net/p/svn-access-mana/code/${SVNAMVERSION}
      svn-access-manager &&     chown -R 27:27 svn-access-manager &&     mkdir /etc/svn
      &&     mkdir /etc/svn-access-manager &&     mkdir -p /svn/repos &&     touch
      /etc/svn/viewvc-apache.conf &&     chown apache:apache /etc/svn &&     chown
      apache:apache /etc/svn-access-manager &&     cd /svn/repos &&     svnadmin create
      --fs-type fsfs test1 &&     svnadmin create --fs-type fsfs test2 &&     chown
      -R apache:apache /svn/repos &&     rm -f /tmp/svn-access-manager.tar.gz /tmp/webtatic-release.rpm
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/config.inc.php
    - /etc/svn-access-manager/config.inc.php
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/svnam-dump.sql
    - /tmp/db.dump
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/chaperone.conf
    - /etc/chaperone.d/chaperone.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/user_service.sh
    - /user_service.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/mysql-setup.sh
    - /mysql-setup.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/setup.sh
    - /setup.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/mysql-load.sh
    - /mysql-load.sh
  - CmdLine:
    - chmod 755 /user_service.sh /setup.sh /mysql-load.sh /mysql-setup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chown apache:apache /etc/svn-access-manager/config.inc.php /tmp/db.dump
    Name: run
    PrependShell: true
  - CmdLine:
    - chown mysql:mysql /tmp/db.dump
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/fix-permissions.sh
    - ./
  - CmdLine:
    - chmod 755 ./fix-permissions.sh ;     ./fix-permissions.sh /var/lib/mysql/   &&     ./fix-permissions.sh
      /var/log/mariadb/ &&     ./fix-permissions.sh /var/run/
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - files/docker-entrypoint.sh
    - /
  - CmdLine:
    - chmod 755 /docker-entrypoint.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: volume
    Volumes:
    - /var/log/httpd
    - /etc/svn-access-manager
    - /svn/repos
    - /var/lib/mysql
    - /var/log/mariadb
  - CmdLine:
    - /usr/bin/chaperone
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
