MetaArgs:
- DefaultValue: 1.14.0-gpu-py3
  Key: TENSORFLOW_VERSION
  ProvidedValue: null
  Value: 1.14.0-gpu-py3
Stages:
- BaseName: tensorflow/tensorflow:${TENSORFLOW_VERSION}
  Commands:
  - Name: workdir
    Path: /
  - CmdLine:
    - apt-get -y update && apt-get -y upgrade &&     apt-get install -y --no-install-recommends
      curl
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /galois
  - Name: workdir
    Path: /galois
  - CmdLine:
    - curl -SL https://github.com/iedmrc/galois-autocompleter/releases/latest/download/model.tar.xz     |
      tar -xJC . &&     pip --no-cache-dir install --upgrade pip &&     pip --no-cache-dir
      install -r requirements.txt &&     apt purge -y git curl &&     apt autoremove
      --purge -y &&     apt clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - python
    - main.py
    Name: cmd
    PrependShell: false
  From:
    Image: tensorflow/tensorflow:${TENSORFLOW_VERSION}
  Name: ""
  Platform: ""
  SourceCode: FROM tensorflow/tensorflow:${TENSORFLOW_VERSION}
