MetaArgs: null
Stages:
- BaseName: debian:testing-slim
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"marthym@github.com"'
    Name: label
  - CmdLine:
    - "export DEBIAN_FRONTEND=noninteractive && \tapt -y update && \tapt --no-install-recommends
      -y install \t\topenssh-client         git \t\ttexlive-base \t\ttexlive-xetex
      \t\ttexlive-latex-recommended \t\ttexlive-latex-extra \t\ttexlive-extra-utils
      \t\ttexlive-fonts-recommended \t\ttexlive-font-utils \t\ttexlive-lang-french
      \t\ttexlive-pictures \t\ttexlive-bibtex-extra \t\tlmodern biber latexmk ghostscript
      && \tapt clean && \tapt autoclean && \trm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
    Name: run
    PrependShell: true
  From:
    Image: debian:testing-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:testing-slim
