MetaArgs: null
Stages:
- BaseName: centos:7
  Commands:
  - Labels:
    - Key: name
      Value: '"YouPHPTube Server Container"'
    Name: label
  - Labels:
    - Key: description
      Value: '"A Docker Container for the YouPHPTube software project."'
    Name: label
  - Labels:
    - Key: author
      Value: '"Michael R. Bagnall <mrbagnall@icloud.com>"'
    Name: label
  - Labels:
    - Key: vendor
      Value: '"FlyingFlip Studios"'
    Name: label
  - Labels:
    - Key: version
      Value: '"1.1"'
    Name: label
  - Env:
    - Key: PATH
      Value: /usr/local/src/vendor/bin/:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    Name: env
  - Env:
    - Key: TERM
      Value: xterm
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.utf8
    Name: env
  - CmdLine:
    - yum -y update
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install epel-release &&   yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      &&   rpm -Uvh https://centos7.iuscommunity.org/ius-release.rpm &&   rpm --import
      http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro &&   rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
      &&   yum -y update &&   yum -y install yum-utils &&   curl -sL https://rpm.nodesource.com/setup_10.x
      | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y groupinstall "Development Tools" &&   yum -y install   git   mariadb   wget   which   gd-devel.x86_64   perl-App-cpanminus.noarch   cronie.x86_64   mod_ssl.x86_64   gettext   docker   bzip2   gcc   gcc-c++   make   nodejs   logrotate   webalizer   ffmpeg   ffmpeg-devel   perl-Image-ExifTool
    Name: run
    PrependShell: true
  - CmdLine:
    - yum-config-manager --enable remi-php72
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install   php   php-bcmath   php-curl   php-gd   php-imap   php-mbstring   php-mysqlnd   php-pgsql   php-odbc   php-pear   php-pecl-imagick   php-opcache   php-pecl-memcached   php-xml   php-pecl-redis   php-pecl-ssh2   php-ldap
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install php72-php-pecl-mcrypt.x86_64
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y upgrade &&     yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/www/html
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /var/www/html &&   cd /var/www/html &&   git clone https://github.com/YouPHPTube/YouPHPTube.git
      streamer &&   chown -R apache:apache /var/www/html
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/httpd/conf/httpd-auth.conf
    - /etc/httpd/conf/httpd-auth.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/httpd/conf/httpd-noauth.conf
    - /etc/httpd/conf/httpd-noauth.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/php.ini
    - /etc/php.ini
  - Chown: ""
    Name: add
    SourcesAndDest:
    - conf/run-httpd.sh
    - /run-httpd.sh
  - CmdLine:
    - chmod -v +x /run-httpd.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chown apache:apache /run-httpd.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /var/www
  - Name: expose
    Ports:
    - "443"
    - "80"
  - CmdLine:
    - /run-httpd.sh
    Name: cmd
    PrependShell: false
  From:
    Image: centos:7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:7
