MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - vst-install.sh
    - /vst-install.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - vst-install-debian.sh
    - /vst-install-debian.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - vst-install-php.sh
    - /vst-install-php.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nodejs_tpl.sh
    - /nodejs_tpl.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - templates
    - /templates
  - CmdLine:
    - /vst-install.sh
    Name: cmd
    PrependShell: false
  - Env:
    - Key: HOSTNAME
      Value: example.com
    - Key: ADMIN_EMAIL
      Value: admin@example.com
    - Key: ADMIN_PASSWORD
      Value: changeme
    Name: env
  - Name: volume
    Volumes:
    - /mysql
    - /home
    - /backup
  - Name: expose
    Ports:
    - 110:110
    - 12000-12100
    - 123:123
    - 143:143
    - "20:20"
    - "21:21"
    - "2222:22"
    - "25:25"
    - 3306:3306
    - 443:443
    - "53:53"
    - 53:53/udp
    - 5432:5432
    - "54:54"
    - 8080:8080
    - 8083:8083
    - 80:80
    - 8433:8433
    - 993:993
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
