MetaArgs: null
Stages:
- BaseName: node
  Commands:
  - Maintainer: tym
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git tmux curl wget make g++ python
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/c9/core.git /c9sdk
    Name: run
    PrependShell: true
  - CmdLine:
    - /c9sdk/scripts/install-sdk.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nginx
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /home/
  - Name: workdir
    Path: /home/
  - Name: expose
    Ports:
    - "8000"
  - Env:
    - Key: USERNAME
      Value: your_username
    Name: env
  - Env:
    - Key: PASSWORD
      Value: password
    Name: env
  - CmdLine:
    - sh
    - -c
    - node /home/c9sdk/server.js -p 8000 -l 0.0.0.0 -a $USERNAME:$PASSWORD
    Name: entrypoint
    PrependShell: false
  From:
    Image: node
  Name: ""
  Platform: ""
  SourceCode: FROM node
