MetaArgs: null
Stages:
- BaseName: owncloud
  Commands:
  - Maintainer: lilg <lilg@asiainfo.com>
    Name: maintainer
  - CmdLine:
    - mkdir /ssl-cert      && ln -s /etc/apache2/sites-available/default-ssl.conf  /etc/apache2/sites-enabled/000-default-ssl.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod ssl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - default-ssl.conf
    - /etc/apache2/sites-available/default-ssl.conf
  - Name: expose
    Ports:
    - "443"
  - CmdLine:
    - docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - apache2-foreground
    Name: cmd
    PrependShell: false
  From:
    Image: owncloud
  Name: ""
  Platform: ""
  SourceCode: FROM owncloud
