MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: Stéphane DI RAIMONDO
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y git wget build-essential openssl expat
      libssl-dev libxml-parser-perl libcam-pdf-perl &&     apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --no-check-certificate -O - http://install.perlbrew.pl | bash
    Name: run
    PrependShell: true
  - CmdLine:
    - ~/perl5/perlbrew/bin/perlbrew init
    Name: run
    PrependShell: true
  - CmdLine:
    - ~/perl5/perlbrew/bin/perlbrew --force install -n `~/perl5/perlbrew/bin/perlbrew
      available | head -1` --as webkeepass -j 3
    Name: run
    PrependShell: true
  - CmdLine:
    - ~/perl5/perlbrew/bin/perlbrew use webkeepass
    Name: run
    PrependShell: true
  - CmdLine:
    - wget --no-check-certificate -O - https://raw.github.com/miyagawa/cpanminus/master/cpanm
      > /opt/cpanm
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /opt/cpanm
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/cpanm /usr/bin/
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /srv/webkeepass
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /srv/webkeepass
    Name: run
    PrependShell: true
  - CmdLine:
    - env GIT_SSL_NO_VERIFY=true git clone https://github.com/sukria/WebKeePass.git
      /srv/webkeepass
    Name: run
    PrependShell: true
  - CmdLine:
    - cpanm Dist::Zilla
    Name: run
    PrependShell: true
  - CmdLine:
    - cpanm XML::Parser
    Name: run
    PrependShell: true
  - CmdLine:
    - cpanm Dancer2
    Name: run
    PrependShell: true
  - CmdLine:
    - cpanm Digest::SHA1
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /srv/webkeepass; dzil authordeps | cpanm -nq && dzil listdeps | cpanm -nq
    Name: run
    PrependShell: true
  - CmdLine:
    - rm /srv/webkeepass/bin/app.pl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - app.pl
    - /srv/webkeepass/bin/
  - CmdLine:
    - chmod +x /srv/webkeepass/bin/app.pl
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - production.yml
    - /srv/webkeepass/environments/
  - CmdLine:
    - rm /srv/webkeepass/lib/WebKeePass.pm
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - WebKeePass.pm
    - /srv/webkeepass/lib/
  - CmdLine:
    - mkdir /keepass
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start.sh
    - /
  - CmdLine:
    - chmod +x /start.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /keepass
  - Name: expose
    Ports:
    - "5001"
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
