MetaArgs: null
Stages:
- BaseName: opendronemap/odm:latest
  Commands:
  - Maintainer: Piero Toffanin <pt@masseranolabs.com>
    Name: maintainer
  - Name: expose
    Ports:
    - "3000"
  - Name: user
    User: root
  - CmdLine:
    - curl --silent --location https://deb.nodesource.com/setup_10.x | bash -
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y nodejs python-gdal && npm install -g nodemon &&     ln -s
      /code/SuperBuild/install/bin/entwine /usr/bin/entwine &&     ln -s /code/SuperBuild/install/bin/pdal
      /usr/bin/pdal
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /var/www
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/var/www"'
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /var/www
  - CmdLine:
    - npm install && mkdir tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/nodejs
    - /var/www/index.js
    Name: entrypoint
    PrependShell: false
  From:
    Image: opendronemap/odm:latest
  Name: ""
  Platform: ""
  SourceCode: FROM opendronemap/odm:latest
