MetaArgs: null
Stages:
- BaseName: wolnosciowiec/docker-php-app:arm7hf
  Commands:
  - Env:
    - Key: APP_ENV
      Value: '"prod"'
    - Key: DATABASE_URL
      Value: '"sqlite:///%kernel.project_dir%/var/data.db"'
    - Key: SITE_TITLE
      Value: '"Anarchist banner rotator"'
    - Key: SITE_DESCRIPTION
      Value: '"Shows always up-to-date list of anarchist pages on every of them. http://iwa-ait.org,
        http://zsp.net.pl"'
    - Key: HEADER_ALLOW_ORIGIN
      Value: '""'
    - Key: HEADER_ALLOW_CREDENTIALS
      Value: "true"
    - Key: HEADER_MAX_AGE
      Value: "3600"
    - Key: HEADER_ALLOW_METHODS
      Value: '""'
    - Key: HEADER_ALLOW_HEADERS
      Value: '""'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /var/www/html
  - CmdLine:
    - cross-build-start
    Name: run
    PrependShell: false
  - CmdLine:
    - cd /var/www/html     && chown www-data:www-data ./ -R     && su www-data -s
      /bin/bash -c "make deploy"
    Name: run
    PrependShell: true
  - CmdLine:
    - cross-build-end
    Name: run
    PrependShell: false
  From:
    Image: wolnosciowiec/docker-php-app:arm7hf
  Name: ""
  Platform: ""
  SourceCode: FROM wolnosciowiec/docker-php-app:arm7hf
