MetaArgs: null
Stages:
- BaseName: openjdk:8-jdk
  Commands:
  - CmdLine:
    - touch /usr/lib/jvm/java-8-openjdk-amd64/release
    Name: run
    PrependShell: true
  - Env:
    - Key: SCALA_VERSION
      Value: 2.10.3
    Name: env
  - CmdLine:
    - curl -fsL https://downloads.typesafe.com/scala/$SCALA_VERSION/scala-$SCALA_VERSION.tgz     |
      tar xfz - -C /usr/local --strip-components 1
    Name: run
    PrependShell: true
  - Env:
    - Key: SBT_VERSION
      Value: 0.13.15
    Name: env
  - CmdLine:
    - curl -fsL https://piccolo.link/sbt-${SBT_VERSION}.tgz |     tar xfz - -C /usr/local
      --strip-components 1
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --recursive https://github.com/omp4j/omp4j.git /omp4j
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /omp4j
  - CmdLine:
    - sbt compile &&     sbt test &&     sbt assembly &&     sbt doc
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root
  - CmdLine:
    - echo "java -jar /omp4j/target/scala-2.10/omp4j-assembly-1.3.jar" > /usr/local/bin/omp4j
      &&     chmod +x /usr/local/bin/omp4j
    Name: run
    PrependShell: true
  - CmdLine:
    - omp4j
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:8-jdk
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:8-jdk
