MetaArgs: null
Stages:
- BaseName: emorymerryman/base:0.2.3
  Commands:
  - Maintainer: Emory Merryman emory.merryman@gmail.com
    Name: maintainer
  - CmdLine:
    - apk update &&     apk upgrade &&     apk add git make bash &&     WORK_DIR=$(mktemp
      -d) &&     git -C ${WORK_DIR} init &&     git -C ${WORK_DIR} remote add origin
      https://git.zx2c4.com/password-store &&     git -C ${WORK_DIR} fetch origin
      &&     git -C ${WORK_DIR} checkout tags/1.6.5 &&     make --directory ${WORK_DIR}
      install &&     rm -rf ${WORK_DIR} &&     apk del git make
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/bin/pass
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: emorymerryman/base:0.2.3
  Name: ""
  Platform: ""
  SourceCode: FROM emorymerryman/base:0.2.3
