MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Maintainer: malaohu <tua@live.cn>
    Name: maintainer
  - CmdLine:
    - apt-get update && apt-get install -y openssh-server python python-pip python-m2crypto
      libnet1-dev libpcap0.8-dev git gcc && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "root:ramiko"|chpasswd && sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin
      yes/' /etc/ssh/sshd_config && sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone -b manyuser https://github.com/malaohu/suansuanru.git suansuanru &&
      git clone https://github.com/snooda/net-speeder.git net-speeder
    Name: run
    PrependShell: true
  - Name: workdir
    Path: net-speeder
  - CmdLine:
    - sh build.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mv net_speeder /usr/local/bin/
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /usr/local/bin/
  - CmdLine:
    - chmod +x /usr/local/bin/entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /usr/local/bin/net_speeder
    Name: run
    PrependShell: true
  - CmdLine:
    - /usr/local/bin/entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
