MetaArgs: null
Stages:
- BaseName: ssiegel/base-debian-systemd
  Commands:
  - Maintainer: Piotr Roszatycki <piotr.roszatycki@gmail.com>
    Name: maintainer
  - Env:
    - Key: container
      Value: docker
    - Key: HOME
      Value: /root
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - set -ex;     apt-get upgrade;         apt-get install         ansible         apt-utils         aptitude         bash-completion         bzip2         byobu         ca-certificates         command-not-found         curl         ckermit         debconf-utils         dnsutils         git         htop         less         libnss-myhostname         links         lsof         man-db         manpages         mc         nano         net-tools         netcat-openbsd         openssh-server         perl         ppp         psmisc         pv         slirp         strace         sudo         systemd-cron         tcpdump         telnet         wget         whiptail         vim         ;         rm
      -f /etc/ssh/*_key*;     systemctl disable ssh;         update-command-not-found;         sed
      -i 's/^account.*pam_nologin.so/# &/' /etc/pam.d/sshd;         rm -f /usr/sbin/policy-rc.d
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/systemd
    Name: entrypoint
    PrependShell: false
  From:
    Image: ssiegel/base-debian-systemd
  Name: ""
  Platform: ""
  SourceCode: FROM ssiegel/base-debian-systemd
