MetaArgs: null
Stages:
- BaseName: rabbitmq:3.7.4-management
  Commands:
  - CmdLine:
    - apt-get update     && apt-get -y install gettext-base     && apt-get clean     &&
      rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/*
    - /etc/rabbitmq/
  - CmdLine:
    - chown -R rabbitmq:rabbitmq /etc/rabbitmq
    Name: run
    PrependShell: true
  - CmdLine:
    - rabbitmq-server
    - -config
    - /etc/rabbitmq/advanced.config
    Name: cmd
    PrependShell: false
  - Name: expose
    Ports:
    - "61613"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entrypoint.coyo.sh
    - /usr/local/bin/docker-entrypoint.coyo.sh
  - Env:
    - Key: DISK_FREE_LIMIT
      Value: '"50000000"'
    Name: env
  - CmdLine:
    - /usr/local/bin/docker-entrypoint.coyo.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: rabbitmq:3.7.4-management
  Name: ""
  Platform: ""
  SourceCode: FROM rabbitmq:3.7.4-management
