MetaArgs: null
Stages:
- BaseName: alpine:3.9
  Commands:
  - CmdLine:
    - apk add --update --no-cache --verbose nfs-utils bash iproute2 &&     rm -f /sbin/halt
      /sbin/poweroff /sbin/reboot &&     mkdir -p /var/lib/nfs/rpc_pipefs &&     mkdir
      -p /var/lib/nfs/v4recovery &&     echo "rpc_pipefs    /var/lib/nfs/rpc_pipefs
      rpc_pipefs      defaults        0       0" >> /etc/fstab &&     echo "nfsd  /proc/fs/nfsd   nfsd    defaults        0       0"
      >> /etc/fstab
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - nfsd.sh
    - /usr/bin/nfsd.sh
  - Name: expose
    Ports:
    - "2049"
  - CmdLine:
    - /usr/bin/nfsd.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.9
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.9
