MetaArgs: null
Stages:
- BaseName: python:3.6.1
  Commands:
  - Maintainer: Martin Kluska <martin@kluska.cz>
    Name: maintainer
  - CmdLine:
    - pip install glue
    Name: run
    PrependShell: true
  From:
    Image: python:3.6.1
  Name: ""
  Platform: ""
  SourceCode: FROM python:3.6.1
