MetaArgs: null
Stages:
- BaseName: debian:wheezy
  Commands:
  - CmdLine:
    - mkdir /opt/etcd
    Name: run
    PrependShell: true
  - CmdLine:
    - export ETCD_VERSION=v0.5.0-alpha.3   && apt-get update && apt-get install -y
      curl --no-install-recommends ca-certificates &&   curl -L  https://github.com/coreos/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz   |
      tar -zxC /opt/etcd --strip-components=1   && apt-get remove --purge -y curl   &&
      apt-get autoremove -y   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: /opt/etcd:$PATH
    Name: env
  - CmdLine:
    - exec etcd
    Name: cmd
    PrependShell: true
  From:
    Image: debian:wheezy
  Name: ""
  Platform: ""
  SourceCode: FROM debian:wheezy
