MetaArgs: null
Stages:
- BaseName: fhub/alpine:v0.1-beta1
  Commands:
  - CmdLine:
    - apk add --no-cache alpine-sdk=1.0-r0
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /var/cache/apk/* && rm -rf /tmp/*
    Name: run
    PrependShell: true
  From:
    Image: fhub/alpine:v0.1-beta1
  Name: ""
  Platform: ""
  SourceCode: FROM fhub/alpine:v0.1-beta1
