MetaArgs: null
Stages:
- BaseName: k8s.gcr.io/pause:3.1
  Commands:
  - Maintainer: wzp
    Name: maintainer
  From:
    Image: k8s.gcr.io/pause:3.1
  Name: ""
  Platform: ""
  SourceCode: FROM k8s.gcr.io/pause:3.1
