MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: ome-devel@lists.openmicroscopy.org.uk
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update     && apt-get install less     && rm -rf /var/lib/apt/lists/*     &&
      apt-get clean
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - install.sh
    - install.sh
  - CmdLine:
    - sh ./install.sh && rm install.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd -ms /bin/bash octave
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - '*.m'
    - /home/octave/
  - CmdLine:
    - chown -R octave:octave /home/octave/
    Name: run
    PrependShell: true
  - Name: user
    User: octave
  - Name: workdir
    Path: /home/octave
  - Name: volume
    Volumes:
    - /source
  - CmdLine:
    - octave
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
