MetaArgs: null
Stages:
- BaseName: php:7-apache
  Commands:
  - Env:
    - Key: FLICKR_KEY
      Value: KEY
    Name: env
  - Env:
    - Key: FLICKR_SECRET
      Value: SECRET
    Name: env
  - CmdLine:
    - "apt-get update && apt-get install -y \t\tunzip         libfreetype6-dev         libjpeg62-turbo-dev
      \        libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/
      --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gd"
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./
    - /var/www/html/
  - Name: workdir
    Path: /var/www/html
  - CmdLine:
    - curl -o phpflickr.zip -L https://github.com/dan-coulter/phpflickr/archive/master.zip
      && unzip phpflickr.zip && rm -rf /var/www/html/includes/phpFlickr && mv phpflickr-master
      includes/phpFlickr
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R www-data /var/www/html/cache/
    Name: run
    PrependShell: true
  From:
    Image: php:7-apache
  Name: ""
  Platform: ""
  SourceCode: FROM php:7-apache
