MetaArgs: null
Stages:
- BaseName: lsiobase/alpine:3.6
  Commands:
  - Maintainer: LinuxServer.io <ironicbadger@linuxserver.io>, sparklyballs
    Name: maintainer
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VERSION
    Name: arg
    Value: null
  - Labels:
    - Key: build_version
      Value: '"Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"'
    Name: label
  - CmdLine:
    - "apk add --no-cache \tapache2 \tapache2-utils \tcurl \tsmokeping \tspeedtest-cli
      \tssmtp \tsudo \tttf-dejavu &&  echo \"abc ALL=(ALL) NOPASSWD: /usr/bin/traceroute\"
      >> /etc/sudoers.d/traceroute &&  sed -i 's#src=\"/cropper/#/src=\"cropper/#'
      /etc/smokeping/basepage.html"
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/bin/python3 /usr/bin/python
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -L -o /usr/share/perl5/vendor_perl/Smokeping/probes/speedtest.pm https://github.com/mad-ady/smokeping-speedtest/raw/master/speedtest.pm
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root/
    - /
  - Name: expose
    Ports:
    - "80"
  - Name: volume
    Volumes:
    - /config
    - /data
  From:
    Image: lsiobase/alpine:3.6
  Name: ""
  Platform: ""
  SourceCode: FROM lsiobase/alpine:3.6
