MetaArgs: null
Stages:
- BaseName: sonarqube:6.1-alpine
  Commands:
  - CmdLine:
    - "apk --update add \t  git \t  curl \t  tmux \t  htop && \t  apk del build-base
      &&       rm -rf /var/cache/apk/*"
    Name: run
    PrependShell: true
  - Env:
    - Key: TZ
      Value: Europe/Lisbon
    Name: env
  - CmdLine:
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://sonarsource.bintray.com/Distribution/sonar-php-plugin/sonar-php-plugin-2.9.0.1664.jar
    - '"/opt/sonarqube/extensions/plugins"'
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://sonarsource.bintray.com/Distribution/sonar-github-plugin/sonar-github-plugin-1.3.jar
    - '"/opt/sonarqube/extensions/plugins"'
  - Env:
    - Key: SONAR_SCANNER_VERSION
      Value: "2.8"
    Name: env
  - Env:
    - Key: SONAR_SCANNER_HOME
      Value: '"/sonar-scanner"'
    Name: env
  - Name: workdir
    Path: '"/"'
  - CmdLine:
    - curl --insecure -OL "https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-$SONAR_SCANNER_VERSION.zip"
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip "/sonar-scanner-$SONAR_SCANNER_VERSION.zip" && mv "sonar-scanner-$SONAR_SCANNER_VERSION"
      "sonar-scanner" && rm "/sonar-scanner-$SONAR_SCANNER_VERSION.zip"
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: ${PATH}:"$SONAR_SCANNER_HOME/bin"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - sonar-scanner.properties
    - '"$SONAR_SCANNER_HOME/conf/sonar-scanner.properties"'
  - Name: workdir
    Path: '"/opt/sonarqube/"'
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - $SONARQUBE_HOME/bin/
  - CmdLine:
    - ./bin/run.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: sonarqube:6.1-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM sonarqube:6.1-alpine
