MetaArgs: null
Stages:
- BaseName: alpine:3.10
  Commands:
  - Maintainer: Josef (kwart) Cacek <josef.cacek@gmail.com>
    Name: maintainer
  - Env:
    - Key: WILDFLY_VERSION
      Value: 17.0.1.Final
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.zip
    - /opt/
  - CmdLine:
    - echo "Installing APK packages"     && apk add --update bash vim nano gawk openjdk8     &&
      echo "Installing WildFly"     && unzip -q /opt/wildfly-$WILDFLY_VERSION.zip
      -d /opt     && rm /opt/wildfly-$WILDFLY_VERSION.zip     && mv /opt/wildfly-$WILDFLY_VERSION
      /opt/wildfly     && echo "Cleaning APK cache"     && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bashrc
    - /root/.bashrc
  - Name: workdir
    Path: /opt
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.10
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.10
