MetaArgs: null
Stages:
- BaseName: attachix/c9-esp8266-sdk:latest
  Commands:
  - Maintainer: Slavey Karadzhov <slav@attachix.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/welcome.html
    - /cloud9/plugins/c9.ide.welcome/welcome.html
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/welcome.js
    - /cloud9/plugins/c9.ide.welcome/welcome.js
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/keybindings.settings
    - /workspace/
  - CmdLine:
    - apk add vim --update-cache --repository https://pkgs.alpinelinux.org/package/edge/main/x86_64/vim
      --allow-untrusted
    Name: run
    PrependShell: true
  - CmdLine:
    - apk add nano --update-cache --repository https://pkgs.alpinelinux.org/package/edge/main/x86/nano
      --allow-untrusted
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/automacaoiot/ESP8266-SDK.git /workspace/AutomacaoIot
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/automacaoiot/Sming /workspace/Sming && cd /workspace/Sming
      && git checkout Feature/3.2.0-HttpMethods
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir shared-workspace
    Name: run
    PrependShell: true
  - Env:
    - Key: SMING_HOME
      Value: /workspace/Sming/Sming
    Name: env
  - Env:
    - Key: SPI_SIZE
      Value: 4MB
    Name: env
  - Env:
    - Key: SERIAL
      Value: python -m serial.tools.miniterm /dev/ttyUSB0 115200
    Name: env
  - CmdLine:
    - /usr/bin/supervisord
    Name: entrypoint
    PrependShell: true
  - Name: volume
    Volumes:
    - /workspace/shared-workspace
  From:
    Image: attachix/c9-esp8266-sdk:latest
  Name: ""
  Platform: ""
  SourceCode: FROM attachix/c9-esp8266-sdk:latest
