MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python-software-properties
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y debconf-utils
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y software-properties-common
    Name: run
    PrependShell: true
  - CmdLine:
    - add-apt-repository -y ppa:webupd8team/java
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true"
      | debconf-set-selections
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y protobuf-compiler
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y oracle-java8-installer
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y curl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y awscli
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libfontconfig1
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libtime-duration-perl
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y cpanminus
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y moreutils
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y task-spooler
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y rubygems
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install rake
    Name: run
    PrependShell: true
  - CmdLine:
    - gem install specific_install && gem specific_install https://github.com/Proemion/github-changelog-generator.git
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install python-pip
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y     apt-transport-https     ca-certificates     && curl -fsSL
      https://download.docker.com/linux/ubuntu/gpg | apt-key add -     && add-apt-repository        "deb
      [arch=amd64] https://download.docker.com/linux/ubuntu        $(lsb_release -cs)        stable"     &&
      apt-get update     && apt-get install -y docker-ce=17.06.0~ce-0~ubuntu
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install docker-compose
    Name: run
    PrependShell: true
  - CmdLine:
    - curl http://ftp.heanet.ie/mirrors/www.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz     |
      tar -zxv -C /opt     && ln -s /opt/apache-maven-3.5.0/bin/mvn /usr/bin/mvn     &&
      mvn -version
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
