MetaArgs: null
Stages:
- BaseName: java:7-jre
  Commands:
  - Name: workdir
    Path: /usr/local/kafka
  - Env:
    - Key: PATH
      Value: $PATH:/usr/local/kafka/bin
    Name: env
  - Env:
    - Key: KAFKA_VERSION
      Value: 0.8.2.2
    Name: env
  - Env:
    - Key: SCALA_VERSION
      Value: "2.10"
    Name: env
  - CmdLine:
    - curl -fSL "http://apache.osuosl.org/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz"
      | tar -xz --strip-components=1
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's!^zookeeper.connect=.*!zookeeper.connect=zookeeper:2181!' config/server.properties
    Name: run
    PrependShell: true
  - CmdLine:
    - kafka-server-start.sh
    - config/server.properties
    Name: cmd
    PrependShell: false
  From:
    Image: java:7-jre
  Name: ""
  Platform: ""
  SourceCode: FROM java:7-jre
