MetaArgs: null
Stages:
- BaseName: debian:latest
  Commands:
  - Key: BUILD_DATE
    Name: arg
    Value: null
  - Key: VCS_REF
    Name: arg
    Value: null
  - Labels:
    - Key: org.label-schema.build-date
      Value: $BUILD_DATE
    - Key: org.label-schema.vcs-url
      Value: '"https://github.com/thawk/docker-calibre.git"'
    - Key: org.label-schema.vcs-ref
      Value: $VCS_REF
    - Key: org.label-schema.schema-version
      Value: '"1.0.0-rc1"'
    Name: label
  - CmdLine:
    - mkdir /documents
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /documents
  - Name: workdir
    Path: /documents
  - Env:
    - Key: PYTHONIOENCODING
      Value: utf-8
    Name: env
  - Env:
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - CmdLine:
    - apt-get update &&  apt-get install --no-install-recommends -y     calibre &&  rm
      -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  From:
    Image: debian:latest
  Name: ""
  Platform: ""
  SourceCode: FROM debian:latest
