MetaArgs: null
Stages:
- BaseName: alledia/composer
  Commands:
  - Maintainer: Alledia <suport@alledia.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - codecept.phar
    - /opt/codecept.phar
  - CmdLine:
    - ln -s /opt/codecept.phar /usr/bin/codecept     && chmod +x /usr/bin/codecept
    Name: run
    PrependShell: true
  From:
    Image: alledia/composer
  Name: ""
  Platform: ""
  SourceCode: FROM alledia/composer
