MetaArgs: null
Stages:
- BaseName: haskell
  Commands:
  - Maintainer: Vincent Demeester <vincent.demeester@zenika.com>
    Name: maintainer
  - CmdLine:
    - apt-get -y install make
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - haskell-make-entrypoint.sh
    - /
  - CmdLine:
    - chmod +x /haskell-make-entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /haskell-make-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: haskell
  Name: ""
  Platform: ""
  SourceCode: FROM haskell
