MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Key: empirversion
    Name: arg
    Value: null
  - Labels:
    - Key: maintainer
      Value: '"EmpireProject"'
    Name: label
  - Labels:
    - Key: description
      Value: '"Dockerfile base for Empire server."'
    Name: label
  - Labels:
    - Key: version
      Value: ${empirversion}
    Name: label
  - Env:
    - Key: STAGING_KEY
      Value: RANDOM
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Name: shell
    Shell:
    - /bin/bash
    - -c
  - CmdLine:
    - apt-get update && apt-get install -qy     wget     curl     git     sudo     apt-utils     lsb-core     python2.7     python-dev   &&
      ln -sf /usr/bin/python2.7 /usr/bin/python   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone --depth=1 -b dev https://github.com/EmpireProject/Empire.git /opt/Empire
      &&     cd /opt/Empire/setup/ &&     ./install.sh &&     rm -rf /opt/Empire/data/empire*
    Name: run
    PrependShell: true
  - CmdLine:
    - python2.7 /opt/Empire/setup/setup_database.py
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/opt/Empire"'
  - CmdLine:
    - python2.7
    - empire
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
