MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
      gnu-libiconv
    Name: run
    PrependShell: true
  - Env:
    - Key: LD_PRELOAD
      Value: /usr/lib/preloadable_libiconv.so
    Name: env
  - CmdLine:
    - apk add --no-cache apache2 php5-apache2 curl     php5-json php5-phar php5-openssl
      php5-mysql php5-curl php5-mcrypt php5-pdo_mysql php5-ctype php5-gd php5-xml
      php5-dom php5-iconv     && mkdir /run/apache2     && mkdir -p /opt/utils
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /app
  - CmdLine:
    - /app/start.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
