MetaArgs: null
Stages:
- BaseName: ubuntu:xenial
  Commands:
  - Maintainer: Susanna Kiwala <ssiebert@wustl.edu>
    Name: maintainer
  - Labels:
    - Key: description
      Value: '"Image for tools used in the CLE"'
    Name: label
  - CmdLine:
    - apt-get update -y && apt-get install -y     wget     git     unzip     bzip2     g++     make     zlib1g-dev     ncurses-dev     perl-doc     python     rsync     default-jdk     default-jre     bioperl     libfile-copy-recursive-perl     libarchive-extract-perl     libarchive-zip-perl     libapache-dbi-perl     curl     ant
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -y && apt-get install -y python-pip python-dev build-essential
      nodejs
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install --upgrade pip
    Name: run
    PrependShell: true
  - Env:
    - Key: maven_package_name
      Value: apache-maven-3.3.9
    Name: env
  - Env:
    - Key: gatk_dir_name
      Value: gatk-protected
    Name: env
  - Env:
    - Key: gatk_version
      Value: "3.6"
    Name: env
  - CmdLine:
    - cd /tmp/ && wget -q http://mirror.nohup.it/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/     && git clone --recursive https://github.com/broadgsa/gatk-protected.git     &&
      cd /tmp/gatk-protected && git checkout tags/${gatk_version}     && sed -i 's/^import
      oracle.jrockit.jfr.StringConstantPool;/\/\/import oracle.jrockit.jfr.StringConstantPool;/'
      ./public/gatk-tools-public/src/main/java/org/broadinstitute/gatk/tools/walkers/varianteval/VariantEval.java     &&
      mv /tmp/gatk-protected /opt/${gatk_dir_name}-${gatk_version}
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /opt/ && unzip /tmp/${maven_package_name}-bin.zip     && rm -rf /tmp/${maven_package_name}-bin.zip
      LICENSE NOTICE README.txt     && cd /opt/     && cd /opt/${gatk_dir_name}-${gatk_version}
      && /opt/${maven_package_name}/bin/mvn verify -P\!queue     && mv /opt/${gatk_dir_name}-${gatk_version}/protected/gatk-package-distribution/target/gatk-package-distribution-${gatk_version}.jar
      /opt/GenomeAnalysisTK.jar     && rm -rf /opt/${gatk_dir_name}-${gatk_version}
      /opt/${maven_package_name}
    Name: run
    PrependShell: true
  - Env:
    - Key: STRELKA_INSTALL_DIR
      Value: /opt/strelka/
    Name: env
  - CmdLine:
    - wget https://github.com/Illumina/strelka/releases/download/v2.7.1/strelka-2.7.1.centos5_x86_64.tar.bz2     &&
      tar xf strelka-2.7.1.centos5_x86_64.tar.bz2     && rm -f strelka-2.7.1.centos5_x86_64.tar.bz2     &&
      mv strelka-2.7.1.centos5_x86_64 $STRELKA_INSTALL_DIR
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - strelka_helper.pl
    - /usr/bin/strelka_helper.pl
  - Env:
    - Key: VARSCAN_INSTALL_DIR
      Value: /opt/varscan
    Name: env
  - Name: workdir
    Path: $VARSCAN_INSTALL_DIR
  - CmdLine:
    - wget https://github.com/dkoboldt/varscan/releases/download/2.4.2/VarScan.v2.4.2.jar
      &&     ln -s VarScan.v2.4.2.jar VarScan.jar
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - intervals_to_bed.pl
    - /usr/bin/intervals_to_bed.pl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - varscan_helper.sh
    - /usr/bin/varscan_helper.sh
  - Env:
    - Key: HTSLIB_INSTALL_DIR
      Value: /opt/htslib
    Name: env
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - wget https://github.com/samtools/htslib/releases/download/1.3.2/htslib-1.3.2.tar.bz2
      &&     tar --bzip2 -xvf htslib-1.3.2.tar.bz2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp/htslib-1.3.2
  - CmdLine:
    - ./configure  --enable-plugins --prefix=$HTSLIB_INSTALL_DIR &&     make &&     make
      install &&     cp $HTSLIB_INSTALL_DIR/lib/libhts.so* /usr/lib/
    Name: run
    PrependShell: true
  - Env:
    - Key: SAMTOOLS_INSTALL_DIR
      Value: /opt/samtools
    Name: env
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
      &&     tar --bzip2 -xf samtools-1.3.1.tar.bz2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp/samtools-1.3.1
  - CmdLine:
    - ./configure --with-htslib=$HTSLIB_INSTALL_DIR --prefix=$SAMTOOLS_INSTALL_DIR
      &&     make &&     make install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - rm -rf /tmp/samtools-1.3.1
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget https://github.com/genome/pindel/archive/v0.2.5b8.tar.gz &&     tar -xzf
      v0.2.5b8.tar.gz
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/pindel-0.2.5b8
  - CmdLine:
    - ./INSTALL /tmp/htslib-1.3.2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - rm -rf /tmp/htslib-1.3.2
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/pindel-0.2.5b8/pindel /usr/bin/pindel
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /opt/pindel-0.2.5b8/pindel2vcf /usr/bin/pindel2vcf
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - pindel_helper.pl
    - /usr/bin/pindel_helper.pl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - write_pindel_filter_config.pl
    - /usr/bin/write_pindel_filter_config.pl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - somatic_indelfilter.pl
    - /usr/bin/somatic_indelfilter.pl
  - CmdLine:
    - apt-get update &&     apt-get install -y         cmake         patch         git
    Name: run
    PrependShell: true
  - Env:
    - Key: SAMTOOLS_ROOT
      Value: /opt/samtools
    Name: env
  - CmdLine:
    - mkdir /opt/bam-readcount
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/bam-readcount
  - CmdLine:
    - git clone https://github.com/genome/bam-readcount.git /tmp/bam-readcount-0.7.4
      &&     git -C /tmp/bam-readcount-0.7.4 checkout v0.7.4 &&     cmake /tmp/bam-readcount-0.7.4
      &&     make &&     rm -rf /tmp/bam-readcount-0.7.4 &&     ln -s /opt/bam-readcount/bin/bam-readcount
      /usr/bin/bam-readcount
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bam_readcount_helper.py
    - /usr/bin/bam_readcount_helper.py
  - CmdLine:
    - pip install cyvcf2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt
  - CmdLine:
    - wget --no-check-certificate https://raw.githubusercontent.com/genome/fpfilter-tool/v0.1.0/fpfilter.pl
      &&     cp fpfilter.pl /usr/bin/fpfilter.pl &&     rm fpfilter.pl
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s $HTSLIB_INSTALL_DIR/bin/tabix /usr/bin/tabix
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docm_filter.pl
    - /usr/bin/docm_filter.pl
  - CmdLine:
    - mkdir /opt/vep/
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/vep
  - CmdLine:
    - wget https://github.com/Ensembl/ensembl-tools/archive/release/86.zip &&     unzip
      86.zip
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/vep/ensembl-tools-release-86/scripts/variant_effect_predictor/
  - CmdLine:
    - perl INSTALL.pl --NO_HTSLIB
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - ln -s /opt/vep/ensembl-tools-release-86/scripts/variant_effect_predictor/variant_effect_predictor.pl
      /usr/bin/variant_effect_predictor.pl
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/lib/perl/VEP/Plugins
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Downstream.pm
    - /opt/lib/perl/VEP/Plugins/Downstream.pm
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Wildtype.pm
    - /opt/lib/perl/VEP/Plugins/Wildtype.pm
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - add_annotations_to_table_helper.py
    - /usr/bin/add_annotations_to_table_helper.py
  - Env:
    - Key: BCFTOOLS_INSTALL_DIR
      Value: /opt/bcftools
    Name: env
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - wget https://github.com/samtools/bcftools/releases/download/1.3.1/bcftools-1.3.1.tar.bz2
      &&     tar --bzip2 -xf bcftools-1.3.1.tar.bz2
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /tmp/bcftools-1.3.1
  - CmdLine:
    - make prefix=$BCFTOOLS_INSTALL_DIR &&     make prefix=$BCFTOOLS_INSTALL_DIR install
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /
  - CmdLine:
    - rm -rf /tmp/bcftools-1.3.1
    Name: run
    PrependShell: true
  - Env:
    - Key: picard_version
      Value: 2.4.1
    Name: env
  - CmdLine:
    - cd /usr/ && git config --global http.sslVerify false && git clone --recursive
      https://github.com/broadinstitute/picard.git && cd /usr/picard && git checkout
      tags/${picard_version}
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/picard
  - CmdLine:
    - git config --global http.sslVerify false && git clone https://github.com/samtools/htsjdk.git
      && cd htsjdk && git checkout tags/${picard_version} && cd ..
    Name: run
    PrependShell: true
  - CmdLine:
    - ant clean all &&     mv dist/picard.jar picard.jar &&     mv src/scripts/picard/docker_helper.sh
      docker_helper.sh &&     ant clean &&     rm -rf htsjdk &&     rm -rf src &&     rm
      -rf lib &&     rm build.xml
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - split_interval_list_helper.pl
    - /usr/bin/split_interval_list_helper.pl
  - CmdLine:
    - pip install toil[cwl]==3.6.0
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/select\[type==X86_64 && mem/select[mem/' /usr/local/lib/python2.7/dist-packages/toil/batchSystems/lsf.py
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -y && apt-get install -y libnss-sss tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "America/Chicago" > /etc/timezone
    Name: run
    PrependShell: true
  - CmdLine:
    - dpkg-reconfigure --frontend noninteractive tzdata
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y build-essential gcc-multilib apt-utils
      zlib1g-dev git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/ && git clone https://github.com/statgen/verifyBamID.git && git clone
      https://github.com/statgen/libStatGen.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/libStatGen && git checkout tags/v1.0.14
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/verifyBamID && git checkout tags/v1.1.3 && make
    Name: run
    PrependShell: true
  - CmdLine:
    - cp /tmp/verifyBamID/bin/verifyBamID /usr/local/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /tmp/verifyBamID /tmp/libStatGen
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y r-base littler
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y lib32ncurses5
    Name: run
    PrependShell: true
  - Env:
    - Key: CONCORDANCE_INSTALL_DIR
      Value: /opt/concordance
    Name: env
  - Name: workdir
    Path: $CONCORDANCE_INSTALL_DIR
  - CmdLine:
    - wget https://raw.githubusercontent.com/mnneveau/concordance/master/newConcordance.py
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install FisherExact
    Name: run
    PrependShell: true
  From:
    Image: ubuntu:xenial
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:xenial
