MetaArgs: null
Stages:
- BaseName: rocker/verse:3.6.1
  Commands:
  - CmdLine:
    - R -e "devtools::install_github('selcenari/ceRNAnetsim', ref= 'master')"
    Name: run
    PrependShell: true
  - Env:
    - Key: NB_USER
      Value: rstudio
    Name: env
  - Env:
    - Key: NB_UID
      Value: "1000"
    Name: env
  - Env:
    - Key: VENV_DIR
      Value: /srv/venv
    Name: env
  - Env:
    - Key: PATH
      Value: ${VENV_DIR}/bin:$PATH
    Name: env
  - CmdLine:
    - echo "PATH=${PATH}" >> /usr/local/lib/R/etc/Renviron
    Name: run
    PrependShell: true
  - Env:
    - Key: LD_LIBRARY_PATH
      Value: /usr/local/lib/R/lib
    Name: env
  - Env:
    - Key: HOME
      Value: /home/${NB_USER}
    Name: env
  - Name: workdir
    Path: ${HOME}
  - CmdLine:
    - apt-get update &&     apt-get -y install python3-venv python3-dev &&     apt-get
      purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ${VENV_DIR} && chown -R ${NB_USER} ${VENV_DIR}
    Name: run
    PrependShell: true
  - Name: user
    User: ${NB_USER}
  - CmdLine:
    - python3 -m venv ${VENV_DIR} &&     pip3 install pip==9.0.1 &&     pip3 install
      --no-cache-dir          nbrsessionproxy==0.6.1 &&     jupyter serverextension
      enable --sys-prefix --py nbrsessionproxy &&     jupyter nbextension install    --sys-prefix
      --py nbrsessionproxy &&     jupyter nbextension enable     --sys-prefix --py
      nbrsessionproxy
    Name: run
    PrependShell: true
  - CmdLine:
    - R --quiet -e "devtools::install_github('IRkernel/IRkernel')" &&     R --quiet
      -e "IRkernel::installspec(prefix='${VENV_DIR}')"
    Name: run
    PrependShell: true
  - CmdLine:
    - jupyter notebook --ip 0.0.0.0
    Name: cmd
    PrependShell: true
  From:
    Image: rocker/verse:3.6.1
  Name: ""
  Platform: ""
  SourceCode: FROM rocker/verse:3.6.1
