MetaArgs: null
Stages:
- BaseName: java:8
  Commands:
  - Maintainer: Faisal Jarkass (fafj@kea.dk)
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y maven
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /SpringBootDockerJar
  - Name: volume
    Volumes:
    - /tmp
  - Chown: ""
    Name: add
    SourcesAndDest:
    - pom.xml
    - /SpringBootDockerJar/pom.xml
  - CmdLine:
    - mvn
    - dependency:resolve
    Name: run
    PrependShell: false
  - Chown: ""
    Name: add
    SourcesAndDest:
    - src
    - /SpringBootDockerJar/src
  - CmdLine:
    - mvn
    - clean
    Name: run
    PrependShell: false
  - CmdLine:
    - mvn
    - package
    Name: run
    PrependShell: false
  - CmdLine:
    - /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    - -jar
    - target/demo-0.0.1-SNAPSHOT.jar
    Name: cmd
    PrependShell: false
  From:
    Image: java:8
  Name: ""
  Platform: ""
  SourceCode: FROM java:8
