MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.12
  Commands:
  - Name: workdir
    Path: /go/src/github.com/subhaze/cloudflare-ip-updater
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - main.go
    - .
  - CmdLine:
    - go get -d -v
    Name: run
    PrependShell: true
  - CmdLine:
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.12 AS builder
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - "apk update \t&& apk upgrade \t&& apk add --no-cache \tca-certificates \t&&
      update-ca-certificates 2>/dev/null || true"
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /root/
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /go/src/github.com/subhaze/cloudflare-ip-updater/server
    - .
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - ./server
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
