MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - Labels:
    - Key: maintainer
      Value: '"DasCodeMonster <pl.lkw.01@gmail.com>"'
    Name: label
  - Name: workdir
    Path: /usr/src/MyBotV2
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package-lock.json
    - ./
  - CmdLine:
    - apk add --update && apk add --no-cache --virtual .build-deps git curl python
      g++ make && apk add ffmpeg && npm install && apk del .build-deps
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - Env:
    - Key: Token
      Value: ""
    - Key: PREFIX
      Value: ""
    Name: env
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
