MetaArgs: null
Stages:
- BaseName: mmxca/php
  Commands:
  - CmdLine:
    - "php -version \t&& yum install -y wget \t&& EXPECTED_SIGNATURE=$(wget -q -O
      - https://composer.github.io/installer.sig) \t&& php -r \"copy('https://getcomposer.org/installer',
      'composer-setup.php');\" \t&& ACTUAL_SIGNATURE=$(php -r \"echo hash_file('SHA384',
      'composer-setup.php');\") \t&& if [ \"$EXPECTED_SIGNATURE\" != \"$ACTUAL_SIGNATURE\"
      ]; then \t \t  >&2 echo 'ERROR: Invalid installer signature'; \t \t  rm composer-setup.php;
      \t \t  exit 1; \t   fi \t&& php composer-setup.php --install-dir=/usr/bin/ --filename=composer
      \t&& RESULT=$? \t&& rm composer-setup.php  \t&& exit $RESULT"
    Name: run
    PrependShell: true
  - CmdLine:
    - "yum erase -y wget \t&& yum clean all \t&& rm -rf /var/lib/yum/* \t&& rm -rf
      ~/*"
    Name: run
    PrependShell: true
  From:
    Image: mmxca/php
  Name: ""
  Platform: ""
  SourceCode: FROM mmxca/php
