MetaArgs: null
Stages:
- BaseName: java:8-jre-alpine
  Commands:
  - Key: JMETER_VERSION
    Name: arg
    Value: '"5.1"'
  - Env:
    - Key: JMETER_HOME
      Value: /opt/apache-jmeter-${JMETER_VERSION}
    Name: env
  - Env:
    - Key: JMETER_BIN
      Value: ${JMETER_HOME}/bin
    Name: env
  - CmdLine:
    - apk add --update ca-certificates openssl unzip && update-ca-certificates &&   mkdir
      -p ${JMETER_HOME} &&   wget -qO- https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
      | tar xvzf - -C /opt/ &&   ln -s /opt/rmi_keystore.jks ${JMETER_BIN}/rmi_keystore.jks
      &&   touch /opt/rmi_keystore.jks &&   rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - Env:
    - Key: PATH
      Value: $PATH:$JMETER_BIN
    Name: env
  From:
    Image: java:8-jre-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM java:8-jre-alpine
