MetaArgs: null
Stages:
- BaseName: redis:alpine
  Commands:
  - Maintainer: bingo <bingov5@icloud.com>
    Name: maintainer
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./conf/redis.conf
    - /usr/local/etc/redis/redis.conf
  - CmdLine:
    - redis-server
    - /usr/local/etc/redis/redis.conf
    Name: cmd
    PrependShell: false
  From:
    Image: redis:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM redis:alpine
