MetaArgs: null
Stages:
- BaseName: buildpack-deps:wily
  Commands:
  - Env:
    - Key: ATS_VERSION
      Value: 6.0.0
    Name: env
  - Name: workdir
    Path: /opt
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - wget "http://archive.apache.org/dist/trafficserver/trafficserver-${ATS_VERSION}.tar.bz2"
      &&     wget "http://archive.apache.org/dist/trafficserver/trafficserver-${ATS_VERSION}.tar.bz2.asc"
      &&     wget "http://archive.apache.org/dist/trafficserver/KEYS"
    Name: run
    PrependShell: true
  - CmdLine:
    - gpg --import KEYS &&     gpg --verify trafficserver-${ATS_VERSION}.tar.bz2.asc
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y     openssl     tcl-dev     expat     libpcre3-dev     libcap-dev    hwloc     libncurses5-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvf trafficserver-${ATS_VERSION}.tar.bz2 &&     cd trafficserver-${ATS_VERSION}
      &&     autoreconf -if &&     ./configure &&     make -j$(nproc) &&     make
      install
    Name: run
    PrependShell: true
  From:
    Image: buildpack-deps:wily
  Name: ""
  Platform: ""
  SourceCode: FROM buildpack-deps:wily
