MetaArgs:
- DefaultValue: 3.8.0b1-alpine3.9
  Key: _TAG
  ProvidedValue: null
  Value: 3.8.0b1-alpine3.9
Stages:
- BaseName: python:${_TAG}
  Commands:
  - Maintainer: iganari
    Name: maintainer
  - CmdLine:
    - apk --update add tzdata &&     cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      &&     apk del tzdata &&     rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  From:
    Image: python:${_TAG}
  Name: ""
  Platform: ""
  SourceCode: FROM python:${_TAG}
