MetaArgs: null
Stages:
- BaseName: sonatype/nexus3
  Commands:
  - Name: user
    User: root
  - Key: NEXUS_CHANGE_PASSWORD_SCRIPT_URL
    Name: arg
    Value: '"https://gist.github.com/making/34e71cb1a56e1280545ade7c9a5032f1/archive/bcedf90963ece53b40106da75666d7dbc1ccfc5a.zip"'
  - Key: NEXUS_SCRIPTING_EXAMPLES_URL
    Name: arg
    Value: '"https://github.com/sonatype-nexus-community/nexus-scripting-examples/archive/master.zip"'
  - CmdLine:
    - yum -y update --disableplugin=subscription-manager && yum clean all
    Name: run
    PrependShell: true
  - CmdLine:
    - yum -y install unzip --disableplugin=subscription-manager     && curl -L ${NEXUS_CHANGE_PASSWORD_SCRIPT_URL}
      --output /tmp/change_password_script.zip     && curl -L ${NEXUS_SCRIPTING_EXAMPLES_URL}
      --output /tmp/master.zip     && yum clean all
    Name: run
    PrependShell: true
  - Name: user
    User: nexus
  - CmdLine:
    - unzip /tmp/change_password_script.zip -d /tmp
    Name: run
    PrependShell: true
  - CmdLine:
    - mv /tmp/34e71cb1a56e1280545ade7c9a5032f1-bcedf90963ece53b40106da75666d7dbc1ccfc5a
      /tmp/change_password_script
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip /tmp/master.zip -d /tmp
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - rm /tmp/master.zip && rm /tmp/change_password_script.zip
    Name: run
    PrependShell: true
  - Name: user
    User: nexus
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - start_nexus.sh
    - /tmp
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - configure_nexus.sh
    - /tmp
  - CmdLine:
    - sh
    - /tmp/start_nexus.sh
    Name: cmd
    PrependShell: false
  From:
    Image: sonatype/nexus3
  Name: ""
  Platform: ""
  SourceCode: FROM sonatype/nexus3
