MetaArgs: null
Stages:
- BaseName: koding/base
  Commands:
  - Maintainer: Sonmez Kartal <sonmez@koding.com>
    Name: maintainer
  - CmdLine:
    - apt-get update &&     apt-get install --yes             mongodb-server             postgresql
      postgresql-contrib             rabbitmq-server             redis-server
    Name: run
    PrependShell: true
  - CmdLine:
    - rabbitmq-plugins enable rabbitmq_management
    Name: run
    PrependShell: true
  - Name: user
    User: postgres
  - CmdLine:
    - sed -i "s/#listen_addresses =.*/listen_addresses = '*'/" /etc/postgresql/9.3/main/postgresql.conf
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.3/main/pg_hba.conf
    Name: run
    PrependShell: true
  - Name: user
    User: root
  - CmdLine:
    - cd /opt && git clone https://github.com/koding/koding.git
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /opt/koding
  - CmdLine:
    - service postgresql start &&     go/src/socialapi/db/sql/definition/create.sh
      &&     service postgresql stop
    Name: run
    PrependShell: true
  - CmdLine:
    - npm install --unsafe-perm &&     echo master > VERSION &&     ./configure --host
      localhost --hostname localhost --publicPort 80 &&     go/build.sh &&     service
      postgresql start && ./run migrate up && service postgresql stop &&     make
      -C client dist &&     rm -rf generated
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - docker-entrypoint
    - /opt/koding/docker-entrypoint
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint.sh
    - /opt/koding/entrypoint.sh
  - Chown: ""
    Name: add
    SourcesAndDest:
    - wait.sh
    - /opt/koding/wait.sh
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - /opt/koding/docker-entrypoint
    Name: entrypoint
    PrependShell: false
  From:
    Image: koding/base
  Name: ""
  Platform: ""
  SourceCode: FROM koding/base
