MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Maintainer: Chris Sim <chris.sim@antpolis.com> <chris.sim@dailyvanity.sg>
    Name: maintainer
  - CmdLine:
    - apt update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y software-properties-common make wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-add-repository --yes --update ppa:ansible/ansible
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y ansible
    Name: run
    PrependShell: true
  - CmdLine:
    - apt clean
    Name: run
    PrependShell: true
  - CmdLine:
    - ansible-playbook
    - --version
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
