MetaArgs: null
Stages:
- BaseName: busybox:latest
  Commands:
  - Maintainer: David Lee Crites <lee@critesclan.com>
    Name: maintainer
  - CmdLine:
    - mkdir -pm 0777 /opt/splunk &&     mkdir -pm 0777 /opt/splunk/temp &&     mkdir
      -pm 0777 /opt/splunk/etc &&     mkdir -pm 0777 /opt/splunk/var
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /opt/splunk/temp
    - /opt/splunk/etc
    - /opt/splunk/var
  - CmdLine:
    - echo '#!/bin/sh' 1>/entrypoint.sh &&     echo 'tail -f /dev/null' 1>>/entrypoint.sh
      &&     chmod 755 /entrypoint.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - busybox
    Name: cmd
    PrependShell: false
  From:
    Image: busybox:latest
  Name: ""
  Platform: ""
  SourceCode: FROM busybox:latest
