MetaArgs: null
Stages:
- BaseName: ubuntu:16.10
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y software-properties-common &&     add-apt-repository
      ppa:certbot/certbot &&     apt-get update &&     apt-get install -y certbot
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /etc/letsencrypt
  - Name: volume
    Volumes:
    - /etc/letsencrypt
  - CmdLine:
    - certbot
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.10
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.10
