MetaArgs: null
Stages:
- BaseName: bcroq/stackless:2.7.9
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y build-essential libxml2-dev libxslt1-dev
      zlib1g-dev libjpeg-dev libfreetype6-dev
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /tmp/kansha
  - CmdLine:
    - cd /tmp/kansha &&     /opt/stackless/bin/pip install -e . --allow-external PEAK-Rules
      --allow-unverified PEAK-Rules --find-links http://www.nagare.org/snapshots --trusted-host
      www.nagare.org
    Name: run
    PrependShell: true
  - CmdLine:
    - cd /tmp/kansha && /opt/stackless/bin/python setup.py compile_catalog &&     /opt/stackless/bin/nagare-admin
      create-db kansha &&     /opt/stackless/bin/nagare-admin create-index kansha
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - /opt/stackless/bin/nagare-admin
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - serve
    - --host
    - 0.0.0.0
    - kansha
    Name: cmd
    PrependShell: false
  From:
    Image: bcroq/stackless:2.7.9
  Name: ""
  Platform: ""
  SourceCode: FROM bcroq/stackless:2.7.9
