MetaArgs: null
Stages:
- BaseName: dataplatform/docker-hive-base:1.0.2
  Commands:
  - Maintainer: MZ
    Name: maintainer
  - Env:
    - Key: SPARK_VERSION
      Value: '"2.2.0"'
    - Key: SPARK_HOME
      Value: '"${MY_APP_DIR}/spark"'
    - Key: SPARK_MASTER
      Value: '"local"'
    - Key: SPARK_DRIVER_MEMORY
      Value: '"512m"'
    - Key: SPARK_EXECUTOR_MEMORY
      Value: '"512m"'
    - Key: SQOOP_VERSION
      Value: '"1.4.6"'
    - Key: SQOOP_HOME
      Value: '"${MY_APP_DIR}/sqoop"'
    - Key: FLINK_VERSION
      Value: '"1.1.3"'
    - Key: FLINK_HOME
      Value: '"${MY_APP_DIR}/flink"'
    - Key: VERTICA_CLIENT_VERSION
      Value: '"8.0.1"'
    Name: env
  - Env:
    - Key: SPARK_CONF_DIR
      Value: '"${SPARK_HOME}/conf"'
    - Key: SPARK_BIN_URL
      Value: '"https://github.com/thaiphamquoc/spark/releases/download/v${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop-2.7.3.tgz"'
    - Key: SQOOP_BIN_URL
      Value: '"http://archive.apache.org/dist/sqoop/${SQOOP_VERSION}/sqoop-${SQOOP_VERSION}.bin__hadoop-2.0.4-alpha.tar.gz"'
    - Key: FLINK_BIN_URL
      Value: '"http://archive.apache.org/dist/flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-hadoop27-scala_2.10.tgz"'
    - Key: VSQL_BIN_URL
      Value: '"https://github.com/thaiphamquoc/vsql/releases/download/v${VERTICA_CLIENT_VERSION}/vertica-client-${VERTICA_CLIENT_VERSION}-0.x86_64.tar.gz"'
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/build
    - /my_build
  - CmdLine:
    - /my_build/install.sh && rm -rf /my_build
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - templates
    - ${MY_TEMPLATE_DIR}
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scripts/init
    - ${MY_INIT_DIR}
  From:
    Image: dataplatform/docker-hive-base:1.0.2
  Name: ""
  Platform: ""
  SourceCode: FROM dataplatform/docker-hive-base:1.0.2
