MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/kube-registry-proxy:0.4
  Commands: null
  From:
    Image: gcr.io/google_containers/kube-registry-proxy:0.4
  Name: ""
  Platform: ""
  SourceCode: from gcr.io/google_containers/kube-registry-proxy:0.4
