MetaArgs: null
Stages:
- BaseName: ubuntu
  Commands:
  - CmdLine:
    - apt-get update && apt-get install -y     software-properties-common     unzip     curl     xvfb     wget     libfontconfig     gnupg     --no-install-recommends
      apt-utils     python-pip     default-jre-headless     libxml2-dev     libxslt-dev     zlib1g-dev     net-tools     default-jre     default-jdk     zip     unzip     build-essential     autoconf     libtool     pkg-config     python-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxdamage1
      libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0
      libgtk-3-0
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    Name: run
    PrependShell: true
  - CmdLine:
    - tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list
      &&wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
      add - &&apt-get update &&apt-get -y install google-chrome-stable
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get -y install unzip &&wget -q https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
      &&unzip chromedriver_linux64.zip &&mv chromedriver /usr/bin/chromedriver &&chown
      root:root /usr/bin/chromedriver &&chmod +x /usr/bin/chromedriver &&rm chromedriver_linux64.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install selenium
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install setuptools
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install pytest allure-pytest pytest-html
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install bzt
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install imgqa
    Name: run
    PrependShell: true
  From:
    Image: ubuntu
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu
