MetaArgs: null
Stages:
- BaseName: ubuntu:trusty
  Commands:
  - Maintainer: dj80hd "werwath@gmail.com"
    Name: maintainer
  - CmdLine:
    - apt-get update -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y python-pip python-dev build-essential git curl python-virtualenv
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /app
  - CmdLine:
    - cd /app & git clone https://github.com/dj80hd/SimpleFlask.git
    Name: run
    PrependShell: true
  - CmdLine:
    - cd SimpleFlask && pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - Name: workdir
    Path: /app/SimpleFlask
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./entrypoint.sh
    - /app/SimpleFlask/
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - CmdLine:
    - ./entrypoint.sh
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:trusty
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:trusty
