FROM node:0.12.7-onbuild

ENV AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID> \
AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY> \
AWS_ELASTICSEARCH_DOMAIN=<AWS_ELASTICSEARCH_DOMAIN> \
BIND_PORT=9200


EXPOSE 9200
