MetaArgs: null
Stages:
- BaseName: proofpilot/environment-opencpu-generic:generic
  Commands:
  - Maintainer: Volodymyr Sheptytsky <vshept@hotmail.com>
    Name: maintainer
  - Env:
    - Key: GIT_TOKEN
      Value: '"5bfae573af3eb9eff8cb52c1beb2be2580b6fcb3"'
    Name: env
  - Env:
    - Key: SOME_C
      Value: '"ServerName opencpu.proofpilot.com"'
    Name: env
  - CmdLine:
    - echo "004"
    Name: run
    PrependShell: true
  - CmdLine:
    - 'mkdir /tmp/OpenCPU  && curl -H "Authorization: token $GIT_TOKEN"       -L https://api.github.com/repos/ProofPilot/OpenCPU/tarball/master
      |       tar -xz --strip 1 -C /tmp/OpenCPU  && ls -l /tmp'
    Name: run
    PrependShell: true
  - CmdLine:
    - rm -rf /home/rstudio/r-ppv3 || true  && mv -f /tmp/OpenCPU/r-ppv3  /home/rstudio/  &&
      rm -rf /tmp/OpenCPU  && chown -R rstudio:rstudio /home/rstudio/r-ppv3  && find
      /home/rstudio/ -type d | xargs chmod a+x  && chmod -R a+rw /home/rstudio
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - etc/
    - /etc/
  - Name: workdir
    Path: /home/rstudio/r-ppv3
  - CmdLine:
    - R CMD build `ls -d */`
    Name: run
    PrependShell: true
  - CmdLine:
    - R CMD INSTALL *.tar.gz
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R rstudio:rstudio /home/rstudio/r-ppv3  && find /home/rstudio/ -type
      d | xargs chmod a+x  && chmod -R a+rw /home/rstudio
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  From:
    Image: proofpilot/environment-opencpu-generic:generic
  Name: ""
  Platform: ""
  SourceCode: FROM proofpilot/environment-opencpu-generic:generic
