MetaArgs: null
Stages:
- BaseName: gcr.io/google_containers/etcd-amd64:3.1.17
  Commands:
  - Maintainer: silenceshell <silenceshell@datastart.cn>
    Name: maintainer
  From:
    Image: gcr.io/google_containers/etcd-amd64:3.1.17
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google_containers/etcd-amd64:3.1.17
