MetaArgs: null
Stages:
- BaseName: centos:centos7
  Commands:
  - Maintainer: Martin Nagy <nagy.martin@gmail.com>
    Name: maintainer
  - Env:
    - Key: container
      Value: docker
    Name: env
  - CmdLine:
    - rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 &&     yum -y
      --setopt=tsflags=nodocs install rpcbind nfs-utils &&     mkdir -p /exports &&     yum
      clean all
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run-mountd.sh
    - /
  - Name: volume
    Volumes:
    - /exports
  - CmdLine:
    - echo 'RPCRQUOTADOPTS="-p 875"' >> /etc/sysconfig/nfs
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'LOCKD_TCPPORT="32803"' >> /etc/sysconfig/nfs
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'LOCKD_UDPPORT="32769"' >> /etc/sysconfig/nfs
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'RPCMOUNTDOPTS="-p 892"' >> /etc/sysconfig/nfs
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'STATDARG="-p 662 -o 2020"' >> /etc/sysconfig/nfs
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 111/tcp
    - 111/udp
    - 2049/tcp
    - 2049/udp
    - 32769/udp
    - 32803/tcp
    - 662/tcp
    - 662/udp
    - 875/tcp
    - 875/udp
    - 892/tcp
    - 892/udp
  - CmdLine:
    - /run-mountd.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: centos:centos7
  Name: ""
  Platform: ""
  SourceCode: FROM centos:centos7
