MetaArgs: null
Stages:
- BaseName: sebp/elk:660
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 30-output.conf
    - /etc/logstash/conf.d/
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - 50-udp.conf
    - /etc/logstash/conf.d/
  - Name: expose
    Ports:
    - 5140/udp
  From:
    Image: sebp/elk:660
  Name: ""
  Platform: ""
  SourceCode: FROM sebp/elk:660
