MetaArgs: null
Stages:
- BaseName: node:6.12-alpine
  Commands:
  - Maintainer: Acumen dev team <acumendev1@gmail.com>
    Name: maintainer
  - Env:
    - Key: SERVERLESS_VERSION
      Value: 1.12.1
    Name: env
  - CmdLine:
    - apk --update add       git       python       py-pip       jq     && pip install
      awscli==1.14.70     && apk del py-pip     && rm -rf /var/cache/apk/*     &&
      npm install       cfn-create-or-update@1.1.2       serverless@${SERVERLESS_VERSION}       -g
    Name: run
    PrependShell: true
  From:
    Image: node:6.12-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:6.12-alpine
