MetaArgs: null
Stages:
- BaseName: busybox:latest
  Commands:
  - Env:
    - Key: CNI_VERSION
      Value: v0.8.3
    Name: env
  - Name: workdir
    Path: /cni
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/containernetworking/plugins/releases/download/$CNI_VERSION/cni-plugins-linux-amd64-$CNI_VERSION.tgz
    - cni-plugins.tgz
  - CmdLine:
    - tar
    - xvzf
    - cni-plugins.tgz
    - -C
    - /opt/cni/bin
    Name: entrypoint
    PrependShell: false
  From:
    Image: busybox:latest
  Name: ""
  Platform: ""
  SourceCode: FROM busybox:latest
