MetaArgs: null
Stages:
- BaseName: biowardrobe2/scidap:v0.0.2
  Commands:
  - Maintainer: Michael Kotliar "misha.kotliar@gmail.com"
    Name: maintainer
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Name: workdir
    Path: /tmp
  - Env:
    - Key: VERSION
      Value: 2.8.2-1
    Name: env
  - Env:
    - Key: NAME
      Value: sratoolkit
    Name: env
  - Env:
    - Key: URL
      Value: '"https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/${VERSION}/sratoolkit.${VERSION}-ubuntu64.tar.gz"'
    Name: env
  - CmdLine:
    - wget -q -O - $URL | tar -zxv &&     cp -r sratoolkit.${VERSION}-ubuntu64/bin/*
      /usr/local/bin &&     cp -r sratoolkit.${VERSION}-ubuntu64/schema /usr/local
      &&     rm -rf sratoolkit.${VERSION}-ubuntu64
    Name: run
    PrependShell: true
  From:
    Image: biowardrobe2/scidap:v0.0.2
  Name: ""
  Platform: ""
  SourceCode: FROM biowardrobe2/scidap:v0.0.2
