MetaArgs: null
Stages:
- BaseName: nginx
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - nginx.conf
    - /etc/nginx/conf.d/custom.conf
  From:
    Image: nginx
  Name: ""
  Platform: ""
  SourceCode: FROM nginx
