MetaArgs: null
Stages:
- BaseName: alpine:3.3
  Commands:
  - CmdLine:
    - adduser -h /goploader -S -u 1000 goploader
    Name: run
    PrependShell: true
  - Env:
    - Key: GOSU_VERSION
      Value: "1.7"
    Name: env
  - CmdLine:
    - apk add --no-cache --virtual build.deps curl gnupg     && curl -o /usr/local/bin/gosu
      -fsSL "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64"     &&
      curl -o /usr/local/bin/gosu.asc -fsSL "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64.asc"     &&
      export GNUPGHOME="$(mktemp -d)"     && gpg --keyserver ha.pool.sks-keyservers.net
      --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4     && gpg --batch --verify
      /usr/local/bin/gosu.asc /usr/local/bin/gosu     && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc     &&
      chmod +x /usr/local/bin/gosu     && gosu nobody true     && apk del build.deps
    Name: run
    PrependShell: true
  - Env:
    - Key: GOPLOADER_VERSION
      Value: quota
    Name: env
  - CmdLine:
    - set -x;     apk add --no-cache --virtual build.deps go git     && export GOPATH=/go
      PATH=/go/bin:$PATH CGO_ENABLED=0     && mkdir -p /go/{pkg,src,bin}     && mkdir
      -p /go/src/github.com/Depado && cd /go/src/github.com/Depado     && git clone
      https://github.com/simonqbs/goploader.git && cd goploader/     && git checkout
      $GOPLOADER_VERSION     && go get -v ./...     && go get github.com/GeertJohan/go.rice     &&
      go get github.com/GeertJohan/go.rice/rice     && rice embed-go -i=./server     &&
      go build -o /goploader/server ./server     && chown -R goploader /goploader     &&
      apk del build.deps     && rm -rf /go
    Name: run
    PrependShell: true
  - Name: workdir
    Path: '"/goploader"'
  - Name: volume
    Volumes:
    - /goploader/data
    - /goploader/config
  - Name: expose
    Ports:
    - "8080"
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - entrypoint.sh
    - /
  - CmdLine:
    - /entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /goploader/server
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.3
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.3
