MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - CmdLine:
    - apk add --update-cache     python     python-dev     py-pip     build-base     bash     curl     git   &&
      pip install --upgrade pip   && pip install virtualenv   && rm -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
