MetaArgs: null
Stages:
- BaseName: cethy/alpine-asciidoctor-builder:latest
  Commands:
  - CmdLine:
    - mv /bin/entrypoint.sh /bin/build.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./entrypoint.sh
    - /bin/entrypoint.sh
  - CmdLine:
    - chmod +x /bin/entrypoint.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./app/*
    - /app/
  - Name: workdir
    Path: /app
  - CmdLine:
    - apk --update add --virtual build-dependencies build-base ruby-dev libffi-dev     &&
      gem install bundler --no-ri --no-rdoc     && bundle install --without development
      test     && apk del build-dependencies
    Name: run
    PrependShell: true
  From:
    Image: cethy/alpine-asciidoctor-builder:latest
  Name: ""
  Platform: ""
  SourceCode: FROM cethy/alpine-asciidoctor-builder:latest
