MetaArgs: null
Stages:
- BaseName: node:10
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /usr/src/
  - Name: workdir
    Path: /usr/src
  - CmdLine:
    - npm install
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - node
    - index.js
    Name: cmd
    PrependShell: false
  From:
    Image: node:10
  Name: ""
  Platform: ""
  SourceCode: FROM node:10
