MetaArgs: null
Stages:
- BaseName: alpine:3.9
  Commands:
  - Maintainer: webmaster@highskillz.com
    Name: maintainer
  - CmdLine:
    - apk add --update --no-cache haveged=1.9.4-r1
    Name: run
    PrependShell: true
  - CmdLine:
    - haveged
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - -F
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.9
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.9
