MetaArgs: null
Stages:
- BaseName: tutum/dind:latest
  Commands:
  - Maintainer: Huaming Rao <huaming.rao@gmail.com>
    Name: maintainer
  - CmdLine:
    - apt-get update -y &&     apt-get upgrade -y &&     apt-get install -y ca-certificates
      wget apt-transport-https vim nano
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/ubuntu/
      `lsb_release -cs` main" > /etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list
      &&     wget -q -O - https://packages.gitlab.com/gpg.key | apt-key add - &&     apt-get
      update -y &&     apt-get install -y gitlab-ci-multi-runner
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - entrypoint
    - /
  - CmdLine:
    - chmod +x /entrypoint
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - tutum-builder
    - /usr/bin/
  - CmdLine:
    - chmod +x /usr/bin/tutum-builder
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "Cmnd_Alias TUTUM_BUILD = /usr/bin/tutum-builder *" >> /etc/sudoers
    Name: run
    PrependShell: true
  - CmdLine:
    - 'echo "gitlab-runner ALL=NOPASSWD: TUTUM_BUILD" >> /etc/sudoers'
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /etc/gitlab-runner
    - /home/gitlab-runner
  - CmdLine:
    - /entrypoint
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - run
    - --user=gitlab-runner
    - --working-directory=/home/gitlab-runner
    Name: cmd
    PrependShell: false
  - CmdLine:
    - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  From:
    Image: tutum/dind:latest
  Name: ""
  Platform: ""
  SourceCode: FROM tutum/dind:latest
