MetaArgs: null
Stages:
- BaseName: owasp/zap2docker-stable:2.8.0
  Commands:
  - Name: user
    User: root
  - Env:
    - Key: HOME
      Value: /root/
    Name: env
  - CmdLine:
    - mv /home/zap/.ZAP /root/.ZAP &&     chown root:root -R /root/.ZAP
    Name: run
    PrependShell: true
  - CmdLine:
    - "apt-get update && apt-get install -q -y --fix-missing     libsaxonb-java &&
      \tapt-get clean &&     rm -rf /var/lib/apt/lists/*"
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/patros/zap2junit/raw/master/zap2junit.xsl
    - /zap2junit.xsl
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - scan.sh
    - zap2junit.xs[l]
    - /
  - CmdLine:
    - chmod +x /scan.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - patch_zap_junit.py
    - /
  - CmdLine:
    - /scan.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ""
    Name: cmd
    PrependShell: false
  From:
    Image: owasp/zap2docker-stable:2.8.0
  Name: ""
  Platform: ""
  SourceCode: FROM owasp/zap2docker-stable:2.8.0
