MetaArgs: null
Stages:
- BaseName: python:3
  Commands:
  - Env:
    - Key: PYTHONUNBUFFERED
      Value: "1"
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /tmp
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get --assume-yes install `cat apt-dependencies.txt | grep -v "#" | xargs`
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install -r https://raw.githubusercontent.com/CroceRossaItaliana/jorvik/master/requirements.txt
    Name: run
    PrependShell: true
  From:
    Image: python:3
  Name: ""
  Platform: ""
  SourceCode: FROM python:3
