MetaArgs: null
Stages:
- BaseName: ubuntu:16.04
  Commands:
  - Maintainer: Brandon B. Jozsa <bjozsa@jinkit.com>
    Name: maintainer
  - CmdLine:
    - apt-get --quiet update ;    apt-get --quiet upgrade -y ;    apt-get update &&
      apt-get install -y       git       python-pcapy       schedtool ;    apt-get
      clean ;    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone https://github.com/stamparm/maltrail.git ;    mkdir -p /var/log/maltrail/
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /maltrail
  - CmdLine:
    - '"/usr/bin/python server.py"'
    Name: cmd
    PrependShell: true
  - Name: expose
    Ports:
    - "8338"
  - CmdLine:
    - /usr/bin/python
    - /maltrail/sensor.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: ubuntu:16.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:16.04
