MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - /rootfs
    - /
  - Labels:
    - Key: vendor
      Value: '"Staudigl-Druck GmbH & Co. KG"'
    Name: label
  - Labels:
    - Key: maintainer
      Value: '"Matthias Pröll (matthias.proell@staudigl-druck.de)"'
    Name: label
  - Labels:
    - Key: release-date
      Value: '"2019-09-03"'
    Name: label
  - CmdLine:
    - "apk --update add openssl bash certbot git python python-dev py-pip gcc linux-headers
      libc-dev libffi-dev openssl-dev libxml2-dev libxslt-dev && \trm -rf /var/cache/apk/*"
    Name: run
    PrependShell: true
  - CmdLine:
    - pip install dns-lexicon[hetzner]
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod +x /authenticator.sh /run.sh /cleanup.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /certs
    Name: run
    PrependShell: true
  - CmdLine:
    - /bin/sh /run.sh && tail -f /dev/null
    Name: cmd
    PrependShell: true
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
