FROM phusion/baseimage:latest
MAINTAINER Alexandre Andrade <kaniabi@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

### TIMEZONE: Configure the docker-image timezone.
ENV TIMEZONE=America/Sao_Paulo
RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime  &&\
    echo ${TIMEZONE} > /etc/timezone

### Update and root password.
RUN echo "root:chucknorris" | chpasswd  &&\
    apt-get update


### PACKAGES-SYSTEM:
# * Install netstat to allow (jenkins) connection health check with: `netstat -tan | grep ESTABLISHED`
# * Install nodejs, fixing the executable on /usr/bin/node
RUN apt-get install -y net-tools curl sudo git default-jre python-dev python3-dev nodejs npm ruby-dev rubygems  &&\
    npm config set prefix /usr/local  &&\
    ln -s /usr/bin/nodejs /usr/bin/node  &&\
    curl -s https://bootstrap.pypa.io/get-pip.py > /tmp/get-pip.py  &&\
    python3 /tmp/get-pip.py  &&\
    pip3 install -U pip  &&\
    pip3 -q install virtualenvwrapper invoke colorama  &&\
    python2 /tmp/get-pip.py  &&\
    pip2 install -U pip  &&\
    pip2 -q install virtualenvwrapper invoke colorama  &&\
    rm /tmp/get-pip.py


### DOCKER ###
RUN apt-get install -y apt-transport-https ca-certificates  &&\
    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list  &&\
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D  &&\
    apt-get update &&\
    apt-get install -y docker-engine=1.11.2-0~xenial


### JENKINS-SLAVE ###
ENV JENKINS_SLAVE_HOME="/home/jenkins"
ENV JENKINS_SLAVE_PARAMS=""

# USER: jenkins-slave
RUN useradd -m jenkins-slave -c "Jenkins Slave User" -d $JENKINS_SLAVE_HOME  &&\
    echo "jenkins-slave:jenkins" | chpasswd  &&\
    adduser jenkins-slave sudo  &&\
    echo "jenkins-slave ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Getting rid of errors on Jenkins job output:
#   tput: No value for $TERM and no -T specified
ENV TERM vt100


# JNLP-CLIENT: Configure JAR file for jnlp-client
ARG JENKINS_JNLP_VERSION=3.2
RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${JENKINS_JNLP_VERSION}/remoting-${JENKINS_JNLP_VERSION}.jar \
  && chmod 755 /usr/share/jenkins \
  && chmod 644 /usr/share/jenkins/slave.jar

COPY jnlp-client.sh /usr/local/bin/jenkins-slave
ENTRYPOINT ["/usr/local/bin/jenkins-slave"]
