MetaArgs: null
Stages:
- BaseName: php:5.5
  Commands:
  - Maintainer: adityaii@gmail.com
    Name: maintainer
  - CmdLine:
    - git clone https://github.com/adityai/orangescrum
    Name: cmd
    PrependShell: true
  - CmdLine:
    - cd $HOME && ls -ltr && echo "Work in progress."
    Name: cmd
    PrependShell: true
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install libapache2-mod-php5 php5-cli php5-mysqlnd curl php5-curl php5-mcrypt
      cron -y
    Name: run
    PrependShell: true
  - CmdLine:
    - a2enmod php5
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: expose
    Ports:
    - "443"
  - CmdLine:
    - sed -i 's;memory_limit = .*;memory_limit = -1;' /etc/php5/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;memory_limit = .*;memory_limit = -1;' /etc/php5/cli/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;display_errors = .*;display_errors = Off;' /etc/php5/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;post_max_size = .*;post_max_size = 4000M;' /etc/php5/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;upload_max_filesize = .*;upload_max_filesize = 2000M;' /etc/php5/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;max_execution_time = .*;max_execution_time = 300;' /etc/php5/apache2/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;max_execution_time = .*;max_execution_time = 300;' /etc/php5/cli/php.ini
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's;max_input_time = .*;max_input_time = 300;' /etc/php5/apache2/php.ini
    Name: run
    PrependShell: true
  - Env:
    - Key: APACHE_RUN_USER
      Value: www-data
    Name: env
  - Env:
    - Key: APACHE_RUN_GROUP
      Value: www-data
    Name: env
  - Env:
    - Key: APACHE_LOG_DIR
      Value: /var/log/apache2
    Name: env
  - Env:
    - Key: APACHE_LOCK_DIR
      Value: /var/lock/apache2
    Name: env
  - Env:
    - Key: APACHE_PID_FILE
      Value: /var/run/apache2/apache2.pid
    Name: env
  - CmdLine:
    - a2enmod rewrite
    Name: run
    PrependShell: true
  - CmdLine:
    - php5enmod mcrypt
    Name: run
    PrependShell: true
  From:
    Image: php:5.5
  Name: ""
  Platform: ""
  SourceCode: FROM php:5.5
