MetaArgs: null
Stages:
- BaseName: node:10.16.0-alpine
  Commands:
  - CmdLine:
    - apk add --update --no-cache git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /src
  - Name: workdir
    Path: '"/src"'
  - CmdLine:
    - npm install --production
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - npm start
    Name: entrypoint
    PrependShell: true
  From:
    Image: node:10.16.0-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10.16.0-alpine
