MetaArgs: null
Stages:
- BaseName: alpine:latest
  Commands:
  - Maintainer: lambdalisue <lambdalisue@hashnote.net>
    Name: maintainer
  - Key: OPTIONS
    Name: arg
    Value: null
  - CmdLine:
    - apk add --no-cache --virtual build-deps     curl git make file libtermkey-dev
      libvterm-dev gettext-dev     libtool autoconf automake cmake g++ pkgconfig unzip  &&
      apk add --no-cache libtermkey libvterm libgcc diffutils gettext  && echo "Install
      official 'iconv'"  && curl -SL http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
      | tar -xz  && cd libiconv-1.15  && ./configure  && make  && make install  &&
      cd ../ && rm -rf libiconv-1.15  && echo "Install Neovim with $OPTIONS"  && git
      clone --depth 1 --single-branch $OPTIONS https://github.com/neovim/neovim  &&
      cd neovim  && git log -1  && make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DENABLE_JEMALLOC=OFF"  &&
      make install  && cd ../ && rm -rf neovim  && apk del build-deps
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /mnt/volume
  - Name: workdir
    Path: /mnt/volume
  - CmdLine:
    - /usr/local/bin/nvim
    Name: entrypoint
    PrependShell: false
  - CmdLine: []
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:latest
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:latest
