MetaArgs: null
Stages:
- As: installer
  BaseName: sethvargo/hashicorp-installer
  Commands:
  - CmdLine:
    - /install-hashicorp-tool "vault" "1.2.2"
    Name: run
    PrependShell: true
  From:
    Image: sethvargo/hashicorp-installer
  Name: installer
  Platform: ""
  SourceCode: FROM sethvargo/hashicorp-installer AS installer
- BaseName: google/cloud-sdk:latest
  Commands:
  - CmdLine:
    - apt-get install -y build-essential curl jq nano ca-certificates &&   rm -rf
      /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    Name: env
  - Chown: ""
    From: installer
    Name: copy
    SourcesAndDest:
    - /software/vault
    - /vault
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - rotator.sh
    - .
  - CmdLine:
    - chmod
    - +x
    - ./rotator.sh
    Name: run
    PrependShell: false
  - CmdLine:
    - ./rotator.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: google/cloud-sdk:latest
  Name: ""
  Platform: ""
  SourceCode: FROM google/cloud-sdk:latest
