MetaArgs: null
Stages:
- BaseName: mesosphere/mesos-slave:1.1.1
  Commands:
  - Maintainer: Patrick Kleindienst <patrick.kleindienst@web.de>
    Name: maintainer
  - Key: AURORA_VERSION
    Name: arg
    Value: 0.17.0
  - Env:
    - Key: USER
      Value: aurora
    Name: env
  - Env:
    - Key: HOME
      Value: /home/aurora
    Name: env
  - CmdLine:
    - apt-get update &&     apt-get install -y python2.7 wget libcurl4-nss-dev
    Name: run
    PrependShell: true
  - CmdLine:
    - wget -c https://apache.bintray.com/aurora/ubuntu-trusty/aurora-executor_${AURORA_VERSION}_amd64.deb
      &&     dpkg -i aurora-executor_${AURORA_VERSION}_amd64.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd $USER --create-home --shell /bin/bash &&     usermod -aG docker $USER
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - thermos.sh
    - /home/$USER/thermos.sh
  - CmdLine:
    - chown $USER:$USER /home/$USER/thermos.sh &&     chmod 500 /home/$USER/thermos.sh
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /home/$USER
  - CmdLine:
    - ./thermos.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: mesosphere/mesos-slave:1.1.1
  Name: ""
  Platform: ""
  SourceCode: FROM mesosphere/mesos-slave:1.1.1
