MetaArgs: null
Stages:
- BaseName: dankempster/composer:base
  Commands:
  - Maintainer: dev@dankempster.co.uk
    Name: maintainer
  - Env:
    - Key: XDEBUG_VERSION
      Value: 2.5.0
    Name: env
  - Env:
    - Key: XDEBUG_SHA1
      Value: 0d31602a6ee2ba6d2e18a6db79bdb9a2a706bcd9
    Name: env
  - CmdLine:
    - set -x     && curl -o xdebug.tgz "https://xdebug.org/files/xdebug-$XDEBUG_VERSION.tgz"     &&
      echo "$XDEBUG_SHA1  xdebug.tgz" | sha1sum -c -     && mkdir -p /usr/src/xdebug     &&
      tar -xf xdebug.tgz -C /usr/src/xdebug --strip-components=1     && rm xdebug.*     &&
      cd /usr/src/xdebug     && phpize     && ./configure     && make -j"$(nproc)"     &&
      make install     && make clean     && docker-php-ext-enable xdebug     && cd
      -     && rm -fr /usr/src/xdebug
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/*.ini
    - /usr/local/etc/php/conf.d/
  From:
    Image: dankempster/composer:base
  Name: ""
  Platform: ""
  SourceCode: FROM dankempster/composer:base
