MetaArgs: null
Stages:
- BaseName: debian:stable-slim
  Commands: null
  From:
    Image: debian:stable-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:stable-slim
- BaseName: i386/debian:stretch-slim
  Commands:
  - Maintainer: skylord123
    Name: maintainer
  - CmdLine:
    - dpkg --add-architecture i386 &&     apt-get update && apt-get install --no-install-recommends
      -y         wget curl ca-certificates libgcc1 libstdc++6 libssl1.1:i386 libstdc++6:i386
      locales locales-all zlib1g:i386 libc6 libstdc++6 ca-certificates libgcc1 libstdc++6:i386
      zlib1g:i386 curl file bzip2 gzip unzip libssl1.1:i386 libxrandr-dev:i386 libxi-dev:i386
      libgl1-mesa-glx:i386 libxtst6:i386 libusb-1.0.0:i386 libxxf86vm1:i386 libglu1-mesa:i386
      libopenal1:i386 libgtk2.0-0:i386 libsm6:i386 libdbus-glib-1-2:i386 libnm-glib4:i386
      libnm-util2:i386 libudev-dev:i386 libudev-dev libpulse0 &&     apt-get clean
      &&     echo "LC_ALL=en_US.UTF-8" >> /etc/environment &&     rm -rf /tmp/* /var/lib/apt/lists/*
      /var/tmp/* &&     ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
    Name: run
    PrependShell: true
  - Env:
    - Key: LANG
      Value: en_US.UTF-8
    - Key: LANGUAGE
      Value: en_US.UTF-8
    - Key: LC_ALL
      Value: en_US.UTF-8
    Name: env
  - Env:
    - Key: DATA_DIR
      Value: '"/serverdata"'
    Name: env
  - Env:
    - Key: STEAMCMD_DIR
      Value: '"${DATA_DIR}/steamcmd"'
    Name: env
  - Env:
    - Key: SERVER_DIR
      Value: '"${DATA_DIR}/serverfiles"'
    Name: env
  - Env:
    - Key: GAME_ID
      Value: '"276060"'
    Name: env
  - Env:
    - Key: GAME_NAME
      Value: '"svencoop"'
    Name: env
  - Env:
    - Key: GAME_PARAMS
      Value: '"template"'
    Name: env
  - Env:
    - Key: GAME_PORT
      Value: "27015"
    Name: env
  - Env:
    - Key: VALIDATE
      Value: '""'
    Name: env
  - Env:
    - Key: UID
      Value: "99"
    Name: env
  - Env:
    - Key: GID
      Value: "100"
    Name: env
  - Env:
    - Key: USERNAME
      Value: '""'
    Name: env
  - Env:
    - Key: PASSWRD
      Value: '""'
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - /scripts/
    - /opt/scripts/
  - CmdLine:
    - mkdir $DATA_DIR &&     mkdir $STEAMCMD_DIR &&     mkdir $SERVER_DIR &&     useradd
      -d $DATA_DIR -s /bin/bash --uid $UID --gid $GID steam &&     chown -R steam
      $DATA_DIR &&     ulimit -n 2048 &&     chmod -R 770 /opt/scripts/ &&     chown
      -R steam /opt/scripts
    Name: run
    PrependShell: true
  - Name: user
    User: steam
  - CmdLine:
    - /opt/scripts/start-server.sh
    Name: entrypoint
    PrependShell: false
  From:
    Image: i386/debian:stretch-slim
  Name: ""
  Platform: ""
  SourceCode: FROM i386/debian:stretch-slim
