MetaArgs: null
Stages:
- BaseName: python:alpine
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - /
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "5000"
  - CmdLine:
    - mkdir app
    Name: run
    PrependShell: true
  - Name: workdir
    Path: app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - '*.py'
    - ./
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - help.md
    - ./
  - CmdLine:
    - python
    - run.py
    Name: entrypoint
    PrependShell: false
  From:
    Image: python:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:alpine
