MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Ralph Soika <ralph.soika@imixs.com>
    Name: maintainer
  - CmdLine:
    - apt-get update  && apt-get install --no-install-recommends -y   exim4-daemon-light
      mailutils xtail vim  && apt-get clean  && rm -rf /var/lib/apt/lists/* /tmp/*
      /var/tmp/* /usr/share/man/?? /usr/share/man/??_*
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - start.sh
    - /exim_start
  - CmdLine:
    - chmod +x /exim_start
    Name: run
    PrependShell: true
  - Env:
    - Key: EXIM_LOCALINTERFACE
      Value: 0.0.0.0
    Name: env
  - Env:
    - Key: EXIM_ALLOWED_SENDERS
      Value: 10.0.0.0/8:172.16.0.0/12:127.0.0.1:192.168.0.0/16
    Name: env
  - CmdLine:
    - /exim_start
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
