MetaArgs: null
Stages:
- As: build
  BaseName: golang:1.12
  Commands:
  - Env:
    - Key: CGO_ENABLED
      Value: "0"
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - /go/src/github.com/m-lab/pusher
  - Name: workdir
    Path: /go/src/github.com/m-lab/pusher
  - CmdLine:
    - go get       -v       -ldflags "-X github.com/m-lab/go/prometheusx.GitShortCommit=$(git
      log -1 --format=%h)"       github.com/m-lab/pusher
    Name: run
    PrependShell: true
  From:
    Image: golang:1.12
  Name: build
  Platform: ""
  SourceCode: FROM golang:1.12 as build
- BaseName: alpine:3.7
  Commands:
  - CmdLine:
    - apk add --no-cache ca-certificates
    Name: run
    PrependShell: true
  - Chown: ""
    From: build
    Name: copy
    SourcesAndDest:
    - /go/bin/pusher
    - /
  - Name: workdir
    Path: /
  - CmdLine:
    - /pusher
    Name: entrypoint
    PrependShell: false
  From:
    Image: alpine:3.7
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.7
