MetaArgs: null
Stages:
- BaseName: logankoester/archlinux
  Commands:
  - Maintainer: Vincent Ambo <tazjin@gmail.com>
    Name: maintainer
  - Chown: ""
    Name: add
    SourcesAndDest:
    - mirrorlist
    - /etc/pacman.d/mirrorlist
  - CmdLine:
    - pacman -Sy --noconfirm &&     pacman -S archlinux-keyring --noconfirm &&     pacman
      -Su --noconfirm
    Name: run
    PrependShell: true
  - CmdLine:
    - pacman -S --noconfirm base-devel sudo
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /build
  - Name: workdir
    Path: /build
  - Chown: ""
    Name: add
    SourcesAndDest:
    - sudoers
    - /etc/sudoers
  - CmdLine:
    - useradd -d /build -G wheel build &&     chmod 0400 /etc/sudoers
    Name: run
    PrependShell: true
  - Name: user
    User: build
  - CmdLine:
    - 'sudo chown build: /build &&            /usr/bin/makepkg -sfc --noconfirm --needed'
    Name: entrypoint
    PrependShell: true
  From:
    Image: logankoester/archlinux
  Name: ""
  Platform: ""
  SourceCode: FROM logankoester/archlinux
