MetaArgs: null
Stages:
- BaseName: neocxi/rllab_exp_gpu_tf:py3
  Commands:
  - CmdLine:
    - bash -c 'source activate rllab3 && conda install -y nomkl && conda uninstall
      -y scipy && conda install -y scipy'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - .
    - /root/code/rllab
  - Name: workdir
    Path: /root/code/rllab
  From:
    Image: neocxi/rllab_exp_gpu_tf:py3
  Name: ""
  Platform: ""
  SourceCode: FROM neocxi/rllab_exp_gpu_tf:py3
