MetaArgs: null
Stages:
- BaseName: ubuntu:vivid
  Commands:
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -yq --force-yes znc znc-dev znc-dbg znc-dev
      znc-perl znc-python znc-tcl make git && apt-get install -yq --force-yes libotr5-dev
      && apt-get autoremove -yq && apt-get clean
    Name: run
    PrependShell: true
  - CmdLine:
    - useradd znc
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - run
    - /znc-run
  - CmdLine:
    - chmod +x /znc-run
    Name: run
    PrependShell: true
  - CmdLine:
    - /znc-run
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:vivid
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:vivid
