MetaArgs: null
Stages:
- BaseName: frolvlad/alpine-glibc
  Commands:
  - Maintainer: Gernot Grames <gernot.grames@gmx.at>
    Name: maintainer
  - Env:
    - Key: container
      Value: docker
    Name: env
  - Env:
    - Key: UPDATED_ON
      Value: '"04 April 2018"'
    Name: env
  - Env:
    - Key: TWONKY_VERSION
      Value: "8.5"
    Name: env
  - Env:
    - Key: TWONKY_PORT
      Value: '9000 #fix'
    Name: env
  - CmdLine:
    - apk add --update bash wget unzip supervisor
    Name: run
    PrependShell: true
  - CmdLine:
    - wget http://download.twonky.com/$TWONKY_VERSION/twonky-i686-glibc-2.9-$TWONKY_VERSION.zip
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /usr/local/twonky
    Name: run
    PrependShell: true
  - CmdLine:
    - unzip twonky-i686-glibc-2.9-"${TWONKY_VERSION}".zip -d /usr/local/twonky
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 705 /usr/local/twonky/twonky* /usr/local/twonky/cgi-bin/* /usr/local/twonky/plugins/*
    Name: run
    PrependShell: true
  - CmdLine:
    - chmod 757 -R /var/run
    Name: run
    PrependShell: true
  - CmdLine:
    - adduser -h /home/twonky -s /bin/sh -D twonky
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir /home/twonky/media
    Name: run
    PrependShell: true
  - CmdLine:
    - chown -R twonky:twonky /home/twonky/media
    Name: run
    PrependShell: true
  - CmdLine:
    - su twonky -c "mkdir -p /home/twonky/.twonky"
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/\"$TWONKYSRV\"/su twonky -c \"$TWONKYSRV\"/g' /usr/local/twonky/twonky.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - sed -i 's/--no-headers//g' /usr/local/twonky/twonky.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apk del wget
    Name: run
    PrependShell: true
  - CmdLine:
    - apk del unzip
    Name: run
    PrependShell: true
  - CmdLine:
    - rm twonky-i686-glibc-2.9-$TWONKY_VERSION.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - supervisord.conf
    - /etc/supervisor/conf.d/supervisord.conf
  - Name: expose
    Ports:
    - "9000"
  - CmdLine:
    - /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    Name: cmd
    PrependShell: true
  From:
    Image: frolvlad/alpine-glibc
  Name: ""
  Platform: ""
  SourceCode: FROM frolvlad/alpine-glibc
