MetaArgs: null
Stages:
- As: builder
  BaseName: golang:1.13.5
  Commands:
  - Name: workdir
    Path: /build
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Makefile
    - .
  - CmdLine:
    - make setup
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - .
    - .
  - CmdLine:
    - make build-docker
    Name: run
    PrependShell: true
  From:
    Image: golang:1.13.5
  Name: builder
  Platform: ""
  SourceCode: FROM golang:1.13.5 as builder
- BaseName: busybox:1.31-glibc
  Commands:
  - Name: workdir
    Path: /
  - Chown: ""
    From: builder
    Name: copy
    SourcesAndDest:
    - /build/ahs
    - /usr/local/bin/
  - CmdLine:
    - /usr/local/bin/ahs
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - ""
    Name: cmd
    PrependShell: false
  From:
    Image: busybox:1.31-glibc
  Name: ""
  Platform: ""
  SourceCode: FROM busybox:1.31-glibc
