MetaArgs: null
Stages:
- BaseName: andrius/alpine-ruby:latest
  Commands:
  - Maintainer: Andrius Kairiukstis <andrius@kairiukstis.com>
    Name: maintainer
  - CmdLine:
    - apk add --update build-base ruby-dev && gem install --no-rdoc --no-ri json tugboat
      && apk del build-base ruby-dev && rm -rf /usr/lib/ruby/gems/*/cache/* && rm
      -rf /var/cache/apk/*
    Name: run
    PrependShell: true
  - CmdLine:
    - tugboat
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - --help
    Name: cmd
    PrependShell: false
  From:
    Image: andrius/alpine-ruby:latest
  Name: ""
  Platform: ""
  SourceCode: FROM andrius/alpine-ruby:latest
