MetaArgs: null
Stages:
- BaseName: python:alpine
  Commands:
  - Name: workdir
    Path: /app
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - requirements.txt
    - .
  - CmdLine:
    - pip install -r requirements.txt
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - main.py
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - feeder.py
    - .
  - CmdLine:
    - python main.py
    Name: entrypoint
    PrependShell: true
  From:
    Image: python:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM python:alpine
