MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - Env:
    - Key: ANDROID_SDK_VERSION
      Value: "4333796"
    Name: env
  - Env:
    - Key: PLATFORM_VERSION
      Value: "28"
    Name: env
  - Env:
    - Key: BUILD_TOOLS_VERSION
      Value: 28.0.3
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get -qq update   && apt-get -qq install -y --no-install-recommends       software-properties-common       unzip       wget       zip       xxd   &&
      apt-add-repository ppa:openjdk-r/ppa   && apt-get -qq update   && apt-get -qq
      install -y openjdk-8-jdk       -o Dpkg::Options::="--force-overwrite"   && apt-get
      -qq autoremove -y   && apt-get -qq clean   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_SDK_VERSION.zip
      -q   && mkdir /usr/local/android   && unzip -q sdk-tools-linux-$ANDROID_SDK_VERSION.zip
      -d /usr/local/android   && rm sdk-tools-linux-$ANDROID_SDK_VERSION.zip
    Name: run
    PrependShell: true
  - Env:
    - Key: JAVA_HOME
      Value: /usr/lib/jvm/java-8-openjdk-amd64
    Name: env
  - Env:
    - Key: ANDROID_HOME
      Value: /usr/local/android
    Name: env
  - Env:
    - Key: ANDROID_SDK_HOME
      Value: $ANDROID_HOME
    Name: env
  - Env:
    - Key: ANDROID_NDK_HOME
      Value: $ANDROID_HOME/ndk-bundle
    Name: env
  - Env:
    - Key: PATH
      Value: $ANDROID_HOME/tools/bin:$ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION:$PATH
    Name: env
  - CmdLine:
    - echo "y" | sdkmanager   "ndk-bundle"   "lldb;3.1"   "cmake;3.6.4111459"   "extras;google;m2repository"   "platform-tools"   "platforms;android-$PLATFORM_VERSION"   "build-tools;$BUILD_TOOLS_VERSION"
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - release
    - /usr/local/bin/release
  - Env:
    - Key: SRC
      Value: /src
    Name: env
  - CmdLine:
    - mkdir $SRC
    Name: run
    PrependShell: true
  - Name: workdir
    Path: $SRC
  - CmdLine:
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    Name: run
    PrependShell: true
  - CmdLine:
    - echo "ndk.dir=$ANDROID_HOME" > local.properties
    Name: run
    PrependShell: true
  - CmdLine:
    - ./gradlew
    - build
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
