MetaArgs: null
Stages:
- BaseName: openjdk:alpine
  Commands:
  - Maintainer: Jin Van <usconan@gmail.com>
    Name: maintainer
  - Env:
    - Key: SERVER_PORT
      Value: "25565"
    Name: env
  - Name: workdir
    Path: /minecraft
  - Name: user
    User: root
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./settings-local.sh
    - /minecraft/cfg/settings-local.sh
  - CmdLine:
    - adduser -D minecraft &&     apk --no-cache add curl wget &&     mkdir -p /minecraft/world
      &&     mkdir -p /minecraft/cfg &&     mkdir -p /minecraft/backups &&    curl
      -SLO http://ftb.cursecdn.com/FTB2/modpacks/FTBPresentsSkyfactory3/3_0_15/FTBPresentsSkyfactory3Server.zip  &&     unzip
      FTBPresentsSkyfactory3Server.zip &&     chmod u+x *.sh &&     echo "eula=true"
      > /minecraft/eula.txt &&     echo "[]" > /minecraft/cfg/ops.json &&     echo
      "[]" > /minecraft/cfg/whitelist.json &&     echo "[]" > /minecraft/cfg/banned-ips.json
      &&     echo "[]" > /minecraft/cfg/banned-players.json &&     echo "[]" > /minecraft/cfg/server.properties
      &&     ln -s /minecraft/cfg/ops.json /minecraft/ops.json &&     ln -s /minecraft/cfg/whitelist.json
      /minecraft/whitelist.json &&     ln -s /minecraft/cfg/banned-ips.json /minecraft/banned-ips.json
      &&     ln -s /minecraft/cfg/banned-players.json /minecraft/banned-players.json
      &&     ln -s /minecraft/cfg/server.properties /minecraft/server.properties &&     ln
      -s /minecraft/cfg/settings-local.sh /minecraft/settings-local.sh &&     chown
      -R minecraft:minecraft /minecraft
    Name: run
    PrependShell: true
  - Name: user
    User: minecraft
  - CmdLine:
    - /minecraft/FTBInstall.sh
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /minecraft/world
  - Name: volume
    Volumes:
    - /minecraft/cfg
  - Name: volume
    Volumes:
    - /minecraft/backups
  - Name: expose
    Ports:
    - ${SERVER_PORT}
  - CmdLine:
    - /bin/sh
    - /minecraft/ServerStart.sh
    Name: cmd
    PrependShell: false
  From:
    Image: openjdk:alpine
  Name: ""
  Platform: ""
  SourceCode: FROM openjdk:alpine
