MetaArgs: null
Stages:
- BaseName: java:8
  Commands:
  - Maintainer: Eliot Kimber "ekimber@contrext.com"
    Name: maintainer
  - Name: workdir
    Path: /usr/share/fonts/opentype/noto
  - CmdLine:
    - wget -O Noto-unhinted.zip -c https://noto-website.storage.googleapis.com/pkgs/Noto-unhinted.zip
      &&   unzip Noto-unhinted.zip &&   rm Noto-unhinted.zip
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - fop
    - /opt/fop
  - Name: volume
    Volumes:
    - /usr/share/fonts
  - Name: volume
    Volumes:
    - /opt/fop
  From:
    Image: java:8
  Name: ""
  Platform: ""
  SourceCode: FROM java:8
