MetaArgs: null
Stages:
- BaseName: debian:buster-slim
  Commands:
  - Env:
    - Key: BAZEL_VERSION
      Value: 0.24.0
    Name: env
  - Env:
    - Key: PATH
      Value: '"/root/bin:${PATH}"'
    Name: env
  - Name: workdir
    Path: /tmp/bazel
  - CmdLine:
    - apt update     && apt install -y curl zip     && curl --silent --location "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
      --output bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh      && chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh     &&  ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
      --user     && rm ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
    Name: run
    PrependShell: true
  - CmdLine:
    - apt install -y git make g++ python
    Name: run
    PrependShell: true
  From:
    Image: debian:buster-slim
  Name: ""
  Platform: ""
  SourceCode: FROM debian:buster-slim
