MetaArgs: null
Stages:
- BaseName: qnib/java7
  Commands:
  - CmdLine:
    - useradd hadoop
    Name: run
    PrependShell: true
  - Env:
    - Key: HADOOP_VER
      Value: 2.5.2
    - Key: SCALA_VER
      Value: 2.10.4
    - Key: SAMZA_BASE_VER
      Value: "2.10"
    - Key: SLF4J_VER
      Value: 1.0.1
    - Key: SAMZA_VER
      Value: 0.8.0
    - Key: HDFS_LIB_DIR
      Value: /opt/hadoop/share/hadoop/hdfs/lib
    - Key: HDFS_URL
      Value: http://search.maven.org/remotecontent
    Name: env
  - CmdLine:
    - curl -fsL http://apache.claz.org/hadoop/common/hadoop-${HADOOP_VER}/hadoop-${HADOOP_VER}.tar.gz
      | tar xzf - -C /opt && mv /opt/hadoop-${HADOOP_VER} /opt/hadoop
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/hadoop/etc/hadoop/*
    - /opt/hadoop/etc/hadoop/
  - CmdLine:
    - yum install -y openssh-server
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/consul.d/check_sshd.json
    - /etc/consul.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/qnib/bin/startup_sshd.sh
    - /opt/qnib/bin/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/bashrc.hadoop
    - /etc/bashrc.hadoop
  - CmdLine:
    - echo "source /etc/bashrc.hadoop" >> /etc/bashrc
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data/hadoopdata/hdfs
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/qnib/hadoop/bin/
    - /opt/qnib/hadoop/bin/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/supervisord.d/hdfs.ini
    - etc/supervisord.d/sshd.ini
    - etc/supervisord.d/yarn.ini
    - /etc/supervisord.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/consul.d/check_hdfs.json
    - etc/consul.d/check_sshd.json
    - etc/consul.d/check_yarn.json
    - /etc/consul.d/
  - CmdLine:
    - yum install -y bsdtar maven
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p ${HADOOP_YARN_HOME}/share/hadoop/hdfs/lib &&     curl -fsL http://www.scala-lang.org/files/archive/scala-${SCALA_VER}.tgz
      |tar xzf - -C /opt/ &&     cp /opt/scala-${SCALA_VER}/lib/{scala-compiler.jar,scala-library.jar}
      /opt/hadoop/share/hadoop/hdfs/lib/ &&     rm -rf /opt/scala-${SCALA_VER}
    Name: run
    PrependShell: true
  - CmdLine:
    - curl -sLo ${HDFS_LIB_DIR}/grizzled-slf4j_${SAMZA_BASE_VER}-${SLF4J_VER}.jar
      ${HDFS_URL}?filepath=org/clapper/grizzled-slf4j_${SAMZA_BASE_VER}/${SLF4J_VER}/grizzled-slf4j_${SAMZA_BASE_VER}-${SLF4J_VER}.jar
      &&     curl -sLo ${HDFS_LIB_DIR}/samza-yarn_${SAMZA_BASE_VER}-${SAMZA_VER}.jar
      ${HDFS_URL}?filepath=org/apache/samza/samza-yarn_${SAMZA_BASE_VER}/${SAMZA_VER}/samza-yarn_${SAMZA_BASE_VER}-${SAMZA_VER}.jar
      &&     curl -sLo ${HDFS_LIB_DIR}/samza-core_${SAMZA_BASE_VER}-${SAMZA_VER}.jar
      ${HDFS_URL}?filepath=org/apache/samza/samza-core_${SAMZA_BASE_VER}/${SAMZA_VER}/samza-core_${SAMZA_BASE_VER}-${SAMZA_VER}.jar
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/hadoop/etc/hadoop/core-site.xml
    - /opt/hadoop/etc/hadoop/
  - Name: volume
    Volumes:
    - /tmp/zookeeper
  - Env:
    - Key: ZK_VER
      Value: 3.4.6
    Name: env
  - CmdLine:
    - curl -fsL http://apache.mirror.digitalpacific.com.au/zookeeper/zookeeper-${ZK_VER}/zookeeper-${ZK_VER}.tar.gz
      | tar xzf - -C /opt && mv /opt/zookeeper-${ZK_VER} /opt/zookeeper
    Name: run
    PrependShell: true
  - CmdLine:
    - yum install -y bc jq
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/supervisord.d/zookeeper*.ini
    - /etc/supervisord.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/qnib/zookeeper/bin/*.sh
    - /opt/qnib/zookeeper/bin/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/consul.d/zookeeper.json
    - /etc/consul.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/zookeeper/conf/zoo.cfg
    - /opt/zookeeper/conf/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/consul-templates/zoo.cfg.ctmpl
    - etc/consul-templates/zoo.myid.ctmpl
    - /etc/consul-templates/
  - Env:
    - Key: PATH
      Value: /opt/zookeeper/bin:${PATH}
    Name: env
  - CmdLine:
    - echo "tail -f /var/log/supervisor/zookeeper.log" >> /root/.bash_history &&     echo
      "cat /opt/zookeeper/conf/zoo.cfg" >> /root/.bash_history
    Name: run
    PrependShell: true
  - Env:
    - Key: KAFKA_VER
      Value: 0.8.2.1
    - Key: API_VER
      Value: "2.11"
    Name: env
  - CmdLine:
    - curl -fLs http://apache.mirrors.pair.com/kafka/${KAFKA_VER}/kafka_${API_VER}-${KAFKA_VER}.tgz
      | tar xzf - -C /opt && mv /opt/kafka_${API_VER}-${KAFKA_VER} /opt/kafka/
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/supervisord.d/kafka*.ini
    - /etc/supervisord.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/kafka/config/server.properties
    - /opt/kafka/config/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/qnib/kafka/bin/*.sh
    - /opt/qnib/kafka/bin/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/consul.d/kafka.json
    - /etc/consul.d/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - etc/consul-templates/kafka.server.properties.ctmpl
    - /etc/consul-templates/
  - CmdLine:
    - echo "/opt/kafka/bin/kafka-console-consumer.sh --zookeeper zookeeper.service.consul:2181
      --topic syslog" >> /root/.bash_history &&     echo "/opt/kafka/bin/kafka-topics.sh
      --zookeeper zookeeper.service.consul:2181 --replication-factor 3 --partitions
      1 --create --topic ring0" >> /root/.bash_history &&     echo "/opt/kafka/bin/kafka-run-class.sh
      kafka.admin.TopicCommand --zookeeper zookeeper.service.consul:2181 --topic ring0
      --describe" >> /root/.bash_history &&     echo "/opt/kafka/bin/kafka-console-producer.sh
      --broker-list localhost:9092 --topic ring0" >> /root/.bash_history &&     echo
      "/opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper.service.consul:2181 --describe
      --topic \$(/opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper.service.consul:2181
      --list|xargs|sed -e 's/ /,/g')" >> /root/.bash_history
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/qnib/consul/etc/bash_functions
    - /opt/qnib/consul/etc/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - opt/qnib/kafka/bin/show_topics.py
    - /opt/qnib/kafka/bin/
  - CmdLine:
    - yum install -y git-core
    Name: run
    PrependShell: true
  - CmdLine:
    - git clone http://git-wip-us.apache.org/repos/asf/samza.git /opt/samza &&     cd
      /opt/samza &&     ./gradlew  publishToMavenLocal
    Name: run
    PrependShell: true
  - CmdLine:
    - 'chown hadoop: /opt/'
    Name: run
    PrependShell: true
  - Name: user
    User: hadoop
  - CmdLine:
    - ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa &&     cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
      &&     chmod 0600 ~/.ssh/authorized_keys
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - ssh/config
    - /home/hadoop/.ssh/config
  - CmdLine:
    - curl -sfL https://github.com/apache/samza-hello-samza/archive/master.zip |bsdtar
      xf - -C /opt/ &&     mv /opt/samza-hello-samza-master /opt/hello-samza/ &&     cd
      /opt/hello-samza &&     mvn clean package
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /opt/hello-samza/deploy/samza/ &&     tar xzf /opt/hello-samza/target/hello-samza-0.10.0-dist.tar.gz
      -C /opt/hello-samza/deploy/samza/
    Name: run
    PrependShell: true
  - Name: user
    User: root
  From:
    Image: qnib/java7
  Name: ""
  Platform: ""
  SourceCode: FROM qnib/java7
