MetaArgs: null
Stages:
- BaseName: ubuntu:18.04
  Commands:
  - CmdLine:
    - dpkg --add-architecture i386   && apt-get update   && apt-get install -y     apt-transport-https     ca-certificates     curl     gnupg     python3     python3-pip     software-properties-common     wget   &&
      pip3 install awscli   && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc
      2>/dev/null | apt-key add -   && apt-add-repository 'deb https://apt.kitware.com/ubuntu/
      bionic main'   && curl -sL https://deb.nodesource.com/setup_12.x | bash -   &&
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash   &&
      apt-get update   && apt-get install -y     nodejs   && npm install -g yarn pnpm   &&
      apt-get install -y     autoconf     automake     bc     binutils     bzip2     cmake     cpio     coreutils     default-jdk     device-tree-compiler     elfutils     fftw3-dev     file     g++     g++-multilib     gawk     gcc     gcc-multilib     gdb     gettext     git     golang     gosu     gzip     libasound2-dev     libavahi-compat-libdnssd-dev     libboost-all-dev     libboost-dev:i386     libboost-program-options-dev:i386     libc6-dev     libssl-dev     libtool     libwebsocketpp-dev     locales-all     lzop     make     ncurses-dev     patch     perl     python     python-dev     openssh-client     rsync     scons     sed     shellcheck     subversion     swig     tar     unzip     uuid-dev     vim     zip     zlib1g-dev     zlib1g-dev:i386   &&
      apt-get clean   && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Env:
    - Key: LC_ALL
      Value: C.UTF-8
    Name: env
  - Env:
    - Key: LANG
      Value: C.UTF-8
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - patch
    - /
  - CmdLine:
    - /docker-entrypoint.sh
    Name: entrypoint
    PrependShell: false
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:18.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:18.04
