MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Alejandro Lazaro <virtualroot@gmail.com>
    Name: maintainer
  - Env:
    - Key: GAME_TYPE
      Value: ctf
    Name: env
  - CmdLine:
    - apt-get update  && apt-get install -y teeworlds-server pwgen  && apt-get clean
      all
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - run.sh
    - /run.sh
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - dm.cfg
    - /dm.cfg
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - tdm.cfg
    - /tdm.cfg
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ctf.cfg
    - /ctf.cfg
  - CmdLine:
    - chmod +x /run.sh
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - 8303/udp
  - CmdLine:
    - /run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
