MetaArgs: null
Stages:
- BaseName: ubuntu-upstart:14.04
  Commands:
  - Maintainer: likol@likol.idv.tw
    Name: maintainer
  - Env:
    - Key: TERM
      Value: xterm
    Name: env
  - CmdLine:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C300EE8C && echo "deb
      http://ppa.launchpad.net/nginx/stable/ubuntu trusty main" > /etc/apt/sources.list.d/nginx-stable.list
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update && apt-get install -y nginx libcurl4-openssl-dev libmcrypt-dev
      libxml2-dev libjpeg-dev libjpeg62 libfreetype6-dev libmysqlclient-dev libt1-dev
      libgmp-dev libpspell-dev libicu-dev librecode-dev
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - http://repos.zend.com/zend-server/early-access/php7/php-7.0-latest-DEB-x86_64.tar.gz
    - /usr/local/php7
  - CmdLine:
    - tar zxPf /usr/local/php7
    Name: run
    PrependShell: true
  - CmdLine:
    - echo 'export PATH="$PATH:/usr/local/php7/bin"' >> /etc/bash.bashrc
    Name: run
    PrependShell: true
  - CmdLine:
    - ln -s /usr/local/php7/bin/php /usr/bin
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/conf/etc
    - /usr/local/php7/etc
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/conf/default
    - /etc/nginx/sites-available/default
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/conf/upstart-conf/php7-fpm.conf
    - /etc/init/php7-fpm.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/conf/upstart-conf/nginx.conf
    - /etc/init/nginx.conf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/www/index.php
    - /var/www/html/index.php
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - assets/php7-upgrade
    - /usr/bin/php7-upgrade
  - CmdLine:
    - chmod 0755 -R /usr/local/php7/bin && chmod 0755 -R /usr/local/php7/sbin && chmod
      0755 /usr/bin/php7-upgrade && apt-get autoremove -y && apt-get autoclean &&
      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - Name: volume
    Volumes:
    - /var/www/html
  - CmdLine:
    - /sbin/init
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu-upstart:14.04
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu-upstart:14.04
