MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - CmdLine:
    - apt-get update &&     apt-get install -y curl git
    Name: run
    PrependShell: true
  - Key: TALISMAN_VERSION
    Name: arg
    Value: '"0.4.6"'
  - CmdLine:
    - curl -L "https://github.com/thoughtworks/talisman/releases/download/v${TALISMAN_VERSION}/talisman_linux_amd64"
      > /usr/bin/talisman &&     chmod +x /usr/bin/talisman
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /usr/src
  - CmdLine:
    - /bin/bash
    - -c
    - talisman --version
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
