MetaArgs: null
Stages:
- BaseName: debian
  Commands:
  - Maintainer: Marcel Grossmann <whatever4711@gmail.com>
    Name: maintainer
  - Labels:
    - Key: architecture
      Value: '"amd64"'
    Name: label
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - Env:
    - Key: MININET_REPO
      Value: git://github.com/mininet/mininet
    Name: env
  - Env:
    - Key: MININET_INSTALLER
      Value: ./mininet/util/install.sh
    Name: env
  - Env:
    - Key: INSTALLER_SWITCHES
      Value: -fbinptvwyx
    Name: env
  - Name: workdir
    Path: /tmp
  - CmdLine:
    - apt-get update         --quiet     && apt-get install         --yes         --no-install-recommends         --no-install-suggests     autoconf     automake     ca-certificates     git     curl     libtool     net-tools     openssh-client     patch     vim     dnsutils
    Name: run
    PrependShell: true
  - CmdLine:
    - "git clone -b 2.2.2 $MININET_REPO     && sed -e 's/sudo //g'         -e 's/DEBIAN_FRONTEND=noninteractive
      //g'     \t-e 's/~\\//\\//g'     \t-e 's/\\(apt-get -y install\\)/\\1 --no-install-recommends
      --no-install-suggests/g'     \t-i $MININET_INSTALLER     && touch /.bashrc     &&
      chmod +x $MININET_INSTALLER"
    Name: run
    PrependShell: true
  - CmdLine:
    - ./$MININET_INSTALLER -nfv     && rm -rf /tmp/mininet               /tmp/openflow     &&
      apt-get clean     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - docker-entry-point
    - /docker-entry-point
  - CmdLine:
    - chmod 755 /docker-entry-point
    Name: run
    PrependShell: true
  - Name: volume
    Volumes:
    - /data
  - Name: workdir
    Path: /data
  - CmdLine:
    - /docker-entry-point
    Name: entrypoint
    PrependShell: false
  From:
    Image: debian
  Name: ""
  Platform: ""
  SourceCode: FROM debian
