MetaArgs: null
Stages:
- BaseName: node:10-alpine
  Commands:
  - Labels:
    - Key: VERSION
      Value: '"1.1"'
    Name: label
  - Name: expose
    Ports:
    - "8080"
  - CmdLine:
    - apk --no-cache add youtube-dl ffmpeg tini ca-certificates
    Name: run
    PrependShell: true
  - Env:
    - Key: NODE_ENV
      Value: production
    Name: env
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - package.json
    - package-lock.json
    - /app/
  - CmdLine:
    - cd /app && npm i
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - dist/
    - /app/dist/
  - CmdLine:
    - /sbin/tini
    - node
    - /app/dist/index.js
    Name: entrypoint
    PrependShell: false
  From:
    Image: node:10-alpine
  Name: ""
  Platform: ""
  SourceCode: FROM node:10-alpine
