MetaArgs: null
Stages:
- BaseName: debian:jessie
  Commands:
  - Maintainer: Ivan Dyachkov <ivan@dyachkov.org>
    Name: maintainer
  - Env:
    - Key: OTP_VERSION
      Value: "18.0"
    Name: env
  - Env:
    - Key: DEBIAN_FRONTEND
      Value: noninteractive
    Name: env
  - CmdLine:
    - apt-get update -qq     && apt-get install -y        build-essential        git        wget        curl        ca-certificates        man
    Name: run
    PrependShell: true
  - CmdLine:
    - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb &&     dpkg
      -i erlang-solutions_1.0_all.deb &&     rm erlang-solutions_1.0_all.deb
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get update -qq && apt-get install -y erlang=1:${OTP_VERSION} erlang-base
    Name: run
    PrependShell: true
  From:
    Image: debian:jessie
  Name: ""
  Platform: ""
  SourceCode: FROM debian:jessie
