MetaArgs: null
Stages:
- BaseName: ubuntu:latest
  Commands:
  - Maintainer: 'Scott Franke version: 0.1'
    Name: maintainer
  - CmdLine:
    - apt-get update
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get upgrade -y
    Name: run
    PrependShell: true
  - CmdLine:
    - apt-get install -y transmission-daemon
    Name: run
    PrependShell: true
  - CmdLine:
    - mkdir -p /root/.config/transmission-daemon
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - settings.json
    - /root/.config/transmission-daemon/settings.json
  - CmdLine:
    - /bin/bash
    Name: cmd
    PrependShell: false
  From:
    Image: ubuntu:latest
  Name: ""
  Platform: ""
  SourceCode: FROM ubuntu:latest
