MetaArgs: null
Stages:
- BaseName: fedora
  Commands:
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - ./docker-gc
    - /docker-gc
  - Name: volume
    Volumes:
    - /var/lib/docker-gc
  - CmdLine:
    - /docker-gc
    Name: cmd
    PrependShell: false
  From:
    Image: fedora
  Name: ""
  Platform: ""
  SourceCode: FROM fedora
