MetaArgs: null
Stages:
- BaseName: rails:4.2.2
  Commands:
  - Maintainer: We ahead <docker@weahead.se>
    Name: maintainer
  - Env:
    - Key: RAILS_ENV
      Value: production
    - Key: NOKOGIRI_USE_SYSTEM_LIBRARIES
      Value: "1"
    - Key: S6_VERSION
      Value: 1.18.1.3
    - Key: S6_BEHAVIOUR_IF_STAGE2_FAILS
      Value: "2"
    Name: env
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-amd64.tar.gz
    - /tmp/
  - Chown: ""
    Name: add
    SourcesAndDest:
    - https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-amd64.tar.gz.sig
    - /tmp/
  - CmdLine:
    - gpg --keyserver pgp.mit.edu --recv-key 0x337EE704693C17EF &&     gpg --verify
      /tmp/s6-overlay-amd64.tar.gz.sig /tmp/s6-overlay-amd64.tar.gz &&     tar -xzf
      /tmp/s6-overlay-amd64.tar.gz -C /
    Name: run
    PrependShell: true
  - Name: workdir
    Path: /portus
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Portus/Gemfile*
    - ./
  - CmdLine:
    - bundle config build.nokogiri --use-system-libraries &&     bundle install --retry=3
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - Portus
    - .
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - root
    - /
  - Name: expose
    Ports:
    - "3000"
  - CmdLine:
    - /init
    Name: entrypoint
    PrependShell: false
  From:
    Image: rails:4.2.2
  Name: ""
  Platform: ""
  SourceCode: FROM rails:4.2.2
