MetaArgs: null
Stages:
- BaseName: sbdev/laravel:laravel-1.7
  Commands:
  - CmdLine:
    - apt-get install -y wget
    Name: run
    PrependShell: true
  - CmdLine:
    - "wget -c \"http://xdebug.org/files/xdebug-2.7.0.tgz\" \t&& tar -xf xdebug-2.7.0.tgz
      \t&& rm xdebug-2.7.0.tgz \t&& (         cd xdebug-2.7.0         && phpize         &&
      ./configure --enable-xdebug         && make         && make install     )   &&
      rm -r xdebug-2.7.0   && docker-php-ext-enable xdebug"
    Name: run
    PrependShell: true
  From:
    Image: sbdev/laravel:laravel-1.7
  Name: ""
  Platform: ""
  SourceCode: FROM sbdev/laravel:laravel-1.7
