MetaArgs: null
Stages:
- BaseName: php:7.0-apache
  Commands:
  - Key: GIT_REPO_URL
    Name: arg
    Value: null
  - CmdLine:
    - apt-get update && apt-get install -y git
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - gitclone
    - /usr/local/bin/
  - CmdLine:
    - chmod a+x /usr/local/bin/gitclone
    Name: run
    PrependShell: true
  - Name: expose
    Ports:
    - "80"
  - CmdLine:
    - gitclone
    - apache2-foreground
    Name: cmd
    PrependShell: false
  From:
    Image: php:7.0-apache
  Name: ""
  Platform: ""
  SourceCode: from php:7.0-apache
