MetaArgs: null
Stages:
- BaseName: redis:5
  Commands:
  - Env:
    - Key: DOCKERIZE_VERSION
      Value: v0.6.1
    Name: env
  - CmdLine:
    - apt-get update && apt-get install -y wget     && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz     &&
      tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz     &&
      rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz     && rm -rf /var/lib/apt/lists/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - bin/run.sh
    - /usr/local/bin/run.sh
  - CmdLine:
    - chmod +x /usr/local/bin/run.sh
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - config/
    - /redis/config
  - Env:
    - Key: REDIS_PORT
      Value: "6379"
    Name: env
  - Env:
    - Key: MASTER_NAME
      Value: mymaster
    Name: env
  - Env:
    - Key: QUORUM
      Value: "2"
    Name: env
  - Env:
    - Key: SENTINEL_PORT
      Value: "26379"
    Name: env
  - Env:
    - Key: MASTER_PORT
      Value: "6379"
    Name: env
  - CmdLine:
    - /usr/local/bin/run.sh
    Name: cmd
    PrependShell: false
  From:
    Image: redis:5
  Name: ""
  Platform: ""
  SourceCode: FROM redis:5
