MetaArgs: null
Stages:
- BaseName: gcr.io/google-containers/kube-apiserver-amd64:v1.12.1
  Commands:
  - Maintainer: lwj
    Name: maintainer
  From:
    Image: gcr.io/google-containers/kube-apiserver-amd64:v1.12.1
  Name: ""
  Platform: ""
  SourceCode: FROM gcr.io/google-containers/kube-apiserver-amd64:v1.12.1
