MetaArgs: null
Stages:
- BaseName: alpine:3.3
  Commands:
  - Maintainer: Chris Grgich-Tran <pootie@grgichtran.com>
    Name: maintainer
  - Name: expose
    Ports:
    - "3306"
  - Env:
    - Key: TERM
      Value: dumb
    Name: env
  - Name: workdir
    Path: /app
  - Name: volume
    Volumes:
    - /app
  - CmdLine:
    - apk add --update bash mysql mysql-client && rm -f /var/cache/apk/*
    Name: run
    PrependShell: true
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - my.cnf
    - /etc/mysql/my.cnf
  - Chown: ""
    From: ""
    Name: copy
    SourcesAndDest:
    - startup.sh
    - /startup.sh
  - CmdLine:
    - /startup.sh
    Name: cmd
    PrependShell: false
  From:
    Image: alpine:3.3
  Name: ""
  Platform: ""
  SourceCode: FROM alpine:3.3
